### PR TITLE
Fix ghost module remote menu for 2.8

### LINKED ISSUE #2559: Ghost Menu  cannot be operated.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Unfortunately, the ghost menu can no longer be operated with the scroll wheel since 2.8 RC1, but everything still worked in 2.7.

### Expected Behavior

working ghost menu

### Version

2.8 RC3

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

On the Zorro with 2.8 RC3 it runs without problems.

### PR DESCRIPTION
**Pull request by 3djc**
This is a quick fix for Ghost module remote menu . Tested only oon TX16S, unsure of behavior on radio without rotary encoder like nv14 (but also unsure how it works today on those)

This fixes #2559

### CODE REVIEW

**Comment by pfeerick** [comment]
On the NV14/EL18 these snippets are responsible for turning on/off the "use trims as keys" emulation... which is also automatically trigged if `isLuaStandaloneRunning()` is true. With `main` standalone Lua is still showing EVT_VIRTUAL_NEXT/EVT_VIRTUAL_PREV and ELRS Lua is working. But I can't quite see how the message is getting handled now... 😢 So it looks like this will only fix it for those with rotary encoders for now... will look at this again the morning.

https://github.com/EdgeTX/edgetx/blob/d7598c8ed8586faef5b05a57e79d05e64c4babe9/radio/src/gui/colorlcd/radio_ghost_module_config.cpp#L96-L98

https://github.com/EdgeTX/edgetx/blob/d7598c8ed8586faef5b05a57e79d05e64c4babe9/radio/src/gui/colorlcd/radio_ghost_module_config.cpp#L154-L156

**Comment by raphaelcoeffic** [comment]
@pfeerick I believe this is because the LVGL events are sent directly instead of being relayed to `onEvent()`. Check the `standalone_lua.cpp`, that should show you the difference.

**Comment by TheIsotopes** [comment]
@pfeerick what is missing to merge this?
I tested it on my TX16S and everything seems to be fine.

**Comment by pfeerick** [comment]
Please read the immediately above comments, the answer is there ;) I've just not had time to dig deeper with the NV14/EL18 as I had already gone down that rabbit hole and not been able to get the events to respond. Merging this issue PR only resolves this for rotary encoder radios. However that may need to do for now, so this may get merged in a few days regardless.

**Comment by pfeerick** [comment]
Ok, NV14 is just annoying me now. This can go in as it is, as it is, as it at least improves the TX16 / rotary encoder radios. 

That means following issues need to be followed up for 2.9:
- ~~need for double enter press at times (the first press is being ignored - although that)~~ fixed already, after this PR was made
- NV14/EL18 trims as buttons support
- doing away with the ghost menu entirely - it really should be Lua based

**Pull request merged**
