### PR TITLE
fix(tts): DE - value 1 representation ("eins", "eine", "ein") 

### PR DESCRIPTION
**Pull request by mha1**
handles DE language quirk for values of exactly 1 and 1.0 properly for all different scenarios:
- units: handles no unit, just singular unit (e.g. Volt), plural units (e.g. Sekunde, Sekunden) also for the odd DE exception to the rule (e.g. rad - "ein Radiant", not "eine" Radiant compared to "eine Stunde")
- fractions: handling special case 1.0

Note: there are also some minor issues with the DE sound pack which need fixing for km, dbm, rpm and mph to work properly. Code is prepared to handle those units and will work correctly as soon as the DE sound pack is updated. 
- km0.wav ("Kilometer") and dbm0.wav ("DBM") are missing
- rpm requires rpm0.wav ("Umdrehung pro Minute") and rpm1.wav ("Umdrehungen pro Minute")
- mph requires mph0.wav ("Meile pro Stunde") and mph1.wav ("Meilen pro Stunde")

@pfeerick: I found more quirks and also DE sound pack issues worth fixing and have done extensive testing on this update, especially going through all units, critical cases (e.g. 0, 0,9, 1.0, 1,1), negative values, small and big numbers. I'd very much appreciate this also going into 2.9.2 knowing km, dbm, rpm and mph will not work properly (unit messages omitted) until the DE sound pack update

Sorry for the inconvenience!

### CODE REVIEW

**Comment by pfeerick** [comment]
Like the cross-referenced commit? note: I didn't use the phrase you gave for `mph1.wav` 🤣

**Comment by mha1** [comment]
stupid copy/paste

dbm0.wav - ok
km0.wav -ok
mph0.wav - ok
mph1.wav - ok
rpm0.wav - ok
rpm1.wav - ok

km, dbm, rpm, mph using your new .wav's tested ok with this PR. Thank you very much!

**Comment by mha1** [comment]
image

edit: mph not ok. copy/paste was worse than assumed. It's miles per hours not minutes

please change to
mph0.wav ("Meile pro Stunde") and mph1.wav ("Meilen pro Stunde")

**Comment by pfeerick** [comment]
Mea culpa... even worse than that... I even typed it in English for the source text, and the penny didn't drop 🤪

**Comment by mha1** [comment]
all good now

**Pull request merged**
