### PR TITLE
Issue #1285

### PR DESCRIPTION
**Pull request by jfrickmann**
- `getfieldInfo` can now also take a source index as argument. Plus it was modified to also handle "telem1+" etc.
- New functions `getSourceIndex(sourceName)` and `getSourceName(sourceIndex)` were added, which use the names shown on the screen instead of the special names table used by `getFieldInfo` and `getValue`.
- Indices are the same for all of the functions, so `getValue(sourceIndex)` also works with indices from `getSourceIndex`.
- New iterator functions `sources([first[, last]])` and `switches([first[, last]])` for getting ranges of sources and switches with a `for` loop.
- `getPhysicalSwitches` was removed, as I consider the iterator function to be a better solution.

### CODE REVIEW

**Comment by jfrickmann** [comment]
@wimalopaan - I have removed `getPhysicalSwitches` and replaced it with an iterator function.

**Comment by jfrickmann** [comment]
@pfeerick, it looks like the tests failed due to an issue with Docker login. Does it get fixed automatically, or do I need to do something to restart the test builds?

**Comment by pfeerick** [comment]
Github actions have been increasingly intermittent/unreliable [most of the day](https://github.community/t/read-timeouts-and-errors-from-github-urls/219615/5)... we just have to wait for github realise and fix what's broken... then retrigger any builds that failed in the meantime

**Comment by wimalopaan** [comment]
> @wimalopaan - I have removed `getPhysicalSwitches` and replaced it with an iterator function.

Ok, thank you for the info! I'll have to chance some scripts then, but this will be no big effort.
Actual I have sever problems with some very simple scripts. I have to tackle that down, produce a new isse with a minimum-example. But I think that are some issues at once ... unfortunately I can't the merge that triggered this mess. It's around the time that LUA_MIXER config var was introduced (but I doubt that that is the reason)

**Comment by pfeerick** [comment]
If you and wimalopaan can verify this is stable, perhaps we can include this in 2.6 as well, and basically forget getPhysicalSwitches ever existed? :grin:

**Comment by wimalopaan** [comment]
It works for me, but I haven't done very extreme testing now.
But it should be ok to include anyway.

**Comment by jfrickmann** [comment]
As far as I can tell, it works. The most tricky part was the modification to `getFieldInfo`, but generally, it is all very straightforward. So I think that you can go ahead and merge it into 2.6.
@offer-shmuely , have you done any testing?

**Comment by offer-shmuely** [comment]
is there a place to download the binary of the companion with this commit?
I do not have a way to compile my own yet.

**Comment by gagarinlg** [comment]
> is there a place to download the binary of the companion with this commit? I do not have a way to compile my own yet.

https://github.com/EdgeTX/edgetx/suites/4790148879/artifacts/133996807

**Review by pfeerick — APPROVED** [review]
I would like to merge this in tonight, so it can be part of 2.6.0-RC2, so if there are no objections it'll likely be merged around 23:00 UTC. Nice to see the new switches iterator in operation in the libGUI update ;) If the version references still say 2.7 at time of merge I'll fix that then.

**Comment by jfrickmann** [comment]
Awsome! I think I added 2.7 in the doc because I guessed that it would not make it in 2.6. Once everything is merged in, I also have some catching up to do with the doc. I have a few outstanding edits there, and i am starting to loose the overview of what I did where...

**Pull request merged**
