### PR TITLE
Remove obsolete language defines and translations, single source for telemetry sensor names 

### PR DESCRIPTION
**Pull request by mha1**
This is a work result of the discussion in https://github.com/EdgeTX/edgetx/pull/3082

Summary of changes:
- removal of obsolete translations
- all sensor names in untranslated.h (can be overridden in xx.h by `#undef STR_SENSOR_<name>` followed by new ` #define STR_SENSOR_<name> `
- naming convention for sensor names `STR_SENSOR_<name>` (plus editorial changes to adapt naming convention)

### CODE REVIEW

**Comment by mha1** [comment]
@HThuren I found a few additional obsolete defines and const char declarations. Can you please run the your language test again. Thannk you very much.

@pfeerick I claimed 280 Bytes of saved flash memory for a TX16s build- To verify I built two version of TX16s firmware. One using the commit this branch is based on (d77389d3), the other using the latest commit to this branch. Here's two excerpts of "arm-none-eabi-readelf -a <.elf>". All section sizes are identical apart from the first line (flash memory, virt. address starting at 0x08000000). Check out the difference in MemSiz.

Flash Bytes saved 0x1801bc-0x1800a4 = 0x118 (280 decimal). I hope my considerations are correct.

Program Headers: TX16s Firmware Base Main without branch
```
  Type           Offset   VirtAddr   PhysAddr   FileSiz  MemSiz   Flg Align
  LOAD           0x010000 0x08000000 0x08000000 0x1801bc 0x1801bc RWE 0x10000
  LOAD           0x1a0000 0x20000000 0x081801bc 0x00aec  0x00aec  RW  0x10000
  LOAD           0x000af0 0x20000af0 0x08180ca8 0x00000  0x0b984  RW  0x10000
  LOAD           0x00c474 0x2000c474 0x08180ca8 0x00000  0x049e8  RW  0x10000
  LOAD           0x000000 0x10000000 0x10000000 0x00000  0x0bc9c  RW  0x10000
  LOAD           0x000000 0xd0000000 0xd0000000 0x00000  0x4ff000 RW  0x10000
```
  
Program Headers: TX16s Firmware Base Main plus Branch
```
  Type           Offset   VirtAddr   PhysAddr   FileSiz  MemSiz   Flg Align
  LOAD           0x010000 0x08000000 0x08000000 0x1800a4 0x1800a4 RWE 0x10000
  LOAD           0x1a0000 0x20000000 0x081800a4 0x00aec  0x00aec  RW  0x10000
  LOAD           0x000af0 0x20000af0 0x08180b90 0x00000  0x0b984  RW  0x10000
  LOAD           0x00c474 0x2000c474 0x08180b90 0x00000  0x049e8  RW  0x10000
  LOAD           0x000000 0x10000000 0x10000000 0x00000  0x0bc9c  RW  0x10000
  LOAD           0x000000 0xd0000000 0xd0000000 0x00000  0x4ff000 RW  0x10000
```

**Comment by HThuren** [comment]
Right, I have cloned your branch and started translation, ap. one hour to go :-)

**Comment by mha1** [comment]
Awesome!

**Comment by HThuren** [comment]
All done, not succes with CZ and IT language

**Comment by mha1** [comment]
can you post the error messages please

**Comment by mha1** [comment]
@HThuren Thanks for running the language build. I found the problem and it is not due to changes made here.

@philmoz Commit 475ad1fb changed radio/src/gui/colorlcd/fullscreen_dialog.cpp. This section compiles with errors for CZ, FR, IT languages.
```
#if defined(TRANSLATIONS_FR) || defined(TRANSLATIONS_IT) || defined(TRANSLATIONS_CZ)
      t = STR_WARNING + "\n" + title;
#else
      t = title + "\n" + STR_WARNING;
#endif

error: expression must have integral or unscoped enum typeC/C++(2140)
```

C++ doesn't like a const char [] in thie std::string concatenation `t = STR_WARNING + "\n" + title;`

The fix is to convert the const char [] to a std::string. With your permission I'll change this section of code. This will build ok:

```
    std::string t;
    std::string warning(STR_WARNING);

    if (type == WARNING_TYPE_ALERT) {
#if defined(TRANSLATIONS_FR) || defined(TRANSLATIONS_IT) || defined(TRANSLATIONS_CZ)
      t = warning + "\n" + title;
#else
      t = title + "\n" + warning;
#endif
```

**Comment by HThuren** [comment]
> @HThuren Would be great if you find time to run the language builds again

Hi @mha1 , I have started the compilation now, a least one hour to go

**Comment by HThuren** [comment]
Hi @mha1 , all good LANG in (DA EN DE CZ SE IT CN TW PL JP) all compiled

**Comment by mha1** [comment]
Great, thank you very much

**Comment by mha1** [comment]
@pfeerick can we go ahead with this? I think the dam has broken already. #3148 (se.h) got merged two days ago. The changes made to se.h were based on changes made in this PR. Amongst those is the single source and naming change for telemetry sensors. Building main in SE configuration will fail right now because some complementary changes made in this PR are missing (eg untranslated.h). I have rebased this PR to current main. Merging this will sort out the current indefinite state of se.h too.

**Comment by pfeerick** [comment]
Ah, damnit... yes, this was supposed to be merged first. Yup, and thanks for the rebase :)

**Comment by mha1** [comment]
@pfeerick No problemo, you got a lot on your plate. I really appreciate your expertise and you putting in lots of hours.

**Pull request merged**
