### PR TITLE
fix: TLite V2 is using another MCU

### PR DESCRIPTION
**Pull request by 3djc**
Handles the two MCU versions found in TLite

### CODE REVIEW

**Comment by gagarinlg** [comment]
So the firmware runs without problems on the F20x and F40x?

**Comment by raphaelcoeffic** [comment]
@gagarinlg Cortex M4F is binary compatible to Cortex M3 ;-) That being said, it will not make use of the FPU on board.

**Comment by raphaelcoeffic** [comment]
> I'm trying to get to the bottom of this with Jumper

The frequencies should probably be checked. For example: is it possible to make the F4 run at the same speed as the F2? (assuming the quartz is identical, otherwise you'll need a different freq init code)

**Comment by 3djc** [comment]
Well in the past we did not check and nobody reported specific problem with those I think

**Comment by pfeerick** [comment]
Prior to this being specifically checked at startup around the time we added the tlitef4 firmware, my TLite V2 ELRS (which until now I didn't realise had a 407 MCU, hence needs this workaround now), seemed to work just fine.

**Comment by 3djc** [comment]
Jumper confirmed some TLite do have a CKS F4 in "F2 compatibilty mode". So I think the PR as such is ok.

**Pull request merged**
