### PR TITLE
safeguard RTC backup memory

### PR DESCRIPTION
**Pull request by mha1**
This PR introduces a simple checksum for the RTC backup memory preventing boot hangs due to corrupt RTC backup memory.

Changes:
-  setter and getter for checksum protected RTC backup register access

### CODE REVIEW

**Comment by philmoz** [comment]
The code in this looks wrong to me, and may explain the crash reports in 2.9 nightly. 
Not sure how this could have passed any testing.

Given
#define RTCBKP0R 0    // RTC backup register 0
#define RTCBKP1R 1    // RTC backup register 1

Then
((uint32_t *)RTC)[RTCBKP0R]  is equivalent to RTC->TR, not RTC->BKP0R

and
((uint32_t *)RTC)[RTCBKP1R]  is equivalent to RTC->DR, not RTC->BKP1R

IMO the getter/setter coding in this PR is a very unsafe way of handling this and prone to future issues.

**Comment by rotorman** [comment]
Would you have a suggestion of how to improve the getter/setter?

**Comment by philmoz** [comment]
The OO solution would be to use functions within the RTC_Typedef structure; but since it's a third party lib that's probably not practical.

I would try passing the RTC variables as pointers to the functions.

rtc.h:
```
uint32_t getRTCBKPR(volatile uint32_t* RTCBKPRegister);
void setRTCBKPR(volatile uint32_t* RTCBKPRegister, uint32_t value);
```

rtc_driver.cpp:
```
uint32_t getRTCBKPR(volatile uint32_t* RTCBKPRegister) {
  uint32_t prim = __get_PRIMASK();
  
  __disable_irq();
  
  if(RTC->BKP19R != RTCCHKSUM()) {
    RTC->BKP0R = 0;
    RTC->BKP1R = 0;
    RTC->BKP19R = RTCCHKSUM();
  }

  uint32_t value = *RTCBKPRegister;

  if(!prim) 
    __enable_irq();

  return value;
}

void setRTCBKPR(volatile uint32_t* RTCBKPRegister, uint32_t value) {
  uint32_t prim = __get_PRIMASK();
  
  __disable_irq();

  *RTCBKPRegister = value;

  RTC->BKP19R = RTCCHKSUM();

  if(!prim) 
    __enable_irq();
}
```

Usage:
```
getRTCBKPR(&RTC->BKP0R)
setRTCBKPR(&RTC->BKP0R, value)
```

If this does not work for variables defined as volatile then the only fallback I can think of is to test the value of the RTCBKPRegister value (0 or 1) in each function and get/set the correct RTC property accordingly.

**Comment by mha1** [comment]
I am very sorry and even more embarrassed to have f'd this up. It's just a mistake ( (well really a major f'up)) in the RTC backup register address calculation. I intended to use the RTC backup registers base address but was using the RTC base address. So Phil is absolute correct about reading/writing RTC->DR and RTC->TR instead of RTC->BKP0R and RTC->BKP1R.

Fixed this by using the correct base address for the address calculation.

Verified on TX16s with instrumented firmware:
```
0.88s: address rtc struct (RTC is defined as &rtc) 0x40002800
0.88s: base address RTC backup registers (expect offset 0x50) 0x40002850
0.88s: size of a single RTC backup register (expect 4, 32bit) 4
0.88s: address RTC BKP0R (expect offset 0x50) 0x40002850
0.88s: address RTC BKP1R (expect offset 0x54) 0x40002854
```

`((uint32_t *)RTCBKBR_BASE)[RTCBKPRegister] = value;` and ` int32_t value = ((uint32_t *)RTCBKBR_BASE)[RTCBKPRegister];` are now reading/writing the correct registers.

**Comment by mha1** [comment]
Please see #3835

**Pull request merged**
