### PR TITLE
Certain Lua script errors will hang the GUI

### PR DESCRIPTION
**Pull request by jfrickmann**
Fixed a bug where a standalone Lua script w/o a run function, or a script with errors in the init function or other errors during loading will hang the GUI

### CODE REVIEW

**Comment by jfrickmann** [comment]
Crap, I just discovered that there is also a problem on color radios. I am working on it...

**Comment by jfrickmann** [comment]
I am still working on this - I will let you know when I think it is ready for review!

**Comment by jfrickmann** [comment]
I feel that this bug has revealed that I need to do some more rigorous testing. I will therefore run the following tests in the simulators:
# Color (TX16S)
## Standalone script
- [ ] Syntax error
- [ ] Runtime error script body
- [ ] Runtime error init()
- [ ] Runtime error run()
- [ ] Preempt script body
- [ ] Preempt init()
- [ ] Preempt run()
## Telemetry script
- [ ] Syntax error
- [ ] Runtime error script body
- [ ] Runtime error init()
- [ ] Runtime error run()
- [ ] Runtime error background()
- [ ] Preempt script body
- [ ] Preempt init()
- [ ] Preempt run()
- [ ] Preempt background()
# B&W (TX12)
## Standalone script
- [ ] Syntax error
- [ ] Runtime error script body
- [ ] Runtime error init()
- [ ] Runtime error run()
- [ ] Preempt script body
- [ ] Preempt init()
- [ ] Preempt run()
## Telemetry script
- [ ] Syntax error
- [ ] Runtime error script body
- [ ] Runtime error init()
- [ ] Runtime error run()
- [ ] Runtime error background()
- [ ] Preempt script body
- [ ] Preempt init()
- [ ] Preempt run()
- [ ] Preempt background()

**Comment by pfeerick** [comment]
Ok, will review with intent for it to be in next nightly.

**Comment by jfrickmann** [comment]
Yes, I agree! As for the error messages, the way that displayLuaError() is implemented, it will only show an error if Lua returns an error string. Therefore, often the generic "Syntax Error". We would need a major rework of the error handling system in Lua to get more accurate error reports.
On the color radios, I simply added a test so that if Lua fails during load, then it does not open the StandaloneLuaWindow, to avoid it freezing. There may be a smarter way to do this, but again, it would take some work and careful design.
As long as people run in the simulator, they get meaningful errors in the logs.

**Comment by pfeerick** [comment]
Right, this will do for now then, as less crashy radio is always a good thing ;)

**Pull request merged**
