### PR TITLE
feat(mpm): remove FrSky special treatment madness

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This PR removes the protocol/sub-protocol mapping that was done before for FrSky protocols and uses now the exact same list of protocols as defined/transmitted by the MPM.

The FrSky protocols are now listed just as specified by the MPM documentation:
- `FrSkyD`: `D8`
- `FrSkyV`: `V8`
- `FrSkyX`: `D16 v1` and pals
- `FrSkyX2`: `D16 v2` and pals

I also took the chance to add the `Kyosho2` protocol (`KT-17`) to the list of statically listed protos (not required but desirable).

### CODE REVIEW

**Comment by 3djc** [comment]
Tested ok 👍

**Comment by elecpower** [comment]
Crashes libsim for TX16S when sim starts if internal protocol protocol set to MULTI in Companion or starting with OFF and changing to MULTI in SYS hardware.

25.90s: enablePulsesInternalModule(): trigger scan
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

**Comment by elecpower** [comment]
Still to test two-way yaml read/write as there is even more 'special treatment' on the Companion side

**Comment by 3djc** [comment]
Isn't the yaml storage currently storing raw mpm values ? So if a user was to read/write data from a radio with those changes in, it would work ok, no ? Asking because I try to understand if radio can be shipped with this changes in, before Companion changes can be implemented

**Comment by elecpower** [comment]
@3djc module data is one of the worse cases of Companion NOT reading and writing raw values. This applies to bin and yml file formats. So any changes require serious regression testing as a minimum.

I started a refactor to simplify months ago but it is so large and I keep getting drawn away on other features and bugs so it keeps getting put off.

**Comment by elecpower** [comment]
@3djc when I see changes to yaml code and reference lists I get nervous especially around protocols. Also descriptions should wherever possible to be kept in sync between radios and Companion to minimise confusion for pilots. Leaving these things to later means they rarely get done and the two drift apart. In the end not my call.
Either way the libsim crash must be fixed before merging.

**Comment by 3djc** [comment]
Don't get me wrong, yes a companion change is desirable to maintain list alignment, and yes @raphaelcoeffic needs to fix this crash bug, but despite that, I'm trying to assess if radio can be sold with a firmware including this change. At this point, I'm thinking that yes, given that a user receiving such a radio can use 2.8.0 companion without issue (but yes, with the discomfort of having a discrepancy between how frsky protocols are grouped in cpn vs radio, but ultimately, if you select say D8 on radio (FrSkyD/D8), it matches on cpn 2.8.0, just displayed as FrSkyX/D8 since the yaml is the same)

**Comment by raphaelcoeffic** [comment]
> Isn't the yaml storage currently storing raw mpm values

We have been storing the real MPM values since YAML. This was in preparation of exactly this change. So I believe that, while Companion will still display the old way, the read/write routines should be ok.

**Comment by 3djc** [comment]
I fixed the simu/libsimu crash, @raphaelcoeffic is going to do the rebase.

**Comment by pfeerick** [comment]
Fine with me... if the difference for Companion is effectively cosmetic I don't see that being a major issue.

**Comment by elecpower** [comment]
Tested a few combinations and appears not to have broken Companion and libsim, with some interpretation, aligns

**Comment by pfeerick** [comment]
LGTM on TX16... some D, V and X1 and X2 models "converted" over cleanly, menu options seem to be working fine, and companion read and write without changing settings  - just the expected variance in protocol/subprotocol combos vs radio.

**Pull request merged**
