### PR TITLE
feat(color): move ADC Filter and Center Beep settings to 'Other' page

### PR DESCRIPTION
**Pull request by philmoz**
The 'Center Beep' setting does not really belong in Pre-start Checks.

This PR moves Center Beep and ADC filter into a new model setup page (to avoid cluttering the main setup page).

screenshot_tx16s_24-03-14_19-55-52
screenshot_tx16s_24-03-14_19-55-57
screenshot_tx16s_24-03-14_19-56-03

screenshot_el18_24-03-15_09-29-15
screenshot_el18_24-03-15_09-29-23

### CODE REVIEW

**Comment by froqstar** [comment]
Now that we have such a lot of space, can we make the label a bit more descriptive, like "beep when centered"?

**Comment by pfeerick** [comment]
Sounds fine to me. I'll add this to the list of PRs to ping translators for next week... I think there are like three PRs that will need translation work done... 

Even though this is a relatively minor change, I would like to hold it over to 2.11 so  documentation doesn't need to be updated at this late state.

**Comment by pfeerick** [comment]
It has been proposed that "Center Beep" be changed to something more descriptive such as "Beep when Centered". Unless you have any other suggestions, can we get some translations for this please 😃 

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @offer-shmuely / @adir-kro HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU 

Unless it is made longer, only two strings should be needed... "Beep when centred"  still just fits in for bw212 UI. 
image

```cpp
#define TR_BEEPCTR                     TR("Ctr Beep", "Beep when centered")
```

**Comment by zyren** [comment]
CN
```c
#define TR_FILTER                      "滤波器"
#define TR_JITTER_FILTER           "ADC滤波器"

#define TR_BEEPCTR                   TR("中点提示音", "中点蜂鸣提示音")
```
**************************************************
TW
```c
#define TR_FILTER                      "濾波器"
#define TR_JITTER_FILTER           "ADC濾波器"

#define TR_BEEPCTR                   TR("中点提示音", "中点蜂鸣提示音")
```

**Comment by robustini** [comment]
IT
#define TR_BEEPCTR                     TR("Beep Ctr", "Beep quando centrato")

**Comment by froqstar** [comment]
DE

`#define TR_BEEPCTR                     TR("MittePieps", "Pieps in Mittelstellung")`

**Comment by Pat6874** [comment]
FR

#define TR_BEEPCTR TR("Ctr Beep", "Bip quand centré")

Le 18 mars 2024, 01:47, à 01:47, Peter Feerick ***@***.***> a écrit:

**Comment by Eldenroot** [comment]
#define TR_BEEPCTR                     TR("Střed. tón", "Pípnutí při středu")

**Comment by HThuren** [comment]
DA

TR("Bip ctr pos", "Bip ved center position")

**Comment by offer-shmuely** [comment]
HE

#define TR_BEEPCTR                     TR("Ctr Beep", "ציפצוף במרכז")

**Comment by kobakirill** [comment]
RU
#define TR_BEEPCTR                     TR("Звук на центре", "Звук на центре")

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_BEEPCTR TR("Dźwięk środ.", "Dźwięk środ. położenia")
```

**Comment by philmoz** [comment]
> RU #define TR_BEEPCTR TR("Звук на центре", "Звук на центре")

The first string is too long for 128x64 B&W radios.

**Comment by ulfhedlund** [comment]
SE
#define TR_BEEPCTR                     TR("Cntr. pip", "Pip när centrerad")

**Comment by adir-kro** [comment]
Remove me from the mails.. I don't like it
 Thanks
***@***.***

Discord only please

בתאריך יום ג׳, 19 במרץ 2024, 07:58, מאת Janek ***@***.***>:

**Comment by kobakirill** [comment]
> > RU #define TR_BEEPCTR TR("Звук на центре", "Звук на центре")
> 
> The first string is too long for 128x64 B&W radios.

Corrected

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_BEEPCTR                     TR("Ctr Beep", "中央値でビープ")

**Comment by zandorsp** [comment]
#define TR_BEEPCTR                     TR("Bip Cntr", "Bip no centro")

**Comment by zandorsp** [comment]
Please, if still possible update the translation to:

PT
#define TR_BEEPCTR TR("Bip Cntr", "Bipe quando centralizado")

**Pull request merged**
