### PR TITLE
Labels bugfix1

### PR DESCRIPTION
**Pull request by dlktdr**
**Companion Bug Fixes for #1374**
- Labels not loading previous settings if zip didn't contain MODELS/labels.yml
- Don't allow rename to a label that already exists
- Model Paste not updating labels list
- Add a favorites label on bin import
- If making a label with a partial name of another would check incorrect items
- Fix crash if delete label clicked with no label selected
- On new Settings, add a favorites label
- Always show the checkboxes with no selected model
- Not marking window as modified if labels changed, added or removed
- Show a warning if user tries to rename to a existing label

**Firmware Bug Fixes**
- Update the title on new model
- Clear new&rename label string dialogs.
- Handle labels.yml properly when no labels in map. (Caused it to add all models as a label when all labels removed)
- Libsimulator not loading models
- Properly set sort button state
- Make new label a button instead of in long press menu

**Both**
- Support commas in labels

### CODE REVIEW

**Comment by elecpower** [comment]
Companion:
- adding a label to a model does not flag the file as changed and therefore on closing does not trigger do you want to save
- when no models in file eg when a new file is created the labels have no check boxes, IMO just an unusual ui handling
- editing label name I would prefer a validator to stop user entering commas rather than swapping with underscore
- when duplicate label names should advise the user and not just undo as the duplicate could be outside the viewable window

**Comment by pfeerick** [comment]
I haven't tried with this PR yet, on a nightly atm, but I noticed when creating a new model, the text up the top still has the old name, although the newly created model is hilighted

**Comment by dlktdr** [comment]
> Companion:
> 
> * adding a label to a model does not flag the file as changed and therefore on closing does not trigger do you want to save

fixed, will push in a while
> * when no models in file eg when a new file is created the labels have no check boxes, IMO just an unusual ui handling

fixed, will push in a while
> * editing label name I would prefer a validator to stop user entering commas rather than swapping with underscore

I will do this in a separate PR. It should work as is and we can get this bug fix in. This was done so it's same as radio. I'm not sure how to do prevent a character from being entered here. What I will do instead is use an escape sequence so there is no limitation.

> * when duplicate label names should advise the user and not just undo as the duplicate could be outside the viewable window

@elecpower how should the user be informed, a QMessagebox::warning pop-up message okay?

> * Simulate radio with multiple models only shows one model on long press of MDL key although temp directory holds all model yml files

I see, will figure this out. Also won't run at all if modified.

Found another bug too on radio if you remove all the labels, somehow adds all the models as labels.. 

@pfeerick Ok that one should be easy one.

**Comment by elecpower** [comment]
> I will do this in a separate PR. It should work as is and we can get this bug fix in. This was done so it's same as radio. I'm not sure how to do prevent a character from being entered there. What I will do instead is use an escape sequence on both radio and companion so there is no limitation. "\\" = '\' & "\c" = ',' sound okay?

Okay

> - when duplicate label names should advise the user and not just undo as the duplicate could be outside the viewable window
@elecpower how should the user be informed, a QMessagebox::warning pop-up message okay?

Yes

**Comment by elecpower** [comment]
> Simulate radio with multiple models only shows one model on long press of MDL key although temp directory holds all model yml files
>> I see, will figure this out. Also won't run at all if modified.

I haven't checked the code but could this be to do with file datetime stamps???

**Comment by dlktdr** [comment]
Here is the rename warning.
image 

**Firmware**
We okay with the new label button down here, with the labels section? 
Should the long press one be removed from the labels menu?
image

**Comment by dlktdr** [comment]
> I haven't checked the code but could this be to do with file datetime stamps???

Really shouldn't be, the firmware code should have re-scanned them all anyway since labels only contains the labels and no model info.

Compiling with the simulator locally here now will find out shortly 😅

**Comment by pfeerick** [comment]
> **Firmware** We okay with the new label button down here, with the labels section? Should the long press one be removed from the labels menu?

That looks good. It's probably better there than in the header, as it keeps the label stuff together, and should fit better on the NV14 as well? And yeah, it's probably a good idea (to remove it from the long press menu, one less entry to clutter the menu).

**Comment by dlktdr** [comment]
I think is good to go for a review and we can bring on more issues. Move labels was not touched so to hopefully not make a merge conflict with #2269.

Here is the current layout of NV14 + TX16S. I moved the labels to the bottom, was a little easier to make the "New Label" button end up in a logical place.

image

**Comment by dlktdr** [comment]
> > *
> 
> I see, will figure this out. **Also won't run at all if modified.**

@elecpower I found out why after I couldn't open simulator some times. It happens if I make a new model and abort the wizard. In that case it doesn't call fixModelFilenames. With the filename blank causes the issue. If you finish the wizard it works as expected.

https://github.com/EdgeTX/edgetx/blob/c1e8a54e59fd753696d0e8553b14ed16f38daa52/companion/src/mdichild.cpp#L1255-L1261

What is the proper action here, just move this 1259-1261 out of the ```if``` so that it's called no matter what since the model was actually created.

Or did I accidentally remove it somewhere else, since I didn't notice this before.

**Comment by elecpower** [comment]
> @elecpower I found out why after I couldn't open simulator some times. It happens if I make a new model and abort the wizard. In that case it doesn't call fixModelFilenames. With the filename blank causes the issue. If you finish the wizard it works as expected.

@dlktdr brilliant find. I have been encountering the same issue for a while too but since it wasn't consistent and the stack of other things on my plate I haven't had time to investigate the sequence. I'll dig around and get back to you. We can do this as a separate PR rather than hold up this one if you like.

**Comment by dlktdr** [comment]
> @dlktdr brilliant find. I have been encountering the same issue for a while too but since it wasn't consistent and the stack of other things on my plate I haven't had time to investigate the sequence. I'll dig around and get back to you. We can do this as a separate PR rather than hold up this one if you like.

O good... after this many changes I just assumed was something I did 😉 

Yes a separate PR will probably be good. I'm sure there will be more issues to add yet can do in another.

**Comment by pfeerick** [comment]
This whacks enough bugs for one PR IMO ;) I'll run and merge tonight if nothing jumps out.

**Comment by elecpower** [comment]
Some quick tests shows the issue goes beyond the wizard so definitely a separate PR. I'll raise an Issue for all to see and take on the PR as looks like I contributed to making it worse.....aargh  :-(

**Comment by pfeerick** [comment]
@elecpower There are enough other things for you to do ... no need to add more bugs to work on... (then again, it means I'm not the only one! 😁 😇 ). 

btw, @dlktdr, thanks for fixing the "lets no load *any* models at all on B&W radios" bug ... tried to load a transmitter to throw a model on it, and instead used 2.7.1 companion (since I have side-by-side installs for the major versions) to alter model settings on a nightly B&W radio (not recommended practice, but can be done in a pinch).

**Comment by dlktdr** [comment]
> btw, @dlktdr, thanks for fixing the "lets no load _any_ models at all on B&W radios" bug ... tried to load a transmitter to throw a model on it, and instead used 2.7.1 companion (since I have side-by-side installs for the major versions) to alter model settings on a nightly B&W radio (not recommended practice, but can be done in a pinch).

?? no problem. I totally ment to do that. 😉

**Review by pfeerick — APPROVED** [review]
Crash test dummy approves ;)

**Comment by pfeerick** [comment]
My wishlist/thoughts take it or leave it are currently
- is there actually any point returning to the model select screen after creating a new model (should have thought of that *before* you made it update the name on creating a new model)?
- is "double tap" to load a new model a bad idea, or a really bad idea? :grin:
- what are Wednesday's lotto numbers?

**Comment by dlktdr** [comment]
> * is there actually any point returning to the model select screen after creating a new model (should have thought of that _before_ you made it update the name on creating a new model)?

😄 - Lol thought of this too.. I can remove that extra bit of code and make it quit instead, I guess that would make more sense to me as well.

> * is "double tap" to load a new model a bad idea, or a really bad idea? 😁

Not sure about this one, will leave it to a vote. I think if it was a double tap there should also be a dialog "Load Model xx?".

> * what are Wednesday's lotto numbers?

If you find them, let me know too 😉 

> btw, I meant to tell you (if you haven't seen it already) - John did a video on this ;) https://www.youtube.com/watch?v=WQshB36fUCc

Nice. He is pretty good at explaining, easy to watch. If he does another before 2.8 release will have to get him to show users how to modify the labels by long pressing on the model and choosing edit label, much quicker than going to model settings.

**Pull request merged**
