### PR TITLE
Fix french and Czech translations for BW radios

### LINKED ISSUE #3526: More bugs with Czech language Radiomaster Zorro 2.8.3
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Maybe bad translation or bad display of Czech characters with diacritics. First character with diacritics on line missing. Pls see attached pictures. Red text is correct.

### Expected Behavior

Right Czech translation, correct displaying characters with diacritics.

### Steps To Reproduce

Scroll through the menu with CZ firmware.

### Version

Other (Please specify below)

### Transmitter

Radiomaster Zorro

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

IMG20230424101254
IMG20230424101337
IMG20230424101350
IMG20230424101426
IMG20230424101503
IMG20230424101544
IMG20230424101638
IMG20230424101652
IMG20230424101727
IMG20230424101744
IMG20230424101853
IMG20230424100928
IMG20230424100946
IMG20230424101042
IMG20230424101111
IMG20230424101122
IMG20230424101136

### PR DESCRIPTION
**Pull request by 3djc**
Accentuated capitals are not supported in BW radio, so subtitute those. Fixed a couple of other issue like asking to touch screen, which has little effect on those (other than requiring cleaning the screen :D). I'm sure there are other left, but most of it should be ok now. Tested ok on 212 and colorlcd too

This also fixes Czech language, or al least all the exemple reported in #3526 (checked all pictures)
This fixes #3526

### CODE REVIEW

**Comment by philmoz** [comment]
Editing the string to change the accented characters to non-accented version will fix the existing B&W translations; but will mean we are going to have to check every translation in the future for missing characters.

It also adversely affects color LCD radios which have all the accented characters in the font.

Wouldn't it be better to add the missing characters to the font itself?

Failing that an extra conversion step in the utf8.cpp file for B&W radios to convert missing characters to valid alternatives would solve the problem without costing very much flash space.

**Comment by gagarinlg** [comment]
Just convert those to lower case automatically.
Adding the characters to the car set would not really help. There are just not enough pixels to display them in a readable manner.

**Comment by philmoz** [comment]
> Adding the characters to the car set would not really help. There are just not enough pixels to display them in a readable manner.

Is this readable:
Screenshot 2023-07-20 at 9 12 40 am

**Comment by 3djc** [comment]
> Failing that an extra conversion step in the utf8.cpp file for B&W radios to convert missing characters to valid alternatives would solve the problem without costing very much flash space.

Thats what I'm planning to do

**Comment by 3djc** [comment]
image

image

**Comment by zandorsp** [comment]
Portuguese makes use of five [diacritics] (ç), [acute accent]  (á, é, í, ó, ú), 
[circumflex accent] (â, ê, ô), 
[tilde] (ã, õ), and 
[grave accent] (à, rarely ò)
I think it need inclusion in utf8.cpp

**Comment by 3djc** [comment]
> Portuguese makes use of five [diacritics] (ç), [acute accent] (á, é, í, ó, ú), [circumflex accent] (â, ê, ô), [tilde] (ã, õ), and [grave accent] (à, rarely ò) I think it need inclusion in utf8.cpp
> 
> My review without accentuation #3796

please open a separate issue if you think things are missing for Portuguese

**Comment by philmoz** [comment]
CZ font update to add 'ň':

utf8.cpp ('ň' can be removed from the substitution array)
```
#elif defined(TRANSLATIONS_CZ)
static wchar_t _utf8_lut[] = {
  L'á', L'č', L'é', L'ě', L'í', L'ó', L'ř',
  L'š', L'ú', L'ů', L'ý', L'Á', L'Í', L'Ř',
  L'Ý', L'ž', L'É', L'ň',
};
```

Font source files (unzip 'CZ sqt5.zip' and replace files in radio/src/fonts/sqt5 folder, 'CZ std.zip' contents goes into radio/src/fonts/std folder):
[CZ sqt5.zip](https://github.com/EdgeTX/edgetx/files/12114751/CZ.sqt5.zip)
[CZ std.zip](https://github.com/EdgeTX/edgetx/files/12114752/CZ.std.zip)

**Comment by 3djc** [comment]
Font and handling added for ň (thanks @philmoz)

**Comment by philmoz** [comment]
I think there is another issue with the CZ translation & font on B&W radios.
The sound related strings have special characters in them that I assume are intended to display a symbol.

They currently look like this:
Screenshot 2023-07-28 at 7 14 10 pm

I am guessing they should look like this:
Screenshot 2023-07-28 at 7 16 01 pm

**Comment by 3djc** [comment]
ok, I'll split into 2 PR, because french is completely unusable currently, so it would be nice to be merged while it takes longer to fix CZ

**Comment by philmoz** [comment]
> ok, I'll split into 2 PR, because french is completely unusable currently, so it would be nice to be merged while it takes longer to fix CZ

Probably ok to keep this one as is. The changes for this new issue are independent and I have another pending PR that I can add them to.

**Comment by 3djc** [comment]
Works for me too, I just would not want to drag this oen foreever, especially because I think it is needed for 2.9 too

**Comment by philmoz** [comment]
I've put the speaker icon fix into #3832

**Comment by pfeerick** [comment]
I'm staying out of the translation stuff for now, so you guys just say when these PRs are ready.

**Comment by 3djc** [comment]
> I'm staying out of the translation stuff for now, so you guys just say when these PRs are ready.

Ready, will be completed for further CZ support but as part of another PR.

needed for 2.9 imho

**Comment by philmoz** [comment]
> I'm staying out of the translation stuff for now, so you guys just say when these PRs are ready.

#3832 isn't really a translation PR. It just fixes some issues that have crept in unnoticed at some point - it should be ok to merge at your convenience.

This one looks ok to me as well.

**Comment by Eldenroot** [comment]
Ď and ď are added too???

**Comment by 3djc** [comment]
no they need font work (like the speaker issue mentionned above)

**Pull request merged**
