### PR TITLE
Model templates and Lua function get/setGlobalVariable bugfix to 2.6

### PR DESCRIPTION
**Pull request by jfrickmann**
I have submitted these to main, but I would also like them included in 2.6.x.

Together with EdgeTX/edgetx-sdcard#48, this will officially release SoarOTX templates for F3K discuss launch gliders!

### CODE REVIEW

**Comment by pfeerick** [comment]
The bugfix would probably be fine, I'll have to check with Raphael as 2.6 is now in maintenance mode, i.e. we really shouldn't be adding new features... but I feel this was close enough that it would be fine.

**Comment by jfrickmann** [comment]
Yeah, since they are doing so much work with LVGL on 2.7, I figured that I would test all of this on 2.6. 

I want to release my SoarETX package as templates that come preloaded with EdgeTX. I also think that we should make some good basic templates for various types of models, possibly with configuration widgets or scripts that provide a simple user interface like brand-name radios.

**Comment by pfeerick** [comment]
Just a FYI, given the proximity of the release date for 2.7, and that 1) both 2.6 and 2.6.1 were heavily delayed and that 2) LGVL is being deferred till 2.8, I've proposed that 2.6.1 be scrapped, and we release 2.7 mostly on time - thus entering feature freeze shortly - so there should be no need to maintain this branch / PR any further... i.e. I'll try and review the latest updates in the 2.7 equivalent tomorrow with a view to merging it (and companion SD card files). Meaning this will get prominence as new feature for 2.7 ;)

**Comment by jfrickmann** [comment]
OK, thanks for letting me know! I will delete it as soon as 2.7 RC1 is out. For now, I am using it for testing, and I also just shared it with RCG people if they want to test. I stayed away from 2.7 because I thought that they were busy implementing LVGL on it.

**Comment by gagarinlg** [comment]
> OK, thanks for letting me know! I will delete it as soon as 2.7 RC1 is out. For now, I am using it for testing, and I also just shared it with RCG people if they want to test. I stayed away from 2.7 because I thought that they were busy implementing LVGL on it.

LVGL is done on an extra branch and there is still a lot of work to be done before it gets ready.

**Comment by pfeerick** [comment]
Closing this PR now as 2.7-rc1 is out...

**Pull request closed without merging**
