### PR TITLE
UI: remove rssiSource and use default value 

### LINKED ISSUE #2552: RSSI Telemety Source
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Whenever something changed in my telemetry the RSSI telemetry source gets lost and on the field, I cannot select it - I can only do this in the Companion and go to tlemetry and select "RSSI()". Not being able to select this in the TX ends in repeating "RSSI critical" voice alarms, which leads to switching it off - bad idea.

### Describe the solution you'd like

Being able to use the same dropdown menu in the TX that I can use to select RSSI telemetry source in the telemetry menu.

### Describe alternatives you've considered

Set it in the Companion - but on the field useless.
Switch Voice alarms off

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mha1**
Fixes #2552 

For justification please refer to discussion in #2552 

Summary of changes:
- force rssi source to default yaml value ("rssiSource: none") at model load if not already set to default
- remove rssi source selection from Companion and b&w UI (color LCD never implemented this option)

### CODE REVIEW

**Comment by mha1** [comment]
@pfeerick what do you think about this?

**Comment by pfeerick** [comment]
You can remove the commented out code completely... it's in the git history if it needs to be reinstated. Otherwise, yup, LGTM. Possibly some other places it can be cleaned out (i.e. remove rssiSourceLabel from Companion completely, so it doesn't need to be hidden)?

**Comment by mha1** [comment]
I can do that. Just left it in for a review before/after.

**Comment by mha1** [comment]
cleaned up cpn and radio code

**Pull request merged**
