### PR TITLE
chore(color): Lvgl performance improvements.

### PR DESCRIPTION
**Pull request by philmoz**
Speed up the Flight Modes, Inputs, Mixes, Outputs, Logical Switches, Global Variables and Special/Global Functions list views.

Change entails removing the Lvgl flex and grid layouts from these list views and using absolute positioning instead.

### CODE REVIEW

**Comment by pfeerick** [comment]
Damn... Raphael will not be happy... but it seems flex layouts are just not suited to our needs... suck up too much RSS. This seems much more responsive now, pretty close to what 2.10-rc3 is on my other radio.

**Comment by philmoz** [comment]
> Damn... Raphael will not be happy... but it seems flex layouts are just not suited to our needs... suck up too much RSS/MCU time. This seems much more responsive now, pretty close to what 2.10-rc3 is on my other radio.

Thanks for testing - if there are any particular pages that feel noticeably slower please let me know which.

I only have the one TX16S so I have to switch firmware versions to test. I have added more accurate timing code for the main menu pages and in my testing all the menu pages show similar or faster speeds than 2.10.

**Comment by pfeerick** [comment]
The only page seemed slower when I tried earlier (and it might be like only 250-300ms difference) was the model settings -> telemetry tab... but I'll go through the rest and see what they look like also.

**Comment by raphaelcoeffic** [comment]
> Damn... Raphael will not be happy... but it seems flex layouts are just not suited to our needs... suck up too much RSS/MCU time. This seems much more responsive now, pretty close to what 2.10-rc3 is on my other radio.

After looking at the changes, I must say it's not that bad :-D Thx @philmoz for such a tremendous amount of work!

**Pull request merged**
