### PR TITLE
feat(ACCESS): configure AUX serial port as "External module"

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
### Description

This allows configuring the external access mod on runtime rather than by compilation option.

First, configure the hardware port (only available on `AUX1`)
Screenshot 2022-10-15 at 20 46 59

Then the module can be chosen:
Screenshot 2022-10-15 at 20 47 42

TODO:
- [ ] Companion support (separate PR)

### CODE REVIEW

**Comment by HThuren** [comment]
DA translation

#define TR_AUX_SERIAL_MODES            "FRA","Telem spejl","Telemetri ind","SBUS træner","LUA","CLI","GPS","Debug","SpaceMouse","Eksternt modul"

**Comment by Eldenroot** [comment]
CZ translation:

`#define TR_AUX_SERIAL_MODES            "VYP","Telemetrie zrcadlení","Telemetrie vstup","SBUS Trenér","LUA","CLI","GPS","Debug","SpaceMouse","Externí modul"`

**Comment by raphaelcoeffic** [comment]
@HThuren @Eldenroot please note that you guys can make PRs against this PR's branch ;-)

**Comment by HThuren** [comment]
Well, havn't tried (yet :-) ), have to figure out how to

**Comment by brainbubblersbest** [comment]
All Warp Levels Working on X12S Enterprise.
And in all Territorys ;D

**Review by gagarinlg — APPROVED** [review]

**Comment by pfeerick** [comment]
Confirmed working on TX16S MK2 (ELRS) with [externalaccess mod](https://github.com/opentx/opentx/wiki/Externalaccessmod). R9M+2019 module running FCC firmware, and was able to register, bind, and configure options on both module and R9 SX receiver. If connecting directly to AUX1, inverters needed.

**Comment by edwardrf** [comment]
I'll apologise for my limited understanding of the firmware, I would like to understand [this portion of the logic](https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/gui_common.cpp#L474-L481):

```
#if !defined(AUX_SERIAL_DMA_TX) || defined(EXTMODULE_USART)
  if (mode == UART_MODE_EXT_MODULE)
    return false;
#else // defined(AUX_SERIAL_DMA_TX) && !defined(EXTMODULE_USART)
  // UART_MODE_EXT_MODULE is only supported on AUX1, as AUX2 has no TX DMA
  if (mode == UART_MODE_EXT_MODULE && port_nr != SP_AUX1)
    return false;
#endif
```

Why AUX1 cannot be set to module if `EXTMODULE_USART` is defined? I am wondering if I can wire in another module internally in to my RadioMaster Pocket, which apparently has an empty UART port on the main board.

Thanks in advance.

**Pull request merged**
