### PR TITLE
chore(radio): Reduce size of the data structures in FLASH storage.

### PR DESCRIPTION
**Pull request by philmoz**
Optimise the layout of the YamlNode structure to reduce FLASH size.

Saves just over 4K on X7S build, slightly more on TX16S.

### CODE REVIEW

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
@philmoz good catch! The changes look reasonable to me.

**Comment by raphaelcoeffic** [comment]
@pfeerick we might even want to consider it for cherry-picking into `2.9` branch. `4 KB` is really a heap of FLASH these days 🥹

**Comment by philmoz** [comment]
I've shaved another 2K off the space used by the YamlNode structures.

**Comment by philmoz** [comment]
Reduced the size of the sensor definition arrays.

Total savings:
- X9D+2019 = 7969 bytes
- TX16S = 7336 bytes
- X7S = 7936 bytes

**Comment by pfeerick** [comment]
> @pfeerick we might even want to consider it for cherry-picking into `2.9` branch. `4 KB` is really a heap of FLASH these days 🥹

For the worst offender (X9D+2019) we're at 
```
Flash:   501.24   97.90%     512	  10.76
```
for EN in 2.9 branch atm, so if you think we're gonna chew through that during the remainder of the 2.9 lifecycle, sure 😆 For a change though we're not scrapping the barrel to the point where I can't even do some of the language builds like DE and DA 😮 ... yet!

**Comment by pfeerick** [comment]
@raphaelcoeffic Still want this for 2.9.1? If so, I'll add to the list for tomorrow as I think `main` has copped enough change for one day / nightly. 🤭 Then we can wrap up 2.9.1 pretty much one time (I did schedule it on the milestone for four weeks after 2.9.0 🤣 ) 🤞

**Review by pfeerick — APPROVED** [review]

**Comment by frankiearzu** [comment]
One question about memory optimiation in the sensors.. I see that we are trying to pack small numbers so that we can use less bits and pack them together...  also saw that we moved the "name" towards the end of the struct.. does that helps the compiler in any way??  is it to stay 32bit aligned?

**Comment by philmoz** [comment]
The changes to the sensor files are in the structures used to parse the incoming telemetry data, not the actual sensor data after parsing. The name field is a a pointer so needs to be 32 bit aligned.

**Comment by frankiearzu** [comment]
Thats what i was thinking... it saves probably about 2-3bytes per sensor definition in the tables.

**Pull request merged**
