### PR TITLE
allow X10(/S) Express radio displays to actually dim, not just get slightly less blinding

### PR DESCRIPTION
**Pull request by packetpilot**
### Fixes
...an issue I nearly opened myself before opening the PR (but didn't!), and does not fix the open issues around backlights & X10 targets that I was able to find.

### Summary of changes
The diff truly does speak for itself in this case -- the brightness floor which was formerly 46 for X10 targets is now 1, hopefully w/ as few char changes as possible.

### Testing
I was able to test on my own X10S Express. I do not have X10 hardware onto which I could load my build. There may be a "very good reason" the minimum of 46 had been set for X10 targets, but I see zero ill side-effects.

### Jesus man, for a change so tiny, just stop typing already!
IMHO, bringing this into 2.9 _might_ be worth considering, but I may be the sole x10 owner whose retinas are made of delicate flower petals that were grown within earshot of sensitivity seminars in the bay area.

It feels good to no longer be backed into a corner of using ETHOS* in order to comfortably use one of my radios. Here's hoping it might help another delicate flower out, too.

*credit where it's due: their UX is decent and likely preferred by anyone whose radio expectations haven't been twisted all around by (o/e)tx use.

### CODE REVIEW

**Comment by 3djc** [comment]
While it may work for somewhat recent radios, it definitely wasn't initially, screen started blinking badly bellow those values (hence the limit that was only added to those radio

**Comment by packetpilot** [comment]
My radio was purchased in Q3 2019.

Of course the changes need reviewing -- that's why this PR exists of course! -- but I don't understand what you're saying with:
> the else statement is for radio that arent x12s nor t16familly sooo,: x10

I've not changed anything w/r/t the else statement other than plucking X10 targets out of the broad net it casts.

I can try to constrain this change to _just_ the _Express_ variants of the X10 (using `PCBREV=EXPRESS`) logic, if you think that'd be worthwhile. I do have what I believe is one of the early X10S Expresses but I didn't have my finger on any RC pulse before 2019 so 🤷... iirc, ACCESS was still rather fresh.

**Comment by packetpilot** [comment]
_Now_ I get what you mean, @3djc! I'll push a commit soon that hopefully demonstrates.

**Comment by pfeerick** [comment]
> I've not changed anything w/r/t the else statement other than plucking X10 targets out of the broad net it casts.

I think the problem JC is probably referring to is that PCBX10 applies to almost all of the colorlcd radios, not just the Horus X10/X10 Express. i.e.  T16, TX16S, T18 as well. However, having said that... RADIO_FAMILY_T16 applies to guess what... T16, TX16S, T18 ... meaning the else pretty much only applies to the X10/X10 Express... but that is more just happy coincidence IMO. It would probably be better to use `RADIO_X10E` there, instead of the more broader `PCBX10`, if you want to specifically catch the X10 Express.

**Comment by packetpilot** [comment]
@pfeerick that suggestion's much better than my quick-and-dirty first pass:
`#elif defined(RADIO_FAMILY_T16) || (defined(PCBX10) && defined(EXPRESS))`

**Comment by packetpilot** [comment]
I'll nerf the [WIP] prefix in the PR title once I get this flashed to my radio (quite soon).

**Pull request merged**
