### PR TITLE
feat(color) - Implement DISPLAY_TRIMS_CHANGE option for color LCD trim widget.

### PR DESCRIPTION
**Pull request by philmoz**
Also refactor trim code.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Does it fix this one? 
https://github.com/EdgeTX/edgetx/issues/2050

**Comment by philmoz** [comment]
> Does it fix this one?
> #2050

Yes, although I'm not happy with the way the trim value is displayed.
It does not fit properly in the trim box for large and negative values.
I am experimenting with displaying it the way B&W radios do.

**Comment by Eldenroot** [comment]
Good, thank you.

It could be enhanced in future :)

**Comment by philmoz** [comment]
I've changed the display to work like B&W radios with the trim value to the side instead of over the position marker.

Screen Shot 2023-03-03 at 9 59 10 am

**Comment by pfeerick** [comment]
This looks great, and B&W consistency is a nice touch (as well as good inspiration at times).

**Pull request merged**
