### PR TITLE
fix(ui) - Trainer setup layout

### PR DESCRIPTION
**Pull request by philmoz**
Update the trainer setup page layout to:
- remove small amount of scroll of landscape layout
- use available space on portrait layout

Screen Shot 2023-01-24 at 8 44 02 am

Screen Shot 2023-01-24 at 7 34 35 am

### CODE REVIEW

**Comment by froqstar** [comment]
Isn't there enough space to replace the `:=` and `+=` with text like "replace" and "add"?
Would be more user friendly IMHO.

**Comment by pfeerick** [comment]
There should be... and I don't see why not... the Multiplex option for mixes is also spelled out, so it would also be consistent with how it's shown there.

**Comment by philmoz** [comment]
> Isn't there enough space to replace the `:=` and `+=` with text like "replace" and "add"?
> Would be more user friendly IMHO.

This will require changing the TR_TRNMODE string and getting translations for 'Replace' and 'Add' for all languages.
The layout will then need to be tweaked to fit the longest translated string.

**Comment by pfeerick** [comment]
```
#define TR_VMLTPX                      "Add","Multiply","Replace"
```

**Pull request merged**
