### PR TITLE
Show mix and output bars on the mixes and output pages.

### PR DESCRIPTION
**Pull request by eshifri**
This is inspired by discussion from 
https://www.rcgroups.com/forums/showpost.php?p=48884147&postcount=2203
https://www.rcgroups.com/forums/showthread.php?3916381-Official-EdgeTX-Discussion-Thread/page147

Summary of changes:
On the mixes screen mix bar is displayed below every mix.
On the outputs screen output bar is displayed under every active (associated with mix)  output.

It might be helpful to be able to see all channels affected by a certain input.
I think it is more useful for mixes than for outputs, hence two separate commits, so outputs screen changes may be dropped.

screenshot_tx16s_22-03-20_10-07-08
screenshot_tx16s_22-03-20_10-09-51

### CODE REVIEW

**Comment by pfeerick** [comment]
I think instead of pursuing this sort of change we should instead try and trigger the full channel monitor instead... At worse, an on screen button, otherwise some mechanism where we use the MDL or perhaps TELE button to call it up. This starts to clutter the UI up unnecessarily.

**Comment by raphaelcoeffic** [comment]
For my part, I liked the status bar when editing a mix or output.

**Comment by eshifri** [comment]
It is reasonably easy to implement a jump to the Channel Monitor as well with a TELEM button.
A little bit more tricky to do it with for the touch interface, but should be possible - need to find a proper place for the button.
So it boils out for what is a better solution.

**Comment by pfeerick** [comment]
If you can hook it to the TELEM button, no need for a touch... oh bugger... NV14/PL18 are basically touch only... ok so I it comes down to either
- needing gesture support like is proposed in another issue
- a button at the top to switch to the channel monitor
- bottom row statusbar like was done with OTX (There is an issue open for that still for  2.8 and I was working on some code for that). #404
- this, but a bit prettier or maybe with options... we're talking about having options for tabs and features are being shown in 2.8, perhaps this could also be optional as part of that... https://github.com/EdgeTX/edgetx/issues/1692

**Comment by gagarinlg** [comment]
Having gestures either need an icon to indicate the availability or it comes to "discoverable UI", what I don't like. When you have an icon that can also be a button and not gesture is needed.
A status bar at the bottom or top sounds like a good idea to me

**Comment by eshifri** [comment]
It is more complicated than I thought: it is possible to get from mixes/outputs tabs to channel monitor.RTN/back button return to the proper tab. But from this moment something in the system thinks that we are on the main screen and TELEM and MODEL buttons are working as if we are in the main view.

**Comment by JimB40** [comment]
Guys need to step in as I saw a least 3 different proposals for TELEM button. And button is One ;)
IMHO TELEM button should stay for what is says Telemetry. Not for Channel Monitor or Screen Setup as it is now. 

Now about displaying value in Mixes & Outputs. 100% yes. That feature is present in OTX and IDK why it was ditched.
Example is setting channel endpoint when you have to have live view on us value while changing endpoint value. Setting enpoints to match 1000-2000 us range.

That being said do not rediscover America. It was done well in OTX.
Selected line had a value preview in marked place and this solution will not clutter UI
159174137-aa09a84f-95bc-44eb-91ba-74f9d211df6d

If I ever need to see more than one channel preview I can always go to Channel Monitor.

Last but not least I would implement this topbar preview for Inputs too.

**Comment by eshifri** [comment]
@JimB40 There is a difference between OTX and ETX here: in ETX you cannot edit anything from this screen - you have to go to the EditMix screen, which has the mixer/channel monitor.
What is the value of seeing active channel only, if you cannot change it?
Channel selection is OK if you have buttons/scroller - for touch interface it is inconvenient, since the menu is immediately involved and you have to cancel it.

**Comment by pfeerick** [comment]
I think he also forgets that in OTX, you can also jump to the channel mixer when at the outputs, mixes page ;) Try press the MDL key when in any of the model setup screens. 

We could either do the same, or use the TELEM key as is currently proposed. The whole purpose of the channel monitor (and also LS overview) being accessible here is so that you DON'T need to back all the way out of the menu, and then go back into the channel monitor. And then go back into where you where to continue making changes. You know, that whole idea of less clicks you keep talking about Robert? 😁 

It partly depends on consistency... what will a short press of TELEM do at the main screen. What will a long press do. Will that same behaviour be carried out when in the SYS or MDL menus? If so, perhaps we need to avoid using TELEM, and use MDL instead. That would also benefit of being the same as how the B&W radios currently are - i.e. with the Zorro, if you were to press MDL whilst editing an input or mix, the channel monitor will come up. This also means we don't have to worry about radios that don't have a TELE button ;) 

Due to how the code is structured, it won't be easy at all to put the channel bar in the tab title area, as that is in the domain of the page tab code, not the mixer page... Also, because of the intended re-write, it would be better to NOT spend too much effort on this, as it could be blown away very shortly if it's UI code...

**Comment by JimB40** [comment]
Sorry guys post-Covid fog ;)
Just looked at 2.7RC1 and we already have live preview for mixes and outputs modal windows
screenshot_tx16s_22-03-27_11-19-30
Kind of obsolete then to add preview to list page?

**Comment by pfeerick** [comment]
I personally think this PR is not the way to do it (just doesn't look right, and seems to clutter the UI), and that #1731 (the shortcut to channel monitor) is the better option. We just need to figure out the best way to get there... do we use the TELE button, or use the MDL button? If we are able to replicate the 'focused' channel header bar display that would be nice, but is right at the bottom of my list of priorities... 

@JimB40 I also managed to add display of current us value for all the displayed rows on the outputs tab, which is also in 2.7RC1. 

If you are happy with this proposal, I can look at putting the parts of this that don't overlap with #1731 in place. 

When at main screen
- Short press TELE => MDL -> TELE tab (or an alternative) (new)
- Long press TELE =>  Screen settings (current short press behaviour)

When in the MDL setup screens
- Short press TELE (or do we use MDL?) => Channel monitor (new)
- Short press SYS => exits and jumps to radio menu

When in the SYS screens:
- Short/long press TELE => does nothing (no change)
- Short press MDL => exits and jumps to model menu

Alternative to MDL -> TELE: 
Do we actually want to go to the MDL -> TELE tab, or just the table of tele sensors (which would be implemented as a new page). I think it would look a lot cleaner if we went that way... can always have a edit button if you need edit the sensors, which jumps to the MDL -> TELE tab.

**Comment by JimB40** [comment]
Agree. Current implementation for chanell preview is more than enough to do tasks.

Regarding key bingings you know my point of view. :)
I would bind SYS and MDL as all-around the system shortcuts that means that whatever is displayed presing them will take you to the binded screen. No mater if you are in MODEL Tabs view, Radio Tabs view, Channel Monitor,  Screen setup, any Modal window etc. These should be all-time active shortcuts that allows you quickly navigate to quite distant place in UI tree without "going up" to Main view with Exit and "going down" using Enter

As we already discussed an partly agreed:

MDL short -> goes to MODEL configuraration Tabs set (exactly to the 1st one that is MODEL SETUP now)
MDL long -> goes to MODELS screen (switching, adding, deleting etc)
SYS short -> goes to TOOLS tab which in futute release will be separate screen called APPS
SYS long -> goes to RADIO configuration Tabs set (exactly to the 1st one that is now TOOLS but after making separate screen called APPS and moving SD Card browser to be one of applications 1st screen will be RADIO SETUP and this will be consistent with MDL long to enter configuration)

First three bindings are already implemented thanks to #1610 but only on main screen view. If you go to any other place in system, SYS & MDL do nothing. Bindings are "empty" 
(TBH it needs to be chceked if someone hasn't used it in any other PR - because they were free)

That leaves TELEM, PAGE > and PAGE< to be used for other purposes.

We have three ideas to use it:
1. Screen Setup - (TELEM short press now)
2. TELEMETRY tab in Model configuration
3. Channel monitor

We can choose two to be all around system shortcuts or code behaviour of TELEM depending on curently displayed content.

**Comment by pfeerick** [comment]
Thanks for proposing this, but as I'm sure you already could guess, will be going with #1748 instead. It was no loss though, as it gave us a something to look at and discuss. ;)

**Comment by 3DRacer** [comment]
> That being said do not rediscover America. It was done well in OTX. **Selected line (channel) should have value preview in marked place** and this solution will not clutter UI 159174137-aa09a84f-95bc-44eb-91ba-74f9d211df6d
> 
> If I ever need to see more than one channel preview I can always go to Channel Monitor.
> 
Thats exactly what i would prefer!
would be perfect with possibility jump output screen with touch that area and/or with MDL button.

**Comment by pfeerick** [comment]
Maybe something like this will surface in a future version... but for now you, get the jump to channel monitor via MDL at any of the model setup screens (when not in a edit subpage).

**Pull request closed without merging**
