### PR TITLE
feat(radio): discover SBUS trainer availability

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This PR allows for discovering on runtime if a serial port is available to allow for SBUS trainer on the external module bay.

Summary of changes:
- SBUS trainer is now based on availability of a UART on HB pin.
- CPPM trainer is now based on availability of a timer on HB pin.
- more generic trainer code.

This PR adds SBUS/CPPM trainer capability to to the X10 Express and CPPM trainer to the X10 / X12S. Radios that have been modded with a UART on PPM/HB (aka. "External ACCESS mod") will profit from this as well, even if configured dynamically by assigning AUX1 to the external module.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
*Notes to myself:* mid-term, we should have the trainer timers / USART defined on external available in module ports, and make use of the `dir_flags` when matching ports.

**Comment by sande005** [comment]
See new issue #4324 to see if it has any bearing on this.  #4167 may not have resolved power issue in Trainer option.

**Comment by raphaelcoeffic** [comment]
> See new issue #4324 to see if it has any bearing on this. #4167 may not have resolved power issue in Trainer option.

The relevant code has been fairly re-written in this PR, so that might change things.

**Comment by mha1** [comment]
tested ok on NV14 with ELRS nano RX on 3.3.1 configured to output SBUS

**Comment by mha1** [comment]
x9d expects SBUS trainer input on the HB pin, whilst most other radios expect it on the S.Port pin. Does the module work on the x10s under otx?

**Comment by sande005** [comment]
No, it did not - according to Frsky and Mike Blandford, the pin configuration was changed on the first X10's, killing the sbus input capability.  BUT on the X10S-E (my version) it WAS restored, but OTX never reimplemented.  Prior discussions about this in RC Groups and in GitHub indicated that Edge would be adding the sbus detection to allow this in all radios that had the capability in 2.10.  Seems like it isn't quite fully functional....(or I've been misled by Frsky and Mike Blandford).

**Comment by mha1** [comment]
use any of your receivers, set them to SBUS output and wire it to the JR bay GND/VCC/S.Port and try Master/SBUS again

**Comment by sande005** [comment]
Now that is interesting....using an old x8r connected as you noted works just fine.  Guess I can do that instead of the fancy module.  Wonder why it works in the Taranis, and not in the X10S?
Finally, a non-bluetooth wireless trainer solution for my radio, which I haven't had since the days of "The Linker" for the Taranis!

Thank you!

**Comment by mha1** [comment]
The x9d is one of the few radios that have a functional HB input and expects SBUS on the HB pin. As the module was designed to work with those radios it outputs SBUS on the HB pin. The X10s expects SBUSin on the SPort pin. I'm sure the module will work if you feed the modules HB pin to the X10s SPort pin.

The use case for Master/SBUS is to allow connecting receivers via SBUSout of the receivers. Depending on the radio you need to feed SBUS to the right pin. This is mainly the SPort pin, only fir Taranis radios it's the HB pin. If in doubt try SPort first and if that doesn't work try the HB pin.

**Comment by sande005** [comment]
Thank you for the extended explanation!  And thanks to all that worked on this to get it up and running on Edge!

**Pull request merged**
