### PR TITLE
Let's do some dirty hack with MPM RX

### LINKED ISSUE #1671: Turning on internal MPM screws the synchronization with the external ELRS module
**Describe the bug**
When using an external ELRS module it is not possible to use the internal MPM as wireless trainer link. Consider e.g. following setting:

`use the external ELRS as link to a model and the internal MPM as wireless trainer link to a spectrum transmitter`

As discussed on discord with @raphaelcoeffic (pafleraf) and @3djc, currently "you cannot synchronize on 2 modules at the same time. At least not if it triggers the mixer as now. The current implementation synchronizes on the internal module if ON, and on the external otherwise." "The fact that the internal MPM is turned on screws the synchronization with the external ELRS module!" "Ideally, we should disable the synchronization on the MPM when it works as a RX." "That should be enough to overcome the issue."

**To Reproduce**
1. use ELRS as external module
2. https://www.expresslrs.org/2.0/quick-start/transmitters/tx-prep/ states at multiple places "NOTE: Make sure the internal module is turned off."
3. so the internal MPM cannot be used at all

**Expected behavior**
It should be possible to use the internal MPM even when there is an ELRS external module present and used (active).

**Screenshots**
(none)

**General information**
 - OpenTX version: 2.3.14
 - Hardware: Radiomaster TX16S
 - OpenTX Companion: -
 - (ELRS: 2.2.0)

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #1671

### CODE REVIEW

**Comment by drtrigon** [comment]
Fantastic! Thanks!

**Comment by raphaelcoeffic** [comment]
> Fantastic! Thanks!

Does it work for you?

**Comment by drtrigon** [comment]
Here comes the tricky part. I still use OTX, sorry. ;)

I hesitate to switch due to the fact that as far as I know it's not possible to convert EdgeTX models to OTX. Just in case I feel that I want to return. (although its's not very likely of course ;)

Sooo... is it possible to port this fix back to OTX for testing? Is @3djc intressed in doing that? Otherwise this would be a reason to switch for me, but that would take time. (I expect around 2 to 4 weeks.)

**Comment by gagarinlg** [comment]
You could make a backup of you models and when EdgeTX doesn't work for you, just use the backup.

**Comment by 3djc** [comment]
> Here comes the tricky part. I still use OTX, sorry. ;)
> 
> I hesitate to switch due to the fact that as far as I know it's not possible to convert EdgeTX models to OTX. Just in case I feel that I want to return. (although its's not very likely of course ;)
> 
> Sooo... is it possible to port this fix back to OTX for testing? Is @3djc intressed in doing that? Otherwise this would be a reason to switch for me, but that would take time. (I expect around 2 to 4 weeks.)

Comes "TORX" protocol and hell freezes over !

I'm more interested in a cleaner version where otx woould handle 0 value and MPM would send it for relevant protocol

**Comment by drtrigon** [comment]
> You could make a backup of you models and when EdgeTX doesn't work for you, just use the backup.

I do have backups already. But I would loose all changes done while using EdgeTX. (I do understand why there is not a huge motivation to make converstion from EdgeTX to OTX possible - I'm not about to complain - just explain)

**Comment by pfeerick** [comment]
I'm not sure this actually resolves the issue yet... and the statement "When using an external ELRS module it is not possible to use the internal MPM as wireless trainer link" is not exactly correct... it's more that the module synchronization is screwed... 

i.e. The link still seems to be functioning perfectly fine, and trainer functions are all working, just the CRSF link is basically the wrong speed, even WITH this PR (tx16s-6fb1e31.bin). For me, with Frsky_XR, Flysky 2A_RX or DSM_RX there is no change between main and this PR, using TX16s as master /w Happymodel ELRS + TX12 internal and external MPM (for non-CC2500 protocols). 

no_mpm

with_mpm

**Comment by drtrigon** [comment]
@pfeerick: Thanks for testing! If you wish you can propose a better phase and I'll happy to replace the mentioned statement.

**Comment by pfeerick** [comment]
> If you wish you can propose a better phase and I'll happy to replace the mentioned statement.

It's all good... I was more just pointing out for if anyone else tests it that "OMG... int MPM Rx and ext ELRS for model is working" isn't the result we're after here as confirmation this is fixed... but that the ELRS is running at the proper speed 😁 

(I guess it helps if I actually send this comment, rather than switch tabs and get distracted :grin:)

**Comment by pfeerick** [comment]
As was discussed last night in DMs, last commit restored MPM functionality, but there the wireless trainer link via the MPM **will be lost** at 500hz ELRS (will basically never establish) but appears rock solid at 250hz or below. i.e. this is **known limitation** of the current implementation, *but* there is some thought as to how it may be possible to improve on this already. 

Tested using TX16S internal MPM with FrskyRX, Flysky2A_RX and DSM_RX protocols, using Happymodel 2.4Ghz ELRS at 250hz as the mater, with TX12 as the student radio using either internal MPM or external MPM as needed. 

Similarly, TPro with FrskyRX, Flysky2A_RX using AION ELRS @ 250hz, again with TX12 as the student radio. 

EP2 receiver connected as a USB joystick as the target in both cases. 

Additionally, dual MPM link is not compromised - TX16S bound to Frsky recevier, with external MPM running in Flysky2a_RX mode with TPro as the student radio.

**Comment by drtrigon** [comment]
( The question might know be can the dual MPM link with trainer on the internal MPM also? Actually it should, right? ;) )

**Comment by pfeerick** [comment]
> ( The question might know be can the dual MPM link with trainer on the internal MPM also? Actually it should, right? ;) )
> 
> Forgot: @pfeerick Thanks a lot for solving this!

Most likely, as it runs the other way as per the last sentence in my reply above. I have a preference for internal as the control, external MPM as the student link though, since external module *could* glitch if it's knocked, internal rf shouldn't.

**Comment by drtrigon** [comment]
Intressting info!

However I think ths PR is kind of very important as there are several often used external modules out there and this fix afferctscall of them. Honestly I'm a bit surprised that this topic did not came up earlier. ;)

**Pull request merged**
