### PR TITLE
Add codename define and update all radio version screens

### PR DESCRIPTION
**Pull request by pfeerick**
* Add a defintion for the codename to the makefile

* Update the version screens for all radios, and link to project version and codename defines so only need to update once in the future

### CODE REVIEW

**Comment by elecpower** [comment]
Lots of places in Companion will also need changing again for the domain name change

**Comment by raphaelcoeffic** [comment]
> Lots of places in Companion will also need changing again for the domain name change.
> Do you want to add codename to Companion's about dialog or just radios?

Isn't it taking the versions from the `CMakeLists.txt`? If not, I think those defines should be used.

**Comment by pfeerick** [comment]
Hm... on that point... should that be `www.edgetx.org`, or leave it without the www?

Happy with this for adding the codename? 
image

**Comment by raphaelcoeffic** [comment]
> Hm... on that point... should that be `www.edgetx.org`, or leave it without the www (on the radios)?
> 
> Happy with this for adding the codename?
> image

“www.” Is so 90s 😅 forget about it ;-)

**Comment by elecpower** [comment]
For consistency http or https.
Copyright start year?

**Comment by pfeerick** [comment]
Updated http references to http, changed www.edgetx.org references to just edgetx.org, and copyright msg, with commented out version for future years...

image

**Comment by raphaelcoeffic** [comment]
> For consistency http or https.
> Copyright start year?

HTTPS please! We have 2021 after all ;-)

**Comment by pfeerick** [comment]
Merge?

**Pull request merged**
