### PR TITLE
Support bluetooth module für Jumper T16

### PR DESCRIPTION
**Pull request by stefan73**
Summary of changes:
Suggesting to turn on internal bluetooth module support for T16. The board has the needed place for the BLE module. Soldered one on it. Built the firmware with bluetooth support. --> works.

### CODE REVIEW

**Comment by pfeerick** [comment]
My 2c on the matter is that unless a given radio comes with x functionality as standard, then the compile option to enable x functionality should remain off. Having said that, given that from what I remember of how the bluetooth effects the UI, it is probably unobtrusive enough that it won't annoy too many people who don't have the module fitted. However I think the longer term fix is still not this - it should be something that is enabled/disabled in the UI on at least colorlcd radios since they have the flash memory space to keep the bluetooth code compiled in. i.e. when either serial1 or serial2 choices in are set to 'bluetooth'. ;)

**Comment by stefan73** [comment]
Agreed. It is indeed quite unobstructive in the UI. If module is turned off in the HW menu, it does not appear in the remainder of the UI (e.g. trainer settings). 
Turning it on for the T16 makes it identical to e.g. the Radiomaster radios, where the module is also not in by factory but edgetx has the option turned on.

**Comment by rotorman** [comment]
Bluetooth is not enabled by default for RM radios. Builds with **-DBLUETOOTH=YES**, e.g. on TX16S would otherwise fix AUX2/USART6 to Bluetooth and not allow the user to select anything else for AUX2.
Thus, presently - as long as Bluetooth is not yet integrated full into new Serial Driver stack, where the selection can be made via AUX2 mode drop-down, turning Bluetooth permanently on for all, is not a good idea IMHO as well.
The goal would be instead to change the Bluetooth code, as pfeerick already suggested, as a choice for the serial port and then no custom build for Bluetooth would be required anymore.

**Comment by pfeerick** [comment]
Closing as this isn't going to happen this way... As Risto pointed out, it is *not* turned on by default from the TX16 either, and enabling it anyway would be in conflict with the WiP on the new serial handing. Do not worry though - in the near future this will not be needed anyway, as it will simply be another option on the hardware page, and you should even be able to choose which port is used for the BT where multiple ports are available, allowing for more flexible connection to externally connected BT module.

**Pull request closed without merging**
