### PR TITLE
chore: Update French translations

### PR DESCRIPTION
**Pull request by Pat6874**
continuation of the translation...
It's not over yet!

Fixes #

Summary of changes:

### CODE REVIEW

**Comment by pfeerick** [comment]
Would you like me to merge this, or are you comfortable with making more commits to this branch as you work on it?

**Comment by Pat6874** [comment]
Hello
I think I will finish the translation very soon, and I thank you for
merging everything. I'm not comfortable with using the github. Sorry.
Patrick

Le mer. 12 avr. 2023 à 11:21, Peter Feerick ***@***.***> a
écrit :

**Comment by Pat6874** [comment]
Hello, I cannot find the translation I proposed yesterday. Please let me
know how to retrieve my work. Thank you

**Comment by pfeerick** [comment]
Are you thinking of this? https://github.com/EdgeTX/edgetx/commit/745c465bedbaea3657bfd453c6e60469be775ba8 I merged that one yesterday.

**Comment by pfeerick** [comment]
You can zip the file, and drag it to the comments area of this PR to upload it as part of a message, and it'll be saved when you submit the comment. 

brave_cisHyzGZxl

**Comment by Pat6874** [comment]
hello peter,
Thank you for your answer, I'll send you the whole file translated into French. As specified, I made some adaptations in text size so that it fits in the fields. I hope that will be the case. Is it possible to verify this point with a provisional version in French integrating my work before publication?
Good day
patrick
[fr.zip](https://github.com/EdgeTX/edgetx/files/11230384/fr.zip)

**Comment by pfeerick** [comment]
I'll be able to skim it for the most part to see if everything fits. What radio do you need this for?

**Comment by Pat6874** [comment]
I use the Tx 16s from eachine.

Le sam. 15 avr. 2023, 12:01, Peter Feerick ***@***.***> a
écrit :

**Comment by Pat6874** [comment]
thanks Peter for the test file.
I made some minor adaptations in order to fit the terms in the fields as well as some cosmetics.
it should be good now.
[fr (2).zip](https://github.com/EdgeTX/edgetx/files/11251416/fr.2.zip)

**Comment by pfeerick** [comment]
The latest changes added. Can you review the `TR_BL_` translations again - you cannot use any Unicode characters for the bootloader-related text. No special characters - only ASCII text.

**Comment by Pat6874** [comment]
hello peter,
I corrected the bootloader section and added the recent line
TR_SHOW_INSTANCE_ID in file
[fr.zip](https://github.com/EdgeTX/edgetx/files/11264096/fr.zip)

**Comment by pfeerick** [comment]
Thanks for that. This built fine locally so will merge this in a day or so unless you have any further changes that come to mind before then. 
[tx16s-fr.zip](https://github.com/EdgeTX/edgetx/files/11267971/tx16s-fr.zip)

**Comment by Pat6874** [comment]
no immediate modification, I have to test all of what has been done

**Comment by Pat6874** [comment]
after last check, I propose some final minor modifications and corrections
[fr.zip](https://github.com/EdgeTX/edgetx/files/11283730/fr.zip)

**Review by pfeerick — APPROVED** [review]

**Comment by Pat6874** [comment]
Good morning,
I have a doubt about the Fr translation of
#define TR_CSWSTICKY
can you tell me its exact function in order to have the correct translation.

**Comment by Pat6874** [comment]
in opentx sticky means "bistable" in french
if the function is identical, we can use the term.
"Bistable" in the "LOGICAL SWITCH" window and
"Bist" in the "LOGICAL SWITCHES" window

**Comment by pfeerick** [comment]
Make sense to you also @3djc ?

**Comment by 3djc** [comment]
Yes sir

**Comment by pfeerick** [comment]
Hm... Well, because it's longer than Chrono, we can't misuse the drawing of the next column to clip it on the overview screen... 😆 
(the one string is used for both the overview and edit screens Patrick, it's not two different strings)

128x64
image

212x64
image

**Comment by 3djc** [comment]
Bist for 128

**Comment by pfeerick** [comment]
Nothing to change really then... as it is already this (unless dropping the b for 212 gives it more meaning?)
https://github.com/EdgeTX/edgetx/blob/bd47b491ba97c2cafe215d5546905d085af4184a/radio/src/translations/fr.h#L80-L90

**Comment by Pat6874** [comment]
I  propose to replace the b of bistb by bista for bistable

**Comment by Pat6874** [comment]
sorry...
I propose to replace the b of bistb by a for bistable

**Comment by pfeerick** [comment]
So `bistb` => `bista` ? You can't have `bistable` because it's too long.

**Comment by Pat6874** [comment]
OK, do as you think is most obvious in terms of understanding and compatible with the size of the fields.

**Pull request merged**
