### PR TITLE
feature:  MIN as source

### LINKED ISSUE #1635: Add MIN as source
Currently in EdgeTX if you want a fixed value for a source input you can use MAX as source if need +100 but if want -100 there is currently no source for that available.

So I propose a MIN source like MAX expect with constant value of -100

There is currently no alternate except to use some other source that happens to have a value of -100, but that is sometimes not guaranted, especially with switches.

### PR DESCRIPTION
**Pull request by mha1**
Resolves #1635

Summary of changes:
- added MIN (-MAX -> -1024) as source

### CODE REVIEW

**Comment by mha1** [comment]
This needs translations for HE, CN, TW and JP languages:

#define TR_MENU_MIN   STR_CHAR_FUNCTION "MIN"

**Comment by pfeerick** [comment]
What would "MIN" look like for you?

- [ ] @zyren CN / TW
- [ ] @offer-shmuely HE
- [ ] @ToshihiroMakuuchi JP

**Comment by zyren** [comment]
CN
```c
#define TR_MENU_MIN STR_CHAR_FUNCTION "固定值MIN"
``` 

TW
```c
#define TR_MENU_MIN STR_CHAR_FUNCTION "固定值MIN"
```

**Comment by ToshihiroMakuuchi** [comment]
JP

#define TR_MENU_MIN STR_CHAR_FUNCTION "最小値"

**Comment by ToshihiroMakuuchi** [comment]
We are very sorry. Please correct the word as it was out of balance with the other words.

JP
#define TR_MENU_MIN STR_CHAR_FUNCTION "最小"

**Comment by mha1** [comment]
@ToshihiroMakuuchi No problem, updated

**Comment by offer-shmuely** [comment]
HE

#define TR_MENU_MIN STR_CHAR_FUNCTION "מינימום"

**Comment by mha1** [comment]
@pfeerick HE,  JP, CN and TW translations are in. Would be good to go live.

**Review by elecpower — APPROVED** [review]
Companion tested using in mix line and simulating plus opened 2.3.15 otx to check if impacted conversion. Passed

**Review by pfeerick — APPROVED** [review]
Read/write tested on TX16S and TPro, no issues, sorry for the delay ... life just gets in the way of fun stuff sometimes 😇

**Comment by mha1** [comment]
no problemo

**Pull request merged**
