### PR TITLE
Custom throttle position for warning

### LINKED ISSUE #1275: Throttle initial position customizable
**Describe the solution you'd like**
I would like to set custom value for throttle initial position (position it should be in to clear throttle warning).

**Additional context**
Some models with reversible motors (ex. boats, quads with 3D mode) have neutral throttle in the middle.

### PR DESCRIPTION
**Pull request by piotrva**
Fixes #1275

Summary of changes:
Adds additional configuration option, that allows to customize throttle position that clears throttle warning.
Also adds suitable menu entries for enabling this option as well as requested % value (-100, 100) of the throttle.
Additionally when the option is active it displays required % value of throttle to clear the warning.
This might be valuable option for:
- Drones in 3D mode
- RC cars with reversible ESCs
- RC boats with reversible ESCs

Notes:
- All changes were tested only on Radiomaster TX12
- Tested that opening yaml file without positions for the settings is safe (defaults to this option disabled)

### CODE REVIEW

**Comment by piotrva** [comment]
@pfeerick I think, considering that #1417 might need some further development - we might consider this to be first in line for merge.

**Comment by pfeerick** [comment]
I wasn't going to say anything! 😋 No problem, I'll look at this tomorrow then.

**Review by pfeerick — APPROVED** [review]
Tested on radio using:
- TX16S
- TX12
- X9D+2019

As indicated, non-presence of option setting behaved as if option disabled (correct). 

Tested Companion using TX12, read and write ok. 

LGTM. Rebased and updated due to changes in main, if it passes all tests (meaning I didn't screw up the update) it's in. We should probably tweak the Companion UI a little but there are a few things being added atm so will leave it until they are all in so it can be re-organised then. 

Bugger, missed nightly build - lunch got in the way...

**Comment by elecpower** [comment]
Agree on Companion tidy after current bunch are in. Also bunch of fixes to T Pro to come across too.

**Comment by wimalopaan** [comment]
It would be cool, if the desired throttle position could be set by moving the throttle stick.

**Comment by pfeerick** [comment]
Later addition... probably have to add a button or press and hold, and then also document that... else no-one will know how to do it ;)

**Comment by wimalopaan** [comment]
Maybe simpler? Activate the custom position field, move the throttle, press return. The same procedure as auto-detection of inputs.

**Comment by piotrva** [comment]
It might be an idea but I think manual setting should also be possible. I will think about it as I am done with checklist stuff and I will make another PR for that change.

**Comment by pfeerick** [comment]
Simpler is _not_ having multiple actions per field, requiring prior knowledge of all the possible actions. :) But simple and easy are not always the same. So I do get your point here - i.e. for setting a source/switch, unlike colorlcd, B&W will let you either move the stick, or scroll/roll the wheel so you have the best of both. So sure, if it's possible to instead read _changes_ to the throttle value while the edit field is active, or instead alter it manually, I think that would make it much easier to use. And sure, no hurry!

**Comment by wimalopaan** [comment]
Side note: the error message should now read as "Throttle not neutral" instead of "Throttle not null"

**Comment by piotrva** [comment]
> Side note: the error message should now read as "Throttle not neutral" instead of "Throttle not null"

Where you have "Throttle not null"?
AFAIK in translation it is "Throttle not idle" and this is what I saw during testing...

**Comment by wimalopaan** [comment]
In german: "Gas nicht null!"

**Comment by piotrva** [comment]
I have not altered translations at all. Only done new items I added in Polish as this is my native language.
If you know German feel free to review the translation.
Tbh I noticed that some of translations are a complete mess. @pfeerick I think at some point some translation review would be needed ...

**Comment by pfeerick** [comment]
Yeah, https://github.com/EdgeTX/edgetx/pull/1035 is still WiP so have to be wary about making changes that will get removed when it's ready for merging. Another long-term goal is to make it so a system like [crowdlin](https://crowdin.com/) can be used in the future... thus making translation more accessible to non-programmers.

**Pull request merged**
