### PR TITLE
Added OneBit option also to color radios

### PR DESCRIPTION
**Pull request by rotorman**
Tested successfully by Discord user Ian_Gage on X10S: https://discord.com/channels/839849772864503828/867878348037947402/979133214520119326

Needs appropriate addition to Companion (@elecpower would be sweet if you would find time to look into this - thanks!).

### CODE REVIEW

**Comment by elecpower** [comment]
> Needs appropriate addition to Companion (@elecpower would be sweet if you would find time to look into this - thanks!).

Companion was skipped yet again when introduced for B&W so I'll add for all

**Comment by pfeerick** [comment]
Both #4fce1dc and #bf4b5d8c0c1e386d5a4852a80d459540bab98ed3 have 

```git config --global --add safe.directory $(pwd)``` on the wrong line... move it up two lines so you're not trying to tell get the build directory is a 'safe dir' ;) i.e. like https://github.com/pfeerick/edgetx/pull/6 And I'll be back on board next week...

**Comment by elecpower** [comment]
Whilst in the area I took the liberty of doing a little housekeeping which I noticed during testing this PR :-)

**Comment by pfeerick** [comment]
I was initially focused on just getting the merge conflicts/LGVL changes resolved, and then went a little further so this now clearly lives in it's own code block and is also more descriptive of what it relates to...

image

**Comment by gagarinlg** [comment]
Without testing on my side, I think it looks good

**Comment by pfeerick** [comment]
Color UI and Companion appear to be working as expected on TX16S, and Companion with TX12.

**Pull request merged**
