### PR TITLE
chore(radio): remove EEPROM macros and related code

### PR DESCRIPTION
**Pull request by philmoz**
Get rid of legacy code.

### CODE REVIEW

**Comment by pfeerick** [comment]
Much over due cleanup... looking good! May be a bit heavy handed as the EEPROM driver code should remain even if not in use at present, as it _may_ resurface for use for factory calibration/reset data.

**Comment by philmoz** [comment]
I put the eeprom_driver files back; but together in radio/src/hal/eeprom instead of previous locations.

**Comment by 3djc** [comment]
Makes a lot of sense to me

**Review by raphaelcoeffic — APPROVED** [review]
LGTM

**Comment by pfeerick** [comment]
Looking good on TX16S, TLite, Commando8, X9D+.

**Pull request merged**
