### PR TITLE
Horus X10 Touch Screen Mod Update-EXPRESS PCBREV check failing in cold temps

### LINKED ISSUE #4509: Touch Screen Mod on Horus X10S Express at low temperatures goes into "Wrong PCB detected"
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

PR #4151 (already merged) that allows using a touch screen lcd on FrSky X10 unfortunately conflicts multi-trainer feature, which contemplates removing a pin from the ISRM module, which is easy to do and which many have done and which I still use in the OpenTX era.
The result is that my X10S Express now reports "Wrong PCB" at power up, now the firmware thinks I applied the modification to the lcd, which is absolutely wrong.
I don't understand why, since the lcd touch screen modification is quite complicated, instead of doing the pcb check you didn't leave a compile flag for it, it would have been better imho, or the PCB reconnaissance should not be done if the firmware is compiled with "-DALLOW_TRAINER_MULTI=YES" as in my case.

### Expected Behavior

With revert 77fd73 my tx turns on regularly, so please @MRC3742 fix this issue, as new implementations normally should not break old established functionality, thanks.

### Steps To Reproduce

1. Modify the ISRM module by removing the pin in the picture
2. Compile the firmware with -DALLOW_TRAINER_MULTI=YES
3. Turn on the TX

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

_No response_

### OS Version

Irrilevant

### Anything else?

294686395-b7b89f98-681d-4a0d-b208-837275129908

The pin to be removed for the Multi-Trainer.

294687051-55d23b1e-4764-4c0d-8535-295a1de8f465

### PR DESCRIPTION
**Pull request by MRC3742**
Fixes #4509 

Unmodified Horus X10 EXPRESS radios were unable to start when exposed to cold temperatures. 
PCB detection, using a check of GPIO pins, which on the unmodified X10 EXPRESS included floating pin 55 (PA.06) was changing its state and tripping an error, leaving the radio unable to start when cold and displaying "Wrong PCB detected" on the LCD display.

~~This PR will revert the PCBREV check back to its original format for all unmodified X10 series radios.~~

~~Building the firmware now requires a custom build with a "-DHARDWARE_TOUCH=ON" option.~~

@pfeerick please review

### CODE REVIEW

**Comment by MRC3742** [comment]
Please hold off on merging this PR. I am working on a different approach ( Plan C ). :laughing: 
I am testing utilizing the weak internal pull-up of GPIO Pin 55 (PA.06) to prevent it from going low in colder temperatures.

More to come - Rich

**Comment by MRC3742** [comment]
( Plan C )  appears to be a huge success!!!!! :tada: 
After making the changes to allow the additional GPIO floating Pin 55 ~ PA.06 (now required due to the Touch Screen Mod) to be pulled-up by the processors internal resistor, all systems are fully working.

I have run quite a few tests and now have the X10 EXPRESS starting up with no problems detected.
I first ran the same test, that failed the other night, by letting the TX sit outside in 32 degrees F. (0 degrees C.) for one hour.
This test which originally caused a NO Start "Wrong PCB detected" error was tonight starting and working as expected.
As an extreme test, I placed the TX in the freezer for another hour until it had reached 0 degrees F. (-18 C.) :cold_face: 
This test also produced the same results causing the TX to start and operate normally. Proof is in the picture!

I then flashed five different earlier versions of Touch Screen Firmware and each time back to this PR test firmware.
Every time the older firmware would fail to start with "Wrong PCB detected" error and new test firmware would start normally.

I have also tested this firmware on the X10 NON-EXPRESS radio. Still working as it was before this fix for the EXPRESS models.
I would summarize that this PR has fixed the no start issue when cold for the Horus X10 EXPRESS.

Rich

@pfeerick  - please review
Thank You for your four step explanation as that is what led me to this fix.  :-)

X10-Express-COLDER

**Comment by robustini** [comment]
Tested, now fi x https://github.com/EdgeTX/edgetx/issues/4509, thanks!

**Comment by pfeerick** [comment]
Thanks for working through this @MRC3742 I was sort of hoping once you had a handle on why it was happening + repo the gremlin you might be able craft an test that works... Thanks @robustini for the confirmation that it's working for you also. 

From my side, all I can say is the code looks good enough for the job, and my X7 is still booting, but I'm also in warmer climate (plus it's not the EXPRESS version). 🌞

**Comment by MRC3742** [comment]
Thanks for sending me down the right path. :point_right: 

This fix also needs to be added to the 2.9 branch before the 2.9.3 release.
Do you want me to make a seperate PR for that or will you just cherry pick what you need from this one?

Rich

**Comment by pfeerick** [comment]
Ah, thanks for the reminder... I did forget this went into 2.9 🤕 ... I've cherry-picked that in, and will push this and other pending 2.9.3 commits now...

**Pull request merged**
