### PR TITLE
TLite F4

### PR DESCRIPTION
**Pull request by 3djc**
Jumper is changing processor for T-Lite from F2 to F4 sku. Absolutely nothing else changes.

@elecpower Not sure how this should be handled Companion wise. The ONLY difference is in the firmware, all the rest is 100% identical

Probaly some tuning is required on the build chain too

### CODE REVIEW

**Comment by elecpower** [comment]
@3djc since has its own firmware then will need to be uniquely identified in Companion so the correct firmware is sourced for Updates.
This will need to link to updated firmware builds workflows @pfeerick maintains

**Comment by 3djc** [comment]
> @3djc since has its own firmware then will need to be uniquely identified in Companion so the correct firmware is sourced for Updates.
> This will need to link to updated firmware builds workflows @pfeerick maintains

Yeah, the trick is to not duplicate a full radio for that. It uses same transforms, simu, everything but final firmware

**Comment by gagarinlg** [comment]
I am not looking forward to the support discussions about this radio and whether the correct firmware was selected.

**Comment by elecpower** [comment]
> I am not looking forward to the support discussions about this radio and whether the correct firmware was selected.

Yep. Just installed EdgeTX and it bricked my radio.

**Comment by 3djc** [comment]
I'll try to get them to  at least put some identification somewehere on the radio 🧷

**Comment by 3djc** [comment]
Added detection for F2 firmware trying to be run on F4

image

**Comment by pfeerick** [comment]
> Thinking about it, do we have a lot of issues TX12 vs TX12MK2 ?

Not that I have seen... would have to ask RM how many they get via their own support channels. 

> I'll try to get them to at least put some identification somewehere on the radio 🧷

IIRC this is what RM have done... pretty sure there was a warning sticker on the radio telling users to flash the MK2 target for the TX12MK2... the other nice thing being the ELRS sticker in the module bay of the ELRS radios (and presumably MPM sticker on new MPM radios).

**Comment by pfeerick** [comment]
Don't forget `radio/src/stamp.cpp` ;)

**Comment by 3djc** [comment]
> ~Don't forget `radio/src/stamp.cpp` ;)~ Hm, maybe not... that is tied to Jumper defines also... 🤷

I have removed MCU checks part of this to make it into a more generic PR for it. Unsure if I should remove the version display, since once the other is merged, you can't be running the wrong MCU firmaware

**Comment by pfeerick** [comment]
My own preference would be to leave it, as some of the more technically inclined may be interested to know what MCU is in their radio, but it's very much neither here nor there. Then again, it's like wanting to know how much flash and RAM is in it... ;)

**Comment by richardclli** [comment]
As the F2 firmware still works for new radio, I think it is better to start support of this in 2.9.0, please rebase the change to main.  @raphaelcoeffic @pfeerick what do you think?

**Comment by richardclli** [comment]
> As the F2 firmware still works for new radio, I think it is better to start support of this in 2.9.0, please rebase the change to main. @raphaelcoeffic @pfeerick what do you think?

@3jdc We all agreed to start support the TLiteF4 in 2.9.0, please rebase the changes in main, thanks.  I already notify Jumper about this decision.

**Comment by pfeerick** [comment]
I tried a quick rebase of this, and it may be simpler to re-do the PR, as it seems to be picking up a bunch of irrelevant changes between 2.8 and 2.9 in trying to rebase.

**Comment by richardclli** [comment]
> I tried a quick rebase of this, and it may be simpler to re-do the PR, as it seems to be picking up a bunch of irrelevant changes between 2.8 and 2.9 in trying to rebase.

I tried as well, nightmare.  Leave this to @3djc ^.^

**Comment by pfeerick** [comment]
I got bored since it is an annoyingly simply PR atm...

**Comment by pfeerick** [comment]
@elecpower If I'm understanding the update and simulator libraries situation properly, the `tlitef4` flavour is needed to identify the simulator library and firmware file to match for download. If I just wanted to use the `tlite` library for simulation purposes, but still match the `tlitef4` binary for firmware updates, is there any provision for that? 

Would just like to avoid needing to build and ship a separate simulator library that is for all intents and purposes only different in name, but not if any real effort is needed... this want will probably go away with the work towards unified targets, so not wanting to invest too much time on anything that could go out the window in a few months time.

**Comment by elecpower** [comment]
The flavour is also used for the profile settings. Lots more radios than anticipated  when design developed.
Let me seen if there is a reasonably  simple mod I can make.

**Comment by elecpower** [comment]
Looks possible, give me a day or 2. I'll either post an update or a PR.

**Comment by elecpower** [comment]
@pfeerick your wish has come true refer PR #3432

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
@elecpower I already approved (reviewed the radio changes), but could you please have a short look over the companion changes?

**Review by elecpower — APPROVED** [review]
@raphaelcoeffic looks okay but it could take advantage of https://github.com/EdgeTX/edgetx/pull/3432 should it be merged to save a libsim build

**Pull request merged**
