### PR TITLE
Tweaks to companion/simulator 

### LINKED ISSUE #734: Companion Application Settings says OpenTX
**Describe the bug**
Settings Application Settings says "Automatic check for OpenTX firmware updates" should probably say "EdgeTX"

**To Reproduce**
Start EdgeTX companion - click settings button or click Companion TX -> Preferences
Click Application Settings tab

**Expected behavior**
Prompt should read Automatic check for EdgeTX firmware updates"

**Screenshots**
Screen Shot 2021-09-15 at 12 00 20 PM

**General information**
 Companion 2.5 Sept 15 2021

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #734

Also tidies up a couple more references to OpenTX

### CODE REVIEW

**Comment by elecpower** [comment]
Replace with setVisible(false)

**Comment by pfeerick** [comment]
Thank you, changing! :)

**Comment by pfeerick** [comment]
Hidden:
image

Disabled:
image

Hm... I actually prefer disabled now that I see it... What do you think @raphaelcoeffic ? PR will disable, otherwise just needs to be changed to the below to hiding the controls instead. 

```
  // Hide these for now, until online elements are implemented
  ui->autoCheckFirmware->setVisible(false);
  ui->autoCheckCompanion->setVisible(false);
  ui->label_18->setVisible(false);
  ui->OpenTxBranch->setVisible(false);
```

**Comment by elecpower** [comment]
I vote for disabled as it will leave a visible reminder to reactivate when the infrastructure is in place to support.

**Comment by elecpower** [comment]
Removing the project name may be misleading to some users as they may interpret as any firmware eg MPM

**Comment by pfeerick** [comment]
Motion carried... Raphael is distracted unbreaking mac companion builds 😆

**Pull request merged**
