### PR TITLE
Category editor

### PR DESCRIPTION
**Pull request by dlktdr**
Here is the basic category editor. Let me know your thoughts

~~Still needs the #714 fix. If you add a new category, rename it with the OSK and press enter & touch the top bar it will Freeze/EM.~~

~~Also needs some translations done.~~

image

### CODE REVIEW

**Comment by dlktdr** [comment]
With https://github.com/EdgeTX/libopenui/pull/22 fix this seems to work well now.

Let me know if I should change anything 👍

**Comment by pfeerick** [comment]
https://github.com/EdgeTX/libopenui/pull/22 is now merged, so you *should* be able to update the submodule pointer in this PR just like you did in your other PR so that the correct libopenui commit is used.

This is working great - I just created three - four new categories on the transmitter without any trouble at all, and moved models around between the groups. 

My only gripe would be if you create/have more than 7 categories on the TX16S, you'll lose the 'create category' button off screen as the window doesn't scroll / get bigger as needed. Given this should be a *short lived* feature, I don't know if that is really a problem that needs fixing (and also probably a plus for the NV14's portrait screen orientation! 😁).

**Comment by dlktdr** [comment]
Cool it works!

I was missing a newline. Looks better now. You can scroll again.

**Comment by pfeerick** [comment]
It seems like Kevin has a better fix for the keyboard that he says is working for all edit controls now, so if that doesn't present any issues that will be merged, and we'll bump the submodule again.

**Comment by wimalopaan** [comment]
In german translation the button gets a "wrong" translation: "Modeltyp erstellen" instead of "Modelkategorie erstellen"

**Comment by dlktdr** [comment]
> In german translation the button gets a "wrong" translation: "Modeltyp erstellen" instead of "Modelkategorie erstellen"

Will have to trust you on that one ;) That is a previous translation I used but I can make that change here if that's okay with everyone. While your looking what is the proper translations for the two new ones I added?
```
#define TR_MODEL_CATEGORIES            "Model Categories"
#define TR_MODELS                      "Models"
```

**Comment by wimalopaan** [comment]
Modellkategorien
Modelle

**Comment by NemesisXB** [comment]
Tested Working on TX16s.

**Comment by pfeerick** [comment]
@dlktdr EdgeTX/libopenui#23 is in, if you would like to bump the submodule again, and unless something comes up, this will be in Sundays nightly (just to give a little more time if any one else wants to try it out in it's final state... it is working fine for me with built on that PR).

**Comment by rburrow87** [comment]
Seems to work nicely on my TX16S too!

**Comment by JimB40** [comment]
@dlktdr Hey Cliff nice work. Would you like to take care of 2.6 models' labels implementation? Which is more or less the same that category but more flexible? If so just DM me on discord :)

**Pull request merged**
