### PR TITLE
Companion fix yaml handling of ACCESS receiver names

### LINKED ISSUE #2018: Companion not reading/writing receiverName value for ACCESS
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When Companion reads in a model using ACCESS protocol, it does not read in the receiverName value and so it does not write it back out when you push the config back to the transmitter.

Unsure if this is a black and white radio specific issue or if the color screen ACCESS radios have the same issue.

### Expected Behavior

receiverName should be carried into Companion and written back out when writing to the TX.

### Steps To Reproduce

 - Register and bind an RX with ACCESS
 - Read the models into Companion (see that Receiver 1 is blank in Companion when it shouldn't be)
 - Write back to the TX (see that all the receivers are now blank in model settings)

### Version

2.7.1

### Transmitter

FrSky X9D+2019

### Anything else?

Module data before reading into Companion:
```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 8
      failsafeMode: NOPULSES
      mod: 
         pxx2: 
            receivers: 1
            racingMode: 0
            receiverName: 
               0:
                  val: "Slick85 "
```

Module data after writing back to TX from Companion, note receiverName val is missing:
```
moduleData:
  0:
    type: TYPE_ISRM_PXX2
    subType: ACCESS
    channelsStart: 0
    channelsCount: 8
    failsafeMode: NOPULSES
    mod:
      pxx2:
        receivers: 1
        racingMode: 0
        receiverName:
          0: ""
```

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #2018

### CODE REVIEW

**Comment by rburrow87** [comment]
Looks like this took care of it!

Not sure if anything really _needs_ to be done about it, but if I try to pull in one of the models that was written out improperly by Companion 2.7.1, it throws an error because "val" is missing. Works fine if I either re-bind or remove the receiver though.

image

```
moduleData:
  0:
    type: TYPE_ISRM_PXX2
    subType: ACCESS
    channelsStart: 0
    channelsCount: 8
    failsafeMode: NOPULSES
    mod:
      pxx2:
        receivers: 1
        racingMode: 0
        receiverName:
          0: ""
```

However, while testing this, I discovered a bug in the TX firmware when using multiple receivers. With 1 receiver, the `receivers` value is 1. With 2 receivers it goes to 3, and with 3 receivers it jumps to 7. I submitted my finding in #2022

**Comment by elecpower** [comment]
I'll add some code to check for the 'bad' data and ignore so you do not get an error. Thanks for testing and reporting.

**Comment by elecpower** [comment]
> However, while testing this, I discovered a bug in the TX firmware when using multiple receivers. With 1 receiver, the receivers value is 1. With 2 receivers it goes to 3, and with 3 receivers it jumps to 7. I submitted my finding in https://github.com/EdgeTX/edgetx/issues/2022

I haven't checked firmware but Companion interprets the receivers as a bit mapped field NOT a count.

**Comment by rburrow87** [comment]
> I'll add some code to check for the 'bad' data and ignore so you do not get an error. Thanks for testing and reporting.

Confirmed the error is fixed!

> > However, while testing this, I discovered a bug in the TX firmware when using multiple receivers. With 1 receiver, the receivers value is 1. With 2 receivers it goes to 3, and with 3 receivers it jumps to 7. I submitted my finding in #2022
> 
> I haven't checked firmware but Companion interprets the receivers as a bit mapped field NOT a count.

The reason I looked at that and thought it was a problem is because when there were 3 receivers and I read in model data, Companion would just close as if I exited. No error popped up. I just assumed it was out of bounds or something since it was higher than 3.

However, it looks like it works fine with 3 receivers now after this latest change.

**Comment by rburrow87** [comment]
Let me know if I should go ahead and open a new issue, but I've noticed that this fix isn't applying to my recently acquired FrSky X12S with ISRM/ACCESS module. Still working nicely with my X9D+2019 though.

**Comment by pfeerick** [comment]
Is this the exact same issue as #2018 though on the X12S?

> When Companion reads in a model using ACCESS protocol, it does not read in the receiverName value and so it does not write it back out when you push the config back to the transmitter.

As the fix here looks to be radio agnostic... i.e. it doesn't care what radio is in use. So this is probably going to be an annoying problem 😁

**Comment by rburrow87** [comment]
Okay now that you made me look at my old post, maybe it's caused by something else 😛 Almost seems like it's treating the X12S like the internal module is set to XJT instead of ISRM even though it's set to ISRM.

This is what the radio writes:
```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 16
      failsafeMode: NOPULSES
      mod: 
         pxx2: 
            receivers: 0
            racingMode: 0
            receiverName: 
               0:
                  val: "SR6"
```

This is how Companion 2.8 reads it in (notice it offers the `Antenna` option as if it's treating it like the internal module is set to `XJT` and not `ISRM` (and I made sure it's set to `ISRM`)):

image

So this is how Companion 2.8 writes it back out:
```
moduleData:
  0:
    type: TYPE_ISRM_PXX2
    subType: ACCESS
    channelsStart: 0
    channelsCount: 16
    failsafeMode: NOPULSES
    mod:
      pxx2:
        receivers: 0
        racingMode: 0
```

But Companion 2.8 still reads in and writes out fine with my X9D+2019:

image

**Comment by pfeerick** [comment]
Huh? I thought it was ISRM that had antenna options, not XJT? 😆 

Hm... the type is still `TYPE_ISRM_PXX2` and `mod` is `pxx2`, so not XJT. but yeah, otherwise looks like XJT (channel count is 16, not 24, antenna opt)...

**Comment by rburrow87** [comment]
They both do the antenna options thing, but the XJT handles antenna options in model data somehow, but the ISRM does it through module settings which are somehow stored in the module or something. You'd have to ask someone more qualified than me for the details on how all that works. 😆

**Comment by raphaelcoeffic** [comment]
ISRM has it in the module options. These options are handled by the module itself.

**Pull request merged**
