### PR TITLE
External RF SBUS refresh rate not functional

### PR DESCRIPTION
**Pull request by dlktdr**
Decided to try to squash an easy bug #733. turns out it was a little more involved. The SBUS refresh rate wasn't adjusting at all, color and B/W. It was incorrectly setting the ppm.framelength value in the GUI instead of sbus.refreshrate

Also removed some numbers to make it (hopefully..) easier to read. Removed a few but now all from PPM too.

I have tested this on my TX16S on the scope. Also found that the maximum default value of 40.0ms period won't work because it overflows the unsigned 16bit when the value is larger than 32.5ms. So I set the maximum to this. I don't think too many people want an SBUS rate that low anyway :)

I have not tested the changes to the B/W models and hopefully someone can confirm if they work :)

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
> I just realised I may be able to test this after all... so will look at this over the weekend.

Definitely a job for a good old logic analyser ;-) @rotorman wanna have a look at this?

**Comment by rotorman** [comment]
Yep, glad to check this out!

**Comment by dlktdr** [comment]
Pulled the X9D+ 2019 out of the it's box :) Uploaded edge. Looks good on 212x64 at least. 

**6ms** - Bit of jitter. Bad screenshot, was more an average of 6 according to the persistence mode
image

**32.5ms**
image

And inverted. also works
image

Also checked the PPM to make sure I didn't screw anything up there. It adjusts and I don't think it's anything I did but if you set 4ch or 5ch you stop getting adjustment above 38.5us. On 6+ Ch goes up to 40ms.. Doesn't go screwy or anything like SBUS did if you went too high.. Probably nothing to worry about :)
image

**Comment by pfeerick** [comment]
> Definitely a job for a good old logic analyser ;-) @rotorman wanna have a look at this?

Why use an analyser when you have an actual SBUS meter/decoder? :-P I just have had a busy few days, so just glad others have been able to follow this up ;)

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
@pfeerick anything missing from your point of view? It's good with me.

**Comment by pfeerick** [comment]
No, just hadn't gotten around to following up on it. TX12 with SBUS/PWM signal meter is working fine with this PR, so on top of Cliff's X9D+2019 tests above, in it goes ;)

**Pull request merged**
