### PR TITLE
feat: add precision setting for mix delay up & down

### LINKED ISSUE #5296: Higher precision delay up/dn
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The problem is certain types of racing need higher precision with delay up/dn. This is related to issue #4593 . 

### Describe the solution you'd like

Same solution as issue #4593 , but for delay up/dn.

### Describe alternatives you've considered

Global variables of drive modes could be used if math was able to be applied to them to get a higher precision value to be used for the delays. I haven't figured out how to multiply a percentage variable by another variable. It seems the global variables are just meant for simple comparison of value.

### Additional context

This is mainly for very fine grained throttle control with the Racemaster MT12 when drag racing, but might also be valuable for other types of racing.

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #5296

### CODE REVIEW

**Comment by elecpower** [comment]
Hi Phil suggestion for alternative GUI layout that moves the precision fields into the Delay Slow table.

Screenshot from 2024-07-22 08-16-40

Alternative
Screenshot from 2024-07-22 08-23-14

**Comment by elecpower** [comment]
Phil this will likely be an ugly merge with #5220

**Comment by philmoz** [comment]
> Hi Phil suggestion for alternative GUI layout that moves the precision fields into the Delay Slow table.

Done.

> Phil this will likely be an ugly merge with #5220

I expect so.

**Review by elecpower — APPROVED** [review]

**Comment by elecpower** [comment]
Tested in Companion and tx16s libsim reading settings

**Comment by pfeerick** [comment]
I'm pretty sure I passed grade 5 maths... something doesn't add up... :laughing: 1 & 3, 2 & 4 should be the same, no? The list matches what the values I entered on the TX, the dialog doesn't. `0.0` precision seems fine, `0.00` has the problem. Slow does not seem to be affected. Other than this gem, LGTM.

image

image

**Comment by philmoz** [comment]
> I'm pretty sure I passed grade 5 maths... something doesn't add up... 😆 1 & 3, 2 & 4 should be the same, no? The list matches what the values I entered on the TX, the dialog doesn't. `0.0` precision seems fine, `0.00` has the problem. Slow does not seem to be affected. Other than this gem, LGTM - T15 and TX12.

Incorrect setting for # of decimal places in companion - should be ok now.

**Review by pfeerick — APPROVED** [review]

**Pull request merged**
