### PR TITLE
Japanese radio translation 🇯🇵

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
`jp.h` based on #2006 (Kudos to @ToshihiroMakuuchi)

### CODE REVIEW

**Comment by ToshihiroMakuuchi** [comment]
@raphaelcoeffic 
I thought my inability to build properly was due to my branch and environment, so I had to recreate it. My apologies.
Thank you again for your PR to the branch and master. I look forward to the merge.

**Comment by raphaelcoeffic** [comment]
> I thought my inability to build properly was due to my branch and environment, so I had to recreate it. My apologies. Thank you again for your PR to the branch and master. I look forward to the merge.

You should be able to download now the GH builds directly from this PR, so you can check if everything is ok.

**Comment by pfeerick** [comment]
@ToshihiroMakuuchi Can you have a look at this once the build checks are complete - you will be able to download a pre-built firmware image from the `Checks` tab up the top (you may need to click on `Run tests and package firmware` next, and then the zip file will be down the bottom under "Artifacts" with the name "edgetx-firmware-merge").

**Comment by ToshihiroMakuuchi** [comment]
@pfeerick 
Sorry for the delay in contacting you. I am using Jumper T16.
If possible, it would be great if you could upload the firmware for the Jumper T16.

**Comment by pfeerick** [comment]
Here you go... no hurry ;)

I had to push some changes as Gyro is now IMU so if you can also look at those and make any necessary changes that would be great. If you want another build later just let me know. 

[t16_jp.zip](https://github.com/EdgeTX/edgetx/files/9225864/t16_jp.zip)

**Comment by ToshihiroMakuuchi** [comment]
Thank you. I will first try to install with this and check the Japanese display.

**Comment by ToshihiroMakuuchi** [comment]
@pfeerick
I was able to confirm the Japanese language display on Jumper T16.
Japanese-language display does not appear to have any serious problems.
If you don't mind, could you build Radiomaster TX16S and T-Lite as well? We are planning to ask Japanese users to help us.

**Comment by ToshihiroMakuuchi** [comment]
@pfeerick 
@raphaelcoeffic 
If you can provide a place and option for Japanese in VOICE LANGUAGE, we can prepare that as well.

**Comment by pfeerick** [comment]
I'll do a TX16S build soon. I'll have to get back to you on the T-Lite build as while it may build, I have this feeling it will be blank if it is anything like the CN/TW builds. 

For voices, there is the SD card pack repo at https://github.com/EdgeTX/edgetx-sdcard-sounds, should be basically able to copy `voices\en-US.csv` or `voices\en-GB.csv` (basically the same, just different phonetics) to `voices\jp.csv` and then change the translation column so it's correct. There will be some work needed here in the firmware to enable/use it, but that would be the next major chunk of translation that's needed.

**Comment by pfeerick** [comment]
Right, here are the T16 and TX16S builds as of the latest state of this branch/PR... T-Lite is not an option yet as it is blank where there should be JP characters! 😆 
[t16-jp.zip](https://github.com/EdgeTX/edgetx/files/9227845/t16-jp.zip)
[tx16-jp.zip](https://github.com/EdgeTX/edgetx/files/9227846/tx16-jp.zip)

**Comment by pfeerick** [comment]
@ToshihiroMakuuchi Are you happy with the initial state of this? If so, I'll merge it into the main firmware, and then we can revisit when as changes are needed.

**Comment by ToshihiroMakuuchi** [comment]
We have confirmed that some, but not all, kanji characters are not displayed.
Please let us fix jp.h again. Target about 5 hours later.

**Comment by pfeerick** [comment]
No problem. There are also couple of other PRs that will add or change some words or phrases, so expect to need to do some updates in a couple of weeks anyway.

**Comment by raphaelcoeffic** [comment]
> kanji characters are not displayed

@ToshihiroMakuuchi we need to regenerate the list of included kanji characters if you add new ones. We cannot possibly include them all ;-)

**Comment by pfeerick** [comment]
Superseded by #2185

**Pull request closed without merging**
