### PR TITLE
Make Ghost menu work with NV14 joystick trims

### PR DESCRIPTION
**Pull request by stefan73**
Enabled the ghost menu to work with the NV14 joystick trims like in lua (for non-touch luas). 
Changed layout to work with NV14.
Cleaned the code tn the NV14 key_driver.cpp

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@stefan73 first of all, thx a lot for your PR! As a side note: could you possibly make a `define` that corresponds to the feature and not to the hardware (for instance `TRIMS_AS_BUTTONS` instead of `PCBNV14`). The goal here is to make it "hardware independent", as we aim at better layer separation, the existing special cases for specific hardware will be removed everywhere possible and replaced with more generic definitions.

For `ifdefs` that depend on the screen format, please use something like (or similar):
```
#if LCD_W > LCD_H
```

Please note that as we move to LVGL, these defines will eventually go away as well and be replaced by dynamic layouts, or at least by some native LVGL mechanisms.

**Comment by stefan73** [comment]
@raphaelcoeffic No worries - happy to take coaching. And I will make some adaptations.
If we want to be really HW independent, we should also not put absolute coordinates. I can try to do that in the ghost UI code; this is just a few numbers here.

With the trims on the Nirvana, I might have an idea but I also need a hint then. Currently we use the trims as buttons whenever a lua script is running. Here we try to extend this to the ghost menu. There is another try to make the use of the trims configurable in the HW menu, so that they would always be buttons. Might be ok for quad flyers but not for planes.

How about using the trims as buttons whenever one is in a menu (incl lua)? - I cannot think of a usecase where one want to trim while configuring. It is ease to check whether a lua script is running. But how do I find out where the radio is in a menu? - Or asked inverse: How do I find out wether one of the mainscreens is active? - If so, one could push the complete handling into the board specific files. With the moves that you line out, this should happen anyways.

**Comment by gagarinlg** [comment]
I do not think there is currently a way to get an indication whether the radio is in a menu and this will not be automatically available with the new UI code.
If this is useful, it can be added. I think an extra issue for this, that is assigned to the lvgl project would be good, so we do not forget it.

**Comment by stefan73** [comment]
Did a change that should reflect the wishes.

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by pfeerick** [comment]
I think we should pull this into 2.6 also as GHOST will be pretty useless on the NV14 without this :grin:

**Pull request merged**
