### PR TITLE
fix(color): prevent recomputing curve points in NumberEdit() constructor

### LINKED ISSUE #2452: Custom curves aren't remembering their saved values
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When you set up a custom curve & come back to it after editing it, the curve doesn't remember the values that you have configured for it.
Instead, the curve points jump to random values & this messes up the custom curves... badly.

### Expected Behavior

Custom curves are supposed to recall the values that you have entered, when you come back to the curve editor.

### Steps To Reproduce

On your controller (in my case, my RadioMaster TX16S Max Edition)...
1.) Model Settings -> Curves.
2.) Pick a curve slot. Any curve slot.
3.) Set the curve type to "Custom".
4.) With the default 5-point curve (although this is applicable to any number of curve points), you set the curve points to any number of your choosing. Just as long as it differs from the values used in your "standard curves". EG Set Point 2's vertical axis to -27 & the horizontal axis to -42; Set Point 4's horizontal axis to 69 & its vertical axis to 42. Leave the endpoints where they are.
5.) Write those numbers down, so you can compare them later.
6.) Exit out of the curve editor. Then, come back to the same curve you just edited. If this bug isn't visible the first time around, repeat this step a couple of times & it should be apparent after the second time you repeat it.

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

Firmware for this is 2.8.0-RC2 although this bug, from what I understand, has been present since the U.I. rewrite & I have a hunch that it's similar to another custom curve issue that has since been fixed.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #2452

### CODE REVIEW

**Comment by pfeerick** [comment]
Hm... it seems I can still get this to repo even with this PR :(

**Comment by ZZ-Cat** [comment]
Yea, same here. I just tried this PR a few minutes ago on my RadioMaster, & my custom curves are still jumping to weird values that I didn't set.

**Comment by pfeerick** [comment]
And `simu` will do it thankfully... so you got no excuse :-P
https://user-images.githubusercontent.com/5500713/194299878-5077e869-d3d5-4921-a374-851cea5f8137.mp4

**Comment by raphaelcoeffic** [comment]
The underlying error here is actually that `NumberEdit` calls `setValue` directly from the constructor. When this happens with the `NumberEdit` that controls the number of points, the code tries to re-align / approximate the points to better compute an increased number of points.

The solution here is really: we should not be calling `setValue()` from within constructor. `update()` is the proper way. However, the main difference between both is that the value is not constrained within `[vmin ; vmax]`, which it is when calling `setValue()`.

**Comment by ZZ-Cat** [comment]
Right-oh, Raph. I just tested your latest commit on my RadioMaster, & it checks out. Custom curves are now working as their supposed to as far as keeping the values that I had set them to is concerned.

There is _one more_ thing about the curves, but I will save that for another issue for a later date.

Thanks for sorting this out. I love the work that you guys have put into this & made it amazing. =^/,..,^=

**Comment by pfeerick** [comment]
Rightyo, poked several other places and NumberEdit seems to be behaving itself, so hopefully *no other weird code* relied on this lunacy...

**Pull request merged**
