### PR TITLE
fix(ui) - LVGL conversion for telemetry.

### PR DESCRIPTION
**Pull request by philmoz**
Conversion to LVGL flex layout for telemetry pages.

For portrait layout, long strings like GPS are displayed in small font in order to fit.

Screen Shot 2023-01-21 at 12 19 23 pm

Screen Shot 2023-01-21 at 12 19 53 pm

Screen Shot 2023-01-21 at 12 20 06 pm

Screen Shot 2023-01-21 at 12 20 28 pm

Screen Shot 2023-01-21 at 12 21 13 pm

Screen Shot 2023-01-21 at 12 23 01 pm

Screen Shot 2023-01-21 at 12 24 07 pm

### CODE REVIEW

**Comment by eshifri** [comment]
AFAIK for everything but FrSky alarms are not based on RSSI but on some other sensors (e.g. for FlySky it is Sgnl), so maybe different name would be better.

**Comment by pfeerick** [comment]
> AFAIK for everything but FrSky alarms are not based on RSSI but on some other sensors (e.g. for FlySky it is Sgnl), so maybe different name would be better.

True, but it's not a static label - it changes with the protocol - `getRssiLabel()`

**Comment by JimB40** [comment]
1. Do we need sensor ID on the list?
2. As I can see sensor lost is indicated by text color change to WARNING. 
How incoming telemetry data trasmission is indicated?

**Comment by philmoz** [comment]
>   How incoming telemetry data trasmission is indicated?

Do you mean the blue dot to the left of the value?
Screen Shot 2023-01-26 at 5 13 33 pm

**Comment by eshifri** [comment]
IMO sensor ID is VERY nice to have for development/debugging. It may be convenient for flying you have several similar sensors.

**Comment by JimB40** [comment]
> Do you mean the blue dot to the left of the value?
Ok so it's like before. Just I'd v-center and h-center in column between sensor number and value.

**Comment by JimB40** [comment]
> IMO sensor ID is VERY nice to have for development/debugging. It may be convenient for flying you have several similar sensors.

Hmm so we can have "dev-mode showing that". Without ID column GPS coords will fit nicely in horizontal
What is purpose to see in overview list that AccX & A3 and all the rest is 224? 
Is it useful anyhow for user (except developer) like this ID is used elswhere in OS as input data?

**Comment by eshifri** [comment]
I think that dev-mode might be sufficient. Especially if it can be configurable rather than compile-time option.

**Comment by JimB40** [comment]
@philmoz one more thing
Sensors list is most used feature in this tab. RC Link alert (RSSI) is set & forget. So I'd switch group order to (from top to bottom):
1. Sensors List
2. RC Link Alerts
3. Variometer

**Comment by pfeerick** [comment]
> Hmm so we can have "dev-mode showing that". 

Not so much a "dev" mode, as end users will need that... more perhaps another checkbox like the "Ignore Instances" one but this one would be "Show Sensor ID" or similar... if we can update the table on the fly / rebuild the page if necessary (i.e. not need the user to leave the page to see the change).

**Comment by JimB40** [comment]
I bet 5% users will need it but if so we already have layout template in Mixes
Screenshot 2023-01-27 at 15 12 33
So place "Show Sensor ID" below sensors list and display detailed data with TINSIZE right aligned above sensor value.
If needed switch can be "Show Sensor Details" and data can be Type / ID / Instance (if set)

**Comment by pfeerick** [comment]
@philmoz Can you take the below onboard as a future enhancement to this PR? Another thought might be to double-line the GPS co-oords so that the font size stays the same. 

> we already have layout template in Mixes Screenshot 2023-01-27 at 15 12 33 So place "Show Sensor ID" below sensors list and display detailed data with TINYSIZE right aligned above sensor value. If needed,  switch can be "Show Sensor Details" and data can be Type / ID / Instance (if set)

**Comment by eshifri** [comment]
May I ask why class SensorValueLabel is derived from StaticText - not DynamicText?

**Comment by ParkerEde** [comment]
@philmoz 
Even if this has already been merged here, could we take this opportunity to ensure that when you press the "Start sensor search" button, the focus remains on this button, so that you can also stop the sensor search again straight away?
It is also confusing that when you delete a sensor, the focus jumps up in the list. It could also jump to the previous entry instead, then you don't have to scroll unnecessarily while you maintain / clean up your sensor data.

**Comment by ParkerEde** [comment]
Addendum: The Start Sensor Search button loses focus as soon as a new sensor is found.

**Pull request merged**
