### PR TITLE
feat(radio): Delay warnings until after splash screen finished

### LINKED ISSUE #3882: Splash screen timing overidden by stick/switch position warnings
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Splash screen timing is overidden by stick & switch position warning announcement and reverts to current model screen.

### Expected Behavior

When splash screen set time is finished, stick and switch position warnings are announced with current model screen displayed.

### Steps To Reproduce

1. Power up.
2. Splash screen comes on.
3. If any stick or switch is out of preset position, reverts to model screen after approx 2 secs and warning is announced, even if max splash screen time is selected.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

2.10.0 - nightly 30-07-23

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3882 

The startup code needs some attention and cleanup; but this should work for now.

Tested on TX16S and X7S.

### CODE REVIEW

**Comment by Kevltan** [comment]
Please do this mod to the X12S👌😊

**Comment by pfeerick** [comment]
?

It will apply to all radios once merged.

**Comment by Kevltan** [comment]
Now working fine on the X12S radio😊👍👌

**Comment by philmoz** [comment]
Any chance this could get merged soon?

I have some additional cleanup / fixes for the startup code that depends on these changes.

**Comment by pfeerick** [comment]
Sounds good to me... TX16S started up ok and Raphael hasn't showed up with complaints 🤭

**Pull request merged**
