### PR TITLE
chore(cpn): update to Qt 5.15.2 and rework application packaging

### PR DESCRIPTION
**Pull request by elecpower**
Summary of changes:
- upgrade to Qt 5.15.2 (last to support 32 bit Win) and minimise qt depreciated warnings
- replace linuxdeployqt with linuxdeploy and linuxdeploy-plugin-qt for new AppImage structure
- windeployqt run in debug mode as a workaround for a bug (Qt appears to have no intention of fixing)
- cmake use AUTOMOC and AUTOUIC for qt, new macros and housekeeping
- update github workflows
- update packaging of dfu-util and libusb sourcing to latest versions
- update packaging of openssl sourcing version 1.1.1 (Qt removed the openssl 1.1.1 tools!!!)

### CODE REVIEW

**Comment by philmoz** [comment]
Are you sure OpenSSL 1.1.1 is necessary on MacOS.

I have no problems building or running Companion using the home-brew Qt5 install and openssl 3 (on Sonoma, both Intel and Apple Silicon).

I also tried on a MacOS 11 VM with the aqt install of Qt 5.15.2 and without openssl 1.1.1 (just 3).
Companion build and runs and I can build the MacOS DMG package as well.
The resulting DMG app works fine on a vanilla MacOS 12 VM.

In all cases I can download all the updates within Companion so the network connection is working.

**Comment by pfeerick** [comment]
FWIW, it does say 1.1.1 _**or later**_

> From Qt version 5.15 onward, the officially supported version for OpenSSL is 1.1.1 or later.
>Qt version 5.15.1 onward is also compatible with OpenSSL 3.

https://doc.qt.io/qt-5/ssl.html

And OpenSSL 3.x seems to be available in a Win32 flavor at https://slproweb.com/products/Win32OpenSSL.html

So given Qt 5.15.2 is in use, it seems like OpenSSL 3.x should be ok. Unless this was one of the issues Neil was trying to work through the other day... (says it's compatible, but in reality, it isn't?).

**Comment by elecpower** [comment]
Thanks @pfeerick @philmoz
Back in Feb 23 I cannot recollect any reference to OpenSSL V3 or 1.1.1 or later in the Qt docs and I read lots.
And also remember we have had users reporting ssl errors when trying to download updates and ssl version incompatibility has been a contributor.
With this new info I will incorporate V3 into the installers and we can just monitor for issues.

In the last macos build a new error has raised its ugly head in relation to installing SDL2. Any ideas macos gurus?

**Comment by philmoz** [comment]
Looks like the 'xcode-version' needs to  be updated in macosx_cpn.yml.

**Comment by philmoz** [comment]
From my testing you also need these lines in companion/src/CMakeLists.txt
```
include(FindDfuutil)
include(FindLibusb1)
```

And this in cmake/FindLibusb1.cmake (in the find_library call):
```
    libusb-1.0.dylib
```

**Comment by elecpower** [comment]
> And also remember we have had users reporting ssl errors when trying to download updates and ssl version incompatibility has been a contributor.

But thinking further that would be for Qt 5.12.9 so hopefully all will be good with 5.15.2

**Comment by elecpower** [comment]
From the macos build

> Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.

Should we be upgrading?

**Comment by philmoz** [comment]
> From the macos build
> 
> > Warning: You are using macOS 11.
> > We (and Apple) do not provide support for this old version.
> 
> Should we be upgrading?

I'd hold off on that for a while - I have not been able to get the 'package'  build to successfully create a DMG image on later versions of MacOS.

**Comment by philmoz** [comment]
> In the last macos build a new error has raised its ugly head in relation to installing SDL2. Any ideas macos gurus?

I tried changing the xcode-version to 13.2.1 in macosx_cpn.yml and running the MacOS Companion build in my fork.

It successfully completed and I can run the resulting Companion image on my Mac.

However the minimum supported MacOS version is now 11.7 - it will no longer run on anything earlier.

I think we're stuck here - we can't build with the old Xcode version anymore so looks like we have to drop support for MacOS 10.

**Comment by philmoz** [comment]
With a bit of tweaking the MacOS build works and is still compatible with MacOS 10.15 as the minimum version.

**Comment by elecpower** [comment]
@pfeerick

MSYS2 Win32 builds for me.

Installers are outstanding:
- Linux AppImage packaging seems complete
- Win32 and 64 packages missing SDL2 (just a path issue)
- Mac package needs more work (not my area of expertise) so need help please

After a bit more testing by some others across the OSes, I recommend merging so we can recommence adding other Companion PRs and I can get to work on Companion ADC refactor as the nightlies are currently broken.

Openssl v3 compatibility needs more testing since we are using pre-built binaries and there are still reports of issues with Qt 5.15.

Work can continue on packaging the installers.

**Comment by philmoz** [comment]
> * Mac package needs more work (not my area of expertise) so need help please

Any details on what needs to be done?

**Comment by elecpower** [comment]
@philmoz all the dependencies are found which is good news.
Need to copy the files to the appropriate packing folders and perform any registering/bundling/etc so they get deployed by the installer.
Need to ensure our files get loaded at runtime irrespective of other versions installed.
For Win we put all the dependencies in the same directory as the companion exe.

**Comment by philmoz** [comment]
> Need to copy the files to the appropriate packing folders and perform any registering/bundling/etc so they get deployed by the installer. Need to ensure our files get loaded at runtime irrespective of other versions installed.

That's already handled by the cmake 'fixup_bundle' call.

**Comment by elecpower** [comment]
> Time for the draft bandaid to get ripped off?

Brace yourself and bite down on that stick

**Comment by pfeerick** [comment]
@mha1 If you want your ms PR to be merged, you know what to do 🤣

**Comment by elecpower** [comment]
@pfeerick don't forget you need to merge https://github.com/EdgeTX/build-edgetx/pull/16 and reset the docker image reference to latest in linux_cpn.yml

**Comment by pfeerick** [comment]
Win64 (Windows 11 23H2): I uninstalled, and then deleted `C:\Program Files\EdgeTX\Companion 2.10`, and then installed latest build. Started ok. When I try Help -> Check for updates or File -> Download Components I get around a dozen of these popups in succession...

image

And this in the debug log
```
[W] unknown():0 - [qt.network.ssl] QSslSocket::connectToHostEncrypted: TLS initialization failed
```

**Comment by elecpower** [comment]
Don't believe what you read! So it's back to bundling openssl v1.1.1.😖

**Comment by pfeerick** [comment]
Yeah, I was just updating this to say... 

If I uninstall this build, it leaves these two files behind... 

image

vs an build from #4220 

image

So, just for giggles, I renamed the files first... 

image

... then replaced them with the proper v1.1 files... now it works. So dunno how it's compatible with openssl 3 🙃

**Comment by pfeerick** [comment]
OFFS!

> OpenSSL 3 is supported with Qt 5.15.13 onwards. If you are using the open-source version, this should be available 9 March 2024

😖 😡 💥 

https://forum.qt.io/post/774709

**Comment by elecpower** [comment]
My interpretation of the discussion is that source compatible but no mention of pre compiled binaries.

**Comment by philmoz** [comment]
> My interpretation of the discussion is that source compatible but no mention of pre compiled binaries.

Maybe that's why MacOS works ok.

**Comment by elecpower** [comment]
> Yeah, I was just updating this to say...
> 
> If I uninstall this build, it leaves these two files behind...
> 
> image
> 
> vs an build from #4220
> 
> image

Uninstalling all  files is on the todo list

**Comment by elecpower** [comment]
> @elecpower So what is the status of this PR then? Figure out bundling of openssl 1.1.1? Is it only a Windows problem where we could keep the 2 DLLs in the repo to be packaged as needed? Just checking where things are at now.

Just dropped a commit that hopefully fixes. Let's see how the Checks go.

**Comment by elecpower** [comment]
Spoke too soon. Must have made another change after I tested. Bad boy.

**Comment by pfeerick** [comment]
Roger that. I was also going to suggest maybe we could keep a copy of the 32bit and 64bit installer from https://slproweb.com/products/Win32OpenSSL.html handy if needed as that has the ready-to-go libraries. 

lol... ouch!

**Comment by elecpower** [comment]
> Roger that. I was also going to suggest maybe we could keep a copy of the 32bit and 64bit installer from https://slproweb.com/products/Win32OpenSSL.html handy if needed as that has the ready-to-go libraries.
> 
> lol... ouch!

Found that one too when trolling. The Lite installers would be sufficent for our needs.
I have just grabbed and uploaded the 1.1.1 versions from 2.9.1 installers though they are 1.1.1v and 1.1.1q. Good enough to test the clients.

**Comment by elecpower** [comment]
@pfeerick The latest action builds appear to be okay

**Comment by pfeerick** [comment]
Yup, LGTM on both Win64 and Linux... no issues with QTNetwork/OpenSSL. I've just merged the builder PR, and will merge this shortly.

**Pull request merged**
