### PR TITLE
Re enable newlib nano

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
But move the BinAllocator structures into SDRAM, in case available.

### CODE REVIEW

**Comment by rotorman** [comment]
Test result of 212559eb with RM TX16S hardware:
compiled under Windows 10, using GNU Arm Toolchain 10 2020-q4-major, running with Segger Ozone, via SWD-header. Unfortunately HardFaults while displaying EdgeTX logo on power-up when -DNANO=YES

When built with -DNANO=NO, runs on radio. I see no HardFault, even with full screen LUA (Yaapu) running.

**Comment by raphaelcoeffic** [comment]
@rotorman @pfeerick I moved things around, with the following changes:

- COLORLCD: `BIN_ALLOCATOR` is disabled for targets.
- COLORLCD: all data sections have been moved to SRAM, except for the stacks (main & task stacks).
- newlib nano is used on all targets (as before).
- `BIN_ALLOCATOR` alignment fix by @rotorman (tweaked values to get less mem usage).

From what I have seen, I think the EM on shutdown with LUA is not related to the custom allocator (`BIN_ALLOCATOR`), as it will still show this behaviour with `BIN_ALLOCATOR` disabled. That issue must be somewhere else.

**Comment by raphaelcoeffic** [comment]
Resolves #109 and #104.

**Comment by pfeerick** [comment]
Will test tomorrow. I did try an earlier build (think it was commit 4b3de91) on both the TX16S and the X9D+ and both booted and seemed their normal selves. T-Lite gets a pass for today as I'll need it tomorrow morning, then it gets tested also.

**Comment by rotorman** [comment]
Tested ed5f472a running on RM TX16S, hooked up via hw-debugger at SWD pins to Segger Ozone.

Result - all good :) no HardFaults (except boardOff() that PR #119 fixes. This is also not visible to end-user, only to hw-debugger).

Second test with -DCLI=YES (#109) also positive, closing #109.

**Comment by raphaelcoeffic** [comment]
Tested ok on:
- [ ] X9-lite
- [ ] T-lite
- [ ] T12

**Comment by pfeerick** [comment]
Tested at https://github.com/EdgeTX/edgetx/pull/113/commits/20a4e4444d4984364e24e653d0adb01fe2700dfc,

Boots ok on:
* TX16S
* X9D+
* T-Lite

**Pull request merged**
