### PR TITLE
feat(cpn): Extend Log Viewer x-axis time format to show milliseconds

### PR DESCRIPTION
**Pull request by mha1**
Summary of changes:
- extends log viewer's x-axis time format to show milliseconds

image

### CODE REVIEW

**Comment by mha1** [comment]
why the "don't merge" label?

**Comment by pfeerick** [comment]
Because you're touching companion :-P

**Comment by mha1** [comment]
Now that you mention it I vaguely remember Neil working on some stuff ...

**Comment by elecpower** [comment]
Sorry Michael but some bad news in that https://github.com/EdgeTX/edgetx/pull/4270 breaks this one. qCustomplot upgrade required changes here

**Comment by mha1** [comment]
Don't worry, I'll wait for your PR to be merged and try again

**Comment by pfeerick** [comment]
@mha1 You should be right to rebase and try again

**Comment by mha1** [comment]
> @mha1 You should be right to rebase and/or try again

rebase done

**Pull request merged**
