### PR TITLE
Jump to channel  monitor from any model page.

### PR DESCRIPTION
**Pull request by eshifri**
This is a modified solution for #1731 

Summary of changes:
New button "Open Channel Monitor" is added to ALL Model pages in the title bar.
It takes user to channel Monitor.
The same can be achieved with short press on "TELEM" button.
RTN takes user back to the edited Model page.

This is cleaner than #1731

### CODE REVIEW

**Comment by pfeerick** [comment]
Oh you sneaky bugger... I just know Robert is going find something to grumble about that... but this works for now :-P. Absolutely perfect use of that space... which is currently quite wasted, and keeps it always visible so you don't need to scroll for it. And with #1745 stacked on top of that, it should work quite nicely keeping focus when you view and come back. I think the only change likely needed for this will to change from TELEM to MDL, as it has not purpose once you're in the model setup area... so should be safe from ongoing discussion on what to assign to what globally. 

snapshot_10

**Comment by JimB40** [comment]
Hehe I won't. I'll just redesign all UI stating from 2.8 ;)

**Comment by pfeerick** [comment]
> I'll just redesign all UI starting from 2.8 ;)

Yup, once LVGL is securely in place... redesign can start... first order of business will be to relegate the timers to their own screen... which will close to halve the length of the main model setup page. Basically any group of settings can be relegated it's own screen. But it will all be a bit dicey as there are a whole bunch of UI things we want to happen in 2.8... so some prioritization will be needed, as what we already want for 2.8 is probably too much.

**Comment by JimB40** [comment]
Yep reading my mind. Timers should have separate tab or at least should be hidden when OFF

**Comment by pfeerick** [comment]
I'll draw you attention back to this concept art for a new UI... which predates EdgeTX :grin: I'd have no complaints using this UI :wink: https://discord.com/channels/839849772864503828/848236370169298945/895721270392545340

**Review by pfeerick — APPROVED** [review]

**Pull request merged**
