### PR TITLE
Issue #817

### PR DESCRIPTION
**Pull request by jfrickmann**
Added a Lua function that can change the value of a sticky logical switch.

### CODE REVIEW

**Comment by jfrickmann** [comment]
I just realized that this PR has a problem with thread safety. Lua running on the GUI thread is messing with mixer thread data 😨 
@rotorman, please chime in if you have any good advice here 😎

**Comment by rotorman** [comment]
FreeRTOS offers numerous thread-safe functions to pass data between the threads. Here, for example `xQueueSend()` and `xQueueReceive()` could be used, abstracted through https://github.com/EdgeTX/edgetx/blob/main/radio/src/rtos.h, to transfer a struct of id and value between the sending LUA thread to mixer thread. See Sec. 3.16 and Sec. 3.22 in https://freertos.org/fr-content-src/uploads/2018/07/FreeRTOS_Reference_Manual_V10.0.0.pdf
Please let me know if this helps you further.

**Comment by jfrickmann** [comment]
Thanks @rotorman !  I grepped for `xQueueSend()` and `xQueueReceive()`, but I only see them inside the thirdparty folder. Do we use these anywhere else, or is there no need for syncing between threads elsewhere in EdgeTX?
I think that this could also be used for sending logical switches to Lua, as e.g. special functions running Lua often run twice on an edge LS because GUI and Lua runs at ~20 Hz and LS only at 10 Hz. So we could have `logicalSwitchesTimerTick()` send a bitmask of LS values every time it runs, and Lua read that every time it runs. That way, one edge triggers one run of the special function script, as long as Lua can keep up.

**Comment by rotorman** [comment]
Presently, the code uses FreeRTOS semaphores and task notifications, both that do not allow arbitrary data to be passed. Using queue's in FreeRTOS is computationally more expensive, but with a queue, you can pass arbitrary data, such as structs. On the other hand, if you just have one value (32-bit number) to send, task notifications are quicker.

**Comment by jfrickmann** [comment]
Looking at the use of TaskNotify calls, I can see that it is used two times for scheduling the mixer. I am definitely not qualified to start messing with that, and I don't think Raphael would be happy if I did 😀 
Maybe a more low rent solution with a few volatile words of shared memory. 

**As far as I understand, the compiler will not rearrange accesses to volatiles, right?**

- We have 64 LSs, and we can switch them on or off. 
- So two words for "turn on" and two words for "turn off". 
- Plus two bytes to acknowledge reading/writing data.

How about the following protocol:

1. Lua will read Mixer's byte, and if clear, then it will write the four words of data and set its own byte.
2. Mixer will check Lua's byte, and if it is set, it will read the four words and set its own byte.
3. Lua will check Mixers byte, and if set, clear its own byte.
4. Mixer will check Lua's byte, and if clear, also clear its own byte.
5. Go to 1.

Mixer will start at 2 or 4 depending on its own byte state, and based on the bit words, it will turn sticky switches on or off as requested when processing the switches in `logicalSwitchesTimerTick()`.

Lua will start at 1 or 3 above, depending on its own byte state. Lua will keep its own copy of the words and set bits when the `setStickySwitch(...)` function is called. Obviously the ON and OFF bits are mutually exclusive, and we should handle the case where someone flips switches too fast. The simplest solution would be to simply cancel the ON bit if followed by OFF instead of setting OFF etc. Lua will clear the internal words every time it writes them out in step 1 above.

**Comment by rotorman** [comment]
I would favor using what FreeRTOS offers, instead of implementing a shared volatile variable.

In case only a single LS is to be turned on or off at any moment, TaskNotifiy would suffice, as selecting a LS out of 64 can be achieved with 6 bits only, with remaining bits (32-6=26) free for state and further optional info/data.
If the state is only binary, then we only need 7 bits out of 32 to control 64 LSs on/off.

@raphaelcoeffic what is your take/suggestion to this?

**Comment by raphaelcoeffic** [comment]
We definitely need a mechanism to achieve a couple of things:
- know when it is ok or not to access certain memory structures used by the mixer,
- in a way that never blocks the mixer.

That being clear, we already have a start, which is a mutex locked when the mixer is running. But IMHO does not achieve what we want, so that we need something better. I'll spend some thoughts on it ASAP.

**Comment by gagarinlg** [comment]
Are atomics implemented? If one variable is enough, that could be a solution.

**Comment by raphaelcoeffic** [comment]
> Are atomics implemented? If one variable is enough, that could be a solution.

Not sure about `atomic` and GCC-ARM. That needs some checking.

**Comment by gagarinlg** [comment]
> Not sure about atomic and GCC-ARM. That needs some checking
We uae std::atomic on Cortex-A with gcc, but I never checked for Cortex-M.

**Comment by jfrickmann** [comment]
I see that the LDREX and STREX instructions are used with inline asm both inside FreeRTOS and in sky9x, e.g. here: https://github.com/EdgeTX/edgetx/blob/493c90d792f7815e89608fb65aa2d426e06485f8/radio/src/targets/sky9x/core_cm3.c#L419-L423

Maybe we can implement a bit array with thread safe functions?
```
void SetBit(bitArray, idx)
void ClearBit(bitArray, idx)
BitArray ReadAndClear(bitArray)
```
When Lua wants to set a switch it calls `SetBit` and when `logicalSwitchesTimerTick()` runs, it calls `ReadAndClear`, and then it flips the sticky switches as it processes everything?

**Comment by jfrickmann** [comment]
I looked into the mutex that Raphael mentioned, and found the following in tasks.cpp:
```
RTOS_MUTEX_HANDLE mixerMutex;
RTOS_CREATE_MUTEX(mixerMutex);
RTOS_LOCK_MUTEX(mixerMutex);
RTOS_UNLOCK_MUTEX(mixerMutex);
```
The number of possibilities is rather overwhelming, and this PR has certainly gotten way more involved than I had imagined. So I will just close it and wait for Raphael to do the thinking. Maybe we can continue the discussion on Discord #dev 😎

**Comment by jfrickmann** [comment]
I reopened this one, because I have a new implementation that I would like you to review @raphaelcoeffic @rotorman @pfeerick

**Comment by jfrickmann** [comment]
Never mind, I will create a new PR

**Pull request closed without merging**
