### PR TITLE
feat(lua): deliver EVT_TOUCH_RELEASE event

### LINKED ISSUE #5585: Propagate TE_RELEASED (touch event) to LUA widgets
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

To emulate a momentary button as a touch button (libGUI), this gui element needs to receive the pressed and the released event. But the TE_RELEASED event ist not converted to a LUA event.

### Describe the solution you'd like

In order to not disturb any existing event logic (e.g. tap events) the TE_RELEASED should be propagated as a new event code to LUA. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wimalopaan**
first try to solve #5585 

Resolves #5585

### CODE REVIEW

**Comment by wimalopaan** [comment]
Looks like the LUA constant  EVT_TOUCH_RELEASE isn't generated (from keys.h???).

**Comment by philmoz** [comment]
radio/src/lua/api_general.cpp - section starting at line 3194

**Comment by wimalopaan** [comment]
LUA constant EVT_TOUCH_RELEASE added

**Comment by wimalopaan** [comment]
@pfeerick  I think this requires also some minor changes in `libGUI` ?

**Comment by pfeerick** [comment]
Possibly. That will be a seperate PR though - source is here
- https://github.com/EdgeTX/edgetx-sdcard/tree/master/sdcard/c480x272/WIDGETS/LibGUI
- https://github.com/EdgeTX/edgetx-sdcard/tree/master/sdcard/c480x320/WIDGETS/LibGUI

@philmoz Happy with the state of this PR?

**Comment by wimalopaan** [comment]
> Possibly. That will be a seperate PR though - source is here
> 
> * https://github.com/EdgeTX/edgetx-sdcard/tree/master/sdcard/c480x272/WIDGETS/LibGUI
> * https://github.com/EdgeTX/edgetx-sdcard/tree/master/sdcard/c480x320/WIDGETS/LibGUI

Ok, I'll make a PR to implement a `momentaryButton`.

**Comment by philmoz** [comment]
EVENT_TOUCH_RELEASE and _MSK_KEY_RELEASE are not needed.

The existing EVENT_TOUCH_BREAK and _MSK_KEY_BREAK values should be covering the touch release state; but the code is not working.

I suggest removing EVENT_TOUCH_RELEASE and using EVENT_TOUCH_BREAK in the event_cb() function and also delete these non-functional lines from the LuaEventHandler::onClicked() function.
```C
    } else {
      es->event = EVT_TOUCH_BREAK;
```

**Comment by wimalopaan** [comment]
> EVENT_TOUCH_RELEASE and _MSK_KEY_RELEASE are not needed.
> 
> The existing EVENT_TOUCH_BREAK and _MSK_KEY_BREAK values should be covering the touch release state; but the code is not working.
> 
> I suggest removing EVENT_TOUCH_RELEASE and using EVENT_TOUCH_BREAK in the event_cb() function and also delete these non-functional lines from the LuaEventHandler::onClicked() function.
> 
> ```c
>     } else {
>       es->event = EVT_TOUCH_BREAK;
> ```

Thanks, I'll have a look at that.

**Comment by pfeerick** [comment]
LGTM on TX16S - EventDemo and LibGUI Demos both appear to be be fully functional still. Thanks for the complimentary LibGUI PR, that looks good also.

**Pull request merged**
