### PR TITLE
NV14 UI fine tuning, resolve #600

### LINKED ISSUE #600: NV14 UI Problem
There are a lot of problems in NV14 UI, because the screen orientation is quite different with other support color radios.

Fix includes:
- protocol selector, used next line for sub-protocol
- diagnostic screen
- more layouts: 1+2, 1x2, 1x4
- better implementation of CN/TW date representation
- ..... what more, please comment.

**General information**
 - EdgeTX main nigntly
 - Hardware Flysky NV14

### PR DESCRIPTION
**Pull request by richardclli**
Current UI has a lot of problem for NV14, narrow screen portfolio, trying to make thing better with some fine tuning.

### CODE REVIEW

**Comment by richardclli** [comment]
If all tests success, will stop at this point.

**Comment by pfeerick** [comment]
*Argh! Too many tabs open syndrome... switched the computer off for the night before pressing the 'Comment' button!* 🤦

This looks great Richard! You've already fixed up some of the things I was going to start looking at (top bar icon spacing and overall size), and closed this before I saw the USB icon was under the sound icon (and also noticed the SD logging dot was not visible), so I've done a PR for that and used the same style. I also moved all the other top bar items to constants also, so there is nothing in topbar that is hard-coded to the screen width any more. https://github.com/EdgeTX/edgetx/pull/607

screen-2000-03-18-014029

**Comment by JimB40** [comment]
@richardclli let's sync it with #372. Most of widgets layouts are barely usable on NV14 except 1 column ones

**Comment by JimB40** [comment]
#372 is closed so I discuss it @  #624

**Pull request merged**
