### PR TITLE
Implement Jump to Curve Edit from input and mixer screens

### PR DESCRIPTION
**Pull request by kevinkoenig**
This PR implements a jump to curve edit screen from long-press of curve Choice() on the input screen and mixer screen.  I implemented a ChoiceEx which handles long-press and passes it back to the creator to take action.  This ideally should be in libopenui

### CODE REVIEW

**Comment by kevinkoenig** [comment]
pushed commit to add longpress on curve in mixes and input screens to launch edit of curve.

**Comment by rotorman** [comment]
Plz see for EdgeTX boiler-plate: https://github.com/EdgeTX/edgetx/blob/main/tools/copyright-header.txt

**Review by pfeerick — APPROVED** [review]
Oh, very nice... so a long ENT press on the curve Choice in either Inputs or Mixes screen brings up the curve screen, and create a standard blank one if it doesn't already exist. On the inputs screen, it correctly updates the curve shown there when you jump back out of editing the curve. Works great! :) 

TX16S

**Comment by pfeerick** [comment]
> This ideally should be in libopenui
Are you thinking of something somewhat similar to this? https://github.com/EdgeTX/libopenui/pull/8

As that also made it so long touch would trigger the 'long' press functionality...

**Comment by jmxp69** [comment]
I installed the bin from the changes menu on this issue. I have 2.5.0 71ddaaf and long press on the curve in inputs does not go to the curve edit screen.

**Comment by pfeerick** [comment]
Long press of ENT? As long touch won't work, hence my comment above. https://youtu.be/rBrCzkqXjlM

**Comment by jmxp69** [comment]
I see, long press of enter does switch to the curve editor. I was long pressing the curve list box itself. I thought the fix was to long press the curve list box but the scroll wheel does work.

**Comment by kevinkoenig** [comment]
> I see, long press of enter does switch to the curve editor. I was long pressing the curve list box itself. I thought the fix was to long press the curve list box but the scroll wheel does work.

I just pushed the fix to make touch work also.

**Pull request merged**
