### PR TITLE
handle events on the outputs screen (#1652)

### LINKED ISSUE #1652: TX16S OUTPUTS Emergency Mode
In OUTPUTS if you try to set channels for the negative field (-100) you can change it up (+/-) but then it jumps to the name field and appear any character not entered for you and it crash in either the negative field (-100) or name field area entering in Emergency mode or blocking transmiter so you can't turn off so must remove batteries in this last case.

Expected behavior
Change data as usual in other vertions.

General information
Edgetx 2.7
Edgetx-firmware-nightly-tx16s-2929f1a
Radiomaster TX16S
IMG_20220302_204257
IMG_20220302_204306
IMG_20220302_204318

### PR DESCRIPTION
**Pull request by eshifri**
Fixes #1652 

Summary of changes: move call to Windows::checkEvents() to after update() call.
This fixies erratic behavior of the rotary selector on the outputs screen.
Maybe fixies  #1639 as well, but I was never able to reproduce this one.

### CODE REVIEW

**Comment by pfeerick** [comment]
I have to admit I've not been able to directly trigger #1639 directly either, only indirectly via this loss of focus when using touch only, so I guess we'll find out! :)

**Comment by pfeerick** [comment]
Unfortunately, testing this on TX16S hardware is indicating this is not fixing it. And, which you didn't want to know, doing bisect testing shows that #1652 is directly related to this commit, thus stems from #1526. And even more annoyingly, it can't be repo'ed on simu (although I did get a segfault when altering the subtrim at one point, which may or may not be related). 

```
c04a716bce593538f6820ab7e780e7faf506f7e0 is the first bad commit
commit c04a716bce593538f6820ab7e780e7faf506f7e0
Author: eshifri <46511024+eshifri@users.noreply.github.com>
Date:   Thu Feb 10 16:23:42 2022 -0800

    feat: Show channel change direction in the output screen via text color (#1526)
    
    chore: Remove COPROCESSOR
    
    * Show channel direction on the output screens (#1385)
    
    * minor cleanup

 radio/src/gui/colorlcd/model_outputs.cpp | 233 +++++++++++++++++++------------
 1 file changed, 140 insertions(+), 93 deletions(-)
 ```

Ok, I think I've pinned down the real culprit... wanna tell me why you're re-building the entire page every time there is an change in value, rather than just invalidating the screen? Which btw isn't needed since this is interactive form, not overview page. 

Completely removing this override to fixes both the rotenc and touch aspects of #1652 ;)

image

**Comment by eshifri** [comment]
invalidate() does not have any effect on this screen.

**Comment by pfeerick** [comment]
I suggest you re-examine the line numbers... this incorrectly overriding in `OutputEditWindow`, NOT `OutputLineButton`, which is where the line colour change is happening (which _does_ use invalidate() btw). You are rebuilding the Edit Window every time the min channel value is updated! Removing that code will not have any effect on the ModelOutputsPage overview - as the 'buttons' are correctly updating themselves as needed.

**Comment by eshifri** [comment]
The color is changed in both screens: for the button and for the static text in the edit window.
invalidate() works for the button.
For StaticText there is no way to change the color of the text - that is why I went for rebuilding the window.
Anyway, the new commit changes the background color and does not touch the whole window.
Maybe this looks better as well. :-)

**Comment by pfeerick** [comment]
I'll give it a try soon, but that looks like it should be fine.  Yeah, updating the UI like that is a big no-no, as it broke the connection for the touch screen keyboard to the UI controls since they were destroyed while it was still active, plus naturally all the other controls lost input focus. Because I'm TAER order, and throttle was at min, naturally min would cause stuff to break whenever it's value as changed, but max would the the same I guess if the throttle was up instead.

**Comment by eshifri** [comment]
Oh, now I understand what was going on.
I think we are missing an API to change the color of the text dynamically based on vents.
We may add setLcdFlags() to Window class or add lcfFlags to setText().

**Review by pfeerick — APPROVED** [review]
If you mean an event driven way to have changes to text updated, then most likely, but I wouldn't worry about making any changes to that until LVGL overhaul is done, which is now looking like it will be in 2.8. We'll then be able to reassess what LVGL has brought to the table, and any other stuff that would be good to have. 

This is working perfectly now! :)

**Pull request merged**
