### PR TITLE
Revised Logical Switches layout

### PR DESCRIPTION
**Pull request by philmoz**
Summary of changes:

This PR changes the logical switch page with the same style of changes as the special/global functions page in PR 2992 .
- Use LVGL flex layout for the list and edit views
- Fixed height for buttons
- Move switch name into the switch button so the entire row acts as a button
- Group unused switches in rows where possible
- Make button behaviour consistent by always opening pop up menu
- Remember selected button and reselect after edit.

### CODE REVIEW

**Comment by JimB40** [comment]
screen-shots?

**Comment by philmoz** [comment]
Screen Shot 2023-01-12 at 7 38 52 pm

Screen Shot 2023-01-12 at 7 39 09 pm

**Comment by JimB40** [comment]
Okay. Here I will instist to fit list item's data in one line.
Logical Switches are often configured in groups so it's very important to see as much as possible how they are activated.

LS_List

To my check on whiteboard if we use more tight styling.
- list item height is 38px
- list item background height is 36px
- list item data background height is 32px
We will be able to fit 5 items.
And with 3.0 where screen name will move to the topbar even 6 lines

**Comment by gagarinlg** [comment]
You can look at the gvar LVGL PR, there I fiddled with paddings until I got a density similar to pre LVGL

**Comment by JimB40** [comment]
LS_List_Data

Okay here are data fields fixings for all LS functions types with max data length

1. a=x, a<x etc
- V1 - switch 
- V2 - numeric value <-100,100> format ##
- AND switch - switch 
- Duration - numeric value <0.0,25.0> format ##.#
- Delay - numeric value <0.0,25.0> format ##.#

2. AND ,OR etc
- V1 - switch 
- V2 - switch
- AND switch - switch 
- Duration - numeric value <0.0,25.0> format ##.#
- Delay - numeric value <0.0,25.0> format ##.#

3. Edge (exception for V2 posotioning as Edge has two V2 values, and Delay that is not applicable)
- V1 - switch 
- V2 - numeric value <0.0,175.0> format ##.#
- V2b -mixed value. Either string '<<' or numeric value <0.0,275.0> format ##.# 
- AND switch - switch 
- Duration - numeric value <0.0,25.0> format ##.#
- Delay - N/A - not displayed.

4. Timer
- V1 - numeric value <0.0,175.0> format ##.# 
- V2 - numeric value <0,1750> format ####
- V2b -mixed value. Either string '<<' or numeric value <0.0,275.0> format ##.# 
- AND switch - switch 
- Duration - numeric value <0.0,25.0> format ##.#
- Delay - numeric value <0.0,25.0> format ##.#

5. Sticky (same as 2 ie AND, OR, XOR)

**Comment by philmoz** [comment]
My concern with the nested rounded rectangles is that the whole line looks like a button; but does not act like one.

Nothing happens if you tap on the switch name.

**Comment by JimB40** [comment]
That's a good point. Names are actually non-touchable (focusable labels) 
It behaves the same in Inputs & Mixes but difrently in Outputs where list item is grouped together with output name (label)
Let me think a while how can we solve it to unify UI.
Most probably styling change will be enough.

**Comment by JimB40** [comment]
We ma consider this styling change.
Group 2

So list's item has a frame to group multi-lines list's items but no background that indicates focusable-touchable UI element.

**Comment by eshifri** [comment]
How about vertical screens (NV14)? Will it be two lines?

**Comment by philmoz** [comment]
> We may consider this styling change. Group 2
> 
> So list's item has a frame to group multi-lines list's items but no background that indicates focusable-touchable UI element.

With the current 'active switch' color being the same light blue this will make active switches blend into the label section which I think will look a bit odd.

**Comment by philmoz** [comment]
I've updated the landscape layout to display on a single line. Portrait layout is two lines.
At this stage I've left it as a single button including the switch name (no nested rectangles).

Screen Shot 2023-01-13 at 10 19 54 am

Screen Shot 2023-01-13 at 10 15 51 am

**Comment by philmoz** [comment]
Paste is only active if a copy has already been done so you would have a hidden button or one that did nothing.

**Comment by philmoz** [comment]
I have added a long press handler to quickly access the '+' button functions.

**Comment by philmoz** [comment]
I have changed the logical switch overview to display the switch function and parameters as an expression (like the special functions PR).

I think this makes the switch operation easier to understand in the overview.

Also added a 's' suffix to time values in the overview and edit pages.

Screen Shot 2023-01-16 at 11 12 50 am

Screen Shot 2023-01-16 at 11 01 57 am

**Comment by JimB40** [comment]
@

> I have changed the logical switch overview to display the switch function and parameters as an expression (like the special functions PR).
> 
> I think this makes the switch operation easier to understand in the overview.

I don't think it will work this way .

1. Readiness decreased

2. Have you proofed it with max length data values? 
212042683-1d280fa1-c9c1-4fc1-8c10-ce130a70bafe
As you can see there int much fee space, so after adding ON/OFF labels clipping or other layout breaks will occur.

**Comment by philmoz** [comment]
These are the widest values I can find:

Screen Shot 2023-01-16 at 5 53 29 pm

**Comment by philmoz** [comment]
Maybe it's just me; but I find this:

Screen Shot 2023-01-16 at 6 16 21 pm

is easier to understand than this:

Screen Shot 2023-01-16 at 6 16 10 pm

**Comment by JimB40** [comment]
Widest valur is negated max telemetry sensor "!WWWW+"

But plaese don't change as there are much more data variances that will cause layout to break.
IE telemetry sensors have unit that can be pretty long and will not fit in any way.
Changig V1 and V2 to ON/OFF is not so simple too plus we have to change docs.

Most important is to see on list properly
- switch/source icon & name
- value 

LS List


I've tried labels with TUZSIZE font but this can decrese UI speed and makes overview cluttered anyway.
LS List Labels


We may try to fit in 3.0 header with column names but this will not work for vertical screen anyway.

**Comment by Eldenroot** [comment]
> I've tried labels with TINSIZE font but this can decrese UI speed and makes overview cluttered anyway. LS List Labels
> 
> We may try to fit in 3.0 header with column names but this will not work for vertical screen anyway.

Anyway, I love it! Really no way to get this? :)

**Comment by philmoz** [comment]
@JimB40 Here is another idea to make more room (not sure about the labels as translation could be a problem).

Screen Shot 2023-01-17 at 1 00 33 pm

**Comment by philmoz** [comment]
I have added the logical switch view in the channel monitor as it also needed conversion to LVGL / flex layout.

I changed it slightly to show inactive logical switches as 'disabled'.
Also fixed the footer to show all values in portrait layout.

Screen Shot 2023-01-22 at 8 51 49 am

Screen Shot 2023-01-22 at 8 50 59 am

**Comment by JimB40** [comment]
@philmoz Logical Switches labels are only ones that do not follow XX00 pattern. 
CH01,CH02,..
TR01,TR02,..
SF1,SF2,...
GV1,GV2,...
FM1,FM2

Can we adjust Logic Switches labels to LS01, LS02 instead of L01,L02

**Comment by pfeerick** [comment]
That may need to be material for a different PR - since you're talking about a system-wide change (probably also with a Companion UI component also), rather than effectively just the LS LVGL page conversion.

**Review by pfeerick — APPROVED** [review]

**Pull request merged**
