### PR TITLE
feat(color): re-add support for rotary encoder velocity increase

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- re-implemented rotary encoder velocity in LVGL rotary encoder driver

### CODE REVIEW

**Comment by pfeerick** [comment]
As you said, I think this needs a little fine-tuning still... seems a little too eager to start accelerating... i.e. even what I would call a moderately slow scroll and it accelerates, but it is definitely working now. Perhaps also needs to be killed or really toned down when the onscreen keyboard is up... otherwise you go from q to the spacebar more times than you would like 😆

**Comment by gagarinlg** [comment]
Is it good to have that globally, or would it make more sense to have this as an option for specific inputs? So it can be enabled on number edit fields, when needed, but disabled when not needed.

**Comment by raphaelcoeffic** [comment]
> Is it good to have that globally, or would it make more sense to have this as an option for specific inputs? So it can be enabled on number edit fields, when needed, but disabled when not needed.

Previously it used to be only in certain inputs like number edit. It does make some sense for me in the drop-downs as well.

**Comment by rburrow87** [comment]
Yeah, since we can't do that trick where you scroll up to get to the bottom of a list anymore, it makes sense for it to have acceleration there as well.

And I agree, it's a bit too eager to start accelerating as of now.

**Comment by gagarinlg** [comment]
> Yeah, since we can't do that trick where you scroll up to get to the bottom of a list anymore, it makes sense for it to have acceleration there as well.
> 

It should not be hard to enable it on LVGL lists and implement it in our own list implementations. But again, this should be optional, depending on the usage and the length of the list. It makes sense when you select an input, but probably not for lists with just 4 entries.

**Comment by robustini** [comment]
Tested and much more comfortable, maybe a slight modularity on acceleration would be useful, now it is very sensitive, thanks Pascal!

**Comment by pfeerick** [comment]
Merging, on the proviso that we need to tune it further ;)

**Pull request merged**
