### PR TITLE
CMake: Use ExternalProject_Add() to split by toolchain

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
## Motivation
CMake does not support using multiple toolchains at the same time. This PR splits the targets between native and cross-compiled targets to be more conform to the way CMake works. At the same time, it offers a cleaner solution to problems raised by compiling for example on Apple silicon. It should also allow for better managing dependencies by allowing for object libraries in a cleaner way.

### Initial `cmake`

This changes the command necessary to compile targets. After the initial `cmake` has been executed, a directory is created for each target architecture (among others):
- `native`: this is everything that runs directly on the host machine (Companion, Simulator, unit tests, etc).
- `arm-none-eabi`: MCU targets (mostly `firmware`).

However, these directories are empty at this point and lack the CMake configuration for these families of target. The configuration is created in the `configure` phase.

### Configuration Step

The `configure` targets allow for CMake to create/update the configuration for the different target architectures. There are 3 targets defined for that:
- `configure`: configures both target architectures
- `native-configure`: configures only `native` targets
- `arm-none-eabi-configure`: configures only `arm-none-eabi` targets

Please note that prior to building anything, the target architecture must be configured.

### Target Architecture Scoped Builds

This means that every build command is now "scoped" on a *target architecture*. This means that the real `firmware` target should be built inside the `arm-none-eabi` directory. See the following example to build with `8` threads (aka. jobs):
```shell
$ make -C arm-none-eabi -j8 firmware
```

The same applies to companion:
```shell
$ make -C native -j8 companion
```

### Shortcut Targets

A number of shortcut targets have been defined for convenience:
- `firmware`
- `libsimulator`
- `companion`
- `gtests-radio` / `tests-radio`
- `simulator`
- `simu`

These can be called directly from the main directory:
```shell
make -j8 firmware
make -j8 libsimulator
make -j8 companion
make -j8 tests-radio
```

The main difference to *Scoped Targets* is that these do depend on `configure`, and will thus trigger the configuration of the target architecture.

### CODE REVIEW

**Comment by rotorman** [comment]
Tested this PR successfully under MSYS2 for building Companion, Simulator, Windows installer, TX16S firmware and simu libs. In addition tested under GitPod for building TX16S firmware.

Here for reference the commands I used. MSYS2:
```
git clone --recursive -b sub-cmake https://github.com/EdgeTX/edgetx.git sub-cmake && cd sub-cmake && mkdir build-output && cd build-output
cmake -G "MSYS Makefiles" -Wno-dev -DCMAKE_PREFIX_PATH=$HOME/5.12.9/mingw73_64 -DSDL_LIBRARY_PATH=/mingw64/bin/ -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DCMAKE_BUILD_TYPE=Release ../
make configure
make -C arm-none-eabi -j`nproc` firmware
make -C native -j`nproc` companion
make -C native -j`nproc` simulator
make -C native -j`nproc` libsimulator
make -C native installer
```

GitPod:
```
https://gitpod.io/#https://github.com/edgetx/edgetx/tree/sub-cmake
cmake -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DCMAKE_BUILD_TYPE=Release ../
make arm-none-eabi-configure
make -C arm-none-eabi -j`nproc` firmware
```

**Comment by rotorman** [comment]
Building was also successful under Ubuntu 20.04 LTS for firmware and libsimulator for TX16S, compact simu for TX16S, Companion and full/big simulator. Commands used:
```
git clone --recursive -b sub-cmake https://github.com/EdgeTX/edgetx.git sub-cmake && cd sub-cmake && mkdir build-output && cd build-output
cmake -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DCMAKE_BUILD_TYPE=Release ../
make configure
make -C arm-none-eabi -j`nproc` firmware
make -C native -j`nproc` companion
make -C native -j`nproc` simulator
make -C native -j`nproc` libsimulator
make -C native -j`nproc` simu
```

`make -C native package` under Ubuntu 20.04 (focal) is not successful, the output is:
```
linuxdeployqt  (commit aeafcd2), build 13 built on 2022-01-28 22:37:07 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (Ubuntu Bionic), which is glibc 2.27.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
```
According to output, 18.04 (Bionic) is latest supported for building package.

**Comment by pfeerick** [comment]
My normal `clean` workflow on WSL 
```
rm CMakeCache.txt ||: && cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S .. && make clean
make -C arm-none-eabi -j`nproc` firmware
make -C native -j`nproc` libsimulator simulator companion
```

is working fine... after the necessary tweaks to `make` and initial `make configure` call. 

It looks like #1742 introduced some `simulator` compile breakage, which this PR seems to fix.

**Comment by rotorman** [comment]
Tested also with Ubuntu 18.04 LTS natively - with it, everything works. Tested commands:
```
git clone --recursive -b sub-cmake https://github.com/EdgeTX/edgetx.git sub-cmake && cd sub-cmake && mkdir build-output && cd build-output
cmake -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DCMAKE_BUILD_TYPE=Release ../
make configure
make -C arm-none-eabi -j`nproc` firmware
make -C native -j`nproc` companion
make -C native -j`nproc` simulator
make -C native -j`nproc` libsimulator
make -C native -j`nproc` simu
make -C native package
```

**Comment by raphaelcoeffic** [comment]
@pfeerick I'm ready when you're ready ;-)

**Comment by pfeerick** [comment]
I'll give it another try :) 

AFAIK later half of https://github.com/EdgeTX/edgetx/pull/1736#issuecomment-1085388821 still applies though 😁

**Review by pfeerick — APPROVED** [review]
Working good on WSL2/Ubuntu and MSYS2. I added the missing custom targets for `simulator` and `simu`, as well as better ignoring of python compiled bytecode. Just waiting for the PR checks to pass.

**Pull request merged**
