### PR TITLE
feat: Warn on shutdown if trainer is connected

### PR DESCRIPTION
**Pull request by 3djc**
This adds a warning when trying to shutdown radio while a trainer is connected, as per @pfeerick comment in #3937

### CODE REVIEW

**Comment by pfeerick** [comment]
I'll throw this out to the translators now since it should be a nice simple one... 

Can we get some translations for this please 😃 

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes DE
- [ ] @Pat6874 FR
- [ ] @offer-shmuely HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT 

Context: There is going to be a warning prompt on shutdown (similar to the USB connected, model still powered one) if the trainer link is still active, which would cover instances such as where the RF link doesn't provide telemetry. 

```
#define TR_TRAINER_STILL_CONNECTED "Trainer still connected"
```

**Comment by froqstar** [comment]
DE:

#define TR_TRAINER_STILL_CONNECTED "Schüler noch verbunden";

**Comment by Eldenroot** [comment]
CZ: Trenér stále připojen

**Comment by Pat6874** [comment]
FR

"Élève encore connecté"

Le 16 oct. 2023, 10:25, à 10:25, Peter Feerick ***@***.***> a écrit:

**Comment by zandorsp** [comment]
> I'll throw this out to the translators now since it should be a nice simple one...
> 
> Can we get some translations for this please 😃
> 
>     * [ ]  @zyren CN / TW
> 
>     * [x]  @Eldenroot CZ
> 
>     * [ ]  @HThuren DA
> 
>     * [x]  @ParkerEde / @TheIsotopes DE
> 
>     * [x]  @Pat6874 FR
> 
>     * [ ]  @offer-shmuely HE
> 
>     * [ ]  @robustini IT
> 
>     * [ ]  @ToshihiroMakuuchi JP
> 
>     * [ ]  @ulfhedlund SE
> 
>     * [ ]  @ajjjjjjjj PL
> 
>     * [ ]  @zandorsp PT
> 
> 
> Context: There is going to be a warning prompt on shutdown (similar to the USB connected, model still powered one) if the trainer link is still active, which would cover instances such as where the RF link doesn't provide telemetry.
> 
> ```
> #define TR_TRAINER_STILL_CONNECTED "Trainer still connected"
> ```

PT

"Trainer ainda conectado"

**Comment by robustini** [comment]
IT

#define TR_TRAINER_STILL_CONNECTED "Trainer ancora connesso"

**Comment by ulfhedlund** [comment]
SE
#define TR_TRAINER_STILL_CONNECTED "Lärare fortfarande ansluten"

**Comment by ajjjjjjjj** [comment]
PL
`#define TR_TRAINER_STILL_CONNECTED "Uczeń ciągle podłączony"`

**Comment by offer-shmuely** [comment]
HE
 
מצב חניך עדיין מחובר

**Comment by HThuren** [comment]
DA
#define TR_TRAINER_STILL_CONNECTED "Træner fortsat forbundet"

**Comment by ToshihiroMakuuchi** [comment]
JP:
#define TR_TRAINER_STILL_CONNECTED "トレーナー通信はまだ継続しています"

**Review by pfeerick — COMMENTED** [review]
@3djc Are you happy with the changes I made?

**Comment by 3djc** [comment]
> @3djc Are you happy with the changes I made?

Yes Sir, Yes !

**Pull request merged**
