### PR TITLE
Japanese translation fixes

### PR DESCRIPTION
**Pull request by ToshihiroMakuuchi**
Pull request to lvgl branch.
Japanese file [jp.h] created. Could you please confirm this ?

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@ToshihiroMakuuchi does this alright to you?
Screenshot 2022-06-06 at 10 06 47
Screenshot 2022-06-06 at 10 07 09
Screenshot 2022-06-06 at 10 07 39
Screenshot 2022-06-06 at 10 07 58
Screenshot 2022-06-06 at 10 08 24
Screenshot 2022-06-06 at 10 10 16
Screenshot 2022-06-06 at 10 11 02

**Comment by raphaelcoeffic** [comment]
Firmware size looks alright as well (similar to Chinese `CN` & Traditional Chinese `TW`):
```
---- Size report for firmware.elf (MCU: STM32F429xI) ----

Section Details:
section              size(B)         addr   loc
.text                1870216   0x08000000   Flash
.ARM                       8   0x081c8988   Flash
.init_array              228   0x081c8990   Flash
.fini_array                4   0x081c8a74   Flash
.data (added)           5660   0x081c8a78   Flash
.data                   5660   0x20000000   SRAM1
.bss                   46484   0x20001620   SRAM1
.ram                   17688   0x2000cbb4   SRAM1
.ccm                   48256   0x10000000   CCRAM
.sdram               5238784   0xd0000000   SDRAM2

Totals         KB    usage  of ttl	KB free
  Flash:  1832.14   89.46%    2048	 215.86
  CCRAM:    47.12   73.63%      64	  16.88
  SRAM1:    68.20   60.89%     112	  43.80
  SRAM2:     0.00    0.00%      16	  16.00
  SRAM3:     0.00    0.00%      64	  64.00
 SDRAM2:  5116.00   62.45%    8192	3076.00
```

**Comment by raphaelcoeffic** [comment]
Working code is pushed to [`jp` branch](https://github.com/EdgeTX/edgetx/tree/jp).

**Comment by ToshihiroMakuuchi** [comment]
@raphaelcoeffic 
Thank you for responding. I can see it in Japanese without any problem. I would like to correct the dictionary file later when it is reflected in the part of the display that does not seem to fit.

**Comment by ToshihiroMakuuchi** [comment]
It seems that I touched the button unintentionally and closed it. Undo it.

**Comment by ToshihiroMakuuchi** [comment]
@raphaelcoeffic 
I am trying to build today with the lvgl branch, but the build is not successful. Is it the same situation?
I was going to try to install the Japanese firmware but unfortunately I couldn't.
I am not very familiar with GitHub, so it could be my own fault. If you don't mind, I would appreciate it if you could share the firmware available for TX16S or T16 somewhere, even if it is a nightly build or something.

**Comment by raphaelcoeffic** [comment]
@ToshihiroMakuuchi we‘re about to merge the LVGL branch. I will rebase the Japanese translation on top then. You should be able to use the firmwares compiled on GH then.

**Comment by raphaelcoeffic** [comment]
@ToshihiroMakuuchi seems I cannot update your PR anymore (probably the branch is gone or different on your side). I created #2026 instead.

**Pull request closed without merging**
