### PR TITLE
feat(nv14/el18): Add help popup showing mapping when using hats as keys.

### PR DESCRIPTION
**Pull request by philmoz**
For when I forget what the key assignments are :)

screenshot_el18_23-11-25_09-39-08

### CODE REVIEW

**Comment by rotorman** [comment]
I wonder if graphical representation might be more intuitive for the user. Due to portrait display, showing the trims in two rows is less perfect though. Here two images I created for further discussion:

Left trim hat:
NV14_buttons_left

Right trim hat:
NV14_buttons_right

**Comment by richardclli** [comment]
Another radio that may use HAT mode is PL18 series, need to consider this as well.

**Comment by rotorman** [comment]
In order to be able to also use this feature on radios that do not have hat type trims (e.g. PL18/Paladin EV), a suggestion to use "trim-navigation" instead of "hats mode" to keep it more generic.

**Comment by pfeerick** [comment]
Just gonna leave this as it is for now, to be tweaked in 2.11 if needed/desired.

**Pull request merged**
