### PR TITLE
Unify telemetry driver (S.Port), fix 2861

### LINKED ISSUE #2861: EL18 cannot achieve 5.25M BAUD for CRSF
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Can only achieve 1.87M BAUD, error occurs when trying to use 3.75M BAUD or 5.25M BAUD.

### Expected Behavior

Hardware is similar to TX16S, both uses USART2, it should works the same way as TX16S

### Steps To Reproduce

1. External Module
2. Select CRSF
3. Select BAUD to 3.75M BAUD or 5.35M BAUD
4. ELRS will report connection problem.

### Version

2.8.0

### Transmitter

Flysky EL18

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #2861

Summary of changes:
Unify the telemetry driver for all radios.

### CODE REVIEW

**Comment by richardclli** [comment]
There are 2 lines that appear in Tarnis driver but differ from the color radio driver, need to see what change is proper:

In telemetryPortInvertedInit, probeTimeFromStartBit used different values, how to merge this?
      probeTimeFromStartBit = 23; //because pin is not probed immediately
//      probeTimeFromStartBit = 25; // TODO: Tarnis used 25, how to merge?

In sportSendBuffer, can this line be omitted?  This only appears in tarnis driver
//  USART_ClearITPendingBit(TELEMETRY_USART, USART_IT_TC);  // TODO: This requires?  Only appear in tarnis driver

**Comment by richardclli** [comment]
I already tested this in TX16S and EL18, both works properly with ELRS.

**Comment by gagarinlg** [comment]
I think @raphaelcoeffic should do the review. I have never been in that part of the firmware and can not answer your todo-questions.

**Comment by richardclli** [comment]
> I think @raphaelcoeffic should do the review. I have never been in that part of the firmware and can not answer your todo-questions.

@raphaelcoeffic Need your review ^.^

**Comment by richardclli** [comment]
Closed because it affects the module-api rework:
https://github.com/EdgeTX/edgetx/pull/3055

**Pull request closed without merging**
