### PR TITLE
Fix max # channels and default channel range

### LINKED ISSUE #299: MODEL -> SETUP can't select proper channel range
1. Go to MODEL -> SETUP

- [ ] 2. Select as External RF Mode: GHST 
2a. Select end channel in Channel Range lower then 8th
2b. Try to select 8th again.
Stuck at 7th as max channel

- [ ] 3. Select as External RF Mode: SBUS 
3a. Select end channel in Channel Range lower then 8th
3b. Try to select 8th again.
Stuck at 7th as max channel

- [ ] 4. Select as External RF Mode: CRSF 
End channel in Channel Range can't be selected
It keeps channel range selected in other mode.

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #299

### CODE REVIEW

**Comment by NemesisXB** [comment]
Tested on RM TX16s with CRSF. Working as expected.

**Comment by pfeerick** [comment]
Walked through the external protocols on the NV14... seemed to work perfectly.

For a laugh, try MPM on the NV14 and look at the size of the protocol scan progress bar😆

**Comment by pfeerick** [comment]
Should you be able to alter the end channel for SBUS? You can't on TX12, but can on NV14? Should it not be the same as CRSF and CHST - fixed range and can only alter start channel?

**Comment by raphaelcoeffic** [comment]
> Should you be able to alter the end channel for SBUS? You can't on TX12, but can on NV14? Should it not be the same as CRSF and CHST - fixed range and can only alter start channel?

It's basically cosmetics, as SBUS has a fixed number of channels, like GHST or Multi.

**Comment by pfeerick** [comment]
SBUS, CRSF and GHST should all be 'read-only'... that's the list ;)

**Comment by raphaelcoeffic** [comment]
> SBUS, CRSF and GHST should all be 'read-only' end-channel... that's the list ;)

Done!

**Review by pfeerick — APPROVED** [review]
Peanut gallery is now satisfied :) 

TX16S hardware + simu, GHST, CRSF and SBUS all look like expected, correct values now. Another one bites the dust!

**Pull request merged**
