### PR TITLE
fix(bw): missing PT special chars handling

### LINKED ISSUE #4803: PT support: Missing special characters support
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

msg71610786-903215

There is no support for special characters in Portuguese. The radio replaces with a space character.

### Expected Behavior

The Portuguese( PT ) needs the following special characters: 
Á, á
Ã, ã
Â, â
Ç, ç
Ê, ê
É, é
Í, í
Ó, ó
Ô, ô
Õ, õ
Ú, ú
À,à  (rarely  used)

EDIT: Revoved î and û ... not used
added à

### Steps To Reproduce

Try to translate the PT.h file with special characters

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX12 / TX12MK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

no

### PR DESCRIPTION
**Pull request by 3djc**
image

Fixes #4803

### CODE REVIEW

**Comment by zandorsp** [comment]
It's worked with this fix:

`#elif defined(TRANSLATIONS_PT)
static wchar_t _utf8_lut[] = {
  L'Á', L'á', L'Â', L'â', L'Ã', L'ã', L'À',
  L'à', L'Ç', L'ç', L'É', L'é', L'Ê', L'ê', 
  L'Í', L'í', L'Ó', L'ó', L'Ô', L'ô', L'Õ', 
  L'õ', L'Ú', L'ú',
};`

**Comment by zandorsp** [comment]
Test strings:

**Comment by zandorsp** [comment]
Tested with this strings: (On Jumper T-Prov2)

#define TR_MENUMODELSEL                TR("ÁÃÂÇÊÉÍ", "SELECAO MODELO")
#define TR_MENU_MODEL_SETUP            TR("ÓÔÕÚÀG", "CONFIG. MODELO")
#define TR_FUNCTION_SWITCHES           "áãâçêéíóôõúàg"

**Comment by zandorsp** [comment]
Won't the blank file https://github.com/EdgeTX/edgetx/blob/main/radio/src/fonts/std/font_pt_04x06.png generate some problems (blank characters) in some cases?

**Comment by philmoz** [comment]
> Won't the blank file https://github.com/EdgeTX/edgetx/blob/main/radio/src/fonts/std/font_pt_04x06.png generate some problems (blank characters) in some cases?

If a translated string includes any special characters, AND is being displayed using the 'SMALL' font size, then this would happen.

From what I can see the strings that could be affected are TR_DURATION_MS, TR_INTERVAL_MS, TR_FM, TR_VTMRMODES, TR_MODE_OPTIONS_AVAILABLE and TR_OPENTX_UPGRADE_REQUIRED.

So long as these don't have any special characters it should be ok.

**Comment by 3djc** [comment]
Yes ideally we would want the 4x6 too, I just don't have the time to hand make one, maybe someone will volunteer:)

**Comment by zandorsp** [comment]
Patch to show correct characters
#elif defined(TRANSLATIONS_PT)
static wchar_t _utf8_lut[] = {
L'Á', L'á', L'Â', L'â', L'Ã', L'ã', L'À',
L'à', L'Ç', L'ç', L'É', L'é', L'Ê', L'ê',
L'Í', L'í', L'Ó', L'ó', L'Ô', L'ô', L'Õ',
L'õ', L'Ú', L'ú',
};

**Comment by zandorsp** [comment]
> Yes ideally we would want the 4x6 too, I just don't have the time to hand make one, maybe someone will volunteer:)

Well I made one now: 
font_pt_04x06

But needs testing and tweakings :)

**Comment by zandorsp** [comment]
> > Won't the blank file https://github.com/EdgeTX/edgetx/blob/main/radio/src/fonts/std/font_pt_04x06.png generate some problems (blank characters) in some cases?
> 
> If a translated string includes any special characters, AND is being displayed using the 'SMALL' font size, then this would happen.
> 
> From what I can see the strings that could be affected are TR_DURATION_MS, TR_INTERVAL_MS, TR_FM, TR_VTMRMODES, TR_MODE_OPTIONS_AVAILABLE and TR_OPENTX_UPGRADE_REQUIRED.
> 
> So long as these don't have any special characters it should be ok.

Well, I doesn`t using special characters in these.

**Comment by philmoz** [comment]
> > Yes ideally we would want the 4x6 too, I just don't have the time to hand make one, maybe someone will volunteer:)
> 
> Well I made one now

Each 4x6 character needs to be drawn in a 5x7 area, with any unused columns on the right set to all black.
The resulting image should be the same width as the 5x7 font with all characters evenly spaced.

I've tweaked your image; but still needs testing.
font_pt_04x06

**Comment by philmoz** [comment]
So it looks like the font handling code is broken for B&W radios and the special characters will only work for the 5x7 font size. ☹️

**Comment by zandorsp** [comment]
> So it looks like the font handling code is broken for B&W radios and the special characters will only work for the 5x7 font size. ☹️

I didn't find anywhere to test the 4x6 especial character font. Am I missing something?

**Comment by philmoz** [comment]
> > So it looks like the font handling code is broken for B&W radios and the special characters will only work for the 5x7 font size. ☹️
> 
> I didn't find anywhere to test the 4x6 especial character font. Am I missing something?

I'm testing in the simulator with a modified build.

**Comment by philmoz** [comment]
Comparison of PT 4x6 and 5x7 in simulator.

screenshot_tx12_24-03-26_13-11-12

**Comment by zandorsp** [comment]
> Comparison of PT 4x6 and 5x7 in simulator.
> 
> screenshot_tx12_24-03-26_13-11-12

Looks nice :)

**Comment by philmoz** [comment]
I've added your 4x6 font image (tweaked slightly) and the updated mapping, plus fixed the code so special characters should work for all font sizes.

**Pull request merged**
