### PR TITLE
Replace StaticText with LVGL labels.

### PR DESCRIPTION
**Pull request by philmoz**
Getting rid of the StaticText labels and using LVGL labels instead also improves the load time.

### CODE REVIEW

**Comment by philmoz** [comment]
I did some timing tests with the simulator on my iMac.

Time (in nanoseconds) to build the GVARS page:
- The current main  branch = 1828000
- EdgeTX/gvars_speedup branch = 1537000 (84%)
- EdgeTX/gvars_speedup + EdgeTX/libopenui/speedup = 1252000 (68%)
- philmoz/gvars_speedup = 817000 (45%)

While the libopenui changes certainly help, removing the StaticText and Window objects entirely from the GVarButton class gives the biggest improvement.

**Comment by gagarinlg** [comment]
Wow
Maybe you could disabe the clock and printf stuff again? I will then accept the PR in my branch.

**Comment by philmoz** [comment]
I've removed all the diagnostics.

**Comment by philmoz** [comment]
> Did you test this with the NV14 simu?

Oops - I was a bit too aggressive with the optimisation. Fixed now.

**Comment by gagarinlg** [comment]
😂👍
There was a reason I added that container window

**Comment by philmoz** [comment]
The latest commit further improves the performance on the GVARS page.
The overall time to display the page content is better; but the main improvement is the initial object creation time is drastically reduced by delaying the main content initialisation.

This improves the responsiveness when navigating between tabs - there is no longer a big delay on this page before you can move to another tab.

**Comment by pfeerick** [comment]
Can you rebase this one for me... it looks like it will be a clean rebase, but if you do git won't assign dual authorship to the commits ;) 

Am I right in believing that this effectively supersedes #3307. And merging in https://github.com/EdgeTX/libopenui/pull/88 shouldn't break anything in conjunction with this? Just double checking as it seems to all be working fine here 😇

**Comment by philmoz** [comment]
I rebased to main; but it is showing a conflict with model_gvars.cpp - not sure what I did wrong?

The libopenui PR should be fine.

**Comment by pfeerick** [comment]
Ah, sorry, I'm an idiot... I didn't look at the target branch and was thinking it was to go *into* main, not Malte's speedup branch, against main... Ok, I'll just try something, and if that doesn't work, can go via that branch... maybe 😆

**Pull request merged**
