### PR TITLE
Add Lua function lcd.drawTextLines(...) 

### PR DESCRIPTION
**Pull request by jfrickmann**
Drawing text across multiple lines inside bounding box

### CODE REVIEW

**Comment by pfeerick** [comment]
Very nice! Tested on NV14 `simu` and TX16s hardware... works a treat. Long message wraps to fill the widget space available with no 'hand-holding' required!

snapshot_10
snapshot_11

A question - if I wanted to have a new line after "No TxGPS detected!" is that possible, as it doesn't like `\n` so maybe there's a proper Lua way to do that?

**Comment by jfrickmann** [comment]
The current function is very simple, it just looks for spaces to separate words and goes to the next line when we run out of space. But if course a function that handles newline and hyphens etc. could be made.

**Comment by JimB40** [comment]
Yep. Jeti has HTML support in LUA :)

**Comment by pfeerick** [comment]
You should know better than to mention Jeti 💩 here! 😛 💸 💸 💸

**Pull request merged**
