### PR TITLE
fix(x9e): missing F3/F4 pots, slider hwdef changes

### LINKED ISSUE #5006: EdgeTx 2.10 Taranis X9E F3 F4 missing in Hardware configuration
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In hardware configuration menu F3 and F4 Pot Input have disappeared while they are physically present on the PCB

### Expected Behavior

F3 and F4 must be visualized in Hardware Menu

### Steps To Reproduce

Go to Hardware menu by long press key Menu
check if F3 anf F4 Pot are visualized

### Version

Other (Please specify below)

### Transmitter

FrSky X9E / X9E Hall

### Operating System (OS)

Linux

### OS Version

_No response_

### Anything else?

screenshot_x9e_24-05-14_20-16-58

### PR DESCRIPTION
**Pull request by 3djc**
Match declaration with OTX initial source

Fixes #5006

### CODE REVIEW

**Comment by elecpower** [comment]
Changing the hw def will likely break Companion binary and adc refactor conversions as I  seem to remember a specific fudge.

**Comment by 3djc** [comment]
I guess it is likely broken as F3/F4 existed pre refactor, and had disappeared since

**Comment by elecpower** [comment]
I'll have a look when I get time

**Comment by elecpower** [comment]
Tested using 2.3.15 otx (binary) and 2.9.4 etx (yaml) and all appears okay. Back to you @3djc to check.

**Comment by pfeerick** [comment]
Do you want me to comment those out If I spot them before merging?

**Comment by 3djc** [comment]
Retested everything, seems good to me !

**Comment by pfeerick** [comment]
Thanks JC :)

**Pull request merged**
