### PR TITLE
fix(lua): add 'repetition' property to getCustomFunction and setCustomFunction tables

### LINKED ISSUE #4692: LUA: special function repeat parameter missing for model.setCustomFunction
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the current main, no value can be set for "Repeat" via lua model.setCustomFunction. I think this has happened since there is now a separate activation switch
image

### Expected Behavior

repeat like  !1x, 1x, 1s, 2s and so on should be setable for model.setCustomFunction

### Steps To Reproduce

try to set repeat like  !1x, 1x, 1s, 2s and so onwith  model.setCustomFunction in a lua script

### Version

Other (Please specify below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

current main

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4692

### CODE REVIEW

**Comment by ParkerEde** [comment]
tried this PR:
GET works okay:
table: 000001b2c3ea4f80 {
  [switch] => -213
  [param] => 0
  [active] => 1
  [value] => 264
  [func] => 12
  [repeat] => -1
  [mode] => 0
}


but if I try to SET with this:
model.setCustomFunction(45, {func=12,switch=-213,value=264 ,param=0,active=1,repeat=-1})
I get an error message:
image

**Comment by philmoz** [comment]
'repeat' is a keyword in Lua. To use it as a table index you need to use ['repeat'].

e.g.:
```Lua
model.setCustomFunction(45, {func=12,switch=-213,value=264 ,param=0,active=1,['repeat']=-1})
```

If you don't want to do this then we will have to change the name.

**Comment by 3djc** [comment]
looks error prone like this, maybe change repeat to repetition ?

**Comment by ParkerEde** [comment]
I personally wouldn't mind, but I think it's better to use a name other than "repeat" as it's less error-prone. I quite like 3djc's suggestion

**Comment by ParkerEde** [comment]
@pfeerick is there a specific reason why this PR is not yet assigned to branch 2.10?

**Pull request merged**
