### PR TITLE
feat(ui) - Add long press handler for new model curves page.

### PR DESCRIPTION
**Pull request by philmoz**
Align with new special function and proposed logical switch UI.
Also adds titles to the menus to make it clearer what action is being performed.

Short press:
Screen Shot 2023-01-24 at 8 36 32 am

Long press:
Screen Shot 2023-01-24 at 8 36 48 am

### CODE REVIEW

**Comment by ParkerEde** [comment]
Unfortunately, I still have a question about this. In the current implementation, it is no longer possible to specifically create a curve as a certain ID. This means that the curves cannot be sorted into blocks according to task. It would be nicer if the (+) button offered a list of free curves and the new curve was then created on the selection. This would be exactly the same as with the specialfunctions or logicalswitches. Could this also be implemented here?

**Comment by philmoz** [comment]
> Unfortunately, I still have a question about this. In the current implementation, it is no longer possible to specifically create a curve as a certain ID. This means that the curves cannot be sorted into blocks according to task. It would be nicer if the (+) button offered a list of free curves and the new curve was then created on the selection. This would be exactly the same as with the specialfunctions or logicalswitches. Could this also be implemented here?

Good idea - let me take a look.

**Comment by Eldenroot** [comment]
> Unfortunately, I still have a question about this. In the current implementation, it is no longer possible to specifically create a curve as a certain ID. This means that the curves cannot be sorted into blocks according to task. It would be nicer if the (+) button offered a list of free curves and the new curve was then created on the selection. This would be exactly the same as with the specialfunctions or logicalswitches. Could this also be implemented here?

always good to create a new ticket.

**Comment by pfeerick** [comment]
> always good to create a new ticket.

... if the PR isn't self explanatory, or are unsure as to whether will actually work on it. ;) Otherwise, it's just added noise.

**Comment by ParkerEde** [comment]
Should I create a new ticket or what do you suggest?

**Comment by pfeerick** [comment]
What for... https://github.com/EdgeTX/edgetx/pull/3091 ? 😆

**Pull request merged**
