### PR TITLE
feat(color): warning when duplicating theme if name exists

### LINKED ISSUE #4148: Theme duplikace
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If I create a duplicate theme and name it, for example, "1" and subsequently delete the duplicate, it is no longer possible to create another duplicate with the same name "1".

### Expected Behavior

A duplicate topic should be named with a name that is not already in use in the list of theme, even if this name was already used for it but was subsequently deleted.

### Steps To Reproduce

1.- Create a duplicate of any theme and name it for example "1"
2.- Delete created duplicate named "1"
3.- Attempt to create a new duplicate of the topic named "1"

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

[EdgeTX "Prozreteľnosť" v2.9.1](https://github.com/EdgeTX/edgetx/releases/tag/v2.9.1)
CZ language

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4148 

Changes:
- Add a warning popup when trying to create a new theme with a name that already exists (folder with same name exists and contains a theme.yaml file)..
- Allow a new theme to be created when the theme folder already exists, so long as the theme.yaml file does not exist (e.g. theme previously deleted, folder may contain theme.yaml.deleted).
- When deleting a theme, remove the theme.yaml.deleted file before trying to rename theme.yaml.
- Change logic of the f_mkdir function in the simulator to match the firmware (return FR_EXIST when directory already exists instead of FR_INVALID_NAME).

### CODE REVIEW

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @offer-shmuely / @adir-kro HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU

```cpp
#define TR_THEME_EXISTS           "A theme directory with the same name already exists."
```

**Comment by froqstar** [comment]
DE

"Ein Theme-Verzeichnis mit demselben Namen existiert bereits"

**Comment by robustini** [comment]
IT
#define TR_THEME_EXISTS           "Esiste già una cartella di temi con lo stesso nome."

**Comment by HThuren** [comment]
I suggest this new define are placed after TR_THEME_EDITOR  in xx.h file to have some grouping.

DA
#define TR_THEME_EXISTS           "Der findes allerede et katalog med samme navn."

**Comment by Pat6874** [comment]
#define TR_THEME_EXISTS "Un thème avec le même nom existe déjà."

Le 18 mars 2024, 01:31, à 01:31, Peter Feerick ***@***.***> a écrit:

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_THEME_EXISTS           "Folder szablonów o takiej samej nazwie już istnieje."
```

**Comment by Eldenroot** [comment]
CZ:

#define TR_THEME_EXISTS           "Adresář vzhledu s tímto názvem již existuje."

**Comment by offer-shmuely** [comment]
HE
#define TR_THEME_EXISTS           "כבר קיימת ערכת נושא עם אותו שם"

**Comment by kobakirill** [comment]
RU
#define TR_THEME_EXISTS "Уже есть каталог с таким названием"

**Comment by ulfhedlund** [comment]
SE
#define TR_THEME_EXISTS "Det finns redan ett tema med samma namn"

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_THEME_EXISTS           "同じ名前のテーマディレクトリが既に存在します。"

**Comment by zandorsp** [comment]
PT

#define TR_THEME_EXISTS     "Já existe um diretório de tema com o mesmo nome."

**Pull request merged**
