### PR TITLE
[color] Fix MPM option title==nullptr

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by pfeerick** [comment]
This fixes the crash problem - models that would previously just cause the tx to completely freeze if I try to turn on multi are fine now, and creating new models and enabling multi mod is fine. 

Perhaps there is an issue with the multimod not finished switching protocol, yet? as I can sometimes change protocols, and then simply re-select the same protocol, and more options are added.

**Comment by raphaelcoeffic** [comment]
> This fixes the crash problem - models that would previously just cause the tx to completely freeze if I try to turn on multi are fine now, and creating new models and enabling multi mod is fine.
> 
> Perhaps there is an issue with the multimod not finished switching protocol, yet? as I can sometimes change protocols, and then simply re-select the same protocol, and more options are added.

Not sure I understand that last one properly: do you get 2 sets of options? This seems more like a UI issue, we don’t require MPM feedback for anything at moment on this page.

**Comment by pfeerick** [comment]
No. They don't appear, and then the second time I pick the *same* protocol they appear. I was thinking if the protocol has just been changed, maybe things like `getMultiOptionTitle(moduleIdx)` don't reflect the state of the module / protocol yet?

**Comment by pfeerick** [comment]
i.e. was on flysky protocol, picked dsm, and then picked dsm a second time...

image

With V2X2, one extra option is present, and removed on the second retry:
image

I think the latter is supposed to have channel remapping... but the MPM docs don't make it as explicitly clear as it does for other protocols.

**Comment by raphaelcoeffic** [comment]
This is really strange, it works on the simu perfectly.... I need to change to the radio and see what happens. This might really be caused by the status reported by the MPM.

**Comment by raphaelcoeffic** [comment]
@pfeerick it should be ok now, if don't mind retesting 🧘🏻‍♀️

**Comment by pfeerick** [comment]
Wildo. Will merge before next nightly if ok.

**Comment by pfeerick** [comment]
DSM2 and DSMX options all appear to be working properly
D16 is working properly also
Changing through various MPM protocols *appears* to be ok now (and any stuffups there can be fixed later)
Transmitter no longer freezes when choosing "MULTI" for internal RF in a new model (which also means my XJT module was innocent)

**Pull request merged**
