### PR TITLE
feat: add "Trims" option to Reset special function 

### LINKED ISSUE #5274: Option for not saving trims
Pascal  Langer is working on a new protocol which brings an interesting challenge: the dirt cheap remote that comes with it does have trims, but this radio doesn't save trim, and always start trims a 0. Instead, the receiver store the last position when turned off and restart from there next time (so in essence with an EdgeTX radio, you get twice the trims: the rims saved on receiver + the ones on the radio)

One way of dealing with it would be an option for not saving trims

Another one would be a trim reset SF

### PR DESCRIPTION
**Pull request by 3djc**
Fixes #5274

Summary of changes:
adds "trims" choice to reset function. Activate reset all trims to 0 in current flight mode.

### CODE REVIEW

**Comment by elecpower** [comment]
> @elecpower could you have a look at the companion side. Tested it ok, but I might have overlocked something

I've only had time for a quick desk check and I pretty sure there are some more +2 -> +3 changes required as sensors follow your new Trim

**Comment by 3djc** [comment]
> > @elecpower could you have a look at the companion side. Tested it ok, but I might have overlocked something
> 
> I've only had time for a quick desk check and I pretty sure there are some more +2 -> +3 changes required as sensors follow your new Trim

Was able to find 2 more, also used a constant

**Comment by elecpower** [comment]
@3djc I took some liberties, hope you don't mind. Also uncovered a couple of source inversion introduced bugs which I have fixed here as well as a separate PR in case @pfeerick merges in different order.
Tested in Companion and checked tx16s simulator mirrored the settings. So its a tick from me.

**Review by elecpower — APPROVED** [review]

**Comment by 3djc** [comment]
Thanks a lot Neil :)

**Comment by elecpower** [comment]
and then an after-thought about my millstone binary import

**Comment by pfeerick** [comment]
LGTM on TX12MK2 :)

**Comment by TGS78** [comment]
Is it possible to reset individual trims instead of all?

**Comment by pfeerick** [comment]
Not a present I think. I was about to say this level of detail may be better via Lua script, but it doesn't seem possible there. So maybe it would be an idea to be able to reset the individual trims also as a further extension of this.

**Pull request merged**
