### PR TITLE
Changes to add danish translations - companion and radio :denmark:

### PR DESCRIPTION
**Pull request by HThuren**
Summary of changes:
Added danish translation to Companion and Radio.
Changed makefiles to have DA flag, Changed translation.cpp and generalsetup.cpp to discover new language in Companion, changed opentxinterface.h to diacover new language in radio.

### CODE REVIEW

**Comment by rotorman** [comment]
@HThuren can you please re-check da.h - it is presently using the old format with LEN_* and \0 fields.
Can you please have a look, e.g. at: https://github.com/EdgeTX/edgetx/blob/main/radio/src/translations/en.h for the updated/present way of defining translation strings and update this PR accordingly. Thx!

**Comment by HThuren** [comment]
Right, I'll change to tthe format without \0, this new format are also more easy to make right.

**Comment by HThuren** [comment]
Hi, I have changed da.h to the new format, and some minor changes to companion_da.h

**Comment by rotorman** [comment]
This PR does not build, e.g. for TX16S, with `-DTRANSLATIONS=DA`.
It is missing some strings, e.g.: `TR_GYR_VSRCRAW`, `TR_GYRO`, `TR_GYRO_LABEL`, `TR_GYRO_OFFSET`, `TR_GYRO_MAX`.

Try https://gitpod.io/#https://github.com/HThuren/edgetx/tree/Add_danish_translation
```
cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DTRANSLATIONS=DA -DCMAKE_BUILD_TYPE=Release ../
make arm-none-eabi-configure
make -C arm-none-eabi -j`nproc` firmware
```
and please add the missing strings.

**Comment by HThuren** [comment]
Right, some leftover from the old way of define without _LEN syntaks. 
I didn't get the errors at my own compilation, wonder why.
Hope there are no more issues

**Comment by rotorman** [comment]
Tested by building TX16S and Zorro firmware, building Companion and Simulator binaries, building TX16S and Zorro simulator libraries plus creating Windows installer. Found no issues anymore, will merge when the GH checks complete (as I see you just merged main to your branch, re-triggering the checks).

**Comment by HThuren** [comment]
Thank You :-) !

**Comment by rotorman** [comment]
Thank **you** for creating the Danish translations!

**Pull request merged**
