### PR TITLE
fix: Translate widget "full screen" menu option

### LINKED ISSUE #2503: Translation of view layout Fullscreen
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

This would add a translation for view layout "Fullscreen", related to #2454 where other widget strings were made translatable.

### Describe the solution you'd like

The view layout "Fullscreen" should be translatable.

I have fixed this in a local branch but since I don't know the string naming conventions or where the string should preferably be located in the various translation files (*.h, translations.cpp and translations.h) I am reluctant to create a PR. 

Should I wait for the experienced programmers suggestions for the above or create a PR with my solution?

I have named the string STR_VIEW_LAYOUT_FULLSCREEN and located it under STR_WIDGET_VALUE, in the if colorlcd section.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ulfhedlund**
Fixes #2503 

Summary of changes:
Added possibility to translate the full screen widget layout by adding TR_WIDGET_FULLSCREEN, set to "Full screen" in all translation files except for Swedish where it is translated already.

### CODE REVIEW

**Comment by pfeerick** [comment]
Perfect! Thank you :)

**Comment by Eldenroot** [comment]
You have missed translations...

**Comment by pfeerick** [comment]
?

**Comment by ulfhedlund** [comment]
I believe @Eldenroot meant that I didn't ping the translators to get their input before the PR. Which I quite correctly didn't do. Is there a list of translators for future use?

**Comment by Eldenroot** [comment]
I will add cz translations... anyway there are lets say 5-6 users who care about translations :)

**Comment by raphaelcoeffic** [comment]
> I will add cz translations... anyway there are lets say 5-6 users who care about translations :)

There would probably be a lot more if we could ship localised versions automatically.

**Comment by gagarinlg** [comment]
I hope it will happen before 3.0,but we will see.

As for the translators list, maybe a new tag for the discord users?

**Comment by Eldenroot** [comment]
Good idea!

**Comment by ulfhedlund** [comment]
I agree there aren't that many using translated versions yet, probably for many reasons. One perhaps being that the feature isn't well known and another that many translations have been only partially complete.
I'll do what I can to promote the translations I have been working on :)

A translator tag in discord would be useful.

**Comment by gagarinlg** [comment]
The tag is created, ping pafleraf in the dev channel to be added

**Comment by pfeerick** [comment]
> @pfeerick: I believe @Eldenroot meant that I didn't ping the translators to get their input before the PR. Which I quite correctly didn't do as I wasn't aware of this procedure. It makes good sense though. 
> Is there a list of translators somewhere, for future use?

That would be because I said I would tag translators *when I remember to* (until they otherwise complain)... But in this case I wasn't so worried since it was one word/phrase, and could be caught up in another PR. Was thinking most people don't like being pinged every five minutes for another word ;)

**Pull request merged**
