### PR TITLE
refactor(cpn): sort custom functions list

### PR DESCRIPTION
**Pull request by elecpower**
Satisfies Companion side of #3591

### CODE REVIEW

**Comment by elecpower** [comment]
@pfeerick no reason this cannot be merged without the radio side is there?

**Comment by pfeerick** [comment]
Yes, and no? Didn't we want radio and companion to match (oh wait, maybe this is deserved since Companion gets left behind?) :zany_face: Companion lists them _mostly_ in the same order as the radio atm, but radio side is going to be a pain (since we can't _just_ sort it like with Companion :cry: ), so probably better to merge this than leave it in limbo any longer.

**Comment by philmoz** [comment]
One option for the radio is a sorted index table for each language translation.
It would not add much to the firmware size (compared to locale handling), and could potentially be auto-generated.

**Comment by pfeerick** [comment]
That's the only really viable option I can see, since it's the index we really need sorted (for it to work for all UIs)... as I think doing the locale sort would have at best worked on colorlcd? Without a major re-write to how it is SF/GF are handled for that part of the UI, that is :face_with_head_bandage:

**Pull request merged**
