### PR TITLE
feat: User configurable audio mute (#3703 port to main)

### PR DESCRIPTION
**Pull request by 3djc**
This is the main compatible version of #3703

### CODE REVIEW

**Comment by pfeerick** [comment]
Hey guys, can we get translations for 
```
#define TR_AUDIO_MUTE TR("Audio mute","Mute if no sound")
```
please. 😄 For context, this feature mutes the speaker on supported handsets if it is not playing sound (thus preventing buzzing if using how power modules, etc.). 


- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes DE
- [ ] @Pat6874 FR
- [ ] @offer-shmuely HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL 

image
image

**Comment by Pat6874** [comment]
FR

#define TR_AUDIO_MUTE TR("Audio muet","Muet si pas de son")

Le 26 juin 2023, 12:09, à 12:09, Peter Feerick ***@***.***> a écrit:

**Comment by Pat6874** [comment]
FR

#define TR_AUDIO_MUTE TR("Audio muet","Muet si pas de son")

Le 26 juin 2023, 12:22, à 12:22, Michael ***@***.***> a écrit:

**Comment by robustini** [comment]
IT
#define TR_AUDIO_MUTE TR("Audio muto","Muto senza suono")

**Comment by Eldenroot** [comment]
CZ:
#define TR_AUDIO_MUTE TR("Ztlumení zvuku","Ztlumení, pokud není slyšet zvuk")

**Comment by offer-shmuely** [comment]
HE

#define TR_AUDIO_MUTE HE(
"השתקת קול",
"השתק כאשר אין סאונד"
)

**Comment by zyren** [comment]
CN
```
#define TR_AUDIO_MUTE   TR("自动降噪","无音频播放时自动降噪")
```
TW
```
#define TR_AUDIO_MUTE   TR("自動降噪","無音頻播放時自動降噪")
```

**Comment by mha1** [comment]
does #3703 stay in 2.9 as it is?

**Comment by ulfhedlund** [comment]
SE (not the easiset to translate but here's an attempt: #define TR_AUDIO_MUTE TR("Audio av","Audio av om inget ljud)Den 26 juni 2023 12:09 skrev Peter Feerick ***@***.***>:
Hey guys, can we get translations for
#define TR_AUDIO_MUTE TR("Audio mute","Mute if no sound")

please. 😄 For context, this feature mutes the speaker on supported handsets if it is not playing sound (thus preventing buzzing if using how power modules, etc.).
 @zyren CN / TW @Eldenroot CZ @HThuren DA @ParkerEde / @TheIsotopes DE @Pat6874 FR @offer-shmuely HE @robustini IT @ToshihiroMakuuchi JP @ulfhedlund SE @ajjjjjjjj PL

**Comment by HThuren** [comment]
DA
#define TR_AUDIO_MUTE TR("Audio fra","Audio fra, hvis der ikke gives lyd")

**Pull request merged**
