### PR TITLE
feat: add trainer virtual switch

### PR DESCRIPTION
**Pull request by 3djc**
Asked for on RCGroups

This provide a virtual switch indicating when a trainer link is active.

The switch is functionality does not depend of trainer type (all work), and can only be ON on the master radio (as the slave radio has no way to know if a master is listening to it)

### CODE REVIEW

**Comment by elecpower** [comment]
Is there an need to write this to yaml as I interpret it as being a condition and there is no need for persistence?

**Comment by 3djc** [comment]
I think there is:
image

**Comment by elecpower** [comment]
Use cases help my understanding. Therefore if 
>can only be ON on master radio (slave radio have no way to know if a master is there listening to it)

then should the switch not be listed/available when trainer mode set to slave?

**Comment by 3djc** [comment]
I wondered about that too, but I felt there was more risk of confusion if a switch was to disappear based on trainer setup (especially in mixers lines). If you are slave, it will just never come true, but remains valid nonetheless

**Comment by pfeerick** [comment]
I tried the hard-wired trainer on X9D+2019, TX16S and Zorro, with a special function that beeps while the trainer is active... worked perfectly, as well as companion read/write. So now I get some form of audio prompt when the trainer connects, while it's active, and when it disconnects (if the audio files are present). 

I just had a thought... we protect the user against being able to power down while USB connected or a telemetry RF link active... but not with the trainer active? Something to think about?

**Pull request merged**
