### PR TITLE
Eshifri/fix 792

### PR DESCRIPTION
**Pull request by eshifri**
This PR fixies #792 by re-drawing the model_setup window, when module window size is changed. (Not the most elegant solution, but works.)
It also adds NV14 internal RF module FW version to the radio_version tab.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@eshifri i‘d really prefer if we could find another trick. Apart from that, I believe this can be made to do funny things pretty easily. We should give us some time to find a more secure / better solution.

**Comment by raphaelcoeffic** [comment]
I think you should check `moveWindowsTop`. This does basically what you need: move all the windows by a certain amount (positive/negative) which are bellow a given point.

**Comment by eshifri** [comment]
I have tried this. The problem with this function is takes the existing window size. It moves the top and truncates the bottom.

**Comment by pfeerick** [comment]
Unfortunately its in the name isn't it... `moveWindowsTop` ... If am I understanding correctly here we want to increase the window height so you can keep scrolling down? Basically when either of the internal, external or trainer dropdown are used, the height is going to need to be recalculated, as it's either been decreased (from some ON state with options to OFF), or increased (OFF to some ON state with options. 

It would be better to do the NV14 internal module fw version display as a separate PR, that can probably be merged right away.

**Comment by kevinkoenig** [comment]
SetInnerHeight changes the scroll region, I think

**Comment by eshifri** [comment]
moveWindowsTop() actually works (if applied in the correct place :-) )

**Comment by raphaelcoeffic** [comment]
I believe you can even move it into the update() itself, instead of calling it right after update(). That would avoid some duplication.

**Comment by eshifri** [comment]
It is already present there and does nothing: the parent window needs to be resized after the update is executed.

**Comment by raphaelcoeffic** [comment]
> It is already present there and does nothing: the parent window needs to be resized after the update is executed.

I need to have a look at that to convince myself…

**Comment by pfeerick** [comment]
Please do, and then bang your head against the wall like a crazy person, raging against the machine 😆 . It's the very last line of the ModuleWindow `update()`, and is still doing *something* because without it, these changes don't work properly. 

https://github.com/EdgeTX/edgetx/blob/580b9b12bc6a10e7fde5a62ee5c819467c575803/radio/src/gui/colorlcd/model_setup.cpp#L1395

**Comment by eshifri** [comment]
Impressive! :-)

**Comment by pfeerick** [comment]
Hm... is this like a russian doll nesting issue? i.e. the heights of the ModuleWindow and TrainerModuleWindow need updating after their contents are changed, and then ModelSetupPage gets adjusted?

**Comment by raphaelcoeffic** [comment]
This works for me as a complete fix for the issue:
```diff
diff --git a/radio/src/gui/colorlcd/model_setup.cpp b/radio/src/gui/colorlcd/model_setup.cpp
index 9d499ddef..b8743ef18 100644
--- a/radio/src/gui/colorlcd/model_setup.cpp
+++ b/radio/src/gui/colorlcd/model_setup.cpp
@@ -673,7 +673,9 @@ class TrainerModuleWindow : public FormGroup
 #if defined(HARDWARE_TOUCH)
       new StaticText(this, grid.getLabelSlot(true));
 #endif
-      getParent()->moveWindowsTop(top() + 1, adjustHeight());
+      auto p = getParent();
+      p->moveWindowsTop(top() + 1, adjustHeight());
+      p->adjustInnerHeight();
     }
   }
 
@@ -1392,7 +1394,9 @@ class ModuleWindow : public FormGroup {
         grid.nextLine();
       }
 
-      getParent()->moveWindowsTop(top() + 1, adjustHeight());
+      auto p = getParent();
+      p->moveWindowsTop(top() + 1, adjustHeight());
+      p->adjustInnerHeight();
     }
 
     void checkEvents() override
```

Did I miss something obvious?

I guess we could integrate it into some more generic class afterwards so it can be used by more places automatically anytime `update()` is called.

**Comment by eshifri** [comment]
Yes, it works.

**Comment by pfeerick** [comment]
Cool! 🥇 That works just nicely... no more nasty page resize or nuttin'... just works! 👍

**Comment by pfeerick** [comment]
Right, just played with this a bit more on the NV14, and the module section is working perfectly. For trainer, what do you think of this change? Basically just moving the update padding out from the `if (g_model.isTrainerTraineeEnable())` function, and having it as main part of `update()`... As I noticed because the NV14 has 'Off' as an option, if you went from say 'Slave/Jack' to 'Off' it behaved differenlty to 'Slave/Jack' off. 



```diff
diff --git a/radio/src/gui/colorlcd/model_setup.cpp b/radio/src/gui/colorlcd/model_setup.cpp
index 79c2acf59..8d13dd937 100644
--- a/radio/src/gui/colorlcd/model_setup.cpp
+++ b/radio/src/gui/colorlcd/model_setup.cpp
@@ -668,14 +668,14 @@ class TrainerModuleWindow : public FormGroup
                    GET_SET_DEFAULT(g_model.trainerData.pulsePol));
         grid.nextLine();
       }
-
+    }
 #if defined(HARDWARE_TOUCH)
-      new StaticText(this, grid.getLabelSlot(true));
+    new StaticText(this, grid.getLabelSlot(true));
 #endif
-      auto par = getParent();
-      par->moveWindowsTop(top() + 1, adjustHeight());
-      par->adjustInnerHeight();
-    }
+
+    auto par = getParent();
+    par->moveWindowsTop(top() + 1, adjustHeight());
+    par->adjustInnerHeight();
   }
 
  protected:
```

**Comment by eshifri** [comment]
Absolutely! Thank you!
I was puzzled by this discrepancy for quite some time.

**Review by pfeerick — APPROVED** [review]
Just waiting on green ticks before merging. Works perfectly for me on NV14 and TX16S.

**Pull request merged**
