### PR TITLE
fix: MT12 ghost trim entries

### LINKED ISSUE #4615: Cursor  in Drive Mode disappears
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If the cursor is set to the 5th trim position (:0) and the menu wheel is rotated to the next option, the cursor disappears for 3 ticks 

### Expected Behavior

the next item after the 5th trim should be "Fade in"

### Steps To Reproduce

- Open the Drive Modes
- select the 5th trim
- roll to the next option
- --> the cursor is not visible anymore

after rotating the menu wheel four times, the cursor is at "Fade in"  

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster MT12

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

version: a0ccea1c (2024-02-07)

### PR DESCRIPTION
**Pull request by 3djc**
Fixes #4615

Now automatically adapt to trim number

### CODE REVIEW

**Review by pfeerick — CHANGES_REQUESTED** [review]
This fixes the "ghost trims", but backfires on TXs like Pocket which only have four trims / so one line of trims, resulting in GV1 be skipped over.

**Comment by philmoz** [comment]
Maybe needs this:
```
  static const uint8_t mstate_tab_fm1[]  = {0, 3, 
#if defined(TRIMS_GPIO_REG_T5L) || defined(TRIMS_GPIO_REG_LSD)
  (uint8_t)max(0, keysGetMaxTrims() - 5),
#endif
  0, 0, (uint8_t)-1, 1, 1, 1, 1, 1, 1};
  static const uint8_t mstate_tab_others[]  = {0, 0, 3, 
#if defined(TRIMS_GPIO_REG_T5L) || defined(TRIMS_GPIO_REG_LSD)
  (uint8_t)max(0, keysGetMaxTrims() - 5),
#endif
  0, 0,(uint8_t)-1, 2, 2, 2, 2, 2};
```

**Comment by 3djc** [comment]
Yep, that does it, I wanted to remove that ifdef, but it opens a can of worm

**Review by pfeerick — APPROVED** [review]
Yup, that seems to be good on Pocket, MT12 and T20. Thanks! :)

**Pull request merged**
