### PR TITLE
Allow Touch Screen Mod on Horus X10 Transmitters

### LINKED ISSUE #4114: Touch Screen Mod for the Horus X10 / X10S
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe the solution you'd like

With the availability to mod the other color LCD radios and add the TX16S touch panel (Horus X12, Jumper T16, and T18)
I'm looking to add the touch panel to the X10 series of transmitters.

It appears that the same mod as done for the Jumper T16 should work on the X10 / X10S.
The firmware would need to be modified to allow these radios the ability for an added touch panel.

I have already attempted this firmware and hardware mod on an X10 (non Express) and have made the changes as was done to add touch to the Jumper T16 on PR #2060 
The radio will start with just the firmware changes and it also shows (although not working) Touch GT911 on the Hardware Analogs screen.
After the hardware mod is done, as on the T16, the radio starts with only "Wrong PCB Detected" on screen and will shut off normally with power button.
Changing back the SCL, SDA lines modded from pull up (3.3V) back to pull down (Ground) the TX will now start normal.
I'm missing something that is causing Pin 97 (PH.07) and pin 98 (PH.08) either floating or pulled up to cause this error.

Any advice?
Thanks - Rich

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MRC3742**
Fixes #4114 

Changes to allow the Touch Screen Mod for the Horus X10 Series of Transmitters.
This Mod requires some soldering directly to the MCU processor pins as no other connection points are available! 

This is very similar to the already documented Jumper T16 Mod (PR #2060) that has been successfully added to EdgeTX.
The X10 / X10S Standard (NOT EXPRESS) radios need an additional pull down 1K resistor attached to MCU pin 55 (PA6)
This will allow the firmware to pass the PCBREV check as intended to distinguish between Standard or EXPRESS mainboards.

The X10 / X10S EXPRESS radios do not need this additional pulldown as they will already pass the check after installing the Mod.

Rich

### CODE REVIEW

**Comment by pfeerick** [comment]
I'm just going to push a rebase of this to remove the unrelated commits. As a side note, this really should have been targeted for the `main` branch, not 2.9.

**Comment by pfeerick** [comment]
@raphaelcoeffic Your thoughts? It looks ok to me, just checking before I press that adorable green button...

**Comment by MRC3742** [comment]
Thanks - I was trying to rebase this PR and................... well you see what happened !!!

I have also tested this PR using the main branch and it works correctly on my Horus X10 (Now with IPS Touch Screen)

Thanks Again - Rich

**Comment by pfeerick** [comment]
lol... no problem... `rebase` can lead to some quite ... interesting... results sometimes.

Glad to hear it, and thanks for the photos and notes in the issue documenting it (will have to add to that to the wiki)... I expect this should be in tomorrow unless some French dude has any grievances... 🤭

**Comment by MRC3742** [comment]
OK - I'll add a little more detail in that issue documenting the upgrade that is being added  :pray:  by this PR. 

Rich

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by robustini** [comment]
@MRC3742 please make changes to the PCB reconnaissance system because this mod conflicts with the "multi trainer" option, which contemplates removing a pin from the ISRM module, which is easy to do, and which many people have done and I still use in the OpenTX era.
The result is that my X10S Express now reports "Wrong PCB" at power-up, now the firmware thinks I applied the lcd modification, wrong.
I don't understand why, since the lcd mod is quite complicated, instead of doing the pcb check you didn't leave a compile flag, would have been better imho, or PCB reconnaissance does not have to be done if the firmware is compiled with "-DALLOW_TRAINER_MULTI=YES" as in my case.
Please fix this, thank you.

immagine

**Pull request merged**
