### PR TITLE
Color LCD: Added CN/TW translation and reduced TW text size

### PR DESCRIPTION
**Pull request by zyren**
Added CN/TW translation and reduced TW text size.
Because the TW text causes the firmware to exceed the flash size, reduce the text size.

### CODE REVIEW

**Comment by pfeerick** [comment]
Thanks! :) So setting the brownout on the TX16S has helped?

**Comment by zyren** [comment]
> Thanks! :) So setting the brownout on the TX16S has helped?

Yes, it is very helpful. This kind of problem is extremely unlikely to cause it to fail to boot. The RTC battery must be removed and installed to restore it.
In addition, if you press the power button quickly and continuously, the system will not boot. After repeating such problems many times, it is determined that modifying the BOR level can avoid such failures.

**Comment by TheIsotopes** [comment]
@pfeerick this should also get a cherry pick into 2.7

**Comment by raphaelcoeffic** [comment]
> @pfeerick this should also get a cherry pick into 2.7

When the milestone is set to "2.7", that means it will be cherry-picked ;-)

**Comment by pfeerick** [comment]
Yes, and unless it's a critical fix I usually leave the cherry-pick for a day or so to give anyone on the nighties a chance to scream bug so it doesn't need to be fixed twice :) Not that this particular one is likely to result in that. But please do yell at me if any that are marked as 2.7 and don't make it over within a couple of days...

**Pull request merged**
