### PR TITLE
Resolve a problem in font generation when y_offset is negative.

### LINKED ISSUE #1199: compiled in spanish have a line above
compiled in Spanish all the text comes out with a line above it

RM TX16S

2.5 , 2.6
IMG_20211201_205004
.
IMG_20211201_205029
IMG_20211201_205119

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #1199

Summary of changes:
- fixed a problem in font bitmap generation when y_offset is negative
- fixed missing special char because of hardcoded list (use dynamic list instead just like cjk) only for color radios
- isolated encoding method for B/W radios
- fixed B/W radio encoding based on the fixed fonts

### CODE REVIEW

**Comment by richardclli** [comment]
Found some char is wrong mapping in other languages, will try to fix as well.

**Comment by richardclli** [comment]
Can anybody help to test different languages?  This should fix all languages wrong char problem.

**Comment by pfeerick** [comment]
I can build a set of all of them if needed, but would need some native/bilingual people to actually test/read it...

**Comment by richardclli** [comment]
I will try to test a few one anyway.  It is interesting that this problem is here for some time but seems nobody reported this.

**Comment by richardclli** [comment]
And well, it should works anyway, now the CJK and other languages shared the same code in special character handling.  The differences are just the code mapping, CJK used 2 byte encoding while others use the remaining space besides standard and extended, and I checked the language that has the most special character (CZ) and it seems ok in the simulator.

**Comment by richardclli** [comment]
I have tested 5 languages in my TX16S (en, cn, tw, es, cz) , all looks good.  I think now need somebody to test the lowest config of a B/W radio with languages (en, es, and cz), and if these are ok, other languages should be good to go.

**Comment by richardclli** [comment]
@pfeerick As this will not affect B/W radios, I think it is good to merge now.

**Comment by pfeerick** [comment]
Sounds good to me... I'll give it a try later today and merge/cherrypick across.

**Comment by richardclli** [comment]
The old code tried to translate these Upper case to lower case:
    "Č": "č",
    "Ě": "ě",
    "Š": "š",
    "Ú": "ú",
    "Ů": "ů",
    "Ž": "ž"

Not sure about the purpose, but it seems no harm for not doing translations.

**Comment by pfeerick** [comment]
To me... these pictures say it all (before and after) :grin:

image
image
image

The lower case conversion may be used by the B&Ws... i.e. 

image

**Comment by richardclli** [comment]
Let me check the B/W font and see if Uppercase chars missing.  Umm......... B/W used fixed fonts, encoding may have a problem then.

**Comment by pfeerick** [comment]
Just another sample for you

image

**Comment by richardclli** [comment]
I think I will try to isolate B/W and color encoding method, based on the fonts used.

**Comment by richardclli** [comment]
I used a fixed encoding for B/W LCD that matches the font files, hope this solves the problems in B/W LCD.  @pfeerick Please help to do some tests.

**Comment by richardclli** [comment]
A few before/after images for cz and es, all looks good now.
IMG 000
IMG 001
IMG 008
IMG 009
IMG 012
IMG 013

**Review by pfeerick — APPROVED** [review]
LGTM on sampling a few languages and comparing with source text. Lets see if any nightly users complain! 😁

**Pull request merged**
