### PR TITLE
fix(lua): array indexes in some set/get functions

### LINKED ISSUE #976: LUA: model.setFlightMode() behaves weird setting trims
I tried to exclude the trims 5 and 6 (index 4 and 5) of flightmode 0 and 1.
Exclude has the mode value 31. 
Doing so via model.setFlightMode(...) sets all (!) trims except index 0 (trim1) to exclude from that mode.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
## Description

**Warning: this PR introduces a change in behaviour**

Prior to this change, `model.getFlightMode()` and `model.getCurve()` would return arrays with integer indexes starting at `0`, which breaks a lot of things with LUA. For instance, copying such an array removes the first element (index `0` is not copied).

**Summary of changes:**
- fixed array indexes in `model.getFlightMode()`
- fixed array indexes in `model.getCurve()`
- use array indexes to allow for incomplete table in `model.setFlightMode()`

Fixes #976

## Test LUA script

This script has been used to test the correctness of the changes.

```lua
local toolName = "TNS|TrimMode|TNE"
local lastEvent = ""
local eventTime = 0

-- String identifying events
local function evt2str(event)
  if event == EVT_VIRTUAL_PREV then return "EVT_VIRTUAL_PREV"
  elseif event == EVT_VIRTUAL_NEXT then return "EVT_VIRTUAL_NEXT"
  elseif event == EVT_VIRTUAL_DEC then return "EVT_VIRTUAL_DEC"
  elseif event == EVT_VIRTUAL_INC then return "EVT_VIRTUAL_INC"
  elseif event == EVT_VIRTUAL_PREV_PAGE then return "EVT_VIRTUAL_PREV_PAGE"
  elseif event == EVT_VIRTUAL_NEXT_PAGE then return "EVT_VIRTUAL_NEXT_PAGE"
  elseif event == EVT_VIRTUAL_MENU then return "EVT_VIRTUAL_MENU"
  elseif event == EVT_VIRTUAL_ENTER then return "EVT_VIRTUAL_ENTER"
  elseif event == EVT_VIRTUAL_MENU_LONG then return "EVT_VIRTUAL_MENU_LONG"
  elseif event == EVT_VIRTUAL_ENTER_LONG then return "EVT_VIRTUAL_ENTER_LONG"
  elseif event == EVT_VIRTUAL_EXIT then return "EVT_VIRTUAL_EXIT"
  else 
    local txt = string.format("Event = %i", event)
    return txt
  end
end

local function run(event)
  
  lcd.clear()

  if event ~= 0 then -- We got a new event
     -- Save the event for subsequent cycles and mark the time
     if event ==  EVT_VIRTUAL_ENTER then
        modes = {}
        modes[5] = 31
        modes[6] = 31
        t = {}
        t["trimsModes"] = modes
        model.setFlightMode(0, t)
        lastEvent = "DISABLE trim 5 & 6"
        -- end
     elseif event ==  EVT_VIRTUAL_MENU then
        fms = model.getFlightMode(0)
        print("trimsModes:")
        for i,m in ipairs(fms["trimsModes"]) do
           print(i, m)
        end
        t = {}
        t["trimsModes"] = fms["trimsModes"]
        model.setFlightMode(0, t)
        lastEvent = "IDENT set modes"
     elseif event ==  EVT_VIRTUAL_PREV_PAGE then
        curve = model.getCurve(0)
        print("Curve 0")
        print(" - Y points:")
        for i,m in ipairs(curve["y"]) do
           print("\t", i, m)
        end
        if curve["x"] then
           print(" - X points:")
           for i,m in ipairs(curve["x"]) do
              print("\t", i, m)
           end
        end
        model.setCurve(0, curve)
        lastEvent = "IDENT curve 0"
     elseif event ==  EVT_VIRTUAL_NEXT_PAGE then
        curve = {}
        curve["y"] = { -50, -25, 0, 25, 50 }
        model.setCurve(0, curve)
        lastEvent = "SET curve 0"
     else
        lastEvent = evt2str(event)
     end
     eventTime = getTime()
  end

  -- Show the last event for 1 sec. in the upper left corner
  if getTime() - eventTime < 100 then
    lcd.drawText(3, 3, lastEvent)
  end

  return 0
end

return {run = run}
```

### CODE REVIEW

**Comment by lshems** [comment]
How can I test? Is this available in companion sim or standalone sim? Can I download compiled companion for w64 somewhere for this pull request.
I want to be sure that the trims can be set in the entire range, as this was an issue as well.

Also, is it worth considering using a new function name for the getcurve()?

**Comment by raphaelcoeffic** [comment]
> How can I test? Is this available in companion sim or standalone sim? Can I download compiled companion for w64 somewhere for this pull request.

I started a companion build for you based on this branch: https://github.com/EdgeTX/edgetx/actions/runs/3259129140

> I want to be sure that the trims can be set in the entire range, as this was an issue as well.

What is the entire range?

> Also, is it worth considering using a new function name for the getCurve()?

`getCurve()` was completely broken. You cannot access the indexes of array that use integer indexes and do not start at `1`. So what is the point in leaving a broken function in the code?

**Comment by raphaelcoeffic** [comment]
> How can I test? Is this available in companion sim or standalone sim? Can I download compiled companion for w64 somewhere for this pull request.

You should really start to make yourself a working compilation environment if you are serious about participating / testing ;-)

You cannot expect people to always do it for you. Just like when you always say "I don't understand C/C++". You could learn it ;-) I know quite some folks who learned it even at advanced age (at least enough to understand how the LUA API function are coded). 

Look here for some documentation on how it works:
- https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-%28MSYS2%29
- https://github.com/EdgeTX/edgetx/wiki/Setting-up-Ubuntu-20.04-in-a-Windows-Subsystem-for-Linux

**Comment by gagarinlg** [comment]
We should really get simu going in a web browser.

**Comment by raphaelcoeffic** [comment]
> We should really get simu going in a web browser.

I'd be already happy with a simple `simu` that would not take hours to compile on Github... The biggest issue is really that the radio code needs to be loaded. Do you want to convert that to `WebASM`?? This is really not about just the UI.

**Comment by lshems** [comment]
I understand your point of view, and I even agree to it. I should learn a
lot of things.

I tried several times, and have no, I repeat no, people I can ask to sit
together and get things working.

I have spent about 100 hours spread over several occasions to set up test
environments, virtual machines, compiler toolkits, GitHub desktop
applications, Ubuntu machines.

I even tried to create help pages on what I've learned so that others could
enter more easily as well.

But every time I want to do something simple, I run into something small
that blocks me from doing it within a reasonable time.

Sorry, I have really tried, but to no avail.

I guess that leaves me without possibilities to test or contribute, other
than by giving my feedback and ideas on what I do understand.

I do not expect some special treatment or whatever. I will just have to
wait untill the things that don't work will get into a release and then
comment if the fix worked or not.

So be it. No hard feelings.

Op zo 16 okt. 2022 12:30 schreef Raphael Coeffic ***@***.***>:

**Comment by lshems** [comment]
I use getcurve without issues. Referencing the 0 element is not an issue as such?
Array[0] will work perfectly fine.

I did write a function myself in lua to work around the index shift.

I don't have an issue myself with changing the behaviour. I'll add a version check to my function, and my apps won't see the difference as they all call my workaround function.

Just thinking about others....

**Comment by raphaelcoeffic** [comment]
@lshems you are most probably the guy who uses the most of the LUA model API. I believe this is very seldom used.

Regarding the curve arrays: as soon as you copy the original array returned into a new variable, index `0` is absent from the copy. Same applies to the trims.

have you tried iterating though these arrays with `ipairs`? You won’t see index `0` either.

This is what I mean with “broken”. It needs so many work-around to work, that it cannot be considered working.

**Comment by gagarinlg** [comment]
@Ishems we can try vie TeamViewer or Teams to set it up together

**Comment by jfrickmann** [comment]
While I completely agree that Lua *should* have been using base 1 for indices from the beginning, you are really opening a can of worms here...  Basically every API function uses base 0 indices, and there will be a LOT of scripts blowing up and a lot of grief if we change it. Just my €0,02...

**Comment by raphaelcoeffic** [comment]
> Basically every API function uses base 0 indices

Really? I checked all of them, and this PR is the result. I'd be happy to have a look at others if you could give me a pointer.

**Comment by lshems** [comment]
> 

Thank you very much, really appreciated. But it ignores the other part of why I am impeded. For just about every thing I want to do I would need help. It would be like giving a synthesizer to a pianist. He would know how to play a tune, but not how to use it for creating the beat if he wanted to.

**Comment by jfrickmann** [comment]
You have to keep in mind that it is not just indices in tables, it is also indices passed to functions. Because otherwise, people have to "translate" inconsistent use of indices between different functions. A quick browse of the documentation found the following functions that would have to be changed:
```
getLogicalSwitchValue(id)
setStickySwitch(id, value)
model.getCurve(curve)
model.getCustomFunction(function)
model.getGlobalVariable(index, flight_mode)
model.getInput(input, line)
model.getInputsCount(input)
model.getLogicalSwitch(switch)
model.getMix(channel, line)
model.getMixesCount(channel)
model.getOutput(index)
model.getSensor(sensor)
model.getTimer(timer)
model.insertInput(input, line, value)
model.insertMix(channel, line, value)
model.resetSensor(sensor)
model.resetTimer(timer)
model.setCurve(curve, params)
model.setCustomFunction(function, value)
model.setGlobalVariable(index, flight_mode, value)
model.setLogicalSwitch(switch, value)
model.setModule(index, value)
model.setOutput(index, value)
model.setTimer(timer, value)
```
I am just saying that it will be a fair amount of work, but worse yet, a lot of arguing and explaining to the scripter community afterwards.

**Comment by raphaelcoeffic** [comment]
These are not LUA arrays... the IDs are internal to EdgeTX and not used in LUA arrays.

`model.getCurve(0)` will still give you the same curve as before.

**Comment by jfrickmann** [comment]
OK

**Comment by raphaelcoeffic** [comment]
The current erratic behaviour can be seen with this:
```lua
        fms = model.getFlightMode(0)
        print("trimsModes:")
        for i,m in ipairs(fms["trimsModes"]) do
           print(i, m)
        end
```

You should see only trim modes from `1` to `5` instead of `0` to `5` as they have been inserted into the table. However, when you set the trim modes, you table MUST start with index `1`, and this index will set `fm[0].mode`.

So at the very least, these functions should allow the "identity function" to work properly, which it does not. Try this out:
```lua
model.setFlightMode(0, model.getFlightMode(0))
```

This will effectively shift **all** the trims by 1 (values + modes). Same happens with curves.

**Comment by raphaelcoeffic** [comment]
> I started a companion build for you based on this branch: https://github.com/EdgeTX/edgetx/actions/runs/3259129140

@lshems your build has been ready for a couple hours now, Sir. Did you test it already?

**Comment by lshems** [comment]
OK, well, the new companion built killed all my curve functions, but ok, that's fine. I'll cope with that as described earlier (I still think a new name would be OK for lot's of people, better than changing the current behaviour).

Anyway, as far as the trims concerned, the issue that was troublesome, but not blocking, of the shifted indexes, is solved it seems. BUT ...

Trims seem to go from -128 to +128 on the simulator using the slider, which seems strange to me as I always thought they went to +/- 125.
if you want to assign -1 using LUA, it skips to 1023. There is still something funny going on that is not correct. Seems to be treated as an integer instead of neg integer. (I'm not into type, but this is how I wpoould describve it). 

Guido.

P.S. thanks for building. I really appreciate it, but I hope you also understand my point of view. I would have needed to spent several hours to get a valid build, trying to understand how GIThub pull requests etcetera work (I have never grasped that and always messed up any try to use it, even for my own code maintenance).. It is not worth it for me.

**Comment by Eldenroot** [comment]
@lshems - actually the building process is quite easy, set up takes 20 minutes? After that it is much easier... I was worried too but it is not difficult, just try :)

**Comment by lshems** [comment]
Let's not pollute any further. I've tried seriously,and concluded it's not for me.

I'll test on precompiled stuff if available and wait for releases otherwise.

Believe me, that's more annoying for me than for you.

**Comment by lshems** [comment]
All offers for help appreciated, bu thanks no thanks.

**Comment by raphaelcoeffic** [comment]
> Trims seem to go from -128 to +128 on the simulator using the slider, which seems strange to me as I always thought they went to +/- 125.

This has been changed a while ago.

> if you want to assign -1 using LUA, it skips to 1023. There is still something funny going on that is not correct. Seems to be treated as an integer instead of neg integer. (I'm not into type, but this is how I would describe it).

We would need LUA code that shows this behaviour. Please add a screenshot as well if necessary to show what you mean with "it skips to 1023".

**Comment by lshems** [comment]
replace the piece of code with this to SET a value to -125
`     elseif event ==  EVT_VIRTUAL_MENU then
        fms = model.getFlightMode(0)
        print("trimsValues:")
        for i,m in ipairs(fms["trimsValues"]) do
           print(i, m)
           fms.trimsValues[1] = -125
        end
        t = {}
        t["trimsValues"] = fms["trimsValues"]
        model.setFlightMode(0, t)
        lastEvent = "IDENT set values"
`

press three time menu and check the printed values and the trims on the simulated model

`trimsValues:
1	-128
2	0
3	0
4	0
149.81s: eeprom write model
149.81s: YAML model writer
149.82s: f_open(C:/Users/gterh/AppData/Local/Temp/etx-UYxnEO/MODELS/model00.yml, a) = 00007ffeca22fa90 (FIL 00000097cafff4c0)
149.82s: f_close(00007ffeca22fa90) (FIL:00000097cafff4c0)
trimsValues:
1	128
2	0
3	0
4	0
153.28s: eeprom write model
153.28s: YAML model writer
153.29s: f_open(C:/Users/gterh/AppData/Local/Temp/etx-UYxnEO/MODELS/model00.yml, a) = 00007ffeca22fa90 (FIL 00000097cafff4c0)
153.29s: f_close(00007ffeca22fa90) (FIL:00000097cafff4c0)
trimsValues:
1	899
2	0
3	0
4	0`

**Comment by lshems** [comment]
it skips from -128 (NOT -125 as expected) to some other weird numbers

**Comment by lshems** [comment]
while just writing the same value again???

**Comment by raphaelcoeffic** [comment]
> it skips from -128 (NOT -125 as expected) to some other weird numbers

- `-128` was set previously (probably by you)
- then you set it to `-125` (`0xFF83`), which gets constrained by the bit mask (`0xFF83 & 0x3FF = 0x838 = 899`)
- the same is set again and again.

The real issue is here was to constraint the value with a bit mask that was too small, rather than with the real `min / max` (depending on whether or not "extended trim" is used or not).

This code was probably never been tested properly (see the relevant commit: https://github.com/EdgeTX/edgetx/commit/fcedcb9c569725ade04ada47414fa1c47ee3929e).

**Comment by lshems** [comment]
So this part is fixed now? Is there a workaround for the current mask?

**Comment by raphaelcoeffic** [comment]
> So this part is fixed now? Is there a workaround for the current mask?

It is fixed now. I don’t think there is any trick to bypass the faulty behavior.

**Comment by lshems** [comment]
Ok. Thanks.

I hope the extra effort in the compilation was worth finding the issue that still remained.

Guido

**Comment by lshems** [comment]
> So at the very least, these functions should allow the "identity function" to work properly, which it does not. Try this out:
> 
> ```lua
> model.setFlightMode(0, model.getFlightMode(0))
> ```

Why not get rid of all these confusing get and set functions. One function would suffice for which the pseudo code would be:

```
function model.flightmode(index, param)
  if param~=nill then
    model.setFlightMode(index, param)
  end
  return model.getFlightMode(index)
end
```

changing only one parameter would be done by:
```
local fadeInSet
local userInput = 1
fadeInSet= model.flightMode(1,{fadeIn=userInput})
```

This would even allow for range checking and other input validation, and make sure your script is really in sync with the model settings, as if you would set userInput to something like 100000, the above script would update the fadeInSet to what was actually set, depending on treatment of the function on out of bound entries.

**Comment by raphaelcoeffic** [comment]
@lshems I'm sorry but I have troubles understanding the benefits of changing the API here. Is that about saving a couple characters when typing the code?

IMHO, the new API function you are proposing is using **implicit** conventions, which is something considered a bad design choice. The difference between a **read-only** and **write** access is massive.

When calling the function, you will have to decide whether to include that parameter or not anyway, thus basically choosing between `set` and `get` (`read` and `write` if you prefer).

**Comment by lshems** [comment]
Never mind. It would just cut the number of necessary functions in halve. Returning the set value after a write is not bad practice in my opinion,but very practical if a function has limited allowed input borders and will either simply set to the highest when overrun or to the lowest when underrun. It prevents returning and managing errorcodes if out of range and the need to document those errorcodes (to low, to high,...). Omitting a parameter for a function to write something should always default to nothing being done.

But again. Never mind.

**Comment by raphaelcoeffic** [comment]
> cut the number of necessary functions in halve

The number of functions is not an issue for the firmware, no worry.

**Pull request merged**
