### PR TITLE
fix(mpm): update internal module

### LINKED ISSUE #2310: Internal MPM update not possible
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

internal MPMs can not be updated, TX12 MKII reverts back to the main screen (with emergency mode indicator), TX16S enters emergency mode

### Expected Behavior

MPMs should be updatable

### Steps To Reproduce

1. enter SD card menu
2. enter FIRMWARE directory
3. select MPM firmware
4. select update

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX12 / TX12MK2, Radiomaster TX16S

### Anything else?

probably all transmitters with internal MPM have the same issue

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #2310 

Summary of changes:
- fix DMA fifo `clear()`
- fix MPM update UART context reset

### CODE REVIEW

**Comment by pfeerick** [comment]
- [x] TX16 /w internal MPM = SD update success, MPM reports FW verison
- [x] Zorro /w internal MPM = SD update successful, MPM reports FW version, bound to a Flysky receiver, and RX telemetry working
- [x] Zorro /w internal ELRS = passthrough update successful, responding to ELRS Lua, sticks are still controlling my USB ELRS adapter...
- [x] TX12 /w int CC2500-MPM - same as Zorro /w MPM, Frsky RX
- [x] TX12MK2 /w int. ELRS - same as Zorro /w ELRS

**Comment by zyren** [comment]
Thanks for repairing this important function. After testing, it is normal to update internal Multi on TX12MK2, but it still fails to update external multi, and the pop-up prompt is still: Device not responding.

**Comment by pfeerick** [comment]
TX12 /w external MPM, updated from 1.3.3.7 => 1.3.3.14 was successful
TX12MK2 /w external MPM, downgraded from 1.3.3.14 => 1.3.3.7, upgraded back to 1.3.3.14

Any chance you hit Flash Int. Module instead of Flash Ext. Module? As this is the error you will get in that case. Also, is the module showing it's status when you go into the model settings? If not, maybe it's not plugged in properly / non-responsive.

**Comment by pfeerick** [comment]
This is getting merged now since it fixes a emergency mode trigger, as well as appears to have no other side effects. 🤞

**Pull request merged**
