### PR TITLE
Touch interface support for time-edit

### PR DESCRIPTION
**Pull request by eshifri**
This brings up virtual keyboard (NV14) for temer edit.
Also simplifies the code.
Tested on NV14 and RM TX16S.

I do not understand what is going on with commits: every  time I rebase my main stream it is shown as new commit.
Sorry about inconvenience.

### CODE REVIEW

**Comment by pfeerick** [comment]
> I do not understand what is going on with commits: every time I rebase my main stream it is shown as ne commit.
> Sorry about inconvenience.

That is fine, and is expected when you merge, instead of rebase. Merge gets the current state of the branch, and updates yours accordingly. What is more important is if you now look at the files changed - only the ones you have actually changed are listed. ;)

Think of it like this. If you start a PR, you are branching off of a repo branch at point 1. In the mean time, changes are made to the source branch (lets call that points 2, 3 and 4, as there have been three commits in this scenario since you made your PR branch), so you want to update your branch to suit. You can either do a merge, which pulls in the changes at points 2,3 and 4. Since it is a merge, it has shows up as a commit. You're up to date, everything is good.

Alternately, you could do rebase. What git will try and do is look at your PR branch, and see that it breaks away from the source branch at commit 1, and is now at commit 4 (i.e. points in time). It will remove the commits you've saved, fast-forward your branch to commit 4, and then attempt to reapply your commits. Assuming there have been no changes in the main branch to that same part of the code, it will go smoothly. If there has been a change, you get a conflict, and have to resolve it. Either way, once the rebase is complete, it is now as if you had done ("based") your PR from commit 4 of the source branch. If it were a local branch you were working on on your own machine, this would be the end of the issue. But, because it's been pushed to a remote server (GitHub), you now need to force-push the changes to github, so that it knows your branch starts from commit 4, and not commit 1. 

It's not "simple", but once you've done it a few times, it will make perfect sense, and you'll wonder why you didn't do it this way before (since for starters, it gets rid of the noise of the merge commits)! 😆

**Comment by pfeerick** [comment]
btw, I wouldn't try rebasing on this PR now since you've got the merge commits - and I don't know what git would do with them now. Next time you have a small/simple PR that has 'fallen behind' the source branch (`main`) and want to get it up to date, try it out then.

**Comment by eshifri** [comment]
Thank you for the explanation, but I did rebase for the main branch in my repository. I have rebased main on main. Directly on the github. And my repository shows this rebase as new commit.

**Comment by pfeerick** [comment]
How did you do it? As a rebase does *not* leave a commit, only a merge does.

**Comment by eshifri** [comment]
Another request submitted.

**Pull request closed without merging**
