### PR TITLE
YAML: Quote stick names

### LINKED ISSUE #1749: Companion : Error reading hardware stick name with special character
**Describe the bug**
_At least on Jumper T-Pro_ :
When setting a name for a stick in Hardware page, Companion can't read the config from radio.yml if there is a special character.
When setting from Companion Hardware tab, YAML file is saved / written without error on the radio.

**To Reproduce**
In radio : Set "-" as a name for Rud stick in Hardware page.
In companion : read configuration from the radio

**Expected behavior**
Read configuration without error

**Screenshots**
Capture d’écran 2022-03-28 à 10 28 33

**General information**
main branch 2.7.0
YAML generated by Radio
```
 sticksConfig: 
   0:
      name: -
```

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #1749

### CODE REVIEW

**Comment by pfeerick** [comment]
So close, yet so far! 😆 

So, conversion from 2.5, and reading yaml in 2.7 companion was fine. However, it looks like somewhere in the UI code it like to mangle stuff...

image

is not

image
 
(that's the sticks in TAER order), and isn't just the sticks. 

[PR1754.zip](https://github.com/EdgeTX/edgetx/files/8370406/PR1754.zip)

**Comment by pfeerick** [comment]
So close, yet so far! 😆 

So, conversion from 2.5, and reading yaml in 2.7 companion was fine. However, it looks like somewhere in the UI code it like to mangle stuff...

image

is not

image
 
(that's the sticks in TAER order), and isn't just the sticks. 

[PR1754.zip](https://github.com/EdgeTX/edgetx/files/8370406/PR1754.zip)

**Comment by pfeerick** [comment]
So close, yet so far! 😆 

So, conversion from 2.5, and reading yaml in 2.7 companion was fine. However, it looks like somewhere in the UI code it like to mangle stuff...

image

is not

image
 
(that's the sticks in TAER order), and isn't just the sticks. 

[PR1754.zip](https://github.com/EdgeTX/edgetx/files/8370406/PR1754.zip)

**Comment by raphaelcoeffic** [comment]
This looks to me like another bug, probably related to the way *potentially-null-terminated-strings* are handled in UI.

**Comment by raphaelcoeffic** [comment]
@pfeerick I believe the issue you are pointing at is here:
https://github.com/EdgeTX/edgetx/blob/5cdff7220559d8a04a2759d4bcb205465ba433a2/radio/src/strhelpers.cpp#L616-L617

The issue here is that only the destination buffer size is considered, and not the source. @wimalopaan I believe you should have a look at this.

**Comment by raphaelcoeffic** [comment]
I found a couple others in the same function:
```diff
diff --git a/radio/src/strhelpers.cpp b/radio/src/strhelpers.cpp
index 404ff88ab..d4627198d 100644
--- a/radio/src/strhelpers.cpp
+++ b/radio/src/strhelpers.cpp
@@ -613,8 +613,9 @@ char *getSourceString(char (&dest)[L], mixsrc_t idx)
       }
 
       idx -= MIXSRC_Rud;
-      memcpy(dest + 1, g_eeGeneral.anaNames[idx], L - 1);
-      dest[L - 1] = '\0';
+      size_t ana_len = std::min(L - 2, sizeof(g_eeGeneral.anaNames[idx]));
+      strncpy(dest + 1, g_eeGeneral.anaNames[idx], ana_len);
+      dest[ana_len] = '\0';
     } else {
       idx -= MIXSRC_Rud;
       getStringAtIndex(dest, STR_VSRCRAW, idx + 1);
@@ -625,8 +626,9 @@ char *getSourceString(char (&dest)[L], mixsrc_t idx)
   } else if (idx <= MIXSRC_LAST_SWITCH) {
     idx -= MIXSRC_FIRST_SWITCH;
     if (g_eeGeneral.switchNames[idx][0] != '\0') {
-      strncpy(dest, g_eeGeneral.switchNames[idx], LEN_SWITCH_NAME);
-      dest[LEN_SWITCH_NAME] = '\0';
+      size_t sw_len = std::min(L - 1, sizeof(g_eeGeneral.switchNames[idx]));
+      strncpy(dest, g_eeGeneral.switchNames[idx], sw_len);
+      dest[sw_len] = '\0';
     } else {
       getStringAtIndex(dest, STR_VSRCRAW,
                        idx + MIXSRC_FIRST_SWITCH - MIXSRC_Rud + 1);
@@ -647,9 +649,10 @@ char *getSourceString(char (&dest)[L], mixsrc_t idx)
                          MAX_GVARS);
   } else if (idx <= MIXSRC_LAST_TIMER) {
     if (g_model.timers[idx - MIXSRC_FIRST_TIMER].name[0] != '\0') {
-      strncpy(dest, g_model.timers[idx - MIXSRC_FIRST_TIMER].name,
-              L - 1);
-      dest[L - 1] = '\0';
+      uint8_t tim_idx = idx - MIXSRC_FIRST_TIMER;
+      size_t tim_len = std::min(L - 1, g_model.timers[tim_idx].name);
+      strncpy(dest, g_model.timers[tim_idx].name, tim_len);
+      dest[tim_len] = '\0';
     } else {
       getStringAtIndex(dest, STR_VSRCRAW,
                        idx - MIXSRC_Rud + 1 - MAX_LOGICAL_SWITCHES -
```

**Comment by wimalopaan** [comment]
I would like to introduce a helper function for that purpose instead of copy-n-paste.
And this you be a template that does the calculation at compile-time.

@raphaelcoeffic did you fixed that already?

**Comment by wimalopaan** [comment]
Maybe this would help:

```
template<size_t N>
using offset_t = std::integral_constant<size_t, N>;

template<size_t DL, size_t SL, size_t O = 0>
void copyToTerminated(char (&dest)[DL], const char (&src)[SL], const offset_t<O> = offset_t<0>{}) {
//    static constexpr size_t len = std::min(DL - O - 1, SL); // unfortinately std::min() isn't constexpr in C++11
    static constexpr size_t dl{DL - O - 1};
    static constexpr size_t len = (dl < SL) ? dl : SL; 
    strncpy(&dest[O], &src[0], len);
    dest[len] = '\0';
}
```

And it can be used as:

`copyToTerminated(dest, g_eeGeneral.anaNames[idx], offset_t<1>{});
`

instead of 

```
      size_t ana_len = std::min(L - 2, sizeof(g_eeGeneral.anaNames[idx]));
      strncpy(dest + 1, g_eeGeneral.anaNames[idx], ana_len);
      dest[ana_len] = '\0';
```

This can be used for all other occurences.

@raphaelcoeffic Should I do this, or is this too much use of templates?

**Comment by pfeerick** [comment]
For what it is worth... this does seem to be doing the right thing for me in the GUI on simu... and my choice of termination value for each case was only based on "what didn't put garbage at the start or trim the end"... nothing more... 

```diff
diff --git a/radio/src/strhelpers.cpp b/radio/src/strhelpers.cpp
index 404ff88ab..3d02e5198 100644
--- a/radio/src/strhelpers.cpp
+++ b/radio/src/strhelpers.cpp
@@ -549,6 +549,17 @@ char *getSwitchPositionName(char *dest, swsrc_t idx)
   return dest;
 }
 
+template<size_t N>
+using offset_t = std::integral_constant<size_t, N>;
+
+template<size_t DL, size_t SL, size_t O = 0>
+void copyToTerminated(char (&dest)[DL], const char (&src)[SL], const offset_t<O> = offset_t<0>{}) {
+//    static constexpr size_t len = std::min(DL - O - 1, SL); // unfortinately std::min() isn't constexpr in C++11
+    static constexpr size_t dl{DL - O - 1};
+    static constexpr size_t len = (dl < SL) ? dl : SL;
+    strncpy(&dest[O], &src[0], len);
+    dest[len] = '\0';
+}
 
 // this should be declared in header, but it used so much foreign symbols that we declare it in cpp-file and pre-instantiate it for the uses
 template<size_t L>
@@ -613,8 +624,7 @@ char *getSourceString(char (&dest)[L], mixsrc_t idx)
       }
 
       idx -= MIXSRC_Rud;
-      memcpy(dest + 1, g_eeGeneral.anaNames[idx], L - 1);
-      dest[L - 1] = '\0';
+      copyToTerminated(dest, g_eeGeneral.anaNames[idx], offset_t<0>{});
     } else {
       idx -= MIXSRC_Rud;
       getStringAtIndex(dest, STR_VSRCRAW, idx + 1);
@@ -625,8 +635,7 @@ char *getSourceString(char (&dest)[L], mixsrc_t idx)
   } else if (idx <= MIXSRC_LAST_SWITCH) {
     idx -= MIXSRC_FIRST_SWITCH;
     if (g_eeGeneral.switchNames[idx][0] != '\0') {
-      strncpy(dest, g_eeGeneral.switchNames[idx], LEN_SWITCH_NAME);
-      dest[LEN_SWITCH_NAME] = '\0';
+      copyToTerminated(dest, g_eeGeneral.switchNames[idx], offset_t<0>{});
     } else {
       getStringAtIndex(dest, STR_VSRCRAW,
                        idx + MIXSRC_FIRST_SWITCH - MIXSRC_Rud + 1);
@@ -647,9 +656,7 @@ char *getSourceString(char (&dest)[L], mixsrc_t idx)
                          MAX_GVARS);
   } else if (idx <= MIXSRC_LAST_TIMER) {
     if (g_model.timers[idx - MIXSRC_FIRST_TIMER].name[0] != '\0') {
-      strncpy(dest, g_model.timers[idx - MIXSRC_FIRST_TIMER].name,
-              L - 1);
-      dest[L - 1] = '\0';
+      copyToTerminated(dest, g_model.timers[idx - MIXSRC_FIRST_TIMER].name, offset_t<0>{});
     } else {
       getStringAtIndex(dest, STR_VSRCRAW,
                        idx - MIXSRC_Rud + 1 - MAX_LOGICAL_SWITCHES -

```

**Comment by wimalopaan** [comment]
@pfeerick I think the offset for the first one is wrong, ist should be `offset_t<1>{}` ?

Side note: `offset_t<0>{}` can be omitted on the call site (its default).

The function `copyToTerminated(...)` misses at least one `static_assert`, I'll introduce that:

```
template<size_t DL, size_t SL, size_t O = 0>
void copyToTerminated(char (&dest)[DL], const char (&src)[SL], const offset_t<O> = offset_t<0>{}) {
//    static constexpr size_t len = std::min(DL - O - 1, SL); // unfortinately std::min() isn't constexpr in C++11
    static constexpr size_t dl{DL - O - 1};
    static_assert(dl > 0, "wrong sizes or offset");
    static constexpr size_t len = (dl < SL) ? dl : SL; 
    strncpy(&dest[O], &src[0], len);
    dest[len] = '\0';
}
```

**Comment by wimalopaan** [comment]
What would be the correct workflow in this case: should I create a PR from this PR/branch. Or should @raphaelcoeffic just use the proposed changes ...?

**Comment by pfeerick** [comment]
> @pfeerick I think the offset for the first one is wrong, ist should be `offset_t<1>{}` ?

Nope... not unless you *want* to cut the last character off. 

> and my choice of termination value for each case was _**only**_ based on "what didn't put garbage at the start or trim the end"... nothing more...

image

image

**Comment by wimalopaan** [comment]
Just tried that on simulator28 and it works correct now.

**Comment by wimalopaan** [comment]
Sorry, not my day today: I did the testing with the wrong version, so i missed the error.
Please use:
```
template<size_t DL, size_t SL, size_t O = 0>
void copyToTerminated(char (&dest)[DL], const char (&src)[SL], const offset_t<O> = offset_t<0>{}) {
//    static constexpr size_t len = std::min(DL - O - 1, SL); // unfortinately std::min() isn't constexpr in C++11
    static constexpr size_t dl{DL - O - 1};
    static_assert(dl > 0, "wrong sizes or offset");
    static constexpr size_t len = (dl < SL) ? dl : SL; 
//    std::integral_constant<size_t, SL>::_;
//    std::integral_constant<size_t, DL>::_;
//    std::integral_constant<size_t, len>::_;
    strncpy(&dest[O], &src[0], len);
    static_assert((len + O) < DL);
    dest[len + O] = '\0';
}
```

**Comment by pfeerick** [comment]
Lovely. I was going to say this PR is getting merged now as I didn't realise at the time the issue being discussed already affected main - just I noticed it when testing this PR. We'll review #1770 today and hopefully merge it for the next nightly unless something curly arises.

**Pull request merged**
