### PR TITLE
chore(color): Reduce font FLASH storage.

### PR DESCRIPTION
**Pull request by philmoz**
Enabling RLE compression and reducing the font to 3 BPP (from 4 BPP) saves a chunk of FLASH.

For EN it saves 39096 bytes.
For TW it saves 143144 bytes.

I don't think there is any noticeable degradation in quality.

EN - current font:
en curr

EN - 3 BPP font:
en 3bpp

TW - current font:
tw curr

TW - 3 BPP font:
tw 3bpp

### CODE REVIEW

**Comment by philmoz** [comment]
I tried 2 BPP as well.
While this would save another 106584 bytes for the TW fonts, I think there is a noticeable degrading of the image.

tw 2bpp

**Comment by raphaelcoeffic** [comment]
The main downside is that it is slower to draw, but maybe it's not that bad. Possibly this can be enabled only for the bigger fonts?

**Comment by philmoz** [comment]
Do you know which has more impact on performance - RLE compression or bit depth?

**Comment by raphaelcoeffic** [comment]
Probably bit depth, but I did not try it out.

**Comment by philmoz** [comment]
> The main downside is that it is slower to draw, but maybe it's not that bad. Possibly this can be enabled only for the bigger fonts?

Unfortunately RLE compression slows down text rendering a lot. Should have tested this, thanks for the heads up.
And RLE compression is required to use 3BPP so that's a bust as well.

Back to the drawing board.

**Comment by philmoz** [comment]
Attempt 2.

STD, BOLD, XS and XXS fonts reverted to original settings.
L, XL and XXL fonts changed to 2 BPP.

The difference is not noticeable to me on the TX16S screen.

Space saving on TX16S:
- EN - 34448 bytes
- TW - 132424 bytes

I've also removed a bunch of unused font files.

**Comment by gagarinlg** [comment]
The larger fonts look a bit rougher at the edges, but I do not think that that is an issue.
The biggest issues are obviously with the asian fonts. When they are still readable, the latin alphabet + language specific charcters should be OK

**Comment by philmoz** [comment]
CN comparison images:

L 4BPP
CN L 4BPP

L 2 BPP
CN L 2BPP

XL 4 BPP
CN XL 4BPP

XL 2 BPP
CN XL 2BPP

CN XXL font does not contain language characters.

**Comment by gagarinlg** [comment]
> CN XXL font does not contain language characters.

Yes, because it would too much flash memory

**Comment by philmoz** [comment]
Is the XXL font actually used by anything?
I can't see any usage of it in the code.

**Comment by 3djc** [comment]
Ins't it accessible to LUA ?

**Comment by raphaelcoeffic** [comment]
> Ins't it accessible to LUA ?

That's it. I had it removed at first, but then folks started to complain because of the Battery/Timer LUA widget using the font.

**Comment by JimB40** [comment]
Maybe then XXL should have numbers and special chars

**Comment by philmoz** [comment]
Version 3.

This removes the L, XL and XXL fonts from the firmware and loads them from SD card files instead.

Benefits:
- All fonts are stored uncompressed. Compressed fonts take more than twice as long to render so this gives a performance boost when using these fonts.
- L, XL and XXL fonts contain all the same language and special characters as the STD font.
- FLASH space saving - 93K for EN, 325K for TW.

Note: this requires the contents of the attached ZIP file to be stored on the SD card in a FONTS folder.

[FONTS.zip](https://github.com/EdgeTX/edgetx/files/12222592/FONTS.zip)

**Comment by philmoz** [comment]
Storing fonts on the SD card might open up the possibility of having all languages built into the firmware.

If we move all but a basic STD font out of the firmware there might be room for all the language translation strings.
Users could then select their language and the language specific fonts could be loaded from the SD card.

**Comment by pfeerick** [comment]
🤣 Damn you! I had literally just written a comment saying that IMO this was looking to be opening the door up to a long-term goal of having all the translations on the SD card - i.e. single language firmware. i.e. yes, keep just one core font in the firmware to guarantee the ability to show text on screen if the SD content is missing for any reason, and then everything else is on the SD. Were you looking over my shoulder or ears burning just then? 🤣 🤣

**Comment by philmoz** [comment]
Great minds think alike :)

**Comment by gagarinlg** [comment]
This is something Raphael and I were already planning a few months ago. We should start to write down those ideas somewhere.
The idea was to implement something that is able to use gettext files.
For the B&W radios the gettext run could be done at compile time and for the quicker radios at runtime.
If the 429 is quick enough or if we have to wait for 7 series MCU has to be tested.

**Comment by pfeerick** [comment]
> We should start to write down those ideas somewhere.

Indeed... the Projects tab would be an excellent place to start...  one of these days🤭

**Comment by gagarinlg** [comment]
I should add that this before @philmoz was as involved as he is now, so there were less people wotking on this kind of changes.

**Comment by pfeerick** [comment]
This is looking really good on TX16S just for EN (~93k reduction in FLASH usage), let alone a more complex symbol set like CN...
```
Totals         KB    usage  of ttl      KB free
  Flash:  1483.18   72.42%    2048       564.82 (rebased PR)
  Flash:  1389.87   67.86%    2048       658.13 (main)
```
with negligible increase in SRAM usage. Will be poking and prodding tomorrow.

**Comment by philmoz** [comment]
One thing this might affect is the EM display. As the XL font won't be in FLASH it may fall back to the STD font size.

Have not tested this.

**Review by pfeerick — APPROVED** [review]
It falls back to STD font size. Generally, this seems to work just fine. Obviously not going to get the larger fonts if the FONTS folder is missing. Yappu Telemetry and iNav Lua widgets and scripts were working just fine with this on TX16S. As far as I'm concerned, the tradeoff of 100kb vs EM screen large print is worth it... 

However, I'd like @raphaelcoeffic and/or @gagarinlg's second opinions.

**Comment by raphaelcoeffic** [comment]
> One thing this might affect is the EM display. As the XL font won't be in FLASH it may fall back to the STD font size.

Would be probably better to test it ;-) You should be able to setup a custom function that triggers EM (basically an empty endless loop that triggers the watchdog).

**Comment by pfeerick** [comment]
> Would be probably better to test it ;-) You should be able to setup a custom function that triggers EM (basically an empty endless loop that triggers the watchdog).

lol... I did that... that's why I said 

> It falls back to STD font size. 

😛

**Comment by pfeerick** [comment]
Damn camera wouldn't focus ...

image

**Comment by philmoz** [comment]
Added RU. 

Updated FONTS.zip file - contents must be in the FONTS folder on the SD card.

[FONTS.zip](https://github.com/EdgeTX/edgetx/files/13049466/FONTS.zip)

**Comment by pfeerick** [comment]
Barring any voices of dissent, this will be merged tonight.

**Comment by pfeerick** [comment]
Fonts are in the SD card repo now.

**Comment by HThuren** [comment]
@pfeerick @raphaelcoeffic @philmoz  - Any consideration regarding DA ?

**Comment by philmoz** [comment]
> @pfeerick @raphaelcoeffic @philmoz - Any consideration regarding DA ?

What considerations are you concerned about? Are there any issues?

**Comment by HThuren** [comment]
no issues, don't fully understand the compression, maybe same to be done for other languages, like DA.
if no, don't bother.

**Comment by philmoz** [comment]
> no issues, don't fully understand the compression, maybe same to be done for other languages, like DA. if no, don't bother.

I tried compression of the fonts initially to save space; but it was too slow.
All fonts are now stored uncompressed. The space saving comes from moving the large fonts to the SD card and loading into RAM at runtime.

**Pull request merged**
