### PR TITLE
fix: Some AFHDS2A/AFHDS3 GPS/ALT telemetry handling issues

### LINKED ISSUE #3543: widgets vs. sensors (TX16s/FS-IA6B FW2.8.3)
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Build system

### Current Behavior

I tried FW 2.8.3 for TX16s with RX FS-IA6B and it maps telemetry data to widgets incorrectly. This is a telemeter. data from the sensor of my construction. So I reverted back to FW 2.8.2 and everything works OK again.

### Expected Behavior

see above

### Steps To Reproduce

1. upload firmware 2.8.3 from https://github.com/EdgeTX/edgetx/releases/tag/v2.8.3

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### LINKED ISSUE #3583: V 2.8.3 Flysky FS-CAT01 altitude sensor
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I updatged from 2.8.1 to 2.8.3 and the FlySky Cat01 altitude sensors do not read correctly.  Initally they say + or - 2-3K meters. Will offset if units are 0-.  Data reads max altitude of over 20Km during any given flight and does not give any intermidate readings.   2.8.1 works fine.

### Expected Behavior

Should be able to offset ot "zero" and should transmit realtime data 0-1,000Ft, and properly record max altitude.  Works fine with V2.8.1

### Steps To Reproduce

4

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

2.8.3

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes (partially) #3543 
Fixes #3583

### CODE REVIEW

**Comment by ajjjjjjjj** [comment]
The root issue here is that FlySky "PREC7" is not really supported. In `convertTelemetryValue()` value is divided to lower precision from 7 to 2 effectively making: value /= 100000.

The easy fix is to lower precision from 7 to 2, so at least value is not truncated.

**Comment by pfeerick** [comment]
So where are things at with this PR now?

**Comment by richardclli** [comment]
Need more work for this.  Need somebody to help to compare the output of the same sensor connect via different equipments.

**Comment by pfeerick** [comment]
> Need somebody to help to compare the output of the same sensor connect via different equipments.

As in? AFHDS2 vs AFHDS3 receiver?

**Comment by richardclli** [comment]
> > Need somebody to help to compare the output of the same sensor connect via different equipments.
> 
> As in? AFHDS2 vs AFHDS3 receiver? Native vs MPM?

Yes, there are a few paths in the code:

1. AFHDS3 receiver connected to PL18 with Flysky firmware.
2. AFHDS3 receiver connected to EdgeTX radios with IRM301 or FRM303.
3. AFHDS2 receiver connected to EdgeTX NV14 with internal AFHDS2 module.
4. AFHDS2 receiver connected to EdgeTX radios with MPM.

**Comment by pfeerick** [comment]
So after some fiddling around, these are the results (with the current state of this PR, and either FS-iA6B or FTr12B RX, the same FS-CAT01 sensor mostly stationary on the desk, attempting to have similar power on and run times to minimise self-heat variability... was done in the order of this list which may explain some variance):

_AFHDS3 receiver connected to PL18 with Flysky firmware._
Started at 30m alt, drifted down to 25m over the course of a minute or two. Pressure not reported at all.

_AFHDS3 receiver connected to EdgeTX radios with IRM301 or FRM303._
Was able to bind, but only got two telemetry sensors? With another PR, I got all the sensors, and it was fairly stable around alt 25m, 1016.2 pressure

_AFHDS2 receiver connected to EdgeTX NV14 with internal AFHDS2 module._
Started around 25m, wandered down to 20m alt, 1016.11 pressure

_AFHDS2 receiver connected to EdgeTX radios with MPM._
Wandering between 19m to 22m, 1015.7 pressure


So, IMO, pressure was as consistent as it's going to be with these sensors (when reported). Altitude consistently went down the longer the sensor was connected, so it may be related to self-heat if the temperature is factored in as part of the calculation. While from start to end it's a variance of 10m, overall it's not excessively great a variance. I'm going to try the FRM303 again with a rebased version of this branch to see if telemetry was broken when this PR was started.

**Comment by richardclli** [comment]
> So after some fiddling around, these are the results (with the current state of this PR, and either FS-iA6B or FTr12B RX, the same FS-CAT01 sensor mostly stationary on the desk, attempting to have similar power on and run times to minimise self-heat variability... was done in the order of this list which may explain some variance):
> 
> _AFHDS3 receiver connected to PL18 with Flysky firmware._ Started at 30m alt, drifted down to 25m over the course of a minute or two. Pressure not reported at all.
> 
> _AFHDS3 receiver connected to EdgeTX radios with IRM301 or FRM303._ Was able to bind, but only got two telemetry sensors? With another PR, I got all the sensors, and it was fairly stable around alt 25m, 1016.2 pressure
> 
> _AFHDS2 receiver connected to EdgeTX NV14 with internal AFHDS2 module._ Started around 25m, wandered down to 20m alt, 1016.11 pressure
> 
> _AFHDS2 receiver connected to EdgeTX radios with MPM._ Wandering between 19m to 22m, 1015.7 pressure
> 
> So, IMO, pressure was as consistent as it's going to be with these sensors (when reported). Altitude consistently went down the longer the sensor was connected, so it may be related to self-heat if the temperature is factored in as part of the calculation. While from start to end it's a variance of 10m, overall it's not excessively great a variance. I'm going to try the FRM303 again with a rebased version of this branch to see if telemetry was broken when this PR was started. edit: I did that with no change, but also realised you must have rebased this recently as it was only a few commits behind. Will try again tomorrow with a nightly to try and pin it down further.

Alt is calculated with pressure alone.

**Comment by richardclli** [comment]
I think I may need to work out some more tweaks for the gps readings in this PR.  Almost forgotten about this PR

**Pull request merged**
