### PR TITLE
Fix baud rate defaults

### PR DESCRIPTION
**Pull request by pkendall64**
Default value 0 is 400k baud, unless SPORT_MAX_BAUDRATE < 400000 in which case default value 0 is 115k baud.

I have tested this on TX16, but don't currently have access to a stdlcd radio to test.

### CODE REVIEW

**Comment by pfeerick** [comment]
I will test on X9D+2019 and T-Lite tonight - but will only be able to test screen menu restructure as I don't have anything crossfire.

**Comment by raphaelcoeffic** [comment]
@pkendall64 am I correct in assuming this is what you actually mean?

```diff
diff --git a/radio/src/telemetry/crossfire.h b/radio/src/telemetry/crossfire.h
index 430af2dad..ae06f9188 100644
--- a/radio/src/telemetry/crossfire.h
+++ b/radio/src/telemetry/crossfire.h
@@ -114,8 +114,12 @@ const uint8_t CROSSFIRE_FRAME_PERIODS[] = {
   #define CROSSFIRE_INDEX_TO_STORE(i) i
 #else
   // index 1 (400000) is the default 0 value
-  #define CROSSFIRE_STORE_TO_INDEX(v) (v + 1) % DIM(CROSSFIRE_BAUDRATES)
-  #define CROSSFIRE_INDEX_TO_STORE(i) (i + 4) % DIM(CROSSFIRE_BAUDRATES)
+  #define CROSSFIRE_DEFAULT_INDEX 1
+  #define CROSSFIRE_STORE_TO_INDEX(v) \
+    (v + CROSSFIRE_DEFAULT_INDEX) % DIM(CROSSFIRE_BAUDRATES)
+  #define CROSSFIRE_INDEX_TO_STORE(i)                            \
+    (i + (DIM(CROSSFIRE_BAUDRATES) - CROSSFIRE_DEFAULT_INDEX)) \
+        % DIM(CROSSFIRE_BAUDRATES)
 #endif
 
 #define CROSSFIRE_BAUDRATE    CROSSFIRE_BAUDRATES[CROSSFIRE_STORE_TO_INDEX(g_eeGeneral.telemetryBaudrate)]
```

If this is the case, then please specify it like that. That should allow for adding other rates more easily.

**Comment by raphaelcoeffic** [comment]
As for the PR itself, one thing needs to be clear, and I don't have a better solution, but this should be noted somewhere (documentation?):
- changing `SPORT_MAX_BAUDRATE` from `< 400k` to `>= 400k` will effectively change the meaning of what is stored in the radio file, thus taking the setting *automatically* one further (`+1`).

**Comment by pkendall64** [comment]
> If this is the case, then please specify it like that. That should allow for adding other rates more easily.

Yes, thats exactly what I meant. I'll update the PR.

**Comment by pkendall64** [comment]
> As for the PR itself, one thing needs to be clear, and I don't have a better solution, but this should be noted somewhere (documentation?):
> 
> * changing `SPORT_MAX_BAUDRATE` from `< 400k` to `>= 400k` will effectively change the meaning of what is stored in the radio file, thus taking the setting _automatically_ one further (`+1`).

Yes, I was just basically putting back what was there previously for systems that could only do 115k baud.

**Comment by nm17** [comment]
LOL, I was just about to make the same pull request. Good job, this needs fixing asap. ELRS is broken by default without this fix.

**Comment by nm17** [comment]
@raphaelcoeffic please review this pr again

**Comment by pfeerick** [comment]
Given I feel the most appropriate test for this is for transition from 2.4 to 2.5 (as unexpected behaviour and some awkwardness is to be expected when using nightlies), I tried with a clean ELRS model on X9D+2019, went from 2.4.0 to this PR, and it defaulted to 400k baud, and ELRS lua and module just worked without having to change anything. So that would suggest this PR has resolved the issue correctly for B&W. 

On my T-Lite, which was running the current main, it jumped from 400k to 3.75M and couldn't talk to the ELRS lua, but when I switched back to 400k it was fine. So I gather for those on nighties it will require re-setting the baud rate again, as jumping from 2.4.0 to this PR on the T-Lite was 400k also, although I didn't clear the EEPROM settings as this is my daily driver ;)

Going from 2.4.0 => this PR on TX16S also resulted in defaulting to 400k, and nightly to this PR going to 3.75M. So end-user wise, it looks like this has restored correct behaviour for end users using release versions.

**Review by pfeerick — APPROVED** [review]
End user experience wise, I'm happy this has resolved the issue. Just needs reviewing by @raphaelcoeffic for any final gotchas... :)

**Pull request merged**
