### PR TITLE
Unregister LUA widgets when the factory is destroyed

### LINKED ISSUE #183: After having mounted SD, LUA widgets lists not populated correctly.
TX16S, gh action build for head, https://github.com/EdgeTX/edgetx/commit/4627b3c3240844dd3e07f06d845565c7cb9debd4

When I go to either...

```
Menu -> Screen Settings -> User Interface (Top Bar) -> Setup widgets -> select a place for a widget -> Select widget
Menu -> Screen Settings -> Main View 1 (Layout)     -> Setup widgets -> select a place for a widget -> Select widget
```
... after having connected USB Storage mode, the lists sometimes have garbage values... and it changes every time. I have four 'widgets' in my `/WIDGETS` folder, and the first of the four screenshots correctly shows the list correctly ((I didn't connect USB storage for that one).

image
image
image
image

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #183

### CODE REVIEW

**Comment by pfeerick** [comment]
Right, gave up on that antenna mount search... hot glue and a zip tie it is. 😁 

tx16s-c30101a, no change in behaviour :(

**Comment by raphaelcoeffic** [comment]
> tx16s-c30101a, no change in behaviour. Still garbled widgets lists after disconnecting USB 😢

Sorry, that was my stupidity: assuming that a working thing on my radio would mean anything 😅

**Comment by pfeerick** [comment]
This now no longer shows garbage values, but it does not appear that the widgets on the SD card are rescanned/repopulated.. i.e. only the widgets up to 'Value' (visible in the screenshot in the issue) are now listed.

**Comment by raphaelcoeffic** [comment]
> This now no longer shows garbage values, but it does not appear that the widgets on the SD card are rescanned/repopulated.. i.e. only the widgets up to 'Value' (visible in the screenshot in the issue) are now listed.

Ok, I think this time it should be correct.

**Comment by pfeerick** [comment]
_Yabba Dabba Doo_ ... third time is the charm... works perfectly. TX16S. Also tested the expected use case where this would confound and annoy... installing a new LUA widget (thanks to justfly for having TX16 ready LUA widgets)... new widget was detected and worked perfectly.

**Pull request merged**
