### PR TITLE
chore: Automate windows installer license copyright year

### PR DESCRIPTION
**Pull request by elecpower**

### CODE REVIEW

**Comment by pfeerick** [comment]
Nice... I'd noticed it was a wee bit out of date but couldn't be bothered fixing it... your way was better than what I intended though 
 :grin:

**Comment by elecpower** [comment]
I was thinking of you when I noticed and decided to fix. One less task for you to do.

**Comment by pfeerick** [comment]
The funny thing is, I saw the content of the other PR first, and was then looking at this one and going "WTH... it looks different to what I looked a a few minutes ago!" 🤪 This heat is certainly getting to me...🔥... anyway, I think I'll do the same for the firmware... it's overdue the automation.

**Comment by elecpower** [comment]
If doing firmware probably best to move the string function to the top level CMakelist

**Comment by pfeerick** [comment]
Yup, already there. Will just gh actions settle down as has been hit with several multi-os companion builds... and currently 🙏 that nightly runs correctly after my changes to the action 🤭

**Pull request merged**
