### PR TITLE
Show true raw info on radio analogs diagnose screen (FlySky hall gimbal only)

### PR DESCRIPTION
**Pull request by rotorman**
Show true raw input value on radio analogs diagnose screen for FlySky hall gimbals (signed short).

### CODE REVIEW

**Comment by pfeerick** [comment]
It has gone from 100/-100 to some 2000/-2000 (except for the throttle - that only goes as far as ~1665), and the signs are inverted... 

i.e. before (mode 2, sticks down and to the right. 
image

after... 
image

**Comment by rotorman** [comment]
@pfeerick Thank you for testing - the values seem plausible, although for my Paladin EV sticks (metal mechanics, but the sampling electronics with dual MLX90393 should be the same or very close), the range measured is more than +/- 2000:
```
[0] LH Rudder   right: 0xF5CF=-2609, left: 0x08B9=+2233, diff: 4842
[1] LV Throttle up:    0xF87D=-1923, down: 0x0936=+2358, diff: 4281
[2] RV Elevator up:    0xF718=-2280, down: 0x0823=+2083, diff: 4363
[3] RH Aileron  right: 0xF674=-2444, left: 0x096A=+2410, diff: 4854
```
@richardclli do you have any objections of merging this PR? Verified to work on RM/Eachine TX16S and NV14.

**Comment by richardclli** [comment]
I do not think the hex values are valuable.  Just show the hex in signed numbers is nice, and it would be good to add in the driver converted value (i.e. the driver will output 0-4096 values after calculating with the factory calibrated values).

**Comment by rotorman** [comment]
@richardclli Do you suggest:
1) the first column to show the uncalibrated raw value in decimals
2) the second column to show the calibrated/pre-processed 12-bit value (not the EdgeTX 11-bit value) ?
That might indeed be even more informative. Did I understand you correctly? If so, I would try to re-implement it.

**Comment by rotorman** [comment]
Thank you for the feedback and tips. I improved the PR to include the raw value in the first column, now shown in decimal format. In the second column the pre-processed value is shown, also in decimal:

DSC_0181

Please check if this is better. Thx!

**Comment by pfeerick** [comment]
I see you conflicted with yourself through #617 😆 

So trying this on the TX16S-HALL gets me this sort of reading (R(1) left, T(2) down, E(3) up, A(4) right. Around ~1000 difference in extremes for each stick. 
image

On the NV14, same stick positions, nearly the full 4096 difference for some sticks!
image

How about showing the +100/-100 values on the NV14 as well, since there's plenty of space... or is that of no value?

**Comment by rotorman** [comment]
> How about showing the +100/-100 values on the NV14 as well, since there's plenty of space... or is that of no value?

Yes, why not - would make sense, especially on NV14 with std. digital hall, to have this special case. I would not be sad if you would implement this (could test in simu only).

**Comment by pfeerick** [comment]
Fair enough, will look that tomorrow or Friday... and get this out of the way ;) Almost time to freeze for RCs! ;)

**Comment by rotorman** [comment]
@pfeerick I'll ping you on this one - probably slipped your attention due to numerous other cool PRs. Thx!

**Comment by raphaelcoeffic** [comment]
> @pfeerick I'll ping you on this one - probably slipped your attention due to numerous other cool(-er) PRs. Thx!

In fact he passed it on to me 😇

**Comment by pfeerick** [comment]
Oh, yeah, I did, didn't I... got stuck getting it to work with both Horus and NV14 targets properly... that squirrel just kept running!

**Comment by pfeerick** [comment]
Right, I think Raphael just needs to push the tweak to unbreak `simu` for NV14 and merge this as it is... not worth the hassle when we have bigger fish to fry ;)

**Pull request merged**
