### PR TITLE
Hott integration

### PR DESCRIPTION
**Pull request by mha1**
Summary of changes:
This is a port of all the fixes and updates for the Graupner HoTT telemetry that were successfully integrated and tested in OpenTX 2.4.15 (dev).

Merged pull requests:
https://github.com/opentx/opentx/pull/8767
https://github.com/opentx/opentx/pull/8779

Fixes the following OpenTX 2.4.14:
https://github.com/opentx/opentx/issues/8798
https://github.com/opentx/opentx/issues/8796
https://github.com/opentx/opentx/issues/8759
https://github.com/opentx/opentx/issues/8751
https://github.com/opentx/opentx/issues/8709

### CODE REVIEW

**Comment by mha1** [comment]
Please have a look at this PR and approve it if you like it. It's just a port of all the fixes and extensions to the Graupner HoTT telemetry protocol implemented and test in OpenTX 2.3.15-dev

**Comment by raphaelcoeffic** [comment]
@mha1 can you please move the sensor names to the “untranslated.h” file? Also, please remove the “Z” in front.

**Comment by mha1** [comment]
@raphaelcoeffic thank you very much for your input. Moving sensor name defines to a single file makes it a lot easier to maintain. I suppose no one would have wanted language specific sensor names anyway. I also removed the leading "Z". If you find some spare time I'd appreciate you giving the update a quick look again - Michael

**Review by raphaelcoeffic — APPROVED** [review]
Much better this way, thx! I don’t have any Hott gear to test, so I will leave it to others.

**Comment by pfeerick** [comment]
Same here... given it should only affect HOTT telemetry (and you've been able to test it quite extensively), I'm inclined to just merge it (i.e. expect that in the next day or so :grin:) I have the requisite transmitter hardware (i.e. MPM - both internal and external with CC2500s, but no receivers. I might get a GR-12L at some point unless you can recommend a compatible receiver that is a bit more readily available and isn't as expensive? 

Did you get any response from your call for testers on Discord?

**Comment by mha1** [comment]
@raphaelcoeffic @pfeerick 

Thanks for your support. Indeed this only affects telemetry, no change to any UI code. And I tested this extensively with private builds based on OpenTX 2.3.14. In fact I still fly my helicopters and gliders with different Graupner HoTT receivers and telemetry devices (Graupner and third party like Unisens) with this change. Attached to my MPM PR (https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/pull/627 - went into 1.3.3.7) justifying the change to support processing of HoTT telemetry warnings you'll find a log file recorded by my Goblin 500 helicopter (GR-18 and T-100 telemetry ESC).

Unfortunately I did not receive any feedback from testers. Drop me your address and I'd be happy to lend you one of my GR-16 receivers for testing.

Michael

**Comment by pfeerick** [comment]
In my case, don't worry about that as I'm over in Australia... so if I were really concerned I'd just charge a new receiver to the ETX project ;) We'll know soon enough if there are any issues as there will either be total silence or a horde of the 5 HOTT ETX users worldwide (jk) complaining 😁

**Comment by mha1** [comment]
Thanks for merging, I look forward to meeting 5 new friends. 

@pfeerick Feed the roos for me, mate.

**Pull request merged**
