### PR TITLE
chore(ui): convert gvars window to LVGL

### PR DESCRIPTION
**Pull request by gagarinlg**
Summary of changes:
gvars window proted to LVGL

### CODE REVIEW

**Comment by Eldenroot** [comment]
Cool, one by one

**Comment by gagarinlg** [comment]
Yes, that was the plan. But my next task is something less UI and more close to the HW

**Comment by pfeerick** [comment]
There's a positioning (nesting?) issue going on... just try scrolling down - the header bar disappears and doesn't come back. 

When changing the precision, it changes the GV as displayed at the top, but not any of fields - they still get shown without the decimal. For reference, this is what I'm expecting to see change for min/max and FM values

companion_tFzL26EcAI

The rest of my gripes are cosmetics and can be fine-tuned later ;)

**Comment by gagarinlg** [comment]
I fully concentrated on the list view regarding the decimals. I never bothered to check the edit page,🫣

**Comment by pfeerick** [comment]
Sorry for the delay. The aforementioned issues appear to be gone. Any other UI tweaks needed can be done later as this does what it says on the tin ;)

**Pull request merged**
