### PR TITLE
fix(color): Improve layout of Module / RX version pop up

### LINKED ISSUE #2320: Module / RX version pop up doesn't look nice
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

"Multimodule" shouldn't be wrapped like that.

image

### Expected Behavior

no breaking words

### Steps To Reproduce

select Radio Settings, Version, Models / RX version

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

build 9fbf0b7b

### PR DESCRIPTION
**Pull request by mha1**
Fixes #2320

Summary of changes:
changed the popup to two columns and two separate lines for type and status, for pictures see issue #2320

### CODE REVIEW

**Comment by pfeerick** [comment]
Just a minor correction for PXX2, and I also moved the NV14 internal RF module to this screen also as it's the proper place for it (and also resolves the annoyances of it showing on the EL18 when it shouldn't, and showing `0.0.0` when the rf module is off). Thanks for this! :)

**Comment by mha1** [comment]
Great, thanks!

**Comment by TheIsotopes** [comment]
@mha1 
Ghost module is only displayed as `Ghst` but the Status is not displayed on my TX16S MKII and `no info` appears on my Zorro.
Please can you check that.

**Comment by pfeerick** [comment]
That would be correct... the same name is used as is shown in the module selection list.  There is currently no status info for Ghost, and these changes are color specific. ;) 

image

**Comment by pfeerick** [comment]
Yeah, given we have `MULTI` I don't know why it is `GHST`, and I can't see any dumb logic that is looking at the name. Was just pointing out it's been like that for a very long time ;) I'll check it doesn't break my ghost module and change it if nothing goes wrong.

**Comment by TheIsotopes** [comment]
thx @pfeerick and @mha1 

I thought I see the mhz display under status, like elrs status?!

Imo should we leave `Ghst` output as it is.

**Comment by pfeerick** [comment]
No, not yet... just like it's not being shown on the module settings screen. 

It would be nice to show the RF Power and RF Profile ... not sure if any of the other module telemetry it gives will be of any use or interest.

**Pull request merged**
