### PR TITLE
Translations Rework #1 WIP Don't Merge

### PR DESCRIPTION
**Pull request by richardclli**
Summary of changes:

1. Cleaned up unused constant names in translations.cpp and translations.h
2. Check and clean up broken codes that used broken translations
3. Work out a new way for translation code generation, eliminate all the intermediate #defines (using Python script)

The first thought about the code generation is to make use translations.h as base, and all translations will be coded in a python script with python types as different string construct, the #defines will still works in this way as python will take #define as comments.

The python script will generate the translation.c directly based of the language and other special definitions (e.g. screen size)

Another script will be written to verify if the translations scripts has any problem by comparing to translations.h

Will work out a prototype and accept further comments, some examples of future translations file:

`STR_OFFON = ["禁用","开启"]`
`STR_MMMINV = ["---","反"]`
`#if defined(PCBHORUS)`
`  STR_VMIXTRIMS = ["禁用","启用","Rud","Ele","Thr","Ail","T5","T6"]`
`#else`
`  STR_VMIXTRIMS =["禁用","启用","Rud","Ele","Thr","Ail"]`
`#endif`

### CODE REVIEW

**Comment by pfeerick** [comment]
Can you also incorporate https://github.com/EdgeTX/edgetx/pull/889 into this PR if the constant still needed.

**Comment by richardclli** [comment]
> Can you also incorporate #889 into this PR if the constant still needed.

Yes, I will take a look, anyway.  Currently Chinese translations are not complete yet.  Many text are still hardcoded.  I will verify the translations once I finished the new code generator.

**Comment by richardclli** [comment]
The build finally works for the tests as well.

**Comment by richardclli** [comment]
No need after LVGL change.

**Pull request closed without merging**
