### PR TITLE
long press or long touch open selection menu on the inverted switch

### PR DESCRIPTION
**Pull request by eshifri**
This pull request implements #437: long press or long touch open selection menu on the inverted switch: e.g. if current SD position is UP, the selection will be set on !SD UP.

No changes in libopenui are required with this version.

### CODE REVIEW

**Comment by pfeerick** [comment]
I see one problem with this - two position switches don't have inverted states (at present at least - that may or may not change in the future). So this allows for non-existant invert states to be selected - i.e. RM TX16S SF and SH are both two position - so if you long press on SF(up) it will set !SF(up), which is invalid. 

And one other minor niggle - is it possible to *not* show the menu if it is a long press - i.e. just do the inversion?

**Comment by eshifri** [comment]
I was not sure about opening the menu. Eventually, I convinced myself that it was the right thing to do, but I still do not have strong opinion. It may be not trivial, but should be possible.
The missing state is more complicated: as you have definitely noticed, the icon and hence some placeholder for inversion of two positional switches exists - it is just not present on the menu, hence undesired behavior. This means that !UP != DOWN for two positional switch, which is not very rational as well. 
So, I do not know... I can probably look how many positions any given witch has, but if later we decide to return these inversions of the two positional switches into the menu...
BTW, the inversion works not only for the switches: e.g. RSSI converts to !RSSI.

**Comment by eshifri** [comment]
Both your wishes are granted. :-)

**Comment by JimB40** [comment]
> so if you long press on SF(up) it will set !SF(up), which is invalid

Why is that? AFAIR I can select !SF in logical switches

**Comment by pfeerick** [comment]
You shouldn't be able to... two position switches across the board don't have inverted states (hence #178 and poll on Discord)

**Comment by JimB40** [comment]
Yep I know that for 2pos 'down' is the same than 'not up' still IMHO possibility of reaching goal using different ways was one of OTX core assumptions.

**Comment by pfeerick** [comment]
Well, it looks like https://github.com/EdgeTX/edgetx/issues/178 is going to go ahead, based on community feedback, so the inverted two pos option won't be a problem. Hopefully that  won't clash with the fix eshifri came up with... that's on me if it does though, as I plan to get this merged first.

**Comment by eshifri** [comment]
Should not be a problem: as long as the new position is marked as available, this code will work correctly.

**Review by pfeerick — APPROVED** [review]
LGTM... and works really nice pretty much anywhere there is a switch combo... i.e. timer switch, special function, mixer, etc... Thank you! :)

**Pull request merged**
