### PR TITLE
feat: add support for serial passthrough to serial gimbals

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by richardclli** [comment]
@raphaelcoeffic How this works?  No UI? Use cli to control the serial passthrough?  Need to use the debug build for cli?

**Comment by 3djc** [comment]
No ui just new cli "rfmod gimbals" command, regular builds are fine

**Comment by 3djc** [comment]
Hasn't this one been superseeded by the noiw merged GX12 PR ? @raphaelcoeffic

**Comment by pfeerick** [comment]
Looks like it... some variation of these two commits are present in #5703. I think this was broken out at the time so that it could be tested against/ reviewed for flysky gimbals while waiting for this to be announced.

**Pull request closed without merging**
