### PR TITLE
fix: some radio settings were overwritten or not applied

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
- fix default VCP configuration (was not applied)
- fix internal module configuration (was always overwritten with default module)

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]

**Comment by pfeerick** [comment]
Fixes both the VCP not being set to CLI issue on supported radios (i.e. TX16S, Zorro) we were talking about and also that the internal module setting wasn't being populated when it didn't exist.

**Comment by TheIsotopes** [comment]
@raphaelcoeffic Is it normal that VCP after a change (e.g. OFF)  is always set back to CLI? 
found on TX16S and Zorro

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic Is it normal that VCP after a change (e.g. OFF) is always set back to CLI?
> found on TX16S and Zorro

Yes, as designed. The point being here that ELRS relies on CLI for passthrough flashing. So if it is OFF, it will go back to default, which is CLI.

**Comment by pfeerick** [comment]
We could possibly make it more specific though? *IF* Internal Module == CRSF, default it back to CLI if off/not set? As it's not *needed* for MULTI... or is that because you're thinking we would be update MPM firmware through CLI in the future also? It's not like it's really a problem since that is/was the primary use for VCP (or as debug).

**Comment by raphaelcoeffic** [comment]
I would really like being able to update the MPM via passthrough as well! And it should even be possible in fact.

**Pull request merged**
