### PR TITLE
chore(cpn): Run Qt Linguist updater

### LINKED ISSUE #2317: Regenerate Companion translation sources each release
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Translations are regenerated at build time but the Github source is not refreshed. 

### Describe the solution you'd like

Update the Github source as part of the workflow for each release

### Describe alternatives you've considered

_No response_

### Additional context

Refer Qt documentation https://doc.qt.io/qt-5/qtlinguist-index.html
Also https://github.com/opentx/opentx/wiki/Flow-for-the-Translators

QT 5.12.9 is in use
https://github.com/lelegard/qtlinguist-installers/releases

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #2317

Summary of changes:

Ran the following on Windows

```
@ECHO OFF

SET QTLINGUIST_LUPDATE="c:\tools\QtLinguist\bin\lupdate"
SET REPO_DIR="E:\repos\GitHub\edgetx\edgetx"
SET CPN_SRC_DIR="E:\repos\GitHub\edgetx\edgetx\companion\src"

for %%f in ("%CPN_SRC_DIR%\translations\*.ts") do (
    echo Processing "%%f"...
    %QTLINGUIST_LUPDATE% %CPN_SRC_DIR% -no-obsolete -ts "%%f"
)
```

Got these warnings / grumbles for each if of any interest:
```
E:/repos/GitHub/edgetx/edgetx/companion/src/warnings.h:95: Class 'AppMessages' lacks Q_OBJECT macro
E:/repos/GitHub/edgetx/edgetx/companion/src/storage/firmwareinterface.cpp:390: Cannot invoke tr() like this
E:/repos/GitHub/edgetx/edgetx/companion/src/storage/firmwareinterface.cpp:390: Class 'FirmwareInterface' lacks Q_OBJECT macro
E:/repos/GitHub/edgetx/edgetx/companion/src/updates/updatecompanion.cpp:36: tr() cannot be called without context
E:/repos/GitHub/edgetx/edgetx/companion/src/updates/updatecompanion.cpp:41: tr() cannot be called without context
E:/repos/GitHub/edgetx/edgetx/companion/src/updates/updatecompanion.cpp:46: tr() cannot be called without context
E:/repos/GitHub/edgetx/edgetx/companion/src/updates/updatecompanion.cpp:52: tr() cannot be called without context
```

@elecpower Can you cast an eye over the changes and tell me if there is anything I should be worried about (other than judging by one of the matches, the fact that this hasn't been done in over four years)? 😆

### CODE REVIEW

**Comment by elecpower** [comment]
After 4 years I'm surprised there aren't a bucket load more errors. I'll take a look and see how many can be resolved.

**Comment by elecpower** [comment]
@pfeerick compiled this branch for companion and ran your script in Ubuntu 20.04 and no errors.
I did notice companion/src/CMakeLists.txt line 105 does not match the list of translation/*.ts files and companion/src/translations.cpp lines 37 thru 53. The translations.cpp needs to interface with mainwindow.cpp to set the app language.

**Comment by pfeerick** [comment]
lol... that's even worse... six years ago! 😆 https://github.com/opentx/opentx/pull/4676

**Comment by elecpower** [comment]
@pfeerick the more we dig the more pain we find aaargh.
Was not much of an issue in OTX as very few ppl to help with translations but here we have some very willing helpers. 
I really think we should bite the bullet and align with ISO text and voices for radios, Companion and supporting repos and eliminate the multiple language lists. For maintenance I would suggest we try for a single one shared by radios and Companion.

**Comment by gagarinlg** [comment]
For LVGL there is this
https://github.com/lvgl/lv_i18n

**Comment by pfeerick** [comment]
> this PR seems to delete a lot in the DA translation file, look not right

As you can see from the command run, only the standard `lupdate` update command from the Qt Translation toolkit has been run. Some of the stuff was automatically removed because those strings are no longer present -eg. category related stuff, EEPROM. Possibly other stuff was removed because it was duplicated - i.e. I can see some of the telemetry sensor translations are repeated twice or even three times. I'm guessing you've been editing the source text directly, rather than using QT Linguist (not blaming, I'm only just starting to use it myself!), so you wouldn't have been aware of warnings like:

image

image

And if you started from the English translation file (which was similarly out of date - as mentioned above, some of this stuff has not been refreshed properly in 4-6 years) well, it seems to have gotten it's fair share of pruning also, so this is simply bringing things back into alignment so it should be smooth sailing from now on. If you've not used QT Linguist yet, it will make things a *lot* easier - lets you focus on just what needs translating, will auto-suggest based on pre-existing translations where it can, and makes sure the files are properly formatted. You can get the standalone version for Mac and Windows here: https://github.com/lelegard/qtlinguist-installers/releases

> the SE translation file are missing

No, the SE translation file is *unchanged* by this PR as it is already up-to-date ;)

**Comment by pfeerick** [comment]
> @pfeerick the more we dig the more pain we find aaargh. Was not much of an issue in OTX as very few ppl to help with translations but here we have some very willing helpers. I really think we should bite the bullet and align with ISO text and voices for radios, Companion and supporting repos and eliminate the multiple language lists. For maintenance I would suggest we try for a single one shared by radios and Companion.

What's new 😆 

Well, that just made this 2.9 material I think, and definitely... there's a few things that need a refresh for translation handling overall - i.e. need to make JP voice work for radio (as well as zh_tw now I think also), as well as more flexibility for voice pack directory (before you panic, I'm not saying this will be all in this PR, just jotting down what's been at the back of my mind for a while now)... 

> For maintenance I would suggest we try for a single one shared by radios and Companion.

Where have I heard that before (not specifically related to translations)? 😁 But definitely, one single consistent format for supported languages, which we can use everywhere. I do prefer the ISO/RFC 4646 spec since that allows for the country and then language variations, so shouldn't need to be changed again any time soon!

**Comment by HThuren** [comment]
RIGHT, have run the linguist, gave some work to do in da_DK translation :-)
Worst, that some accelators was missing...

Good tool we have here

**Comment by HThuren** [comment]
Now translated and created #2738 after this instructions

**Comment by ulfhedlund** [comment]
The Swedish sounds can not be downloaded and doesnt work either. The sv/se directory naming is  an issue. Would be nice to have them working too.

**Comment by ulfhedlund** [comment]
The four warnings about strings in ./companion/src/updates/updatecompanion.cpp being called without context means there are strings missing in the translation files and hence not translated. 
I have fixed this locally and after running lupdate there are now corresponding additional strings in the .ts file. However it needs to be verified by a developer. 
Should I make a PR or leave this for future general rework/changes in translations (as discussed above)?

**Comment by pfeerick** [comment]
Neil / elecpower, actually, but yes, they should be gone after this PR. And no, I don't think it was due to missing strings, but because of how the calls to `tr()` were done in that particular part of the code.

**Comment by HThuren** [comment]
> Neil / elecpower, actually, but yes, they should be gone after this PR. And no, I don't think it was due to missing strings, but because of how the calls to `tr()` were done in that particular part of the code.

I belive you are right, I found some missing translations, now fixed. But still miss Ali, Elv, Thr and Rud, but not sure what happens if translated in firmwares/boards.cpp

**Comment by elecpower** [comment]
> I belive you are right, I found some missing translations, now fixed. But still miss Ali, Elv, Thr and Rud, but not sure what happens if translated in firmwares/boards.cpp

At the same time as fixing updatecompanion I made a change to firmware to add translations. Does this not work or are the strings not passed to translation eg no tr("Ali")? An example would help me.

**Comment by HThuren** [comment]
Hi @elecpower 
Some examples
Inputs
image
Mixes
image
Print model inputs
image
Print model Mixes
image

**Comment by HThuren** [comment]
Maybe from here, but not sure
image

**Comment by elecpower** [comment]
Hi @HThuren thanks for the info. The code snippet is the source of the issue but cannot simply be translated as is since it is used for yaml import/export and text strings must match exactly. I have a couple of ideas for a fix so stay tuned.

**Comment by elecpower** [comment]
@HThuren @pfeerick added translation to all analogs.
I have performed some testing and appears I haven't broken yaml or anything else but I stand to be corrected ;-)

**Comment by HThuren** [comment]
@elecpower, great I have made a copy of board.cpp and try to compile the companion

**Comment by HThuren** [comment]
@elecpower, Inputs works well
image

but no change to mixes (I supppose here are no changes to companion_da.ts)

**Comment by HThuren** [comment]
... but also need to test changes in radio, fetch to companion, and visa versa

**Comment by elecpower** [comment]
@HThuren thanks for testing. I'll check out mixes when I have a chance.

**Comment by HThuren** [comment]
@elecpower, all works well, I had to change in Radio, and that was well
THANK YOU
INPUTS
image
MIXES
image

**Comment by HThuren** [comment]
... now we just need boards.cpp to be merged ...

**Comment by pfeerick** [comment]
@elecpower If I rebase this to remove the conflicts, your thoughts on merging this now... I think the issues you raised in https://github.com/EdgeTX/edgetx/pull/2685#issuecomment-1307874033 are part of a bigger re-write?

**Comment by elecpower** [comment]
@pfeerick rebate and merge. Agree the comments are a much bigger task

**Comment by ulfhedlund** [comment]
Will there be new translations required for all languages (including Swedish)?

**Comment by HThuren** [comment]
> So, there will now be quite a few new translations required in the Boards context?

@ulfhedlund, yes, like this (Danish here):
image
image

**Comment by pfeerick** [comment]
Synced (read/write) TX12 and TX16S with no issues with inputs/mixes, so it looks like the analog input translation are behaving properly. Funnily enough, based on the mutterings in the dev chat the other night, this naming might get revisited again soon 😆

**Comment by elecpower** [comment]
> Funnily enough, based on the mutterings in the dev chat the other night, this naming might get revisited again soon 😆 

Just read the thread and I had a dejavu moment from OTX 😖

**Pull request merged**
