### PR TITLE
Add capability to build more firmwares than scheduled for tests

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by brainbubblersbest** [comment]
Thank you a lot. 
The X10 express Radio is infact, no old X10 with different HF Modules. It's a Own Radio Model with a Own pcbrev resistor. (pcbrev express)

Same for the x7 access. This PR make absolute Sense.

**Comment by raphaelcoeffic** [comment]
> Thank you a lot.
> The X10 express Radio is infact, no old X10 with different HF Modules. It's a Own Radio Model with a Own pcbrev resistor. (pcbrev express)
> Resulting in wrong firmware Error at Boot up.
> 
> Same for the x7 access. This PR make absolute Sense.

Unfortunately, I’ll have to use some tricks: with the matrix builds, we are hitting the limit for the free tier, so that I need to rethink this a little.

**Comment by brainbubblersbest** [comment]
Thats at least a total acceptable current state after this explanation. 😉 
It was not clear to me, that here is something like a Limit in such a sort.

**Comment by raphaelcoeffic** [comment]
> Thats at least a total acceptable current state after this explanation. 😉
> It was not clear to me, that here is something like a Limit in such a sort of.

The funny thing is: it is written nowhere, but as soon as some workflow has more targets than the number of parallel runners you can use, it is starts stalling the builds forever, and I must cancel manually.

**Comment by pfeerick** [comment]
I would suggest it may be something else entirely... since "A job matrix can generate a maximum of 256 jobs per workflow run. This limit also applies to self-hosted runners." and since we haven't specified `max-parallel` for the strategy, it will be at the default of two parallel jobs. It could be limit related, or it could have been [the outage they had yesterday](https://www.githubstatus.com/incidents/7p1nnvkgh96y)...

**Comment by raphaelcoeffic** [comment]
> I would suggest it may be something else entirely... since "A job matrix can generate a maximum of 256 jobs per workflow run. This limit also applies to self-hosted runners." and since we haven't specified `max-parallel` for the strategy, it will be at the default of two parallel jobs. It could be limit related, or it could have been [the outage they had yesterday](https://www.githubstatus.com/incidents/7p1nnvkgh96y)...

Thx for the hints! However, this happened already a couple of days ago, but I could give it a new try with the params you pointed at.

**Comment by pfeerick** [comment]
There was another outage on the 29th of July, but I think that ended up being the day after this when you take the timezone into account... I've just seen some weird stuff happen with GitHubs Actions sometimes and it's nothing to do with the configuration, but issues on GitHubs. I don't think even if we hit the limit of the number of runners or tasks it woud matter, since they are supposed to be queued... 

https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

**Comment by raphaelcoeffic** [comment]
> There was another outage on the 29th of July, but I think that ended up being the day after this when you take the timezone into account... I've just seen some weird stuff happen with GitHubs Actions sometimes and it's nothing to do with the configuration, but issues on GitHubs. I don't think even if we hit the limit of the number of runners or tasks it woud matter, since they are supposed to be queued...
> 
> https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

You will notice that I did not imply that the behavior I observed was like GH pretends it is ;-) this is just what I observed, which is what matters at the end: can we use it or not? 😇

**Review by pfeerick — APPROVED** [review]
Just need to add more to flasher's fw.json in the morning once this has taken effect ;) 

If there's no reason that https://github.com/EdgeTX/edgetx/pull/510/files#diff-0df595be8e96ece6e759d210a699745983f8fb639617bccdcffe7a0d827f6c08R141 has to be uppercase with hyphen that would be great also... just saying ;)

**Comment by raphaelcoeffic** [comment]
> Just need to add more to flasher's fw.json in the morning once this has taken effect ;)
> 
> If there's no reason that https://github.com/EdgeTX/edgetx/pull/510/files#diff-0df595be8e96ece6e759d210a699745983f8fb639617bccdcffe7a0d827f6c08R141 has to be uppercase with hyphen that would be great also... just saying ;)

😭

**Comment by raphaelcoeffic** [comment]
> Just need to add more to flasher's fw.json in the morning once this has taken effect ;)
> 
> If there's no reason that https://github.com/EdgeTX/edgetx/pull/510/files#diff-0df595be8e96ece6e759d210a699745983f8fb639617bccdcffe7a0d827f6c08R141 has to be uppercase with hyphen that would be great also... just saying ;)

Done!

**Pull request merged**
