### PR TITLE
Lua function for trainer status

### PR DESCRIPTION
**Pull request by CamGenius**
Summary of changes:
Adds a lua function for getting the status of the trainer input. #627
Also adds a sound function for trainer initial connection.

### CODE REVIEW

**Comment by dlktdr** [comment]
Testing trainer input fairly often, I like the idea of having the extra voice for trainer connected 👍 It not obvious it's working the first time you connect a device. When you consider some of the previous issues with the trainer jack on TX16s or trying to find the proper PPM input levels, did you pick the right bluetooth address, not having a notification the first time it's working can be highly confusing. (Also need to bring back the trainer connected icon on the main title bar.. but that's another issue)

@CamGenius What is the purpose of having disconnected and not_connected? Are these not the same thing?

**Comment by pfeerick** [comment]
Have tested this with the following dumb widget, and a newly generated `trainco.wav` on TX16S and both the audio and Lua are working perfectly.  Tracking the initial state, connect and reconnect is excellent, as would allow a widget or standalone lua to track the state of the link and react accordingly. 

```lua
local options = {
}

local function create(zone, options)
  local widget = { zone=zone, options=options }
  return widget
end

local function update(widget, options)
  widget.options = options
end

local function background(widget)
end

local function refresh(widget)
  local trainerStatus = getTrainerStatus()

  if trainerStatus == 0 then
    lcd.drawText(widget.zone.x, widget.zone.y, "Not Connected", LEFT);
  elseif trainerStatus == 1 then
    lcd.drawText(widget.zone.x, widget.zone.y, "Connected", LEFT);
  elseif trainerStatus == 2 then
    lcd.drawText(widget.zone.x, widget.zone.y, "Disconnected", LEFT);
  elseif trainerStatus == 3 then
    lcd.drawText(widget.zone.x, widget.zone.y, "Reconnected", LEFT);
  else
    lcd.drawText(widget.zone.x, widget.zone.y, "Unknown state", LEFT);
  end
end

return { name="Trainer Status", options=options, create=create, update=update, refresh=refresh, background=background }

```

**Comment by BatesKG** [comment]
Hi @CamGenius and @pfeerick 
I was just trying to do this on the weekend.   Awesome!   
I was just setting the student Tx to output a max value on Ch10 and was checking for the high value of TR10 on the instructor radio.  It was a little flakey though and would randomly cause disconnects when the logical switches didn't see the value for some reason.   It was also on openTx but will be updating the instructor radio to ETX this weekend after a successful conversion on the student radio.

One request.....  Could you please add one extra line to the script to insert the numerical value of 'trainerstatus' into a telemetry or global variable on the radio that logical switches could reference?   
I have my system set up so that it automatically announces a disconnect and passes control back to the instructor if the trainer link is lost.  I'm also testing the trainer link exists before allowing the transfer of control, even if the trainer switch is activated.
Thanks!
KevinB

**Comment by pfeerick** [comment]
I'm not sure that is the best way to do it... probably better to have a lua widget or some other script do that sort of conversion - it's not telemetry as such, and sending it to a GV then begs the question "which GV" and "who else is going to complain we've just clobbered GV# that they use for XYZ"

e.g. The flight modes widget uses GV9 IIRC (to store the persistent flight counter). I suggest instead that perhaps a "trainer" widget needs to be developed, and as part of that an option to push the trainer state to a (configurable) GV.

**Pull request merged**
