### PR TITLE
Fix timer data conversion

### LINKED ISSUE #403: Timer On is converted to Start
On my X9D+, the timers were set to ON, and they got converted to "Start" when I upgraded to EdgeTX from OTX 2.3.11.

### LINKED ISSUE #566: Model Timer 1 changes from On to Start when moving from OpenTX
**Describe the bug**

When a timer is set in OpenTX as On with a switch. After conversion to EdgeTX model, the setting changes to "Start" and timer keeps counting down until it's changed to "Start" again. Also the Persistent option gets filled with gibberish. 

**To Reproduce**

Create Timer 1 on a model in OpenTX. 
Set name
Set mode = ON and a switch position. 
Set time
Set countdown = haptic , 30s
Set persistent = Manual Reset

Now flash EdgeTX and let the models get converted. In the new EdgeTX model, Mode becomes Start and sometimes there is gibberish in the Persistent field. 

**Expected behavior**

Timer settings should remain consistent after moving to EdgeTX

**Screenshots**

**General information**
 - EdgeTX version
2.4.0
 - Hardware
 RM TX16S

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #403
Fixes #566

### CODE REVIEW

**Comment by elecpower** [comment]
@raphaelcoeffic there appears to be another data conversion quirk. When timer mode Start was introduced did you also change the countdown start mapping as it seems to be roughly inverted from v219. The radio gui doesn't match OpenTX.

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic there appears to be another data conversion quirk. When timer mode Start was introduced did you also change the countdown start mapping as it seems to be roughly inverted from v219. The radio gui doesn't match OpenTX.

That was not me changing it, but I can have a look.

**Comment by elecpower** [comment]
Assumed you signed off on the change so apologies for the 'blame' which wasn't the intention.
But it does highlight the need for these types of changes being reviewed as they can have flow on across radios companion and data conversion. A simple change can create lots of effort for others to diagnose and fix.

**Comment by raphaelcoeffic** [comment]
This is one of the changes that had been made for OTX 2.4 that I did not know of and discovered after the fork. I thought it was there for a reason, so I decided to keep it. Like many things, it was somehow done, but not to the end.

**Comment by elecpower** [comment]
Great, legacy stuff. Obviously not enough OTX nightly testers to pick it up. I had the same lack of testing on Companion changes and they were released and then raised as issues within days of the release.
Since it is now being used in its current form by ETX users and I assume we do not want another eeprom version so I'll update the radio and Companion data conversion again and Companion ui.

**Comment by raphaelcoeffic** [comment]
@elecpower thx a lot!

**Pull request merged**
