### PR TITLE
fix: Add remaining/elapsed display on BW telem topbar

### PR DESCRIPTION
**Pull request by 3djc**
While @pfeerick was couting sheeps, request : https://github.com/EdgeTX/edgetx/pull/3856#issuecomment-1655569858

Handles remaining/elapsed display on BW telemetry screen topbar and move to HH:MM:SS format

### CODE REVIEW

**Comment by lightbulbjim** [comment]
Would it make more sense to do:

if timer < 60 minutes
    MM:SS
else
    HH:MM
end

This matches the format of both the home screen and voice callouts.

**Comment by pfeerick** [comment]
Thanks JC :) 

My only concern then would be that it wouldn't be quite as... obvious? ... that one is the time, and the other not the time (although the same could be said if  it is counting up, and active 🤭 )

I'll let the PR author case the deciding vote 😆

**Comment by 3djc** [comment]
My concern exactly. Because this is a screen designed to be read while you fly, you don't have the luxury to leave your eyes on this screen for a couple of seconds to see if right collum is counting quickly (hence MM:SS) or not. HH:MM:SS is unambigous imho. I had concider adding an arrow or something to show if remaining or actual was displayed, but dit not find one that wasn't confusing

**Comment by lightbulbjim** [comment]
Makes sense. Thanks!

**Pull request merged**
