### PR TITLE
chore: improve VBAT measurement

### PR DESCRIPTION
**Pull request by 3djc**
Cleanup of VBAT measurement definition for Radiomaster and Jumper radio where we have exact drawings and resistors values. This will break existing calibration (likely not by a whole lot), but overall I think it is for the best. In most cases, default value should already be very accurate

### CODE REVIEW

**Comment by pfeerick** [comment]
> This will break existing calibration (likely not by a whole lot), but overall I think it is for the best.

Depends by what you mean by a whole lot... 1V of movement seems like a lot for me 🤪 i.e. T-Pro jumped from 7.82 to 8.92V, but T12-Max and Zorro were a lot less - T12-Max from 7.79 to 8.12, and Zorro from 7.95 to 7.69. X9D+2019 was correctly non-affected. 

I completely agree, having the calculated value rather than a magic number is much better, and is more flexible for future variations.

**Comment by rcmz** [comment]
Is there a way to reset battery calibration to default ?

**Comment by 3djc** [comment]
You can delete your radio.yaml and re run stick calibration at start, or (more advanced) edit the file to delete vbat calibration data)

**Comment by rcmz** [comment]
@3djc I reseted `txVoltageCalibration` in `radio.yaml` to 0 but it resulted in an incorrect battery voltage of 8.9V.
(PS : don't delete the `txVoltageCalibration` in `radio.yaml`, it resets your whole config !)

**Comment by 3djc** [comment]
It doesn't if you do it properly by setting the right flag to say you hand edited it (hence the more advanced warning;)

What radio ?

**Comment by rcmz** [comment]
Jumper T20

**Comment by 3djc** [comment]
I'll have a look at the drawings tomorrow

**Comment by 3djc** [comment]
@rcmz Could you try this ?

[firmware.bin.zip](https://github.com/user-attachments/files/20157618/firmware.bin.zip)

WARNING: backup your SD card before use, and restore after since this firmware is based on main

**Comment by rcmz** [comment]
@3djc it now goes up to 8.6V with no radio active, and 8.4 with ELRS at 100mW.
I'm not sure ELRS was active or not for the 8.9V result.

**Comment by 3djc** [comment]
My voltmeter is dead, so hard for me to test, but I have ordered a new one, should arrive today. Fingers crossed!

**Pull request merged**
