### PR TITLE
fix: PWM gimbals initialisation and inversion

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
The PWM sticks present in some radios were not detected properly:
- X-lite S / Pro: *untested*
- X10S (Express and ACCST): ✅
- Commando 8: ✅

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
Good for me on iFlight Command8 - went from not working to working, sticks all in the right directions.

**Comment by ParkerEde** [comment]
tested with the X10S Express. Now it works correctly again. The direction is also correct

**Comment by pfeerick** [comment]
I'll leave for another day or so to allow for the user with the X-Lite Pro to report back, but looking good so far :)

**Comment by Talha909** [comment]
I will check it today and let you know.

**Comment by pfeerick** [comment]
Given there has been no contrary feedback for 1/3 targets, merging 🤭

**Pull request merged**
