### PR TITLE
Increased resources for Lua widgets

### PR DESCRIPTION
**Pull request by jfrickmann**
Developing SoarETX, I find that the Lua widgets quickly become slow and stuttering, and hit the CPU limits. So I have added a little more CPU resources to the Lua widgets here.

I have pulled against 2.6, as that is what I work with. Does it also get into main and 2.7?

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Please `main`. If applicable, it will be cherry picked.

**Comment by JimB40** [comment]
Experiencig same with may apps wiget mode on 2.6

**Comment by gagarinlg** [comment]
Why is there a difference between 2.5 and 2.6 and also between TX16S and NV14? We're there any changes regarding Lua that affect speed?

**Comment by JimB40** [comment]
I don't think widget speed on 2.5 was any faster than 2.6
But I haven't used much my apps in wighet mode on 2.5

**Comment by jfrickmann** [comment]
I will close this one, and making a new one on main

**Comment by jfrickmann** [comment]
Please see #1498.

**Pull request closed without merging**
