### PR TITLE
feat: Support for MPM DSM clone mode

### LINKED ISSUE #3969: Clone option for MPM DSM Protocol
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add an additional option to the DSM MPM screen to indicate whether it should operate in Normal or Cloned mode (similar to the FRSKY cloning).  TX should then send the value in the optionValue (byte3) bit5 - for DSM currently:

Bits 0..3 num_ch
Bit 4 Not Used
Bit 5 Not Used
Bit 6 Frame Rate
Bit 7 Max Throw

Additionally it would be good if the bind button was disabled/hidden when Cloned mode is selected to avoid any uncertainty of whether a bind operation is actually required.
Initial suggestion is to add something like (with the values Cloned[1] & Normal[0]):
262975517-aaa6d0db-decd-429e-9bb7-7936e989e4be

User would need to:
1. Clone the TX using the DSM_RX protocol using the RX_num to identify the model match number.
2. Go to the DSM protocol select 'Cloned' and then match the subprotocol and RX_num to the model being cloned.
Note: Spektum XOR the model match number with the last byte of the ID, hence the need to select the correct model match number when cloning the TX (so that the ID can be determined without model match).

I have already added the ability to Clone and Erase as DSM TX in my own fork of the MPM repo.  If it would be possible to have a binary with this feature added to allow me to test that would be great (X9d+ & TX16s).

### Describe alternatives you've considered

_No response_

### Additional context

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/396

### PR DESCRIPTION
**Pull request by 3djc**
Support for MPM DSM clone

image

This closes #3969

DSM clone supporting changes are part of MPM 1.3.3.30 and later

### CODE REVIEW

**Comment by pfeerick** [comment]
I think this will just need an option in Companion similar to colorlcd. I've tested this with MPM 1.3.3.33 (that's a lot of 3s!) TAER on TX16S, against a Spektrum DX6i and OrangeRX 615 RX, was able to clone the TX, and connected to RX perfectly.

**Comment by ParkerEde** [comment]
I tried to clone an ext. MPM 1.3.3.20 in a X10 Expr. with MPM 1.3.3.33 and current main for TX16S. Apparently without success.
The ext. MPM 1.3.3.20 is bound to a Blade130S via the DSM X 2F protocol and works correctly. 
I have now set the TX16S to "DSM_RX" and "clonetx", pressed the "Bind" button and the X10S Expr. also pressed the "Bind" button. On the X10S Expr. with ext. MPM it beeped as usual, on the TX16S it did not.
Did I do something wrong, or is it not possible to clone the DSM X 2F of another MPM? After this procedure, I set the TX16S to "DSM" and "cloned" and set the correct RXID. I also deactivate the channel mapping. If I now want to use the TX16S with the Blade130S, no connection is established.

**Comment by 3djc** [comment]
For MPM cloning, there is a much simpler solution since mpm ids can be read/write ....

**Comment by ParkerEde** [comment]
> For MPM cloning, there is a much simpler solution since mpm ids can be read/write ....

was the way I did it the right way? Should it have worked? How can you do this with the MPM ID's read/write?

**Comment by 3djc** [comment]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Lua_scripts/README.md#multiconfig

**Comment by johnnym007** [comment]
Althought the above is an easier method for cloning MPM modules, this should have worked.

It's probably easiest to create a new model in the TX to be cloned.  But not essential.  This will prevent the bind being changed to any existing RXs while cloning.

When in DSM_RX -> Clone_TX ensure that the 'Receiver' numbers on both radios are the same.  Start the bind on DSM_RX radio before the radio being Cloned.

There should be no need to rebind again now.  Select DSM protocol, Cloned & match the protocol settings and Receiver number to the settings of the original TX and everything should work.

**Comment by ParkerEde** [comment]
it works now. My mistake was plain and simple. I forgot to set the RF protocol correctly during the first few attempts. So it has to say:
Mode: MULTI DSM, RF protocol: X 2F, subtype: cloned
Previously I had left it at the default value of 2 1F.

**Pull request merged**
