### PR TITLE
refactor(cpn): Support JSON radio hardware definitions

### LINKED ISSUE #3592: Companion - S1 Knob Switch on FrSky X9 Lite is Non Functioning and Cannot be Assigned
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

No response to S1 rotary knob in Companion V 2.8.3.

### Expected Behavior

S1 rotary knob should be mapped to be configurable as a channel function.
It works fine in OpenTX Companion V 2.3

### Steps To Reproduce

In "Settings - Settings", choose "Radio Type" as FrSky Taranis X9-lite S
On Mixer tab assign S1 to Channel 5
Simulate and observe no movement on Channel 5

### Version

2.8.2

### Transmitter

FrSky X9 Lite / Lite S

### Operating System (OS)

Windows

### OS Version

Windows 10 Home 22H2

### Anything else?

image

### LINKED ISSUE #3982: CPN: LS and RS not set correctly after reading Model and settings from radio
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

in Companion in the hardware settings the sliders LS and RS not set correctly after reading Model and settings from radio

Radio:
image

Companion:
image

### Expected Behavior

in the Comapnion the settings from the radio profile should be taken over correctly after reading the model and radio settings

### Steps To Reproduce

- build companion with RM TX16S with current main 
- make sure that in the radio under Hardware/Sliders LS and RS is assigned correctly and is no longer set to "none"
- start companion
- read modell and radio settings
- observe Radio Settings/TAB Hardware
- both Slider LS and RS are set to "none"

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Win11

### Anything else?

current main

### LINKED ISSUE #4099: Companion - Calibration is not read correctly
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

with latest Companion nightly `0aff002c` the calibration is not read correctly

see the Rudder on screenshot - S1 and S2 are ok, these have been deactivated

Screenshot 2023-09-24 091157

### Expected Behavior

Correct calibration values when reading out the transmitter

### Steps To Reproduce

...

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster Zorro

### Operating System (OS)

Windows

### OS Version

11

### Anything else?

_No response_

### LINKED ISSUE #4507: Companion model print randomly crashes application
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Application crashes randomly

### Expected Behavior

Stable application

### Steps To Reproduce

Random

### Version

Nightly (Please give date/commit below)

### Transmitter

Other (Please specify below)

### Operating System (OS)

Linux, macOS, Windows

### OS Version

Ubuntu 20.04, Win 10

### Anything else?

_No response_

### LINKED ISSUE #4589: Companion model logical switch and special function references to lua outputs not parsed correctly
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Provided lua is checked in radio profile, it is possible to configure logical switch sources as lua script outputs.
After saving the file, closing and reopening, lua references other than output 'a' are missing.

### Expected Behavior

Model file should be parsed correctly

### Steps To Reproduce

1. ensure lua checked in radio profile
2. create a new model
3. add a new logical switch referencing lua sources
4. save the settings and close the file
5. reopen the file
6. references missing where not output 'a'

### Version

2.9.3

### Transmitter

Other (Please specify below)

### Operating System (OS)

Linux, Windows

### OS Version

Ubuntu 20.04, Win 10

### Anything else?

As set
lsluaset

As reloaded
lsluareloaded

Model yaml
Screenshot from 2024-01-31 16-46-02

### PR DESCRIPTION
**Pull request by elecpower**
Summary of changes:
- remove most of the 1st attempt
- move from static board configurations to use radio definitions json files. This also has the advantage of keeping radio sims, firmware and Companion in sync
- group separate structs for same item eg pots into single structs
- maintain support for reading legacy radio settings configuration formats eg bin, otx, etx and convert all formats inc yml as necessary
- yaml encode and decode
- IMPORTANT: 'cmake --build . --target native' and 'cmake --build native --target hardware_defs' MUST be executed for each radio before 'cmake --build . --target native' and 'cmake --build native --target companion'. The companion and simulator targets only includes the files for the pattern '\<build-output\>/native/radio/src/\*.json'. The path will change to something like '\<source directory\>/radio/src/hwdefs/\*.json' when the files are not dynamically generated.

Fixes #3592
Fixes #3982
Fixes #4099
Fixes #4507
Fixes #4589

TODO
- [x] generate hw defn json files on each compile of Companion and remove point in time copies from repo
- [x] issue: extra pots configured as multi pos pot do not respond to gui clicks eg TX16S. Update: appears to be working again.
- [x] gyros ie TILT_X and TILT_Y are not included in json files but need to be in source lists. Should they or if compiler directive then should be profile firmware option rather than hardcoded. Update: hardcode their inclusion until included in json file.
- [x] mouse/joysticks a couple of json files include but most do not so similar to gyros. Update: hardcode their inclusion until included in json file.
- [x] decision: board to board conversion where in past switches were remapped automatically. Update I decided that only a few (mainly FrSky) radios had this implemented, to map based on tags and thus auto re-index.
- [x] clean up code inc removing debug messages, unused code and consolidate
- [x] bucket loads of testing including loading all supported formats, 2.10 and prior yml versions and the usual to and from 2.10 radios
- [x] issue: radio libsim (used TX16S) flex switch position not reflected in Radio Settings Analogs or Switches Test page. Update: convert switch position to analog value and pass value to flex analog. 
- [x] issue: function switches needs further work especially radio libsim eg T20. Update:: do not create std switches
- [x] issue: some json files eg x9d+ do not have default type for flex inputs thus they are initialised to None which is an annoyance for pilots. Unable to determine default for pots and sliders across all radio types. Action: Fix json files or less favourable resort to hardcoding! Update: radio/utils/hw_defs/pot_config.py  had refs to x9dp and x9dp2019 when should be x9d+ and x9d+2019. Fixed with #4489
- [x] treat Function Switches as sub-type of general switches like Flex Switches

TODO Post Merge
- update build instruction documentation for all toolchains
- update scripts for all toolchains
- create list of additional configuration to be included in json files to avoid hardcoding in Companion
- when conversion from older file formats is withdrawn refactor Board namespace to class (too much work for this PR), add json firmware config similar to radio hw config and refactor Firmware (consolidating and simplifying).

### CODE REVIEW

**Comment by pfeerick** [comment]
I'm going to post stuff as I encounter issues, rather than summarise or lump stuff together. I must be one unlucky chump... right out of the bat I hit this (testing will on Windows unless otherwise stated):

With TX16S profile selected I get this message no less than three times. Tried with a new profile, same result

image

**Comment by pfeerick** [comment]
Adding a new Profile

image

Error shows once on selecting Radiomater Pocket as the Radio Type, and then two more times upon clicking Ok to leave the screen. 

Doesn't happen with the Boxer, TPro or X12S profiles I had configured, so I am thinking it's related to the recently added radios.

**Comment by pfeerick** [comment]
Reading the RM Pocket (is running nightly from a few days ago):

Read models OK, upon checking a configured model, inputs had no sources, trim set to no trim (unconfigured so ON in the model). A mixer line with a source was also missing it's source. 

For reference, attached is the model in question, as it was on the radio, and what Companion exported after reading from the radio.

[model_from_radio.zip](https://github.com/EdgeTX/edgetx/files/13937382/model_from_radio.zip)
[model_from_cpn.zip](https://github.com/EdgeTX/edgetx/files/13937386/model_from_cpn.zip)

**Comment by elecpower** [comment]
@pfeerick unable to load [radio].json 99.9% of the time means the json files were not generated prior to Companion being compiled (see my IMPORTANT NOTE above)

**Comment by elecpower** [comment]
If there is no json file then all bets are off about what happens subsequently...

**Comment by elecpower** [comment]
@pfeerick building a libsim will generate its json file as a necessary step

**Comment by elecpower** [comment]
@pfeerick so I downloaded the Appimage from the last commit and it is missing some radios. Will have to scan the build step to see if I can see why. I know the tx16 works as that is one is tested extensively.

**Comment by 3djc** [comment]
I guess the issue might come from recent radio that don't have simu defined (waiting for an automatically generated one). We can define a generic one in the meantime

**Comment by elecpower** [comment]
Looks like one of my clean up/fix-its broke the yaml parser and it was working just fine. Will look at tomorrow. By then the build will have finished so can check the debug messages.

**Comment by elecpower** [comment]
> I'm going to post stuff as I encounter issues, rather than summarise or lump stuff together. I must be one unlucky chump... right out of the bat I hit this (testing will on Windows unless otherwise stated):
> 
> With TX16S profile selected I get this message no less than three times. Tried with a new profile, same result
> 
> image

Yeah just one of those things in the way Boards are handled in the older code and why it needs to be refactored.

**Comment by elecpower** [comment]
> Reading a 2.9 radio with 2.10 firmware (FrSKY X9D+) again has no sources.

Please clarify, as if the firmware is 2.10 then the radio s 2.10 not 2.9 or am I missing something?

**Comment by elecpower** [comment]
Fall on sword moment re yaml :-(
If time hopefully fix tonight.

**Comment by elecpower** [comment]
> Adding a new Profile
> 
> image
> 
> Error shows once on selecting Radiomaster Pocket as the Radio Type, and then two more times upon clicking Ok to leave the screen.
> 
> Doesn't happen with the Boxer, TPro or X12S profiles I had configured, so I am thinking it's related to the recently added radios.

No libsim built for Pocket so that is why it is missing

**Comment by pfeerick** [comment]
When I was saying a 2.9 radio with 2.10 firmware, I was referring to a
radio that existed in 2.9, opposed to a radio added in 2.10.

Only testing with github  checks files, not anything built locally.

**Comment by elecpower** [comment]
> Adding a new Profile
> 
> image
> 
> Error shows once on selecting Radiomaster Pocket as the Radio Type, and then two more times upon clicking Ok to leave the screen.
> 
> Doesn't happen with the Boxer, TPro or X12S profiles I had configured, so I am thinking it's related to the recently added radios.

So the Build logs show that the TX16S is the last libsim compiled. Very strangely, to me at least, is that the hwdef resource file is being constructed every time before a libsim is compiled and not just once before Companion is compiled as was the plan. This explains why the last compiled libsim in this case TX16S is not added to the Companion hwdef resource file.

A CMake guru to the rescue please!

**Comment by pfeerick** [comment]
Ouch... so it looks like each time `cmake --build . --target native-configure` is called in the look in `tools/build-companion.sh` that builds each plugin, your hardware definitions test is being run (hence why the tx16s is missing as the last one run), and the results of each successive pass cached. 

This should probably have been restricted to the package / installer targets? Since that is what `tools/build-companion.sh` uses to actually do the companion build? In the meantime... I'm going to make one possibly naive change to the build script, and see if I can trip it for the companion configure pass... lets see what github actions says! :zany_face:

**Comment by elecpower** [comment]
I just love it when we guess on possible fixes. Sooooo professional.

**Comment by pfeerick** [comment]
lol... well, it'll either work, or break spectacularly 'cause I forget that another command needed to be fun first... I'm hoping to find out in about 4 minutes that it's the first door, but am hedging my bets both ways... :see_no_evil: 

Even if it does work, IMO it's only masking that fact that the hwdef detection is being run when it shouldn't be (as it's not relevant).

**Comment by elecpower** [comment]
I suspect there is other unnecessary stuff running eg guessing qt translations as that is what I based the hwdefs on

**Comment by pfeerick** [comment]
Yeah, reading through that file properly at last, rather than from when I was pulling bits piecemeal from the last update PR, I think it would actually be quite scarey to see when a lot of that stuff is being processed... I think the Companion `CMakeLists.txt` is overdue some TLC... 

It's funny you mentioned the translations... I saw that when scrolling through, and that reminded me where I'd seen the QT LUPDATE commandline before... rather than that script I use... if the dependency is present I should be able to use the `companion_translations` target to do the same update.

**Comment by elecpower** [comment]
@pfeerick the yaml appears fixed or at least better than the mess I made. I have only had time to perform some checks on TX16S Companion and libsim.

**Comment by elecpower** [comment]
@pfeerick just checked the 2.9 Pocket radio file you uploaded and it is still not parsing correctly so I'll revisit the version conversion code and let you know when I think I have fixed

**Comment by elecpower** [comment]
@pfeerick latest commit appears to fix your Pocket model

**Comment by elecpower** [comment]
@pfeerick my latest build hack commit works and TX16S is now included.
From my reading of the cmake doco, it would appear the better solution is to invoke a script to build the hwdefs.qrc and make it a dependency of companion target. Open to suggestions cmake gurus.

**Comment by elecpower** [comment]
@pfeerick checked github win 64 and appimage assets and change to a script works.

**Comment by elecpower** [comment]
The standalone simulator is currently broken. It cannot find any boards. Stay tuned...

**Comment by elecpower** [comment]
Standalone simulator fixed. It was not loading the hwdefs resource file on startup

**Comment by pfeerick** [comment]
Next hiccup I've found, present on Zorro TX16S (maybe all?)... A GF that was set to be ON, and use S1/S2 looses  it's trigger value on read from radio. When I set it to the correct trigger, and attempt a write back, the trigger somehow becomes OFF (it's magic... not even an option!!!). The Zorro lost it's value also (S1/S2) , but that may be because I was reading/writing 2.10... I need to try that again and see exactly what is going on. Attached is a older ETX file that suffers this same issue, from 2.8.3 it seems, and which Companion 2.9 is able to read just fine. 
[TX16S ELRS.zip](https://github.com/EdgeTX/edgetx/files/14000477/TX16S.ELRS.zip)

**Comment by elecpower** [comment]
Also calibration for Thr and Ail are switched

**Comment by elecpower** [comment]
A tweak here and a tweak there. Calibration fixed and GVs load correctly and show in sim.
We really need some Companion test scripts to make our life less complicated.

**Comment by 3djc** [comment]
If you look in test/conversions.cpp, you have the bases at least for reading test, but yes, needs some work

**Comment by elecpower** [comment]
> If you look in test/conversions.cpp, you have the bases at least for reading test, but yes, needs some work

Need to create a Frankenstein model with all the possible settings.
Read it and check
Write it new file name.
Read new file and check.
Even better perform across radio and Companion.

**Comment by elecpower** [comment]
@pfeerick hold off testing. Thanks to Marcopter uncovering another glitch combo for pots and sliders.

**Comment by philmoz** [comment]
I wonder whether a lot of the complexity and compatibility issues could be resolved by using the simulator libraries in Companion to handle the hardware definition details and YAML read/write.

If we expose API's in the simulator library for Companion to get hardware info and read/write YAML files then you no longer need prebuilt json files and remove all the parsing discrepancies.

**Comment by 3djc** [comment]
Well the plan is also to have a standardised simulators feeding from hardware definitions to expose radio specifics, the two are kinda linked

**Comment by philmoz** [comment]
> Well the plan is also to have a standardised simulators feeding from hardware definitions to expose radio specifics, the two are kinda linked

I can understand the appeal of that; but it may have a potential risk of widening the gap between radio firmware and simulator behaviour.

**Comment by 3djc** [comment]
Well, we first started by making the radio firmware behave like this in a way, with that infamous PR breaking everything. There is now fewer differences between radio firmware than that has never been. It's fully there yet, but hal.h has really lost a lot of weight, and many of it is now generated from hardware description files. It still is at compile time, and maybe will have to stay there for current hardware class, maybe even next

**Comment by philmoz** [comment]
Makes sense.

Might still benefit from using the YAML read/write functions in the sim lib instead of having two separate libraries.

**Comment by elecpower** [comment]
> I wonder whether a lot of the complexity and compatibility issues could be resolved by using the simulator libraries in Companion to handle the hardware definition details and YAML read/write.
> 
> If we expose API's in the simulator library for Companion to get hardware info and read/write YAML files then you no longer need prebuilt json files and remove all the parsing discrepancies.

Nice thought but I'm not sure how much we would gain or would we just create a new set of issues.

Companion and radios do not share the same data structures. So there would still need to be before and after API call manipulation. This is in part due to past Dev abuse but more the need for Companion to support all radios in one structure and multiple radios concurrently.

Companion is using the same json files that are used to build the sims/firmware (with some tweaks) so we have improved the alignment. @raphaelcoeffic has indicated his desire to add more info to the json files so we can work towards eliminating hardcoding radio specific features/capabilities in Companion.

Companion supports reading file formats (including early version yaml parsing) that radios have dropped so we would be eliminating some conversion support.

Obviously more heads and more discussion required.

**Comment by elecpower** [comment]
@pfeerick Hi Peter, here is the current status of testing.
Marcopter hasn't reported any new issues since https://github.com/EdgeTX/edgetx/pull/4406/commits/d9519e69c00a2999fca39198af3bba0514ef4434 with his initial testing.
I have created a 2.9.3 TX16S and used every possible source (I think) and every special function.
Converting from 2.9.3 and checked Companion.
Checked simulator..
2.9.3 X9D+ just custom screens converted and simulated.
So back over to you. 
I'll keep testing .

**Comment by pfeerick** [comment]
I've tried several combinations of TX16 and Zorro, pulling configs from 2.9 to 2.10 using Companion, and then reading and writing them back, and nothing _obvious_ is jumping out, so I think you banished most of the gremlins ;) 

Unless there is something outstanding I think its time to merge this, and get more people using it. Then we can also sort out getting at least minimal functionality for the Pocket, etc. (enabling simulator).

**Comment by elecpower** [comment]
I have no other tweaks I wanted to sneak in so let the beast run free

**Comment by Yury-MonZon** [comment]
I'm trying to add my Jumper T20 radio in Companion 2.10-rc1 on Linux. I'm getting this error:
image

Is there anything I'm missing?

**Comment by pfeerick** [comment]
Please wait for 2.10.0-rc2, should be this weekend. Known issu per
https://github.com/EdgeTX/edgetx/issues/4700

**Pull request merged**
