### PR TITLE
Higher baud rates

### PR DESCRIPTION
**Pull request by JyeSmith**
ExpressLRS Tx modules are capable of running at 3.75Mbps (maybe faster?) which is the limit for the x7 (F2).  Users are already very aware of the buad setting and changing it for new hardware or after completing mods such as installing a new inverter.  This option will enable users to who feel the need for speed, and shave more than 500us off end to end latency.

https://github.com/EdgeTX/edgetx/issues/522

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@pkendall64 thx for the additional UI work! That's much better now. I was wondering how that would work otherwise ;-)

**Comment by pkendall64** [comment]
> @pkendall64 thx for the additional UI work! That's much better now. I was wondering how that would work otherwise ;-)

No problem. I don't have any other radios to test with, so I have no idea if x9d or others work.

**Comment by pfeerick** [comment]
So what's the test procedure needed for this (I have a X9D+2019)? Setup CRSF=>ELRS and see if it will still talk at the highest/various refresh/baud rates  I haven't done any hardware mods to this TX (if needed) as it's till got the new toy smell.

**Comment by pfeerick** [comment]
Some preliminary results until I know what the hell I need to be doing! 😁 

Unmodified X9D+2019, Happymodel 2.4Ghz ELRS module, freshly downloaded 'v2' ELRS lua script 

115200, normal or onebit, 250hz packet rate (500hz would never 'lock')
400000, onebit only (normal would not talk at all), 500hz packet rate 
921600, no connect
1870000, no connect
3750000, no connect

**Comment by pkendall64** [comment]
You will have to flash ELRS master branch to your Happymodel module before you will be able to use the higher baud rates.

**Comment by pkendall64** [comment]
A lot of modules and/or radios cannot seem to use the 921600 rate, so we may have to change that to 1Mbaud after all others are tested to work.

**Comment by pfeerick** [comment]
> You will have to flash ELRS master branch to your Happymodel module before you will be able to use the higher baud rates.

Ok, looks like I'm flashing master to it sooner than I planned! 😆 Build done... flashing now...

**Comment by pkendall64** [comment]
> > You will have to flash ELRS master branch to your Happymodel module before you will be able to use the higher baud rates.
> 
> Ok, looks like I'm flashing master to it sooner than I planned! 😆 Build done... flashing now...

Welcome to the crazy house!

**Comment by pfeerick** [comment]
Nah, I'll just make you lives a living nightmare by finding bugs you swear shouldn't exist :-P

Right, so my mistake - I copied the V2 script to the wrong folder, so was using the V1 script before. 

Anyway... now running current master on the happymodel... 

baud | sampling rate | pkt rate | comments
--- | --- | --- | ---
115200 |  onebit | max 250hz  |  normal didn't seem to work
400000 | normal | 500hz | onebit not work
921600 | onebit | 500hz |  normal not work, regardless of pkt rate, never "locked on" properly... kept wandering 
1870000 | normal/onebit | 500hz | normal seemed more stable
3750000 | normal/onebit | | lua script / tx froze up - could power down normally but not exit lua.

**Comment by pkendall64** [comment]
115200 will only reliably work to 150hz on 2.4 modules as theres not enough window to send the data to the module or from module to radio. And at 3750000 many radios with F1 STM chips can't handle that speed.

**Comment by rotorman** [comment]
@pkendall64 EdgeTX supports only radios with STM32F2 and STM32F4 microcontrollers currently. Which STM32F1 radio do you mean?

**Comment by pkendall64** [comment]
> @pkendall64 EdgeTX supports only radios with STM32F2 and STM32F4 microcontrollers currently. Which STM32F1 radio do you mean?

F2 Sorry, The F2 chip doesn't seem powerful enough to do 3.75Mbaud

**Comment by JyeSmith** [comment]
F2 is ok at 3.75 and this is what Ive been testing in the x7.

Tx modules using the F103 will only go up to 1.87 e.g. NamimnoRC.

**Comment by pfeerick** [comment]
> 115200 will only reliably work to 150hz on 2.4 modules 

So it will be different if I try with my 915Mhz module? 

250hz@115200 *seemed* stable, but I started with 150 and went up to 250, as the lua was slow to load otherwise.

**Comment by raphaelcoeffic** [comment]
Just spilling a bit of oil into the fire: shouldn’t this be kind of automatic? Like finding the highest bitrate that works? This setting would merely limit the highest bitrate possible, but it could fall back to lower bitrate in order to make it work?

**Comment by pkendall64** [comment]
Yes, I think on the ELRS end we need to only allow the 250hz and lower rates when 115k baud is selected.
BTW, I have fixed 250hz on 115k on our end in a branch which I'll PR to ELRS soon. Just polishing it up a little more 😄

**Comment by JyeSmith** [comment]
> 
> 
> Just spilling a bit of oil into the fire: shouldn’t this be kind of automatic? Like finding the highest bitrate that works? This setting would merely limit the highest bitrate possible, but it could fall back to lower bitrate in order to make it work?

Sure that will be the end goal.  But this PR will let users start testing higher buads and we can get feedback on what works.

**Comment by rotorman** [comment]
At least two users at Discord are having problems with ELRS and the default high baud rate. Reducing to 400k, seems to solve the issue - thus my suggestion would be to change the default.

Post 1: https://discord.com/channels/839849772864503828/839849772864503832/887395731311300729
Post 2: https://discord.com/channels/839849772864503828/839849772864503832/887792151906361344

**Comment by JyeSmith** [comment]
Yeah, default shouldnt be 3.75M as that wont work on F103 based modules.  Im not sure how to do this, hard code CROSSFIRE_BAUDRATE back to 400k?  @pkendall64 thoughts?

**Comment by pkendall64** [comment]
I'll take a look at this today/tomorrow. I'm not sure how the default is currently set. I assume its just because g_eeGeneral.telemetryBaudrate defaults to 0 and is getting the first rate out of the list which is now 3.75M!

**Comment by pfeerick** [comment]
Thank you, as going to open an issue for that, but this will probably do. I think a default actually needs to be set, rather than simply using the first entry in the list, which was not needed before since 400k was the highest speed anyway.

**Comment by raphaelcoeffic** [comment]
> I'll take a look at this today/tomorrow. I'm not sure how the default is currently set. I assume its just because g_eeGeneral.telemetryBaudrate defaults to 0 and is getting the first rate out of the list which is now 3.75M!

0 should stay the default value, but it can be mapped to 400kpbs. This is because any value that gets added to the binary storage schema without explicit format conversion needs to be 0.

**Pull request merged**
