### PR TITLE
R9M access: fix subtype

### LINKED ISSUE #1585: External R9M ACCESS module does not transmit channel information in f.port mode (telemetry works)
**Describe the bug**
Coming from OTX 2.3.14, i installed EdgeTX 2.6 with externalaccessmod and RC output disappeared from the receiver.
When the receiver is connected, the channel data sometimes refreshes once and stays there until turned off. Moving the sticks does not change the channel outputs.
Telemetry always works fine.

**To Reproduce**
-install EdgeTX 2.6.0

**Expected behavior**
RC channels should work through f.port

**Screenshots**
--

**General information**
 - EdgeTX version  2.6.0 with externalaccessmod
 - Hardware  RM TX16S with R9M 2019 module (fw 1.3.0 flex)
 - R9MX receiver (fw 1.3.2 flex) 
 

Checked 3 times now, the whole setup works fine on OpenTX. 
tested with - flex mode (868MHz) with R9MX receiver
                   - EU (LBT) mode with the same receiver 
I guess there is something wrong with the externalaccessmod.

*edited for clarity

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #1585 

Summary of changes:
- do not send a sub-type for PXX2 R9M modules

### CODE REVIEW

**Comment by pfeerick** [comment]
@brainbubblersbest Would you care to do the honours and confirm this finally puts this to rest? :grin:

**Comment by brainbubblersbest** [comment]
Oh yes. There's nothing Im waiting for more. 😄

**Comment by raphaelcoeffic** [comment]
I just realised that a custom firmware (with `-DHARDWARE_EXTERNAL_ACCESS_MOD=YES`) needs to be compiled to be able to test, so here is a set of test firmware for `TX16S`, `X10` (regular) and `X12S`:
[pr2211-test-firmwares.zip](https://github.com/EdgeTX/edgetx/files/9415034/pr2211-test-firmwares.zip)

**Comment by brainbubblersbest** [comment]
Maybe one thing at least.
On opentx with flex firmware, (if I remember right) the Automatic Power Level was somehow declared? Can anyone check this?

**Comment by raphaelcoeffic** [comment]
@brainbubblersbest this PR is aimed at fixing #1585. So the question here is: does it? We really need to separate issues and not clutter issues/PRs with all sort of other findings. If there is anything to be checked/tracked, it should probably be in another issue.

**Comment by brainbubblersbest** [comment]
Ill check that.

**Pull request merged**
