### PR TITLE
Consistify icons for model setting, select, and category

### PR DESCRIPTION
**Pull request by olliw42**
substitutes https://github.com/EdgeTX/edgetx/pull/123
todo: i made an attempt at new icons but someone may want to create better ones

### CODE REVIEW

**Comment by rotorman** [comment]
Thx Olli, here some impressions:
new_main_menu1
in comparison the old main menu:
old_main_menu1

Models screen:
models

**Comment by pfeerick** [comment]
Icons can get overhauled as part of 2.4.1 theme work, but this at least makes things more consistent! ;) 👍

**Comment by JimB40** [comment]
Much better icon for model selection
With one exception that it’s assumes that models = planes. Still this something for 2.4.1.

but if possible i’d get rid of this second circle.
1. Icon is smaller so harder to see and undersand
2. It has no UI/UX value

marked preferred version (should be with proper icon of course)
62FD59CB-4724-4B46-8C36-06AB7199D060

**Comment by pfeerick** [comment]
Indeed... four of the eight menu icons have circles within circles... Doesn't add an value at all, and even worse, loses some screen real estate to make the icons bigger and more meaningful. I wasn't going to touch on the assumption of planes as that isn't the focus here... it's just consistent icons, not necessary *what* icons are best... that needs to be done as part of the complete overhaul of the UI/UX...

**Comment by olliw42** [comment]
what's upholding this?
maybe not the final as desired by UI people, but better than before, IMHO

**Comment by pfeerick** [comment]
From what I can remember of running it, nothing.  Sure, icons could be better, but that is a bigger UI consistency issue, not an issue with this PR...

**Review by pfeerick — APPROVED** [review]
Makes icons a bit more consistent... graphics can be overhauled properly across the board in 2.4.1

**Pull request merged**
