### PR TITLE
Reset GT911 touch controller on I2C lockup

### PR DESCRIPTION
**Pull request by rotorman**
This PR resets the GT911 touch controller on I2C bus lockup, where GT911 keeps pulling SDA low. Tested on RM TX16S - also many thanks for tips and tests by @rcvideoreviews , @jmildenhall & @NemesisXB at Discord.

Along resetting the GT911, this PR also
1) Increases GT911 refresh period from 10 ms to 20 ms
2) increases X & Y thresholds to 1 (0 keeps outputting them continuously)
3) Reads out the GT911 firmware version number and displays it on radio analog diagnose screen
4) logs I2C hiccups and displays hiccup count on radio analog diagnose screen

### CODE REVIEW

**Comment by rotorman** [comment]
Here example trace on RM TX16S I2C pins:

TX16S I2C 100 kHz

Full [Saleae Logic v1.2.29](https://support.saleae.com/logic-software/legacy-software/older-software-releases) capture attached.
[RM TX16S I2C 100 kHz touch.zip](https://github.com/EdgeTX/edgetx/files/6762524/RM.TX16S.I2C.100.kHz.touch.zip)

**Comment by olliw42** [comment]
this is all just wild speculation based on hope, like the previous "fix", isn't it
if i2c signals are good which one can assume here, usually/often the sda down happens because of conceptually wrong communication like a stop missing or being late and such, i.e., IMHO you rather should look into the communication details
the i2c code looks problematic because (1) it is polling and not isr and (2) has lots of returns which harshly stop communication
(it's in a thread, right, so can be intercepted any time...)
I would think that time might be better spend for reading up a bit on the web to gain a bit more competence on i2c instead of poking in the wild ;) 
IMHO

**Comment by pfeerick** [comment]
Not really wild speculation... and neither was the prior PR - that was aligning the touchscreen drivers settings with known working settings used by the Linux driver, since the same controller is used on cheap tablets, and did prevent some touchscreen driver lockups. Through methodical examination of the problem, Risto has been able to identify that the GT911 is locking up the SDA line (the I2C signals are *not* 'good'), rather than the STM32F4, suggesting it may not actually be something wrong in how OTX/ETX is driving it, but a issue with the chip - i.e. it doesn't like a specific combination of settings, due to a a bug in the GT911s internal firmware, The aim of this PR is to slow the I2C comms down, as well as turn of features not used, in order to test that hypothesis... it's not "wild speculation based on hope".  If this fails, when the GT911 locks up, we're going to have to reset and re-init it... which would just be annoying. This would not be the first time workarounds have had to be done because of faulty silicon firmware, and it won't be the last.

**Comment by rotorman** [comment]
Hi @olliw42 I did some tests while the SDA locks up (also measured voltage over resistor on SDA to make sure it is the GT911 locking to pulling low and not the STM32F4). Here first example where this happens:

Lockup1

and here second:

Lockup2

More details, incl. the full Saleae Logic captures you find in Discord:
a) https://discord.com/channels/839849772864503828/839895574244229152/861173950121902080
b) https://discord.com/channels/839849772864503828/839895574244229152/861266913900494878

In case you detect any I2C irregularities caused by EdgeTX code there, would be very interested to learn, but for me it looks like the GT911 locks up and goes awry, requiring either multiple SCL clocks to come out of lockup or reset. About the first way here, while manually pulling SCL low with test lead:
SCL_toggling_to_get_out_of_lockout
As you see it releases SDA after some SCL cycles.

**Comment by rotorman** [comment]
Touch & slide & repeat seems to be a way to induce the lockup (here with 5750951 thx to @rcvideoreviews on Discord):
https://www.youtube.com/watch?v=gc_DS0lNmHE

**Comment by rotorman** [comment]
It is expected that this PR will fail to build on GitHub, until https://github.com/EdgeTX/libopenui/pull/6 is not yet merged.

**Comment by rotorman** [comment]
@raphaelcoeffic to the rescue. This problem solving continues in PR #413.
Closing here.

**Pull request closed without merging**
