### PR TITLE
chores(lua): generate keys definitions

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by pfeerick** [comment]
Rebasing this will give you a chance to kick the `defined(USE_TRIMS_AS_BUTTOS)` line that snuck in via that other PR (which should probably be `USE_HATS_AS_KEYS`). I'm staying well away from this one as I don't know how to factor that in in the jinja file 🤭 .

For the testing, you just want to know if the correct events fire, and if they still fire? As Robert's [DevTools](https://github.com/JimB40/LUA-Dev-Tools) should help with that.

**Comment by raphaelcoeffic** [comment]
> For the testing, you just want to know if the correct events fire, and if they still fire? As Robert's [DevTools](https://github.com/JimB40/LUA-Dev-Tools) should help with that.

That is the idea, but I would give him the opportunity to check himself, as I know he will complain afterwards otherwise :-D

**Comment by JimB40** [comment]
Wondeful opportunity. To be frank seen better ones 😛

**Comment by pfeerick** [comment]
@raphaelcoeffic Just a friendly reminder that this is still here... wanna do that rebase for me, and take care of the 
`defined(USE_TRIMS_AS_BUTTOS)` which should probably be USE_HATS_AS_KEYS?

**Pull request merged**
