### PR TITLE
fix(color): Unify button colors

### LINKED ISSUE #2304: Buttons look different for Model Setup and
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion Simulator

### Current Behavior

Button in Radio Setup with Background:
image

Same button type in Radio Settings e.g. TOOLS and RADIO SETUP without background:
image
image

### Expected Behavior

consistent graphical represantation

### Steps To Reproduce

Browse through menus

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #2304

Requires EdgeTX/libopenui#67

### CODE REVIEW

**Comment by pfeerick** [comment]
Much better, more consistent now. Reverted to default theme, but also looked better with that theme (Greenfields):
image
image
image

**Comment by Eldenroot** [comment]
I think that "Tools" screen should have the buttons centered... now they are aligned to the left side, why?

**Comment by pfeerick** [comment]
Or perhaps just make them bigger... just centring them is a waste of space! 😜

**Comment by mha1** [comment]
Much much better. Thank you very much! Centering or increasing the size of the button would be the cherry on the cake.

before
image
after
image

**Pull request merged**
