### PR TITLE
Call GV_IS_GV_VALUE() without offset applied

### LINKED ISSUE #722: Output > 101.3% or < -101.3% switches to GV
There are [two reports on Discord](https://discord.com/channels/839849772864503828/839895574244229152/887168111390896138) about this

> hmm, so on my TX16S on build 542213de, if an output is more than 101.3% or less than -101.3%, it turns into a GV instead of -101.3% or something

> same for me with extended limits on it puts them into the GV FW version 2.5.0 (f5c946a0)

@eshifri Any ideas, since it probably stems from #687 ?

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #722

### CODE REVIEW

**Comment by pfeerick** [comment]
Sorry, still broken (at least visually, will test actual output in a moment). With Extended Limits on, min below -101.3 and max above 101.3 breaks the channel ouput view - no bars for output, end stops in the wrong place.

**Comment by pfeerick** [comment]
Basically buggers up output... i.e. setting output min less than or equal to -101.4  and max greater than or equal to 101.4 results in instant servo jumping neutral (center) position and no further movement, which is in line with what is shown on the channel monitor.

**Comment by eshifri** [comment]
The problem is any value above 1024 - (10 + 1) is treated as an index into GV.
So with EL values higher than 101.3 will be interpreted as GVs (with crazy index).
And vice versa: GVs will be shown as strange values.
Probably the easiest solution is to reduce resolution for limits (get rid of PREC1)

**Comment by raphaelcoeffic** [comment]
> The problem is any value above 1024 - (10 + 1) is treated as an index into GV.
> So with EL values higher than 101.3 will be interpreted as GVs (with crazy index).
> And vice versa: GVs will be shown as strange values.
> Probably the easiest solution is to reduce resolution for limits (get rid of PREC1)

Nope, the problem is really that the macro must not be called with the offset applied.

**Comment by eshifri** [comment]
OK, I will take your word. :-) Definitely you know this code better.
I this case similar changes are required for channel_bar.h

**Comment by pfeerick** [comment]
@eshifri Have I missed anything? This appears to be working properly now with and without extended limts, with and without GVs, and channel monitor appears to be matching actual output to receiver. 

The only issue I have encountered now is consistent with OTX, and I don't think it's one that need to be fixed, which is that GVs can take outputs outside of the extended or normal limits. As far as I'm concerned, that is acceptable behaviour, as the limits options are for normal UI functions and ranges, not for when you start fiddling with GVs and don't properly set their limits.

**Comment by eshifri** [comment]
@pfeerick If it works - it works, but channel_bar.h contains several lines like this:
      if (GV_IS_GV_VALUE(ld->min - LIMIT_STD_MAX, -limit, 0)) {
        ldMin = limMin;
      } else {
        ldMin = ld->min;
      }

(Sorry, for some reason my browser refuses to save the lnk)
https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/colorlcd/channel_bar.h#L155
and
https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/colorlcd/channel_bar.h#L203

**Comment by pfeerick** [comment]
Hm, whoops, I forgot to push the commit as I noticed github was being annoying and not building...

**Comment by eshifri** [comment]
Now that should be it!

**Comment by pfeerick** [comment]
Excellent... If you're happy, and checks are happy, I'll merge it in the next half hour or so... and hopefully put this to rest! 😁

**Comment by jmxp69** [comment]
Yay...testing right now.

**Comment by jmxp69** [comment]
Looks good to me! Thanks Guys.

**Pull request merged**
