### PR TITLE
feat(color): Updated to new logo

### PR DESCRIPTION
**Pull request by rotorman**
Updated 480x272 pixel screen splash to use new EdgeTX logo & mascot.

@elecpower Could you please have a look at required Companion changes to use the [new logos](http://edgetx.org/logos/) as well - thx!

### CODE REVIEW

**Comment by froqstar** [comment]
H(edge)hogTX :)

**Comment by rotorman** [comment]
> awaiting for approved graphics rather than my quick and nasty ones.
Please see https://edgetx.org/logos/
You can find there downloadable ZIPs with the new logo and mascot.

**Comment by pfeerick** [comment]
@mhotar While you are looking at #3817, would you be able to look at this PR also, as these four graphics need updating for this to be complete: 

Colorlcd Splash screen - note that this graphic is not used , and only representation, so really should have been deleted, not updated in this PR IMO. The logo is generated out of the next two files as needed for 480x272 and 320x480 displays (and later will also be 480x320 screens). 
https://github.com/EdgeTX/edgetx/blob/main/radio/src/bitmaps/480x272/splash.png

Colorlcd Splash screen - central logo
https://github.com/EdgeTX/edgetx/blob/main/radio/src/bitmaps/480x272/splash_logo.png

Colorlcd  Splash screen - background grid (repeated as needed to fill screen)
https://github.com/EdgeTX/edgetx/blob/main/radio/src/bitmaps/480x272/splash_bg.png

Colorlcd Main Menu Carousel AND screen corner logo
https://github.com/EdgeTX/edgetx/blob/main/radio/src/bitmaps/480x272/default_theme/mask_edgetx.png

B&W 128x64
https://github.com/EdgeTX/edgetx/blob/main/radio/src/bitmaps/128x64/splash.png

B&W 212x64
https://github.com/EdgeTX/edgetx/blob/main/radio/src/bitmaps/212x64/splash.png 

For the colorlcd screen corner logo, something like this seemed to work, would just need to play with the position/sizing, or split it so the menu carousel and corner icons are different. Although, looking again, maybe just the position? Leaving it as a mask is the best option IMO so it always contrasts well with whatever colors are used. 
image

For the B&W 128x64, I was thinking maybe the below logo, but I think the 212x64 would benefit from... something more since has more width to play with...
image

**Comment by pfeerick** [comment]
@JimB40 Any updates on the graphics needed to be able to update the logo for colorlcd and B&W radios?

**Comment by pfeerick** [comment]
Is that scaled, and *then* blown up 500% though? Making it blurrier than it really is?

No problem, if he's busy, he's busy... it'll happen when time permits. It would be "nice to have" for 2.9, but since that was already in RC (and overdue release), I don't see it being that much of an issue if 2.9 stays with old logos.

**Comment by JimB40** [comment]
Nope it is new Box Logo scaled down from 500x500px to 30x30px to preserve quality.
When scaling down you have oprtion to have anti-alias (blurry edges) or not (sharp edges).
We should have sharp-edges (only black & white). 
But then scaling to size like 30x30 with sharp edges give poor result.  Resolution is so small that algorithm place pixeles in wrong place.

So either manual edit is needed on pixel level or there is gfx transformation I'm not aware of.
Let's wait for expert to speak.

Pinged Martin on Discord and he responded with okay, but we can't expect express :)

**Comment by pfeerick** [comment]
No worries, and thanks for the update. I was just looking at the bottom where it says 500%, and assumed you had zoomed the images in after scaling, making blurry even blurrier ;) 

What, have you not heard of AI GFX transformations? It'll be a thing any day now, if it's not already. After all, there's "AI generated artwork" already 🤭

**Comment by mhotar** [comment]
Hello. I had a quick look to these task you want me to try. I am not right person for seamless tiles at background. At least I can try :) In meantime I made a splash screen.
startup2

**Comment by mhotar** [comment]
bootloader_2

**Comment by mhotar** [comment]
Here comes one with tiles. At least I tried. But the one with finer tiles @JimB40 proposed is good as well.
splash_1
bootloader_1
These have all screen long tiles 480x10px
splash_2
splash_2B

**Comment by mhotar** [comment]
Here comes the hardest part 128x64 BW
Here is a few of them, so you can choose from.
bg5

bg1

bg2

bg3
bg4
bg6

**Comment by rotorman** [comment]
@mhotar no chance to include the new circle/star around EdgeTX text for 128x64 BW?

**Comment by mhotar** [comment]
I am not sure. Even the text itself is a challenge.

**Comment by mhotar** [comment]
bg8
bg11
bg12
bg9

**Comment by rotorman** [comment]
This: 
258651434-00e91e67-9930-4179-bcae-12789ce4a692
and the reverse of it, look best to me, although the circling boomerang tips get a bit grainy unfortunately, but with only 64 pixels in height, not much one can do...

**Comment by pfeerick** [comment]
Yes, limited pixels on those screen, so it's only going to be so crisp
(unless you step back 😉). The most important thing is to stay as true to
the logo as possible. Although that does mean a lot of real estate on the
212x64 display isn't used... So while I also like the logo Risro mentioned,
maybe EdgeTX in the proper front for 212x64 (like 1 or 5 for first lot of
examples)? Logo also seems like it would be overly repetitive, so
consistency, maybe the same for 128x64 also? Either way, all of these can
be used as custom splash screens people set themselves, so nothing is lost
in coming up with these different designs. I also like the third one, as
that is a bit of a throwback to Eddie holding the ETX logo.

**Comment by rotorman** [comment]
As discussed in today's project steering committee meeting, gonna merge this PR now as is.
We expect further PR(s) for black-and-white targets and also for Companion to include the new logos as well.

**Pull request merged**
