### PR TITLE
chore: Do not display trims position when trim is set as 3POS

### PR DESCRIPTION
**Pull request by 3djc**
Do not draw the trim position indicator when trims are set to 3POS

### CODE REVIEW

**Comment by froqstar** [comment]
For color LCD this works already?

**Comment by 3djc** [comment]
Part of 2.10 rc1 readme: Unused trim switches can be used as 3POS switches

**Comment by froqstar** [comment]
Should've asked differently:
For color LCD this is not a problem since the trim display code already checks for the trim being a 3pos switch?

**Comment by 3djc** [comment]
I see, no it is not checking, but it is not checking either if trims are disabled I think. Could you have a look @philmoz ?

**Comment by philmoz** [comment]
> I see, no it is not checking, but it is not checking either if trims are disabled I think. Could you have a look @philmoz ?

Quick fix - add this between lines 2 and 3 of MainViewTrim::checkEvents()
```C++
  trim_t v = getRawTrimValue(mixerCurrentFlightMode, stickIndex);
  if (v.mode == TRIM_MODE_NONE || v.mode == TRIM_MODE_3POS) {
    // Hide trim if not being used
    if (!lv_obj_has_flag(lvobj, LV_OBJ_FLAG_HIDDEN))
      lv_obj_add_flag(lvobj, LV_OBJ_FLAG_HIDDEN);
    return;
  } else {
    if (lv_obj_has_flag(lvobj, LV_OBJ_FLAG_HIDDEN))
      lv_obj_clear_flag(lvobj, LV_OBJ_FLAG_HIDDEN);
  }
```

**Pull request merged**
