### PR TITLE
NV14: Small attempt at making controls bigger

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by richardclli** [comment]
The original spacing is very large for NV14, and I did the change to make it similar to horus config.  You can check out this:

https://github.com/EdgeTX/edgetx/commit/784b3c5ab6285a911d37792abeb36a2b040accbd#diff-576b4c2a86fcca794e7f4c0f72877097487ddd75fb4ed145f6e0a61b2bc19ae6

The point is the original large spacing will make the UI seems broken as Icon size not aligned with the spacing properly.  Making it smaller as horus, the screen looks more harmonize but another problem is not friendly with those have large finger.

So not sure what can be done?  Maybe need to have some customized icons for NV14.

**Comment by raphaelcoeffic** [comment]
@richardclli ppl are complaining right now it is very hard to use the controls (buttons, slider, etc). So the question is: what can we do about it?

**Comment by richardclli** [comment]
I think the most problematic part is sliders, one can never slide to the rightmost end, because the screen is narrow and no right margin.  It cannot be helped without UI revamp.

**Comment by JimB40** [comment]
Relates to #170

**Comment by raphaelcoeffic** [comment]
Superseded by #1900

**Pull request closed without merging**
