### PR TITLE
Fixed string option for Lua widgets

### PR DESCRIPTION
**Pull request by jfrickmann**
String options were not working for Lua widgets.

### CODE REVIEW

**Comment by wimalopaan** [comment]
Do we now have string-options with more than 4 chars, and no need to self-decode the 32-bits in lua? 
Great!

**Comment by jfrickmann** [comment]
Yes, there are 8 chars available. It looks like there was something before, but it used that zchar-stuff, which seems to be only used in old model files now. It had already been changed in the Text widget (C++) and the on-screen keyboard, so it was not working here anymore. But it should be fixed now.

**Comment by jfrickmann** [comment]
Actually, I take that back. Lua widgets could _write_ string options as "zchars" (which is wrong) but they have never been able to _read_ anything other than number and color options.

**Comment by wimalopaan** [comment]
I don't think so. Way back to OpenTx and in EdgeTx widgets can read STRING options, by they get the 4-char string as a 32-bit lua-int with the individual bytes as the chars. You need sth like this to decaode:

```
local function isDigit(v)
  return (v >= string.byte("0")) and (v <= string.byte("9"));
end

local function isLetter(v)
  return (v >= string.byte("A") and (v <= string.byte("Z"))) or (v >= string.byte("a") and (v <= string.byte("z")));
end

local function nthChar(n, v)
  local c = bit32.extract(v, n * 8, 8);
  if (isDigit(c) or isLetter(c)) then
    return string.char(c);
  end
  return nil;
end

local function optionString(option)
  local s = "";
  for i = 0,3 do
    local c = nthChar(i, option);
    if (c) then
      s = s .. c;
    else
      return s;
    end;
  end
  return s
end
```

**Comment by jfrickmann** [comment]
Yes, and that is exactly because it reads it as a number. It is a union with 8 bytes allocated to either a string or a 32-bit integer, and it always read it as an integer, even if it should be a string. That's what I have just fixed.

**Comment by wimalopaan** [comment]
Ok, so the new code returns the option as type(v)=="string" now? Just to make the code working with OpenTx and EdgeTx.

**Comment by jfrickmann** [comment]
> Ok, so the new code returns the option as type(v)=="string" now? Just to make the code working with OpenTx and EdgeTx.

Yes

**Comment by wimalopaan** [comment]
This works for me!

If this get's in, we can close https://github.com/EdgeTX/edgetx/issues/793

**Comment by pfeerick** [comment]
Thank you ;)

**Review by pfeerick — APPROVED** [review]
Tested with the following widget on both NV16 and TX16S. Widget went from number garbage instead of string entered in options to showing string entered in options. 

```lua
local options = {
  { "String", STRING, "abc"}
};

local function create(zone, options)
   return {
      zone = zone,
      options = options,
      events = 0
   };
end

local function update(widget, options)
  widget.options = options;
end

local function background(widget)
end
 
function refresh(widget, event, touchState)
   print("s: " .. widget.options.String);
   lcd.drawText(5,5,widget.options.String);
end

return { name="String Test",
	 options = options,
	 create = create,
	 update = update,
	 refresh = refresh,
	 background = background
};

```

**Pull request merged**
