### PR TITLE
Trim fixes

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
- "[...] trim reached" taking configured range into consideration (normal vs extended).
- color lcd: clip values displayed to stay within visual range.

### CODE REVIEW

**Comment by pfeerick** [comment]
Just tried this out... all good - except for the right (elevator in my case) tirm bar - the knob went MIA when "over-trimmed". I especially like the fact that the trims even go yellow (instead of blue) when "over-trimmed", rather than their normal blue. 

image

**Comment by raphaelcoeffic** [comment]
@pfeerick Thx! I had forgotten the vertical trim 🙄😅 It should be fixed now as well.

**Comment by pfeerick** [comment]
I ... I... I have no comeback to that. You *forgot* the verticals trims? But if you need them? 😆

**Comment by pfeerick** [comment]
LGTM... all trim knobs now stay within view, even when trimmed "out of range". If extended trims is turned on, they also stay within view, and turn yellow only when going into their extended range. Trim knob movement range is also adjusted accordingly. :)

**Pull request merged**
