### PR TITLE
Companion: add 3-pos switch neutral to  simulation joystick dialog

### PR DESCRIPTION
**Pull request by hendjoshsr71**
While testing #4687 and configuring my joystick in the simulator there were no positions for the neutral switch position on the 3 position switches. 

**Before:**  "SB-" doesn't show up
image

**After:  "SB-" and "SC-" are selectable states**
image

Testing utilized #4687 as the base branch. See [test branch for pocket](https://github.com/hendjoshsr71/edgetx/tree/pr/siim_add_sb_neutral_to_joystick)

### CODE REVIEW

**Comment by philmoz** [comment]
There is no middle position for switches in Companion joystick setup because it is redundant.
If neither of the switch up or switch down buttons is on then the switch must be in the middle position.
The simulator logic knows this and handles it automatically.

To use the switches on the transmitter in Companion you should configure the joystick setup in Advanced mode then set the button type to Companion.
screenshot_tx16s_24-03-11_12-08-39

**Comment by hendjoshsr71** [comment]
Yes, I'm using the advanced USB config but I didn't see a special mode for Companion. (Thanks btw to whoever did the advanced usb tab work as I can now use a real controller in QGC & Mission Planner easily!)

That is interesting to require a specific mode for just the Companion app. I don't think saving a button because you can deduce the middle position justifies a special mode. (And a special model I need to keep in sync with my others.)

Ideally, the same radio profile for could be used by Companion, QGC, Mission Planner, Liftoff, Real Flight, etc.

**Comment by philmoz** [comment]
> That is interesting to require a specific mode for just the Companion app. I don't think saving a button because you can deduce the middle position justifies a special mode.

When setup fully the advanced mode allows you to use every control on the radio to control the simulator in Companion. This includes all axes, pots, sliders, switches and trims. On a radio like the TX16S there are not enough buttons available in the joystick interface to be able to use 3 buttons for each switch.

**Comment by hendjoshsr71** [comment]
> > That is interesting to require a specific mode for just the Companion app. I don't think saving a button because you can deduce the middle position justifies a special mode.
> 
> When setup fully the advanced mode allows you to use every control on the radio to control the simulator in Companion. This includes all axes, pots, sliders, switches and trims. On a radio like the TX16S there are not enough buttons available in the joystick interface to be able to use 3 buttons for each switch.

Cool! I htought that might be the case

Which joystick interface is this? Windows, linux, a usb thing? Or just Companion?

**Pull request closed without merging**
