### PR TITLE
fix: MPM module status

### LINKED ISSUE #1187: R9M/FLEX colorlcd has missing options
In enabling FLEX support as part of #1043, it was noticed that there is no "S.Port Link Enabled" shown at any time or RF Power option when FLEX selected. 

image
image

### LINKED ISSUE #4197: no telemetry on my zorro
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

since testing the new nightly i found that my telemetry no more works.

after more testing i found the bug comes with #3822. 

 @raphaelcoeffic pls can you check this

here a screenshoot:
screen-2023-10-13-131434

you can see Status: Disable int. and RSSI (0) even though the receiver is connected.

### Expected Behavior

working telemetry

### Steps To Reproduce

use [this firmware](https://github.com/EdgeTX/edgetx/actions/runs/6502139222) on zorro with frsky r-xsr

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster Zorro

### Operating System (OS)

Windows

### OS Version

10 23H2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
We should only consider whether or not the MPM has a working telemetry link.

Fixes an issue introduced in #3822 

Fixes #4197, resolves #1187

### CODE REVIEW

**Comment by pfeerick** [comment]
This fixes the first part of the issue - `TR("Disable int.", "Disable internal RF")` being shown all the time on colorlcd and B&W w/ internal MPM, but now it says No telemetry as mentioned in #4197.

**Comment by raphaelcoeffic** [comment]
> This fixes the first part of the issue - `TR("Disable int.", "Disable internal RF")` being shown all the time on colorlcd and B&W w/ internal MPM, but now it says `No telemetry` as mentioned in #4197. TX16S, Zorro /w internal MPM

Ok, so it's not just the status display thingy: it actually does not have any valid telemetry status.

**Comment by raphaelcoeffic** [comment]
@pfeerick I fixed the second part (in pulses) which has also assuming that S.PORT is used, rather than checking just checking for a RX port in general.

**Comment by TheIsotopes** [comment]
@raphaelcoeffic @pfeerick 
now i tested again and it fixed #4197... thx👍

**Comment by raphaelcoeffic** [comment]
I sneaked in an implementation for #1187 as well, as @gagarinlg was complaining 🤪

**Comment by pfeerick** [comment]
Seems to be working properly now for X9D+2019, TX16S /w MPM, Zorro /w MPM

**Pull request merged**
