### PR TITLE
feat(color): Revert back to using embedded fonts.

### PR DESCRIPTION
**Pull request by philmoz**
PR to revert all fonts back to being embedded in FLASH.

Reasons:
- Concerns raised about ongoing support issues with fonts being on SD card
- Performance issue where startup time may be increased significantly due to the time it takes to load the fonts.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Should I have a look at LZ4 compression to be able reduce the footprint? (obviously not for 2.10, but well)

**Comment by philmoz** [comment]
> Should I have a look at LZ4 compression to be able reduce the footprint? (obviously not for 2.10, but well)

I was thinking about that; but I don't believe it will be simple.

The binary format is not really suitable as it needs a complex loader (lv_font_load) which only works on files - there is no in memory version. And it is slow.

The 'lvgl' format in the .c font files has lots of different structures for each font - the various pointers are currently sorted out at compile time. If we compressed this then the de-compressor would need to be able to relocate and fix up all the references in the decompressed data.

**Comment by raphaelcoeffic** [comment]
> there is no in memory version. And it is slow.

In fact there is now. They merged support for memory backed files and loading fonts from buffer this summer. I cannot comment on the loader though.

> If we compressed this then the de-compressor would need to be able to relocate and fix up all the references in the decompressed data.

I know.... I've been thinking about this for a while now. It would more or less require to patch the structures in RAM, which sounds quite painful and brittle.

**Comment by philmoz** [comment]
> I know.... I've been thinking about this for a while now. It would more or less require to patch the structures in RAM, which sounds quite painful and brittle.

It is possible to LZ4 compress the font data - I created a custom format and a tool to convert and compress the LVGL generated font data. The firmware then decompresses the data and builds the LVGL compatible fonts at run time.

Works in both the simulator and on my TX16S.

Saves 48K for EN fonts and 68K for TW fonts.

It should also be possible in future to convert this to a binary format to be loaded from storage and it should be a lot faster to load than the LVGL binary font format.

Once this PR is merged I'll create a new one with this compression option for review.

**Pull request merged**
