### PR TITLE
Default Theme facelift

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
I'm not yet 100% done, but this way people can already check it out ;-)

image

### CODE REVIEW

**Comment by rotorman** [comment]
Following video shows a bit of present state (9faea55a). Especially the display of selected telemetry screen layout, IMHO could benefit from a contrast boost (in the video roughly at 0:27):
https://www.youtube.com/watch?v=zidA1e8m2bo

**Comment by raphaelcoeffic** [comment]
> Following video shows a bit of present state ([9faea55](https://github.com/EdgeTX/edgetx/commit/9faea55aadc44b545c10b42f0cc8f3de5096af93)). Especially the display of selected telemetry screen layout, IMHO could benefit from a contrast boost (in the video roughly at 0:27, the selected layout to the right of "Layout" can be barely seen presently):
> https://www.youtube.com/watch?v=TS2vsp4DFfA

Fortunately, I haven't looked at these screens yet. It should look much better tomorrow morning.

**Comment by pfeerick** [comment]
Since the back button is showing again (top left)...
image
... which I think is a good thing btw ... can it be a bit bigger, and cover up the logo? ;)

**Comment by raphaelcoeffic** [comment]
> ... which I think is a good thing btw ... can it be a bit bigger, and cover up the logo? ;)

I'm finished making it invisible and transparent 😝

**Comment by rotorman** [comment]
Some impressions of e7f53f98 can be seen in the following video:
https://www.youtube.com/watch?v=yx4DqXilBn4
Looking very very nice!

**Comment by pfeerick** [comment]
> I'm finished making it invisible and transparent stuck_out_tongue_closed_eyes

NOOOOO!!!!! Gimme back my back button! :D Yeah, it was sort covering up the other icon(s), although you could have gotten rid of them instead! :-P 

And damn, you were quick rotorman... nice video! ;)

**Comment by rotorman** [comment]
I tried this time making a video with a simulator for better contrast as compared to filming off screen:

https://www.youtube.com/watch?v=OSc0pMeUXJc

Note, e.g. at 0:38 there is a red tone still visible for curves.

**Comment by rotorman** [comment]
In 5d84efc found further red text:
Red Text

**Comment by pfeerick** [comment]
Looking good! Thanks for bringing back some way of knowing what 'category you are in also ;) 

If power cycling the radio, the select model screen doesn't appear to know which is the active model any more - model settings says it's the Ladybird (correct), model select is highlighting the last model on the list and behaving as if it is the active model. Once it is set it seems to be ok for the session. 

My only other gripe so far would be this (which btw also shows the screenshot functionality works perfectly... this *is* what was on the screen at the time!)
image

I don't know what the trigger is yet... I can cycle the four category pages several times with both page keys and touch and it won't play up, go in and out of the model select screen, and then all of the sudden it will do it. Does not appear to be any rhyme or reason, and I'm not adverse to saying it is the SD card installed.

**Comment by raphaelcoeffic** [comment]
> I don't know what the trigger is yet... I can cycle the four category pages several times with both page keys and touch and it won't play up, go in and out of the model select screen, and then all of the sudden it will do it. Does not appear to be any rhyme or reason, and I'm not adverse to saying it is the SD card installed.

Probably something with memory allocation not done properly. What you are seeing there are random regions in memory.

**Pull request merged**
