### PR TITLE
Simulator data file export fix (version 220)

### LINKED ISSUE #276: double conversions
When opening SIMULATOR for T16 with FILE option, and choosing OpenTX2.3.12 file, it gets converted correctly, including model names and input line names.

When closing the sim, and restarting, it will do the conversion for a second time, messing all up.

### PR DESCRIPTION
**Pull request by rotorman**
Should resolve #276 
@lshems could you please test.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@rotorman the issue here is that, yes, it will fix the issue at hand, but at the same time it will break everything else in Companion, as it does not know the differences between 219 and 220. They are very few, but we still need do it to avoid other related issues. @elecpower it seems we really need your help 😇

**Comment by elecpower** [comment]
@raphaelcoeffic I'm unable to look at until next week. I haven't been tracking all the PRs so I'll check in when I have time to get a summary of all the changes.

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic I'm unable to look at until next week. I haven't been tracking all the PRs so I'll check in when I have time to get a summary of all the changes.

Thx a lot! No problem! You can get an easy overview by looking at the way it is converted in the radio: https://github.com/EdgeTX/edgetx/blob/2.4/radio/src/storage/conversions/conversions_219_220.cpp

**Comment by raphaelcoeffic** [comment]
@rotorman I think this one is obsoleted by #409. Do you agree?

**Comment by rotorman** [comment]
Yep, closing.

**Pull request closed without merging**
