### PR TITLE
Redo PR2583

### PR DESCRIPTION
**Pull request by pfeerick**
Fixes rebase force push screwup... #2583

### CODE REVIEW

**Comment by pfeerick** [comment]
@eshifri So why exactly did we need to resurrect `BREAKSPACE` ?

**Comment by eshifri** [comment]
@pfeerick To be honest I do not remember. :-(
It is not exactly necessary. I think I was following some example in the code.

**Comment by pfeerick** [comment]
lol... I was thinking maybe the audio processing considers the space when speaking and adds a pause? And the BREAKSPACE define was just a way to do that without adding a space to the translation text?

**Comment by pfeerick** [comment]
I'll see if if I can see any difference with and without it.

**Comment by pfeerick** [comment]
@eshifri Let me know what you think of that change - I'm open to suggestions or better use of the existing flags ;) English only wants the singular for 1, and then plural from then onwards, but was being caught up in the PLURAL1 handling every time the last digit was 1

**Comment by eshifri** [comment]
Yes, BREAKSPACE was used to insert a SPACE :-). Somehow, I decided it was better than adding an empty space before the word.
The intention was to define PLURAL1==PLURAL2 for some languages. I think it more convenient than the flag, but it is not a "strong opinion". :-)

**Comment by pfeerick** [comment]
It made sense while BREAKSPACE existed, but now it's just a nuisance. Even then, it was something that was probably better calculated out on the fly while generating the UI rather than tacking onto the translations... i.e. IMO translations shouldn't have any formatting attached to them... (glares at the CENTER and INDENT formatting 🤭😆)

More than welcome to tweak and improve it further... at this point, I just wanted to stop it doing "21 minute", "31 minute" instead of "21 minutes", "31 minutes", etc. 😉

**Comment by eshifri** [comment]
Isn't it sufficient to change
#define TR_USE_SINGULAR_IN_PLURAL   1
from 1 to 0 in English?

Obviously, I do not have any nostalgic feelings for BREAKSPACE. :-)

**Comment by pfeerick** [comment]
Oh, much better :)

**Pull request merged**
