### PR TITLE
Change TR2 and TR3 definitions for TR_for_NV14

### LINKED ISSUE #2254: NV14 Text issues Telemetry and Model setup
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When checking Telemetry Tab/Page found text on top of each outer and not clearly readable. Picture attached.

Also the, Model Setup page, graphic needs better contrast for active lettering, too hard to read in Sun light. Picture attached.
IMG_20220831_101553
IMG_20220831_101625

### Expected Behavior

To be able to clearly read all text displayed.

### Steps To Reproduce

Go to Telemetry Tab/Page and see text on top of each out, not readable.
Model Setup page and see active button displayed. Active button text is White change colour to Black.

### Version

Nightly (Please give date/commit below)

### Transmitter

FlySky NV14

### Anything else?

I like Edgetx.
General information
EdgeTX "Black Pearl" v2.8.0-Nightly (e6697bca)
FLYSKY NV14 
FS-iA6B

### PR DESCRIPTION
**Pull request by eshifri**
Fixes #2254

Summary of changes: use shorter strings for NV14

### CODE REVIEW

**Comment by pfeerick** [comment]
I think it only fixes it indirectly - the real issue being that tab hasn't been converted yet to use flex layouts. Hence the text wrapping isn't being properly taken into account. 

The second part of that issue is then one of colors used - I'm not sure if that's properly doable yet as I don't think a color field was allocated for active button text color.

**Comment by pfeerick** [comment]
Aw... c'mon... you didn't want to port the entire page over? 😆 I don't blame you... I actually did start doing that... and was making progress, and then threw in the towel when I got to the sensor table view... as I didn't think leaving that code commented out was a viable option🤪

**Comment by eshifri** [comment]
I thought somebody was working on it. :-)
And since my knowledge of lvgl is at the beginner level, I do not think I'm the right person to interfere with this work. :-)

Would it be a reasonable approach to leave the table as is and convert the rest of the page?
Or there will be a problem with the content after the table?

**Comment by pfeerick** [comment]
> I thought somebody was working on it. :-)
> And since my knowledge of lvgl is at the beginner level, I do not think I'm the right person to interfere with this work. :-)
> 
> Would it be a reasonable approach to leave the table as is and convert the rest of the page?
> Or there will be a problem with the content after the table?

It's a todo ;) I don't think it's as simple as that as once you start porting the rest of the page to flex layout then sensor table doesn't know how to fit in. It'll happen eventually :)

**Pull request closed without merging**
