### PR TITLE
fix(cpn): Add radio specific name and label validators

### LINKED ISSUE #4603: Character set bug when transferring between radio and companion
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Other (Please specify below)

### Current Behavior

The bug happens when transferring models back and forth between firmware and companion (windows).
2.9.3 in both firmware and companion
I got a model label called "Sjö" (swedish for sea as in seaplane)
When transferring to companion the label gets duplicated to "SjÃ" and "Sjö". The models gets moved from the label Sjö to "SjÃ".
When transferring back to firmware I got two labels instead of one.

### Expected Behavior

Labels with international character set is kept intact when transferring back and forth between companion and firmware

### Steps To Reproduce

Create a label in the companion with international characters, example "Sjö"
Transfer models and settings to the radio
Assign a model to that label in the radio
Transfer models to companion
Two labels exists "SjÃ" and "Sjö"

### Version

2.9.3

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Windows 11 64bit

### Anything else?

bug-companion-characterset

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #4603

Summary of changes:
- change Utf8 to Latin1
- add radio lcd type name and label validators based on firmware permitted characters
- validate names and labels on yaml decode and replace an invalid character with a space. Note: Leading and trailing spaces are removed. 
- use new validators for GUI validation and ensure all name fields are validated
- autolineedit no longer assumes char field is a name. ie now behaves the same as QString field. Up to the dev to assign a validator when required.

Notes
- needs a non-English locale user to test to ensure Qt is not localising the regular expressions.

### CODE REVIEW

**Comment by pfeerick** [comment]
@mha1 @HThuren Any chance you can check if this PRs Companion works for you in native language/locale?... i.e. does it read and write without mangling model names, mix names, etc? Can probably get away with just a read and then compare against the radio, as all the validation and fixups should be done at read time...

**Comment by mha1** [comment]
non-English locale user means Companion language other than English regardless of firmware/radio language?

**Comment by mha1** [comment]
I checked this PR's CPN GUI with language set to German and a few of my models. LGTM. Most of the times German special characters (Umlauts and 'ß') are destroyed in localization but looking good here.

One thing I noticed is the model creation wizard allows to input German special characters which are not valid in model names. Consequently saving the created model will receive the standard MODELxx name. It's just confusing.

In general Translations need some love. There are quite a few missing spread over the entire CPN GUI. Example: Labels Management:  2 out of 5 missing. 
image
Don't look at me ...

**Comment by elecpower** [comment]
> One thing I noticed is the model creation wizard allows to input German special characters which are not valid in model names. 

Good catch. Fix coming soon...

**Comment by elecpower** [comment]
Added some more translation items while I was at it

**Comment by pfeerick** [comment]
> Edit: I can't see mangling of model names, mixer names or anything else happening on LCD radios because the keyboard doesn't offer special language specific special characters. The keyboard is the same for all radio languages

Thanks for that, was going to be the next thing I was going to check, but I suspected language specific special characters were limited to display (i.e. translations) with common input. Maybe something we can improve as more translation and localisation improvements are done, but that is for a future discussion. So this should just be making sure Companion is consistent with what the firmware will let you input, and sanitises the values if you tried to put invalid characters in manually. I know this going to make some people unhappy as the firmware can display some of the characters, but there are characters that won't be displayed, so better to make Companion match what the firmware actually lets you input.

**Pull request merged**
