### PR TITLE
feat(cpn): add keys to T20 simulator for rotary encoder movement

### PR DESCRIPTION
**Pull request by philmoz**
For us Mac users without scroll wheels 😄

### CODE REVIEW

**Comment by pfeerick** [comment]
Wait, what? Macs don't have squeaky wheels?

**Review by pfeerick — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
Last time I checked it worked with the normal scroll gesture. It doesn‘t anymore?

**Comment by 3djc** [comment]
We have whells without wheel on the mouse no ?

**Comment by pfeerick** [comment]
It probably does - but might do three clicks per swipe, which is no fun at all.

**Comment by raphaelcoeffic** [comment]
> We have wheels without wheel on the mouse no ?

This?
Screenshot 2024-07-08 at 13 27 52

**Pull request merged**
