### PR TITLE
(re)enable mute for TX16S based on RM feedback

### PR DESCRIPTION
**Pull request by 3djc**
Based on feedback received from Radiomaster customers, they would prefer to re-enable mute for TX16S.

I'll do later a user configurable version, but for 2.10

Would be nice if this one could be part of 2.9

### CODE REVIEW

**Comment by mha1** [comment]
I lost most of the touch audio feedback (beep on touch)

**Comment by 3djc** [comment]
Previous 'reference test' was trim, trim works fine, I guess we need to fine tune for touch then.

Is that on first touch or rapidly repeating ?

**Comment by 3djc** [comment]
I guess I'm not doing the right test

https://github.com/EdgeTX/edgetx/assets/5167938/e16667ee-6483-41f2-9689-d86610be8325

**Comment by mha1** [comment]
Is this the tonight's nightly? I'll try again

**Comment by mha1** [comment]
hit the EdgeTX logo, select model settings (does it beep?), then touch the icons on the top bar one after the other

**Comment by 3djc** [comment]
image

I guess your audio circuit might be a little off spec and would require slightly different mute/unmute values? But as said above, bets fix is to have it optionnal

**Comment by mha1** [comment]
as far as I understand it you changed the unmute delay for the TX16s from 120ms to 150ms. What was the problem?

**Comment by mha1** [comment]
Another symptom: the EdgeTX startup message "welcome to EdgeTX" is truncated to "elcome to EdgeTX". The "W" is inaudible.

**Comment by mha1** [comment]
Playing with the numbers doesn't seem to make a difference. Reverting your PR brings back the full welcome message and all touch beeps. I don't think I have a "special" out of spec TX16s (not MKII). That's why I think this PR should not be in 2.9 unless your 2.10 UI change goes with it.

**Comment by 3djc** [comment]
We have to understand better since nearly all radio use the feature, I will try to find if one of my tx16s behaves like yours and ask Radiomaster to conduct further tests

**Comment by mha1** [comment]
I'll continue tomorrow with a scratch built SD card, radio.yml and a minimal model.yml to exclude config side effects. If still persistent I'll upload a video demonstrating the chopped welcome message and missing touch beeps.

**Comment by 3djc** [comment]
Beginning of 'welcome ' cut means you need to raise unmute delay. Try 170 maybe instead of 150

**Comment by pfeerick** [comment]
I've tried three different TX16S - a very early TX16S from when non-touch was an option, and two later ones that are somewhere between the MK1 and MK2, and for all three I get the beeps on touch when sound set to all, and I don't think the welcome of `hello.wav` is being trimmed on mine. Sorry, I can't help with a reproducible case there! I have no issue merging https://github.com/EdgeTX/edgetx/pull/3703 once we've added the companion side support, but would still like to know what's different here.

**Comment by 3djc** [comment]
Same here, tested all 3 I have, cannot reproduce, and 150ms is already quite a margin above chip specification (100ms)

image

**Comment by mha1** [comment]
170ms didn't change it so I cleared the SD card, just put 2.8 release sounds on it and let the radio with tonight's nightly flashed create virgin radio.yml and model01.yml files. No more truncated welcome message. I blame my home brew sounds. But touch feedback is still the same. I noticed leaving gaps between successive touches don't have beeps, fast successive touches have beeps, most likely omitting the beep for the first one, see video https://www.youtube.com/watch?v=KxXazxZTPpU

If you want to recreated the exact condition of my test scenario flash [tx16s-009b638.bin.txt](https://github.com/EdgeTX/edgetx/files/11833332/tx16s-009b638.bin.txt) and put this on your SD card [RADIO.zip](https://github.com/EdgeTX/edgetx/files/11833317/RADIO.zip)

image

**Comment by 3djc** [comment]
image

https://github.com/EdgeTX/edgetx/assets/5167938/681613de-6c55-468c-b9ba-19dfcb082054

Absolutely cannot reproduce.  I seem to remenber some people near launch did mod their audio because sound wasn't loud enough, did you do any of that ?

The way mute work is dead simple. It ways no sound for AUDIO_MUTE_DELAY duration. When there has been no sound for that long, audio chip is muted. When next sound comes, it unmutes audio chip, wait AUDIO_UNMUTE_DELAY, then play the sound.

If you don't hear the 'first beep', it means despite waiting AUDIO_UNMUTE_DELAY, the audio circuit is still not ready. Keep increasing AUDIO_UNMUTE_DELAY, so that we understand what is the value for your chip

**Comment by mha1** [comment]
Nope, no HW mod whatsoever.

PS: Firefox won't show your video

**Comment by mha1** [comment]
Are you sure beeps are queued and not played instantly?

**Comment by 3djc** [comment]
Thats the whole purpose

> Nope, no HW mod whatsoever.
> 
> PS: Firefox won't show your video

Edge and chrome will tho

**Comment by 3djc** [comment]
image

image

See for yourself...

Thats actually the whole issue around mute, and why it is such an annoyance, it introduces a lag of AUDIO_UNMUTE_DELAY ms

**Comment by mha1** [comment]
ok, we're getting there. 500ms makes all touches beep and as expected with a very noticeable latency. I'll do some builds to find the threshold.

**Comment by 3djc** [comment]
Those values are used by default in nearly all otx/edgetx radio but tx16s, because RM has done an amazing job at shielding audio circuit on that radio, so it is really something that those values dont work on your radio (and as I said, already include de 50% safety margin vs chip specification)

**Comment by mha1** [comment]
Result: 250ms works reliable, 240ms works but you can hear a tiny first part of the beep missing

What do we do with this? My radio sure seems not representative but it shows there are radios out there which haven't studied the specs (at least as far as the audio chip is concerned). If you want to stick with 150ms the UI options seems mandatory.

**Comment by 3djc** [comment]
Such a high value has me wonder if your 5v regulator hasn't blown up and audio is powered by vbat. Anyhow, I think we want the UI choice, agreed @pfeerick ?

**Comment by mha1** [comment]
Does the 5V regulator also supply AUX1 and AUX2?

**Comment by mha1** [comment]
Answered myself, no, Audio has its own 5V regulator. From Risto's blog:

image

**Comment by mha1** [comment]
Where did you find the IDChip 8002A data sheet? I only found chinese versions of the datasheet.

**Comment by mha1** [comment]
Put my scope to good use and checked the audio voltage regulator. Rock steady and noise free 5V. But my radio has a 8002D chip not a 8002A as described in Risto'S TX16s HW blog. Dunno if that make the difference.

**Comment by 3djc** [comment]
I have asked RM about it, but they have some kind of dragon festival or something like that, may be a couple of days before I get an answer

**Comment by mha1** [comment]
Can you take a look at one of your working radios which version of the 8002 it has exactly?

**Comment by mha1** [comment]
I have extended CPN with PR #3710 as counterpart to your PR #3703. It adds a checkbox to CPN's Edit Radio Settings page.

resulting radio.yml:
Box unchecked -> audioMuteEnable: 0
Box checked -> audioMuteEnable: 1

image
image

**Comment by mha1** [comment]
Michael

**Comment by 3djc** [comment]
> Michael

Boy, usually elecpower jumps in like that, did not even look at the author, my apologies (to both of you!)

**Comment by mha1** [comment]
No problemo, I should have formally introduced myself :-)

It'll still take a while to finish the check builds. I'd appreciate you trying this. And there is one thing I didn't know off hand. Currently the checkbox will be available for all radios. Are there any rules to follow, i.e. exclude specific radios or radio categories?

**Comment by 3djc** [comment]
Radio side it is based on hall defines, currently that's all non frsky radio (unsure about flysky, did not check)

**Comment by pfeerick** [comment]
The UI option will be a good mitigation for this, as we can then wait for reports that the sound is being clipped, and then just tell people to use the option to restore the old behaviour. If we get enough reports that it's a problem, we can change things... i.e. maybe will have to bring in a configurable option and just pre-load it with the current values. Then it will be end of the issue, period 😆

**Comment by mha1** [comment]
@3djc Yes, I saw your UI implementation is tied to AUDIO_MUTE_GPIO being defined. Look at the hal.h files I'd say the UI option should be visible for:
- all Color LCD radios (including NV14 and the likes) except Horus X12S
- TX12, TX12MK2, ZORRO, BOXER, T8, TLITE, TPRO, LR3PRO

Correct?

I'll update the CPN PR to reflect this.

**Comment by 3djc** [comment]
Looks correct. Ins't brand defined anywhere in Companion (did not look), that would be easier than de radio list

**Comment by mha1** [comment]
I forgot Commando8. That has AUDIO_MUTE_GPIO defined.

No, but it has a family "T12 board" defined:

```
inline bool IS_FAMILY_T12(Board::Type board)
{
  return board == Board::BOARD_JUMPER_T12 ||
         board == Board::BOARD_RADIOMASTER_TX12 ||
         board == Board::BOARD_RADIOMASTER_TX12_MK2 ||
         board == Board::BOARD_RADIOMASTER_ZORRO ||
         board == Board::BOARD_RADIOMASTER_BOXER ||
         board == Board::BOARD_RADIOMASTER_T8 ||
         board == Board::BOARD_JUMPER_TLITE ||
         board == Board::BOARD_JUMPER_TLITE_F4 ||
         board == Board::BOARD_JUMPER_TPRO ||
         board == Board::BOARD_BETAFPV_LR3PRO ||
         board == Board::BOARD_IFLIGHT_COMMANDO8;
}
```

The only difference is it lists TLITE_F4 which isn't listed in taranis/hal.h. I suppose it is treated as TLITE in radio code, i.e. has a audio mute GPIO too. Correct?

This would be the resulting term for CPN:

```
    case HasAudioMuteGPIO:
      // All color lcd (including NV14) except Horus X12S
      // TX12, TX12MK2, ZORRO, BOXER, T8, TLITE, TPRO, LR3PRO, COMMANDO8
      return ((IS_FAMILY_HORUS_OR_T16(board) && !IS_HORUS_X12S(board)) ||   
              (IS_FAMILY_T12(board) && !(board == Board::BOARD_JUMPER_TLITE_F4)));
```

**Comment by pfeerick** [comment]
TLITE_F4 is basically identical to the TLITE, it's just a different processor, so that looks about right.

**Pull request merged**
