### PR TITLE
feat: CPP Widget names also translatable

### LINKED ISSUE #2443: Built-in widget names are not translated
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I don't know if it's a bug or if these selections are hard-coded, but I don't think so.
I believe instead that they are translated but they remain in English despite having chosen Italian.

### Expected Behavior

They should appear in the chosen language.

### Steps To Reproduce

1. Go to TELE, User Interface, Set Widget
2. Choose a box
3. Click on "select widget"

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #2443

All of the built-in widgets now set a display name, which is translatable. The internal name is not changed, hence configured widgets will survive changes in language ;)

### CODE REVIEW

**Comment by pfeerick** [comment]
If you would be so kind:
```
#define TR_WIDGET_GAUGE                "Gauge"
#define TR_WIDGET_MODELBMP             "Models"
#define TR_WIDGET_OUTPUTS              "Outputs"
#define TR_WIDGET_TEXT                 "Text"
#define TR_WIDGET_TIMER                "Timer"
#define TR_WIDGET_VALUE                "Value"
```

@ParkerEde DE
@ulfhedlund SE
@Eldenroot CZ
@robustini IT

**Comment by robustini** [comment]
#define TR_WIDGET_GAUGE                "Indicatore"
#define TR_WIDGET_MODELBMP             "Immagine"
#define TR_WIDGET_OUTPUTS              "Uscite"
#define TR_WIDGET_TEXT                 "Testo"
#define TR_WIDGET_TIMER                "Timer"
#define TR_WIDGET_VALUE                "Valore"

**Comment by ulfhedlund** [comment]
Swedish
#define TR_WIDGET_GAUGE              "Mätare"
#define TR_WIDGET_MODELBMP      "Modeller"
#define TR_WIDGET_OUTPUTS          "Output"
#define TR_WIDGET_TEXT                  "Text"
#define TR_WIDGET_TIMER                "Timer"
#define TR_WIDGET_VALUE                "Värde"

**Comment by Eldenroot** [comment]
CZ
#define TR_WIDGET_GAUGE "Měřidlo"
#define TR_WIDGET_MODELBMP "Modely"
#define TR_WIDGET_OUTPUTS "Výstupy"
#define TR_WIDGET_TEXT "Text"
#define TR_WIDGET_TIMER "Časovač"
#define TR_WIDGET_VALUE "Hodnota"

I will check one more time later today after work

**Comment by ParkerEde** [comment]
DE

**Comment by pfeerick** [comment]
Thank you all :)

@zyren I forgot to tag you also - are you able to do CN / TW translations?

```
#define TR_WIDGET_GAUGE                "Gauge"
#define TR_WIDGET_MODELBMP             "Models"
#define TR_WIDGET_OUTPUTS              "Outputs"
#define TR_WIDGET_TEXT                 "Text"
#define TR_WIDGET_TIMER                "Timer"
#define TR_WIDGET_VALUE                "Value"
```

And from PR #2397
```
#define TR_MODELS_MOVED "Unused models moved to"
```

**Comment by robustini** [comment]
@pfeerick locally tested, all ok!

**Comment by ParkerEde** [comment]
@pfeerick if possible please:
DE
#define TR_WIDGET_MODELBMP "Modellfoto"

**Comment by Eldenroot** [comment]
Is it model or model image?

**Comment by robustini** [comment]
> Is it model or model image?

Yes, actually also in Italian it would be "Immagine modello" if it fits as character numbers.

**Comment by ParkerEde** [comment]
> Is it model or model image?

it is model image

**Comment by robustini** [comment]
"Immagine modello" in Italian fits as the number of characters, so I update my comment above.

**Comment by robustini** [comment]
> So, some historical trivia... the widget was originally called ModelBMP, because all it did was show the model image. But it can also show the model name, and if you don't set an image can be used to just show the model name. So it got renamed "Models" since "ModelBMP" made no sense anyway since it wasn't limited to BMP images.

LGTM, so I update my comment above with "Modelli".

**Comment by robustini** [comment]
> So, some historical trivia... the widget was originally called ModelBMP, because all it did was show the model image. But it can also show the model name, and if you don't set an image can be used to just show the model name. So it got renamed "Models" since "ModelBMP" made no sense anyway since it wasn't limited to BMP images.

In Italian it seems as if one would select one of the existing models, and not the image and label of that model, so "Models" is not right imho.
In italian is better "Immagine modello" or simply "Immagine".

**Comment by pfeerick** [comment]
> @pfeerick is doesn't show the model name if it ends up on the top bar,

Correct... because the top bar would only show a couple of characters of the name at best ;)

And if you remove the image, from the model, it will show the title only, and you can adjust the size and colour of the model name via the widget options. So I don't think there is one single short easy name for it, as "Model Name and Image" isn't a nice short widget name ;) I'm just letting you know know why it's not called ModelBMP any more. If you can come up with a better name even better. Or if you feel the equivalent of "Model Image" is the best name for it that's fine (and good to know) :)

**Comment by robustini** [comment]
I noticed that two lines are also supported in the selection, so I would put it in full "Immagine e nome modello".

**Comment by ulfhedlund** [comment]
It would be great if you could change the Swedish translation as follows:
#define TR_WIDGET_MODELBMP "Modellbild"

**Comment by ulfhedlund** [comment]
> > @pfeerick is doesn't show the model name if it ends up on the top bar,
> 
> Correct... because the top bar would only show a couple of characters of the name at best ;)
> 
> And if you remove the image from the model, it will show the title only, and you can adjust the size and colour of the model name via the widget options. So I don't think there is one single short easy name for it, as "Model Name and Image" isn't a nice short widget name ;) I'm just letting you know know why it's not called ModelBMP any more. If you can come up with a better name even better. Or if you feel the equivalent of "Model Image" is the best name for it that's fine (and good to know) :)

How about "Model info"?

**Comment by pfeerick** [comment]
Sounds fine to me... If you are all happy with that we can change it to that.

**Comment by robustini** [comment]
> How about "Model info"?

That widget shows either the model image only or the image and the name of the model as I have shown above, too misleading to use "info" for this thing in my opinion.

**Comment by ParkerEde** [comment]
@pfeerick okay than please:
DE
#define TR_WIDGET_MODELBMP "Modellinfo"

**Comment by Eldenroot** [comment]
CZ edited.

**Comment by zyren** [comment]
CN Translation:

#define TR_WIDGET_GAUGE                "行程"
#define TR_WIDGET_MODELBMP             "模型信息"
#define TR_WIDGET_OUTPUTS              "输出"
#define TR_WIDGET_TEXT                 "文本"
#define TR_WIDGET_TIMER                "计时器"
#define TR_WIDGET_VALUE                "数值"

#define TR_MODELS_MOVED "未使用模型移至"

**Comment by zyren** [comment]
TW Translation:

#define TR_WIDGET_GAUGE "行程"
#define TR_WIDGET_MODELBMP "模型信息"
#define TR_WIDGET_OUTPUTS "輸出"
#define TR_WIDGET_TEXT "文本"
#define TR_WIDGET_TIMER "計時器"
#define TR_WIDGET_VALUE "數值"

#define TR_MODELS_MOVED "未使用模型移至"

**Pull request merged**
