### PR TITLE
Fixed issue #1500

### PR DESCRIPTION
**Pull request by jfrickmann**
Works on my TX16S. @raphaelcoeffic should verify that it does not break something in Companion!

### CODE REVIEW

**Comment by jfrickmann** [comment]
#1500

**Comment by jfrickmann** [comment]
This solution is incomplete. The radio reads YAML data generated by Companion correctly, but it writes it back wrongly.

**Comment by jfrickmann** [comment]
OK, I think that I got it fixed both ways now

**Review by pfeerick — APPROVED** [review]
This seems to work perfectly on TX16S and TX12 running 2.6.0, and also fixes it in simulator. This also fixes a a conversion issue 2.5.0 -> 2.6.0 i.e. where -GV9 became `-GV:` and `-GV1` became `-GV2` . Looking at the trace line right above one of your changes it looks like it was *supposed* to be '0' all along, but obviously wasn't. Nice catch! :)

**Pull request merged**
