### PR TITLE
fix: Deactivate logs and close log file if USB is connected

### LINKED ISSUE #4023: SD card error when logging is active and USB connected/disconnect
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

- Activate SD card logging
- Plug in USB connection to PC while logging is active
- select USB storage
- disconnect USB conection
- SD card error message pops up

### Expected Behavior

No error message

### Steps To Reproduce

see section current behavior, also present in 2.9 an main

### Version

2.8.5

### Transmitter

Flysky NV14

### Operating System (OS)

Windows

### OS Version

_No response_

### Anything else?

my bad, missed a use case

### PR DESCRIPTION
**Pull request by mha1**
Fixes #4023

### CODE REVIEW

**Comment by pfeerick** [comment]
At a glance it looks fine, so I'll probably push this to 2.9 and 2.8 branches. There aren't any 2.8 releases planned at this time, but it'll be there if that changes.

**Comment by mha1** [comment]
what's going on with checks?

**Comment by pfeerick** [comment]
Changes to the docker container meaning a recent change in main is needed.

**Comment by mha1** [comment]
yes, I figured. libclang missuing. checks ran fine after rebasing 1h ago

**Comment by pfeerick** [comment]
Not as easy as I expected to repo... on the TX16S with default 1s logging it actually didn't seem to want to error on me... when I brought it down to 0.3s it started breaking 😆

**Comment by mha1** [comment]
don't you hate those sneaky little bastards that are trying to trick you into thinking everything is ok?

Thanks for merging.

**Pull request merged**
