### PR TITLE
chore(translation): CZ "Manage Models"

### PR DESCRIPTION
**Pull request by mhotar**
I got an email from Petr Faltus asking for this change. Which seems to be reasonable. He tested the change on TX16S.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Nevím...

**Comment by mhotar** [comment]
@Eldenroot
I have not reviewed this change in context of the real radio menu in person. If you are not sure with this change, as being the edgetx translator for CZ. I am going to close this pull request. Do you agree?

**Comment by Eldenroot** [comment]
Provide us a screenshot of this change and why you want to change it...

**Comment by pfeerick** [comment]
Perhaps because "manage models" had the exact same translation string as "model setup"?

**Comment by pfeerick** [comment]
I.e. Doesn't this PR change it so manage models _actually_ says something like manage models in CZ , rather than model setup/model settings?

**Comment by Eldenroot** [comment]
Thats the issue, if we wanna change it, we need to use 2 different strings,

**Comment by pfeerick** [comment]
Please actually look at the change made... There **are** two separate translation strings, and one was duplicated! :facepalm:

**Comment by Eldenroot** [comment]
You are right, I am sorry.. both of you. Anyway this needs some testing, I will flash the nightly and we will see.

**Pull request merged**
