### PR TITLE
feat(ui): Value widget text alignment options

### PR DESCRIPTION
**Pull request by rotorman**
Adds two new options to value widget to align label and value optionally also to center or right border of the widget zone:

grafik

grafik

I tried my best with translations, but am pretty sure that there are some languages that I did not manage to match perfectly.

### CODE REVIEW

**Comment by Eldenroot** [comment]
CZ is fine, just only one typo (it was here before your PR, if you can fix it in this PR would be nice). Thx!

**Comment by elecpower** [comment]
@rotorman I assume you would like me to sync Companion so got it

**Comment by rotorman** [comment]
> CZ is fine, just only one typo (it was here before your PR, if you can fix it in this PR would be nice). Thx!

Sure, what should I fix?

@elecpower yes, please! Thx!

**Comment by Eldenroot** [comment]
I added a comment
image

**Comment by elecpower** [comment]
@rotorman done

**Comment by pfeerick** [comment]
> I added a comment

@Eldenroot Just FYI - it says pending in that screenshot - so you didn't actually _submit_ the comment/review... hence why it didn't show up ;)

**Review by pfeerick — APPROVED** [review]
LGTM. Works fine when coming from a version of the widget without the extra options (i.e. no change), aligns nicely, and opts survived being read/written with companion.

**Comment by phileville** [comment]
Would it be possible to also add these options to the "Text" widget as well?

**Pull request merged**
