### PR TITLE
Show true raw analog output on diagnose page

### PR DESCRIPTION
**Pull request by rotorman**
Show true unscaled and unfiltered analogs for diagnose purpose on the analog diagnose screen.

Tested on physical RM TX16S and RM Zorro.

### CODE REVIEW

**Comment by rotorman** [comment]
This PR results that the display output is wiggly - which on the diagnose page is im my opinion a good thing - it shows the reality of the signal. But on the other hand if the value flickering is too fast, the last digit(s) become unreadable.
I do not wish to filter them, but am thinking that it would be possibly a good idea to lower the refresh rate of the analogs diagnose page down to some 5 fps max. in order for a human to be able to still read the values.

**Comment by pfeerick** [comment]
Given how much the value would change, almost seems like it is worth averaging it over say 0.25 seconds, and also showing the amount of deviation from the average over that period... but slowing it down will do ;)

**Comment by rotorman** [comment]
I explicitly opted against any smoothing (=averaging) in order to show the user the real raw value. As these typically are jittery, well the diagnose page should IMHO also show it. The default 20 Hz flickering (menusTask period) was too much for the eye to see the digits, especially on black and white LCD screens the last digits were without the refresh rate slow-down barely visible due to ghosting. In my opinion the current state of this PR is pretty optimal, but I am open to improvement suggestions!

One of the goals behind this PR is also to be able to get rid of analog switches calibration (think here 6-Position, or PL18EV stick end switches) and have a good and safe pre-programmed detection borders. For this we need some raw data from the users to be able to see manufacturing tolerances.

**Review by pfeerick — APPROVED** [review]
It's usable in it's current form. I was surprised how laggy 5 times per second became (partially because I was looking for it) - I almost want to make so it reverts to live if the delta has changed more than say 50. 😆 

> Indeed one option would be to show the average value with the deviation, but this takes more screen space.

Or perhaps look at how this was done in other parts of the UI where lines were too long ;) It would periodically alternate the values shown. 

Since we are talking of data sampling for analog switch positons, this is why I think at some point we need to look at the average, and max pos and neg deviation for that - then a user can report something like 1POS = 1200 avg, min 1180, max 1209 without having to sit there and watch the numbers, trying to spot the highest and lowest. Needs to be as simple as possible if you want more people to do it ;) Or even better, can we do something through the SD logging?

**Comment by rotorman** [comment]
@pfeerick In the latest commit, I created your suggestion of time-changing views: the std. mixer values, the filtered raw with deviation and the unfiltered raw.
Presently, the view is changed every 5 sec, but ideally, IMHO, it would be nicer for the user to be able to select a view. For example using keys (e.g. Page), a roller, or swiping, instead of automatically advancing. Would you have tips to achieve this?

**Comment by pfeerick** [comment]
At this point, I think you effectively have three view, so perhaps better to go three separate tabs for colorlcd... then normal page btns and touch works to change tabs? On B&W I would advance by time for simplicity of interface, otherwise page for next.

**Comment by rotorman** [comment]
I am happy with the final result (presently only color radios have the latest advancements implemented). The analogs dialog page has now 4 tabs for the user to choose:

1) std. calibrated values, display output as known previously:

analogs_diagnose_tab1

This page also lists the touch screen data and optional IMU data (which will be better off moved to dedicated pages in the future).

2) Filtered raw values with maximum deviation shown (not statistical std. deviation, but max. deviation in raw ADC units !):

analogs_diagnose_tab2

3) Unfiltered raw values (1-to-1 without any frame-rate limitation, jittery)

analogs_diagnose_tab3

4) Minimum, maximum and range (=max-min) page. Actively moving all sticks from one limit to the other is required by the user.

analogs_diagnose_tab4

I bluntly stole some already in the system available icons for the tabs - surely there can be better suited versions of them, but just created by someone with more artistic talent than me...

Please let me know what you think. Thx!

**Comment by rotorman** [comment]
Added two analog diagnose views to 128x64 B/W radios as well - a user can now choose between a calibrated analogs view and a raw values view with a display output limited to 5 frames-per-second due to visibility reasons on B/W LCD displays.

Here screenshots of both views in question:
CA

RA

**Comment by rotorman** [comment]
In latest commit, I added similar 2 page option also to 212x64 pixel B/W radios. Due to lack of such radio on my side, I was only able to test this commit in simulator:

screenshot_x9d+_22-01-19_22-29-24

screenshot_x9d+_22-01-19_22-29-50

It would be sweet, if somebody with a 212x64 pixel radio could at least once test this PR on real radio, before merging. Thx!

**Comment by pfeerick** [comment]
I'll try out the three variants later today... This is looking really nice Risto! :)

**Comment by pfeerick** [comment]
Dammit Risto! I was about to post this diff for you to fix that up (as well as use the same syntax used elsewhere so you stop repeating yourself ;) ) Three if blocks doing the same thing? ;)

image

[t-pro.patch.txt](https://github.com/EdgeTX/edgetx/files/7903253/t-pro.patch.txt)
 
Anyway, X9D+2019 and TX16S were perfect. T-Pro, well, you can guess ;) 


IMG_20220120_172259 (Large)

IMG_20220120_172315 (Large)

IMG_20220120_173239 (Large)

**Comment by rotorman** [comment]
@pfeerick thank you for the improvements on key handling and style!

**Comment by pfeerick** [comment]
No problem... I know my own code doesn't follow the DRY (Don't Repeat Yourself) principle at times / whilst it's still a WiP :grin: So are you right with merging this if everything works now?

**Comment by rotorman** [comment]
If you deem it worthy for merging, then yes - it looks good on my side. Thx!

**Comment by pfeerick** [comment]
Ok, I'll do last round of testing and then it will be right for tomorrows nightly and pushing back to 2.6

**Review by pfeerick — APPROVED** [review]
LGTM on TX16S, NV14, X9D+2016 and TPro. It's a wrap (for now!).

**Pull request merged**
