### PR TITLE
Support internal module as a hardware setting

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- introduce a new hardware setting for internal module
- model setup will only allow the internal module set in hardware settings

### CODE REVIEW

**Comment by brainbubblersbest** [comment]
Please merge.
Can i Download via tortoise git to self compile by type branch "select-internal-Module" ?

**Comment by raphaelcoeffic** [comment]
> Please merge.
> Can i Download via tortoise git to self compile by type branch "select-internal-Module" ?

You should be able to check out the branch, I believe. Every Git client should support this.

**Comment by pfeerick** [comment]
- TX16S - haven't tested beyond UI behaviour yet, but menus are present, and changes in radio hardware page are being reflected in model setup. 
- X9D+2019  - is not present, but code indicates is X9 radios specifically excluded. 
- TX12 - havn't tested beyond UI behaviour yet, menus present, changes in hardware page are being reflected in model setup

It is rather funny that if you had say 'MULTI' selected in either colorlcd or B&W case that they are still shown in model setup after making the change in hardware, but that is holding true to how the model is configured. And how many times do you swap the internal module anyway. 😆 I don't know if it is worth somehow indicating that it is invalid though. 

Seemingly unrelated to this PR (was present in nightly also), there are seem to be two blank lines that have parameters/consume scroll at the bottom of the screen for both X9D+2019 and TX12.

**Comment by pfeerick** [comment]
> Can i Download via tortoise git to self compile by type branch "select-internal-Module" ?

Yes, `select-internal-module` is the right branch to use for this PR. 
https://tortoisegit.org/docs/tortoisegit/tgit-dug-checkout.html

**Comment by brainbubblersbest** [comment]
Thank you both.
@pfeerick It definately reduce the amount of possible compile variations.
Same for Serial rewrite. Were you can choose the connected device at runtime. 
Wouldnt it be better to blend this options out later in the gui, by sort of a checklist menu, If not wanted by User side?

**Comment by pfeerick** [comment]
The typical user would set it once in the lifetime of their radio (unless they change the internal module) - assuming it can't be auto-detected. So it 1) as you say, reduces compile variations,  2) allows for more flexibility without compilation as to what the internal module will be,  3) is a matter of setting the option and forgetting. 

What exactly would this look like, other than the option as it stands now, in the radio hardware settings screen?
> Wouldnt it be better to blend this options out later in the gui, by sort of a checklist menu, If not wanted by User side?

**Review by pfeerick — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
> Wouldnt it be better to blend this options out later in the gui, by sort of a checklist menu, If not wanted by User side?

"ausblenden"? As in, hide the menu item away?

**Comment by brainbubblersbest** [comment]
> > Wouldnt it be better to blend this options out later in the gui, by sort of a checklist menu, If not wanted by User side?
> 
> "ausblenden"? As in, hide the menu item away?

Yes. So this 
1-would reduce compile variants

2-hide Menu settings for "typical users" to avoid confusions

3-advanced users, or users that want to swap factory installed hardware to a other one have the ability to unhide this Menu entries. Like an Advanced Mode. 

It's just an idea for deliver easy usage or advanced functions in the same firmware.bin
Like Developer options on Android. 
Or Advanced Mode on EdgeTX Flasher.

**Comment by raphaelcoeffic** [comment]
> 1-would reduce compile variants

That is what the PR does.

> 2-hide Menu settings for "typical users" to avoid confusions

The module is already set by default to what it probably is (depending on the radio model)

> 3-advanced users, or users that want to swap factory installed hardware to another one have the ability to unhide this Menu entries. Like an Advanced Mode.

So basically we would trade the "Internal Module" hardware menu item against a "Unhide the internal module setting" menu item? You see the problem?

But I get your idea. It makes sense in my mind to basically hide most of the settings in "Hardware" behind sub-screens, and basically only offer a couple of buttons that allow you to select what you would want to setup. This would "hide" it a bit more, without adding an additional menu item.

**Comment by brainbubblersbest** [comment]
> > 1-would reduce compile variants
> 
> That is what the PR does.
> 
> > 2-hide Menu settings for "typical users" to avoid confusions
> 
> The module is already set by default to what it probably is (depending on the radio model)
> 
> > 3-advanced users, or users that want to swap factory installed hardware to another one have the ability to unhide this Menu entries. Like an Advanced Mode.
> 
> So basically we would trade the "Internal Module" hardware menu item against a "Unhide the internal module setting" menu item? You see the problem?
> 
> But I get your idea. It makes sense in my mind to basically hide most of the settings in "Hardware" behind sub-screens, and basically only offer a couple of buttons that allow you to select what you would want to setup. This would "hide" it a bit more, without adding an additional menu item.

Yes, or in that way. 
To be More specific i mean just hide the non Standard Things.
With edgetx, there is already a lot of new possibilitys. Like isrm in a rmt16s. There is no need for the User to select it. Till He physically changed it to that. This would avoid future topics like: I choose isrm on my t16s. And still cannot bind with access receivers. Why my mpm cannot bind to access Hardware?
Or: cannot use Externalaccess after select it. (but has not done additional wiring)
I think most of the users just buy a Radio and fly. 
They dont want to change anything physically inside it. But If, they can activate it anytime as an additional function.

**Comment by raphaelcoeffic** [comment]
> I think most of the users just buy a Radio and fly.

No problem with that. In that case, the setting should just not be changed. In fact, most of the hardware settings are basically bogus then. We could just leave the "Names", and activate all the rest with a "Advanced" button.

**Comment by brainbubblersbest** [comment]
Oh my... I finally come to Flash d775e75 and realized that i miss understand something.
Yes thats already what i meant. 🙄
Sorry for that. 
It's perfect. 😅

**Comment by pfeerick** [comment]
> Oh my... I finally come to Flash [d775e75](https://github.com/EdgeTX/edgetx/commit/d775e75e81b35ea2729ef053ce34e205b6a967e4) and realized that i miss understand something.

Yeah, that usually helps! 😆 I was going to say I really don't get the point, since the setting is hidden away enough  - I basically view the hardware tab as 'advanced' anyway... as most people will never touch it, or when they do, it's for very specific tasks. I'm glad you like it... this really opens up more flexible configuration options... no need to custom compile if not running a 'stock' internal module! :)

**Comment by wimalopaan** [comment]
Just realized that on X9E radio there is NO internal module selectable.
I used this cmake line
cmake -DHELI=OFF -DTRANSLATIONS=DE -DPCB=X9E -DGVARS=YES -DLUA=YES -DXJT=ON  -DOVERRIDE_CHANNEL_FUNCTION=OFF -DCMAKE_BUILD_TYPE=Release ..
Looks like tihis has todo with the hardware-settings page, where one can select the type of internal module
this setting isn't present on the x9e now

**Pull request merged**
