### PR TITLE
Add tap count to simulator

### PR DESCRIPTION
**Pull request by jfrickmann**
For double tap etc.

### CODE REVIEW

**Comment by pfeerick** [comment]
Works great Jesper! :) Thank you once again!

**Comment by wimalopaan** [comment]
How do I generate tap events in simulator?

**Comment by pfeerick** [comment]
You click the mouse :-P

**Comment by pfeerick** [comment]
New Windows Companion build is here => https://github.com/EdgeTX/edgetx/actions/runs/1235705469 (latest build can always be found [here](https://github.com/EdgeTX/edgetx/actions/workflows/win_cpn.yml). 

Mac Build is under way...

**Comment by jfrickmann** [comment]
Awesome 😀🍻

**Pull request merged**
