### PR TITLE
fix(cpn): halt when multiple locations for read and write models and settings detected

### PR DESCRIPTION
**Pull request by elecpower**
Quick and nasty. Revisit in binary clean up.

### CODE REVIEW

**Comment by pfeerick** [comment]
This only warns (with a scary, critical warning msgbox) right? It doesn't b0rk the read/write until the indeterminate location is fixed? Not asking for changes, just checking verbiage is correct ;) This could possibly be considered a feat(ure) rather than a (bug) fix, given it is alerting the user to what could be considered a configuration issue.

**Comment by pfeerick** [comment]
Deliberately separating this from the last comment as it's more about future planning/discussion. Not entirely sure of a reliable way to make this really lock on to the radio, without starting to check for multiple folders. As can't really rely on the `.yml` being present in case it's a new radio/SD that hasn't been booted yet. There is the sdcard version file, but obviously if it's a really old sd card pack, or someone has for whatever reason decided to delete that file, it's not much help. 

What're your thoughts as to future fix... detect multiple possible paths, and show a drive picker, throwing the problem to the user to resolve (and become aware of)? Only other thing I can think of is a signature file/UUID that goes with each profile, and you look for that (as well?)...

**Comment by elecpower** [comment]
...and thus why I kept it crude at this point. Stop reading and writing from/to unexpected location.

The pick list is the way to go but the whole thing needs refactoring as the numerous checks that have been added over time are scattered thru the calls. Need to bring them back to the top level for an optimum user experience.

**Comment by pfeerick** [comment]
LGTM

https://github.com/user-attachments/assets/cfca3e3d-9896-4e68-aa27-f98e8a807915

**Pull request merged**
