### PR TITLE
feat: option to disable power on/off haptic

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
 - Adds an option to Radio Settings that allows for the haptic on power on and off to be disabled. It is on by default, preserving existing behaviour of radios. 

Text for the menu entry is currently
```cpp
TR("Pwr ON/OFF Haptic","Power ON/OFF Haptic")
```
unless there is any suggested alternative. 

Has been tested on 
- Boxer
- LR3Pro
- TPro
- TX16S
- X9D+2019

### CODE REVIEW

**Comment by ParkerEde** [comment]
DE
TR("Pwr AN/AUS Haptik","Power AN/AUS Haptik")

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 Will be merged in seven days or when translations complete, whichever comes first. 

```
TR("Pwr ON/OFF Haptic","Power ON/OFF Haptic")
```
image
image
image

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [x] DE
- [ ] @Pat6874 FR
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU

**Comment by zyren** [comment]
CN

```c
TR("开关机震动","开关机震动提示")
```

*****************************************

TW

```c
TR("開關機震動","開關機震動提示")
```

**Comment by Pat6874** [comment]
FR:

TR("Pwr ON/OFF Vibreur","Power ON/OFF Vibreur")

**Comment by HThuren** [comment]
DA

#define TR_PWR_ON_OFF_HAPTIC           TR("Vib. strøm til/fra","Vibrator strøm til/fra")

**Comment by Eldenroot** [comment]
CZ:

TR("Zap ON/OFF vibrace","Zapnutí ON/OFF vibrace")

**Comment by robustini** [comment]
IT
TR("Vibraz. Pwr ON/OFF","Vibrazione Pwr ON/OFF")

**Comment by zandorsp** [comment]
PT:
TR("Vibra ao LIG/DESL", "Vibrar ao Lig/Desl")

**Comment by ToshihiroMakuuchi** [comment]
JP:
TR("Pwr ON/OFF Haptic","電源 ON/OFF 時のバイブ")

**Comment by ulfhedlund** [comment]
SE
#define TR_PWR_ON_OFF_HAPTIC            TR("Tx AV/PÅ vibr.","Radio AV/PÅ vibration")

**Comment by ajjjjjjjj** [comment]
PL
```c
TR("Wibracja włączania","Wibracja włączania")
```

**Pull request merged**
