### PR TITLE
Add live data to Telemetry Edit Screen

### PR DESCRIPTION
**Pull request by dlktdr**
Was trying to calibrate the remote battery voltage today and it was a little more difficult than it should have been without live feedback. 

This pull request adds a <s>footer bar at the bottom</s> header on the telemetry edit screen showing the live value. Font goes red on stale data.

Let me know if this is an okay place for it. Only issue I see is if you use the OSK it hides the footer.

Tested on TX16S.

image

### CODE REVIEW

**Comment by pfeerick** [comment]
I like :) What about putting it in the header? There is precedent for putting "live" stuff in the header... i.e. Special Function / Logical Switch active state highlight...

**Comment by dlktdr** [comment]
I didn't even notice the data on those pages.. 👍 

Change Made 
image

**Comment by pfeerick** [comment]
Looks great... thank you! Makes some use of that otherwise "dead space" that is the header bar :)

**Comment by dlktdr** [comment]
Last commit to correct this issue here.
## Before
image

## After
image

**Comment by eshifri** [comment]
How about comment in line 31? :-)

**Review by pfeerick — APPROVED** [review]
Looks and works great on TX16S and NV14. Thank you! :)

**Pull request merged**
