### PR TITLE
fix(color): personal templates saved to wrong folder

### LINKED ISSUE #4885: Radiomaster TX16S Saves New Template In Wrong Directory
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When creating a new template from an existing model, the template is saved under the directory `/TEMPLATES/PERSONAL`. In the current vanilla SD card contents (v2.9.0 Sept 3, 2023) for the TX16S, there is no directory named `/TEMPLATES/PERSONAL` in the `/TEMPLATES` folder. My understanding is that the OS creates the `/TEMPLATES/PERSONAL` directory when the first template is created from a model. I believe this is incorrect behavior for the current SD card file structure.

### Expected Behavior

The vanilla v2.9.0 SD card file structure in the TEMPLATES directory already contains the following folders: `1.Wizard`, `2.Personal`, and `3.SoarETX`. It is my assumption that for this given structure, the function that creates the new template should place the `new_template.yml` file in `/TEMPLATES/2.Personal` to adhere to this SD card structure.

### Steps To Reproduce

1. Enter model manager screen
2. Select any existing model. Click it, and in the context menu create a template from that model
3. A message appears asking to accept the creation of the template and its name. Press yes to create the template
4. Press the SYS button to enter system menu
5. Page to the SD Card tab
6. Enter the TEMPLATES folder.
7. There will be four folders, the one in question is `TEMPLATES/PERSONAL`

### Version

2.9.4

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Change personal template folder name to match SD card layout.

Fixes #4885

### CODE REVIEW

**Comment by pfeerick** [comment]
I see three options here:
- revert the change in the SD card pack
- merge this, and tell users rename the folders so they don't have two folders. 
- silently rename on the handset if the old folder(s) are present...

I prefer the first out of simplicity, but think the third is better for end users as they don't need to do anything.

**Comment by philmoz** [comment]
It looks like the TEMPLATE folders were renamed Sep 2023 so reverting these would affect anyone who has updated their SD card contents.

It should be possible to add a startup check to rename folders (if the new ones are not present).
If both TEMPLATES/PERSONAL and TEMPLATES/2.Personal exist then we can move any files to the new folder.

**Comment by philmoz** [comment]
I've take a slightly different approach to the folder renaming concern.

If the new folder exists (2.Personal) the template is saved there.
If the new folder does not exist; but the old one does (PERSONAL), then the template is saved there.
If neither folder exists then the new folder is created and the template saved to it.

This way it works regardless of whether the user has updated their SD card contents or not.
It also avoid trying to guess what to do when both folders exist (i.e. it's up to the user to clean up).

**Comment by pfeerick** [comment]
And state would naturally be if both exist, it will use the new `2.Personal` in preference to the old `PERSONAL`. 

Sounds good to me... If there are two sets of folders I'm sure the user will do something about it then ;)

**Pull request merged**
