### PR TITLE
Widget colours

### LINKED ISSUE #258: Timer: Change widget colour
>I would use the darker blue.
https://github.com/EdgeTX/edgetx/issues/252#issuecomment-863846834

It's currently red

https://github.com/EdgeTX/edgetx/blob/2.4/radio/src/gui/colorlcd/widgets/timer.cpp

### PR DESCRIPTION
**Pull request by pfeerick**
Finally looked at how to get rid of some more of that red ;)

First up is the timer, before on the left, after on the right:
timer

Then since I saw that the colour change also had some impact on the output bar widget... I thought I'd de-redify it also.
outputs

I leave it up to you if you want to merge one or both - hence two commits. The colour isn't that good for the text on the output bars when they overlap, but it also isn't that great with the red... so I think for now it's an acceptable compromise until we decide what happens with the widgets and colours. 

The colour variables tweaked only seem to apply two those two widgets. 

Closes #258

### CODE REVIEW

**Comment by JimB40** [comment]
Feeling blue now @pfeerick . :)  
Thx didnt want to escalate issue for 2.4.0 as priority is low

Still after bar's color change text (output name) is barely visible.
1. Mimic solution from Gauge Widget where text color changes to light (light blue or white) in part that is under dark bar.
204156356_215548767081697_1601111668056054465_n

2. Use lighter color from palette to suit both light and dark background (like #14A0E5)

**Comment by pfeerick** [comment]
Indeed... baby steps. :)

Yes, the way the gauge does resolve that problem. ... I'll have to look and see if I can ~~steal~~ borrow that mechanism here also. But seems like it would require there be a background on the bar though. Have to see how it actually works.

For 2, that's the blue of the trim knobs, isn't it?
image

**Comment by JimB40** [comment]
Seems the same. gave you rgb hex code in previos post

**Comment by pfeerick** [comment]
@JimB40 So is this more like what you had in mind? 
image
image

**Comment by pfeerick** [comment]
Note to self... resolve https://github.com/EdgeTX/edgetx/issues/430 as part of this.

**Comment by pfeerick** [comment]
I'm going to close this PR, and start afresh, now that the colour theme/naming changes are in effect - the changes planned as part of this PR are no longer relevant, but new ones have arisen ;)

**Pull request closed without merging**
