### PR TITLE
fix: external MPM flash

### PR DESCRIPTION
**Pull request by mha1**
Summary of changes:
- specific pulse timer inits for and pwm toggle mode
- set correct RX/TX polarity for MPM bootloader
- extended flash process timeout from 12.5ms to 100ms as robustness measure

### CODE REVIEW

**Comment by pfeerick** [comment]
@raphaelcoeffic I've only tried this on the TX16S with external MPM, but it has resolved the flashing issue for that. I did a bisect and asked Michael to take a look at it, as it all went horribly wrong at (prior to that, there was the occasional mid-flash failure, but this PR onwards introduced complete inability to flash. 

Next up will be TX12, X9D+ and external MPM, and also an STM32 ELRS module. 

```
6aa1fc90c483ad29c8c12e6eba596f276d83aa18 is the first bad commit
commit 6aa1fc90c483ad29c8c12e6eba596f276d83aa18
Author: Raphael Coeffic <raphaelcoeffic@users.noreply.github.com>
Date:   Fri May 5 11:20:29 2023 +0200

    fix: signal polarity for soft-serial & timer based protocols (#3513)
 ```

**Comment by ParkerEde** [comment]
I tested this PR with the Horus X10S Express and the TARANIS QX7S ACCESS. The ext. MPM could be flashed correctly

**Comment by mha1** [comment]
As a proud owner of a new external RM 4in1 MPM I can confirm flashing the module is not working in main but working with this PR (as it did with my ext MPM flash PC simulator)

**Comment by pfeerick** [comment]
Perfect timing Maestro! 

- RM TX12 w/ iRange 4in1 MPM 🟢 
- Frsky X9D+ w/ RM 4in1 MPM 🟢 
- RM TX12MK2 w/ HM ES915TX ELRS 🟢 
- Jumper T-Pro internal MPM & external RM 4in1 MPM 🟢

**Comment by mha1** [comment]
Thank you

**Pull request merged**
