### PR TITLE
refactor(color): Use LVGL styles and objects for UI, legacy cleanup

### PR DESCRIPTION
**Pull request by philmoz**
This is a big refactor of the color UI code - hopefully without breaking too much; but there are bound to be some teething problems.

Main goals:
- Use LVGL styles and objects for UI
- Consistency
- Cleanup legacy code
- Groundwork for 3.0

For the most part things should look pretty much the same; however there are a few UI changes to note.

Focus border has been made thicker to be more visible:
Screenshot 2023-12-12 at 11 31 04 am

Text color on active item is PRIMARY1:
Screenshot 2023-12-12 at 11 32 01 am

Tick marks on sliders display over slider bar:
Screenshot 2023-12-11 at 5 26 03 pm

When editing screen layouts the selected widget has the solid border and the others have a dashed border:
Screenshot 2023-12-11 at 4 25 18 pm

Topbar battery icon shows battery level as a colored bar - green >= 60%, amber 25% - 59%, red < 25% (these are LVGL, not theme colors):
Screenshot 2023-12-11 at 4 23 32 pm

Timer widget count up/down bar uses an LVGL arc instead of a PNG image.:
Screenshot 2023-12-11 at 4 24 10 pm

Guage widget % value moved to above the bar - LVGL has no equivalent to the invertRect() function previously used.
Screenshot 2023-12-11 at 4 24 46 pm

### CODE REVIEW

**Comment by pfeerick** [comment]
From the screenshots, a lot of this looks better. However, till will have to wait until we branch off for 2.10 for merge, given the amount of change involved. 

@JimB40 I noticed in https://github.com/EdgeTX/edgetx/issues/3220 you never did anything for the mixer lines... any thoughts re: changing the active mixer line font color to PRIMARY1?

**Comment by philmoz** [comment]
Updated USB SD connected display:
screen-2023-12-12-191605

**Comment by raphaelcoeffic** [comment]
@philmoz looks good to me! Looks like tremendous amount of work!

**Comment by philmoz** [comment]
As of last commit this is now 18K smaller than current main on TX16S.

**Comment by philmoz** [comment]
Using one of the debug tools in LVGL it's possible to visualise the screen redraw/refresh overhead.
In the videos below, LVGL changes the color of any screen area that is being redrawn.

2.9 - yikes!:
https://github.com/EdgeTX/edgetx/assets/9474356/26149f2f-d7cc-4c3a-b9d9-daf25420d57e

2.10 main branch - better:
https://github.com/EdgeTX/edgetx/assets/9474356/874db46c-eb3d-4312-bd28-3dcfa9a0de7f

This PR:
https://github.com/EdgeTX/edgetx/assets/9474356/e9838ac8-3148-4cd6-bfd4-402d31efa682

Lua widgets still redraw every 100ms (or so) - we really need a better display API for Lua apps.

**Comment by richardclli** [comment]
So there will be a performance boost after this PR is applied?

> Using one of the debug tools in LVGL it's possible to visualise the screen redraw/refresh overhead. In the videos below, LVGL changes the color of any screen area that is being redrawn.

**Comment by philmoz** [comment]
> So there will be a performance boost after this PR is applied?

Well the CPU will be doing less work refreshing stuff so there should be some improvement.
How much is hard to determine - there are some pages that take a while to build; but this is LVGL overhead so they don't change.

On my TX16S this PR feels more responsive overall; but that could be my imagination :)

**Comment by XuNeo** [comment]
Hi @philmoz ,
> Lua widgets still redraw every 100ms (or so) - we really need a better display API for Lua apps.

I have developed a [lua lvgl binding](https://github.com/XuNeo/luavgl). It's not 100% finished yet, but I would love to hear from your input to make it better. 

The binding will be upgraded to lvgl v9 soon, which has been improved a bit for bindings using the new property APIs.

**Comment by philmoz** [comment]
> I have developed a [lua lvgl binding](https://github.com/XuNeo/luavgl). It's not 100% finished yet, but I would love to hear from your input to make it better.
> 
> The binding will be upgraded to lvgl v9 soon, which has been improved a bit for bindings using the new property APIs.

Thanks, it is on my radar to look all - does it support lvgl 8.2?

**Comment by XuNeo** [comment]
I have just pushed a fix to make it compatible with v8.2. Not fully tested but the basic function can work now.

**Comment by 3DRacer** [comment]
My RM TX16S with DE language freezes when trying to display the SD card contents. Key SYS--> Open SD card directory. Only by removing the battery can it be revived. Is this known?

**Comment by philmoz** [comment]
> My RM TX16S with DE language freezes when trying to display the SD card contents. Key SYS--> Open SD card directory. Only by removing the battery can it be revived. Is this known?

Are you using the latest version of this PR?
Does it happen with the current nightly version?
Can you try a different SD card?

**Comment by 3DRacer** [comment]
> > My RM TX16S with DE language freezes when trying to display the SD card contents. Key SYS--> Open SD card directory. Only by removing the battery can it be revived. Is this known?
> 
> Are you using the latest version of this PR? Does it happen with the current nightly version? Can you try a different SD card?

- yes, that is the version from January 4th. Same problem with previous versions of this PR
- I'll test this on the weekend
- I can try that later. My SD is a sandisk16GB, formatted in 4GB with 4KB cluster
In a selfbuild with the last master, the SD is displayed normally. No freezing

**Comment by tonims1** [comment]
In outputs put a positive or negative value in Subtrim, in various channels. moving a stick makes this effect

https://github.com/EdgeTX/edgetx/assets/7953406/eb82920e-6220-4c89-b664-3bcbd48170be

**Comment by philmoz** [comment]
> In outputs put a positive or negative value in Subtrim, in various channels. moving a stick makes this effect

Are you using the latest version of this PR?

**Comment by tonims1** [comment]
Yes. The last one..

**Comment by philmoz** [comment]
> Yes. The last one..

That's strange. I saw this quite a while ago and fixed it  - at least I no longer have the issue on my TX16S (mk2) or EL18.

What is the VERS string in the System -> Version page?
What radio are you using?

**Comment by philmoz** [comment]
@tonims1 Can you please try the latest update to see if the problem is fixed on your radio.

**Comment by philmoz** [comment]
> My RM TX16S with DE language freezes when trying to display the SD card contents. Key SYS--> Open SD card directory. Only by removing the battery can it be revived. Is this known?

@3DRacer This should be fixed in the latest commit to this PR.

**Comment by tonims1** [comment]
> @tonims1Pots provar l'última actualització per veure si el problema s'ha solucionat a la teva ràdio.

Now it works perfectly. I have a RM TX16. Another thing I have noticed is that when you want to change models in manage models it is slower than in the current version, only when there is the image of the model, only text works perfectly

**Comment by philmoz** [comment]
> Now it works perfectly. I have a RM TX16. Another thing I have noticed is that when you want to change models in manage models it is slower than in the current version, only when there is the image of the model, only text works perfectly

I haven't noticed any significant slowdown on my TX16S - if you have time can you create short videos showing the difference.

**Comment by tonims1** [comment]
https://github.com/EdgeTX/edgetx/assets/7953406/8a820799-3d23-448b-aad2-7e787fc322e4
Main 2.10

https://github.com/EdgeTX/edgetx/assets/7953406/7fee8470-bd00-4df9-b95f-692f4ab6180e
PR 4407

**Comment by 3DRacer** [comment]
> > My RM TX16S with DE language freezes when trying to display the SD card contents. Key SYS--> Open SD card directory. Only by removing the battery can it be revived. Is this known?
> 
> @3DRacer This should be fixed in the latest commit to this PR.

no freeze anymore. works fine. thanks

**Comment by tonims1** [comment]
> @tonims1Podeu comprimir les vostres carpetes MODELS i IMATGES i penjar-les aquí, si us plau.

Here you have them. thank you
[7tmp.zip](https://github.com/EdgeTX/edgetx/files/14121910/7tmp.zip)

**Comment by tonims1** [comment]
> > Aquí els teniu. gràcies [7tmp.zip](https://github.com/EdgeTX/edgetx/files/14121910/7tmp.zip)
> 
> Gràcies. L'última versió hauria de ser millor.

thank you. is better . now it works perfectly

**Comment by philmoz** [comment]
> > When editing screen layouts the selected widget has the solid border and the others have a dashed border:
> When you first go in, the first box has both dotted and solid border.

Thanks, may have lost something in one of the rebases. Will look into it.

> In Model Setup, the fields for the model image and name are shorter... the former isn't such an issue, but the latter should be longer so you can see more of the name.

The boxes should resize to fit the name - they do on my TX16S.

> Performance wise, having just come from 2.10-rc2, this actually feels more sluggish. Also, when you are in the channel monitor, you can actually see the channel bars and text rebuilt, whereas 2.10 has no delay/artifacts.

Which radio? 
The channel monitor has no issues on my TX16S, and overall performance does not seem slower to me.
Can you record a video of the channel monitor.
I did timing tests between 2.9 and this PR a while ago but have not done any recently - they were pretty similar across the board.

**Comment by pfeerick** [comment]
TX16S. you'll see on the radio on the left the lag and also the shorter than model name field. 

Video may still be unavailable for a few minutes as was still running through copyright checks... https://youtu.be/gg5X17oLii8

**Comment by pfeerick** [comment]
Much better... it's still a little more sluggish than 2.10 but much better than it was. Did you want to work on this more or merge and keep going? One less PR to rebase ;)

**Comment by philmoz** [comment]
> Much better... it's still a little more sluggish than 2.10 but much better than it was. Did you want to work on this more or merge and keep going? One less PR to rebase ;)

If you're ready to go with big 2.11 changes then I'd like to get this in.

**Comment by pfeerick** [comment]
Your wish is granted. I'm crossing fingers 2.10 won't be needing any major changes by this point in the RC cycle so cherrypicking anything needed for it not too... _painful_?

**Pull request merged**
