### PR TITLE
chores(flysky): separate AFHDS2A and AFHDS3 into 2 different module type

### LINKED ISSUE #836: NV14 Internal Module protocol
@elecpower Just noticed that for the NV14 it's showing AFHDS3 for the internal module protocol instead of AFHDS2A

Also, whilst I beleive the RF output power can be changed, that isn't exposed in the settings atm, but I don't know which side is right as far as the bin file settings (i.e. simply missing from interface, or Companion shouldn't be showing it). 

image

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #836

This should allow to remove some of the hacks added earlier.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@philmoz @richardclli may I outsource separating the `AFHDS2A` / `AFHDS3` options UI to you? I think this is mostly about splitting `flysky_settings.{h,cpp}` into `afhds2a_settings.{h,cpp}` and `afhds3_settings.{h,cpp}`, as this PR introduces 2 separate module types.

@elecpower may I also outsource the Companion changes to you? I believe the focus is probably on the YAML conversion here. The conversion is basically from `type=TYPE_FLYSKY` & `subType=[AFHDS2A | AFHDS3]` to `type=[TYPE_FLYSKY_AFHDS2A | TYPE_FLYSKY_AFHDS3]`.

**Comment by raphaelcoeffic** [comment]
@pfeerick should we add the `el18` target to CI as well? I think we should have `el18` replace `nv14` in the tests, and have final builds for both (second phase).

**Comment by elecpower** [comment]
> @elecpower may I also outsource the Companion changes to you? I believe the focus is probably on the YAML conversion here. The conversion is basically from `type=TYPE_FLYSKY` & `subType=[AFHDS2A | AFHDS3]` to `type=[TYPE_FLYSKY_AFHDS2A | TYPE_FLYSKY_AFHDS3]`.

Accepted. After I finish merging pots and sliders config into pots config with all the necessary conversions for old and new settings which I am about half way thru fixing.

**Comment by pfeerick** [comment]
> @pfeerick should we add the `el18` target to CI as well? I think we should have `el18` replace `nv14` in the tests, and have final builds for both (second phase).

Yup, sounds like a good time to do it... want me to add/swap the bits to build_gh and actions? This probably also makes life a bit easier with Companion as then we can start supporting the AFHDS2A and AFHDS3 specific options, which lines up nicely with my "want" for EL18 to get Companion support this cycle :)

**Comment by pfeerick** [comment]
I think that's all the "generic" bits. I also made a slight change to the order of tests - as I've found the x9dp2019 is the most likely B&W radio to implode if something goes wrong (partly as it probably has the most stuff turned on / hence also the least free space), so moved it to the top so it either passes or fails quicker. TX16S is probably the most representational horizontal LCD, and then the nl14/el18 for portrait LCD... I don't really think we need to do *both* for the tests post this PR, but probably should do until it's finished, since the tests will break the builds quicker?

**Comment by elecpower** [comment]
Companion base work done. Will move on to testing NV14 by comparing with its libsim.
Unable to test EL18 libsim yet as has not been added to Companion that I can find.
There appears to be a need for some Companion clean up of AFHDS3 as it appears to be a hack of an old AFHDS2A. eg  there is a binary import mapping which how it existed back then I do not know. In this case I'd suggest we just drop the import and any legacy fields in moduledata.h.

**Comment by pfeerick** [comment]
There is zero support for EL18 in Companion at present, hence my earlier comment. Working on #3247 is on my 2.10 wish-list :grin:

**Comment by elecpower** [comment]
@pfeerick would you like me to start a PR for #3247 in the next few days/week? I'd put all the building blocks in place and leave it to you to refine/fix.
That would be enough for me to run up the libsim to help test this PR.

**Comment by pfeerick** [comment]
> @pfeerick would you like me to start a PR for #3247 in the next few days/week? 

Yes, that would be great. With a skeleton in place, I can run through it with the actual hardware and make/suggest/beg for any changes.

**Comment by elecpower** [comment]
What no grovel 😉

**Comment by pfeerick** [comment]
> beg

It was implied 🤣

**Comment by elecpower** [comment]
The nv14 libsim crashes in:
- Radio Settings clicking hardware tab
- Model Settings | Setup tab | clicking Int. Module

Does not crash in main branch so will wait for it to be fixed before mirroring the ui in Companion.

**Comment by raphaelcoeffic** [comment]
@elecpower potentially this was caused by `TR_MODULE_PROTOCOLS` missing one element, which should be fixed with [b091c27](https://github.com/EdgeTX/edgetx/pull/3783/commits/b091c2783a28c3df3c17fbd777e117f430ce9487).

**Comment by elecpower** [comment]
> @elecpower potentially this was caused by `TR_MODULE_PROTOCOLS` missing one element, which should be fixed with [b091c27](https://github.com/EdgeTX/edgetx/pull/3783/commits/b091c2783a28c3df3c17fbd777e117f430ce9487).

@raphaelcoeffic that fixed the crash, thanks

**Comment by elecpower** [comment]
Tested with #3807

**Comment by philmoz** [comment]
> @pfeerick would you like me to start a PR for #3247 in the next few days/week? I'd put all the building blocks in place and leave it to you to refine/fix.
> That would be enough for me to run up the libsim to help test this PR.

I started working on the firmware UI changes. NV14 working ok; but I'm a bit stuck without companion support for EL18.

**Comment by richardclli** [comment]
> @philmoz @richardclli may I outsource separating the `AFHDS2A` / `AFHDS3` options UI to you? I think this is mostly about splitting `flysky_settings.{h,cpp}` into `afhds2a_settings.{h,cpp}` and `afhds3_settings.{h,cpp}`, as this PR introduces 2 separate module types.
> 
> @elecpower may I also outsource the Companion changes to you? I believe the focus is probably on the YAML conversion here. The conversion is basically from `type=TYPE_FLYSKY` & `subType=[AFHDS2A | AFHDS3]` to `type=[TYPE_FLYSKY_AFHDS2A | TYPE_FLYSKY_AFHDS3]`.

Let me take a look first, work on the same branch with you?

**Comment by philmoz** [comment]
PR #3861 separates the UI settings pages for AFHDS2A and AFHDS3.

**Comment by elecpower** [comment]
PR #3807 has this PR as its base for the EL18 simulator. So Companion side is done except for fix ups that @pfeerick was going to check when he had a spare minute lol

**Comment by philmoz** [comment]
> PR #3807 has this PR as its base for the EL18 simulator. So Companion side is done except for fix ups that @pfeerick was going to check when he had a spare minute lol

Hmm, I can't see EL18 as a radio type in Companion for setting up to run the simulator.

**Comment by elecpower** [comment]
> Hmm, I can't see EL18 as a radio type in Companion for setting up to run the simulator.
> 
> Ok, so I need 3807 as well?

Yes you do @philmoz

**Comment by philmoz** [comment]
Does #3807 supersede this PR?

It appears to have all the changes from this PR plus some others.

Tried merging them; but I get conflicts.

**Comment by pfeerick** [comment]
No, it includes all the commits up to `[fix: TR_MODULE_PROTOCOLS](https://github.com/EdgeTX/edgetx/pull/3783/commits/491c4e172f0d1bb35ebc7274eb81a45ab6817001)`, diverges slightly, and then both branches have the subsequent four commits. I'll see if I can deconflict them, and then redirect the companion PR into this branch, since it seems to be the one that will end up pulling all the changes together.

**Comment by philmoz** [comment]
I was able to merge my UI changes to the latest version of #3807 so companion and simulator work for EL18.

One issue is when I flashed all this to the EL18 radio the internal module type got changed to AFHDS2A instead of AFHDS3 (the model was bound to a TR8B receiver). It might need some conversion logic to change the old type/subtype to the new types.

**Comment by philmoz** [comment]
PR #3867 fixes the AFHDS3 conversion issue when loading old model settings.
Also fixes a layout issue with the 'Channel Range' controls on portrait LCD.

**Comment by raphaelcoeffic** [comment]
@pfeerick I just rebased. Anything more needed apart from "more tests"?

**Comment by philmoz** [comment]
> Let me know your thoughts on this one

It seems ok to me. I've used this when building for EL18 and the radio binds and works with the AFHDS3 receiver.

Can't test the NV14 / AFHDS2A side though.

**Comment by pfeerick** [comment]
Thanks. I'll try the NV14 side out then, and just give the EL18 a look over.

**Comment by pfeerick** [comment]
NV14 seems to be working both prior to and post this PR with no major issues - receiver still working fine, settings read and wrote fine on radio, and settings also survived Companion sync unscathed. I was going to try the FRM303 with TX16S but it wouldn't cooperate on 2.9.0 (or this PR) so I need to see why the mod to support the module isn't working.

**Pull request merged**
