### PR TITLE
Allow CPP Widgets Override with LUA

### PR DESCRIPTION
**Pull request by DavBfr**
Allows #221 

Summary of changes:

Iterate the Widgets factory backward to give priority to the Lua widgets over the internal C++  Widgets.
This allows reimplementing the internal widgets with Lua without any sacrifice or `defines`.

### CODE REVIEW

**Comment by pfeerick** [comment]
Unfortunately, this doesn't seem to work properly/consistently. 

i.e. do a simple test - rename Timer2 to Timer, and update it's `return` so that it returns the name `Timer`. Start the radio up, and choose the first 'Timer' entry (since there are now two). It will use the build-in Timer. Then, if you restart the radio, it will *attempt* to use the lua one, but will error out. 

This probably needs to be done differently so that the actual source of the widget is determined (lua, builtin), and then if a LUA one is present the built-in one is dropped.

**Comment by DavBfr** [comment]
This was my first attempt but with more code change. It should work correctly.
The options have to be somehow compatible if you override a widget.

**Comment by pfeerick** [comment]
Ah true. The problem therein (with compatible options) though is if a Lua widget replaces a built-in one, then it won't necessarily have the same options - potentially it will have more/different ones since the goal is for it to improve on the built-in one. Otherwise, that somewhat defeats the purpose, doesn't it? I'll see how badly I can break it this time (in the morning) :)

**Comment by DavBfr** [comment]
The number or type of options changes should not make it crash as it's fixed to 5 options. If you have any issues, I can try to reset an option to its default value if the type has changed.

**Review by pfeerick — APPROVED** [review]
Ok, that wasn't quite "next morning" ... 😆 

Yes, this seems to be working properly now... built-in widget is dropped from use, double menu entries are gone, and Lua widget is consistently being used when a name collision detected, allowing for the override. There is one edge case I've found, where if you are naughty and rename a widget when in USB Storage mode, but you really shouldn't be doing that... really should be in bootloader mode when editing anything that isn't user files, reading logs, etc.

**Pull request merged**
