### PR TITLE
fix: Style/color tweaks

### PR DESCRIPTION
**Pull request by pfeerick**
**Summary of changes:**
- text color for active LS buttons in monitor, which also affected some keyboard icons (for the better IMO)
- text color for active flight mode button
- text color for active internal/external/trainer button
- width/layout of channel monitors bars for portrait screens
- minor tweaks to alignment of channel monitor bar in relation to text, and icon layout

Before and afters
image
image

But I can't see what controls these buttons yet:
image
image

### CODE REVIEW

**Comment by pfeerick** [comment]
@gagarinlg Any idea what needs poking to control the text color of the buttons in the bottom two images?

**Comment by pfeerick** [comment]
Channel bar and channel monitor tweaks now look like this:
snapshot_11
snapshot_12

snapshot_22
snapshot_23

**Comment by Eldenroot** [comment]
Looks nice! Good job!

**Comment by JimB40** [comment]
Whitespace between channel text & bars in monitor!

**Comment by gagarinlg** [comment]
> @gagarinlg Any idea what needs poking to control the text color of the buttons in the bottom two images in the first post?

They probably have the default text color. Some form of lv_obj_set_style_...

**Comment by pfeerick** [comment]
> Whitespace between channel text & bars in monitor!

Maybe, if there is space. I've not touched that at all.

**Comment by pfeerick** [comment]
Right, 2px is all you're getting :-P

snapshot_25
snapshot_26
snapshot_13
snapshot_14

**Comment by pfeerick** [comment]
Few more brain cells must have been working... find it this time :) "Active" button text for those two-state buttons is now PRIMARY1 rather than PRIMARY2, so the contrast is kept. Hm... why is FM text left aligned... 

snapshot_01
snapshot_02

**Pull request merged**
