### PR TITLE
Added flysky build script and solved some build problems but got stuck in LUA, resolves #6.

### LINKED ISSUE #6: No script for NV14 building
There is no script for NV14 building.  I will see if I can add one.  Please help to verify if I made any mistakes.  Thanks.

### PR DESCRIPTION
**Pull request by richardclli**

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@richardclli please let me know if you any help with LUA. Just drop-by at our discord server to discuss what you need.

**Comment by richardclli** [comment]
I have got pass the LUA, now fixing others.  Will notify you if need any more help.

**Comment by rotorman** [comment]
We have a following user report via Discord/Tests on this PR on NV14:
https://www.youtube.com/watch?v=mFsoK43soO8
@richardclli Would you have any tips?

**Comment by tientrung113** [comment]
https://youtu.be/mFsoK43soO8
Can you help me to solve this problem?\
sorry if the youtube link here is wrong

**Comment by richardclli** [comment]
Well, I just managed to make it compile successfully.  However, the code base in v2.4 seems never works properly.  I guess is that the codebase of NV14 is originated from OpenTX 2.1 and many changes in OpenTX just breaks the NV 14 code.  Need to fix bit by bit.  BTW, I am not sure if anybody can help on this.  This transmitter is very good looking and will be cool if EdgeTX 2.4 works on it.

**Comment by richardclli** [comment]
Here is latest code base of working NV14 firmware.

**Comment by raphaelcoeffic** [comment]
@richardclli are the issue on the UI side or hardware / drivers? For the drivers, most of it is a copy of what you can find in the `horus` targets. If this is the UI, well, it's more or less expected, and some work is needed, but this time it common code between all the color lcd radios, which makes it more maintainable.

**Comment by tientrung113** [comment]
i have x12s but it's too heavy to have this fly14.  can you share me the file containing your running firmware?

**Comment by tientrung113** [comment]
> Here is latest code base of working NV14 firmware. https://github.com/open-flysky/Flysky-OpenTX-Test-Branch

i have x12s but it's too heavy to have this fly14.  can you share me the file containing your running firmware?

**Comment by richardclli** [comment]
You can download latest official working firmware in here: https://www.flysky-cn.com/nv14xiazaien

**Comment by richardclli** [comment]
Well, I think both.  However, nv14 is not using horus target, it is its own nv14 target, so I think we need to walkthrough and compare the working version to horus and modify nv14 target so that it fits to new modifications.  In order to make it to compile successfully, I tried to change what blocks the compilation and marked the code with TODO for those I am not quite sure.

And I would like to generalize the support of the gimbal driver of NV14, since tthis nice designed gimbal has a full aluminum version and can be put in TX16S/T16/T18 to greatly improves the feeling and precision. ^.^ I will sharemore about this gimbal later on if you are all interested.
> 
> 
> @richardclli are the issue on the UI side or hardware / drivers? For the drivers, most of it is a copy of what you can find in the `horus` targets. If this is the UI, well, it's more or less expected, and some work is needed, but this time it common code between all the color lcd radios, which makes it more maintainable.

**Comment by richardclli** [comment]
Will use another branch to work out the build, please check the nv14-build branch, do not merge this pull request.

**Pull request closed without merging**
