### PR TITLE
chore: Translate some more radio firmware elements

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
- timer mode choices translated using already existing translation elements
- `STR_TIMER_MODES` was being declared multiple times, just do it once
- "Show mixer monitors" toggle at the bottom of mixes page translatable

### CODE REVIEW

**Comment by Eldenroot** [comment]
In my opinion - add a standalone string for Throttle start

For the tr_show_mixers_monitor - in Czech it should be:

"Zobrazit monitor mixů"

**Comment by ParkerEde** [comment]
DE
TR_SHOW_MIXER_MONITORS "zeige Mischermonitor"
TR_TIMER_MODES "Timer Modes"

**Comment by robustini** [comment]
Forgotten the throttle start in Italian?

#define TH_THROTTLE_START "Partenza acceleratore"

**Comment by robustini** [comment]
@pfeerick sorry, I misinterpreted.
Here are the changes:

#define TR_OFFON               "Attivato","Disattivato"
#define TR_START               "Partenza"
#define TR_THROTTLE_PERCENT_LABEL     "% Motore"

**Comment by pfeerick** [comment]
The `TH_THROTTLE_START` mistake was because the monkey behind the keyboard was getting bored by that point 🤣 O think the OFF/ON as Disattivato/Attivato should be fine... it should now use OFF/ON if on a small screen, and switch to Disattivato/Attivato on larger screens.

**Comment by ParkerEde** [comment]
DE
#define TH_THROTTLE_START "Gas Start"
#define TR_OFFON "AUS","EIN"    //is already translated in de.h
#define TR_START "Start"   //is already translated in de.h
#define TR_THROTTLE_PERCENT_LABEL "Gas %"

**Comment by robustini** [comment]
"OFF/ON if on a small screen, and switch to Disattivato/Attivato on larger screens" is the best choice.

**Comment by robustini** [comment]
@pfeerick I think something has gone wrong.
I see "Partenza" and "Partenza motore", I don't understand the difference.
Also I see two "Motore", it is double.

**Comment by ulfhedlund** [comment]
SE: TR_THROTTLE_START = "Gas start"

**Comment by ulfhedlund** [comment]
When trying latest local build (SE language) on Xlite and toggling through the different timer modes the simulator crashes with a segmentation fault when I reach the "top": On, Off, THs, TH%, THt and then... crash!
Should I create a separate issue?

**Comment by pfeerick** [comment]
@robustini For the double Motore, you are experiencing https://github.com/EdgeTX/edgetx/issues/2606 ;) 

I'll have to work in English, so hopefully, you can make sense of this

So this is the timer modes menu
image

 OFF and ON are simple, timer is off, or timer is on. Start is a like on, but once it is on, it stays on. i.e. so if you have the timer on a swtich or a condition (i.e. telemetry is present?), the first time that becomes active, the timer starts running, and will not stop. Then you have Throttle, which means the time is running any time the throttle is active. Throttle %, which means the timer speed is proportional to throttle position (i.e. 50% throttle, timer runs at half speed, 75% throttle, 75% speed, etc). And Throttle start will start the timer when throttle moves the first time, and the timer will just keep going. 

@ulfhedlund Not yet, need to see if it is something specific to this PR first.

**Comment by robustini** [comment]
> @robustini For the double Motore, you are experiencing #2606 ;)
> 
> I'll have to work in English, so hopefully, you can make sense of this
> 
> So this is the timer modes menu image
> 
> OFF and ON are simple, timer is off, or timer is on. Start is like on, but once it is on, it stays on (it latches on). i.e. so if you have the timer on a swtich or a condition (i.e. telemetry is present?), the first time that becomes active, the timer starts running, and will not stop. Then you have Throttle, which means the time is running any time the throttle is active. Throttle %, which means the timer speed is proportional to throttle position (i.e. 50% throttle, timer runs at half speed, 75% throttle, 75% speed, etc). And Throttle Start will start the timer when throttle moves the first time, and the timer will just keep going (like Start, it latches on).
> 
> @ulfhedlund Not yet, need to see if it is something specific to this PR first.

In the code that I have compiled there is in fact "%", why can't I see it in the menu?

immagine

**Comment by pfeerick** [comment]
> For the double Motore, you are experiencing #2606 ;)

No, it is simply *not* showing the character, as pointed out in #2606 ;)

**Comment by zyren** [comment]
CN
-------------------------------------------------------
#define TH_THROTTLE_START           "油门开启"
#define TR_OFFON                    "开启","关闭" 
#define TR_START                    "开始" 
#define TR_THROTTLE_PERCENT_LABEL   "油门比例 %"
#define TR_THROTTLE_LABEL           "油门启停" 
#define TR_SHOW_MIXER_MONITORS      "查看通道混控"
-------------------------------------------------------

TW
-------------------------------------------------------
#define TH_THROTTLE_START           "開始"
#define TR_OFFON                    "開啟","關閉" 
#define TR_START                    "開始" 
#define TR_THROTTLE_PERCENT_LABEL   "油門比例 %"
#define TR_THROTTLE_LABEL           "油門啟停" 
#define TR_SHOW_MIXER_MONITORS      "查看通道混控"
-------------------------------------------------------

**Comment by robustini** [comment]
> > For the double Motore, you are experiencing #2606 ;)
> 
> No, it is simply _not_ showing the character, as pointed out in #2606 ;)

I see, so at the moment is better this:

#define TR_THROTTLE_PERCENT_LABEL "Motore percentuale"

**Comment by pfeerick** [comment]
> I see, so at the moment is better this:
> 
> #define TR_THROTTLE_PERCENT_LABEL "Motore percentuale"

Well, right now, yes... but I'd rather fix the underlying bug so this doesn't need to be changed for all languages ;)

**Pull request merged**
