### PR TITLE
Internal CRSF

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
## Summary of changes:
- ported TBS code to support CRSF telemetry on internal and external module (see opentx/opentx#8665)
- revamp telemetry polling
- CRSF now uses task notifications to process telemetry with lower latency (and thus should not require bigger buffers) 
- added serial pass-through (460.8kbps does work, not much more).

## Serial passthrough

This features requires `CLI` enabled (by default in this PR on TX16S).

Once connected to `CLI` via USB (choose `USB Serial (debug)` in the menu):
```
serialpassthrough rfmod 0 460800
```

## Other commands

It is also possible to set the value of the `power` and `bootpin` state (thx to @pkendall64):
```
set rfmod 0 power [on/off]
set rfmod 0 bootpin [on/off/0/1]
```

And last but not least, `start` or `stop` the pulses:
```
set pulses [0/1]
```

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
TODOs:
- [ ] enable setting module power supply.
- [ ] fix auto-baud on `serialpassthrough` setup (optional baudrate parameter).

**Comment by pkendall64** [comment]
After talking on discord we thought the commands could be
```
set rfmod 0 power [on/off]
set rfmod 0 bootpin [on/off/0/1]
```
for consistency

**Comment by CapnBry** [comment]
Tested on 5.25M and working full duplex, baby. And thanks to pkendall64's updates in the dupletx passthrough flashing worked without pressing any buttons or anything. Amazing work!

**Comment by pfeerick** [comment]
Baseline test before merge:

RM TX12 (B&W target):
- [ ] MPM status ok & selectable
- [ ] MPM able to update
- [ ] MPM bind
- [ ] MPM telemetry
- [ ] CRSF/ELRS selectable
- [ ] CRSF/ELRSable to update
- [ ] CRSF/ELRS bind (lua)
- [ ] CRSF/ELRS telemetry

RM TX16S (colourlcd target):
- [ ] MPM status ok & selectable
- [ ] MPM able to update
- [ ] MPM bind
- [ ] MPM telemetry
- [ ] CRSF/ELRS selectable
- [ ] CRSF/ELRSable to update
- [ ] CRSF/ELRS bind (lua)
- [ ] CRSF/ELRS telemetry

**Review by pfeerick — APPROVED** [review]
Looks good so far, nothing seems broken, so over to the nighty crew ;) I've not looked at the CLI, but I see there is the USB serial debug option present for the TX16S when plugged in.

**Comment by raphaelcoeffic** [comment]
> Looks good so far, nothing seems broken, so over to the nighty crew ;) I've not looked at the CLI, but I see there is the USB serial debug option present for the TX16S when plugged in.

Yep, we might rename it to something more meaningful as well. Just not sure what to use.

**Comment by wimalopaan** [comment]
Maybe this is responsible for compilation error on T12?

```
/home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp: In function 'void intmoduleSendNextFrame()':
/home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp:746:47: error: 'union InternalModulePulsesData' has no member named 'crossfire'
746 |       intmoduleSendBuffer(intmodulePulsesData.crossfire.pulses,
|                                               ^~~~~~~~~
/home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp:747:47: error: 'union InternalModulePulsesData' has no member named 'crossfire'
747 |                           intmodulePulsesData.crossfire.length);
|                                               ^~~~~~~~~
make[3]: *** [radio/src/CMakeFiles/firmware.dir/build.make:2470: radio/src/CMakeFiles/firmware.dir/pulses/pulses.cpp.o] Fehler 1
```
...
cmake -DUSB_SERIAL=OFF -DHELI=OFF -DTRANSLATIONS=DE -DPCB=X7 -DPCBREV=T12 -DINTERNAL_MODULE_MULTI=OFF -DLUA=YES -DGVARS=YES -DGHOST=OFF -DAFHDS3=OFF -
DCROSSFIRE=OFF -DOVERRIDE_CHANNEL_FUNCTION=OFF ..
...

**Comment by raphaelcoeffic** [comment]
> Maybe this is responsible for compilation error on T12?
> 
> ```
> /home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp: In function 'void intmoduleSendNextFrame()':
> /home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp:746:47: error: 'union InternalModulePulsesData' has no member named 'crossfire'
> 746 |       intmoduleSendBuffer(intmodulePulsesData.crossfire.pulses,
> |                                               ^~~~~~~~~
> /home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp:747:47: error: 'union InternalModulePulsesData' has no member named 'crossfire'
> 747 |                           intmodulePulsesData.crossfire.length);
> |                                               ^~~~~~~~~
> make[3]: *** [radio/src/CMakeFiles/firmware.dir/build.make:2470: radio/src/CMakeFiles/firmware.dir/pulses/pulses.cpp.o] Fehler 1
> ```
> 
> ... cmake -DUSB_SERIAL=OFF -DHELI=OFF -DTRANSLATIONS=DE -DPCB=X7 -DPCBREV=T12 -DINTERNAL_MODULE_MULTI=OFF -DLUA=YES -DGVARS=YES -DGHOST=OFF -DAFHDS3=OFF - DCROSSFIRE=OFF -DOVERRIDE_CHANNEL_FUNCTION=OFF .. ...

But do you disable all protocols and modules? 😅

**Comment by wimalopaan** [comment]
Because I don't need them.

Yesterday or the day before that still worked ...

**Comment by wimalopaan** [comment]
Turnung `-DINTERNAL_MODULE_MULTI=ON` does NOT fix that (because T12 has no internal module).
Only `-DCROSSFIRE=ON` fixes. 
Well, if I have the option to turn crsf off, because I don't need that, it should compile fine.

**Pull request merged**
