### PR TITLE
fix(yaml): flex switch warnings

### LINKED ISSUE #4938: Issue with flex switches and switch warning
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There is an issue with YAML saving of customs switches. The warnings are using only 1 leter to save instead of the usual format.
SA.SB,.. are saved as A,B,...
FL, FL2,.. are saved as .... L (all of them)

So when read, only FL1 gets populated, with the value of the last FL been encoded in warnings

### Expected Behavior

Flex are saved in an error free format

### Steps To Reproduce

Create flex switches, assign several to switch warning. Turn off, turn on. oh noooo

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster MT12

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
TODO:
- [x] Companion support

Fixes #4938

### CODE REVIEW

**Comment by 3djc** [comment]
@elecpower could you have a look at the companion part ?
Basicaly

Old format: 
switchWarningState: AuBuEuFuG-IuJu

New format:
switchWarning: 
   SA:
      pos: up
   FL1:
      pos: mid
   FL2:
      pos: down

**Comment by 3djc** [comment]
A terrible thought crossed my mind. Are flex switches supported at all in Companion ?

omg, checked with a TX16S and it looks flex switches aren't managed at all in companion !!!

**Comment by elecpower** [comment]
> @elecpower could you have a look at the companion part ?
> Basicaly
> 
> Old format: 
> switchWarningState: AuBuEuFuG-IuJu
> 
> New format:
> Capture d’écran 2024-05-01 à 11 09 42
> 

Got it

**Comment by elecpower** [comment]
Tested using TX16S libsim in Ubuntu 20.04 and found the sim freezes when Simulate Radio a second time and always when Simulate Model.
Similar occurs on main. I managed to run multiple Simulate Radio without freezing. Simulate Model froze 1st run and then Simulate Radio froze.
The official release Win 10 running 2.10 RC3 does not freeze in either mode.
I need to work on #4950 so I'll leave this for now.

**Comment by 3djc** [comment]
Tested on 'real' radio, works perfectly, also added another SF using FL, wrote to radio, all successfull !!! Thanks @elecpower

**Comment by elecpower** [comment]
The libsims are prone to misbehave if memory is not initialised especially since the radio code is run in a wrapper. Had problems in the past where simpgmspace doesn't mirror radio.

**Comment by pfeerick** [comment]
> Tested on 'real' radio

Can you mention *which* one next time please? :laughing:

**Review by pfeerick — APPROVED** [review]
LGTM on MT12 and TX16S. 

Already configured switch warnings worked properly on both, and two newly added FLEX switch warnings on MT12 were functional and displayed better. TX16S appeared to work - I don't have extra switches populated on my test subject, but the warning appeared to be working and was correct read and written back by Companion, and did work in the simulator.

**Comment by pfeerick** [comment]
> Tested using TX16S libsim in Ubuntu 20.04 and found the sim freezes when Simulate Radio a second time and always when Simulate Model. Similar occurs on main. I managed to run multiple Simulate Radio without freezing. Simulate Model froze 1st run and then Simulate Radio froze.

I had this happen on and off since maybe 2.8, so had gotten used to always saving ETX before using Simulator as it would segfault Companion on closing... you weren't able to repo at the time so we calked it up to me using a newer Ubuntu distro. Interestingly, I'm running Linux Mint now, and Simulator seems to be working perfectly with both the build from this PR and also 2.10-rc3... no segfaults or anything after multiple open/closes of Simulator so that is another +1 for Mint :laughing:

**Pull request merged**
