### PR TITLE
Fix MPM XK shows invalid protocol

### LINKED ISSUE #3264: MPM select XK shows Protocol Invalid - 2.8.1
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Since upgrading to 2.8.1 I am unable to bind to Xk X450 model using the correct MPM setting, I get the error message, Protocol Invalid on the protocol selection page.
Reverting back to 2.8.0 sees the issue resolved and the model binds fine again.      

MPM is running the same v1.3.3.20 firmware

### Expected Behavior

Would expect it to work as it does in 2.8.0

### Steps To Reproduce

Running 2.8.1
1 - select internal module protocol XK
2 - select sub protocol X450
3 - Unable to bind and get Protocol Invalid message

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #3264

Summary of changes:

### CODE REVIEW

**Comment by richardclli** [comment]
Fixed a typo, but not seems to help.

**Comment by pfeerick** [comment]
Strange thing is it affects the B&W radios, and on the 2.8 branch, is specific to 2.8.1, so must have been something I missed between the 2.8.0 and 2.8.1 changes... i.e. I there think it stems from the changes in
9ac21dbecc1d9f0ef8bfbe213ba9aeddee21c5d3
8c44b002e75ad8a74fd9e93d00364ecc14e50063

or in 2.9 that would be 
https://github.com/EdgeTX/edgetx/pull/3032
https://github.com/EdgeTX/edgetx/pull/3112

**Comment by richardclli** [comment]
I traced in MPM and figured out that EdgeTX send out an invalid protocol index to MPM and MPM reply with invalid protocol.
XK protocol is no. 62, but a no. 126 is sent.

It is interesting when you convert these 2 numbers in binary:
62 = 00111110
126 = 01111110

Why there is a strange bit change?

**Comment by pfeerick** [comment]
What's even weirder is after some random sampling of protocols, it seems to just be that one in particular. 🤪

**Comment by richardclli** [comment]
multi.cpp show something abnormal:

  uint8_t headerByte = 0x55;
  // header, byte 0,  0x55 for proto 0-31, 0x54 for proto 32-63
  if (type & 0x20)
    headerByte &= 0xFE;

  if (failsafe)
    headerByte |= 0x02;

  sendMulti(p_buf, headerByte);

Every 32 protocols need the change of header, but seems the code not handling type > 63.  Umm.... now we have 9x protocols, looks this will cause problems.

**Comment by richardclli** [comment]
I am thinking if this problem is related as well.  https://github.com/EdgeTX/edgetx/issues/2713

**Comment by richardclli** [comment]
Need to take some time to verify both the edgetx and mpm source code.

**Comment by pfeerick** [comment]
Probably not - if memory serves right #2713 is because options flags are changed on the fly compared to what was sent on startup, and the code is not checking for those changes.

**Comment by richardclli** [comment]
@pfeerick I finally nailed down the problem.  The index shifts so that bits 6,7 are calculated wrongly because of Frsky's mess and Raphael missed that point.  Please review and test it.

**Comment by richardclli** [comment]
My test is good in TX16S.

**Comment by pfeerick** [comment]
Yup, looks good here too on Zorro and TX16S, and even better, XK 420 is working with my K989 again ;)

**Comment by cpwilson** [comment]
Tested on my TX16s and the XK X450 and working fine for me now - nice work all :)

**Pull request merged**
