### PR TITLE
Companion B&W radios clean up sd card MODELS folder before writing updated models to sd card

### LINKED ISSUE #1696: On B&W radios, deleting models in companion doesn't actually work
Due to how models are handled differently on B&W radios, the actual model.yml files need to be deleted in order for them to be removed from the list on the radio... which companion currently isn't doing. 

So either we need to:

1) use a models.yml on B&W radios, so companion can alter just the index file like with colorlcd
2) actually delete the model files on B&W radios

I think option 2 is reasonable, as well as for companion to delete model files no longer in use on colorlcd... given the warnings that writing to the transmitter is "destructive / overwrites settings"...

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #1696

Summary of changes:
On B&W radios, before writing models to MODELS folder on sd card:
- delete all modelsxx.yml files
- delete models.yml file if it exists

A bit of translation housekeeping

### CODE REVIEW

**Comment by pfeerick** [comment]
Fantastic... Exactly what I was hoping for. Thanks Neil! :)

**Comment by pfeerick** [comment]
Should we add this to 2.7.1, or leave for 2.8?

**Comment by elecpower** [comment]
Whist it fixes a bug it is not critical. I feel some more nightly user testing might be wise since it is destructive. 2.8 is not that far away.

**Comment by pfeerick** [comment]
Sounds good... 2.8 it is ;)

**Comment by hclivess** [comment]
Fixed my issues with being unable to download models into computer. Thanks!

**Pull request merged**
