### PR TITLE
feat: customisable switches generated sources

### LINKED ISSUE #4989: Improve customisable switches with automatic "source "
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently, customisable switches are only switches, and if you want say have it work like a 6POS, it does create a lot of work

### Describe the solution you'd like

Creation of 3 sources (GR1 to GR3) that match the customisable switches groups
Those source will be managed by the system without user intervention.
They will range from -100 to 100 with as many steps as there are switches in the group. If 0 switches in group, then source value is set to 0

If you have model default, all customisable switches are in group 1 and "always on' not enable, you will have
GR1: -100 to 100 in 7 steps
GR2: always 0
GR3: always 0

If you have model default, all customisable switches are in group 1 and "always on' enabled, you will have
GR1: -100 to 100 in 6 steps
GR2: always 0
GR3: always 0

If you have 4 switches in group1 and 2 in group 2 and both groups "always on" disabled:
GR1: -100 to 100 in 5 steps (all off = -100, sw1 = -50, sw2 = 0 , sw3 = 50, sw4 = 100)
GR2 : -100 to 100 in 3 steps (both off = -100, sw5 = 0, sw6 = 100) 
GR3: always 0

If you have 4 switches in group1 and 2 in group 2 and group 1 "always on" enabled:
GR1: -100 to 100 in 4 steps (sw1 = -100, sw2 = -33 , sw3 = 33, sw4 = 100)
GR2 : -100 to 100 in 3 steps (both off = -100, sw5 = 0, sw6 = 100) 
GR3: always 0
### Describe alternatives you've considered

Use SF like today

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 3djc**
This add 3 sources (GR1 to GR3) on radio that  have customisable switches as described in https://github.com/EdgeTX/edgetx/issues/4989

This PR is best when used in conjunction with #4994 (which prevents user misconfiguration)

This fixes #4989 

@elecpower: I've done my  best for companion support, but please check thoroughly.

### CODE REVIEW

**Comment by elecpower** [comment]
@3djc IMO this needs to be based on #4722.
@philmoz and I have already spent time keeping 4722 rebased (the sooner it is merged or closed the better).
I'll have a look at what you have done so far and provide feedback but not approve until priorities are resolved by someone on a higher pay grade.

**Comment by pfeerick** [comment]
Sounds good to me... had been ignoring it somewhat since it was still tagged as 'draft'. So looks like it will be #4722, #4994 and then #5016?

**Comment by elecpower** [comment]
Tested Companion and T20 libsim.
1. create new model in Companion - pass
2. configure custom switches across 2 groups - pass
3. add inputs, mixes, logical switches and special functions referencing the 3 groups and sources either side in the lists - pass
4. save, close and reopen the models and settings - pass
5. check encode and decode - pass
6. launch simulator - pass
7. check decode - pass
8. make a small change to force the yaml to be written - pass
9. copy and zip the files into an etx file - pass
10. close the simulator - pass
11. close the models and settings - pass
12. open the simulator generated models and settings - pass
13. check the encode and decode - pass

For consistency with other sources and switches and to keep lists short, groups should only be available for selection in lists when they are configured.

The groups should optionally allow them to have user defined names assigned like all other sources and switches, and for the same reasons they have user defined names. I can imagine this would be the first enhancement request after the feature becomes available so why not do it as part of this implementation to save rework.

**Comment by elecpower** [comment]
> Sounds good to me... had been ignoring it somewhat since it was still tagged as 'draft'. So looks like it will be #4722, #4994 and then #5016 (in order of age)?

Re Draft, I do not see any changes except for rebases from @philmoz so best to check with him him being ready for Review.

**Comment by elecpower** [comment]
@3djc 4722 WILL break this due to the index change from zero to one based

**Comment by 3djc** [comment]
I'll review this when 4722 gets merged, but I agree, we need to changes merged sooner rather than later

**Comment by 3djc** [comment]
Ready for test

**Comment by elecpower** [comment]
Still needs to have unused/not configured GRx suppressed to be consistent with other types

**Comment by 3djc** [comment]
> Still needs to have unused/not configured GRx suppressed to be consistent with other types

Radio side is done, where should I look in companion code ?

**Comment by elecpower** [comment]
RawSource::isAvailable to show/hide in lists.
Ensure group config changes trigger the lists to be refreshed.

**Comment by 3djc** [comment]
Will add companion side show/not show once 4994 has  been merged, as some functions I need are in there

**Comment by elecpower** [comment]
IMHO it does not get merged until it is a completed feature as this is how the two get out of sync.

**Comment by 3djc** [comment]
@elecpower , could you please take care of : Ensure group config changes trigger the lists to be refreshed.

**Comment by 3djc** [comment]
Thanks @elecpower , seems to work ok :)

**Comment by pfeerick** [comment]
This is working better than I could have hoped when the customisable switches were first introduced, and the need for a traditional 6POS needed.

Just one _tiny_ detail... GR2 and GR3 don't actually appear to giving any output here? GR1 works, but GR2 and GR3 *don't* :cry: 

[pr5016.yml.zip](https://github.com/user-attachments/files/15688588/pr5016.yml.zip)

Just a thought... can we get something for the GRx in the popup source lists also? Not an issue either way, as logical switches aren't there either, so maybe this is can be considered a switch also?

**Comment by 3djc** [comment]
I believe I have fixed the computation issue (thanks to the just in time T15 merged that allowed me to work with debug (yeah !!)), but please test it thoroughly.

Not sure I understand your other point, maybe ping me on discord ?

**Comment by pfeerick** [comment]
I think that is probably topic for a followup PR... I was referring to this popup menu...

image

Would be nice to have shortcuts to the customisable switch groups and/or LS... but it also needs to not show trainer when trainer is not actually configured. 

And I thought you'd like being able to rebase to include the T15 ;)

**Review by pfeerick — APPROVED** [review]
LGTM on T-Pro and T15 :)

**Pull request merged**
