### PR TITLE
Updates to Lua scripts

### PR DESCRIPTION
**Pull request by jfrickmann**
Attempting to guess a fix for #773

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@JimB40 we need you to test this :-)

**Comment by jfrickmann** [comment]
Now that issue #773 seems to be fixed, I am going to continue here with the promised rework of the Lua error messages, so please wait before merging!

**Comment by jfrickmann** [comment]
Okie, this one is ready to be pulled in. I got rid of the popups for error messages. Instead, the Lua task will draw the error message in lieu of running the Lua script until the user stops it by long pressing exit as usual. This simplified some things, and avoids potential deadlocks with the color GUI. I have also given the messages a shine up.

**Comment by pfeerick** [comment]
This generally looks ok to me, and is a significant improvement in error message display  - on both B&W and colourlcd. 

i.e. This unhelpful message ...
image

... became ...
image

On TX16 type display, error display is better also:
snapshot_01

On NV14 not so good:
snapshot_04

So can we bump down the size of the font generally, or at least on the screens where height > width?

**Comment by JimB40** [comment]
make it full screen on BW 128x64. With longer path most valuable info - error line number is hidden.
As I can see now too.

**Comment by jfrickmann** [comment]
Okie I have reduced the font size for color if the screen is taller than white. 
For BW radios, I am using some drawing routines that are also used for popups, so I would rather not make them full size, as that would also affect other stuff.

**Comment by pfeerick** [comment]
I'll double-check how it looks on the NV14, and hopefully merge soon or tonight. re: B&W radios, the other limitation will be number of characters reserved for the error message - 64 characters. To avoid hitting memory limits on B&W transmitters I presume (so we don't have errors in showing the error message? 😁)?

**Comment by JimB40** [comment]
Yep error handling on BW is pain in the ass. All i see sometimes is /SCRIPTS/TOOLS/TELEMERY/MYSCRI...
Maybe log someday.
Using xpcall for a long time but for newbies would be plus.

**Review by pfeerick — APPROVED** [review]
Because I'm fussy 😛. This looks fine on NV14 now... (I get the error going out of the box... word wrap needs a space or hyphen in order to be able to wrap the line, and there is none)... 

snapshot_05

**Comment by jfrickmann** [comment]
OK, I have added opening brackets as possible line breakers, and shrunk the font one size on tall screens.

**Pull request merged**
