### PR TITLE
Fixes DFU-Util "Unexpected argument" error

### PR DESCRIPTION
**Pull request by rotorman**
Tested under Ubuntu 20.04.1 with dfu-util v0.11

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
LGTM on Ubuntu and Windows, and is probably one that would be a good PR to do over on OTX as well as it fixes this edge-case issue that has bugged some people.

Can I just confirm that you encountered this because you self-built dfu-util rather than use the distro repos copy, and then linked `/usr/local/bin/dfu-util` to `/usr/bin/dfu-util`? As this was the scenario in which I could reproduce the issue this fixes. Whereas with the OS repo provided copy of dfu-util, which installed to `/usr/bin`, I had no issue.

Regardless, merge as you see fit.

**Comment by rotorman** [comment]
> Can I just confirm that you encountered this because you self-built dfu-util rather than use the distro repos copy, and then linked `/usr/local/bin/dfu-util` to `/usr/bin/dfu-util`? As this was the scenario in which I could reproduce the issue this fixes. Whereas with the OS repo provided copy of dfu-util, which installed to `/usr/bin`, I had no issue.

Exactly this. With Ubuntu's own dfu-util v0.9 (installed with `sudo apt-get install dfu-util`), I saw no issue, but with own built dfu-util 0.10 and 0.11 that I integrated as below, the issue of unexpected argument was there (here showing dfu-util v0.11 as an example):
```
sudo apt-get -y install build-essential libusb-1.0-0-dev pv
sudo apt-get -y remove modemmanager
wget -q --show-progress --progress=bar:force:noscroll http://dfu-util.sourceforge.net/releases/dfu-util-0.11.tar.gz
pv dfu-util-0.11.tar.gz | tar xzf -
cd dfu-util-0.11/
./configure 
make
sudo make install
cd ..
rm dfu-util-0.11.tar.gz
rm -rf dfu-util-0.11
sudo ln -s /usr/local/bin/dfu-util /usr/bin/dfu-util
```

Merging.

**Comment by rotorman** [comment]
@pfeerick just checked OpenTX - the 2.3 branch is correct already:
https://github.com/opentx/opentx/blob/f171cd4d329bde51b5cc9c17334b21a51d12e605/companion/src/radiointerface.cpp#L53
The issue seems to be present only in the 2.4 branch:
https://github.com/opentx/opentx/blob/54c3f657e48bc6f13fd074df62ddf1ec17fbc92c/companion/src/radiointerface.cpp#L53

**Comment by pfeerick** [comment]
Oh, good. And that also shines some more light on the issue... including that it was only relatively recently fixed. I was thinking at first it might have been something to do with the linking, but it seems to be connected to the version of dfu-util... i.e. only illegal from 0.10 onwards. It was probably more prevalent amongst Arch users as Ubuntu even now (hirsuite) only distrubutes 0.9, and not many people would have call for installing it themselves. 

https://github.com/opentx/opentx/pull/8556

**Pull request merged**
