### PR TITLE
feat(bw): add collapsable sections to B&W radio setup tab

### PR DESCRIPTION
**Pull request by philmoz**
Summary of changes:
- Make Sound, Vario, Haptic, Alarms, Brightness, GPS and Enabled Features sections collapsable.
- Move Startup Sound checkbox to Sound section.

### CODE REVIEW

**Comment by 3djc** [comment]
I personnaly dislike that trend that has been applied to colorlcd, but there is was for good reason about touch. 

The beauty of BW UI is that you have all accessible a scroll speed (which is really fast). Hiding things under sections is not a good thing on BW IMHO

**Comment by pfeerick** [comment]
Even with a fast scroll speed, there is a point where it is better to have things collapsed, than having to scroll. i.e. the enabled features section is a good example of one that really needed to be collapsible... I'm not so sure the other sections, but will have to try it before I can really comment further. But I generally thing if a group has 4 or maybe 5 entries, it probably shouldn't be collapsed... and certainly shouldn't be collapsed if less than that. The tricky part is finding that balance... i.e. that point where is it quicker/easier to scroll and click, than scroll and scroll.

**Comment by pfeerick** [comment]
@3djc What do you think about a general rule of limiting collapsible sections to say groupings with 6-7 or more lines... basically one screen or more of entries?

**Comment by pfeerick** [comment]
@philmoz Can you update this accordingly... since bw128 can show 8 lines, when you subtract the top line, and the section name line, that would make it so that only sections with 6 or more entries should be collapsible.

**Comment by philmoz** [comment]
I don't think having a collapsible section has anything to do with screen height. It's about de-cluttering to make it easier to find things in a large unordered list.

Examples are Vario, Haptic and GPS. All are small sections; but also are not things you would need to have access to often (if at all).

If you set this rule in place then the Throttle section in model setup should have its collapsible section removed (a backwards step). 
Worse the number of entries in the preflight checks section depends on whether the checklist option is checked. So is it collapsible or not?

**Comment by pfeerick** [comment]
> I don't think having a collapsible section has anything to do with screen height. It's about de-cluttering to make it easier to find things in a large unordered list.

Yes, and no. Any UX person will tell you that (similar to number of bullet points per screen in presentations) you do not group things to the point that it takes *more* clicks to access smaller groupings. Hence why 6 is a pretty common number, and just happens to coincide with screen height here. 

> Examples are Vario, Haptic and GPS. All are small sections; but also are not things you would need to have access to often (if at all).

Which are also examples of things that should not be collapsed because they are so small. Given the B&W navigation is actually quite fast - since you can roll the scroll wheel, or for radios without a rotenc, hold the button down -  you can scroll long lists quite quickly. 

> If you set this rule in place then the Throttle section in model setup should have its collapsible section removed (a backwards step).

No, not for the purposes of this PR. And obviously any rule would need to be fine tuned more, as for some longer screens, it makes sense to have more groupings. In this case, this seems to be be making the setup page too short, and frankly awkward to use since need to start expanding sections all the time. To be honest, I don't see any real benefit to collapsing any section of that page atm except for the enabled features section since that is so long. Especially as while I don't personally use vario, or GPS, perhaps someone else does, and needs to change those settings periodically, so this just makes it more awkward for them. 

Perhaps if the collapsed/expanded state(s) were persistent, that may change this entirely, since then you can expand/collapse sections to your hearts content, thus keeping the sections you routinely want access to expanded... :thinking: 

> Worse the number of entries in the preflight checks section depends on whether the checklist option is checked. So is it collapsible or not?

Simple - worst case scenario always applies.

**Pull request merged**
