### PR TITLE
fix: Auto adjust PPM frame length

### PR DESCRIPTION
**Pull request by mha1**
Summary of changes:
- adjusts PPM frame length if channel count > 8
- channel count in [1;8] -> frame length = 22.5 ms
- channel count in [9,16] -> frame length = 22.5ms + (channel count - 8)  * 2ms
- example channel count 9 -> frame length = 24.5ms
- example channel count 16 -> frame length = 38.5ms
- auto adjusted value can be manually overriden

### CODE REVIEW

**Comment by mha1** [comment]
b&w targets already auto adjust for PPM modules but not for Trainer mode. Added auto adjust for Trainer mode on b&w targets accordingly.

**Comment by mha1** [comment]
tested ok on TX16s, TX16s sim, X7 sim, X9D sim

**Comment by mha1** [comment]
With the bw radios having auto adjust PPM frame length already implemented (module only, not for trainer) I'd rather consider this a fix than improvement :-)

**Comment by driedeker** [comment]
lets hope it does not crash stuff like last time this was played with for those using analouge servos

**Comment by pfeerick** [comment]
> With the bw radios having auto adjust PPM frame length already implemented (module only, not for trainer) I'd rather consider this a fix than improvement :-)

Agreed... this is more a feature parity fix ;)

**Comment by mha1** [comment]
@driedeker 
> lets hope it does not crash stuff like last time this was played with for those using analouge servos

Can you be more specific? What historic change (PR) are you referring to? 

I can't see this PR causing problems for a number of reasons:
- this PR implements UI behavior for color radios that is already implemented in 2.8 for b&w radios (and I presume 2.7 too) without any documented issues
- Up to 8 channels there is no auto adjust. Frame length is still set at the default 22.5ms
- Even if auto adjusted users can always override the proposed frame length value to whatever they think is correct

And I am sure selecting more than 8 (maybe 9) channels without (manually or auto) adjusting frame length to more then 22.5ms will cause more problems as the frame gap will shrink close to zero.

**Comment by driedeker** [comment]
> @driedeker
> 
> > lets hope it does not crash stuff like last time this was played with for those using analouge servos
> 
> Can you be more specific? What historic change (PR) are you referring to?
> 
> I can't see this PR causing problems for a number of reasons:
> 
> * this PR implements UI behavior for color radios that is already implemented in 2.8 for b&w radios (and I presume 2.7 too) without any documented issues
> * Up to 8 channels there is no auto adjust. Frame length is still set at the default 22.5ms
> * Even if auto adjusted users can always override the proposed frame length value to whatever they think is correct
> 
> And I am sure selecting more than 8 (maybe 9) channels without (manually or auto) adjusting frame length to more than 22.5ms will cause more problems as the frame gap will shrink close to zero.

was in the days of opentx so way back 2.1-2.2 and yes I am on a b w taranis.

**Comment by pfeerick** [comment]
LGTM on TX12 and TX16S, PPM output is behaving itself, and both PPM and trainer UIs on colorlcd behaving like Companion and B&W PPM ui (as is trainer B&W UI).

**Pull request merged**
