### PR TITLE
Eshifri/model notes icon

### LINKED ISSUE #488: Model Notes missing?
See second post

### PR DESCRIPTION
**Pull request by eshifri**
This adds "Model Notes" button to the carousel (if notes exist).
Resolves #488

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
Looks good to me... works great on the TX16S - adds model notes icon if model notes file present, doesn't add it if not present. Icon is the same as the model select, but as far as I'm concerned that's fine as it should be done as part of tweaking all the icons.

**Comment by eshifri** [comment]
I believe the icon is the same as Model Setup - not Model Select.

**Comment by pfeerick** [comment]
Oops, so it is... it just doesn't help much when you see two icons on the same menu for two different tasks. I would expect it to look more like a notepad when it gets updated... I think all but two of the icons will get the chop as they are circles within circles, wasting valuable icon space.

**Comment by eshifri** [comment]
The text is different. Notepad will look bettr, but I do not see it in the list of available icons.

**Comment by pfeerick** [comment]
lol... yes, which is why I said "that's fine as it should be done as part of tweaking **all** the icons" ...

**Comment by eshifri** [comment]
Yes, this was my understanding until I saw Ooops. :-)

**Comment by pfeerick** [comment]
Sorry, yeah, that was re: which icon was doubled ;)

Do you think something like this would be ok?

image

If so, I'll see if I can figure out how to add it.

**Comment by eshifri** [comment]
Of course! Perfect!

**Comment by pfeerick** [comment]
I'll have a look at that in a couple of hours then ;)

**Comment by raphaelcoeffic** [comment]
Cherry-picked in 645afc11767452049.

@eshifri could you please always rebase your MRs on top of current main? Otherwise, I always see a couple of other commits in the PRs which are not related to the PR itself.

**Comment by raphaelcoeffic** [comment]
> Sorry, yeah, that was re: which icon was doubled ;)
> 
> Do you think something like this would be ok?
> 
> image
> 
> If so, I'll see if I can figure out how to add it.
> 
> If not, maybe something else from https://icons8.com/icons/set/note

Looks good, please add it :-)

**Comment by pfeerick** [comment]
PR done #525. Apologies for the delay... I got a email just a few minutes after commenting on this saying the parts for my PC had arrived, so was surrounded by bits of PC for the last day as I deconstructed the old one, and built it back up again... A clean build of the TX16 firmware now takes only 21 seconds. 😮

**Comment by eshifri** [comment]
> Cherry-picked in [645afc1](https://github.com/EdgeTX/edgetx/commit/645afc11767452049e7d5e336fe99f3e64501d23).
> 
> @eshifri could you please always rebase your MRs on top of current main? Otherwise, I always see a couple of other commits in the PRs which are not related to the PR itself.

Sorry about that. I do not have much experience with github.
Do you mean I should not rebase the branch after submitting the pull request?

**Comment by pfeerick** [comment]
Basically when you are doing Merge/Pull Requests, if you keep rebasing on the source branch (`main` in this case) (during the life of the PR), it will make it so that *only* your changes come through as part of the pull request. If you look at this PR for instance, you'll see that even though it was in relation to one file, there are other changes in the mix also, making extra noise. You will probably need to force push after a rebase, as it is essentially re-writing history since you've already pushed a PR, and want to change it's starting point. 

Rebase basically removes your commits, pulls in the current version of the branch being rebased on, and then trys to put your commits back on again. There could be merge conflicts if something has changed since in the section of code you are modifying - if so, you make the necessary changes and continue with the rebase. 

Another thing to play with is the use of the[ linking keywords when creating PRs to resolve issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)... i.e. "fix/fixes/fixed" or "close/closes/closed" are trigger words for Github, that tell it that the issue number that follows can be automatically closed if the pull request is merged. It's just a handy automation tool that

**Pull request closed without merging**
