### PR TITLE
Fix mixer setup "invisible mixers"

### PR DESCRIPTION
**Pull request by kevinkoenig**

### CODE REVIEW

**Comment by eshifri** [comment]
I remember empty first mixer was creating some ugly problems (do not remember which ones). Is it OK now?

**Comment by raphaelcoeffic** [comment]
> I remember empty first mixer was creating some ugly problems (do not remember which ones). Is it OK now?

Well, we shall see :-D

**Comment by pfeerick** [comment]
Right, so testing this with TX16S + MPM + X8R receiver, and NV14 + FS-IA10B (plus 3-4 servos on each) and it does appear to work and the radio doesn't crash or break the link or anything. However, this then raises a rather nasty bug, and it seemed to trigger the NV14 to EM whilst trying to undo it. 

https://user-images.githubusercontent.com/5500713/144791861-012b39d1-8ce8-4780-a8be-02606ac7ede5.mp4

**Comment by raphaelcoeffic** [comment]
It is to be noted that the B&W UI solves the issue in a totally different way: the source attribute cannot be set to `"---"`, so the case is closed, as it can never be empty "the normal way".

From the storage's point of view, the issue should not happen as well, as a `all-0` mix is not listed at all, thus having the follow-up mixes being listed first anyway.

**Comment by pfeerick** [comment]
My first quick test of this on TX16S hardware suggests it is working perfectly now. I'll keep playing with it though.

**Pull request merged**
