### PR TITLE
fix(color): Use ACTIVE theme color for inputs, mixes, LS, GV and SF.

### LINKED ISSUE #3866: Wrong colors in menue Logical Switches
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Activating a Logical Switch does change the color of the line. But the new color is that of the background of the screen and not the color for "Active".

### Expected Behavior

Color changes should stay unchanged to V2.8.4: Activating a Logical Switch did change the color of the line to the "Active" color, giving a good contrast to the background of the screen.

### Steps To Reproduce

Define any logical condition being normally False/Inactive.
Make this condition become True/Active.
Watch the coor of the line change to the color of the background of that screen: No contrast. 

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2, Other (Please specify below)

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### LINKED ISSUE #3893: Change of colour in tthe special functions area
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Something I have just noticed mainly as i don't fly with the latest version of ETX.
when a switch is active in Special Funtions the difference in colour change is no where near as noticable as it used to be.
 in 2.9 RC1 is is now white to a pale blue which is much less noticable also and now the enable button is yellow 

### Expected Behavior

In my case using the ETX std background was white = an inactive switch/function and yellow as an active switch/function
The enable button  used to be dark blue white border.

### Steps To Reproduce

active model menu / special functions

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

win 10  ETX 2.9 RC1

### Anything else?

I raised this in general and no one seemed interested but in my case I find this change makes quick viewing or any viewing in any sort of day light a non event if you wish to see if a switch is acative or not as the colour change is a none event under any sort of bright light condition.
image
image

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3866 and fixes #3893

### CODE REVIEW

**Comment by philmoz** [comment]
I hope this is ok - I created it on the edgetx GitHub instead of my fork.

**Comment by pfeerick** [comment]
Old version of `main`? Otherwise, sure, doesn't matter if it's on ETX or fork ;)

**Comment by philmoz** [comment]
I thought I branched it from 2.9 ??

**Comment by pfeerick** [comment]
Ah, that explains it... it's set to merge into main, not 2.9... one moment...

**Comment by pfeerick** [comment]
Perfecto! Now it is entirely up to the theme to decide what color is best :)
msrdc_wnLSmLFihk
msrdc_aWargmvU1S
msrdc_pLNsz2tKiu

**Comment by JimB40** [comment]
Just will leave it here because, now screens lists look different on every screen.
And with those changes 'here and there' UI consistency that was in 2.7-2.8 is gone.

Lists with no sub-items (lines)
1. Unseleced
2. Focused (selected)
3. Unselected - Active
4. Focused (selected) - Active 

Screen List Item

Lists with no sub-items (lines)
1. Unseleced list item
2. Focused (selected) list item, Focused 1st sub-item (line)
3. Unselected list item , Active 2nd sub-item (line)
4. Focused (selected) list item, Focused 1st sub-item (line), Active 2nd sub-item (line) 

Screen List MultiItem

**Comment by philmoz** [comment]
In LVGL the input/mix group is not a selectable element so it cannot have focus - only the individual input/mix lines have focus. While it could probably be done it isn't consistent with the concept of a 'focussed' control in LVGL.

Of more concern to me is this:
Screenshot 2023-08-04 at 7 57 26 am

As you have drawn it, this would require two different FOCUS colors, one for the list and one for the item.
This would probably require a new color to be added to the system and would then be a different type of inconsistency.

**Comment by JimB40** [comment]
@pfeerick you can close https://github.com/EdgeTX/edgetx/issues/3021
Same issue but with 2.8

**Comment by pfeerick** [comment]
@JimB40 I do get what you mean about it being different... i.e. on 2.7.x you had the extra level of detail that highlighted what channel the focused line belonged to. 

image

The question is is that information of any practical value? So, looking at how it looks now:

image

If we go back to the in-the-field usage scenario, then yes, it makes it more obvious what line you are at, than just the line focus border. i.e. I'd be able to more easily tell I'm on one of the 'Rud' lines when not looking at my nice computer screen indoors (which even then takes longer to figure out than I would care to admit 🤭)

Regarding the colour, knowing you, it's probably something like PRIMARY2 and SECONDARY1 for the list focus colours, and then FOCUS for the lines?

**Comment by JimB40** [comment]
Yes Screen List with sub-lines is the hardest UI element to make it consistent with other elements.

1. List with sub-lines
We want to inform user that:
- item is selected (Group of UI elements) - CH1.
- line is selected -  100% Thr 
- on top of that line is active

I think 2.7 implementation grasped is well. You can see what group and line is selected and on top of  thart hat is active.
With this list lines visual priority is given to ACTIVE state. (big yellow inversion). IMHO is more important here to see what (SF,GF,LS, input line) is active so that leaves border in FOCUS color to see what is selected. 
Still with CH1 (label) inveted in FOCUS color you can learly say what item is selected 

2.  Other UI elements
Then it is always in UI about priorites.
So with other UI elements like: Text Inputs, Number Inputs, Switches, Sliders, Buttons that open popup list etc. is more important to put visual priority on selection.  That's why inversion with FOCUS color is better than tiny frame.

258352254-ae892a66-c0ae-4a98-a5cc-2785c04191b4

3. Standard buttons 
IMHO they should fall in in second category (when selected whole button background inverse with FOCUS color)
Then it's a matter of finding good way to show user it also ACTIVE at the same moment.

In my design when button is FOUSED and ACTIVE I've retained bacground color as FOCUSED and changed button text to ACTIVE color. I must say I'm not 100% happy with clarity ratio. So we may find another way to inform when button is both FOCUSED and ACITIVE. Like give button yellow frame (ACTIVE color). Then visual priority is still on selection not on being active. 
Button Text Info

Overall idea is ... if something is inverted in FOCUS color it is seleced by user.
TopBar icons follows this scheme.

**Comment by pfeerick** [comment]
I didn't want this to digress from the topic being discussed at present - lists like the inputs and mixes lines - so all I ill say with regards to the image showing the states is being able to tell between FOCUSED or ACTIVE FOCUSED is indeed 💩 🤣  . Almost as if a `> Text <` is needed to make it visually different.

**Comment by JimB40** [comment]
Can't say like that about my own work :) 
1. 99% you already know button is ACTIVE because you've seen playn yellow before you selected it
2. Most important is to visualize FOCUS state as you want it to use it ATM. information about ACTIVE is additional at this moment of user interaction
3. As wrote ACTIVE-FOCUSED state can be done beter not loosing primary UX goals. 
4. Never said I'm 100% right all the time, Quite often I'm very pleased with devs/users UX comments or ideas or comments to improve. Thing is than in UX, topics like usabilty, readabilty, constancy, speed of usage go first then we ask ourself "Does it look good"? 

So I'm always open to test different ideas (at best tested on device). Particularly in areas that I know can be done better. :)

**Pull request merged**
