### PR TITLE
improve backlight handling on color lcd radios

### PR DESCRIPTION
**Pull request by gagarinlg**
no more backlight off for color lcd radios

disable backlight input controls in radio setup screen, when they are not used by the selected backlight mode -> needs PR ~~https://github.com/EdgeTX/libopenui/pull/34~~ to work

https://github.com/EdgeTX/libopenui/pull/33

force backlight on to be at least the brightness of backlight off

### CODE REVIEW

**Comment by pfeerick** [comment]
Ok, lets not do that... (normally I can bump the submodule once it's merged but this time it's being a pain, I think because of other changes made in the mean time - anyhoo, that can be fixed post merge. 

One query as to behaviour and then it's good to go - the off and on sliders can no longer be dragged by touch - i.e. try the the haptic strength slider a few lines up, and then try either the on or off brightness sliders (was not a problem before). Culprit isn't jumping out at me... and it is an acceptable gremlin for otherwise better behaviour.

**Comment by gagarinlg** [comment]
> One query as to behaviour and then it's good to go - the off and on sliders can no longer be dragged by touch - i.e. try the the haptic strength slider a few lines up, and then try either the on or off brightness sliders (was not a problem before). Culprit isn't jumping out at me... and it is an acceptable gremlin for otherwise better behaviour.

This is strange and should not happen. Depending on your backlight setup, they might be completely unaccessable on purpose, but sliding should not be changed, when they are enabled. I will try in my lunch break.

**Comment by gagarinlg** [comment]
So I did read the code and test it.
What I found is, that you have to hit a spot in the area of the slider, that matches the current value. So on a silder with just 5 positions it is easy to hit the right area, but the Backlight has 100 steps, so it is prettx hard to hit the right spot. Sometimes I do manage to hit the right spot, but most of the time not.
It has nothing to do with the handling of the enable flag in libopenui or the changes in this PR, as far as I understand the code.
What I propose is to have a capture area on sliders with a high number of values. So that the first slide event is handled like a touch up and then following slide events as slides. If you are outside the capture area it does nothing, as it s currently.
But, IMHO this is a new issue to be opened.

**Review by pfeerick — APPROVED** [review]
Ah ha... yes, that makes perfect sense now, as nothing in this PR or the libopenUI PR was the cuplrit, and poking the TX16S a bit more I can see what you mean about needing to be 'accurate' about where you press for it to 'latch on'... so yes, that particular problem around making touch a bit more... 'fuzzy' would be the focus of another issue. 

This will be merged after today's nightly... as there are enough changes introduced into that for now! 😆

**Pull request merged**
