### PR TITLE
Windows & Mac OSX companion build

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This is based on #706, with little additions to cope for MacOSX build.

### CODE REVIEW

**Comment by elecpower** [comment]
Is the init code that was commented out going to be reinstated before merge?

**Comment by raphaelcoeffic** [comment]
> Is the init code that was commented out going to be reinstated before merge?

I wasn't planning to, but you tell me ;-) ATM, the Theme does not accept any params anyway. And I'm not sure we should have 4 screens configured. So maybe this needs a bit of revamp anyways.

**Comment by elecpower** [comment]
The code replicates the default theme and   first custom screen layout set by radio.
Shouldn't they align?

**Comment by raphaelcoeffic** [comment]
> The code replicates the default theme and first custom screen layout set by radio.
> Shouldn't they align?

Oh! Sorry for not reading carefully enough! Ok, so I can just rename the macros and uncomment?

**Pull request merged**
