### PR TITLE
This is EdgeTx not OpenTx I

### PR DESCRIPTION
**Pull request by olliw42**
renames opentx.h, opentx.cpp, opentx_xxx.h to edgetx.h, edgetx.cpp, edgetx_xxx.h

compiles for T16 and Tx16S, and tested to work fine on T16

not sure if there are side effects with companion, simulator etc, never looked at these, but should not be hard to sort out

:)

comment: I would see more to do along this lines, like renaming function like opentxInit() but would do it step-by-step, after approval or rejection of a previous pr :)

### CODE REVIEW

**Comment by pfeerick** [comment]
Do we really want those changes yet though? If this is to become a completely separate project, sure, but if the work done in EdgeTX goes back into OpenTx and kicks it back into life, these are problematic changes, no? Should changes like this wait until after seeing what the future of EdgeTX vs OpenTx is? Or did I miss the memo about OpenTX being dead, all hail EdgeTX? 😆

**Comment by olliw42** [comment]
that's a valid question, and I have a clear opinion:
1) if one wants to do such changes it will be much easier to do them early on
2) as much as I can see from the few days this fork is existing, the hopes that the two code bases will stay relatively similar so that backporting will be relatively easy are false hopes ... this code base IMHO will very quickly develop and move on and if it wants to keep it's promise even only remotely - to be edge - there is no way out of it. IMHO it's very simple: Either you want to have edgetx code be similar to opentx, but then edgetx won't be more than just a feature branch of opentx, or you want it to lead, then opentx has to follow and not vice versa

**Comment by pfeerick** [comment]
Indeed... I think at the end of the day... [whilst there is the hope that stuff can be 'backported'](https://www.rcgroups.com/forums/showpost.php?p=47115055&postcount=5102) ... this is cleary the 'experimental' version ... and as such, any PRs back to opentx will just have to rectify any changes...

**Comment by olliw42** [comment]
@raphaelcoeffic a response at least would be much appreciated, so I know how I should proceed :)

**Comment by raphaelcoeffic** [comment]
We had a common agreement with Kilrah that it would be sufficient to make it clear “ETX is not OTX” by just changing splash, version tag names. Other disruptive changes would indeed cause quite some trouble when merging stuff back. Let’s hope this will really happen (the merge backs, that is).

**Comment by raphaelcoeffic** [comment]
> that's a valid question, and I have a clear opinion:
> 
> 1. if one wants to do such changes it will be much easier to do them early on
> 2. as much as I can see from the few days this fork is existing, the hopes that the two code bases will stay relatively similar so that backporting will be relatively easy are false hopes ... this code base IMHO will very quickly develop and move on and if it wants to keep it's promise even only remotely - to be edge - there is no way out of it. IMHO it's very simple: Either you want to have edgetx code be similar to opentx, but then edgetx won't be more than just a feature branch of opentx, or you want it to lead, then opentx has to follow and not vice versa

I second your opinion on both items, but let’s try to not close the door right now.

**Comment by olliw42** [comment]
ok, many thx for the clarification, much appreciated

I however have then to frankly say that edge won't be then as edge as it was suggested
I fail to understand how that "not closing the door" could be possible in view of things like a new RTOS, less define tokens but dynamic features, and other things which seem to be already on the plate. Seems not yet fully thought out. IMHO. :)

I close this then :)

**Comment by raphaelcoeffic** [comment]
Time will tell: if we progress so fast that merging back is not possible without huge efforts, then so be it. But I will not “force it”, just let it happen. This is a fine line ;-)

**Comment by raphaelcoeffic** [comment]
But I must say that I am overwhelmed by the engagement our young community is showing! This is really moving into the right direction!

**Comment by olliw42** [comment]
:)

**Comment by pfeerick** [comment]
> I however have then to frankly say that edge won't be then as edge as it was suggested
> I fail to understand how that "not closing the door" could be possible in view of things like a new RTOS, less define tokens but dynamic features, and other things which seem to be already on the plate. Seems not yet fully thought out. IMHO. :)

It may very well may not work... ideally this would go down somewhat like Cleanflight vs Betaflight, if I understand the history of that right.  Betaflight stuff is being merged back into Cleanflight on a regular basis... and the same is hoped to happen here. That would *include* all of the improvements of newer RTOS. But if they see fit to not allow that, or feel it needs more testing, etc, EdgeTX might end up going it's own way. Only time will tell... we'll probably get an idea of the state of affairs in July once 2.4 is out and in the wild. :)

**Pull request closed without merging**
