### PR TITLE
Fix Branch Artifact Naming

### PR DESCRIPTION
**Pull request by CoderElectronics**
@raphaelcoeffic This is the fix for the changes that were made earlier to branch naming.

### CODE REVIEW

**Comment by gretel** [comment]
think [my approach](https://github.com/EdgeTX/edgetx/pull/100) is more elegant 🤷. the change to `README.md` should not be in this, tho.

**Comment by raphaelcoeffic** [comment]
@CoderElectronics small hint: please amend your commits and force push to the PR branch rather than having a list of more or less same commits. Ideally you should have only one commit with the final result in this PR.

**Comment by pfeerick** [comment]
What, you don't want to squash merge it? :-P

**Comment by raphaelcoeffic** [comment]
> What, you don't want to squash merge it? :-P Although I _may_ have also been the person who resolved a PR merge conflict across forks by simply replacing all the code in the source file in the parent fork... instead of a rebase! 😆 😮 What can I say..... it was a near complete re-write anyway! 😁

I can absolutely do squash-merges, but that does not solves the issue with the review ;-) It is quite irritating to see code changes there that are in no way related to the PR itself.

**Comment by CoderElectronics** [comment]
@raphaelcoeffic Sorry about that, I was not on my normal laptop and my branch wasn't fully set up. I will make sure to use that next time!

**Pull request closed without merging**
