### PR TITLE
fix: enforce custom switches rules when configuring

### LINKED ISSUE #4990: Quirks in behaviour of customisable function switches.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There are some oddities in the way the customisable switches behave (tested on T20V2).

My understanding is that a switch group should follow the following rules.
- only zero or one of the switches in the group can be on at any given time
- if the group is set to always on, then one of the switches must be on

Issues:
- When a switch group is changed to always on, the radio does not enforce the rules so the group could have 0 or more than one switch turned on depending on the current state of the switches.
- When a switch is added to a group, the rules are not enforced so multiple switches can be turned on.
- If more than one switch on a group has the startup state set to UP or DOWN then the radio will start with all the affected switches in the group turned on - again breaking the only one rule for a group.
- If a switch is removed from an always on group the group could be left with no switch turned on.

Other concerns, with the B&W UI:
- If the switch type is set to None then the group and always on checkbox should be hidden.
- If the switch is part of an always on group then the switch type 'Toggle' should not be available (the switch will not work as a toggle when in a group).

### Expected Behavior

When editing the custom function switches the rules should always be enforced to prevent invalid states being created.
- When a switch is added to a group:
  - Set the startup state to 'Last Value'.
  - If the group is always on:
    - If the switch type is set to 'Toggle' change it to 2POS.
    - If no switch in the group is on, then turn on the newly added switch.
  - If any other switch in the group is turned on, then turn off the newly added switch.
- When a switch is removed from a group:
  - If the group is always on, and no other switch in the group is on, turn on the first switch in the group (if there are any).
- When a group is changed to always on:
  - If no switch in the group is turned on, turn on the first one.
- When a switch startup state is set to UP:
  - If the switch is in a group then set the start position of all other switches in the group to 'Last Value'
- When a switch type is set to 'None':
  - Hide the group selector and always on checkbox
- When a switch is in a group:
  - Do not show the DOWN option for the switch startup state.
  - If the group is always on:
    - Do not show the 'Toggle' option for the switch type.

### Steps To Reproduce

Setup custom function switches with the various states described above.

### Version

Other (Please specify below)

### Transmitter

Jumper T20 V2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4990 

Changes to the UI for setting up custom function switches to prevent invalid setup.

### CODE REVIEW

**Comment by 3djc** [comment]
Overall very nice (i realize this is WIP)
- I think we can hide Groups that have no switches in them
- There is a functional issue, where selecting a switch for the group doesn't delete the '=' for other switch in group
- I think most, if not all, of the functions in model_setup should move to a common place, like switches.cpp


I will wait for that change to be merged to address #4989, since both need similar functions added

**Comment by philmoz** [comment]
> * I think we can hide Groups that have no switches in them

Done.

> * There is a functional issue, where selecting a switch for the group doesn't delete the '=' for other switch in group

I think this is fixed now.

> * I think most, if not all, of the functions in model_setup should move to a common place, like switches.cpp

Moved the ones that aren't UI specific.

I've also renamed FS_START_UP to FS_START_ON and FS_START_DOWN to FS_START_OFF to avoid confusion and because the previous names were backwards. E.G. if you use one of the custom switches in a SF then the ON state shows as SW DOWN, not UP which is consistent with usage for normal switches.

**Comment by 3djc** [comment]
Perfect !

**Comment by philmoz** [comment]
For completeness, I've added an option to set the startup state of a group to 'Off'.
This will force the group to be all off on startup.
Only applies to groups that are not set to always on.

**Comment by 3djc** [comment]
Successfully tested on T20V2

**Comment by philmoz** [comment]
Changed the diag page to use arrows and OFF/ON labels.

screen-2024-05-14-223649

**Comment by elecpower** [comment]
Screenshot from 2024-05-17 13-17-40

Add space character between Group and number ie Group1 -> Group 1 for labels and drop down lists

Would it not be more appropriate for the 'Start Switch' label to be 'Start' as the option per group is not always a switch eg Restore or Off

**Review by pfeerick — APPROVED** [review]
Firmware side seems to work great, applies the rules as laid out and all makes sense. 

Companion side needs a little more work as it while it seems to apply the rules just like the firmware, it does it differently... i.e. if you set SW6 to toggle, no group, set a group to always on, you can't assign SW6 to that group (whereas the firmware would let you, but force it to 2POS). And if you do this in reverse, i.e. set SW6 to be momentary, assign it to a group, and *then* set the group always on, it disables the group combobox, and the type field flashes but doesn't update until mouse-over and is now unselected rather than 2POS. 

image

I would prefer to merge this as is, and continue any Companion work in #5016 since that is the next one in line for this three PR chain... sound ok? (Assuming, of course, this is isn't related to a limitation what we can do with Companion UI).

**Comment by philmoz** [comment]
> I would prefer to merge this as is, and continue any Companion work in #5016 since that is the next one in line for this three PR chain... sound ok?

Give me a little while to check - I would prefer to have this PR clean if possible.

**Comment by philmoz** [comment]
Should be fixed now. 
Also squashed another bug where startup state of all switches could get reset when group was set to always on.

**Comment by pfeerick** [comment]
Yes, looks like you got it... thanks! :)

**Pull request merged**
