### PR TITLE
CRSF: fix telemetry decoders for CRSF telemetry packets 0x07 and 0x09

### PR DESCRIPTION
**Pull request by mha1**
CRSF defines two telemetry packets delivering vertical velocity, The older but still valid CRSF_FRAMETYPE_VARIO packet (ID 0x07) and the newer (extended) CRSF_FRAMETYPE_BARO_ALTITUDE (ID 0x09):

```
// CRSF_FRAMETYPE_VARIO (ID 0x07)
typedef struct crsf_sensor_vario_s
{
    int16_t verticalspd;  // Vertical speed in cm/s, BigEndian
} PACKED crsf_sensor_vario_t;

// CRSF_FRAMETYPE_BARO_ALTITUDE (ID 0x09)
typedef struct crsf_sensor_baro_vario_s
{
    uint16_t altitude; // Altitude in decimeters + 10000dm, or Altitude in meters if high bit is set, BigEndian
    int16_t verticalspd;  // Vertical speed in cm/s, BigEndian
} PACKED crsf_sensor_baro_vario_t;
```
The current CRSF telemetry decoder implementation lists the CRSF packet CRSF_FRAMETYPE_BARO_ALTITUDE parameters altitude and vertical speed as sensor Alt with ID 9, subID 0 and VSpd with ID 7, subID 0. According to the CRSF spec VSpd should be reported as ID 9, subID 1 for the CRSF_FRAMETYPE_BARO_ALTITUDE packet.

Summary of changes:

This fix implements the CRSF spec for both packet types and ensures in case an FC or any other external CRSF source sending both packets the sensors are discovered and listed with their correct ID/subID and are listed as two disjoint sensors distinguishable by their sensor ID.

Vspd from source CRSF_FRAMETYPE_VARIO) -> ID 7, subID 0
Vspd from source CRSF_FRAMETYPE_BARO_ALTITUDE -> ID 9, subID 1

The reasoning behind this clear separation is the use case where a receiver with built-in Vario is used (e.g. RM ER8-GV) and an external Vario delivers data too. The user can now decide which Vario source shall be used for Vario tone generation..

If desired the distinction could be made clearer by additionally changing the sensors names to e.g., Vsp7 and Vsp9. Let me know if this

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@CapnBry can you please confirm this?

**Comment by CapnBry** [comment]
Hrm, I don't really know. 

One major problem is this code removes the check on packet length and just assumes that the telemetry packet `CRSF_FRAMETYPE_BARO_ALTITUDE` will have the VSpd item. I am not 100% certain (or even 25% certain really) that all senders support this. iNav and Betaflight do not support this sensor; iNav supports only the Vario but both send altitude only in the GPS packet. I know other handset firmwares do not support the VSpd-in-baroalt (ETHOS for sure does not) so it is likely all senders also do not include this data in that packet which would cause an OOB memory access in that case. That would still be inside the allocated buffer, but would generate invalid VSpd. I would recommend leaving that code how it is for compatibility. The baroalt packet was sort of semi official I think so many things about it are "transitional support" I think.

As far as the EdgeTX IDs, I do not know why those would be part of any official CRSF spec as they're internal to the EdgeTX implementation. The only CRSF ID required is in the packet itself, where this is ID 0x09 and what EdgeTX does with it after unpacking it is not CRSF. There is an opportunity for `CRSF_FRAMETYPE_VARIO` (supported only by iNav but filled with baro+GPS fusion) to overwrite the VSpd from the BARO_ALT packet since they have the same EdgeTX ID, but I believe these two telemetry types to be mutually exclusive as they are implemented in other firmwares currently: you would not send VSpd separately if you have a BARO_ALT you could send it with for free and sending both ... [feints in wasted bandwidth]. The suggested use case of 
> where a receiver with built-in Vario is used (e.g. RM ER8-GV) and an external Vario delivers data too
Seems a little crazy to me, as the ExpressLRS paradigm is to disable sending of one sensor when another external one is used in its place (currently only VBAT/Current). Who would buy a Vario RX then buy a separate external Vario and then also want to be able to select to not use it? If there was an external Vario, then it would take precedence over the internal. I guess maybe if there was a flight controller where you couldn't disable outputting the VSpd item? Betaflight allows disabling telemetry items, not sure about other firmwares. You would **NEVER** hook up a flight controller to an ExpressLRS Vario receiver though, as the amount of telemetry added by the FC makes the Vario data come so infrequently as it would be flarkin' useless.

### Conclusion
Did you get more than you bargained for when you asked for my insight? 😱 I always have a lot to say but want to provide the clearest picture when reviewing. In short:
* The code removing the length check MUST remain, that packet type is still half supported everywhere after being in for a year, and the half-sized packet will be around for years so it can not be assumed to always be present.
* If you're ok with adding mode code space (hopefully that struct lives in .text) then the extra line to support two VSpds isn't terrible. It would be a pretty rare use and that use would render the Vario worthless due to the delay. I would fix that on the supply side of the tiny OTA pipe, not send two then display one that is already several seconds old.

**Comment by mha1** [comment]
Hi Bryan,

I reverted back to the length check. Please let me check if I understood you correct. 

This is how ELRS defines the baro alt packet (0x09). It's has payload size 4:

src\lib\CrsfProtocol\crsf_protocol.h
```
// CRSF_FRAMETYPE_BARO_ALTITUDE
typedef struct crsf_sensor_baro_vario_s
{
    uint16_t altitude; // Altitude in decimeters + 10000dm, or Altitude in meters if high bit is set, BigEndian
    int16_t verticalspd;  // Vertical speed in cm/s, BigEndian
} PACKED crsf_sensor_baro_vario_t;
```

You're saying some (legacy code) FC's send  0x09 with payload size 2 like this:
```
// CRSF_FRAMETYPE_BARO_ALTITUDE
typedef struct crsf_sensor_baro_vario_s
{
    uint16_t altitude; // Altitude in decimeters + 10000dm, or Altitude in meters if high bit is set, BigEndian
} PACKED crsf_sensor_baro_vario_t;
```
Correct? So if I send this this packet EdgeTX will discover this as "Alt" and only "Alt", no "VSpd"? Am I right?

Oh, and can I DM you?

Thanks for your time,
Michael

**Comment by pfeerick** [comment]
This may give some additional context : https://github.com/EdgeTX/edgetx/pull/2253

**Comment by mha1** [comment]
Answering to myself. Yes, if you send out a crsf_sensor_baro_vario_t packed (struct has 4 bytes payload) and set the payload len to 2 when assembling the frame Alt is discovered and VSpd is not discovered. I am surprised you let this go through. To me this would be an ill formed frame as I'd expect a 4 byte payload from 0x09's definition. But anyway the check is back in. 

But please can we not feed my OCD even more and have the rest of this PR:
- have VSpd  with ID and subID 7/0 if a 0x07 frame is discovered
- have another VSpd with ID and subID 9/1 if a 4 byte payload baro_alt frame is discovered

I mean this is exactly what already happens with Alt:
- Alt is discovered with ID and subID 2/4 if a GPS frame (ID 0x02) is detected
- another Alt is discovered with ID and subID 9/0 if a baro_alt frame (0x09) is detected

**Comment by mha1** [comment]
Tested this PR on TX16s with Jumper AION micro module and BetaFPV nano RX.

test case 1: 
- sending "short payload 2 bytes" ID 0x09 packet [c8  4  9 27 11 66]
- expect only ALT to be discovered with 9/0
- tested ok

test case 2: 
- send ID 0x07 packet [c8  4  7 14 1a bb]
- expect VSpd to be discovered with 7/0
- tested ok

test case 3: 
- sending "short payload 2 bytes" ID 0x09 packet [c8  4  9 27 11 66]
- send ID 0x07 packet [c8  4  7 14 1a bb]
- expect ALT 9/0 and VSpd 7/0
- tested ok

test case 4:
- sending "regular payload 4 bytes" ID 0x09 packet [c8  6  9 2b 6b  4 d2 af]
- expect ALT  9/0 and VSpd 9/1
- tested ok

test case 5:
- send sending "regular payload 4 bytes" ID 0x09 packet [c8  6  9 2b 6b  4 d2 af]
- send ID 0x07 packet [c8  4  7 14 1a bb]
- expect ALT 9/0, VSpd 9/1 and VSpd 7/0
- tested ok, see pictures

image
image
image
image

**Comment by 3djc** [comment]
I think it ignores CapnBry comment that one should never use two vario because of the loads it puts on telemetry feed. Using space, albeit small, for something that should be done isn't best use of of said space ?

**Comment by mha1** [comment]
Same with ALT if you have an external GPS on a receiver with internal vario like the ER8GV

**Comment by 3djc** [comment]
Not quite, barometric alt and gps alt have little in common (not same values, not same refresh rate,...)

**Comment by 3djc** [comment]
Yeah, 'as long as you don't discover'...

**Comment by mha1** [comment]
they will still work until you re-discover. This is standard behavior I'm afraid,

The EdgeTX internal reference by list index is a major flaw of the telemetry system. If you re-discover the sensors the same sensors will be found but mostly shuffled on other list indexes because the list is populated in the order telemetry delivers them. You can't predict the order. Ask Peter, he knows and it's on the clean up list. 

And all this without my PR's interference.

**Comment by mha1** [comment]
@3djc I bow to the master, you were right. In general changing the ID of a Sensor will break existing setups, changing the instance ID (= subID) doesn't make a difference.

But this PR won't break existing setups because no ID's are changed. It just adds a new sensor which will only be available after re-discovering. As always with re-discocery if it places the new sensor (if present) at the end of the existing list you're good. If not and it reshuffles the list you'd have to go through your setup in any case. 

image

**Comment by 3djc** [comment]
It always add new sensors at the end. Aren't you changing  CRSF_FRAMETYPE_BARO_ALTITUD from 7.0 to 9.1 ? So anyone that had their sensors at 7.0 will basically have to rediscover and have there setup broken, no ?

**Comment by mha1** [comment]
1. if your existing config receives VSpd from CRSF packet 0x07 (vario packet) nothing changes.
2. if your existing config receives VSpd from a 4 byte payloaded CRSF packet 0x09 VSpd will change ID from 7 to 9.

Yes, number 2 breaks an existing setup. But are we really in the backward compatibility trap? My 5ct: making things right beats backward compatibility.

You are right, new sensors are added at the end of the list but it will most of the times shuffle the sensors if you delete all sensors and the discover again.

How I see my proposal(!):

This PR just makes things right with 0x07 and 0x09 packets. Latest golden ELRS release receiver firmware 3.3.0 sends out 0x07 if it receives a 0x07 at the CRSF serial port. And will send out 0x09 (Alt and Vspd) if an internal baro is detected (as for ERxV receivers) or if it receives it via the CRSF serial port. If an internal vario is detected and 0x09 is received on the CRSF port they will even overwrite each other but that's a different story, https://github.com/ExpressLRS/ExpressLRS/blob/5e3d2e3549ffa00c34ead517d57310a92be7ff7b/src/lib/Baro/devBaro.cpp#L52C1-L98

In 3.3.0 having both 0x07 and 0x09 in parallel is perfectly within what ELRS permits. This should be reflected in EdgeTX telemetry as well I believe. And what bandwidth limitations are we talking? Module to handset?  Another 8 bytes matter?

Btw: I'd be more concerned about https://github.com/EdgeTX/edgetx/discussions/3998#discussioncomment-6911242

**Comment by 3djc** [comment]
Bandwidth is air bandwidth, vspd needs fast updates, on craft with a lot of channels.

And breaking users setup should not be taken lightly, imho

**Comment by CapnBry** [comment]
> To me this would be an ill formed frame as I'd expect a 4 byte payload from 0x09's definition. 

It isn't ill formed though because some things only send BaroAlt in that packet and none of us knows what the actual spec is-- we only have partial code as a reference. The 4 byte payload version was a backward compatible extension to double the update rate of the two independent fields and the values were intended to be redundant. That is, if the sender had a Baro they would publish BaroAlt and optionally VSpd in the same packet. If they did not have just a Baro, they could still send a VSpd (from GPS or sensor fusion) using the standalone version. If there were two VSpd items in the EdgeTX telemetry item list, you can't tell which one is which when selecting it via other menus in EdgeTX either which is not a great experience.

If someone has plugged a GPS into their ER8GV (which you keep using as an example but does not support this at all) then I would expect the incredibly smart and handsome ExpressLRS developers to **not send standalone VSpd from the GPS** and only send GPS and BaroAlt+VSpd. You wouldn't want to waste telemetry bandwidth to send an extremely useless GPS-based VSpd when the very high precision Baro-based VSpd is available.

Vario VSpd reporting is a unique telemetry item which is incredibly latency-sensitive and when you're sending it, you want as little else clogging up the telemetry pipe to get it into the user's ears (thanks to the incredibly talented and handsome EdgeTX developers) as soon as possible. You wouldn't want to try to find thermals with the vario if it has a long lag (seconds) between the change in VSpd and it being reported to the handset so you minimize the other stuff which would include not sending two VSpds.

I have no strong opinion on if a second VSpd should be added to EdgeTX, but I do have a strong opinion that things that send VSpd as their key feature should **never** send *two* VSpds, one of which is total garbage. That is easily fixed on the sender side, if it was ever a problem, which it won't be because the upstream developers are smart enough to write the code correctly for providing that key feature in the most performant way possible.

**Comment by mha1** [comment]
Yes handsome they are I'm sure.

I still didn't manage to make the use case clear. Assume an external device with GPS and(!) Baro combined on the same board connected to the CRSF port of a receiver with built in Baro. So two baros. My thinking: to let the user decide which one he/she thinks performs better it be necessary to have both Vspd's reported and of course EdgeTX to have both discovered.

But don't worry, I give up but have a question: 

Assume you have such a combined GPS and Baro on an external board connected to the CRSF port. What is your suggestion for packets to use and rates to use for the packets.  0x02 at 1hz (or 5Hz?) with Alt in 0x02 being baro altituide and 0x07 at let's say 10Hz? Don't use 0x09 at all? Or 0x02 at 1hz or 5Hz with ALT being GPS Alt and 0x09 for baro alt and vv at 10Hz? Then the internal baro needs to be silent as it is done for Vin.

Or something completely different?

**Comment by mha1** [comment]
@3djc have you looked at https://github.com/ExpressLRS/ExpressLRS/blob/5e3d2e3549ffa00c34ead517d57310a92be7ff7b/src/lib/Baro/devBaro.cpp#L52C1-L98

Any thoughts?

**Comment by CapnBry** [comment]
I do understand your use case, but if there's an external GPS+Baro that spits out CRSF I'm not sure what to do. It certainly is valid that the user could buy a vario RX and then also buy a vario GPS and want to use them together. The pilot may want the external VSpd or maybe they want the internal VSpd, so yeah they should see both right? But really they only want one of the two and should disable one of the two at the source unless they really don't care about VSpd at all and at that point there's really nothing to discuss. 🤪 I would say theoretically that if the RX sees a BaroAlt, it would disable its own internal BaroAlt reporting to prioritize what the user clearly wants, which is to use the external sensor.

There's no scheduling of telemetry transmission in ExpressLRS, it just continuously loops through the possible items and if there's something to send, it goes. There's no priority to anything so the only way to prioritize is to keep the queue as empty as possible.  We really don't want to start getting into adding metrics to prefer the sending of some items more frequently since that becomes a nightmare of every user wanting different priorities based on different setups. ExpressLRS is complicated enough without having to build your own prioritized telemetry cadence schema per model.

How often should an external GPS publish? 🤷‍♀️ It depends? It clogs the pipe so it is just a detriment to the primary telemetry purpose. Even once a second will have a big performance hit on the Vario operation because the GPS packet is so huge. Maybe this external GPS+Baro has its own config to address this? It is hard for me to answer because it is like you're asking me "I'd like to reduce the effectiveness of Vario RXes... how bad should it be?". I would say "not at all", but you design your thing in a way that best pleases you / is useful to the users you imagine. If that includes sending BaroAlt then we'd update ELRS to not send the RX's BaroAlt when it sees yours. If you send GPS and Vario, we'd send those as well as internal BaroAlt which is obviously a problem you wanted to address with this PR, but also not a great design performance-wise.

**Comment by mha1** [comment]
Sorry for digging this up again. One change I'd still like to do. Consider a GPS sending 0x02 packets and a Vario (e.g. ERx-V internal Vario) sending 0x09 packets. Alt will be discovered by EdgeTX twice but with the same name:
- 0x09 Alt delivering barometric altitude from Vario -> sensor "Alt"
- 0x02 Alt delivering GPS altitude (MSL) -> sensor "Alt"

Now consider defining a calculated sensor "distance" which calculates the slant range between home point (first valid GPS position) and the crafts position by using the crafts GPS position and a selectable sensor for the altitude of the craft. You'd have to select "Alt" in our case.

With both 0x02 and 0x09 altitudes listed as "Alt" the distance calculation picks the first "Alt" match it finds in the list of sensors. Depending on how the previous discovery populated the sensor list it will sometimes pick "Alt" (MSL), and sometimes "ALT" (baro altitude). Basically a random result.

My proposal is to assign both altitudes unique names so the distance calculation GUI allows selecting the correct altitude:
- 0x02 Alt -> "GAlt" for GPS altitude (MSL)
- 0x09 Alt -> "Alt" for barometric altitude (AGL)

**Comment by 3djc** [comment]
You can rename sensors

**Comment by mha1** [comment]
I'll take this as an objection. Would still be nice to discover them properly in the first place

**Pull request closed without merging**
