### PR TITLE
fix(yaml): Do not limit to static MPM protocol definitions

### LINKED ISSUE #4144: Could not save for pre-release multiprotocol
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I use pre-release multiprotocol, for example,FX/9630. I can change the setting for external module in model A, then I switch to model B, then switch back to model A, the configuration in model A is lost. If I use FX/860, the configuration is kept. Edgetx 2.8.5 seems no problem.

### Expected Behavior

Maybe edgetx 2.9 checks the multiprotocol and invalidate the protocol not defined in its header files, which prevents us to use latest multiprotocol version than the release version when 2.9 is built.

### Steps To Reproduce

Described in current behavior section

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #4144

### CODE REVIEW

**Comment by 3djc** [comment]
Colorlcd UI isn't handling it properly (yet ;))

image

**Comment by gagarinlg** [comment]
We either have to store the protocol name or display the ID, when we do not have a name.

**Comment by 3djc** [comment]
BW > all ?

image

;)

**Comment by raphaelcoeffic** [comment]
Screenshot 2023-10-01 at 15 37 09

**Comment by pfeerick** [comment]
Tried with internal and external MPM on 1.3.3.33 with a previously unlisted protocol,  TX16S, Zorro, X9D+2019 all seem to be working fine. If the protocol is not in the built-in list and the module is not present, the index number is shown instead, and you only lose the setting if you try to change it.

**Pull request merged**
