### PR TITLE
feat: new SF GV Adjust mode to copy source (instead of %) value

### LINKED ISSUE #5403: GV does not use correct value when used as a source
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When an SF is used to record a GV from another source, and then that GV is used as an Input source, the result is 1/10th of the original.
Ex: if Ele is -68, and recorded to GV1, then GV1 is used as a mixer replace source, it results in a value of -7 (6.8 rounded) being used, not -68.  Changing units/prec in GV settings will change the display value of the GV, but not the end result.

This has not been tested in radio, to see if behavior is different.

### Expected Behavior

Maintain the actual value.

Simple version of issue attached.  Change 'txt" to "etx"
[GV Replace Input.txt](https://github.com/user-attachments/files/16532465/GV.Replace.Input.txt)

### Steps To Reproduce

Use a SF to adjust a GV to a Source value.
Define the GV as an Input
Set up a mix replace line to use that GV Input as a source.

### Version

2.10.3

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

Win 11

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #5403 

- Companion strings changed to match firmware.
- STR_MIXSOURCE changed to add '(%)', language translations modified using STR_SOURCE string.
- STR_MIXSOURCERAW string added, language translations created by combining STR_SOURCE and STR_VALUE.

Language translations need to be checked.

### CODE REVIEW

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 Will be merged in seven days or when translations complete, whichever comes first. 

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU 

Can you check if the changes for your specific language look correct. You should be able to go to [Files changed](https://github.com/EdgeTX/edgetx/pull/5406/files) tab above, scroll down to the "translations" folder on the left side, and then pick your language file - the relevant lines will be highlighted. Let us know if there is "No change" or some change required.

**Comment by froqstar** [comment]
A screenshot of how this looks in the context of the screen would be really helpful.

**Comment by philmoz** [comment]
> A screenshot of how this looks in the context of the screen would be really helpful.

Posted in issue #5403

**Comment by zyren** [comment]
I checked the CN and TW translations in [Files changed](https://github.com/EdgeTX/edgetx/pull/5406/files) and they are absolutely correct

image
image

**Comment by robustini** [comment]
IT ok!

immagine

**Comment by ParkerEde** [comment]
DE:
#define TR_MIXSOURCERAW                "Quelle (Wert)"

**Comment by Eldenroot** [comment]
CZ:

#define TR_MIXSOURCERAW "Zdroj (hodnota)"

**Comment by ulfhedlund** [comment]
SE translation OK!

**Comment by HThuren** [comment]
DA translation also in top

**Comment by Pat6874** [comment]
FR
#define TR_MIXSOURCE "Source (%)"
#define TR_MIXSOURCERAW "Source (valeur)"

Le 8 août 2024, 11:41, à 11:41, Peter Feerick ***@***.***> a écrit:

**Comment by ajjjjjjjj** [comment]
PL OK.

**Comment by zandorsp** [comment]
PT ok

**Comment by ToshihiroMakuuchi** [comment]
JP: 
#define TR_MIXSOURCE "ソース (%)"
#define TR_MIXSOURCERAW "ソース (値)"

**Comment by zandorsp** [comment]
Ops, I'm sorry, change the PT to:
#define TR_MIXSOURCE                   "Fonte (%)"
#define TR_MIXSOURCERAW                "Fonte (valor)"

**Comment by Pat6874** [comment]
FR


#define TR_MIXSOURCE "Source (%)"


#define TR_MIXSOURCERAW "Source (valeur)"




Le 8 août 2024, 11:41, à 11:41, Peter Feerick ***@***.***> a écrit:

**Comment by pfeerick** [comment]
Something isn't quite right on the radio side in how the second parameter for `def` is being saved and read (and I don't think it is the bug in #5434 tripping me up)... I tried to sequentially pick each of the adjust types - so it **should** be CONSTANT, SOURCE, SOURCERAW, GVAR, INCDEC) ... but as you can see what was selected in the radio, what was read by Companion, and what the radio read back after a reboot (only a reboot of the radio - no changes by Companion), are all over the place. If I try setting in Companion... the model settings look correct in file, but the radio reads them wrong there also. 

yaml from radio, Companion read, radio as configured and after reboot
image

vs Companion

```yml
customFn:
  0:
    swtch: SA2
    func: ADJUST_GVAR
    def: 0,Cst,42,0
  1:
    swtch: SA2
    func: ADJUST_GVAR
    def: 1,Src,I0,0
  2:
    swtch: SA2
    func: ADJUST_GVAR
    def: 2,SrcRaw,I1,0
  3:
    swtch: SA2
    func: ADJUST_GVAR
    def: 2,GVar,gv(8),0
  4:
    swtch: SA2
    func: ADJUST_GVAR
    def: 3,IncDec,7,0
```

**Comment by pfeerick** [comment]
lol... five seconds too slow... 

```
diff --git a/radio/src/storage/yaml/yaml_datastructs_funcs.cpp b/radio/src/storage/yaml/yaml_datastructs_funcs.cpp
index b1d3b9e345..067c322eac 100644
--- a/radio/src/storage/yaml/yaml_datastructs_funcs.cpp
+++ b/radio/src/storage/yaml/yaml_datastructs_funcs.cpp
@@ -1470,7 +1470,7 @@ static const char* const _func_sound_lookup[] = {
 };
 
 static const char* const _adjust_gvar_mode_lookup[] = {
-  "Cst", "Src", "GVar", "IncDec"
+  "Cst", "Src", "SrcRaw", "GVar", "IncDec"
 };
 
 static void r_customFn(void* user, uint8_t* data, uint32_t bitoffs,
 ```

**Review by pfeerick — APPROVED** [review]
Both TX16S and T12MAX radio and companion side are good after that change.

**Comment by koaxheli** [comment]
In Companion 2.11.0, the GV --> SRC switches are not available for selection in the mixer simulation.
2 11 0-Companion

**Pull request merged**
