### PR TITLE
Hebrew radio translation 🇮🇱

### PR DESCRIPTION
**Pull request by stavfx**
Add Hebrew support, fonts and translations

image
image
image

### CODE REVIEW

**Comment by gagarinlg** [comment]
LVGL has even more RTL-Support. It should be possible to reverse the inputelement and description order automatically, depending on the language.

**Comment by stavfx** [comment]
Can we do that in a separate PR? 
This is a step in the right direction that people are happy to work with

**Comment by pfeerick** [comment]
That sounds fine with me... this is a start. My only concern would be the inclusion of the Arial font... isn't that a copyrighted font? i.e. belonging to the The Monotype Corporation?

**Comment by pfeerick** [comment]
That would be the goal - other than the font issue, this PR in its current form seems looks to be a good enough start, and we can then get some feedback as to what else is needed.

**Comment by pfeerick** [comment]
LGTM... assuming no build issues, and you guys are happy with the current state of this (given you're the native language guys, not me 🤭 ) I think this can get merged.

**Comment by pfeerick** [comment]
Did a couple of local builds to make sure everything is building properly, seems to be fine. I can see some strings still need translating, but that is to be expected. When you're happy with this PR, can you add 

```
addLanguage("he");
```

to around line 107 of `companion/src/firmwares/opentx/opentxinterface.h` (have a look at #3587 if you need a reference) so that Companion also knows about the Hebrew language setting.

**Comment by stavfx** [comment]
Replaced Arial font with [Arimo from Google](https://fonts.google.com/specimen/Arimo/about) (Apache 2.0 license).
Added `addLanguage("he");` as instructed. We are all set.

**Review by pfeerick — APPROVED** [review]

**Comment by stavfx** [comment]
Thanks for the support @pfeerick!

**Pull request merged**
