### PR TITLE
chore: remove support for binary storage format

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This PR removes in-radio support for binary storage format and related conversions. Following firmwares will be `YAML` only.

### CODE REVIEW

**Comment by froqstar** [comment]
So to migrate from OpenTX one first needs to flash EdgeTX<=2.8, and then the latest release, correct?

**Comment by raphaelcoeffic** [comment]
> So to migrate from OpenTX one first needs to flash EdgeTX<=2.8, and then the latest release, correct?

Yes, or you use Companion, which will retain compatibility to the binary formats and continue to support them.

**Comment by pfeerick** [comment]
Now is probably a good time to flip the EdgeTX version over to 2.9 as well? Not that I should have done it earlier... 😆

**Comment by gagarinlg** [comment]
> Now is probably a good time to flip the EdgeTX version over to 2.9 as well? Not that I should have done it earlier... 😆 And did you notice the PR number? 🤓

We can do it Microsoft style, we leave the version number for years and add a date code to it

**Comment by pfeerick** [comment]
Didn't you hear... they decided three years after positively stating that "Windows 11 will be the last version ever" that "Windows 12 is now being worked on" 🤦 ... but yeah, date code is certainly another way to do it...

**Comment by raphaelcoeffic** [comment]
> Now is probably a good time to flip the EdgeTX version over to 2.9 as well?

Ideally, this should be the first commit after forking a stable branch 🤓

**Pull request merged**
