### PR TITLE
feat(color): Remove splash screen and boot loader background, add version info

### LINKED ISSUE #638: Bootloader and Startup screen background
So we already started this with @raphaelcoeffic but stalled waiting for 2.5 UI rework

So here is preview
1. Startup screen
Splash
2. Bootloader
Bootloader

Do here is how to do:
1. Tile (535 bytes)
bkg_holes_tile
2. Full Mask (48kB)
bkg_holes_mask
3. Quarter Mask (12kB)
bkg_holes_mask_025

So to reduce mem usage trick is to get Quarter mask duplicate 3 times, rotate and position in right place
Should be 100% symmetrical. If not I'll replace it
@pfeerick @richardclli feasible?

### LINKED ISSUE #4134: Splash screen backround  ... must leave
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

screenshot_tx16s_23-09-29_06-04-28

Guys I know we use what we have but...
This bkg looks: outdated, ugly, incompatible with Eddie ... pick watever you want
It's like to buy new car and put old worn out tyres ...

### Describe the solution you'd like

As there was infinite discussion about new backround ie "I like, I dont like, maybe this maybe that" ...
Just make background PRIMARY3 (dark blue) like on our EdgeTX banner and it will look awesome.

Then disscusion can be continued ...

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Also display version and codename on splash screen.

Fixes #4134, resolves #638

### CODE REVIEW

**Comment by philmoz** [comment]
Moved the logo to the left on landscape and up on portrait for better balance.

landscape splash

portrait splash

**Comment by pfeerick** [comment]
If it's not a tagged version (i.e. not VERSION_TAG) can I also get the commit hash as a third line? Thus effectively it becomes 
BUILD_BRANCH (2.10.0) (as is shown now)
BULD_TYPE (PR4139/selfbuild/custom) (as is shown now)
BUILD_COMMIT (#1234567) (i.e. GIT_STR)

**Comment by philmoz** [comment]
landscape splash

portrait splash

**Comment by pfeerick** [comment]
@JimB40 Are we moving forward with this?

**Comment by philmoz** [comment]
One of the disadvantages of using a black background is it makes the backlight bleed a lot more obvious on my TX16S.

I don't know how common this is or if other radios are affected. My EL18 does not have any backlight bleed.

IMG_1691

**Comment by pfeerick** [comment]
I've not seen TX16S display quite that bad before (even considering cameras can sometimes make it seem worse than it looks to the eye)... just the expected poor black/white bleed across the whole screen because these are not OLED displays with good black/white contrast. I would be thinking the screws for the backlight/LCD stack have either been over-tightened, or it's pinched. I found it quite easy to do when doing things like adding the touch screen, replacing the LCD or case hardware.

**Comment by philmoz** [comment]
I tried loosening the screws; but it did not help. Did not pull the whole thing out to check seating though.

If mine is an unusual case that's ok - I was just concerned that if it was common then this PR could cause extra questions/issues to be raised.

**Comment by JimB40** [comment]
> @JimB40 Are we moving forward with this?

Apparently size matters in this case ...that's what she says, so if you won't come up with next codename longer than 200px just merge it.

**Comment by pfeerick** [comment]
We'll cross that bridge then if that happens... 🤣 I think we'll probably be fine though. Will be interesting to see what the feedback is as people start seeing the new screen (or don't if they have custom splash screens).

**Pull request merged**
