### PR TITLE
Jumper TPro V2

### PR DESCRIPTION
**Pull request by 3djc**
This brings support for Jumper T-Pro V2 (F4 processor, more switches, Oled screen)

This also brings two additionnal switches (pushing down the trim 'sticks') to the v1 Jumper T-Pro

This REQUIRES #2631

manual tests: https://github.com/EdgeTX/edgetx/actions/runs/4861350851

### CODE REVIEW

**Comment by gumileeev** [comment]
> manual tests: https://github.com/EdgeTX/edgetx/actions/runs/4849854905

Tell me, if I want to test this on a jumper t pro v2 - will the name of the program model be the same, that is, tpro-96f0547.bin, or should it be new? Which?

**Comment by 3djc** [comment]
I've left a compiled firmware in https://discord.com/channels/839849772864503828/1096211997575610479

**Comment by gumileeev** [comment]
> It REQUIRES deleting at least RADIO folder (maybe model too, unsure) coming from supplied firmware


I don't know, maybe I should unsubscribe elsewhere, but I don't know where to do it right. I installed the update, before that I deleted the radio folder.
On the stock program, 2 things bothered me:
1. Sometimes when I turned it on, I got an SD card error. (I have a good card, not stock, I previously used it without problems on t pro v1)
2. The clock behaves strangely every time, scenario 2:
A. When turned on, I see the time 00:00 (if you go to the clock settings, the date and time will be reset to 00:00). If I turn the device off and on again, I will see the set clock again, but they will lag behind.
b. When I turn it on, I see the time, but it always lags behind. The feeling that when you turn off the remote control - the time does not count.
After the update, I have not yet seen the SD card error, but the problem with the clock still remains.
Can I somehow disable the information that the version of the program is intended for testing?

**Comment by 3djc** [comment]
1. Sd card error should not exist in this firmware
2. I shared the issue with Jumper, but this is currently an holliday period in China, so no response yet

I have updated the firmware above to not include warning

**Comment by gumileeev** [comment]
> I have updated the firmware above to not include warning

Unfortunately, it was in the last file where you turned off the warning window - the EDGE IM screensaver began to appear only for a fraction of a second, and changing the screensaver duration setting does not affect the duration of the screensaver.
I took a video so you can see.
Also in the video you can clearly see how, when you turn it on for the first time after a long idle time, the time always starts showing from 00:00, and if you turn it on again, then the time is already shown different from 00:00. True, the time is still not correct, because. Apparently at the moment the device is turned off - time recording stops. I hope my observations are helpful. Thank you!
https://youtu.be/ti_nAF_qcfw

**Comment by 3djc** [comment]
Those errors, don't exist here, please ensure you deleted both RADIO and MODELS, and you dont use companion at all

**Comment by osleg** [comment]
I also noticed that sticks calibration is not being persistent, and it's reset to defaults together with the clock, could be related to the same issue as RTC.

**Comment by gagarinlg** [comment]
> I also noticed that sticks calibration is not being persistent, and it's reset to defaults together with the clock, could be related to the same issue as RTC.

No, those two are not related.

**Comment by pfeerick** [comment]
> I also noticed that sticks calibration is not being persistent, 

That is suggestive of a SD card issue again, as it's saved to the SD card (or should be).

**Comment by 3djc** [comment]
Again, not seing any of this here, and I have been testing this T-ProV2 a lot because of the RTC issue. Ensure:
- not reporting issue based on factory installed firmware,  it just is not right
- use only the firmware above, and delete MODELS and RADIO before running it for the first time
- never use Companion or import from another radio until #2621 is supported, as this firmware is based on a large scale rewrite
- if you have sd issues, replace supplied sd by quality one

We think we traced down the RTC clock issue to a hardware issue on the radio, workiing with Jumper to confirm it

**Comment by gumileeev** [comment]
> We think we traced down the RTC clock issue to a hardware issue on the radio, workiing with Jumper to confirm it

can this be fixed programmatically or with a soldering iron?
Will you tell us when you will receive confirmation?

**Comment by rotorman** [comment]
> can this be fixed programmatically or with a soldering iron?

It looks like this would be possible to fix with a soldering iron, although won't be a task for the faint of heart as likely pin 143 of the MCU needs to be elevated from the PCB and connected/bridged to neighbouring pin 144 for the RTC fix.

**Comment by osleg** [comment]
> Again, not seing any of this here, and I have been testing this T-ProV2 a lot because of the RTC issue. Ensure:
> 
>     * not reporting issue based on factory installed firmware,  it just is not right
> 
>     * use only the firmware above, and delete MODELS and RADIO before running it for the first time
> 
>     * never use Companion or import from another radio until [Switch & ADC refactor #2631](https://github.com/EdgeTX/edgetx/pull/2631) is supported, as this firmware is based on a large scale rewrite
> 
>     * if you have sd issues, replace supplied sd by quality one
> 
> 
> We think we traced down the RTC clock issue to a hardware issue on the radio, workiing with Jumper to confirm it

* Latest bin taken from GH Actions
* Formatted new SD card
* Not using companion or imports
* Brand new, freshly formatted class 10 SD

Created new model, it got stored to the SD as expected and all the values are persistent.

Which file stores calibration values? `RADIO/radio.yml`?

**Comment by gagarinlg** [comment]
Yes, the radio.yml files stores the calibration

**Comment by rotorman** [comment]
> Which file stores calibration values? `RADIO/radio.yml`?

YAML files can be opened and inspected with any std. text editor. If you are on Windows, then even basic Notepad will do (although NotePad++ would give better color coding of YAML). Just open the file with a text editor and look the content - you will easily be able to identify the sections holding the proportional channels calibration data.

**Comment by 3djc** [comment]
RTC issue has been confirmed as pure hardware issue  and cannot be fixed by software. Jumper will fix further unit produced, and people who already received one should contact point of sale for initiating a fix process

**Comment by Nack-RUS** [comment]
Hello! Thank you all for your hard work!
The radio T-Pro V2 cannot memorize any settings of the top switches SW3-SW6.
These settings are retained until the first power off. The next turn on the radio - and they disappear. i usse firmware from  [3djc].
Embedded (internal) ELRS is also not available.

**Comment by osleg** [comment]
> 

Try to reformat/change SD card, especially if you are using the one that came with it

**Comment by gumileeev** [comment]
> RTC issue has been confirmed as pure hardware issue and cannot be fixed by software. Jumper will fix further unit produced, and people who already received one should contact point of sale for initiating a fix process

If only they would make a photo manual so that everyone would understand exactly which leg to raise and where to solder 🤷 It seems fair 🤔

**Comment by 3djc** [comment]
You need specialised equipement to do it, cannot be safely done witrh just a soldering iron

**Comment by Nack-RUS** [comment]
.....
The radio T-Pro V2 cannot memorize any settings of the top switches SW3-SW6.
These settings are retained until the first power off. The next turn on the radio - and they disappear. i usse firmware from  [3djc].
Embedded (internal) ELRS is also not available.
........

I assign buttons to flight modes. modes are switched. But after turning off / on the SW3-SW6 buttons disappear from the settings and FM2-FM5 can no longer be turned on with the buttons. Also, if you set up logical functions with these buttons, the same thing happens. Somewhere in the definitions there is an inaccuracy.
SD formatted, it did not affect the problem.
Also, there is no option to select internal ELRS.

**Comment by rotorman** [comment]
> Embedded (internal) ELRS is also not available.

Keep in mind there are two places in EdgeTX code, where internal module type needs to be set. First is radio system wide settings, reached with a long press on the top-most left key. There you select the type of internal module installed. For internal ELRS, needs to be set to CRSF.
On the model settings, reached via short top-left key press, you can enable and disable the internal module usage for this particular model. There you need to set the internal RF also to CRSF to use it.

**Comment by Nack-RUS** [comment]
WhatsApp Image 2023-05-09 at 17 56 18
WhatsApp Image 2023-05-09 at 17 56 19


ELRS appears only as part of a multi-module among other protocols. Also, you can select CRSF on the external module. Neither the first nor the second is in my device. Therefore, the LUA script does not see the internal ELRS module.

**Comment by Nack-RUS** [comment]
on ELRS the question is removed. Thanks for the clarifications. I could not find the desired item in the basic settings of the radio module. I'm sorry for the inconvenience.

**Comment by Klabel** [comment]
I have the same problem after a thoughtless flashing. I may not have looked carefully, but I did not find the firmware to return everything. model t-pro v2 built-in elrs

**Comment by Izord** [comment]
> 
https://discord.com/channels/839849772864503828/1096211997575610479/1105449195390906408

Found this thanks to original poster

pin 143 and 144

**Comment by 3djc** [comment]
@Nack-RUS; SW3+ fixed
[TPROV2-PRODUCTION-10-5-23.zip](https://github.com/EdgeTX/edgetx/files/11439737/TPROV2-PRODUCTION-10-5-23.zip)

**Comment by Nack-RUS** [comment]
> @Nack-RUS; SW3+ fixed [TPROV2-PRODUCTION-10-5-23.zip](https://github.com/EdgeTX/edgetx/files/11439737/TPROV2-PRODUCTION-10-5-23.zip)


Very grateful!

**Comment by pfeerick** [comment]
When you do the calibration, make sure you don't press hard on the throttle for the downward position. If you can clear the warning simply by putting pressure on the stick to push it to the bottom, it's still calibration related. Otherwise, need to double check what is happening on the SYS -> HARDWARE -> Debug -> Anas screen and see *where* -100 physically is.

**Comment by 3djc** [comment]
Also check radio mode, if set incorectly, it will trigger this error

**Comment by Nack-RUS** [comment]
> Also check radio mode, if set incorectly, it will trigger this error (SYS/Radio setup last line)


I'm sorry. That's my fault. Understood.

**Comment by amobyJD** [comment]
> > @Nack-RUS; SW3+ fixed [TPROV2-PRODUCTION-10-5-23.zip](https://github.com/EdgeTX/edgetx/files/11439737/TPROV2-PRODUCTION-10-5-23.zip)
> 
> Very grateful!

did this fix you mirrored screen for the edgetx for tpro v2 ? I have the same issue .. I just got the controller, Im very much new and Im just trying it this controller out.

**Comment by Klabel** [comment]
> > > @Nack-RUS; SW3+ fixed [TPROV2-PRODUCTION-10-5-23.zip](https://github.com/EdgeTX/edgetx/files/11439737/TPROV2-PRODUCTION-10-5-23.zip)
> > 
> > 
> > Very grateful!
> 
> did this fix you mirrored screen for the edgetx for tpro v2 ? I have the same issue .. I just got the controller, Im very much new and Im just trying it this controller out.

the image is normal, but there is no crsf operation mode in the built-in transmitter menu

**Comment by gumileeev** [comment]
> SW3+ fixed
> [TPROV2-PRODUCTION-10-5-23.zip](https://github.com/EdgeTX/edgetx/files/11439737/TPROV2-PRODUCTION-10-5-23.zip)

Need to delete the RADIO and MODEL folder again? How can you transfer old models less painfully?

**Comment by 3djc** [comment]
This firmware is based on #2631 that is unfinished development. At this point in time I would avoid trying to import models, much much safer to recreate those

**Comment by amobyJD** [comment]
> > > > @Nack-RUS; SW3+ fixed [TPROV2-PRODUCTION-10-5-23.zip](https://github.com/EdgeTX/edgetx/files/11439737/TPROV2-PRODUCTION-10-5-23.zip)
> > > 
> > > 
> > > Very grateful!
> > 
> > 
> > did this fix you mirrored screen for the edgetx for tpro v2 ? I have the same issue .. I just got the controller, Im very much new and Im just trying it this controller out.
> 
> the image is normal, but there is no crsf operation mode in the built-in transmitter menu

yea about this I have flashed this bin file to my remote, and then after flashing, I changed the hardware internal RF from multi to csfr
346134163_1637836280016424_771024165513031842_n
and then crsf should be available in the model setup 
346103397_1076602997060228_7067610379579122229_n

i don't know if this what you're referring to. I'm new to all this.. haha

**Comment by pfeerick** [comment]
That is correct. Some transmitters (like the T-Pro) can have different internal RF, so rather than having multiple firmwares, you can set what the internal RF is on the radio. Then the internal RF option in model setup will be correct for your transmitter. And you use the external RF section in model setup if you install the nano module adapter onto the back of the radio and use a module with that.

**Comment by Nack-RUS** [comment]
Dear friends, thank you very much for the tip to fix the RTC reset hardware problem. Even with a manual from the microcontroller on hand, it would be difficult to guess that the reason is the incorrect connection of the output of the internal PDR supervisor. After resoldering PDR pin, the RTC is stopped resetting. Thank you!

**Comment by amobyJD** [comment]
> Dear friends, thank you very much for the tip to fix the RTC reset hardware problem. Even with a manual from the microcontroller on hand, it would be difficult to guess that the reason is the incorrect connection of the output of the internal PDR supervisor. After resoldering PDR pin, the RTC is stopped resetting. Thank you!

can you show me what you did fixing the RTC ?

**Comment by rotorman** [comment]
See EdgeTX Discord post: https://discord.com/channels/839849772864503828/1096211997575610479/1105449195390906408

**Comment by Izord** [comment]
> can you show me what you did fixing the RTC ?





 I used a magnifying glass, a soldering iron at 300C, and a 31 gauge insulin needle to pry the pin up while heating with the iron.  Then I pried it over to the other pin and did a bit of silver solder.    It's not pretty, but it works.  Jumper support has been very responsive to email.

**Comment by osleg** [comment]
Another option: phone camera with zoom, regular soldering iron, Japanese knife (you know the the really sharp one) and a needle

**Comment by tomy983** [comment]
Hi, I just received my t-pro V2 and was wondering why I had a 2.9.0 version of edgetx and found this PR. I'e not quite got what the issue is whith the RTC. Does it only affect the displayed time?

**Comment by osleg** [comment]
> Hi, I just received my t-pro V2 and was wondering why I had a 2.9.0 version of edgetx and found this PR. I'e not quite got what the issue is whith the RTC. Does it only affect the displayed time? 

yes, it only affects real time clock reset on poweroff.

> 	TBS agent lite, Model Locator (by RSSI) and WizardLoader crash the radio when I open them, elrsV3 works fine.

Some scripts depend on radio settings, or you might have problematic sd card. Or something else...

>  Do you think I should return the radio?

It's my first radio too, and while it has some issues I keep it, just applying fixes for everything that's broken.
The problem is not the radio itself tho, the problem is that it's not officially released and officially (yet) unsupported by edgetx radio

**Comment by osleg** [comment]
The stock update, iirc, is not functional.
You have to update to the version from this PR, I think @3djc posted it above. 

> no problem changing gimbals (any reasons?)

There are currently 2 known problems with the radio:
1. RTC pin is not routed correctly
2. Gimbals drift on temperature change

Basically, using radio for 10–15 minutes causes miscalibration because of heat, which returns to normal when it cools down.

If you see that you get that issue as well - contact jumper's support and they will send you new HAL sensors that (supposedly) fix the issue.

They also send a new motherboard if you fail to solder the RTC pin or a small present (antenna and elrs reciever) in case you solder it successfully

**Comment by YardoDEVS** [comment]
Hi people, I bought my radio at banggood. Has anyone had a chance for a refund from them?
Them told me to send them a video with the problem but I don't know how can I take it from the firmware posted by 3djc, either I don't know if the problem is visible at some kind of menu. I'm very dissapointed with this return policy and I can't understand why I should do the fixes myself in this radio...

**Comment by osleg** [comment]
>     * RTC-Bug - the link provided to discord does not work for me, i edn on the discord site telling me that i got lost. and from the pics here i'm not sure what needs to be done, so can anyone explain in detail what's the mission to accomplish?
> 
> 
> What i understood: the 2nd pin from the edge must be unsoldered/disconnected from pc: is this also possible by cutting the trace? (did that on other occasions, but idk if there's another trace/via below the chip.) then we connect it with the 1st pin on the corner. but should that pin also be unsoldered? sorry for the stupid question, but with the pics posted above i'm not sure.

You don't need to unsolder last pin. The problem is that 143 should be routed to power, instead it routed to ground. You can cut the trace, don't go too deep just to be sure, but all of those who reported back had no probs with cutting it.

You don't have to unsolder 144th pin, it routed to power and that's exactly what you need for 143.

So just cut -> blob-shortcut

**Comment by 3djc** [comment]
> * In @3djc latest firmware posted above it seems to crash (blinking ! on top left) when i scroll below the internal-rf sub-entries in hardware page. so it never shows the "external module" line, but instead the screen goes off/on, LED in powerbutton changes to blue and it's on start-screen with the blinking ! on top left corner.

You probably did not delete RADIO folder.

image

image

**Comment by smartinick** [comment]
> 

Thanks for making me understand - sounds like a easy job!

@3djc - Thanks for your reply as well - deleted the Radio folder, no more crash on the hardware page.

So one thing is the rtc issue, but the rest - does it sum up to cheap/faulty sd cards beeing shipped?
it looks like getting rid of it and placing clean files on a different card solves all the problems?
(and off course the firmware beeing developed here - Huge Thanks!

**Comment by rotorman** [comment]
Needing to delete the \RADIO folder has to do with EdgeTX for this radio being under development and thus not due to quality or hw issue.

**Comment by 3djc** [comment]
Put as draft because of the large rebase. Will re-issue it when adc branch has been merged

**Comment by smartinick** [comment]
When i want to configure Switch warnings, the menu only shows "A B " (Model / Setup Page, "S-Warning")
Consulting the edgetx wiki gave me no hint how to add additional buttons, so is it just me?
Or is it a feature of the current status of the v2 version?

Maybe i found a issue with the latest binary posted here?

**Comment by pfeerick** [comment]
Can repo. Congratulations, you found a bug! 🐛 😆

**Comment by 3djc** [comment]
> When i want to configure Switch warnings, the menu only shows "A B " (Model / Setup Page, "S-Warning") Consulting the edgetx wiki gave me no hint how to add additional buttons, so is it just me? Or is it a feature of the current status of the v2 version?
> 
> Maybe i found a issue with the latest binary posted here?

Set SE and SF as 2POS in SYS/Hardware ;)

**Comment by smartinick** [comment]
> > When i want to configure Switch warnings, the menu only shows "A B " (Model / Setup Page, "S-Warning") Consulting the edgetx wiki gave me no hint how to add additional buttons, so is it just me? Or is it a feature of the current status of the v2 version?
> > Maybe i found a issue with the latest binary posted here?
> 
> Set SE and SF as 2POS in SYS/Hardware ;)

Dann, another error between seat and Transmitter :)
Thanks for the hint, works like a Charm!

**Comment by 3djc** [comment]
Latest, if not greatest :D

[TProV2-PROD-02-06-23.zip](https://github.com/EdgeTX/edgetx/files/11635921/TProV2-PROD-02-06-23.zip)

**Comment by YardoDEVS** [comment]
A newbie question: how to create the latest ELRS firmware for the TX? for have the same version of a just bought RX. In other words... with the latest firmware posted by 3djc is there in youtube or other place any tutorial for newbies of how to binding a RX to the radio? I only find opentx tutorials of how to bind ELRS in opentx in my language (spanish) but I will go with EdgeTX anyway If I can do the setup.

And another question: When I launch ELRS setup from TX the radio stucks at loading screen. this can be because I have not deleted RADIO folder before launching the lua for ELRS setup? or can be my microsd card corrupted? when we should delete the RADIO folder, before or after writing the latest compilations of the 3djc firmwares?

Thanks in advance for you help!

**Comment by 3djc** [comment]
Please ask those types of question on the support discord: https://discord.gg/wF9wUKnZ6H

**Comment by tomy983** [comment]
Hi @YardoDEVS, also newbie here. 
> A newbie question: how to create the latest ELRS firmware for the TX? for have the same version of a just bought RX. In other words... with the latest firmware posted by 3djc is there in youtube or other place any tutorial for newbies of how to binding a RX to the radio? I only find opentx tutorials of how to bind ELRS in opentx in my language (spanish) but I will go with EdgeTX anyway If I can do the setup.
> 
Here is what I did for ELRS:
- Download ExpressLRS Configurator https://www.expresslrs.org/quick-start/installing-configurator/
- Select wanted release (first number I think has to match RX release, so for me I stayed on 2.5.2 because drone could not go higer), but if your drone Rx can go to version 3.x.x go for it...
- For Target I choose Jumper 2.4 GHz and device Jumper AION T-Pro 2400 TX
- Flashing method WIFI
- Options (where you also set binding phrase):
image
- Press BUILD, it will download some software for building and after a while it will pop up a folder with few files. For me, with my options, the file to choose is "Jumper_AION_2400_T-Pro_TX-2.5.2.bin"
- Go to the radio, hold menu button, pick from TOOLS menu ExpressLRS (if you have problems here like I did keep reading, will explain)
- Select WIFI connectivity and Enable WiFi.
- On your PC connect to WIFI named ExpressLRS (pass is "expresslrs") and in browser navigate to 10.0.0.1
- From there upload new firmware (for me "Jumper_AION_2400_T-Pro_TX-2.5.2.bin") with correct version and passphrase to the module
- On the model set the same passphrase as you did on the Tx
- Done.

> And another question: When I launch ELRS setup from TX the radio stucks at loading screen. this can be because I have not deleted RADIO folder before launching the lua for ELRS setup? or can be my microsd card corrupted? when we should delete the RADIO folder, before or after writing the latest compilations of the 3djc firmwares?
> 
I had some issues with Lua scripts, here is what I did:
- Remove SD and plug it into PC via adapter
- Back up whole SD content
- Format SD
- Copy files from your backup back to SD
- In SD navigate to SCRIPTS\TOOLS
- Delete everything in there
- Inside SCRIPTS\TOOLS folder only have this single freshly downloaded file https://github.com/ExpressLRS/ExpressLRS/blob/3.x.x-maintenance/src/lua/elrsV3.lua?raw=true (i know the files says V3 and my firmware version is 2.x.x but I think it is not relevant or not an issue)
- While you have the sd in the PC put your language pack in the SOUNDS folder (download it from https://github.com/EdgeTX/edgetx-sdcard-sounds/releases)
- Put back SD and it should work, forget about the others scrips they where in the SCRIPTS\TOOLS, they never worked for me and putting them back caused problems again. 

> Thanks in advance for you help!

Hope this helps.

Also, if you will be installing a new firmware in the radio (only FW compatibles are the ones in this conversation at present and also Jumper customer service will direct you here to 3djc releases) you will have to delete the RADIO and MODELS folders content in the SD card. This will "mess" up quite a few options in the radio and things might not work properly until you go trough the menus and put things as they where (protocolos, internal external transmitter, mode of sticks are just few I remember, but better to write everything down before you do).
For update procedures, the only one that I could do is the one called Migrate from OpenTX to EdgeTX (altough in this case not a migration..) and I followed the instructions found here: https://oscarliang.com/flash-edgetx/#How-to-Migrate-from-OpenTX-to-EdgeTX but basically:
- Copy the firmware .bin file for your radio to the FIRMWARE folder on the SD card.
- Eject Storage and unplug the USB cable
- Reboot and when prompted press any key
- Long press the menu button and go to SD card page and select FIRMWARE
- Press enter on the firmware you copied, select "Flash bootloader" and when finished power down the radio
- **Push roll AND yaw trim inwards** at the same time while re-powering up the radio (Bootloader mode)
-  select “Write Firmware” and then pick the firmware...
-
Good luck

**Comment by YardoDEVS** [comment]
> Hi @YardoDEVS, also newbie here.
> 
> > A newbie question: how to create the latest ELRS firmware for the TX? for have the same version of a just bought RX. In other words... with the latest firmware posted by 3djc is there in youtube or other place any tutorial for newbies of how to binding a RX to the radio? I only find opentx tutorials of how to bind ELRS in opentx in my language (spanish) but I will go with EdgeTX anyway If I can do the setup.
> 
> Here is what I did for ELRS:
> 
> * Download ExpressLRS Configurator https://www.expresslrs.org/quick-start/installing-configurator/
> * Select wanted release (first number I think has to match RX release, so for me I stayed on 2.5.2 because drone could not go higer), but if your drone Rx can go to version 3.x.x go for it...
> * For Target I choose Jumper 2.4 GHz and device Jumper AION T-Pro 2400 TX
> * Flashing method WIFI
> * Options (where you also set binding phrase):
>   image
> * Press BUILD, it will download some software for building and after a while it will pop up a folder with few files. For me, with my options, the file to choose is "Jumper_AION_2400_T-Pro_TX-2.5.2.bin"
> * Go to the radio, hold menu button, pick from TOOLS menu ExpressLRS (if you have problems here like I did keep reading, will explain)
> * Select WIFI connectivity and Enable WiFi.
> * On your PC connect to WIFI named ExpressLRS (pass is "expresslrs") and in browser navigate to 10.0.0.1
> * From there upload new firmware (for me "Jumper_AION_2400_T-Pro_TX-2.5.2.bin") with correct version and passphrase to the module
> * On the model set the same passphrase as you did on the Tx
> * Done.
> 
> > And another question: When I launch ELRS setup from TX the radio stucks at loading screen. this can be because I have not deleted RADIO folder before launching the lua for ELRS setup? or can be my microsd card corrupted? when we should delete the RADIO folder, before or after writing the latest compilations of the 3djc firmwares?
> 
> I had some issues with Lua scripts, here is what I did:
> 
> * Remove SD and plug it into PC via adapter
> * Back up whole SD content
> * Format SD
> * Copy files from your backup back to SD
> * In SD navigate to SCRIPTS\TOOLS
> * Delete everything in there
> * Inside SCRIPTS\TOOLS folder only have this single freshly downloaded file https://github.com/ExpressLRS/ExpressLRS/blob/3.x.x-maintenance/src/lua/elrsV3.lua?raw=true (i know the files says V3 and my firmware version is 2.x.x but I think it is not relevant or not an issue)
> * While you have the sd in the PC put your language pack in the SOUNDS folder (download it from https://github.com/EdgeTX/edgetx-sdcard-sounds/releases)
> * Put back SD and it should work, forget about the others scrips they where in the SCRIPTS\TOOLS, they never worked for me and putting them back caused problems again.
> 
> > Thanks in advance for you help!
> 
> Hope this helps.
> 
> Also, if you will be installing a new firmware in the radio (only FW compatibles are the ones in this conversation at present and also Jumper customer service will direct you here to 3djc releases) you will have to delete the RADIO and MODELS folders content in the SD card. This will "mess" up quite a few options in the radio and things might not work properly until you go trough the menus and put things as they where (protocolos, internal external transmitter, mode of sticks are just few I remember, but better to write everything down before you do). For update procedures, the only one that I could do is the one called Migrate from OpenTX to EdgeTX (altough in this case not a migration..) and I followed the instructions found here: https://oscarliang.com/flash-edgetx/#How-to-Migrate-from-OpenTX-to-EdgeTX but basically:
> 
> * Copy the firmware .bin file for your radio to the FIRMWARE folder on the SD card.
> * Eject Storage and unplug the USB cable
> * Reboot and when prompted press any key
> * Long press the menu button and go to SD card page and select FIRMWARE
> * Press enter on the firmware you copied, select "Flash bootloader" and when finished power down the radio
> * **Push roll AND yaw trim inwards** at the same time while re-powering up the radio (Bootloader mode)
> * select “Write Firmware” and then pick the firmware...
> 
> Good luck

Thanks so much tomy983!

**Comment by YardoDEVS** [comment]
Only one more question @tomy983 the first firmware or when you say "flash bootloader" here I should write the elrs3.2.1 for jumper-t-pro tx 2400 isn't? and the last step is write the latest @3djc firmware at this post? Sorry but I can't understand these last steps. Thanks in advance!

**Comment by ac0815** [comment]
> Only one more question @tomy983 the first firmware or when you say "flash bootloader" here I should write the elrs3.2.1 for jumper-t-pro tx 2400 isn't? and the last step is write the latest @3djc firmware at this post? Sorry but I can't understand these last steps. Thanks in advance!

Flash bootloader is done in the tpro Menu/Display, you flash the tpro Firmware File from SD Card.
After the restart (Holding the 2 Buttons as States above) you flash the SAME File again (but as Firmware, not only bootloader)

**Comment by YardoDEVS** [comment]
Owww Ok thanks @ac0815

**Comment by YardoDEVS** [comment]
I have launched lua for WiFi ELRS firmware upload following the steps that posted @tomy983 but it takes more than 5 minutes and the screen it still showing:
Loading...

The end of the line shows an empty check mark box and nothing happens... Can be this problem of the microsd that comes with the Radio or what can I doing wrong?

The radio boot and firmware is updated to the latest posted by @3djc

**Comment by PavanDendi** [comment]
Hi all, when connected to USB as a joystick, none of the buttons are being reported.  I get the gimbals and pots as axes, but the shoulder buttons, toggles, and 3-way switches don't register as button presses.  I have tried updating to the latest firmware in this thread, and I can't find any settings that seem to help/work.  Changing the USB joystick mode from Classic to Advanced seems to break joystick functionality so not even the axes get reported.

I can set the buttons to report as axes, and that seems to work, but I don't know if all sims would support assigning an axis for a keystroke.  It seems like the USB joystick configuration for the tpro v2 is not correct.

**Comment by gagarinlg** [comment]
You have to assign the switches to channels. Channels above a certain number are reported as switches to the PC. There is no fixed gimbal/pot/switch assignment to specific joystick inputs. You have to do it manually.

**Comment by PavanDendi** [comment]
> You have to assign the switches to channels. Channels above a certain number are reported as switches to the PC. There is no fixed gimbal/pot/switch assignment to specific joystick inputs. You have to do it manually.

Ah, thanks!  My other radios worked out of the box by default.  Sorry for the rookie question 😅

**Comment by PavanDendi** [comment]
Also, my controller does not seem to have any issues with the RTC.  The time did reset when I flashed firmware, but I think that was caused by flashing the V1 firmware before I was aware of this thread.  The clock has been behaving properly for the past 4 days now, so I might have a newer hardware revision.  I ordered from AliExpress from seller "XDRC Store" on May 26.

Let me know if there's anything I can do to check if it's a new hw rev

**Comment by pfeerick** [comment]
Externally I don't think so, other than the time still tracking when the radio is off, and RTC the battery not going flat in about six days. If you open the radio up, you'll most likely find some version of the mod shown here done https://github.com/EdgeTX/edgetx/pull/3554#issuecomment-1552262063, or possibly different PCB routing if they've done a new PCB revision and gone through all the old boards.

**Comment by PavanDendi** [comment]
Yeah, it looks like it's the same board, but they are doing the mod manually before shipping out.
jumper tpro board

**Comment by 3djc** [comment]
Superseeded by #3718

**Comment by infectedfpv** [comment]
Hi there guys, I´m new here and knowing all the bugs the Jumper t pro v2 has so i pulled the trigger and i bought from this seller. https://www.aliexpress.com/item/1005005292421931.html?spm=a2g0o.order_list.order_list_main.17.ad061802WYSFIk&gatewayAdapt=4itemAdapt

it came with no problem on RTC battery.. so maube its a new version?
WhatsApp Image 2023-06-29 at 14 41 04

WhatsApp Image 2023-06-29 at 14 40 46

**Comment by gagarinlg** [comment]
They called back the radios and modified the mainboards. Open it and see for two shorted pins on the MCU

**Comment by infectedfpv** [comment]
> They called back the radios and modified the mainboards. Open it and see for two shorted pins on the MCU

Ok here are the pictures, two shorted pins already made from factory.
WhatsApp Image 2023-06-29 at 15 29 25
WhatsApp Image 2023-06-29 at 15 29 24

**Comment by smartinick** [comment]
To all future Readers: don't open it to find out if yours is affected, turn it on, check your rtc batt voltage (mine gave a warning when turning on).
Leave it on, your clock will show 00:01 after one minute.
Turn it off, wait some 10 seconds, turn it on again, does the clock start at 00:00 or 00:01?

In case of low batt, change the batt, you have to open it, so check the PCB for the fix.
If no low rtc batt, and it keeps the time when turned off/on, you are fine. No need to waste time opening it.
If it looses the time, you are affected by the rtc issue.

**Comment by tomy983** [comment]
> In case of low batt, change the batt, you have to open it, so check the PCB for the fix.
If no low rtc batt, and it keeps the time when turned off/on, you are fine. No need to waste time opening it.
If it looses the time, you are affected by the rtc issue.

The RTC battery is a CR1220, in case you have to change it (I just had to open the radio to find out...)

**Comment by pfeerick** [comment]
For future reference, this was replaced by https://github.com/EdgeTX/edgetx/pull/3718

**Comment by daenielmojica** [comment]
> I have launched lua for WiFi ELRS firmware upload following the steps that posted @tomy983 but it takes more than 5 minutes and the screen is still showing: Loading...
> 
> The end of the line shows an empty check mark box and nothing happens... Can be this problem of the microsd that comes with the Radio or what can I be doing wrong?
> 
> The radio boot and firmware is updated to the latest posted by @3djc
> 
> EDIT: Just updated the ELRS firmware, all working, all I have to do is setting the RF mode and RF model too


Hello, Can you teach me how you fix the stuck in loading

**Comment by 3djc** [comment]
Lastest 3.3.0 official ELRS release improves internal module of those radio to support 1.87Mbps

**Comment by daenielmojica** [comment]
> > Hello, Can you teach me how you fix the stuck in loading
> 
> Do you mean for the ELRS Lua script/tool? This _typically_ only comes up when you don't have the ELRS RF turned on, or the serial baud rate is set too high. From what the earlier commenter said, updating the ELRS firmware using ELRS Configurator worked for them - which makes sense that it _could_ misbehave somewhat, as my unit came with an older ELRS firmware.

I'm still stuck in loading after downloading the lua script

**Comment by 3djc** [comment]
> > > Hello, Can you teach me how you fix the stuck in loading
> > 
> > 
> > Do you mean for the ELRS Lua script/tool? This _typically_ only comes up when you don't have the ELRS RF turned on, or the serial baud rate is set too high. From what the earlier commenter said, updating the ELRS firmware using ELRS Configurator worked for them - which makes sense that it _could_ misbehave somewhat, as my unit came with an older ELRS firmware.
> 
> I'm still stuck in loading after downloading the lua script

Not the right place for this, please use discord support for that

**Pull request closed without merging**
