### PR TITLE
Save models list after changing a model name

### LINKED ISSUE #1079: models.yml not updating after naming model
When you rename a model, models.yml is not updating the name field, so the model just shows as MODELXX in the selection screen.

Also, I don't know if this is actually intended behavior, but when I create a model and delete it, it does not delete the model yml file.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #1079

### CODE REVIEW

**Comment by pfeerick** [comment]
Is it possible to also get the names populated during initial conversion... as after a fresh start with no yml files... this is the initial `models.yml` state... and the name for a model doesn't seem to get populated until it is renamed. 

```yml
- Models
  - filename: model1.yml
    name: 
  - filename: model2.yml
    name: 
  - filename: model3.yml
    name: 
  - filename: model4.yml
    name: 
  - filename: model5.yml
    name: 
```

**Comment by raphaelcoeffic** [comment]
@pfeerick sure, we can try to smash another as well in the same PR.

**Comment by pfeerick** [comment]
And a third issue while you're playing in this space...  model names in actual model files are strings... i.e. double-quoted, whereas in `models.yml` they are not, which then means only the first name is shown in the model select list if there is a space in the name ;)

**Comment by raphaelcoeffic** [comment]
@pfeerick both done 😊

**Comment by pfeerick** [comment]
Right, so I though the kitchen sink BIN model collection and radio config at it... and 

- initial conversion worked perfect... 

```yml
- "Multirotor"
  - filename: "model1.yml"
    name: "fPV 250"
  - filename: "model2.yml"
    name: "Ladybird"
  - filename: "model3.yml"
    name: "Syma X5C"
  - filename: "model4.yml"
    name: "Cheerson CX10"
  - filename: "model5.yml"
    name: "JJRC H20"
  - filename: "model6.yml"
    name: "H Frame"
  - filename: "model7.yml"
    name: "Big Tricopter"
  - filename: "model8.yml"
    name: "Mini Tricopter"
  - filename: "model22.yml"
    name: "MODEL23"
  - filename: "model27.yml"
    name: "MODEL28"
  - filename: "model30.yml"
    name: "MODEL31"
  - filename: "model31.yml"
    name: "0uDEL32"
  - filename: "model32.yml"
    name: "MODEL33"
- "Fixed Wing"
  - filename: "model9.yml"
    name: "Skysurfer"
  - filename: "model10.yml"
    name: "Skyhunter"
  - filename: "model11.yml"
    name: "ZOHD Dart 250G"
- "Helicopter"
  - filename: "model12.yml"
    name: "Blade MCX"
  - filename: "model13.yml"
    name: "Super CP"
- "Other"
  - filename: "model14.yml"
    name: "Simulator"
  - filename: "model15.yml"
    name: "Simple 4 Chan"
  - filename: "model16.yml"
    name: "Noise thing"
  - filename: "model17.yml"
    name: "Cheerson CX20"
  - filename: "model18.yml"
    name: "FrSky CloneRX"
  - filename: "model19.yml"
    name: "Testing"
  - filename: "model26.yml"
    name: "MODEL27"
```

- Model name is being updated correctly

- Model names with spaces are being shown correctly

Would you like to resolve one more teensy issue? 😆 Um... ok... double quotes are ... new ... and where did my `Wing` go? 😁 

image

**Comment by raphaelcoeffic** [comment]
> Would you like to resolve one more teensy issue? 😆 Um... ok... double quotes are ... new ... and where did my Wing go? 😁

Fixed 😊 And I took the chance to verify the models list passes YaML linters.

**Review by pfeerick — APPROVED** [review]
That fixed it :) Seems to be working fine now, and it's always to have lint-compatible code ;)

**Pull request merged**
