### PR TITLE
fix(usart): possible endless loop in case some error flag is set but RXNE is not

### LINKED ISSUE #3482: Emergency Mode after entering ELRS Lua
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter Firmware

### Current Behavior

After flashing latest nightly build (01829a1) radio powers and behaves as usual, accessing expresslrs Lua script OR tbs agent lite and turning Jr bay module wifi on crashes the radio into emergency Mode.

Power cycling and try again it does it again, but it may take more or less time until emergency mode but never gets really into wifi mode

Ruled out:
module shorting (it behaves similarly with several modules 
Bad battery 
Sd card

Downgrading to release v2.8.2 03e80fb everything seems to run ok (same 2.8 sd card, same files) 

### Expected Behavior

Turn on, do things without crash 

### Steps To Reproduce

Flash latest nightly
Sd card already on 2.8
Turn on
Access exlrs lua scrip (or tbs agent lite) 
Turn WiFi on 

EMERGENCY MODE 

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

_No response_

### Anything else?

Tx16s v1 (very first version) with updated v4 gimbals

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #3482

Summary of changes:

### CODE REVIEW

**Comment by richardclli** [comment]
The crash gone when I revert the changes in the usart driver.

And I figured out that the pulse driver changes is missing when merging the PR, not sure if this is needed.

**Comment by pfeerick** [comment]
> And I figured out that the pulse driver changes is missing when merging the PR, not sure if this is needed.

You might want to refer to https://github.com/EdgeTX/edgetx/pull/3419

**Comment by mha1** [comment]
@richardclli Hey Richard, please don't commit the change you made to radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp. I reverted to the pre #3882 version of the pulse driver with #3419 to fix #3418. You'd effectively go back to a non working version of the pulse drivers for some radios, like the X10e. Thanks - Michael

**Comment by mha1** [comment]
@richardclli ... and flashing internal and external modules, especially external MPM on the X10e needs to be retested before merging the changes you made to the USART driver as this was the trigger for the changes Raphael made in #3382.

**Comment by richardclli** [comment]
> @richardclli Hey Richard, please don't commit the change you made to radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp. I reverted to the pre #3382 version of the PPM driver with #3419 to fix #3418. You'd effectively go back to a non working version of the PPM driver for some radios, like the X10e. Thanks - Michael

Got it, I will remove it in this PR.

**Comment by richardclli** [comment]
> @richardclli ... and flashing internal and external modules, especially external MPM on the X10e needs to be retested before merging the changes you made to the USART driver as this was the trigger for the changes Raphael made in #3382.

And one change in #3382 will cause the emergency mode with ELRS 5.25M running the ExpressLRS LUA script.

**Comment by richardclli** [comment]
@raphaelcoeffic 

The implementation in 2.8 is like this:

  while (status & (USART_FLAG_RXNE | USART_FLAG_ERRORS)) {
    uint8_t data = TELEMETRY_USART->DR;
    if (status & USART_FLAG_ERRORS) {
      telemetryErrors++;
    }
    else {
      telemetryNoDMAFifo.push(data);
#if defined(LUA)
      if (telemetryProtocol == PROTOCOL_TELEMETRY_FRSKY_SPORT) {
        static uint8_t prevdata;
        if (prevdata == 0x7E && outputTelemetryBuffer.size > 0 && outputTelemetryBuffer.destination == TELEMETRY_ENDPOINT_SPORT && data == outputTelemetryBuffer.sport.physicalId) {
          sportSendBuffer(outputTelemetryBuffer.data + 1, outputTelemetryBuffer.size - 1);
        }
        prevdata = data;
      }
#endif
    }
    status = TELEMETRY_USART->SR;
  }

which is the same as the original implementation, not sure why you change it in #3382

**Comment by pfeerick** [comment]
@richardclli Please don't copy random bits of code in without at least saying what file they are in so we don't have to go searching for them. Better still, link the code like I just did when I edited the message. 

Did you realise you pasted a code snipped from `telemetry_driver.cpp` for 2.8 - which is not actually modified in #3382 ???  - and also no longer exists it seems.

**Comment by richardclli** [comment]
> 

It is not exists because it is replaced by the new serial driver, which unifies all the handling of the serial code.  However, the logic should be similar unless the problem already exists in v2.8 and try to fix it in v2.9.

**Comment by pfeerick** [comment]
I usually use this because I'm highlighting snippets of code:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

But it also looks like there is a keyboard shortcut if you just want to link to a file generally:
https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files

**Comment by richardclli** [comment]
@raphaelcoeffic Please take a look, thanks.

**Comment by raphaelcoeffic** [comment]
Ok guys, the point is the following:
- when an error is detected, that does not mean that the byte just read from the register is not OK. This change comes from my journey studying how the STM32 HAL code handles the case,
- I believe ELRS LUA crashes for a different reason. What happens here is that we are possibly masking the issue, not fixing it.

**Comment by raphaelcoeffic** [comment]
Ok, bottom line is:
- crash was not related to ELRS LUA at all,
- but rather an endless loop in the USART ISR (see [53f172b](https://github.com/EdgeTX/edgetx/pull/3486/commits/53f172bb0703156db1cedaeb381bdbb88b8a9e9d))
- it could happen with any external module in case a USART error flag is set without `RXNE` set at the same time.

**Comment by richardclli** [comment]
@raphaelcoeffic This fixes the problem.  No crash anymore, thanks.

**Pull request merged**
