### PR TITLE
chore: more OTX to ETX housekeeping

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
- rename opentx and helper files
- update translation reference to OTX for upgrade

Although it affects significant number of files, should be unobtrusive enough to not break other PRs. Next up is changing over to `#PRAGMA`...

### CODE REVIEW

**Comment by philmoz** [comment]
Curious as to what this means: '- LVGL font code doesn't like pragma,'

**Comment by pfeerick** [comment]
You could try it yourself :-P And witness all the noise from the compiler about pragma being used in the font headers.

**Comment by philmoz** [comment]
I changed lv_conf.h and had not issues?

**Comment by pfeerick** [comment]
Wasn't that changed in this PR, so shouldn't be one of the listed exceptions?

I'm referring to these include style guard defines... in the LVGL **font code** c files... 

```
#ifndef LV_FONT_ARIMO_HE_16
#define LV_FONT_ARIMO_HE_16 1
#endif

#if LV_FONT_ARIMO_HE_16
///blah
#endif /*#if LV_FONT_ARIMO_HE_16*/
```

**Comment by philmoz** [comment]
I didn't consider those as they are auto-generated by the lv_font_conv tool - hence my confusion.

**Comment by pfeerick** [comment]
Sorry about that! Yeah, and no apparent options to change that formatting, so it got added to the ignore list. This is probably done for now anyway, as I'm not touching Companion side at all (yet?!).

**Pull request merged**
