### PR TITLE
Fix theme editor

### LINKED ISSUE #1064: Leaving Color theme editor with RTN does not show the yes(no dialog properly
RTN is misbaving here: RTN-down shows the save dalog, RTN-release dismissis it without a chance to select the "Enter" option immediately.

Tested on simulator.

### PR DESCRIPTION
**Pull request by kevinkoenig**
Please note that pull requests are NOT an appropriate way to ask questions or support.

Fixes #1064 

Summary of changes:

1. Fix KEY_EXIT processing when theme changed
2. Also fixes some color issues on ListBox()
3. Fixes various issues with PreviewWindow()
4. theme file structure implementation to match #897 
5. Sort theme names
6. changed touch handling on Theme List.  You now need to long-press to bring up the menu.
7. Added more controls to PreviewWindow()

### CODE REVIEW

**Comment by pfeerick** [comment]
Conversion script is ready in theme directory. And I'll branch the themes directory when this is merged (for v2.6) so that 2.5 themes are preserved for compatibility.

**Comment by pfeerick** [comment]
Way to bury the lead... you implemented one or two things I didn't think we'd see until 2.7... nice! :) I won't ruin the surprise 😁 

Overall this looks great. Just a couple of niggles (since you mentioned NV14 😁), and something to think about, but is no means required.

NV14 tweaks:
- In screens settings, move the logo image over a little to the left
- In the radio -> themes listview, move the name and author text down a few pixels
- In the edit theme, and edit colour screens, make the header buttons taller. NV14 is touch only, and the edges are particualry hard to touch, so taller buttons making the possible touch area further away from the screen edge is better :)

image
image
image
image


And the thing to *think about* is in relation to trying to make things more responsive... can we load the logo image *after* building the UI (in both screen settings, and radio->theme editor)? i.e. have a "Loading image..." placeholder, and then after x ms (similar to the image preview carousel) it then loads the image? Thus the UI is responsive right away, and the delay needed to load the image will be barely noticeable. i.e. you could move from entry to entry in the list without any delay as long as you do it within that delay period. If you think that is going to lead to more problems, or is impractical, please say so! :)

**Comment by kevinkoenig** [comment]
made all suggested updates, except delaying loading of bitmaps.  I will do that after the merge.  don't want to mix and match items

**Review by pfeerick — APPROVED** [review]
Agreed... "performance enhancers" can be covered in another PR. Latest changes have improved NV14 experience... but the NV14 still works best in combination with hat trim RTN+ENT.

**Pull request merged**
