### PR TITLE
fix(qx7-access): isrm sub-protocol

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by pfeerick** [comment]
This is already in 2.8, but I'll still merge this into 2.7 in case we do end up with a maintenance release.

**Comment by rburrow87** [comment]
Adding "OFF" seems to have messed up the FrSky X12 (and probably X10). Now OFF shows the ACCESS items, ACCESS shows the D16 items, etc. But that did fix it for the X9D+2019.

(excuse the picture of a screen)
IMG_2216

**Comment by pfeerick** [comment]
oh, interesting... so it might need a colorlcd define... thanks for the heads up... will check that out later today.

**Comment by pfeerick** [comment]
Ok, this should sort that out... I can see where it went wrong before now... colorlcd has two choice dropdowns, so didn't need doesn't need `OFF`, but B&W does, which is where it went wrong before.

**Comment by rburrow87** [comment]
That seems to have fixed it! I noticed I can't scroll to LR12 on the X12S ISRM or X9D+2019, but that's probably a separate issue? Even I could, I have no LR12 stuff to verify function with.

**Comment by pfeerick** [comment]
lol... I couldn't either... I wasn't actually sure if that was right or wrong so I was hoping you'd say something. Funnily enough... I think I *might* have grand total of one LR receiver in my own frsky D assortment (got some of the V series stuff also)... However, looking at OpenTX Companion and Simulator for reference, it seems like that is correct - only the ACCESS and D16 options are visible for the X9D+2019 and 10 Express/ACCESS ... so it looks like I can backport this to 2.7 also to wrap that up for now. Ideally changes should be made it so that the two versions of the list aren't needed... but that is a problem for another day.

**Comment by rburrow87** [comment]
Now that you mentioned that I did a little searching, and I don't think LR12 should be there for ISRM either. Seems to be an XJT thing. 🙃

Speaking of which, I wonder if internal XJT on the ACCST version of these radios need the same setup?

**Comment by raphaelcoeffic** [comment]
The odd thing is probably that the sub-proto numbers do not mean the same thing on the different type of ISRMs. This is something we should look into. “OFF” is clearly not needed in either implementation.

**Comment by pfeerick** [comment]
@rburrow87 Um... you have point there... suppose could fix that also before someone points it out (who would have thunk it... pre-emptive bug fixing!)... 😆 As well as having no "OFF" since I don't think that counts as a protocol... 🤣

**Comment by raphaelcoeffic** [comment]
@pfeerick the ugly point here is:

- **colorlcd** displays the module directly: `STR_ISRM_RF_PROTOCOLS[subType]`

https://github.com/EdgeTX/edgetx/blob/67f008760bd84e2dda88ee3455c05bd507520a40/radio/src/gui/colorlcd/model_setup.cpp#L672-L683

- **128x64** displays the module subType `+1`: `STR_ISRM_RF_PROTOCOLS[subType + 1]`

https://github.com/EdgeTX/edgetx/blob/67f008760bd84e2dda88ee3455c05bd507520a40/radio/src/gui/128x64/model_setup.cpp#L972-L973

- **212x64**  displays the module subType `+1`: `STR_ISRM_RF_PROTOCOLS[subType + 1]`

https://github.com/EdgeTX/edgetx/blob/67f008760bd84e2dda88ee3455c05bd507520a40/radio/src/gui/212x64/model_setup.cpp#L913-L928

So, instead of allowing this madness by defining `STR_ISRM_RF_PROTOCOLS` depending on whether the UI uses `+1` or not, we should rather remove this `+1` where used. I don't think it makes **any** sense.

**Comment by pfeerick** [comment]
:vomit: it's actually worse than that... it's *just* the fricking 212x64 when **_not_** the `INTERNAL_MODULE_PXX1` that is really screwing it all up... if it wasn't for that... wouldn't need "OFF" in the list... for XJT and ISRM protocols... I've working through that now... stay tuned ;)

**Comment by pfeerick** [comment]
@raphaelcoeffic OK, I admit defeat... Just one teensy weeny issue... I was able to remove it from all the radios... part of it was simpler than I thought it would be... but now now I just can't get it to let me set the ISRM subType ... it's damn annoying as the 
```
else if (isModuleXJT(INTERNAL_MODULE))
```

block immediately before is working,,, but the 

```
else if (isModulePXX2(INTERNAL_MODULE))
```
just never seems to run... even though the exact same check done when trying to TRACE it down fire... 

If you could put me out of my misery that would be great, no rush... I'm off the bed now. 😆 

It also looks like we could almost do away with `MODULE_SUBTYPE_PXX1_OFF` also?

https://github.com/EdgeTX/edgetx/tree/lets-finally-end-ISRM-madness

**Comment by raphaelcoeffic** [comment]
@pfeerick I think your branch is missing this:
Screenshot 2022-08-04 at 12 48 21

**Comment by pfeerick** [comment]
Ah yes... that would explain it... I'll test it on hardware and if everything works will do some code formatting and open a PR for that. Thank you sensei!

**Pull request merged**
