### PR TITLE
Added Lua constants for logical switch and special/custom functions

### PR DESCRIPTION
**Pull request by jfrickmann**
See issue #1020

### CODE REVIEW

**Comment by lshems** [comment]
Nice. Do the references also make sense now, or not yet.

Source numbers etc?

**Comment by wimalopaan** [comment]
Thank you very much!

**Comment by jfrickmann** [comment]
> Nice. Do the references also make sense now, or not yet.
> 
> Source numbers etc?

You can see exactly what I have done under "Files changed" above. I have simply made the constants that determine the types of logical switch function and special function types available to Lua, under the exact same name as they have in the C++ code.

As for the source numbers, it's easy for switches (see #1154) but for value sources it's still the same old `getFiledInfo` and `getValue` crap...

**Comment by wimalopaan** [comment]
Thank you for your work!!!

Is this going to land in 2.6?

**Comment by pfeerick** [comment]
Given `firmware-size` suggests around 776 bytes difference in firmware size between main and this PR for the X9D+2019... you have can have it... :grin:

**Comment by pfeerick** [comment]
Two questions before merging this:
- Is it worth shortening the names to get back a little flash memory, or is that making them too obtuse? i.e. `LS_FUNC_` => `LSF_`, `FUNC_` => `F_`. It brings down the character count from 652 to 504, so will probably drop the firmware size increase similarly. 
- Do we care about `FUNC_RESERVE5`? I know it and `FUNC_RESERVE4` exist but I'm not quite sure what their purpose is, other than possibly reserved space the data constants or placeholders when things like lua or audio are disabled?

**Comment by wimalopaan** [comment]
Do we have any flash shortage on tiny radios? Like jpt12 oder tlite? 
If it is only a flash concern and not a RAM concern then I would like to have the long names.

**Comment by wimalopaan** [comment]
Ok, then I have to adapt my lua-skripts ...
but, well, it is ok for me ... lets stabilze now ;-)

**Comment by pfeerick** [comment]
Yes, space is starting to get of concern for some B&W targets (which is the reason for the RLE compression PR for the graphics was done a couple weeks back to get back space... there is ample space _for now_... but it's better to be frugal now so we can putt of cutting the cord as long as possible). 

Don't you just hate 'smart' compilers... it's not following normal rule of thumb re size increase. For a T-Lite, the following are the firmware sizes for current main, and this pr (once rebased on main) for the first commit, seccond commit, and the following diff, which restores the original naming). It looks like the compiler must be recognising that the same name is being used twice, so as soon as you use a 'shorter' name for the constant itself, it uses up more space. So it looks like you can have your long constants if there are no objections?! Sorry for the extra work :-O

```
main:      482400
pr 1:      483256
pr 2:      483328
pr diff:   483216
```

```diff
diff --git a/radio/src/lua/api_general.cpp b/radio/src/lua/api_general.cpp
index 3886e08c3..b52726923 100644
--- a/radio/src/lua/api_general.cpp
+++ b/radio/src/lua/api_general.cpp
@@ -2152,49 +2152,49 @@ const luaR_value_entry opentxConstants[] = {
   { "SWITCH_COUNT", SWSRC_COUNT },
   { "MAX_SENSORS", MAX_TELEMETRY_SENSORS },
 
-  { "LS_NONE", LS_FUNC_NONE },
-  { "LS_EQV", LS_FUNC_VEQUAL },
-  { "LS_ALMOSTEQV", LS_FUNC_VALMOSTEQUAL },
-  { "LS_GTV", LS_FUNC_VPOS },
-  { "LS_LTV", LS_FUNC_VNEG },
-  { "LS_AGTV", LS_FUNC_APOS },
-  { "LS_ALTV", LS_FUNC_ANEG },
-  { "LS_AND", LS_FUNC_AND },
-  { "LS_OR", LS_FUNC_OR },
-  { "LS_XOR", LS_FUNC_XOR },
-  { "LS_EDGE", LS_FUNC_EDGE },
-  { "LS_EQ", LS_FUNC_EQUAL },
-  { "LS_GT", LS_FUNC_GREATER },
-  { "LS_LT", LS_FUNC_LESS },
-  { "LS_DEQGT", LS_FUNC_DIFFEGREATER },
-  { "LS_ADEQGT", LS_FUNC_ADIFFEGREATER },
-  { "LS_TIMER", LS_FUNC_TIMER },
-  { "LS_STICKY", LS_FUNC_STICKY },
-
-  { "SF_OVERRIDE", FUNC_OVERRIDE_CHANNEL },
-  { "SF_TRAINER", FUNC_TRAINER },
-  { "SF_INST_TRIM", FUNC_INSTANT_TRIM },
-  { "SF_RESET", FUNC_RESET },
-  { "SF_SET", FUNC_SET_TIMER },
-  { "SF_ADJ", FUNC_ADJUST_GVAR },
-  { "SF_VOL", FUNC_VOLUME },
-  { "SF_FAILSAFE", FUNC_SET_FAILSAFE },
-  { "SF_RANGECHECK", FUNC_RANGECHECK },
-  { "SF_BIND", FUNC_BIND },
-  { "SF_PLAY_SOUND", FUNC_PLAY_SOUND },
-  { "SF_PLAY_TRACK", FUNC_PLAY_TRACK },
-  { "SF_PLAY_VALUE", FUNC_PLAY_VALUE },
-  { "SF_PLAY_SCRIPT", FUNC_PLAY_SCRIPT },
-  { "SF_BG_MUSIC", FUNC_BACKGND_MUSIC },
-  { "SF_BG_MUSIC_PAUSE", FUNC_BACKGND_MUSIC_PAUSE },
-  { "SF_VARIO", FUNC_VARIO },
-  { "SF_HAPTIC", FUNC_HAPTIC },
-  { "SF_LOGS", FUNC_LOGS },
-  { "SF_BACKLIGHT", FUNC_BACKLIGHT },
-  { "SF_SCREENSHOT", FUNC_SCREENSHOT },
-  { "SF_RACING", FUNC_RACING_MODE },
+  { "LS_FUNC_NONE", LS_FUNC_NONE },
+  { "LS_FUNC_VEQUAL", LS_FUNC_VEQUAL },
+  { "LS_FUNC_VALMOSTEQUAL", LS_FUNC_VALMOSTEQUAL },
+  { "LS_FUNC_VPOS", LS_FUNC_VPOS },
+  { "LS_FUNC_VNEG", LS_FUNC_VNEG },
+  { "LS_FUNC_APOS", LS_FUNC_APOS },
+  { "LS_FUNC_ANEG", LS_FUNC_ANEG },
+  { "LS_FUNC_AND", LS_FUNC_AND },
+  { "LS_FUNC_OR", LS_FUNC_OR },
+  { "LS_FUNC_XOR", LS_FUNC_XOR },
+  { "LS_FUNC_EDGE", LS_FUNC_EDGE },
+  { "LS_FUNC_EQUAL", LS_FUNC_EQUAL },
+  { "LS_FUNC_GREATER", LS_FUNC_GREATER },
+  { "LS_FUNC_LESS", LS_FUNC_LESS },
+  { "LS_FUNC_DIFFEGREATER", LS_FUNC_DIFFEGREATER },
+  { "LS_FUNC_ADIFFEGREATER", LS_FUNC_ADIFFEGREATER },
+  { "LS_FUNC_TIMER", LS_FUNC_TIMER },
+  { "LS_FUNC_STICKY", LS_FUNC_STICKY },
+
+  { "FUNC_OVERRIDE_CHANNEL", FUNC_OVERRIDE_CHANNEL },
+  { "FUNC_TRAINER", FUNC_TRAINER },
+  { "FUNC_INSTANT_TRIM", FUNC_INSTANT_TRIM },
+  { "FUNC_RESET", FUNC_RESET },
+  { "FUNC_SET_TIMER", FUNC_SET_TIMER },
+  { "FUNC_ADJUST_GVAR", FUNC_ADJUST_GVAR },
+  { "FUNC_VOLUME", FUNC_VOLUME },
+  { "FUNC_SET_FAILSAFE", FUNC_SET_FAILSAFE },
+  { "FUNC_RANGECHECK", FUNC_RANGECHECK },
+  { "FUNC_BIND", FUNC_BIND },
+  { "FUNC_PLAY_SOUND", FUNC_PLAY_SOUND },
+  { "FUNC_PLAY_TRACK", FUNC_PLAY_TRACK },
+  { "FUNC_PLAY_VALUE", FUNC_PLAY_VALUE },
+  { "FUNC_PLAY_SCRIPT", FUNC_PLAY_SCRIPT },
+  { "FUNC_BACKGND_MUSIC", FUNC_BACKGND_MUSIC },
+  { "FUNC_BACKGND_MUSIC_PAUSE", FUNC_BACKGND_MUSIC_PAUSE },
+  { "FUNC_VARIO", FUNC_VARIO },
+  { "FUNC_HAPTIC", FUNC_HAPTIC },
+  { "FUNC_LOGS", FUNC_LOGS },
+  { "FUNC_BACKLIGHT", FUNC_BACKLIGHT },
+  { "FUNC_SCREENSHOT", FUNC_SCREENSHOT },
+  { "FUNC_RACING_MODE", FUNC_RACING_MODE },
 #if defined(COLORLCD)
-  { "SF_NO_TOUCH", FUNC_DISABLE_TOUCH },
+  { "FUNC_DISABLE_TOUCH", FUNC_DISABLE_TOUCH },
 
   { "SHADOWED", SHADOWED },
   { "COLOR", ZoneOption::Color },

```

**Comment by jfrickmann** [comment]
So do you want me to undo the last commit?

**Comment by pfeerick** [comment]
I think so... and just drop FUNC_RESERVE5?

**Comment by jfrickmann** [comment]
OK, consider it done!

**Comment by pfeerick** [comment]
Thanks! :) I thought this might have missed todays nightly as I got sidetracked,but it looks like it hasn't run yet :)

**Comment by wimalopaan** [comment]
Perhaps we should switch to numeric constants and drop the use of string-constants for this. Clearly, this is only possible if these constants can be used in LUA code. Looks like we all should starting the CPP for lua code ;-)

**Comment by wimalopaan** [comment]
If flash size is beginning to be a major concern, then we should keep all the compile-time options we have (e.h. HELI) (or introduce more of those options). I just mention here https://github.com/EdgeTX/edgetx/issues/1249 going in the opposite direction. I strongly argue to keep the compile-time-options.

**Comment by pfeerick** [comment]
I doubt they will go away entirely, and depending on flash usage needs, features like #1249 may not make it to B&W targets. Or could be a feature that is bumped off to continue support if needed. I somehow don't think it itself will be a major issue flash wise, more a matter of that it allows everything to be left turned on. 

It is more a matter of ensuring that anything that is API / constant related is made as compact as practicable right from the start (as it's hard to change later) rather than going "oh look, we have 18kb of space left, we'll never fill that up!" ... and six months later it's gone and we have to start culling.

**Comment by wimalopaan** [comment]
Do you have measures, how the code / flash-size reduces if e.g. HELI is off?

**Comment by pfeerick** [comment]
I don't have any automated / granual breakdown of the size difference... against a B&W target compile is fast enough I just run build and check the size... i.e. again, against the T-Lite simply because it's a B&W radio... we're talking about a little over ~1KB saving if you turn heli tab off. 

```
483232 Dec 15 06:27 firmware-heli.bin
482040 Dec 15 06:28 firmware-noheli.bin
```

**Comment by gagarinlg** [comment]
The image compression on B&W radios with the higher resolution reduced the image size by almost 20kB.
It shouldn't be a big problem to do this also for the lower resolution radios. Obviously the reduction wouldn't be as big.

**Comment by wimalopaan** [comment]
Maybe there is a misunderstanding on my side: does HELI=OFF only deconfigure the heli-tab? I thought it would also deconfigure the whole heli-mixer-stuff, and there should save more space?

**Comment by pfeerick** [comment]
Indeed. I don't think the lower res B&W radios need it just yet... It was the X9D series that I think was of concern before, but it will probably be a good idea to do them as well at some point if only for consistency.

**Comment by pfeerick** [comment]
> Maybe there is a misunderstanding?

I don't think so, other than that there are two sets of savings - flash and RAM ;) As you can see, against t-lite target, it shaves a bit more than 1kb off the flash usage, but I'm not sure how much RAM will be recovered.

Thankfully the B&W radios aren't at the turnigy 9x stage where you need to start turning things off if you wanted some other feature on.

**Pull request merged**
