### PR TITLE
chore(bw): tidy up Radio Setup menu

### PR DESCRIPTION
**Pull request by philmoz**
Summary of changes:
- Indent the 'Mode' label in the 'Sound' section.
- Move the 'Contrast' setting to be directly under the 'Brightness' setting in the 'Backlight section'.
- Indent the 'Contrast setting.

### CODE REVIEW

**Comment by inventor7777** [comment]
Very nice!

**Comment by 3djc** [comment]
I think we should move away from the indent been part of the screen and use INDENT_WIDTH instead. It helps a lot when you have to resue that word

**Comment by philmoz** [comment]
> I think we should move away from the indent been part of the translation string and use INDENT_WIDTH or similar in lcdDrawText() instead. It helps a lot when you have to resue that word

I've cleaned up the usage of the INDENT macro in the code and replaced it with INDENT_WIDTH.
Cleaning up all the translation strings is a big job and probably something for another PR.

**Comment by 3djc** [comment]
Clearly, one step at a time!

**Comment by pfeerick** [comment]
`GRAPHICS` was another 9x legacy define... so good riddance!

**Review by 3djc — APPROVED** [review]

**Review by pfeerick — APPROVED** [review]
LGTM also. Nice to see the GPS header for those options, as well as optimisation of some of the translation helper code. I noticed while reviewing that the "Default channel order" parameter was out of alignment (and has been for a while) by one character so fixed that also.

**Pull request merged**
