### PR TITLE
Implementation of Theme Persistence

### PR DESCRIPTION
**Pull request by kevinkoenig**

### CODE REVIEW

**Comment by kevinkoenig** [comment]
[theme files.zip](https://github.com/EdgeTX/edgetx/files/7262616/theme.files.zip)


put these files in your THEMES directory and they will be settable in the us under screen setup.  once a theme is chosen the radio will boot with those theme colors the next time.  

deleting the the file defaulttheme.txt in THEMES directory will reset to default.

Have fun

**Comment by kevinkoenig** [comment]
this still needs some testing before merging

**Comment by pfeerick** [comment]
If it's any consolation, it seems to be working fine now on my TX16S.... I can see all the themes (just the ones that are still using the original yml layout are showing `---`). Selecting a valid one applies the theme, and it is remembered across power cycle.

**Comment by kevinkoenig** [comment]
I modified the format

**Comment by kevinkoenig** [comment]
one last set of changes and i think it is ready to merge.  Copy the files in the attached zip to have some fun
[themefiles.zip](https://github.com/EdgeTX/edgetx/files/7272285/themefiles.zip)
.

**Comment by JimB40** [comment]
Gave test ride. Works like charm.
TO DO
1. Go back to YAML simple color syntax @kevinkoenig
from PRIMARY1: RGB(0xRR, 0xGG, 0xBB) to PRIMARY1: 0xRRGGBB  
2. Prepare one more included theme (OTX RED) - tribute to DNA :) @JimB40 
3. Clean up and final check of /THEMES folder files (@JimB40 when 1 is implemented)
4. Final test ride
5. Merge (@pfeerick)
6. Have a beer? :)

**Comment by pfeerick** [comment]
For 3, that would would also require a PR/update to the [sdcard ](https://github.com/EdgeTX/edgetx-sdcard)repo ;)

**Comment by kevinkoenig** [comment]
> Gave test ride. Works like charm.
> 
> TO DO
> 
> * [ ]  1. Go back to YAML simple color syntax @kevinkoenig
>   from PRIMARY1: RGB(0xRR, 0xGG, 0xBB) to PRIMARY1: 0xRRGGBB
> * [ ]  2. Prepare one more included theme (OTX RED) - tribute to DNA :) @JimB40
> * [ ]  3. Clean up and final check of /THEMES folder files (@JimB40 when 1 is implemented)
> * [ ]  4. Final test ride
> * [ ]  5. Merge (@pfeerick)
> * [ ]  6. Have a beer? :)

Jim
should we really go back to simple syntax.  The new syntax allows for both hex and numeric RGB values.  It is super easy to do just wondering?

**Comment by kevinkoenig** [comment]
Just implemented both formats.  if color value starts with 0x it will parse it as a hex value.  if it starts with RGB it will parse it as an RGB value.  This should now be ready to go.

**Comment by rotorman** [comment]
Awesome work guys! Looking really good:
https://www.youtube.com/watch?v=5JY9dgtNC2E

**Comment by pfeerick** [comment]
This indeed does look great, and I have been unable to get anything to break, even doing some nasty stuff like spelelling badly in the theme config file ;) 

My only question is this... how hard (as in how long :-P) would it be to make a change for the NV14? Basically, the text info for the theme can be full screen width, and the preview shown below it, again full width. There is a define `#if defined(PCBNV14)` that you can use to have code toggle for the NV14 layout changes...

This is what it currently looks like:
image

**Comment by raphaelcoeffic** [comment]
> This indeed does look great, and I have been unable to get anything to break, even doing some nasty stuff like spelelling badly in the theme config file ;)
> 
> My only question is this... how hard (as in how long :-P) would it be to make a change for the NV14? Basically, the text info for the theme can be full screen width, and the preview shown below it, again full width. There is a define `#if defined(PCBNV14)` that you can use to have code toggle for the NV14 layout changes...

Please don't use things like `PCBNV14`. You'd rather use the screen size as a discriminator. Most places use something like: ```
#if LCD_HEIGHT > LCD_WIDTH
```

**Comment by raphaelcoeffic** [comment]
@pfeerick should be simple. It's just a matter of using lines instead of columns for the screenshot / description fields.

**Comment by pfeerick** [comment]
Sorry, yes, `#if LCD_HEIGHT > LCD_WIDTH` was actually what I had in mind, I just didn't see it at the time... as it should *not* be NV14 specific, and won't be btw ;)

**Comment by kevinkoenig** [comment]
> Sorry, yes, `#if LCD_HEIGHT > LCD_WIDTH` was actually what I had in mind, I just didn't see it at the time... as it should _not_ be NV14 specific, and won't be btw ;) And it was more a matter of "will you have time to squeeze it in and and test it so it can get merged shortly" 😆 No pressure!

Well the code has been updated, tested, and improved.  While I was at it I added much better word wrapping, so it doesn't split within a word to go to a new line.  These functions are contained in a new file called str_functions.h/cpp.  Right now the files are located in color_lcd but should be moved to a generic spot.  They are applicable for all strings.  I also implemented trim(), and trim_start().  Lets get this merged, and I will move the string files to a more generic spot in the future.  

We really should have a utility directory where stuff like this goes.

**Comment by rotorman** [comment]
@JimB40 now as the PR has been merged, we could update also https://github.com/EdgeTX/edgetx-sdcard with the THEMES subfolder with e.g. https://github.com/EdgeTX/edgetx/files/7272285/themefiles.zip
Would you like to do it (if you need help with git, plz let me know)?

**Comment by stronnag** [comment]
Please also rename  `EgdeTX.png` to `EdgeTX.png` :)

**Comment by kevinkoenig** [comment]
Yes that is done already.  It took me 20 minutes to figure that out 

Sent from Mail for Windows

**Comment by rotorman** [comment]
@kevinkoenig the code works in radio, but there are some issues when ran from simulator -> namely it tries to load THEMES from the program path and not from the given SD card path.
One problematic line is: https://github.com/EdgeTX/edgetx/blob/cf7cf79dc32f82478501c4918ecb296d78589080/radio/src/gui/colorlcd/theme_manager.cpp#L248
By changing .\ to \, it can find the themes but still not list them. E.g. here trying under Win 10. As can be taken from debug output, the code combines SD card path with simulator binary path:
```
26.24s: convertFromSimuPath(): C:/Program Files/EdgeTX/Companion 2.6 -> /C:/Program Files/EdgeTX/Companion 2.6
26.24s: f_getcwd() = /C:/Program Files/EdgeTX/Companion 2.6
26.24s: convertToSimuPath(): /C:/Program Files/EdgeTX/Companion 2.6/THEMES/Testing.yml -> C:/ProgramData/EdgeTX/simu_sdcard/horus/C:/Program Files/EdgeTX/Companion 2.6/THEMES/Testing.yml
```

**Comment by wimalopaan** [comment]
Same here on Linux:

```
in scanForThemes
4,09s: opening directory: ./THEMES
4,09s: convertToSimuPath(): ./THEMES -> ./THEMES
4,09s: f_opendir(./THEMES) = error 2 (Datei oder Verzeichnis nicht gefunden)
4,09s: convertToSimuPath(): /THEMES/EdgeTX.png -> /home/lmeier/OpenTx/sd26.simulator/THEMES/EdgeTX.png
4,09s: findTrueFileName(/home/lmeier/OpenTx/sd26.simulator/THEMES/EdgeTX.png)
4,09s:  not found
4,09s: f_open(/home/lmeier/OpenTx/sd26.simulator/THEMES/EdgeTX.png) = INVALID_NAME (FIL 0x7f91d117ffe0)
6,16s: convertFromSimuPath(): /home/lmeier/Projekte/edgetx/edge/build_tx16s -> /home/lmeier/Projekte/edgetx/edge/build_tx16s
6,16s: f_getcwd() = /home/lmeier/Projekte/edgetx/edge/build_tx16s
6,16s: convertToSimuPath(): /home/lmeier/Projekte/edgetx/edge/build_tx16s/THEMES/selectedtheme.txt -> /home/lmeier/OpenTx/sd26.simulator/home/lmeier/Projekte/edgetx/edge/build_tx16s/THEMES/selectedtheme.txt
6,16s: findTrueFileName(/home/lmeier/OpenTx/sd26.simulator/home/lmeier/Projekte/edgetx/edge/build_tx16s/THEMES/selectedtheme.txt)
6,16s:  not found
6,16s: f_open(/home/lmeier/OpenTx/sd26.simulator/home/lmeier/Projekte/edgetx/edge/build_tx16s/THEMES/selectedtheme.txt) = error 2 (Datei oder Verzeichnis nicht gefunden) (FIL 0x7f91aa7fb640)
```

**Comment by kevinkoenig** [comment]
Risto,
When I run simu on ubuntu (under windows) it works for me.  Are you using simulator25?  Also I am a little lost on the correct way to do this that will work on radio, simu, and simulator25. 

The first implementation that called f_getcwd() worked on simu but not radio.  I figured, and “./” should automatically be cwd on all platforms.  Obviously on the radio ./ is the root of the sdcard always.  On simu and simulator25, it should also be cwd of the process, which is then translated into a real path.  

Can you shed some light please.

Sent from Mail for Windows

**Comment by rotorman** [comment]
Please see #861 - tested this under Windows 10 - now works as expected. We have report in Discord that now works also under Arch Linux: https://discord.com/channels/839849772864503828/842693696629899274/894620831785844756

The https://github.com/EdgeTX/edgetx/blob/cf7cf79dc32f82478501c4918ecb296d78589080/radio/src/gui/colorlcd/theme_manager.cpp#L35-L43 was unnecessary, adding system path to THEMES path.

**Pull request merged**
