### PR TITLE
feat(color): make warning for serial port voltage levels clearer

### PR DESCRIPTION
**Pull request by philmoz**
As discussed on discord.

screenshot_tx16s_24-03-07_09-34-30

### CODE REVIEW

**Comment by ulfhedlund** [comment]
SE translatiotion to add if possible, please:
#define TR_TTL_WARNING  "Varning: Överskrid inte 3.3V på TX/RX pinnarna!"

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_TTL_WARNING "Uwaga: Nie przekraczaj 3.3V na pinach TX/RX!"
```

**Comment by kobakirill** [comment]
RU
#define TR_TTL_WARNING "Внимание: Напряжение на выводах TX/RX не должно превышать 3,3 В!"

**Comment by ParkerEde** [comment]
DE:
`#define TR_TTL_WARNING "Warnung: An den TX/RX Pins dürfen 3.3V nicht überschritten werden!"`

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 Thank you to those who already spotted this and provided a translation ;)

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @Pat6874 FR
- [ ] @offer-shmuely / @adir-kro HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @zandorsp PT

```
#define TR_TTL_WARNING                 "Warning: Do not exceed 3.3V on TX/RX pins!"
```

**Comment by zyren** [comment]
CN
```c
#define TR_TTL_WARNING  "请勿在TX和RX引脚接入高于3.3V电平信号 !"
```

*********************************************************
TW
```c
#define TR_TTL_WARNING  "請勿在TX和RX引腳接入高於3.3V電平信號 !"
```

**Comment by robustini** [comment]
#define TR_TTL_WARNING                 "Attenzione: non superare 3.3V sui TX/RX pins!"

**Comment by HThuren** [comment]
DA
#define TR_TTL_WARNING  "Advarsel: Spænding på TX/RX poler må ikke overstige 3,3V!"

**Comment by Eldenroot** [comment]
CZ:

#define TR_TTL_WARNING                 "Varování: Nepřekračujte napětí 3.3V na TX/RX pinech!"

**Comment by Pat6874** [comment]
FR

#define TR_TTL_WARNING "Attention: Ne pas excéder 3.3V aux pins TX/RX !"

Le 18 mars 2024, 01:30, à 01:30, Peter Feerick ***@***.***> a écrit:

**Comment by offer-shmuely** [comment]
HE already translated

**Comment by philmoz** [comment]
> HE already translated

You want to use the English text?

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_TTL_WARNING                 "警告: TX/RXピンは3.3Vを超えてはいけません！"

**Comment by zandorsp** [comment]
PT

#define TR_TTL_WARNING  "Aviso: Não exceder 3,3V nos pinos TX/RX !"

**Pull request merged**
