### PR TITLE
combo box for pwr off delay

### PR DESCRIPTION
**Pull request by olliw42**
this takes up the idea of pfeerick in issue https://github.com/EdgeTX/edgetx/issues/13, to make the setting for 'Pwr Off Delay' a combo box instead of a numeric entry field.

I too like that better as it's easier gui wise.

Other changes indicated in that issue https://github.com/EdgeTX/edgetx/issues/13 were not followed up, I couldn't get what the limited ranges would be.

Question: The strings should go into translate, but I'm not sure what the script which creates the files is really doing. The main question I guess would be, would they have to be added to ALL translate files, or would it be sufficient to add them to only e.g. en?
(I'm really not enthusiastic about doing some Cinese translation....)

COMMENT: not related to this pr but for general info: The handling of g_eeGeneral.pwrOffSpeed is quite strange, and I first suspected a bug, and it still very much looks like a bug, but I couldn't figure it out and it seems to work as is. The strange thing is that the setting can change from 0,..,3, but it is then subtracted from 2 (g_eeGeneral.pwrOffSpeed = 2 - newValue). So 2-3 can happen which converts into a large value since it is uint. Maybe that's a dirty trick, I don't know. This is not only found in this place here but in several places in the code, hence not related to this PR, but probably something to watch out.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
> Question: The strings should go into translate, but I'm not sure what the script which creates the files is really doing. The main question I guess would be, would they have to be added to ALL translate files, or would it be sufficient to add them to only e.g. en?

With the current code, it is necessary to add it to all of them, otherwise compilation will break with the missing translation. There is a python script for that (cumbersome to use, I admit).

> (I'm really not enthusiastic about doing some Chinese translation....)

No problem here: just add it in english, someone will pick it up later (I know someone).

**Comment by raphaelcoeffic** [comment]
> COMMENT: not related to this pr but for general info: The handling of g_eeGeneral.pwrOffSpeed is quite strange, and I first suspected a bug, and it still very much looks like a bug, but I couldn't figure it out and it seems to work as is. The strange thing is that the setting can change from 0,..,3, but it is then subtracted from 2 (g_eeGeneral.pwrOffSpeed = 2 - newValue). So 2-3 can happen which converts into a large value since it is uint. Maybe that's a dirty trick, I don't know. This is not only found in this place here but in several places in the code, hence not related to this PR, but probably something to watch out.

This has been done this way to guaranty that the default value (0 by default when the field does not exist yet) keeps the current behaviour as it was  at the time (4s).

**Comment by olliw42** [comment]
moved STR thing to untranslated

changed the values to 0s, 1s, 2s, 4s, since your comment implies it's 4s and not 3s (as it was before)

**Comment by pfeerick** [comment]
For what it's worth, non-PR code is 0,1,2,3 seconds (currently trying out https://github.com/EdgeTX/edgetx/commit/ec87e40c56035068d7bea63e74d9581c1abb5710), so it wasn't a mistake on your part ;) Either way, this PR works very nicely! :)

**Comment by olliw42** [comment]
for curiosity, what is holding up this PR?

**Comment by raphaelcoeffic** [comment]
> for curiosity, what is holding up this PR?

Nothing, just some other issues to fix, and me not having tested yet ;-)

**Pull request merged**
