### PR TITLE
fix: Throttle idle trim for surface radio

### LINKED ISSUE #4504: Throttle idle trim handling in surface radio
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Throttle idle trim applies on the whole range, and it's max value is at -1024 instead of 0

### Expected Behavior

Throttle trim only applies to forward section:
- all the reverse range should see no trim effect
- full effect should be a 0 throttle

### Steps To Reproduce

On default model, activate throttle idle trim
At full reverse, you cannot reach -100, and 0 is reach only after some reverse push

### Transmitter

RadioMaster MT12

### PR DESCRIPTION
**Pull request by 3djc**
Defines the following behavior for surface radio when **T-Trim-Idle is enabled**

Throttle trim only applies to forward section:
- all the reverse range should see no trim effect
- full effect should be a 0 throttle

Fixes #4504

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
LGTM for MT12, was certainly wrong before due to the centred throttle control.

**Comment by 3djc** [comment]
While working on radio test for surface, I noticed something wrong. In fact, in current implementation the trim potency is doubled compared to air radio for throttle channel (regardless of trim idle or not), this is because full trim result in the same +25 value, but when +25 is 1/8 of the total range for air radio (-100 to 100), it is 1/4th of the forward (or reverse) channel.  I have therefore introduced a division of trim value for the th channel o surface radio

**Comment by 3djc** [comment]
Closed, the whole thing need some more work.

**Comment by pfeerick** [comment]
Ouch... back to the drawing board!

**Comment by 3djc** [comment]
I have it working fine now, but I want to complete the whole gtest for mt12 in case something else is hiding

**Comment by pfeerick** [comment]
Good thing it's January...  else I'd make a quip about "see you next year then...." 🤭

**Pull request closed without merging**
