### PR TITLE
Fix trainer signal period

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- fix last period depending on the PPM driver used.
- apply frame length setting properly

### CODE REVIEW

**Comment by pfeerick** [comment]
Much better... Using default "8CH, 22.5ms, 300us, -" settings

Pre PR - idle after 8CHs is way too short
image

Post PR - length is now padded out properly
image

**Comment by raphaelcoeffic** [comment]
Yep, 16bit on a 2MHz timer. So overflow is around that value.

**Comment by pfeerick** [comment]
Well, to be honest it seams like it would be nuts to have a longer frame, yet less channels... so hopefully it's a limitation that won't be of any consequence. Could be fixed in the UI to some extent by making it have an 'adaptive' frame size based on the number of channels and padding between them. Someday :grin: Looks like worse case scenario 4 CH @ 40ms with 100us gaps comes out at 38.2ms... so pretty close! 

This is happily doing 40ms with 800us gaps now on TX16... as you would do... I have the throttle on Ch1 and Ch8 IIRC so I could see the first set of eight channels. 

image

Working good on:
- [X] X9D+2019
- [X] TX16S
- [ ] T-Lite
- [ ] NV14

**Review by pfeerick — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
Cherry picked into 2.7

**Pull request merged**
