### PR TITLE
chore: abbreviation of voice names for smaller screens

### PR DESCRIPTION
**Pull request by kobakirill**
Routine work

Fixes #

Summary of changes:

### CODE REVIEW

**Comment by pfeerick** [comment]
Is this primary for bw128? As I'm thinking we can maybe be able to use TR() here then to give long and short forms... :thinking:

**Comment by kobakirill** [comment]
> Is this primarily for bw128? As I'm thinking we can maybe be able to use TR() here then to give long and short forms... 🤔

Yes?for bw128.

**Comment by 3djc** [comment]
So do something like:

#define TR_VOICE_ENGLISH          TR("Англ","Английский")

**Comment by froqstar** [comment]
What would be awesome to have (but annoying to do for devs I guess) is to indicate the number of characters we have per screen size next to the key to translate.

**Comment by 3djc** [comment]
Fonts are not fixed width on those radio, so it varies quite a lot

**Pull request merged**
