### PR TITLE
fix(radio) - Fix timer unit announcements.

### PR DESCRIPTION
**Pull request by philmoz**
Broken in switch refactor PR.

### CODE REVIEW

**Comment by pfeerick** [comment]
What did it do, say the wrong units?

**Comment by philmoz** [comment]
Played number only - no units since it was trying to play a non-existent file ('spareX.wav').

**Comment by pfeerick** [comment]
Looking at this list, which I am assuming this should match, is dbm (which isn't on line 172) being missed?

https://github.com/EdgeTX/edgetx/blob/632eceba6d2daaa96df4f530b8275ae67e38f4d7/radio/src/audio.cpp#L142-L181

**Comment by philmoz** [comment]
> Looking at this list, which I am assuming this should match, is dbm (which isn't on line 172) being missed?

No idea. I just reverted the change so it now matches the 2.9 code.

I don't understand why this was changed in the first place - how is telemetry units related to ADC/switch refactoring?

**Comment by pfeerick** [comment]
Some minor reformatting was done, and some stuff was moved out (and more is TODO'd) to other files as part of the refactoring of that file, so it was probably just got caught up in the mix. There is a reason this was done early in the 2.10 cycle ;)

**Pull request merged**
