### PR TITLE
feat(fw): Only attach SD card in USB storage mode

### PR DESCRIPTION
**Pull request by rotorman**
Skips creating the "FIRMWARE" drive, when attaching radio in mass storage mode to the computer. Tested with RM TX16S.

### CODE REVIEW

**Comment by philmoz** [comment]
This breaks the ability to update the firmware with Companion when the radio is connected as USB storage.

On my system a DFU firmware update in Companion takes over 3 minutes.

By comparison a firmware update directly to the 'RM TX16S' volume over USB takes only 3 seconds.

Updating from the SD card is quicker than DFU; but requires more steps and is still nowhere near as fast updating to the USB volume.

**Comment by philmoz** [comment]
I'm not against this change per-se (it would probably be better for many users); but it should be optional with a setting to turn it on and off at the users discretion.

**Comment by gagarinlg** [comment]
Using this firmware drive is a bad idea when you are using Windows.
We are thinking of adding UF2 support instead, which would be much more reliable than that drive.

**Comment by philmoz** [comment]
> Using this firmware drive is a bad idea when you are using Windows.

Some people would say using Windows is a bad idea :)
Why not remove the ability in the Windows version of Companion or pop up a warning.
Removing a feature that works on MacOS and Linux seems a backward step.

> We are thinking of adding UF2 support instead, which would be much more reliable than that drive.

Once that is available, and working reliably across all platforms, then by all means remove the USB storage volume; but please don't remove the fastest way to update the firmware in the meantime.

**Comment by gagarinlg** [comment]
> Some people would say using Windows is a bad idea :)

I agree with that statement, sadly there is sometimes no way around it.


> Why not remove the ability in the Windows version of Companion or pop up a warning

Because people can still just copy the file over to the drive.

Maybe we can make it a compile time option for the time being?

**Comment by pfeerick** [comment]
I don't think it is _guaranteed_ to work on Mac or Linux either - I'm pretty sure I've seen the odd report that it has bricked firmware on Mac or Linux, requiring DFU for recovery. So I would at least strongly recommend that inexperienced users do not use this form of firmware update unless they are comfortable with using DFU mode to recover if it goes wrong. We really do need that UF2 style support to ensure the file copy update method is done in a robust manner.

**Comment by philmoz** [comment]
> I don't think it is _guaranteed_ to work on Mac or Linux either

A compile time options would work for me - if it's not too much effort.
Otherwise I'll just have to live with slower updates.

**Comment by rotorman** [comment]
@philmoz I am not saying that I do not consider adding a compile time option DUALSTORAGE (feel free to propose an alternative name) until we have UF2 setup, but have you considered Serial-Wire-Debug (SWD) for flashing, this is even faster and very robust, just needs a SWD-capable programmer/debugger, like J-Link/J-Trace or ST-Link?

**Comment by philmoz** [comment]
> but have you considered Serial-Wire-Debug (SWD) for flashing, this is even faster and very robust, just needs a SWD-capable programmer/debugger, like J-Link/J-Trace or ST-Link?

Unfortunately a debugger is not an option for me at this stage.

**Comment by pfeerick** [comment]
Maybe `FWDRIVE`? `DUALSTORAGE` sounds more like something to do with the SPI VFS ;)

**Comment by philmoz** [comment]
The latest version still mounts the firmware volume when the radio is started in boot loader mode and connected to USB.
The firmware volume is skipped if powered on normally and connected to USB.

Maybe the FWDRIVE compile option should only enable the firmware volume in boot loader mode?

**Comment by philmoz** [comment]
This change also appears to fix the issue where the radio volumes will not mount at all on MacOS Ventura when both volumes are present. When only the storage volume is present Ventura seems to be happy to mount it.

**Comment by pfeerick** [comment]
@rotorman Hm... [cedd0af](https://github.com/EdgeTX/edgetx/pull/3045/commits/cedd0af5cbe0ed50846c4ab881d1e027c2086914) ... did you forget to push the prior commit? You shouldn't need to do a commit _just_ to make github actions trigger... But while you're adding newlines... do you want to fix up `usbd_desc.c` also... it's also missing a EOF newline ;)

**Comment by philmoz** [comment]
> If you updated by copying the `firmware.bin` then you're not updating the bootloader ;)

Yes, I realised that after I posted.
 
> IMO, no, it should stay disabled regardless of bootloader or normal operation. Bootloader mode is what people are told to use when accessing the radio via USB, rather than when the radio is on (and config files in use). So 9 times out of 10 they will be in bootloader mode.

It would still only appear when building with the FWDRIVE option. So only people building with this option (me) and only when in boot loader mode, will the firmware volume appear.

**Comment by pfeerick** [comment]
Oh, sorry, yes, I see that now. However, what is the real point of adding that extra complexity ("if FWDRIVE && if BOOT")? Are you saying that there was some difference in MacOS Ventura around whether the radio was in the bootloader or normal firmware when showing the drives?

**Comment by philmoz** [comment]
Ventura currently won't mount either volume if the firmware volume is present so getting rid of it for normal builds will eliminate a problem for Mac users. From my testing the single volume mounts ok in either normal or boot loader mode.

I was suggesting having the FWDRIVE firmware volume only in boot loader mode as an extra failsafe.
I try and only update the firmware in boot loader mode as it has failed when running the normal firmware.

**Comment by pfeerick** [comment]
Yeah, that makes sense... you can't overwrite running firmware ;) So I take it you need to use something other than Ventura in order to do the firmware update via the firmware volume?

**Comment by rotorman** [comment]
> @rotorman Hm... [cedd0af](https://github.com/EdgeTX/edgetx/pull/3045/commits/cedd0af5cbe0ed50846c4ab881d1e027c2086914) ... did you forget to push the prior commit? You shouldn't need to do a commit _just_ to make github actions trigger... But while you're adding newlines... do you want to fix up `usbd_desc.c` also... it's also missing a EOF newline ;)

Here was a glitch with GitHub with https://github.com/EdgeTX/edgetx/pull/3045/commits/4361936966435f66affcb9572e522ecc954e0e43 as the _Re-run all jobs_ button was also missing. I discussed with pafleraf and the path decided to get over the problem was to kick GH by doing a new commit (that should be squashed when merging).

Regarding _usbd_desc.c_ - I do see a EOF newline being present already (at least in a local checkout)?

**Comment by pfeerick** [comment]
Hm... I was thinking of the wrong file... you fixed `usbd_desc.c` in the initial commit, and it was `usbd_storage_msd.cpp` that was missing it... which was done in the kicker commit... sorry! 😇 
image

Naughty GitHub!! 👿

**Comment by rotorman** [comment]
> I was suggesting having the FWDRIVE firmware volume only in boot loader mode as an extra failsafe.
> I try and only update the firmware in boot loader mode as it has failed when running the normal firmware.

If you want bootloader with FWDRIVE and main fw without, then flash bootloader with -DFWDRIVE=YES and fw without specifying -DFWDRIVE, or explicitly set to -DFWDRIVE=NO.

**Comment by pfeerick** [comment]
> If you want bootloader with FWDRIVE and main fw without, then flash bootloader with -DFWDRIVE=YES and fw without specifying -DFWDRIVE, or explicitly set to -DFWDRIVE=NO.

Agreed - if you want the FWDRIVE present in either, just build one FW with the option overridden to Y/ON and then you can flash it to the bootloader to get FW drive at the bootloader. Works fine with TX12 and TX16S, stock settings and also custom to have the firmware drive at the bootloader again.

**Pull request merged**
