### PR TITLE
feat(bw128): add option to invert LCD/OLED display

### PR DESCRIPTION
**Pull request by philmoz**
Tested on OLED (T14 and T20v2) and LCD (X7, MT12 and TLite).

TODO:

- [x] Companion suport.

### CODE REVIEW

**Comment by philmoz** [comment]
I moved the option to the hardware tab as suggested in discord. Thanks @pfeerick 

screenshot_t20v2_24-04-28_09-48-34

**Comment by inventor7777** [comment]
Will this be added to the final 2.10, or do I have to get the special version to get this feature?

**Comment by pfeerick** [comment]
2.10 is feature complete, so this will be in 2.11 if merged.

**Comment by inventor7777** [comment]
> 2.10 is feature complete, so this will be in 2.11 if merged.

Sounds good! I hope it is added eventually, because I could definitely use it.

**Comment by arthurson** [comment]
i remembered this function has been required on discord around years ago , so happy  everyone can use it now

**Comment by DuckyScr** [comment]
Hi, I have downloaded the build and it doesnt have persistance. I have been waiting for this and also asked on discord so it is really good feature for me but whenever I chek it and it toggles and works. BUT after I turn the radio off and then on it is not checked and not working. Tested on RadioMaster Boxer

**Comment by philmoz** [comment]
It's working on the B&W radios I have; but I don't have a boxer to test on.

Can you turn on the option and before restarting copy the RADIO/radio.yaml file off the radio.
Then restart and copy the same file off the radio again.
Please upload both file here in a ZIP file.

**Comment by DuckyScr** [comment]
[Archive.zip](https://github.com/EdgeTX/edgetx/files/15304063/Archive.zip)
here it is

**Comment by philmoz** [comment]
Thanks for that - can you try the version in this ZIP file please.

[boxer_lcdinvert_240514.bin.zip](https://github.com/EdgeTX/edgetx/files/15304657/boxer_lcdinvert_240514.bin.zip)

**Comment by DuckyScr** [comment]
[Archive.zip](https://github.com/EdgeTX/edgetx/files/15304858/Archive.zip)
still the same issue, there is the yml

**Comment by philmoz** [comment]
Can you confirm - after a reboot if you turn the option off and back on then the screen inverts?

**Comment by DuckyScr** [comment]
Yes, that is exactly what it does

**Comment by philmoz** [comment]
Thanks.again - here's another firmware to try (no need to upload the radio.yaml files).

[boxer_invert_try2.bin.zip](https://github.com/EdgeTX/edgetx/files/15305264/boxer_invert_try2.bin.zip)

**Comment by 3djc** [comment]
Working fine here, even with your radio.yml

https://photos.app.goo.gl/nBNZbu6kgghicmtF7

**Comment by DuckyScr** [comment]
And what version of sdcard content you have?

**Comment by 3djc** [comment]
it doesn't matter there

**Comment by DuckyScr** [comment]
Ok so I'll try to find some issues or smth that woukd cause the problem. Thanks for help :)

**Comment by pfeerick** [comment]
Only one minor detail :hand_over_mouth: 
- Companion: It updates RADIO/radio.yml, but does not set the correct value. I was trying to go from inverted, back to normal, but it wrote `invertLCD: 1` on the update. 

Everything else looks great... well, screen quality (at a budget) permitting.

**Comment by philmoz** [comment]
> * Companion: It updates RADIO/radio.yml, but does not set the correct value. I was trying to go from inverted, back to normal, but it wrote `invertLCD: 1` on the update.

Copy paste error - should be fixed now.

**Comment by pfeerick** [comment]
Perfect, thanks! :)

**Pull request merged**
