### PR TITLE
Fix handling default values of VALUE inputs of mixer scripts

### PR DESCRIPTION
**Pull request by wimalopaan**
The default values of VALUE inputs in the input table of a mixer script were used as a offset, not as a default value.

### CODE REVIEW

**Comment by pfeerick** [comment]
I know why you did this, as it is common in the code to only store changes relative to the default (hence no room needed if still at default value), so it's not really a fix but a change. As such, this will also need a big fat warning to go with it it as already setup models using mixer script will need to be updated if this PR is merged since the values will all be wrong. 

However, this needs a little more work - as while it seems to save the entered value to the config file correctly, and operate correctly with https://raw.githubusercontent.com/RCdiy/OpenTXLua/master/MIXES/GtStd.lua as a test script, I think continuing to use `GET_SET_WITH_OFFSET` is showing the wrong value when you re-enter the edit screen for the mixer script... probably needs `GET_SET_DEFAULT` instead?

**Comment by pfeerick** [comment]
Can you double check this change for me (setting `sd->inputs[i].value = si.def;` was part of what was causing the value shown to be wrong):
```diff
diff --git a/radio/src/gui/colorlcd/model_mixer_scripts.cpp b/radio/src/gui/colorlcd/model_mixer_scripts.cpp
index eea874255..449cb98fb 100644
--- a/radio/src/gui/colorlcd/model_mixer_scripts.cpp
+++ b/radio/src/gui/colorlcd/model_mixer_scripts.cpp
@@ -111,11 +111,9 @@ class ScriptEditWindow : public Page {
           ScriptInput& si = sio.inputs[i];
           new StaticText(window, grid.getLabelSlot(true), si.name, 0, COLOR_THEME_PRIMARY1);
           grid.nextLine();
-          if (si.type == INPUT_TYPE_VALUE) {              
-              (new NumberEdit(gInputs, inputsGrid.getSlot(), si.min, si.max,
-                           GET_SET_WITH_OFFSET(sd->inputs[i].value, 0)))->setDefault(si.def);
-              sd->inputs[i].value = si.def;
-              
+          if (si.type == INPUT_TYPE_VALUE) {
+            (new NumberEdit(gInputs, inputsGrid.getSlot(), si.min, si.max,
+                           GET_SET_DEFAULT(sd->inputs[i].value)));
           } else {
             new SourceChoice(gInputs, inputsGrid.getSlot(), 0,
                              MIXSRC_LAST_TELEM,
```

**Comment by wimalopaan** [comment]
Well, I don't see the correct handling of the default value in the code / macros.
But yes, I'll give you feedback.

**Comment by wimalopaan** [comment]
As expected, this does not work for me, because

1) initially the value isn't set to the default
2) pressing the "DEF" button for the number edit does not set to the default, because the `vdefault`-attribute in 'BaseNumberEdit` isn't set.

**Comment by wimalopaan** [comment]
> I know why you did this, as it is common in the code to only store changes relative to the default (hence no room needed if still at default value), so it's not really a fix but a change. As such, this will also need a big fat warning to go with it it as already setup models using mixer script will need to be updated if this PR is merged since the values will all be wrong.

Well, ok, I wasn't aware of that fact. But, that is really weird, because it does not save anything here!

LUA is disabled actually in release and nightlies, therefore I think the big-fat warning should be no problem.

Apart from that: for me the usage of input VALUE with default-values other than 1 never really worked ;-)

**Comment by wimalopaan** [comment]
Well, ok, maybe this was a wrong undertanding of how to apply your path above ;-) You have to revert the change in `interface.cpp` also:

```
diff --git a/radio/src/gui/colorlcd/model_mixer_scripts.cpp b/radio/src/gui/colorlcd/model_mixer_scripts.cpp
index eea874255..8d1f60bfa 100644
--- a/radio/src/gui/colorlcd/model_mixer_scripts.cpp
+++ b/radio/src/gui/colorlcd/model_mixer_scripts.cpp
@@ -111,10 +111,13 @@ class ScriptEditWindow : public Page {
ScriptInput& si = sio.inputs[i];
new StaticText(window, grid.getLabelSlot(true), si.name, 0, COLOR_THEME_PRIMARY1);
grid.nextLine();
-          if (si.type == INPUT_TYPE_VALUE) {
+          if (si.type == INPUT_TYPE_VALUE) {
(new NumberEdit(gInputs, inputsGrid.getSlot(), si.min, si.max,
-                           GET_SET_WITH_OFFSET(sd->inputs[i].value, 0)))->setDefault(si.def);
-              sd->inputs[i].value = si.def;
+                             GET_SET_WITH_OFFSET(sd->inputs[i].value, si.def)))->setDefault(si.def);
+
+//              (new NumberEdit(gInputs, inputsGrid.getSlot(), si.min, si.max,
+//                           GET_SET_WITH_OFFSET(sd->inputs[i].value, 0)))->setDefault(si.def);
+//              sd->inputs[i].value = si.def;

} else {
new SourceChoice(gInputs, inputsGrid.getSlot(), 0,
diff --git a/radio/src/lua/interface.cpp b/radio/src/lua/interface.cpp
index a806019d3..fd7f82a51 100644
--- a/radio/src/lua/interface.cpp
+++ b/radio/src/lua/interface.cpp
@@ -1124,7 +1124,7 @@ static bool resumeLua(bool init, bool allowLcdUsage)
if (sio -> inputs[j].type == INPUT_TYPE_SOURCE)
luaGetValueAndPush(lsScripts, sd.inputs[j].source);
else
-            lua_pushinteger(lsScripts, sd.inputs[j].value);
+            lua_pushinteger(lsScripts, sd.inputs[j].value + sio->inputs[j].def);
}
} else
#endif
```
This way it works, but using the name `...OFFSET...` is really totally misleading to me, and, as I said above, the use of such function-like macron, which expand to a sequence, should be totally removed!

**Comment by pfeerick** [comment]
Ah, ok, because you didn't really explain what you were doing :) I see what you mean now as for me, the edit field itself was being filled in with the default value provided in the script I was using to test this with. 

And while LUA_MIXER is not enabled by default, enough people would build it themselves that changes that suddenly mean all settings are changed *must* be drawn to their attention. 

As far as removing functions like GET_SET_WITH_OFFSET, GET_SET_DEFAULT, etc... I can't say I have an opinion either way at present. It is all the way through the codebase, and they are used consistently, so I probably lean in the side of disagreeing with you on that point. It is a helper macro that has a clear defined purpose... GET value, SET value, with OFFSET for each. 

What I would like to see gone is things like the OFFSET type behaviour, as I don't think it has a purpose anymore given the memory and storage constraints it was done for are gone now. Plus, since you can actually see the values in the config file, it is just confusing... i.e. with GtStd having a default value of 5, how on earth are you supposed to know that `value: 10` really means 15 (5+10). But that is a whole different topic. This is working properly now without breaking prior behaviour so just going to tweak the formatting for this and merge it.

**Comment by wimalopaan** [comment]
Well, if this has always been the case, I will be quite ...

But, if afterwards the script changes its default-value, the actual value also changes because the default value is accidentiylly handled as an offset. And offset and default are different words, at least to me.

**Comment by pfeerick** [comment]
Please don't be... who's going to do the PR removing all that mess then? 😆 

They are different, and yes, that is the inherent issue in using the default value as offset. However, given in that instance the user has control over what version of the script they are running, and what default => offset value is, it was probably seen as an acceptable trade off for the reduction in storage usage, memory writes, etc. This is why, probaly in 2.8, I would like to go through the whole codebase and remove all the offset settings writing stuff, and make it so the settings you see in the yml file are the actual settings... why 2.8? Because it would requite a settings version change, and I think 2.7 should lets things settle in that area.

**Pull request merged**
