### PR TITLE
feat(color): add color options for radio info widget battery level indicator

### PR DESCRIPTION
**Pull request by philmoz**
Allow users to set the low, middle and high battery level colors.

Should these be translatable strings?

screenshot_tx16s_24-04-06_13-47-53

### CODE REVIEW

**Comment by froqstar** [comment]
Looks like we have miles of space there? So for DE:

"Farbe Akku fast leer"
"Farbe Akku mittel"
"Farbe Akku voll"

If there is more space maybe insert a "bei" inbetween "Farbe" and "Akku" for extra clarity.

Could we make the default "full" color depending on the theme secondary foreground (?) color (white in this case)? Green could look ugly with some themes or stick out too much visually when it doesn't need to. Battery full, all good, no need to visually alert the user?

**Comment by philmoz** [comment]
I have added translation strings for the widget names and settings.

```C
#define TR_DATE_TIME_WIDGET       "Data & Time"
#define TR_RADIO_INFO_WIDGET      "Radio Info"
#define TR_LOW_BATT_COLOR         "Low battery"
#define TR_MID_BATT_COLOR         "Mid battery"
#define TR_HIGH_BATT_COLOR        "High battery"
```

**Comment by pfeerick** [comment]
> Should these be translatable strings?

'fraid so... and sorry for just clobbering this with your other PR :zany_face: translations seem to like to always collide

**Comment by ulfhedlund** [comment]
SE translations
#define TR_DATE_TIME_WIDGET       "Datum & Tid"
#define TR_RADIO_INFO_WIDGET      "Radioinfo" (or if it fits "Radioinformation")
#define TR_LOW_BATT_COLOR         "Lågt batteri"
#define TR_MID_BATT_COLOR         "Medium batteri"
#define TR_HIGH_BATT_COLOR        "Högt batteri"

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @froqstar DE - Just the DATE_TIME, RADIO_INFO left
- [ ] @Pat6874 FR
- [ ] @offer-shmuely
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [x] SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU 

```
#define TR_DATE_TIME_WIDGET       "Date & Time"
#define TR_RADIO_INFO_WIDGET      "Radio Info"
#define TR_LOW_BATT_COLOR         "Low battery"
#define TR_MID_BATT_COLOR         "Mid battery"
#define TR_HIGH_BATT_COLOR        "High battery"
```

**Comment by froqstar** [comment]
DE
```
#define TR_DATE_TIME_WIDGET       "Datum & Uhrzeit"
#define TR_RADIO_INFO_WIDGET      "Fernst. Info"
#define TR_LOW_BATT_COLOR         "Farbe Akku fast leer"
#define TR_MID_BATT_COLOR         "Farbe Akku mittel"
#define TR_HIGH_BATT_COLOR        "Farbe Akku voll"
```

**Comment by HThuren** [comment]
DA
#define TR_DATE_TIME_WIDGET       "Dato & Klokke"
#define TR_RADIO_INFO_WIDGET      "Radio info"
#define TR_LOW_BATT_COLOR         "Batteri lavt"
#define TR_MID_BATT_COLOR         "Batteri medio"
#define TR_HIGH_BATT_COLOR        "Batteri højt"

**Comment by offer-shmuely** [comment]
HE


#define TR_DATE_TIME_WIDGET       "תאריך ושעה"
#define TR_RADIO_INFO_WIDGET      "מידע השלט"
#define TR_LOW_BATT_COLOR         "מתח סוללה נמוך"
#define TR_MID_BATT_COLOR         "מתח סוללה בינוני"
#define TR_HIGH_BATT_COLOR        "מתח סוללה גבוה"

**Comment by zandorsp** [comment]
PT 
 ```
#define TR_DATE_TIME_WIDGET       "Data & Hora"
#define TR_RADIO_INFO_WIDGET      "Inf do Rádio"
#define TR_LOW_BATT_COLOR         "Bateria Baixa"
#define TR_MID_BATT_COLOR         "Bateria Média"
#define TR_HIGH_BATT_COLOR        "Bateria Alta"
 ```

**Comment by robustini** [comment]
IT

#define TR_DATE_TIME_WIDGET       "Data & Ora"
#define TR_RADIO_INFO_WIDGET      "Radio Info"
#define TR_LOW_BATT_COLOR         "Batteria bassa"
#define TR_MID_BATT_COLOR         "Batteria media"
#define TR_HIGH_BATT_COLOR        "Batteria alta"

In Italian low (bassa), mid (media) and high (alta) are never related to the state of a battery, but to a position in space.
So better alternative for IT:

#define TR_LOW_BATT_COLOR         "Batteria scarica"
#define TR_MID_BATT_COLOR         "Batteria media"
#define TR_HIGH_BATT_COLOR        "Batteria carica"

**Comment by zyren** [comment]
CN

```c
#define TR_DATE_TIME_WIDGET       "日期和时间"
#define TR_RADIO_INFO_WIDGET      "遥控器信息"
#define TR_LOW_BATT_COLOR         "低电量"
#define TR_MID_BATT_COLOR         "中电量"
#define TR_HIGH_BATT_COLOR        "高电量"
```

************************************************

TW

```c
#define TR_DATE_TIME_WIDGET       "日期和時間"
#define TR_RADIO_INFO_WIDGET      "遙控器信息"
#define TR_LOW_BATT_COLOR         "低電量"
#define TR_MID_BATT_COLOR         "中電量"
#define TR_HIGH_BATT_COLOR        "高電量"
```

**Comment by Eldenroot** [comment]
CZ

#define TR_DATE_TIME_WIDGET       "Datum a čas"
#define TR_RADIO_INFO_WIDGET      "Informace o vysílačce"
#define TR_LOW_BATT_COLOR         "Vybitá baterie"
#define TR_MID_BATT_COLOR         "Středně nabitá baterie"
#define TR_HIGH_BATT_COLOR        "Plně nabitá baterie"

**Comment by ToshihiroMakuuchi** [comment]
JP 

#define TR_DATE_TIME_WIDGET       "日付と時刻"
#define TR_RADIO_INFO_WIDGET      "送信機情報"
#define TR_LOW_BATT_COLOR         "バッテリー低"
#define TR_MID_BATT_COLOR         "バッテリー中"
#define TR_HIGH_BATT_COLOR        "バッテリー高"

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_DATE_TIME_WIDGET       "Data i czas"
#define TR_RADIO_INFO_WIDGET      "Informacje o radiu"
#define TR_LOW_BATT_COLOR         "Rozładowana bateria"
#define TR_MID_BATT_COLOR         "Średni stan baterii"
#define TR_HIGH_BATT_COLOR        "Naładowana bateria"
```

**Comment by kobakirill** [comment]
#define TR_DATE_TIME_WIDGET       "Дата и время"
#define TR_RADIO_INFO_WIDGET      "Инфо о пульте"
#define TR_LOW_BATT_COLOR         "Разряженная АКБ"
#define TR_MID_BATT_COLOR         "Середина АКБ "
#define TR_HIGH_BATT_COLOR        "Заряженная АКБ"

**Pull request merged**
