### PR TITLE
Added auto-switch / auto-source to colorlcd

### LINKED ISSUE #118: Autofill Switch Selection Not Working
**General Information**
Transmitter:  RadioMaster TX16S
EdgeTX version:  using tx16s-564dda3.bin & SD Card contents from 26 May, 5:23 pm

**Describe the bug**

1.  Autofill feature of selecting switches as sources in Mixes Page and Special Functions Page does not work.  Instead, you need to manually scroll through the drop-down menu options to choose the source you wish to use from the drop-down menu.  

2. When attempting to use a sound track in Special functions Page after selecting "Play Track" and then selecting the Value field, only lq.wav appears in drop-down menu (even after I have uploaded a sound track which was working properly with OpenTX, it does not work in EdgeTX)

**To Reproduce**
1. Go to Special Functions Page (and/or Mixes Page)
2. Scroll to empty SF line and press enter to edit
3. Press enter in Switch field.  Flip switch of choice - nothing happens (need to scroll through list of options to select the one you're interested in using rather than flipping switch and having it "autofill" for you

4. Scroll down to Function field and press Enter
5. Select Play Track
6. Scroll to Value Field and Press Enter
7. Even though other sound tracks are on SD card (I've uploaded custom sound tracks which did and do play as sound tracks using OpenTX) , the only one that is displayed to be selected is lq.wav (unable to select other tracks).  Even when lq.wav is selected, after having set it up on a switch, the sound track does not play

**Expected behavior**
1.  Expected to be able to flip a switch to "autofill' entry field of menu options
2.  Expected all sound tracks loaded on SD card to be available for selection and then to play properly when activated by Special functions switch as source

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #118

### CODE REVIEW

**Comment by pfeerick** [comment]
Switch autodetection seems to work great on the TX16S (generally). One or two gremlins found whilst testing this PR (but not necessarily directly related):

For the following three menus, whilst the source or switch menus are displayed, when you press return, focus is returned to the underlying menu, but the menu is still shown instead of cleared from the screen. 

- Model Setup -> Timer -> Switch and source menus
- Model Setup -> Inputs -> Switch and source menus
- Model Setup -> Mixes -> Switch and source menus

Model Setup -> Inputs -> source menu is quite jumpy when using a pot or slider - seems to keep jumping between the source previously set, and the detected changing input.

Discussion point:
- In the Inputs and Mixes screens, switches are in the sources menu (as well as the switches menu)... should switches be auto-detected in the sources menu also (as they are not presently for me).

**Comment by raphaelcoeffic** [comment]
> For the following three menus, whilst the source or switch menus are displayed, when you press return, focus is returned to the underlying menu, but the switch/source menu is still overlaid on the screen instead of cleared.

Will be fixed!

**Comment by raphaelcoeffic** [comment]
> should switches be auto-detected in the sources menu also (as they are not presently for me).

Absolutely! Let me fix this 😇

**Comment by raphaelcoeffic** [comment]
@pfeerick both issues should now be fixed.

**Comment by pfeerick** [comment]
Much better! :) I would say 95% done. Detection seems be be working fine for switches and sources... the focus issue is gone... and the Model Setup -> Inputs -> source menu is a lot less jumpy, but is still paying up a bit. It jumps between the first item on the list, and the detection, but if you flick a switch a few times, it might jump to the first item and stay there. 

For completeness, I see there are what look to be stick inputs for the switch menus - Rl, Rr, Ed, Eu, etc... I presume that's Rudder Left, Rudder Right, Elevator Down, Elevator Up... do we want them working yet, or put that in the 'be nice to add later?' box?

**Comment by raphaelcoeffic** [comment]
> and the Model Setup -> Inputs -> source menu is a lot less jumpy, but is still paying up a bit. It jumps between the first item on the list, and the detection, but if you flick a switch a few times, it might jump to the first item and stay there.

Now I can see it as well. No problem, I'll fix it right away.

**Comment by pfeerick** [comment]
Self-build with `-DDISABLE_COMPANION=YES -DPCB=X10 -DPCBREV=TX16S -DCMAKE_BUILD_TYPE=Release` has indeed ironed out that last glitch, and I can't see any regressions.

**Comment by pfeerick** [comment]
t16-92c2fba.bin from https://github.com/EdgeTX/edgetx/actions/runs/914113701 is also behaving as expected.

**Pull request merged**
