### PR TITLE
colorlcd: fix for drawNumber INVERS and text per font size h/v offsets

### PR DESCRIPTION
**Pull request by yaapu**
requires https://github.com/EdgeTX/libopenui/pull/4

probably the vertical offset is needed in other lua draw* methods as well, needs checking

### CODE REVIEW

**Comment by rotorman** [comment]
Thank you @yaapu for the update. I tested your 582f2262 on RadioMaster TX16S. The 0 in the top center of HUD is unfortunately not quite centered:
TX16S 582f2262

I believe it also needs horizontal adjustment (in addition to the vertical adjustment done in this PR).

As I have presently no S.PORT telemetry hw setup to test with, merged the changes of radio/src/lua/api_colorlcd.cpp and libopenui from this PR with current #150 (04a91fb4) and tested with MAVLink (ArduPlane v4.0.9 via DragonLink) on TX16S AUX1.

TX16S 04a91fb4

Here, especially on the rightmost HUD green number "0.5" on can nicely see that the digits should be drawn a little bit to the left as well.

**Comment by yaapu** [comment]
...this is OpenTX 2.3.11
image
perhaps 1 pixel left?

**Comment by rotorman** [comment]
> perhaps 1 pixel left?

We could try first with only 1 pixel, yes ;)

**Comment by rotorman** [comment]
Further issue I found was the height of text dashes in the HUD with the horizon level markers:

TX16S 04a91fb4 HUD dash

**Comment by yaapu** [comment]
..argh... this seems to indicate the v-offset depends on font size, i.e. fonts have been vertically adjusted individually based on size

**Comment by yaapu** [comment]
updated with per font size h/v offsets, tested on simu target

opentx 2.3
image

edgetx 2.4
image

**Comment by rotorman** [comment]
Tested today's new additions merged again with PR #150 (04a91fb4).
20210612_YaapuMod

Looking really good. Only lower right of HUD seems minus 1 pixel lower than HUD lines:

HUD

**Pull request merged**
