### PR TITLE
fix(ui) - Adjust model setup layout to better fit on portrait LCD screen.

### PR DESCRIPTION
**Pull request by philmoz**
Before:
Screen Shot 2022-12-29 at 5 14 35 pm

After:
Screen Shot 2022-12-29 at 5 13 46 pm

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Looks better to me as well. I think we had the minimum size for buttons for the NV14, where the buttons would have been too small otherwise.

**Comment by eshifri** [comment]
I'm not sure: buttons are smaller and not aligned. So it is definitely not worse, but not necessarily better. :-)

**Comment by philmoz** [comment]
If all the buttons have equal width and are aligned horizontally then it looks like this (German and English shown for comparison).

Screen Shot 2022-12-30 at 7 57 33 am

Screen Shot 2022-12-30 at 7 48 50 am

**Comment by gagarinlg** [comment]
You could try to use FLEX_ALIGN_STRETCH to try to get all. Buttons to the same height

**Comment by eshifri** [comment]
IMO it looks better. Probably, with all buttons being the same size it would be close to perfect. :-)

**Comment by philmoz** [comment]
> You could try to use FLEX_ALIGN_STRETCH to try to get all. Buttons to the same height

@gagarinlg I can't find any documentation on this. Can you give an example of how to use it?

**Comment by rotorman** [comment]
I guess LV_GRID_ALIGN_STRETCH was meant. Here example:
https://docs.lvgl.io/master/examples.html?highlight=lv_grid_align_stretch#demonstrate-grid-s-free-unit

**Comment by gagarinlg** [comment]
Probably, I am on my phone, sorry

**Comment by philmoz** [comment]
From what I can tell LV_GRID_ALIGN_STRETCH resizes the content to fill space in a grid cell. It does not resize a grid row height to fit the tallest item. For this to work the grid row height needs to be known in advance.

I can't find any way to automatically size buttons to fill vertical space other than manually setting them to a fixed height.

If anyone knows a way to do this please let me know.

**Comment by eshifri** [comment]
Maybe lv_obj_set_grid_dsc_array() with LV_GRID_CONTENT  in the row_desc?

**Comment by philmoz** [comment]
According to the LVGL documentation LV_GRID_CONTENT will only resize content width.

**Comment by eshifri** [comment]
static const lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static const lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_CONTENT, LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(root, col_dsc, row_dsc);

https://docs.lvgl.io/8.3/others/fragment.html?highlight=lv_grid_content
https://docs.lvgl.io/8.3/others/fragment.html?highlight=lv_grid_content#stack-navigation-example

**Comment by philmoz** [comment]
> static const lv_coord_t col_dsc[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST}; static const lv_coord_t row_dsc[] = {LV_GRID_FR(1), LV_GRID_CONTENT, LV_GRID_TEMPLATE_LAST}; lv_obj_set_grid_dsc_array(root, col_dsc, row_dsc);
> 
> https://docs.lvgl.io/8.3/others/fragment.html?highlight=lv_grid_content https://docs.lvgl.io/8.3/others/fragment.html?highlight=lv_grid_content#stack-navigation-example

I've tried that and can't get it to work. If anyone has an actual working example where buttons resize properly in width and height in ETX it would be appreciated.

**Comment by philmoz** [comment]
This is what I get. LV_GRID_ALIGN_STRETCH expands way too much. I'm probably missing something here; but I have no idea what.

Using LV_GRID_ALIGN_CENTER:
Screen Shot 2022-12-30 at 1 14 23 pm

Using LV_GRID_ALIGN_STRETCH
Screen Shot 2022-12-30 at 1 16 23 pm

**Comment by pfeerick** [comment]
This is the current state of this PR:

image

IMO it is better than the current state, and good enough for now. It would be nice if all the buttons were the same height, which I know was the goal being sought, so it will have to do until we can figure that out.

**Pull request merged**
