### PR TITLE
Independent telemetry input via AUX-serial

### PR DESCRIPTION
**Pull request by wimalopaan**
Add the ability to feed in telemetry data independent of the int/ext-module settings. 
Uses the FrSky-Hub-protocol (2.0) because this works unidirectional. So the attached device must send its telemetry data every 20ms spontaneous.

### CODE REVIEW

**Comment by wimalopaan** [comment]
Followup to #1462

**Comment by raphaelcoeffic** [comment]
Typically, this should be an additional parameter for “Telemetry input”. We really need to stop adding new modes for each combination of mode and what feels like a parameter 😅

**Comment by wimalopaan** [comment]
> Typically, this should be an additional parameter for “Telemetry input”. We really need to stop adding new modes for each combination of mode and what feels like a parameter sweat_smile

D'accord: I promise not to add more ;-)

**Comment by raphaelcoeffic** [comment]
@wimalopaan could you please isolate the changes and rebase on top of `main`? I see a compilation of your changes so far, without being really differentiated by PR / feature.

**Pull request closed without merging**
