### PR TITLE
feat(color): Improvements to switch and source select menu

### PR DESCRIPTION
**Pull request by philmoz**
Fixes https://github.com/EdgeTX/edgetx/issues/1538

Based on feedback from PR #4055, I've made some more changes to the switch and source popup menus.
- Add 'All' filter button which is selected by default.
- Add 'Clear' filter button (switch select only) which only shows the '---' selection.
- Change filter buttons to look like other buttons.
- Increased filter buttons size and spacing for easier touch activation.
- Show filter buttons in two columns to avoid scrolling.
- Show label above menu list, either selection type or current filter.

Screenshot 2023-09-25 at 9 22 37 am
Screenshot 2023-09-25 at 9 22 57 am
Screenshot 2023-09-25 at 9 23 13 am

### CODE REVIEW

**Comment by philmoz** [comment]
Todo:
- The 'Clear' button also needs to be available on the source select; but this is not always the case (need to work out logic).
- May need to have three columns for filters on landscape layout.

**Comment by philmoz** [comment]
Now shows 'Clear' filter when needed, and uses 3 columns for source select on landscape display.

Screenshot 2023-09-25 at 11 06 03 am

**Comment by JimB40** [comment]
Testing PR. This is fkn awesome. :)
So good to see concept works and choosing source or switch is now piece of cake

**Comment by JimB40** [comment]
Few remarks.

Source selection:
1. Shouldn't we have "Clear" & "---" as first items in Source selection popup?. 
Reason is consistency rather, don't see use case when you have to clear source but I havent reviewed all source fields yet.

2. Switch inversion
I know inverted items have negated ID in system so it's easy to display them like now, but it terms of UX this way sucks a little comparing to old method used in OTX and early ETX.
This is particularly visible when programming LS routines. So you choose LS48 then .. you find out it should be inverted. So now you have to scroll like 100 items to select !LS48. Plus to select next negated switch you need to move roller in oposite direction. I always make UI mistakes at this point.

Concept:
a. We have switches list starting with '---' that is filtered or not.
b. There additional button placed in filter area at the very bottom with "Inverse" or shorter "NOT"
c. If you tap this button switch list will exchange for negated values, while selected item is still focused.
d. This button should not be includedd in PAGE>, PAGE< carousel because we will loose this quick clearang feature.
e. For key navigation. LONG ENTER press was always good way to go. It is used to bring Context menu with options but in this case inversion is the only "option" so we don't need to display  additional menu.


3. Filter/button area background
Initialy I've designed dark color (SECONDARY1) to differenciate this form data arrea (item list) but that would need another styling for buttons so:
For filter/button ara we should try SECONDARY3. Same color that is used as background elswhere
Pop-up has frame and diming overleay underneath so it should look okay

**Comment by philmoz** [comment]
> 1. Shouldn't we have "Clear" & "---" as first items in Source selection popup?.
>    Reason is consistency rather, don't see use case when you have to clear source but I havent reviewed all source fields yet.

If the '---' option is not valid for the field then there is no point displaying it (or the Clear button).

Some source fields can be cleared (e.g. Mix), some cannot (e.g. Input).
(I'm not sure why you can clear the source in a Mix line; but that's what the current code allows.)

**Comment by JimB40** [comment]
> > 1. Shouldn't we have "Clear" & "---" as first items in Source selection popup?.
> >    Reason is consistency rather, don't see use case when you have to clear source but I havent reviewed all source fields yet.
> 
> If the '---' option is not valid for the field then there is no point displaying it (or the Clear button).
> 
> Some source fields can be cleared (e.g. Mix), some cannot (e.g. Input). (I'm not sure why you can clear the source in a Mix line; but that's what the current code allows.)

Yep minor thing. forget this point.

**Comment by JimB40** [comment]
Found edge case.
With one item and no filter groups. Minimum pop-up height should be increased.
IMG_0746

**Comment by philmoz** [comment]
> Found edge case. With one item and no filter groups. Minimum pop-up height should be increased.

Not sure I can do much about that - the size is controlled by the menu list.

At least it's better than this:
Screenshot 2023-09-25 at 6 33 02 pm

**Comment by JimB40** [comment]
List is wrong but you should get concept.
SS_01
SS_02

**Comment by pfeerick** [comment]
> So how do you invert switch on NV18? Ah forgot ... we made Key emulation PR :)

I said "long press" ... it works for touch as well! ;)

UI-wise... invert is in the wrong place for me... if I press back, I expect it to go from "All" at the top, to the bottom most button... so that should be clear. Then you can have invert, and then all the filter buttons. Why exactly does this make sense to you for the page back navigation (starting from 1)?

brave_oQFkviX84J

**Comment by philmoz** [comment]
> UI-wise... invert is in the wrong place for me... if I press back, I expect it to go from "All" at the top, to the bottom-most button... so that should be clear. Then you can have invert, and then all the filter buttons. Why exactly does this make sense to you for the page back navigation (starting from 1)?

Invert is not a filter - it changes the current selection to be inverted (e.g. SA --> !SA or vice versa). It would also change the displayed items in the list to be inverted or not.

It should work like a normal button; not be auto activated like the filter buttons so it can't be in the PAGE navigation.

**Comment by JimB40** [comment]
Eh Peter it would be so much faster if you sleep ;)

ENTER is used only on the right hand list. 
PAGE> and PAGE< change focus on the left hand side items but also applies filter (no need to press ENTER)

INVERT need key press to be applied but SHORT ENTER is already in use.
On the other hand implementif focus change left<->right will mess and complicate UI

To recap no need to include it in focusable fields.
It is button to indicate you can tap on it but it never  gets focus.

**Comment by pfeerick** [comment]
So the button is *only* for touch then (and thus can be hidden on non-touch UIs)?

**Comment by JimB40** [comment]
Well for those color radio models without Touch capabilities we can change it so it looks like label (just indicator) after you LONG press ENTER. But then list will be visually changed with items including ! 
So I think it is not needed at all. LONG PRESS was always kind of 'hidden' feature without visual representation on UI so users know about it. 
if we can sense if touchUI is not present I'd make it not visible.

**Comment by 3djc** [comment]
Yes touch interface can be 'sensed'

**Comment by philmoz** [comment]
I've added the 'Invert' button and associated logic. Long press will switch inverted state.

I did not hide the 'Invert' button for radios without touch screen, as I think it provides a better visual cue of the inverted state than just the '!' marks in the names.

Screenshot 2023-09-26 at 8 34 32 am

Also hidden the 'Clear' button if there are no other filters.

Screenshot 2023-09-26 at 8 35 06 am

**Comment by pfeerick** [comment]
Can't hide the toolbar completely if there is not more than one filter?

> as I think it provides a better visual cue of the inverted state

While I agree with the intention, for that to work, it would need not be a verb (action) word there, or to be displayed differently. If you need to explain to someone "this looks like a button, smells like a button, tastes(!?) like a button, but doesn't work" then that UI concept fundamentally is broken.

**Comment by JimB40** [comment]
Looks good. Will test in after early morning coffee
Agree with Peter, if something is not behaving like a button it shouldn't look like it.
Label "inverted" would serve better

**Comment by JimB40** [comment]
Two things after testing:
1. List item is loosing focus if switch wans not selected previously (cleared to '---')
2. Can't find Pots/Sliders/6-pos in sources.

https://youtu.be/NIdlf-dPR2k

**Comment by philmoz** [comment]
> 1. List item is loosing focus if switch was not selected previously (cleared to '---')

I will see what I can do with this.

> 2. Can't find Pots/Sliders/6-pos in sources.

Existing functionality - 2.8 is the same.

**Comment by pfeerick** [comment]
> Can't find Pots/Sliders/6-pos in sources.

Pots /sliders are not switches ;) So if you go into any 'switches' list, you won't find them. 


However, they do seem to be missing in your case at https://youtu.be/NIdlf-dPR2k?si=MJS0pgqad3ZKCA3Z&t=384 ... the group icon was completely missing for you... and instead, you had the constants icon where it should have been like here...
image

However, from what I could see from the look of the main screen at the start of the video ... you may need to go into Radio Settings -> Hardware -> Pots, and actually enable S1/S2/6POS/LS/RS again! 🤭

**Comment by JimB40** [comment]
image

Volume by GF
Left 2.10 - LS but no POTS
Right 2.9 - POTS but no LE

**Comment by pfeerick** [comment]
1) you need to check my above comment about actually ensuring your pots/sliders are enabled ;) 

2) Logical switches have never been (and probably will never be) available in global functions since they are not necessarily available for all models. And when you go into special functions on 2.9, there is no filter for them (but they are in the list when you scroll past the last of the switches) as that is being added by this PR ;)

**Comment by pfeerick** [comment]
Most likely an issue due to the switch and pots ADC PR which every now and then we find another gremlin from. There is another PR that will probably break things again (or by coincidence also fix this) pending, so there has been no point fixing this. Hazards of running nightly / dev firmware ;)

**Comment by JimB40** [comment]
image

Apparently Logical  switches ARE available i  2.9 providence when you select for exmample source for volume in GF.

There is no icon for filter but they are present in ALL list.

I think we should review fields that need "sources" as input to check what is available and if that is ok.

**Comment by JimB40** [comment]
Another example (bug?)
Selecting switch:
'ON' and 'One' is included when 'All' is applied but not with 'Other' filter or any other filter.

**Comment by pfeerick** [comment]
Sorry, my mistake there... I looked further back, and it looks like it has always been the case re: inputs/ls/cyc etc being available for those two functions (brightness and volume) in GF (since it is *only* those two functions), so it probably doesn't matter that much... would just hope there is some special handling or such to ensure that if you have say the brightness linked to a LS that is non-existent for a given model that doesn't turn the backlight off 🤭 )... bit pointless IMO for volume and brightness to able to be set to a LS, since it will either be off or on (i.e. MAX)... but whatever.

**Comment by 3djc** [comment]
LS should not be available imho, since as you mention, they are model specific

**Comment by JimB40** [comment]
Agree For Volume or Brightness and few more you need something linear or multi-value rather the bi-state.
But then.
1. We allow to select all of them not going into use case. (maybe someone will come up with LS routine that lower volume or brightness)
2. We go "Apple-way" -> review all fields and allow to select only what we think is needed.

**Comment by pfeerick** [comment]
Probably better to go 2, but maybe not in this PR... to keep it on track. Basically, IMO, since we're talking about a global function, anything model-specific (so inputs, heli mixes, trainer, outputs, GVs, LSs, etc) should get the axe... leaving pretty much only stuff that is hardware level like sticks, switches and constants.

**Comment by 3djc** [comment]
> 2. We go "Apple-way" -> review all fields and allow to select only what we think is needed.

that's what isSourceAvailableinGlobalFunction() is supposed to do (not sure the exact name, not in front of code)

**Comment by pfeerick** [comment]
That is a function :) `isSourceAvailableInGlobalFunctions()` It however looks to exclude only telemetry atm.

**Comment by 3djc** [comment]
> That is a function :) `isSourceAvailableInGlobalFunctions()` It however looks to exclude only telemetry atm.

Then that's what we call 'room for improvement' ;)

**Comment by philmoz** [comment]
Added 'On' and 'One' to the 'Other' filter.
Added flight mode filter for switch select (available in SF/GF switch).
Retain current selected menu item when 'inverted' state changes.

Note: selected menu item is not retained when the filter changes. If the filter includes the original field value (when the menu was opened) it will be selected, otherwise the first item is selected.

**Comment by JimB40** [comment]
Flashed, tested on various fields.
Can't find anything malfunctioning.
Good job @philmoz :)

**Comment by philmoz** [comment]
Fixes #1538

**Comment by pfeerick** [comment]
FYI, GitHub only auto-links PRs and issues when you use the keywords in the initial comment... not sure whether that's good or bad :shrug:

**Review by pfeerick — APPROVED** [review]
Looks to be working exactly as advertised on TX16S and EL18. Thanks for the great work on this one guys! :)

**Pull request merged**
