### PR TITLE
Add codename to version string and to bootloader title

### PR DESCRIPTION
**Pull request by rotorman**
Solves #1847 by adding codename to version string in the VERSION page and also on the bootloader title.

Here, as tested on TX16S mkII physical target (notice the addition of `-dev`):

grafik

grafik

### CODE REVIEW

**Comment by wimalopaan** [comment]
You can get the same effect using the `OPENTX_VERSION_SUFFIX` environment variable for the cmake.

**Comment by raphaelcoeffic** [comment]
> You can get the same effect using the `OPENTX_VERSION_SUFFIX` environment variable for the cmake.

Thus meaning we should set the `VERSION_SUFFIX` (why `OPENTX_`?) depending on release / dev branch.

**Comment by rotorman** [comment]
By default it could be set to `-SB` for self-builder, if users are building themselves, then `vX.X.X-SB` is automatically used and can be easily distinguished when providing help/support to users.
GitHub builds could use `-DEV` and `-REL` accordingly.

**Comment by pfeerick** [comment]
Or link it to the release git tags - if it is a tagged release, use the tag version (thus it will also indicate it is a rc). If it's not, it's a dev or self-build.

**Comment by rotorman** [comment]
Please double check if I got this right:
https://github.com/EdgeTX/edgetx/blob/e15156e1d1ae3185a7920e3f28983ec7a8f8ae33/tools/build-gh.sh#L51-L59

The result on radio with present state for GitHub built firmware (do not like "merge" string though so much):
grafik

and the same locally built w/o specifying `EDGETX_VERSION_SUFFIX`:
grafik

Also, a test build warning screen is shown now on power-up, although at the moment only for self-built versions where EDGETX_VERSION_SUFFIX is not defined:

grafik

Ideally, this could be shown for all non-release versions.

**Comment by rotorman** [comment]
Changed GitHub build `merge` to `dev`:

grafik

and local self-build to `custom`:

grafik

I prefer this, but am open to suggestions.

**Comment by pfeerick** [comment]
> Ideally, this could be shown for all non-release versions.

Most definitely **_not_** ... this was an intentional change right from the start AFAIK, and regardless, I do not want to see this re-introduced. It is annoying AF when running nightly releases regularly. 

Regarding the tags, `merge` is correct if it is coming up for pull request branches, since they are `merge` branches. This also tells you the build is from a PR, *not* from the dev branch, which from what I can tell this obscures. And `selfbuild` would be more that SB, since it's not an acronym ;) Also just seem more descriptive than "custom" ... custom what? ;)

**Comment by rotorman** [comment]
I hear you, thank you for the feedback!

In latest commit TEST_BUILD_WARNING screen is gone, `-merge` is back and self built firmwares are marked with `-selfbuild`

grafik

grafik

**Review by pfeerick — APPROVED** [review]
I think this is a fantastic starting point. I would still like to see PR number exposed if it's a PR build, but that seems to be be somewhat involved to tease out of github, so can be something for a future PR. 

Most importantly, this communicates that either a developmnent, a release build, or a self build is in use :)

**Pull request merged**
