### PR TITLE
fix: YAML timer handling

### LINKED ISSUE #3946: in special function - Play Value - Tmr1 was deleted after update to current main
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have in etx 2.9 special functions an entry "Play value" - Motor (Tmr1).
After the update there is only "Play value" - --.

But when I open the list, I can select "Motor" for Tmr1.

Tmr1 is defined

### Expected Behavior

the entry should remain after the update as it was before the update.

### Steps To Reproduce

1. define in etx 2.9 Timer 1 with the name - Motor, %Throttle
2. create in etx 2.9 special functions an entry "Play value" - Motor
3. update to current main
4. observe the special functions entry shows"Play value" - --

### Version

Other (Please specify below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

_No response_

### Anything else?

current main

### PR DESCRIPTION
**Pull request by 3djc**
Fix timer not been saved a mixer source in YAML since adc refactor mega PR

Also fixes UI inconsistencies (see below)

This fixes #3946

MERGE NOTE: partner for https://github.com/EdgeTX/edgetx/pull/3956

### CODE REVIEW

**Comment by elecpower** [comment]
> @elecpower I have tried to follow pre 2.10 naming so companion should not be affected

Since I assume you have thoroughly tested the change to/from Companion then this comment should be 'IS not affected'  ;-)

**Comment by 3djc** [comment]
> > @elecpower I have tried to follow pre 2.10 naming so companion should not be affected
> 
> Since I assume you have thoroughly tested the change to/from Companion then this comment should be 'IS not affected' ;-)

You assumed **cough cough** right that I had planned companion test for this morning !! The results are mixed? For the scope if this change, it works fine, BUT I did find that the timer handling doesn't match the new radio behavior (if a timer is not defined, it should not appear on list). I'll open an issue for that

**Comment by elecpower** [comment]
Should not be too difficult for me to fix as the list already has an available filter mechanism. Just need to set flag on timers.

**Comment by 3djc** [comment]
> Should not be too difficult for me to fix as the list already has an available filter mechanism. Just need to set flag on timers.

This is what drives it radio side : https://github.com/EdgeTX/edgetx/blob/2f3c1043275c0425e41555c4d861721da7917ae7/radio/src/gui/gui_common.cpp#L252

**Comment by elecpower** [comment]
Thanks for the code link

**Comment by 3djc** [comment]
Ok we are today in a bit weird situation:

image

I'm cleaning that with only the short form

**Comment by pfeerick** [comment]
The UI side may need a little more work, as for colorlcd with no timers enabled, you can create a set SF, and it says Timer 1 in the choice box, but then you get a dimmed screen if you press it to bring up your choices. And for B&W it is showing Tmr1 even though it's not really a valid option. i.e. option probably needs to be disabled / have a popup instead saying no timers enabled if you press it, but that's a problem for another time.

**Pull request merged**
