### PR TITLE
chore(color): Model setup page cleanup

### PR DESCRIPTION
**Pull request by philmoz**
Makes the buttons on the model setup page consistent height (matches the radio setup -> Tools page buttons).
Cleanup the code.

Screenshot 2023-08-04 at 3 52 55 pm
Screenshot 2023-08-04 at 3 54 51 pm

### CODE REVIEW

**Comment by pfeerick** [comment]
lol... that's third of the three issues I had jotted down from this morning gone already 😆 

- topbar time and date widget should default to theme colour (not black) when added
- toolbar `page <` not working (2.10 main)
- multiple buttons in row, same height

**Comment by JimB40** [comment]
@philmoz If you touch it please move "ADC filter" option below groups. This is 'set and forgret' feature and things in groups (Timers)  are more probable to change frequently. So less scrolling.

**Comment by philmoz** [comment]
> * toolbar `page <` not working (2.10 main)

I can't reproduce this in the simulator (have not tried on a radio).

**Comment by JimB40** [comment]
Don't know if I get your point right @pfeerick, but here is MODEL SETUP - GENERAL screen design done sometime ago that follows same UX principle that #2939 

MODEL SETUP - GENERAL

Left side panel (model name, picture, and labels) is sticky.
Right side panel with buttons for group options scrolls.

This will give: 
- good overview what is on/off
- no scrolling or just a bit of scrolling.

So wouldn't be afraid to put another button like "Filters" or "Hats" for NV14 with just one option inside.
Those are 'set and forget' features. 

Advantage is that you can hide this whole button not thinking too much what is the configuration screen behind this button. Not visible - not accesible.

**Comment by philmoz** [comment]
> This is from Companion build from a week ago, which is the same as radio. It seems the long press emulation of `PAGE >` for `PAGE <` is working, but not the normal press of `PAGE <` isn't.

Thanks, when you said toolbar I thought you meant the top menu bar.

Looks like another ADC switch refactor issue - KEYS_GPIO_REG_PGUP no longer exists all radios default to the long press event only.

**Comment by pfeerick** [comment]
> So wouldn't be afraid to put another button like "Filters" or "Hats" for NV14 with just one option inside.
Those are 'set and forget' features.

Except, the key to being able to make that view so compact is being about to group options, rather than having multiple buttons leading to single screens with single options... which is also confusing and frustrating AF as a user, as well as crap UI design. Yes, sometimes you will have a screen with only one option, because it doesn't fit into any of the other categories, but I don't believe that to be the case here. Regarding the hats option, I can see some rationale for it being under "Trims", although it is still a UI/navigation option, not a "trim" setting per se. However, following that screenshot, there are eight buttons needed _already_ as "enabled features" is missing, so you would already have to scroll if you want a button for ADC filter (Hats button is not relevant at present as that is portrait UI). 😛 

If you have to scroll to get to the button, which takes you to a screen with a single option, since the control for that option will take up one line, just like a new row of buttons would, why make it awkward? 🤣 i.e. put it at the bottom (your suggestion), or remove it from that screen entirely, into one of the existing other categories (my suggestion).

**Comment by pfeerick** [comment]
> Looks like another ADC switch refactor issue - KEYS_GPIO_REG_PGUP no longer exists all radios default to the long press event only.

Ouch! Then again, that could be intentional. Paging forward and backwards through a tabbed view like model settings works for both buttons on TX16S, and holding PAGE down on X10/T16 (i.e. single page button radios) in simulator to trigger page back works, so maybe the event used in the toolbar needs changing?

**Comment by philmoz** [comment]
> Ouch! Then again, that could be intentional. Paging forward and backwards through a tabbed view like model settings works for both buttons on TX16S, and holding PAGE down on X10/T16 (i.e. single page button radios) in simulator to trigger page back works, so maybe the event used in the toolbar needs changing?

Looks like name change - #3902

**Comment by raphaelcoeffic** [comment]
> Looks like another ADC switch refactor issue - KEYS_GPIO_REG_PGUP no longer exists all radios default to the long press event only.

We should definitely avoid having the UI depend on such hardware definitions. This should be handled directly by the hardware layer.

**Comment by JimB40** [comment]
> buttons leading to single screens with single options... which is also confusing and frustrating AF as a user
As I wrote 'set & forget' feature. Doesn't mater it's in-line somhere low in screen or button openning pop-up. 
Maybe you switch it many times during test but average user set it once.

In a web apps I have click-stats and this tool shortens "what-if" wondeting in favour of of hard data, but no need to have click-stat to see Timer settings are going to be confugured more often than ADC fiter.

**Pull request merged**
