### PR TITLE
LcdColorIndex - Make default colour first entry

### LINKED ISSUE #462: INav Lua colors are incorrect
Here is a pic of what it should look like with the white text and what it looks like when running EdgeTX.

inav1
IMG_5293

As discussed in the lua discord channel.  I'm opening a bug report for this issue.

TX is a RadioMaster TX16s running EdgeTX RC3 latest nightly build.

**Reply from Risto on this issue.**

I had a look at LUA color handling and compared it with OpenTX. Well the enum is different. I got it to work with EdgeTX (here screenshot from EdgeTX simulator24), but you are not gonna like the solution unfortunately or the details - as I guess either iNav devs must rework their script or EdgeTX needs to match the enum order with color order of OpenTX 2.3 (details below):

inav_fixed

In EdgeTX and OpenTX, text in LUA is output using luaLcdDrawText() https://github.com/EdgeTX/edgetx/blob/6ded23f26bc01580ab7d506941bf72eaee7d77a9/radio/src/lua/api_colorlcd.cpp#L217-L260
It's color (line 236 in the previous link) is taken from a lcdColorTable: https://github.com/EdgeTX/edgetx/blob/6ded23f26bc01580ab7d506941bf72eaee7d77a9/radio/src/gui/colorlcd/colors.cpp#L23 that uses enum index.
EdgeTX uses following index: https://github.com/EdgeTX/edgetx/blob/6ded23f26bc01580ab7d506941bf72eaee7d77a9/radio/src/gui/colorlcd/colors.h#L28-L75
In OpenTX there is the same enum, but the list is differently populated: https://github.com/opentx/opentx/blob/c6e8ed866c48cef2ef34c335dea093ab9198ce43/radio/src/gui/480x272/colors.h#L50-L83
Thus when the raw index values are used (as iNav LUA widget apparently does), the output is different. The first index in OpenTX is TEXT_COLOR_INDEX, whereas in EdgeTX ALARM_COLOR_INDEX.
In order to get the white text in iNav LUA, I reshuffled the order in colors.h and made DEFAULT_COLOR_INDEX the first entry instead of red ALARM_COLOR_INDEX, rebuilt EdgeTX simulator and voila the screenshot above with white text as it should...

### PR DESCRIPTION
**Pull request by pfeerick**
For functions/cases where the default colour is not specified. Resolves #462. 

Basically, when not colour was specified, ALARM_COLOR_INDEX was being used, meaning for example, text with no colour specified was red. Example of this at it's worst has been the iNAV telemetry lua, with all the previously white text elements turned red. In a simple lua widget on the main panel, text was also red instead of either dark blue or black. 

I don't have full iNAV capable telemetry, so I am relying on the fix mentioned in that issue. It does not appear to have any negative effects on other widgets, or other screen elements. 

Before:
image
image

After:
image
image

With a random D16 receiver just so there was *some* telemetry:
image

### CODE REVIEW

**Comment by pfeerick** [comment]
Oh, what the fug? I just ran `tests-radio` locally (TX16 target, as I wanted to see the failed image) and it passed?! Does the T18 not like me?

```
############ Running 71 test(s) from 16 test case(s), iteration: 1.
[----------] 2 tests from color
++
[----------] 2 tests from Crossfire
++
[----------] 1 test from Storage
0.00 RamBackupWrite sdsize=11922 backupsize=11922 rlcsize=190
+
[----------] 4 tests from FrSky
++++
[----------] 7 tests from FrSkySPORT
+++++++
[----------] 3 tests from SpecialFunctionsTest
0.00 LayoutFactory::initPersistentData() setting option 'Top bar'
0.00 LayoutFactory::initPersistentData() setting option 'Flight mode'
0.00 LayoutFactory::initPersistentData() setting option 'Sliders'
0.00 LayoutFactory::initPersistentData() setting option 'Trims'
0.00 LayoutFactory::initPersistentData() setting option 'Mirror'
+++
[----------] 8 tests from Lcd_colorlcd
0.00 convertToSimuPath(): /src/radio/src/tests/lines_480x272.png -> /src/radio/src/tests/lines_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/lines_480x272.png)
0.00    found: /src/radio/src/tests/lines_480x272.png
0.00 f_open(/src/radio/src/tests/lines_480x272.png, 1) = 0x616000004880 (FIL 0x5644bebcd760)
0.00 f_close(0x616000004880) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/vline_480x272.png -> /src/radio/src/tests/vline_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/vline_480x272.png)
0.00    found: /src/radio/src/tests/vline_480x272.png
0.00 f_open(/src/radio/src/tests/vline_480x272.png, 1) = 0x616000004b80 (FIL 0x5644bebcd760)
0.00 f_close(0x616000004b80) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/primitives_EN_480x272.png -> /src/radio/src/tests/primitives_EN_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/primitives_EN_480x272.png)
0.00    found: /src/radio/src/tests/primitives_EN_480x272.png
0.00 f_open(/src/radio/src/tests/primitives_EN_480x272.png, 1) = 0x616000004e80 (FIL 0x5644bebcd760)
0.00 f_close(0x616000004e80) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/transparency_EN_480x272.png -> /src/radio/src/tests/transparency_EN_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/transparency_EN_480x272.png)
0.00    found: /src/radio/src/tests/transparency_EN_480x272.png
0.00 f_open(/src/radio/src/tests/transparency_EN_480x272.png, 1) = 0x616000005180 (FIL 0x5644bebcd760)
0.00 f_close(0x616000005180) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/clipping_480x272.png -> /src/radio/src/tests/clipping_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/clipping_480x272.png)
0.00    found: /src/radio/src/tests/clipping_480x272.png
0.00 f_open(/src/radio/src/tests/clipping_480x272.png, 1) = 0x616000005480 (FIL 0x5644bebcd760)
0.00 f_close(0x616000005480) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/opentx.png -> /src/radio/src/tests/opentx.png
0.00 findTrueFileName(/src/radio/src/tests/opentx.png)
0.00    found: /src/radio/src/tests/opentx.png
0.00 f_open(/src/radio/src/tests/opentx.png, 1) = 0x616000005780 (FIL 0x5644bebcd760)
0.00 f_close(0x616000005780) (FIL:0x5644bebcd760)
0.00 convertToSimuPath(): /src/radio/src/tests/bitmap_480x272.png -> /src/radio/src/tests/bitmap_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/bitmap_480x272.png)
0.00    found: /src/radio/src/tests/bitmap_480x272.png
0.00 f_open(/src/radio/src/tests/bitmap_480x272.png, 1) = 0x616000005a80 (FIL 0x5644bebcd760)
0.00 f_close(0x616000005a80) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/mask_menu_radio.png -> /src/radio/src/tests/mask_menu_radio.png
0.00 findTrueFileName(/src/radio/src/tests/mask_menu_radio.png)
0.00    found: /src/radio/src/tests/mask_menu_radio.png
0.00 f_open(/src/radio/src/tests/mask_menu_radio.png, 1) = 0x616000005d80 (FIL 0x5644bebcd760)
0.00 f_close(0x616000005d80) (FIL:0x5644bebcd760)
0.00 convertToSimuPath(): /src/radio/src/tests/masks_480x272.png -> /src/radio/src/tests/masks_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/masks_480x272.png)
0.00    found: /src/radio/src/tests/masks_480x272.png
0.00 f_open(/src/radio/src/tests/masks_480x272.png, 1) = 0x616000006080 (FIL 0x5644bebcd760)
0.00 f_close(0x616000006080) (FIL:0x5644bebcd760)
+0.00 convertToSimuPath(): /src/radio/src/tests/darkmode_EN_480x272.png -> /src/radio/src/tests/darkmode_EN_480x272.png
0.00 findTrueFileName(/src/radio/src/tests/darkmode_EN_480x272.png)
0.00    found: /src/radio/src/tests/darkmode_EN_480x272.png
0.00 f_open(/src/radio/src/tests/darkmode_EN_480x272.png, 1) = 0x616000006380 (FIL 0x5644bebcd760)
0.00 f_close(0x616000006380) (FIL:0x5644bebcd760)
+
[----------] 3 tests from Lua
0.00 luaInit
0.00 lsScripts 0x617000000080
+++
[----------] 15 tests from TrimsTest
+++++++++++++++
[----------] 1 test from Curves
+
[----------] 11 tests from MixerTest
+++++++++++
[----------] 2 tests from Heli
++
[----------] 1 test from Trainer
+
[----------] 1 test from getSwitch
+
[----------] 1 test from evalLogicalSwitches
+
[----------] 9 tests from Timers
+++++++++
[==========] 71 tests from 16 test cases ran. (708 ms total)
[  PASSED  ] 71 tests.
```

**Comment by pfeerick** [comment]
Failed:
failed_transparency_EN_480x272

Test Reference:
transparency_EN_480x272

The test:
https://github.com/EdgeTX/edgetx/blob/a5e0aab49b9becb5c585c90cd63f96d00710f969/radio/src/tests/lcd_480x272.cpp#L155-L195

I presume it's failed *because* the colour palette sequence has changed?

**Comment by raphaelcoeffic** [comment]
@pfeerick to generate the pictures to pass the tests, the simplest is to use the same docker container image we are using here, and collect the "failed_xxx" pictures, removing the "failed_" parts. This compares the pictures pixel by pixel, but the python lib we use to generate the fonts is only "pixel exact" against the exact same version.

**Comment by pfeerick** [comment]
So that is an "ok" for making it so test passes? As I wasn't sure yet if this is the "right" way to fix the problem, or just right enough for now! :grin:

**Comment by raphaelcoeffic** [comment]
> So that is an "ok" for just making it so test passes as well? As I wasn't sure yet if this is the "right" way to fix the problem, or just right enough for now! 😁 I so nearly just named the commit for this "Put head in sand and rig the test".

I may have had assigned the first entry to zero to be more explicit, but I think this is anyway the case, even without.

**Pull request merged**
