### PR TITLE
feat: special function to push customisable switches

### LINKED ISSUE #5487: Change the state of customizable buttons via special functions
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I use one of the six customizable function buttons on my Jumper T20 to enable f.e. the Betaflight Air Extension. But I would also like to automatically switch off the Air Extensions when I change to angle mode. I know this function can be already achieved via the Betaflight Modes, but the LED of the customizable function button would then be incorrect. So changing the button state via a special/global function would be great. Additional Benefit: unused buttons could be also misused as f.e. a flashing indicator LED.

### Describe the solution you'd like

Add the possibility to SET and TOGGLE the state of customizable function buttons via special/global functions.
How to deal with grouped buttons would probably need additional discussion.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 3djc**
Thanks @philmoz for colorlcd UI

Fixes #5487

### CODE REVIEW

**Comment by 3djc** [comment]
@elecpower , could you do the Companion piece ?
Basically this adds a special func for radio with customisable switches, with 2 params:
- which switch ? SW1 to SWx (num function switch)
- duration; 0 to 25.5s, store exactly like SDLogs (value is in tenth of seconds)

**Comment by elecpower** [comment]
> @elecpower , could you do the Companion piece ?
> Basically this adds a special func for radio with customisable switches, with 2 params:
> - which switch ? SW1 to SWx (num function switch)
> - duration; 0 to 25.5s, store exactly like SDLogs (value is in tenth of seconds)

Yes

**Comment by elecpower** [comment]
Subject to a blunder on my part, I'm done, so back to you to test.

**Comment by 3djc** [comment]
Seems to work perfectly ! Thanks @elecpower  !

**Comment by pfeerick** [comment]
Firmware (T20) and Companion (linux) LGTM :)

**Pull request merged**
