### PR TITLE
Model templates for color radios

### PR DESCRIPTION
**Pull request by jfrickmann**
Here is what I cooked up after the brief discussion on Discord 🤓 

Model templates are now stored in sub folders under /TEMPLATES. The templates are just regular YAML model files that are read after a model is created. Thus they can have everything that a model has, including widgets and Lua scripts etc.

- Each sub folder can have a file named about.txt with a general description of the template collection in that folder.
- The template YAML file names are shown in the list of templates. Typically, this should also be the name of the model in the YAML file, although it does not have to be.
- If there is a text file with the same name, then it is shown as a description of the model template.
- Models can be saved as templates, and these go in the PERSONAL sub folder.
- I have included some example files here that you can use for testing. The SoarETX/F3K template is a snapshot of my development, and if you load the Lua files under WIDGETS, then you can see how it loads them "out of the box".

I believe that templates have the potential to bridge the gap between these "nerd radios" and the main brand radios, if we make some good standard templates with simple, user-friendly interfaces for model setup based on Lua scripts and widgets.

I have not made anything for BW radios, and since that will mostly be a do-over, I will save that for a later time. We should also discuss if the small BW radios have enough storage and RAM for more features like this one?

[ModelTemplatesSD.zip](https://github.com/EdgeTX/edgetx/files/8011244/ModelTemplatesSD.zip)

### CODE REVIEW

**Comment by elecpower** [comment]
I prefer CUSTOM to PERSONAL for the user versions folder name as once any settings are modified they become personal.
Can we please have all files in YAML format if they are intended to be read by radio or Companion.
If it is pre-packaged a model then it should copy the supporting files to the correct places on the SD card and handle overwriting of existing files.

**Comment by jfrickmann** [comment]
> I prefer CUSTOM to PERSONAL for the user versions folder name as once any settings are modified they become personal. Can we please have all files in YAML format if they are intended to be read by radio or Companion. If it is pre-packaged a model then it should copy the supporting files to the correct places on the SD card and handle overwriting of existing files.

I guess it's just a matter of choosing a name. I prefer PERSONAL, because it is your own personal templates that you saved from your own models, as opposed to templates that you got from other sources.

Everything that the radio reads is YAML here. The text files are comments for the user to read.

My intention with this is to provide my own SoarETX templates for sailplane models. And I will do that by submitting it to the standard SD-card content. I hope that other providers of popular model templates will do the same, so radios can come with a good selection of high quality model templates with scripts and widgets ready to go "out of the box".

**Comment by pfeerick** [comment]
I've not looked at this yet, but it might also be a good idea to give input in https://github.com/EdgeTX/edgetx/pull/1374 as to how this would look once that is in place ;) I really like where you are headed with this though!

**Comment by jfrickmann** [comment]
We can label the models with the name of the template folder and template that they were created from.

But I find it important that we have separate folders for the template collections, to make it easy to add a new collection of templates to our radios.

**Comment by pfeerick** [comment]
I was wondering more perhaps should we add a button for Templates to that UI, or perhaps link it to new model - i.e. Prompt whether you want to use a template, or create an empty model? Or perhaps they just get labeled as templates, and when you try to 'open' them it forces a new model to be created.

**Comment by jfrickmann** [comment]
> I was wondering more perhaps should we add a button for Templates to that UI, or perhaps link it to new model - i.e. Prompt whether you want to use a template, or create an empty model? Or perhaps they just get labeled as templates, and when you try to 'open' them it forces a new model to be created.

It is linked to a new model. If the TEMPLATE folder with sub folders exists, then you can select a template. If you press RTN then it will just create the usual basic model. There is a new item on the popup menu for models to save as template.

Why don't you take it for a spin and see for yourself 😎

**Comment by JimB40** [comment]
What about PRESETS?

**Comment by pfeerick** [comment]
That is something different, and is basically what I think R has mind to work towards - basically blocks of code like LS as you suggest - which are also reusable so can be changed in one place, or imported into the model and thus have unique settings for that model.

**Comment by pfeerick** [comment]
Right, so from my preliminary testing, this looks and works great. My only peeve with it is the assumption (presumption?) that user will want to load from a template - i.e. create new model always takes you to the templates screen. Perhaps a prompt for Blank Model or From Template? Or at least a button on that screen that you can press if you don't want to use a template? I know we could document the workflow to now be 'Press RTN at template screen if you don't want to use template when creating a model" but I think it should be "blindingly obvious" in order to prevent "why can't I skip" support questions. 

It might even be worth putting a button in the template header bar, as then we could possibly also put another one in later to trigger the wizard loader...

**Comment by jfrickmann** [comment]
I can certainly add a "Blank Model" button somewhere that does the same as pressing RTN. Or we can make a folder with "Basic Models" where there is a "Blank Model" template among others?

As for model wizard scripts, these are just regular standalone scripts, right? We could do the following: if there is a .lua file with the same name as the .yml file in the template subfolder, then it fires it up after the model has been read from the .yml file. That way, people can have matching model templates and wizard scripts.

**Comment by pfeerick** [comment]
At this point, I would prefer just a nice bit fat "Blank Model" button - minimal presses/clicks to access - which as you say is basically the same as RTN, but looks nicer and more understandable to end user IMO. But that could certainly be included as part of a standard templates library that can be fleshed out later. 

Yes, they're just standalone scripts - ones in `\SCRIPTS\WIZARD`, which I added the simple frontend for in `\SCRIPTS\TOOLS`. You could certainly add facility for templates that have their own setup script if you wish, but I was thinking when adding the 'blank model' button keeping in mind future addition of another button for the generic wizard loader, as it would make it easier to access for those people who do want it. It's entirely up to you if you want to add this now, or later. I only see the first part being a blocker for merging this now. If you can easily add the rest in the next couple of days that would be great! :)

**Comment by jfrickmann** [comment]
Your "Blank Model" button has been added as requested!

**Comment by jfrickmann** [comment]
Now if there is a Lua script with the same name as the template file, then it is run. You can test it by
- Create a blank model and save it as a template
- Save the following little Lua script in the same folder and with the same "first name" as the template file:
```
local function run(event)
  chdir("/SCRIPTS/WIZARD")
  return "plane.lua"
end

return { run = run }
```

**Comment by jfrickmann** [comment]
I made a WIZARD template folder with simple models and scripts that load the Lua wizard scripts in 
https://github.com/EdgeTX/edgetx-sdcard/pull/53

**Comment by pfeerick** [comment]
This seems to be working great now. I don't see any major remaining issues in scope of this PR - i.e. the lua screen buffer is rearing it's ugly head again here, but that needs to be fixed elsewhere, not here. There are some minor sizing changes I'd like to see for better touch usability or better compability with the NV14, but I can make most of those myself so will do that later today. I'll merge this now so it's in the next nightly for more exposure, and then we can do any follow tweaks. Thank you for this! :)

**Comment by rotorman** [comment]
@jfrickmann can you please have a look from 1:45 mark RCVR video about model templates - the model picture shows up only after leaving the screen and coming back to it: https://youtu.be/w4u6PZSYvYM?t=107

**Comment by pfeerick** [comment]
I'm not so sure that second issue is anything to do with templates, and more to do with either the source file name, or sd viewer itself... if you look closer... the first file has first two letters capitalised, last one lowercase. The second and third files both have first letter capitalised, second and third letters lowercase. This is even though for YAML are all using the constant - YAML_EXT - which is `.yml`. So the file manager view will probably want some TLC at some point, to show file extensions consistently, regardless of if they have been created by the radio or by the user radio. 

image

**Comment by jfrickmann** [comment]
Please see #1709 for a fix to the image update.

I think that the capitalization has to do with the FAT file system being case-insensitive, yet allowing lower and upper case. I vaguely remember a similar situation where I could not fix the case after it had been written the wrong way. I deem that out of scope for this PR 😁

**Comment by pfeerick** [comment]
Yes, there was another issue where had to do some fancy handling for that... FYI, just to split hairs :-P ... FAT is actually "case-insensitive, case-preserving"... just to make life hard. In other words, it is technically case insensitive, but it still preserves the exact case used to create files :-O So it's up to individual systems whether they want to show the case as it is, or enforce all upper, or all lowercase.

**Pull request merged**
