### PR TITLE
T-pro support

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Many thanks to @3djc!

### CODE REVIEW

**Comment by 3djc** [comment]
Reading this might be needed : https://github.com/opentx/opentx/wiki/Function-switches

**Comment by raphaelcoeffic** [comment]
This is probably still missing actually building the binaries as part of GH actions.

**Comment by elecpower** [comment]
The switches are not available for use in any of the switches lists in Companion. Is @3djc looking after this?

**Comment by raphaelcoeffic** [comment]
> 

Not sure, but I must admit that it is not my priority number one, as long as YAML is not supported in Companion.

**Comment by raphaelcoeffic** [comment]
TODO:
- [ ] fix USB strings (still says FrSky 😅)

**Pull request merged**
