### PR TITLE
fix: flash progress text stuck at device reset

### LINKED ISSUE #3695: 2.9 - When writing the firmware on external module sentence is wrong
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I just noticed today that when I write the firmware of the FrSky R9M module with ELRS during the flash at the bottom the words "module reset" remains even while writing as seen in the image, when it should only appear initially and then write "writing in progress".

### Expected Behavior

It should do what I wrote above, I tried it with an older EdgeTX firmware (2.8) and in fact it works.
I don't think the problem is in the language, IT is correct, here the two different sentences, the second one should appear while writing:

#define TR_DEVICE_RESET                 "Resetto dispositivo..."
#define TR_WRITING                         "Scrittura..."

### Steps To Reproduce

1. Flash the latest master (2.9)
2. Write ELRS firmware to external module

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

Windows 10 Pro x64

### Anything else?

immagine

### PR DESCRIPTION
**Pull request by mha1**
fixes #3695

### CODE REVIEW

**Comment by mha1** [comment]
The fix is not module dependent. Nevertheless it should be tested with all sorts of modules.

**Comment by mha1** [comment]
Forgot: tested ok on TX16s internal and (my brand new) external RM 4in1 nano MPM

**Comment by mha1** [comment]
nicer version still working on TX16s internal and external MPM

**Comment by pfeerick** [comment]
Working perfectly again with XJT, STM32 ELRS and int MPM update on TX16S. Nicely done, thank you! :)

**Comment by ParkerEde** [comment]
Working perfectly with int. ISRM and ext. MPM on Horus X10S Express

**Comment by pfeerick** [comment]
Thanks for testing! :)

**Pull request merged**
