### PR TITLE
fix: BT defined on T15

### LINKED ISSUE #5414: Blckscreen after config change
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If you Compiler with bluetooth and switch it on in telemetry Mode it you get a Black screen

### Expected Behavior

No Black screen

### Steps To Reproduce

Look videl

Get back by plug in usb open companion select by blind usb sd card on Jumper (maybe several Times to get it 🫤)
Deaktivate Bluetooth telemetry by companion
Write config restaet junper

### Version

2.10.3

### Transmitter

Other (Please specify below)

### Operating System (OS)

Windows

### OS Version

Windows 

### Anything else?

Jumper t15

https://github.com/user-attachments/assets/19fc4287-2100-4358-a1da-be27a40dad74

### PR DESCRIPTION
**Pull request by 3djc**
This radio needs to use aux1 for BT, with no enable pin. (WIll not work with FrSky module, but should with DIY ones)

Fixes #5414

This is untested since I don't have a BT module

### CODE REVIEW

**Comment by pfeerick** [comment]
When you say untested, does fix the black screen issue, since presumably that didn't need bluetooth module? ;)

**Comment by druckgott** [comment]
I can test it, but how can I bulid it with bluetooth
grafik

**Comment by pfeerick** [comment]
@druckgott  [t15-31a49cf8d.zip](https://github.com/user-attachments/files/16642883/t15-31a49cf8d.zip)

**Comment by 3djc** [comment]
@pfeerick https://github.com/EdgeTX/edgetx/pull/5448 updated

**Comment by druckgott** [comment]
so its working no blackscreen anymore. Local Adress and so on is not working with a "normal" bluetooth modul.

Can it work with this? I have one off this moduls also here:
https://www.instructables.com/Bluetooth-on-Radiomaster-TX16S/

**Comment by 3djc** [comment]
Clearly will not work with a normal BT module, you need one emulating frsky BT trainer module, something like this : https://btwifimod.gitbook.io/untitled

**Comment by druckgott** [comment]
I checked it but there is comming up next probleme. Prinzipiell its working with the upper modul, but on trainer mode scann it crash:
https://github.com/EdgeTX/edgetx/issues/5454

**Pull request merged**
