### PR TITLE
Fix NV14 modules and protocols

### LINKED ISSUE #836: NV14 Internal Module protocol
@elecpower Just noticed that for the NV14 it's showing AFHDS3 for the internal module protocol instead of AFHDS2A

Also, whilst I beleive the RF output power can be changed, that isn't exposed in the settings atm, but I don't know which side is right as far as the bin file settings (i.e. simply missing from interface, or Companion shouldn't be showing it). 

image

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #836
Checked using NV14 libsim with AFHDS2A and AFHDS3A enabled.
2A mirrors settings BUT 3 does not for freq and mode. I have been looking at this for a couple of days with no luck. So time for some fresh eyes. Not pointing fingers but it may even be the radio code as the data dumps from the import/export appears okay.

Note: I have only commented out the debugging info in the import/export for the time being until the NV14 is finalised.

### CODE REVIEW

**Comment by elecpower** [comment]
@raphaelcoeffic thanks for the feedback. I catered for this repurposing albeit clunky. The mode is set and read fine for 2a. The freq is not displayed for 2A so only have 3 to see its interpretation.

PS considering the module type limit has been reached, are you planning to refactor modules and protocols anytime soon as this needs a major rewrite in Companion to clean up and simplify? The field remapping and reuse makes adding new modules and protocols, maintenance and diagnosis a pain. After having to plug the NV14 in I was considering a revamp but if changing I would hold off.

**Comment by eshifri** [comment]
AFAIK AFHDS3 does not work on the NV14 radio itself with the current SW.

**Comment by elecpower** [comment]
@eshifri yeah saw it commented out as an option though did enable to build the libsim for testing the display and edit of the settings between it and Companion settings only as this assists in checking the settings import and export mapping magic needed.

**Comment by raphaelcoeffic** [comment]
> PS considering the module type limit has been reached, are you planning to refactor modules and protocols anytime soon as this needs a major rewrite in Companion to clean up and simplify? The field remapping and reuse makes adding new modules and protocols, maintenance and diagnosis a pain. After having to plug the NV14 in I was considering a Companion revamp but if changing I would hold off.

Yes, this planned right after the YAML integration, which should give us this liberty.

**Pull request closed without merging**
