### PR TITLE
multi: move the TQly & TRSS hack where it belongs

### LINKED ISSUE #1139: TX16S TQly and TRSS telemetry missing
I noticed that the TQly and TRSS telemetry sensors were suddenly dead in my models using FrSkyX2 D16 the last couple of days. I confirmed that something changed after Nov 20th because I flashed to a bin I compiled on the 20th and they are working again. Flashed back to a current nightly and they stop working again.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #1139

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
The issue is that basically everywhere, `telemetryProtocol` is used to determine certain things. This is just not true, as you can have multiple of them, as you can get telemetry from multiple modules. I tried to tackle that a bit when dealing with the internal CRSF. However, it has certain drawbacks for this kind of hacks.

Let's face it, this is a plain hack! MPM should generate a proper separate package, instead of highjacking an existing one (RSSI)

**Comment by pfeerick** [comment]
Before this PR, no TRSS and TQly, with this PR, they were detected. I have my doubts about the TRSS value, as it seems to be pegged at 120dB, but it could also just be the receiver I'm using since it does have full range ears on it (and is sat next to the transmitter :grin: )

@rburrow87 Are you able to give this a try and see if they behave like you remember?

**Comment by raphaelcoeffic** [comment]
>  it seems to be pegged at 120dB

That should be fixed now.

**Review by pfeerick — APPROVED** [review]
Perfect! TRSS and TQly are now present and behaving like I thought they used to on TX16S and TX12. Also had independent confirmation on Discord from another TX16s user.

**Comment by piotrva** [comment]
The commit did not triggered companion build/tests, while actually causing companion to fail to build as per connection through simulation...

**Comment by rburrow87** [comment]
Sorry I didn't get to it sooner, had a busy day. Seems like TRSS and TQly are good now!

I noticed that build issue too when trying to compile tonight.

**Pull request merged**
