### PR TITLE
feat(GT911): Add CLI command to reset touch panel config

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Related to #2063

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@wimalopaan it seems the config can be perfectly reseted with this CLI command.

On my TX16S, this leads to the following output:
```
> reset_gt911
GT911: old config version is 65
GT911: new config version is 0
```

On the next reboot, the config number read is `65` ('A'), as I had `GT911_CFG_NUMBER` set to `'A'` for test purposes.

**Comment by wimalopaan** [comment]
Thats great! I had no luck with that on my controller ... and I verified all communication with a LogicAnalyzer. But anyway, very cool to have the intercative setting command!

**Comment by raphaelcoeffic** [comment]
This has been tested today on a X12S and allows for removing the software inversion. For those who installed @wimalopaan ’s builds, it might work already (when software inversion is gone), for the others, a config reset via CLI will be needed.

**Comment by raphaelcoeffic** [comment]
I’ll try to have something more “automatic” if I get to it, but that should already release the pain.

**Comment by pfeerick** [comment]
Given how often this would be needed, this should be enough. And/or we add a button to the hardware tab (for that radio, if touchscreen enabled) to reset the touchscreen config (might also be good to show the current setting on the diags screen)...

**Comment by pfeerick** [comment]
FWIW, mine was 109 ... I won't make any IQ jokes as I'll surely lose! 🤣 


https://user-images.githubusercontent.com/5500713/192137446-4fdcd3c0-8b20-4144-a1a4-b7f65b87d107.mp4

**Comment by raphaelcoeffic** [comment]
> FWIW, mine was 109

This is normal, see current definition:
```c++
#define GT911_CFG_NUMBER        0x6D
```

**Comment by pfeerick** [comment]
Perfect! :) I'll leave it for a day to give Kevin from the related issue a chance to respond, and then merge.

**Pull request merged**
