### PR TITLE
refactor(mixer): improve delays

### LINKED ISSUE #4254: Delay doesn't work in interaction with Flight Modes
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When Delay is set on any mixer line, if any Flight Mode is unchecked, Delay won't work, no matter what the currently active Flight Mode actually is.

### Expected Behavior

Delay should work kor any assigned flight mode, even if not assigned for all flight modes.

### Steps To Reproduce

In this example, CH1 responds to a change in the source value two seconds after that value changes, as expected. But CH2, which is the same as CH1 except that it has one or more flight modes excluded, ignores the Delay setting and changes immediately.

Code:
```
CH1     SF Weight(+100%) Delay(u2:d2)

CH2     SF Weight(+100%) Flight modes(FM0:FM0, FM2:FM2, FM3:FM3, FM4:FM4, FM5:FM5, FM6:FM6, FM7:FM7, FM8:FM8) Delay(u2:d2)
```

### Version

2.9.1

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

_No response_

### Anything else?

This is a port over from an OpenTX discussion found starting here:[https://www.rcgroups.com/forums/showpost.php?p=51655957&postcount=10106](https://www.rcgroups.com/forums/showpost.php?p=51655957&postcount=10106)

Confirmed as an issue with Edge here:[https://www.rcgroups.com/forums/showpost.php?p=51658113&postcount=5860](https://www.rcgroups.com/forums/showpost.php?p=51658113&postcount=5860)

Thanks to user MiamiMike for "Steps to Reproduce" clipped from his post on RCGroups.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This PR removes the distinction between following with respect to how delays are handled:
- a conditional mixer line (using a set of flight modes and/or conditional switch),
- a non-conditional one.

Fixes #4254

### CODE REVIEW

**Comment by philmoz** [comment]
Looks ok to me. I was looking at this yesterday and your solution is almost exactly the same as what I came up with.

One thing, not directly related to this issue, is that the 'stickIndex' variable is redundant.
Change line 794 to:
    mixsrc_t srcRaw = md->srcRaw;
and you can delete stickIndex.

**Comment by raphaelcoeffic** [comment]
@pfeerick we should probably mention this in the release notes. Just in case someone had set something in the delays that was ineffective then, but would be now.

**Review by 3djc — COMMENTED** [review]
Looks good to me, I think time to rework fully the mixer is closing, no matter how scary

**Comment by gagarinlg** [comment]
Only with unit tests with close to 100% code coverage

**Comment by pfeerick** [comment]
Can't see anything broken here... only fixed :grin: Servo auto test delay/slow mixer, and various switch-based slow/delay with FM conditionals working as expected.

**Pull request merged**
