### PR TITLE
feat: add ability to disable trainer warning on shutdown

### LINKED ISSUE #4818: Add New Radio or Model Config Option to disable Trainer Still Connected warning at shutdown
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

With a perpetually connected Nano BLE Sense Rev 2 connected to the Aux_ UART ports (as a Headtracker BLE Receiver), on the Radio Master TX16S MKII and MT12 radios (being configured as Radio Aux_ SBus Trainer | Model Master Trainer), when powering down the radio, there is a nuisance warning of Trainer Still Connected.

### Describe the solution you'd like

It is desired to have a config option to suppress this warning at power down, as the Arduino SBC BLE radio is perpetually connected internally - a warning of a perpetual condition is not warranted.

### Describe alternatives you've considered

I've considered both approaches of having this option in the radio hardware or the model configuration.  Warning suppression is the feature desired, whether the option is broad (done in Radio configuration) or model-specific (done in Model configuration) is moot, as long as the goal of removing the nagging warning can be attained.  Thank you, in advance.

### Additional context

I experience this issue on my TX16S MKII color LCD radios and B&W MT12 radio.

### PR DESCRIPTION
**Pull request by 3djc**
Add ability to disable "trainer connected" warning on shutdown

This closes #4818

### CODE REVIEW

**Comment by pfeerick** [comment]
lol... there goes my plan to do this week... and I did self-assign to myself too!

**Comment by 3djc** [comment]
Sorry sorry sorry !

**Comment by ulfhedlund** [comment]
SE translation:
#define TR_TRAINER_SHUTDOWN_ALARM          TR("Lärare alarm", "Kolla läraranslutningen")

**Comment by pfeerick** [comment]
Yes, it's me again! Can we get some translations for this please 😃 

image
image

```cpp
#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trainer shutdown", "Check trainer on shutdown")
```
- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [x] SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU

**Comment by zandorsp** [comment]
PT
"Trainer shutdown", "Check trainer on shutdown"

**Comment by zandorsp** [comment]
PT
#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trainer ao desl", "Checar trainer ao desligar")
#define TR_RSSI_SHUTDOWN_ALARM         TR("RSSI Deslig.", "Checar RSSI ao desligar")   

Please include update of the #define TR_RSSI_SHUTDOWN_ALARM for standardization purpose

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trainer shutdown", "シャットダウン時にトレーナーをチェック")

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_TRAINER_SHUTDOWN_ALARM TR("Trener wyłączanie", "Sprawdzaj trener przy wyłączaniu")
#define TR_RSSI_SHUTDOWN_ALARM TR("RSSI wyłączanie", "Sprawdzaj RSSI przy wyłączaniu")
```

**Comment by ParkerEde** [comment]
DE
#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trainer-Chk aus?", "Prüfe Trainer bei Ausschalten")

**Comment by HThuren** [comment]
DA
#define TR_TRAINER_SHUTDOWN_ALARM       TR("Træner alarm", "Kontroller træner forbindelse")

**Comment by HThuren** [comment]
DA
Sry I missed..
#define TR_RSSI_SHUTDOWN_ALARM TR("RSSI alarm", "Kontroller RSSI forbindelse")

**Comment by robustini** [comment]
IT

#define TR_TRAINER_SHUTDOWN_ALARM      TR("Spegnimento Trainer", "Controllo trainer allo spegnimento")

**Comment by Pat6874** [comment]
FR:

#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trainer shutdown",
"Vérifier écolage avant extinction")


If too long:

#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trainer shutdown", "Vérif.
écolage avant arrêt")


Le dim. 5 mai 2024 à 12:52, Marco Robustini ***@***.***> a
écrit :

**Comment by Eldenroot** [comment]
CZ:

#define TR_TRAINER_SHUTDOWN_ALARM      TR("Trenér vypnutí", "Kontrola trenéra při vypnutí")

**Comment by kobakirill** [comment]
RU
#define TR_TRAINER_SHUTDOWN_ALARM      TR("ВЫК Тренер", "Проверьте работу тренера при ВЫКЛ")

**Comment by zyren** [comment]
CN

```c
#define TR_TRAINER_SHUTDOWN_ALARM      TR("关机检查教练", "关机时检查教练信号")
```

************************************************

TW

```c
#define TR_TRAINER_SHUTDOWN_ALARM      TR("關機檢查教練", "關機時檢查教練信號")
```

**Pull request merged**
