### PR TITLE
move sourcechoice and switchchoice to ChoiceEx implementation

### PR DESCRIPTION
**Pull request by kevinkoenig**
this PR depends on a PR in libopenui that moves and enhances ChoiceEx.  much cleaner implementation.

### CODE REVIEW

**Comment by rotorman** [comment]
@kevinkoenig I assume, you are referencing the following libopenui PR: https://github.com/EdgeTX/libopenui/pull/18

**Comment by kevinkoenig** [comment]
I am.  I guess I should have referenced the PR #.  Sorry.

Kevin

Sent from Mail for Windows

**Comment by pfeerick** [comment]
Isn't this for the getTicks line?

ie.. from https://github.com/EdgeTX/libopenui/pull/18

https://github.com/EdgeTX/libopenui/blob/c4336b262ef94551951ffde5ddc776e0818d6e42/src/choiceex.cpp#L36

**Comment by kevinkoenig** [comment]
Well I needed to get ticks to test for long press.  So I need a callback for that.  If there is a way to get ticks in libopenui directly I can fix that

**Comment by eshifri** [comment]
case CURVE_REF_CUSTOM: {
        auto choice = new ChoiceEx(curveParamField, rect, -MAX_CURVES, MAX_CURVES,
                                 GET_SET_DEFAULT(line->curve.value), get_tmr10ms);

ChoiceEx::ChoiceEx(FormGroup * parent, const rect_t & rect, int vmin, int vmax, std::function<int16_t()> getValue, std::function<void(int16_t)> setValue, WindowFlags windowFlags) :
  Choice(parent, rect, vmin, vmax, getValue, setValue, windowFlags)

**Comment by pfeerick** [comment]
No, per the linked PR https://github.com/EdgeTX/libopenui/pull/18

https://github.com/EdgeTX/libopenui/blob/c4336b262ef94551951ffde5ddc776e0818d6e42/src/choiceex.cpp#L36
```
ChoiceEx::ChoiceEx(FormGroup * parent, const rect_t & rect, int16_t vmin, int16_t vmax, std::function<int16_t()> getValue, std::function<void(int16_t)> setValue, std::function<uint32_t()> getTicks, WindowFlags windowFlags) :
  Choice(parent, rect, vmin, vmax, getValue, setValue, windowFlags)
```

**Comment by pfeerick** [comment]
You have absolutely perfect timing... I was just about to open this PR up when you commited ;) It by itself seems to fix the textedit widget "keyboard crash" but as you said on the libopenui PR - lets fix it properly there since it's the root culprit. This, in conjunction with https://github.com/EdgeTX/libopenui/pull/18 is working fine for me. But because https://github.com/EdgeTX/libopenui/pull/19 includes all the PR#18 changes since it's probably based on the PR#18 branch rather than libopenui master, that should be merged instead since it will do both (unless you want to clean PR#19 up to only be the crash fix).

**Review by pfeerick — APPROVED** [review]
LGTM and fixes the top bar crash. Just waiting for checks to confirm formatting changes didn't mess anything up before merging.

**Pull request merged**
