### PR TITLE
R9M Flex power option menu for colorlcd

### PR DESCRIPTION
**Pull request by Arvycka**
Adds power selection menu for R9M Flex (ACCST, pre 2019) on colorlcd radios. Tested working on a tx16s.
https://github.com/EdgeTX/edgetx/issues/1187

### CODE REVIEW

**Comment by Arvycka** [comment]
I'm not a dev and probably it's not how it's supposed to be done, but I tested it on my radio and found working fine. 
screen-2022-04-23-155402

**Comment by pfeerick** [comment]
I'll look at this properly in the morning, but I think this may be able to be done much simpler. i.e. looking at this as it is, it is simply a matter of adding two more conditions to the first choice, no need to duplicate the label and choice code again. But I'll have to look and make the options are right. But thank you for the hint ;)

**Comment by Arvycka** [comment]
Oh, right, good point!

**Comment by pfeerick** [comment]
Would you be able to double-check this for me? It should do the trick, as that check is basically just "if not EU".

**Comment by Arvycka** [comment]
> Would you be able to double-check this for me? It should do the trick, as that check is basically just "if not EU".

Tested, it's working. RF power menu is present in all modes. Thanks.

**Comment by pfeerick** [comment]
Thanks, perfect! :)

**Pull request merged**
