### PR TITLE
NV14/EL18 Added reboot when detect USB is plugged.

### LINKED ISSUE #2725: EL18 switch off with USB connected will enter emergency mode
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When the radio is switched off with USB connected, it will enter emergency mode.

### Expected Behavior

When the radio is switched off with USB connected, it should enter charging mode.

### Steps To Reproduce

1. Switch on radio
2. Connect USB and select storage
3. Switch off radio
4. Emergency mode

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #2725

Summary of changes:

### CODE REVIEW

**Comment by richardclli** [comment]
Seems works, but still need some more work, please help:

1. Shutdown when USB is plugged in will have ugly screen fades, cna this be improved?
2. It works for all USB modes except USB storage, USB storage did not even have a popup to warn USB is connected, what is wrong about the detection when USB storage is used?

**Comment by pfeerick** [comment]
> 1. Shutdown when USB is plugged in will have ugly screen fades, cna this be improved?

Do you mean when being reset to charge screen? Perhaps need to clear/reset/turn off the LCD first.

**Comment by richardclli** [comment]
> > 1. Shutdown when USB is plugged in will have ugly screen fades, cna this be improved?
> 
> Do you mean when being reset to charge screen? Perhaps need to clear/reset/turn off the LCD first.

Yes, but do you have the code in switching off the LCD?

**Comment by pfeerick** [comment]
NV14 has `lcdOffFunction()` which is supposed to issue the right off command depending on the LCD fitted.

**Comment by richardclli** [comment]
> NV14 has `lcdOffFunction()` which is supposed to issue the right off command depending on the LCD fitted.

Let me check this out.

**Comment by richardclli** [comment]
So not this should be now considered done.  Why USB Storage now working is another issue.

**Comment by richardclli** [comment]
Works with USB storage with this PR:

https://github.com/EdgeTX/edgetx/pull/2743

**Comment by pfeerick** [comment]
I rebased this on `main` as #2743 is merged and built locally - worked perfectly with NV14 and EL18 :) Rebooted with no screen into charge screen.

**Pull request merged**
