### PR TITLE
Removed unused code referencing the LCD backup buffer

### PR DESCRIPTION
**Pull request by jfrickmann**

### CODE REVIEW

**Comment by pfeerick** [comment]
Are you pursuing the "last standalone app shown while loading" issue? If so, you may actually need these functions ;) If you look at

```cpp
void StandaloneLuaWindow::attach(Window* newParent)
{
  Window::attach(newParent->getFullScreenWindow());
  Layer::push(this);
  setFocus();
}
```

*if* you alter the `LCD_BACKUP_FRAME_BUFFER` _before_ the layer is pushed, the content of `LCD_BACKUP_FRAME_BUFFER` is what will be shown whilst the app is busy loading... i.e. I added `lcdStoreBackupBuffer();` before the Window::attach(), and instead of showing the last app, it now shows the last frame from the radio setup screeen (or perhaps last alternate frame)

Perhaps the perfect place to clear that buffer, and put a "FAT PROGRAM LOADING... PLEASE WAIT" msg? 😆 

Doing it here should catch both TOOLS and / SD browsing triggers of LUA scripts. 

Something to think about, anyway, as I was going to suggest culling all of  the `LCD_BACKUP_FRAME_BUFFER` manipulation function for NV14, horus and simu targets, since `standalone_lua.cpp` seems to be the only time any of them are used, but it could be one of those half-implemented features also...

**Comment by jfrickmann** [comment]
Actually, that was not on my mind at all! I was just digging around trying to understand how it works, and noticed that these lines of code were unused. Please see #1011 for what was on my mind 😎 

Couldn't we just call `BitmapBuffer::drawSolidFilledRect(x, y, w, h, flags)` to clear it before pushing the layer?

**Comment by pfeerick** [comment]
I was initially thinking about something like this
```cpp
  BitmapBuffer buffer(BMP_ARGB4444, LCD_W, LCD_H, lcdGetBackupBuffer());
  buffer.drawSolidFilledRect(0, 0, LCD_W, LCD_H, COLOR2FLAGS(BLACK));
```
since it both clear the buffer *and* show up whilst you wait for a fat app to load... i.e. I know of one in particular that takes a good two seconds to load before it starts writing to the screen... but the issue then is it will flash up when you load *any* app then... I would prefer to grab the last screen state, draw a message on it, and then present that... which will be much less noticeable than a flash to back and loading of the app...

i.e. something like this, but done properly & prettier... you basically see the message pop up, but since it's over the top of either the last or second last frame, it isn't that jarring if it is a app that writes to screen immediately. 
```cpp
lcdStoreBackupBuffer();
BitmapBuffer buffer(BMP_ARGB4444, LCD_W, LCD_H, lcdGetBackupBuffer());
buffer.drawSolidFilledRect(LCD_W/2-80, LCD_H/2-25, 160, 50, COLOR_THEME_PRIMARY2);
buffer.drawText(LCD_W/2, LCD_H/2-20, "Loading", FONT(XL)|CENTERED|COLOR_THEME_PRIMARY1);
```

**Comment by jfrickmann** [comment]
Ahh, OK. So you are actually planning to use the functions that I wanted to remove here? In that case, please feel free to dump this PR, and carry on with what you are doing there 😎 
But please see if the unused prototype in view_main_menu.cpp can be removed.

**Comment by pfeerick** [comment]
Nah, just spitballing atm... we'll see how things turn out. ;)

**Comment by pfeerick** [comment]
I'm going to close this as either this code will end up being used, or will be made redundant anyway as part of LVGL and be stripped out then.

**Pull request closed without merging**
