### PR TITLE
fix(access): ported pop-up dialogs to flex layout

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Currently based on #2100 and shall be rebased once that PR is merged.

Needs https://github.com/EdgeTX/libopenui/pull/58

### CODE REVIEW

**Comment by rburrow87** [comment]
The color screen ACCESS menus are much better! And I am no longer getting any telemetry dropouts on my X12S ISRM or X9D+2019.

I noticed the Page Up/Down buttons don't work on the model setup screen when the cursor is on Model name. If I scroll to any other element, it works fine. Doesn't happen in the nightly.
screen-2022-08-06-155148

And unless this is outside of the work you did with fixing up the dialog windows, there should be a receiver number/model ID field for ACCESS too 😬https://github.com/EdgeTX/edgetx/issues/2146

**Comment by raphaelcoeffic** [comment]
@rburrow87 `Page Up/Down` should work again now, and receiver ID has been added.

**Comment by rburrow87** [comment]
Looks good to me! 😀

**Comment by raphaelcoeffic** [comment]
@rburrow87 no more telemetry drops?

**Comment by rburrow87** [comment]
Nope! 30+ minutes and had no telemetry drops using this PR.

**Comment by brainbubblersbest** [comment]
If that does something for 868 915 mhz menu i would try a build

**Pull request merged**
