### PR TITLE
feat(color): Manage Models page styling

### PR DESCRIPTION
**Pull request by philmoz**
Change model select page to use common button styling.
Improved sort order icons.

After:
screenshot_tx16s_23-11-13_11-58-25
screenshot_tx16s_23-11-13_12-01-49

Before:
screenshot_tx16s_23-11-13_11-59-04
screenshot_tx16s_23-11-13_12-01-09

### CODE REVIEW

**Comment by pfeerick** [comment]
Consistency is always good, and this does look somewhat nicer IMO with the rounded model icons. 

My only gripe would be around the model image size... we've gone down from around 148x88 px (model category days) to around 162x88px and now 158x65px (rough measurement off the screenshots)... although I do appreciate that the top of the image is getting clipped with the current implementation, so it's effectively 162x65px visible... I guess I'm just grumbling because it _seems_ to be getting smaller and smaller... and I'm wondering when the radios will come supplied with a magnifier sheet. Although, to be fair, it was much worse in OTX days... a tiny 58x32 image 🤪

A food for thought idea... is there any benefit to having a button in the header that can show/hide the labels sidebar completely? i.e. if you only have one label, or are happy to change with hardware keys, it's wasted screen space that can be reclaimed for showing another column of  (smaller still!!) model icons... (I'm only asking for thoughts on the matter, not implementation!!)

**Comment by philmoz** [comment]
I can fill the button with the image; but then the text can get lost. Open to suggestions.

screenshot_tx16s_23-11-14_11-46-19

**Comment by philmoz** [comment]
Or this:

screenshot_tx16s_23-11-14_12-05-24

**Comment by pfeerick** [comment]
Don't think we can do semi-transparencies / translucent, can we? Otherwise, could do a bar similar to the active one, as a fill to give the text contrast. Else, I prefer the model name centred (but would also like more feedback on that second one - as is probably just because it's *different*). What about 2, with it centred (i.e. keep the fill for contrast).

**Comment by philmoz** [comment]
The previous screenshot (text on left) has text background at 80% opacity.

Centered @ 50% opacity:
screenshot_tx16s_23-11-14_12-32-23

Centered @ 80% opacity:
screenshot_tx16s_23-11-14_12-34-24

**Comment by pfeerick** [comment]
Oh... that last one is probably the best one so far IMO 👀 I meant to say before also, I do like the whole button lighting up, rather than just the top line. Much more positive as to which is the active one.

**Comment by raphaelcoeffic** [comment]
@pfeerick @philmoz any idea how we could replace the icons for sorting? They really look *kind of ugly*.

**Comment by philmoz** [comment]
The icons were larger than the available size and were being scaled (not very well).
I scaled them to the correct size and cleaned them up.

If anyone wants to draw new icons they should be 28x28 pixels.

**Comment by pfeerick** [comment]
Might be able to pull some from icons8 ... can specify custom size of 28x28 if find usable icons... i.e. 

https://icons8.com/icons/set/sort-alpha-up
https://icons8.com/icons/set/sort-alpha-down
https://icons8.com/icons/set/sort-amount-up
https://icons8.com/icons/set/sort-amount-down

**Comment by JimB40** [comment]
alphabetical sorting can be simple "A-Z" and "Z-A"

**Comment by philmoz** [comment]
Would it be better to replace both sort buttons with a single popup menu button where the user can select sort order by name?
This would allow translated text for the different sort orders and also allow for additional options in future.

**Comment by pfeerick** [comment]
Icons were probably used to _prevent_ the need for more translations. And sure, you could put a sort button there, which also opens up room for more sort options... but you'll probably lose the ability to see what is currently selected? As I doubt you'll be able to fit both the name of the button **and** the current sort order in that space?

**Comment by philmoz** [comment]
I meant using a 'Choice' control which shows current selection.

E.G.: (Note moved 'New' button to labels long press handler)

screenshot_tx16s_23-11-15_12-52-08

screenshot_tx16s_23-11-15_12-52-14

screenshot_tx16s_23-11-15_12-52-19

**Comment by philmoz** [comment]
I took the original icons and re-scaled them with some more padding so they are not as bulky.

screenshot_tx16s_23-11-15_13-17-41

**Comment by pfeerick** [comment]
Yeah, looks fine... removing the new label button gives you the space you need. Probably need to add a titlebar ("Model sort order" / "Sort Models (by)" perhaps? making it explicitly clear it's not related to sorting the labels) to the menu so there aren't any complaints ;) 

Having the "New Label" option in the labels long press menu / context menu doesn't immediately make sense (i.e. why we don't have "new model" when you do the same for model icons? because it's not an option related to that _specific_ item)... but I don't see much else you can do (other than put in the header, which probably isn't an option for portrait). Maybe it would be better at the bottom of the list... (which you can access in one rotary click / makes no difference for touch)... I think you'd be managing labels more often than creating new ones?

**Comment by philmoz** [comment]
> Having the "New Label" option in the labels long press menu / context menu doesn't immediately make sense.

I thought that too - moving the 'New Model' button the model long press would make them both consistent (if somewhat non-standard).

Another suggestion would be to rename the 'New Model' button to just 'New' and then have it open a popup menu with the 'New Model' and 'New Label' options.

**Comment by philmoz** [comment]
Combining the last few comments:

screenshot_tx16s_23-11-15_13-53-57

screenshot_tx16s_23-11-15_13-54-02

screenshot_tx16s_23-11-15_13-54-54

**Comment by pfeerick** [comment]
If it passes the @JimB40 test that last compilation LGTM.

**Comment by philmoz** [comment]
I've updated the PR to remove the sort order icons and move the 'New Label' button to the 'New' popup menu.

This will require translations for the new strings.

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 For context, have a look at the screenshots here => https://github.com/EdgeTX/edgetx/pull/4313#issuecomment-1811730354

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @offer-shmuely HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU 

```
#define TR_SORT_ORDERS            "Name A-Z","Name Z-A","Least used","Most used"
#define TR_SORT_MODELS_BY         "Sort models by"
#define TR_CREATE_NEW             "Create"
```

**Comment by kobakirill** [comment]
RU
#define TR_SORT_ORDERS               "Имя A-Z","Имя Z-A","Редко использ","Часто использ"
#define TR_SORT_MODELS_BY         "Сортировка моделей по"
#define TR_CREATE_NEW                 "Создать"

**Comment by philmoz** [comment]
> RU #define TR_SORT_ORDERS "Имя A-Z","Имя Z-A","Редко используемые","Часто используемые" #define TR_SORT_MODELS_BY "Сортировка моделей по" #define TR_CREATE_NEW "Создать"

Thanks. Would it be possible to shorten the 'Least used' and 'Most used' translations? There is not a lot of room in the button (see screenshots above).

**Comment by kobakirill** [comment]
> > RU #define TR_SORT_ORDERS "Имя A-Z","Имя Z-A","Редко используемые","Часто используемые" #define TR_SORT_MODELS_BY "Сортировка моделей по" #define TR_CREATE_NEW "Создать"
> 
> Thanks. Would it be possible to shorten the 'Least used' and 'Most used' translations? There is not a lot of room in the button (see screenshots above).

done)

**Comment by zandorsp** [comment]
>...
> * [ ]  @zandorsp PT

> ```
> #define TR_SORT_ORDERS            "Name A-Z","Name Z-A","Least used","Most used"
> #define TR_SORT_MODELS_BY         "Sort models by"
> #define TR_CREATE_NEW             "Create"
> ```

> #define TR_SORT_ORDERS            "Nome A-Z","Nome Z-A","Último usado","Mais usado"
> #define TR_SORT_MODELS_BY         "Ordenar modelos por"
> #define TR_CREATE_NEW             "Criar"

**Comment by pfeerick** [comment]
@kobakirill There is less space on the button at the bottom of the screen than in the choice (popup) menu to show the text, but I guess you'll still get an idea of what is selected from the text shown.

**Comment by robustini** [comment]
IT
#define TR_SORT_ORDERS            "Nome A-Z","Nome Z-A","Meno utilizzato","Più utilizzato"
#define TR_SORT_MODELS_BY         "Ordina modelli per"
#define TR_CREATE_NEW             "Crea"

**Comment by froqstar** [comment]
DE

```
#define TR_SORT_ORDERS            "Name A-Z","Name Z-A","Wenig benutzt","Meist benutzt"
#define TR_SORT_MODELS_BY         "Modelle sortieren nach"
#define TR_CREATE_NEW             "Erstelle"
```

**Comment by HThuren** [comment]
da TRANSLATION:
#define TR_SORT_ORDERS            "Navn A-Z","Navn Z-A","Sidst anvendt","Mest anvendt"
#define TR_SORT_MODELS_BY         "Sorter modeller"
#define TR_CREATE_NEW             "Opret"

**Comment by ajjjjjjjj** [comment]
UX comment: "New" could have ellipsis or three dots after it to communicate there is additional context to show.

```
#define TR_SORT_ORDERS            "Nazwa A-Z","Nazwa Z-A","Najrzadziej użyty","Najczęściej użyty"
#define TR_SORT_MODELS_BY         "Sortuj modele"
#define TR_CREATE_NEW             "Utwórz"
````

**Comment by offer-shmuely** [comment]
#define TR_SORT_MODELS_BY         "סדר תצוגה"
#define TR_CREATE_NEW             "יצירה"

the right to left order is getting messed up, so I will write it in different lines

#define TR_SORT_ORDERS           

אלפביתי A-Z
אלפביתי Z-A
הכי פחות בשימוש
הכי שימושי

**Comment by Pat6874** [comment]
FR:

#define TR_SORT_ORDERS            "Nom A-Z","Nom Z-A","Dernier
utilisé","Couramment utilisé"
#define TR_SORT_MODELS_BY         "Trier modèles par"
#define TR_CREATE_NEW             "Créer"


Le ven. 17 nov. 2023 à 03:29, Peter Feerick ***@***.***> a
écrit :

**Comment by Pat6874** [comment]
Hi Peter,

I've made some translation for companion into Fr.
It's not finished,  but please give me feedback on the translation and if
possible a companion version including my translation for verification.
If it's OK, I'll continue translating the rest.
Patrick

**Comment by ulfhedlund** [comment]
SE#define TR_SORT_ORDERS            "Namn A-Z","Namn Z-A","Minst använd","Mest använd"#define TR_SORT_MODELS_BY         "Sortera modeller på"#define TR_CREATE_NEW             "Skapa"Den 17 nov. 2023 03:29 skrev Peter Feerick ***@***.***>:
Can we get some translations for this please 😃 For context, have a look at the screenshots here => #4313 (comment)
 @zyren CN / TW @Eldenroot CZ @HThuren DA @ParkerEde / @TheIsotopes / @froqstar DE @Pat6874 FR @offer-shmuely HE @robustini IT @ToshihiroMakuuchi JP @ulfhedlund SE @ajjjjjjjj PL @zandorsp PT @kobakirill RU
#define TR_SORT_ORDERS            "Name A-Z","Name Z-A","Least used","Most used"
#define TR_SORT_MODELS_BY         "Sort models by"
#define TR_CREATE_NEW             "Create"

**Comment by zandorsp** [comment]
> > ...
> > 
> > * [x]   @zandorsp PT
> 
> > ```
> > #define TR_SORT_ORDERS            "Name A-Z","Name Z-A","Least used","Most used"
> > #define TR_SORT_MODELS_BY         "Sort models by"
> > #define TR_CREATE_NEW             "Create"
> > ```
> 
> > #define TR_SORT_ORDERS            "Nome A-Z","Nome Z-A","Menos usado","Mais usado"
> > #define TR_SORT_MODELS_BY         "Ordenar modelos por"
> > #define TR_CREATE_NEW             "Criar"

Updated. Corrected.

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_SORT_ORDERS           "名称 A-Z順","名称 Z-A順","利用の少ない順","利用の多い順"
#define TR_SORT_MODELS_BY     "モデルをソート"
#define TR_CREATE_NEW             "作成"

**Comment by mhotar** [comment]
Hello. It seems I am, as always, late on the party. I like the result as is at present. Here are the icons for sorting. Just in case.
edge_sort1

**Comment by mhotar** [comment]
edge_sort_icons1

**Comment by zyren** [comment]
CN
```c
#define TR_SORT_ORDERS            "名称 A-Z","名称 Z-A","不常用","常用"
#define TR_SORT_MODELS_BY         "排序"
#define TR_CREATE_NEW             "新建"
```

TW
```c
#define TR_SORT_ORDERS            "名稱 A-Z","名稱 Z-A","不常用","常用"
#define TR_SORT_MODELS_BY         "排序"
#define TR_CREATE_NEW             "新建"
```

**Comment by adir-kro** [comment]
@pfeerick

I spoke with Ofer and we want to change the trans pls 

#define TR_SORT_MODELS_BY "סדר תצוגה"
#define TR_CREATE_NEW "יצירה חדשה"

the right to left order is getting messed up, so I will write it in different lines

#define TR_SORT_ORDERS

סידור A-Z
סידור Z-A
יותר בשימוש
פחות בשימוש

by the way please add me to the shre list to translation - thanks @pfeerick

**Comment by offer-shmuely** [comment]
thanks @adir-kro

**Comment by mhotar** [comment]
When I have it on my workspace, I tried to resort the page to get more useful space for models. It is hard to say if it is better, but I will publish it for reference anyway :)
edge_sort2

**Comment by Eldenroot** [comment]
CZ:

#define TR_SORT_ORDERS            "Název A-Z","Název Z-A","Nejméne používané","Nejvíce používané"
#define TR_SORT_MODELS_BY         "Seřadit modely podle"
#define TR_CREATE_NEW             "Vytvořit"

**Comment by offer-shmuely** [comment]
Hi
On the HE file, the order looks opposite .
The “A-Z” should be on the left side of the word

IMG_8766

**Comment by pfeerick** [comment]
> When I have it on my workspace, I tried to resort the page to get more useful space for models. 

Thanks for this Martin. It's more of a change to the current UI paradigm than is wanted at the moment, but please keep this in mind for the 3.0 rewrite.

**Pull request merged**
