### PR TITLE
Invert channel in mixer

### PR DESCRIPTION
**Pull request by eshifri**
This pull request implements #437: long press or long touch open channel selection menu on the inverted switch: e.g. if current SD position is UP, the selection will be set on !SD UP.
This required adding "long touch" option to the Window class.
As a result another trick is possible: long touch on the number changes the sign (if possible).
Long Enter press on the number also changes the sign (again, if negative numbers are allowed).

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@eshifri could you please rebase your code on the latest 2.4 branch?

**Comment by eshifri** [comment]
I did. 
Sorry, my github skills are poor.
I will re-do it tomorrow.

And I still do not understand how to handle libopenui code: I pushed it from VScode plugin and it went through, but it looks like it was not really pushed. Do I need to work with libopenui repository explicitely?

**Comment by pfeerick** [comment]
Sweet! :D 

Re: git... my suggestion would be to:
a) work on different features in their own branches... then your git commit log is only for that branch, and you can rebase or merge the main 2.4 at any time to keep things up to date as you work on it. 
b) libopenui submodule is a pain... I just keep doing `git submodule update --recursive` from the terminal (in VSCode) as VSCode's git support is a little stupid as far as wanting to push tags (and not liking that nightly keeps resetting). 

I'm learning a lot of stuff, and dabbling in EdgeTX is making me learn and use more git and C++ ;)

**Comment by raphaelcoeffic** [comment]
@eshifri I believe your rebase failed, as you should have a much smaller commit list. Once rebased, your code needs to be "force pushed", so that the branch here can see the updated history.

**Pull request closed without merging**
