### PR TITLE
feat: Voice choice now in native language

### PR DESCRIPTION
**Pull request by HThuren**
When on native language, Voice choice was still in english, now possible to change this in translation.
Example to be found in bottom at da.h

### CODE REVIEW

**Comment by robustini** [comment]
TR_VOICE_ITALIANO, not ITALINO.

**Comment by ulfhedlund** [comment]
Just wondering... would it make sense if the available languages instead are translated in the specific language, i.e:
#define TR_VOICE_ENGLISH  "English"
...
#define TR_VOICE_DANISH   "Dansk"
...
#define TR_VOICE_FRENCH   "Français"
...
#define TR_VOICE_SWEDISH "Svenska"

**Comment by HThuren** [comment]
Yes, it´s up to you. :-)
da.h has all translated to native danish.
Do the same in se.h, I won't not sure of the right spelling.

If you think always ie. TR_VOICE_DANISH will be "Dansk" I don't agree, my opinion this must be english or native language.

**Comment by ulfhedlund** [comment]
Yes, was just an idea. Perhaps not a good one ;)

**Comment by ulfhedlund** [comment]
@HThuren: if at all possible, could you update the se.h with the following. That would save another PR with these updates.

// Voice in native language
#define TR_VOICE_ENGLISH                "Engelska"
#define TR_VOICE_CHINESE                "Kinesiska"
#define TR_VOICE_CZECH                  "Tjeckiska"
#define TR_VOICE_DANISH                 "Danska"
#define TR_VOICE_DEUTSCH                "Tyska"
#define TR_VOICE_DUTCH                  "Holländska"
#define TR_VOICE_ESPANOL                "Spanska"
#define TR_VOICE_FRANCAIS               "Franska"
#define TR_VOICE_HUNGARIAN              "Ungerska"
#define TR_VOICE_ITALIANO               "Italienska"
#define TR_VOICE_POLISH                 "Polska"
#define TR_VOICE_PORTUGUES              "Portugisiska"
#define TR_VOICE_RUSSIAN                "Ryska"
#define TR_VOICE_SLOVAK                 "Slovakiska"
#define TR_VOICE_SWEDISH                "Svenska"

**Comment by pfeerick** [comment]
> If you think always ie. TR_VOICE_DANISH will be "Dansk" I don't agree, my opinion this must be english or native language.

I agree. For each language set, it should be in that native language. i.e. for the English translation, I would espect to see "German" instead of "Deutsch" ;)

@ParkerEde DE
@Eldenroot CZ
@robustini IT
@zyren CN / TW

Can you check these, make any translations as relevant for your languages:

```
// Voice in native language
#define TR_VOICE_ENGLISH                "English"
#define TR_VOICE_CHINESE                "Chinese"
#define TR_VOICE_CZECH                  "Czech"
#define TR_VOICE_DANISH                 "Danish"
#define TR_VOICE_DEUTSCH                "German"
#define TR_VOICE_DUTCH                  "Dutch"
#define TR_VOICE_ESPANOL                "Spanish"
#define TR_VOICE_FRANCAIS               "French"
#define TR_VOICE_HUNGARIAN              "Hungarian"
#define TR_VOICE_ITALIANO               "Italian"
#define TR_VOICE_POLISH                 "Polish"
#define TR_VOICE_PORTUGUES              "Portuguese"
#define TR_VOICE_RUSSIAN                "Russian"
#define TR_VOICE_SLOVAK                 "Slovak"
#define TR_VOICE_SWEDISH                "Swedish"
```

**Comment by HThuren** [comment]
se.h changed as wanted :-)

**Comment by HThuren** [comment]
German changed too in en.h

**Comment by robustini** [comment]
IT

// Voice in native language
#define TR_VOICE_ENGLISH                "Inglese"
#define TR_VOICE_CHINESE                "Cinese"
#define TR_VOICE_CZECH                  "Cecoslovacco"
#define TR_VOICE_DANISH                 "Danese"
#define TR_VOICE_DEUTSCH                "Tedesco"
#define TR_VOICE_DUTCH                  "Olandese"
#define TR_VOICE_ESPANOL                "Spagnolo"
#define TR_VOICE_FRANCAIS               "Francese"
#define TR_VOICE_HUNGARIAN              "Ungherese"
#define TR_VOICE_ITALIANO               "Italiano"
#define TR_VOICE_POLISH                 "Polacco"
#define TR_VOICE_PORTUGUES              "Portoguese"
#define TR_VOICE_RUSSIAN                "Russo"
#define TR_VOICE_SLOVAK                 "Slovacco"
#define TR_VOICE_SWEDISH                "Svedese"

About Taiwan in Italian the language is written "Taiwanese".

**Comment by robustini** [comment]
@HThuren i'm very sorry, a fix:

#define TR_VOICE_PORTUGUES "Portoghese"

**Comment by HThuren** [comment]
> Portoghese

no problem, changed now

**Comment by HThuren** [comment]
English, Danish, Swedish and Italian ready

**Comment by Eldenroot** [comment]
`// Voice in native language
#define TR_VOICE_ENGLISH                "Angličtina"
#define TR_VOICE_CHINESE                "Čínština"
#define TR_VOICE_CZECH                  "Čeština"
#define TR_VOICE_DANISH                 "Dánština"
#define TR_VOICE_DEUTSCH                "Němčina"
#define TR_VOICE_DUTCH                  "Nizozemština"
#define TR_VOICE_ESPANOL                "Španělština"
#define TR_VOICE_FRANCAIS               "Francouzština"
#define TR_VOICE_HUNGARIAN              "Maďarština"
#define TR_VOICE_ITALIANO               "Italština"
#define TR_VOICE_POLISH                 "Polština"
#define TR_VOICE_PORTUGUES              "Portugalština"
#define TR_VOICE_RUSSIAN                "Ruština"
#define TR_VOICE_SLOVAK                 "Slovenština"
#define TR_VOICE_SWEDISH                "Švédština"`

**Comment by ParkerEde** [comment]
DE
// Voice in native language
#define TR_VOICE_ENGLISH "Englisch"
#define TR_VOICE_CHINESE "Chinesisch"
#define TR_VOICE_CZECH "Tschechisch"
#define TR_VOICE_DANISH "Dänisch"
#define TR_VOICE_DEUTSCH "Deutsch"
#define TR_VOICE_DUTCH "Holländisch"
#define TR_VOICE_ESPANOL "Spanisch"
#define TR_VOICE_FRANCAIS "Französisch"
#define TR_VOICE_HUNGARIAN "Ungarisch"
#define TR_VOICE_ITALIANO "Italienisch"
#define TR_VOICE_POLISH "Polnisch"
#define TR_VOICE_PORTUGUES "Portugiesisch"
#define TR_VOICE_RUSSIAN "Russisch"
#define TR_VOICE_SLOVAK "Slowenisch"
#define TR_VOICE_SWEDISH "Schwedisch"

**Comment by zyren** [comment]
// Voice in native language
#define TR_VOICE_ENGLISH                "英语"
#define TR_VOICE_CHINESE                "中国汉语"
#define TR_VOICE_CZECH                  "捷克语"
#define TR_VOICE_DANISH                 "丹麦语"
#define TR_VOICE_DEUTSCH                "德语"
#define TR_VOICE_DUTCH                  "荷兰语"
#define TR_VOICE_ESPANOL                "西班牙语"
#define TR_VOICE_FRANCAIS               "法语"
#define TR_VOICE_HUNGARIAN              "匈牙利语"
#define TR_VOICE_ITALIANO               "意大利语"
#define TR_VOICE_POLISH                 "波兰语"
#define TR_VOICE_PORTUGUES              "葡萄牙语"
#define TR_VOICE_RUSSIAN                "俄语"
#define TR_VOICE_SLOVAK                 "斯洛伐克语"
#define TR_VOICE_SWEDISH                "瑞典语"

**Comment by HThuren** [comment]
Hi @pfeerick, Tawanise are in fact not in a special languagefile, ie. tts_tw.cpp but only tw.h, why I didn't made that #define.
I do it now for completeness :-), but it will not have the same meaning in the vioce chose box in radio software.

But this mean I need the swedish, italian, german and chinese translation, pls

**Comment by ulfhedlund** [comment]
> Hi @pfeerick, Tawanise are in fact not in a special languagefile, ie. tts_tw.cpp but only tw.h, why I didn't made that #define. I do it now for completeness :-), but it will not have the same meaning in the vioce chose box in radio software.
> 
> But this mean I need the swedish, czech, german and chinese translation for twanise, pls.

SE: Taiwanesiska

**Comment by AVIC621** [comment]
台湾仔你看不懂简体中文吗



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 22, 2022 23:29 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [EdgeTX/edgetx] Voice choice now in native language (PR #2612)

**Comment by HThuren** [comment]
> 台湾仔你看不懂简体中文吗
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Oct 22, 2022 23:29 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: Re: [EdgeTX/edgetx] Voice choice now in native language (PR #2612)

I don't understand ?

**Comment by Eldenroot** [comment]
CZ: Tchajwanština

But I am not sure, do they have own language or is this just Chinese?

**Comment by HThuren** [comment]
> 

Well, I don't know, but I think we just do it :-)

**Comment by HThuren** [comment]
@pfeerick I think we are done, ie you can merge, please.

**Comment by HThuren** [comment]
@ToshihiroMakuuchi maybe you also want to translate for the Japanese part ?

**Comment by HThuren** [comment]
@fraternl, if you still translate the Dutch part, ypu maybe will translate to this PR ?

**Comment by ToshihiroMakuuchi** [comment]
@HThuren 
Voice selection has been changed to Japanese.
I also do PR in @HThuren's branch.

JP
#define TR_VOICE_ENGLISH                "英語"
#define TR_VOICE_CHINESE                "中国語 簡体"
#define TR_VOICE_CZECH                  "チェコ語"
#define TR_VOICE_DANISH                 "デンマーク語"
#define TR_VOICE_DEUTSCH                "ドイツ語"
#define TR_VOICE_DUTCH                  "オランダ語"
#define TR_VOICE_ESPANOL                "スペイン語"
#define TR_VOICE_FRANCAIS               "フランス語"
#define TR_VOICE_HUNGARIAN              "ハンガリー語"
#define TR_VOICE_ITALIANO               "イタリア語"
#define TR_VOICE_POLISH                 "ポーランド語"
#define TR_VOICE_PORTUGUES              "ポルトガル語"
#define TR_VOICE_RUSSIAN                "ロシア語"
#define TR_VOICE_SLOVAK                 "スロバキア語"
#define TR_VOICE_SWEDISH                "スウェーデン語"
#define TR_VOICE_TAIWANESE              "中国語 繁体"

**Comment by zyren** [comment]
CN
************************************************
// Voice in native language
#define TR_VOICE_ENGLISH "英语"
#define TR_VOICE_CHINESE "中文-普通话"
#define TR_VOICE_CZECH "捷克语"
#define TR_VOICE_DANISH "丹麦语"
#define TR_VOICE_DEUTSCH "德语"
#define TR_VOICE_DUTCH "荷兰语"
#define TR_VOICE_ESPANOL "西班牙语"
#define TR_VOICE_FRANCAIS "法语"
#define TR_VOICE_HUNGARIAN "匈牙利语"
#define TR_VOICE_ITALIANO "意大利语"
#define TR_VOICE_POLISH "波兰语"
#define TR_VOICE_PORTUGUES "葡萄牙语"
#define TR_VOICE_RUSSIAN "俄语"
#define TR_VOICE_SLOVAK "斯洛伐克语"
#define TR_VOICE_SWEDISH "瑞典语"
#define TR_VOICE_TAIWANESE "中文-台湾国语"
************************************************

TW
************************************************
// Voice in native language
#define TR_VOICE_ENGLISH "英語"
#define TR_VOICE_CHINESE "中文-普通話"
#define TR_VOICE_CZECH "捷克語"
#define TR_VOICE_DANISH "丹麥語"
#define TR_VOICE_DEUTSCH "德語"
#define TR_VOICE_DUTCH "荷蘭語"
#define TR_VOICE_ESPANOL "西班牙語"
#define TR_VOICE_FRANCAIS "法語"
#define TR_VOICE_HUNGARIAN "匈牙利語"
#define TR_VOICE_ITALIANO "意大利語"
#define TR_VOICE_POLISH "波蘭語"
#define TR_VOICE_PORTUGUES "葡萄牙語"
#define TR_VOICE_RUSSIAN "俄語"
#define TR_VOICE_SLOVAK "斯洛伐克語"
#define TR_VOICE_SWEDISH "瑞典語"
#define TR_VOICE_TAIWANESE "中文-台灣國語"
************************************************

**Comment by ajjjjjjjj** [comment]
pl

// Voice in native language
#define TR_VOICE_ENGLISH                "Angielski"
#define TR_VOICE_CHINESE                "Chiński"
#define TR_VOICE_CZECH                  "Czeski"
#define TR_VOICE_DANISH                 "Duński"
#define TR_VOICE_DEUTSCH                "Niemiecki"
#define TR_VOICE_DUTCH                  "Holenderski"
#define TR_VOICE_ESPANOL                "Hiszpański"
#define TR_VOICE_FRANCAIS               "Francuski"
#define TR_VOICE_HUNGARIAN              "Węgierski"
#define TR_VOICE_ITALIANO               "Włoski"
#define TR_VOICE_POLISH                 "Polski"
#define TR_VOICE_PORTUGUES              "Portugalski"
#define TR_VOICE_RUSSIAN                "Rosyjski"
#define TR_VOICE_SLOVAK                 "Słowacki"
#define TR_VOICE_SWEDISH                "Szwedzki"

**Comment by HThuren** [comment]
hi @ajjjjjjjj, this one are missing:
#define TR_VOICE_TAIWANESE              "Taiwanese"
can you translate this too, please ?

**Comment by HThuren** [comment]
hi @pfeerick, I think we are done, please merge

**Review by pfeerick — APPROVED** [review]

**Comment by HThuren** [comment]
@pfeerick, Great, thanks :-)

**Pull request merged**
