### PR TITLE
Seconds count down for timer show elapsed option and Voice/Haptic support

### PR DESCRIPTION
**Pull request by eshifri**
Summary of changes:
first commit fixes audio time announcements for "odd" timer values.
E.g. current code when the timer is set to 1:32 will announce 1 minute 2 seconds (for elapsed option). After the fix it will be 1 minute as expected.

Second commit adds support for seconds announcement for elapsed time.
Current code will announce remaining seconds independently of the option selected.
New code will announce elapsed seconds.
I'm not convinced this is useful/good idea - hence two commits to allow selective pull in.

### CODE REVIEW

**Comment by pfeerick** [comment]
> Especially I do not understand why we cannot set haptic+voice together like we can on other radio manufactures... And even more

Probably because people have not wanted that before, or no-one has gone and writeen the code to do it ;)

> Second commit adds support for seconds announcement for elapsed time.
Current code will announce remaining seconds independently of the option selected.
New code will announce elapsed seconds.
I'm not convinced this is useful/good idea - hence two commits to allow selective pull in.

I'm also unsure about that second commit conceptually - perhaps we should be thinking about an option to control announcement of seconds, and as of when. See what happens when I actually use it ;)

**Comment by Eldenroot** [comment]
@eshifri - please check the video in this ticket:

https://github.com/EdgeTX/edgetx/issues/1892

video link:
https://www.youtube.com/watch?v=jD05KqG-c6w&t=400s

This is really missing, but thank you for your last commit!

**Comment by eshifri** [comment]
@Eldenroot Thank you for the video!
I guess I'm missing at a certain use case you have in mind, since t o me it looks like tha ETX has almost the same capabilities.
Is it really important to have the flexibility to enable countdowns for 30/20/1 second independently?
It is possible of course, but it is a lot of code since ETX supports multiple targets.

**Comment by Eldenroot** [comment]
> @Eldenroot Thank you for the video! I guess I'm missing at a certain use case you have in mind, since t o me it looks like tha ETX has almost the same capabilities. Is it really important to have the flexibility to enable countdowns for 30/20/1 second independently? It is possible of course, but it is a lot of code since ETX supports multiple targets.

I used this a lot when I had Spektrum.

Especially:
- every minute
- expiration
- 10 to 1 second - beeps

I understand that this is not simple to add and everybody prefers something different, but I find these really useful. 

I can collaborate, free to discuss - discord.

**Comment by Eldenroot** [comment]
Hi, any progress with this one? Thx

**Comment by eshifri** [comment]
I think it is implemented here. Almost completely. It does not have flexibility to enable 30 and 20 s beeps independently, but the rest is here.

**Comment by Eldenroot** [comment]
OK, do you have any plans on these mentioned above? Maybe to extend in another PR? Or anyway how to set it easily? :) thx!

**Comment by Eldenroot** [comment]
OK, I understand :) So I hope this will get soon to nightly .) thx!

**Comment by pfeerick** [comment]
Ok, I've had a chance to play with this on the radio now, and I see what you mean by the changes to voice dependent on whether show remain or show elapsed is configured. Let's leave this as it is, and see what feedback we get from nightly users... in one respect it makes sense, as it makes it so the timer value is being verbalised rather than counting down even though you have the timer configured as an elapsed timer.

**Comment by Eldenroot** [comment]
Ok, great. Maybe create a ticket with these for discussion? I believe it should be implemented someday ;)

**Comment by pfeerick** [comment]
Of course, you're free to do so if you wish. Then we can see how much interest there is for those features, and what is the best way to go about incorporating them if there is enough interest / someone wanting to work on it.

**Comment by ParkerEde** [comment]
nice. also tested with lua model.setTimer ....  extraHaptic=1. works fine

**Pull request merged**
