### PR TITLE
More translated to Danish

### PR DESCRIPTION
**Pull request by HThuren**
Changes to companion and radio

### CODE REVIEW

**Comment by HThuren** [comment]
Hi, the MacOSX test run fails due to some phyton installation process, when install qt.
I think this not are a problem to the PR itself.

**Comment by pfeerick** [comment]
Yes... there's either some breakdown with the github runners or some other package dependency/update isssue... it's not related to the PR. I retried it a couple of times in case they had a network issue but it didn't get any further.

**Comment by HThuren** [comment]
Hi pfeerick, next step, merge into main, before too much differ :-), or ?

**Comment by pfeerick** [comment]
Yup, looks good. Thanks! :)

**Pull request merged**
