### PR TITLE
Translation of range test

### PR DESCRIPTION
**Pull request by ulfhedlund**
Summary of changes:
One string TR_RANGE_TEST added to translate the window/popup title when a range test is performed on color radio.

rangeTest

Translators, please provide translation in your language for
#define TR_RANGE_TEST                  "Range test"

@ParkerEde DE
@Eldenroot CZ
@robustini IT
@zyren CN / TW
@ajjjjjjjj PL
@ToshihiroMakuuchi JP
@HThuren DA
@Pat6874 FR

### CODE REVIEW

**Comment by Pat6874** [comment]
In FR
#define TR_RANGE_TEST "Test de portée"

Le 11 mai 2023, 20:59, à 20:59, ulfhedlund ***@***.***> a écrit:

**Comment by Eldenroot** [comment]
CZ: Test dosahu

**Comment by HThuren** [comment]
DA
#define TR_RANGE_TEST TR("Rækkevidde", "Test af rækkevidde")

**Comment by ulfhedlund** [comment]
> DA #define TR_RANGE_TEST TR("Rækkevidde", "Test af rækkevidde")

It is only used on color radios so the TR might not be needed.

**Comment by HThuren** [comment]
DA 
#define TR_RANGE_TEST "Test af rækkevidde"

**Comment by ParkerEde** [comment]
DE
#define TR_RANGE_TEST "Reichweitentest"

**Comment by ajjjjjjjj** [comment]
PL
`#define TR_RANGE_TEST "Test zasięgu"`

**Comment by robustini** [comment]
Since in the tx with lcd space we have some I think, at least in Italian, it is correct to specify that it is a "low power test link", since so many people ask me what "range" means.
So:

IT
#define TR_RANGE_TEST "Test del link radio a bassa potenza"

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_RANGE_TEST "受信強度テスト"

**Comment by zyren** [comment]
*************************************************************************
CN

#define TR_RANGE_TEST "距离测试(低功率)"
*************************************************************************
*************************************************************************
TW

#define TR_RANGE_TEST "距離測試(低功率)"
*************************************************************************

**Comment by ulfhedlund** [comment]
@pfeerick: I believe this is ready for merge, when you so decide.

**Comment by pfeerick** [comment]
LGTM, and thanks for the ping that it's ready to go.

**Pull request merged**
