### PR TITLE
feat: Add "Enable" button to all SF/GF (#3024)

### LINKED ISSUE #3024: Add missing Enable switch to SF/GF functions
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Lack of Enable control in below stated Specia/Global Functions:
- Play Sound
- Play Track
- Play Value
- Lua Script
- BgMusic
- BgMusic II
- Vario
- Haptic
- SD Logs
- Screenshot
- RacingMode
- No Touch
- Set Main Screen

### Expected Behavior

Implement Enable control

### Steps To Reproduce

-

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #3024
Squashed rebase of #3038 for inclusion in v2.9

### CODE REVIEW

**Comment by pfeerick** [comment]
@philmoz I've finally attempted to bring #3038 back up to a mergeable state. Would you mind looking over it, and seeing if there is anything that went horribly wrong during the rebase, or could be improved on. I've only had a quick run-through to make sure TX16S, TX12 and X9D+2019 all compile, and appear to be functioning in the simulator. 

The B&W 128x64 interface would be nicer if the checkboxes only showed on configured SFs, but as far as I can tell I ported that code over correctly so may be an issue in the original implementation.

**Comment by philmoz** [comment]
Line 218 of radio/src/gui/128x64/model_special_functions.cpp should be 'j = 5;'

The fields no longer fit on 128x64 for the 'Lua Script' function - script name overlaps repeat value. Not sure how to fix this.
Screen Shot 2023-05-16 at 8 11 00 pm

**Comment by pfeerick** [comment]
Thanks :)

Yeah, the 128x64 interface is just cramped for space. I guess there will probably be an issue with the play track function also.

**Comment by philmoz** [comment]
The 'enable' flag is not being read in from the YAML file for some functions.
- Override works
- Instant Trim and Lua Script fail (always start disabled).

Tested in the simulator by re-loading the radio data button.

**Comment by philmoz** [comment]
PR #3602 fixes a few problems.

**Comment by pfeerick** [comment]
Merged in, thanks. Nice thinking... removing the macro since it's no longer needed/used would have conveniently highlighted any other cleanup that could be done. And looks like I did mangle some of the rebase in `yaml_datastructs_funcs.cpp` ... 😇

**Comment by pfeerick** [comment]
@3djc Do you have any thoughts on this re: UI? Are there any other tricks we can use?

**Comment by 3djc** [comment]
This feature (the checkbox) was introduced to be able to disable 'more complex' SF without loosing the configuration. I'm really unsure of the value of saving say 'instant' trim.... and there is not much magic that can be done without resorting to 'one' page, but what a step back...

**Comment by pfeerick** [comment]
Need to think a little more outside the box when thinking of functions like instant trim, screenshot, etc - it makes more sense when a global function, as you can leave it in the list, with the switch allocated, and then only turn it on when needed. 

The only catch here is the 128x64 screen... it's not an issue for 212x64 or colorlcd, and adds some much-needed consistency to the UI. Looks like this moves to 2.10 until we can figure out to squeeze it in.

**Comment by philmoz** [comment]
The only thing I can think of for the 128x64 LCD is to reduce the length of the affected function names (in all translations) and then move the parameter to the left.

Examples:

Screenshot 2023-07-28 at 4 42 03 pm

Screenshot 2023-07-28 at 4 45 31 pm

**Comment by pfeerick** [comment]
Now that I've rebased #2145, this actually looks a lot neater to do (shorten affected names just for the 128x64... was a bit of a mess before how the SF strings were defined.

**Comment by philmoz** [comment]
I've rebased this to current main.

I changed the default for the 'active' flag to disabled as there is some risk when setting the other parameters of having the function enabled first.

Also discovered a problem - the YAML reader assumes the new format where all SF/GF have the active flag. It does not handle reading older model files where only one of the active/repeat settings was ever set. Depending on the function used this can cause the repeat value to be read incorrectly. Have not tested Companion yet; but I suspect it will have issues as well.

**Comment by philmoz** [comment]
I've added the changes to shorten the function names and adjust the parameter position for 128x64 LCD screens.

**Pull request merged**
