### PR TITLE
Optimize the date format of CN/TW 

### PR DESCRIPTION
**Pull request by zyren**
Add 0 in front of the single digit. For example, the display format of 8-1 is not so good, and it can be better to change it to 08-01.
Also change example:
8-23 to 08-23
10-5 to 10-05

image

### CODE REVIEW

**Comment by zyren** [comment]
Oh, some errors, I need to resubmit

**Comment by pfeerick** [comment]
There's no need for the if else conditionals... just use printf/sprintf zero padding ;)

```sprintf(str, "%02d-%02d", t.tm_mon + 1, t.tm_mday);```

The 02 between the % and the d tells printf/sprintf to automatically pad with zeros if the number is less than two digits.

**Comment by zyren** [comment]
> There's no need for the if else conditionals... just use printf/sprintf zero padding ;)
> 
> `sprintf(str, "%02d-%02d", t.tm_mon + 1, t.tm_mday);`
> 
> The 02 between the % and the d tells printf/sprintf to automatically pad with zeros if the number is less than two digits.

Nice, I'm too beginner in programming

**Comment by pfeerick** [comment]
We all have to start somewhere ;) I take it the "comment and close" button on the left side strikes again? I've done that a few times! 😆

**Comment by rotorman** [comment]
In light of #634, I am closing this here.

**Pull request closed without merging**
