### PR TITLE
cpn: iFlight Commando8 support

### PR DESCRIPTION
**Pull request by pfeerick**
Implements preliminary Companion/Simulator support for iFlight Commando8

Todos
- [x] TEST!
- [x] Add simulator component
- [x] Refactor on top of #2240
- [x] Compare against #1902
- [x] reword first commit

I ended up not giving a damn about aesthetics and didn't add the side-bars on the simulator... since the graphics don't match it properly anyway... it would have only been a view of the edge of the gimbals anyway and can be added later. 

image

### CODE REVIEW

**Comment by pfeerick** [comment]
@elecpower Given this radio doesn't have OpenTX support (and given the state of the OTX PR I suspect this is unlikely to change), what ... for want of a better word... legacy/EEPROM  ... support can I remove?

**Comment by gagarinlg** [comment]
If I remember correctly, think there was a decision to not introduce EEPROM support for new radios.

**Comment by pfeerick** [comment]
Yup... but I need to know how much can be removed for this radio as it is pretty embedded in Companion ;)

**Comment by elecpower** [comment]
> @elecpower Given this radio doesn't have OpenTX support (and given the state of the OTX PR I suspect this is unlikely to change), what ... for want of a better word... legacy/EEPROM ... support can I remove? Also, I still need to test this, but if there is anything else that jumps out can you let me know.

Agree with @gagarinlg no need for EEPROM stuff except the few placeholder board entries even if not correct.

IMO iFlight should provide the simulator graphics if they want it supported. 

From a quick scan it looks okay but I'm sure your rigorous testing will find any blips.

**Pull request merged**
