### PR TITLE
feat: S.Port telemetry for PPM/SBUS external module

### LINKED ISSUE #5064: TX16S, EdgeTX 2.10.0, no S.Port telemetry from external module?
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

No sensors discovered on the model settings telemetry tab when using S.Port telemetry in the external module bay after upating to 2.10.0

It was working in 2.9.2, and also works after rolling back to 2.9.4

For context, I'm using a Dragonlink module connected to the external module bay using SBUS protocol, which feeds S.Port telemetry back to the S.Port pin in the module bay at 57600 baud.

### Expected Behavior

Sensors should be discovered like in previous firmware.

### Steps To Reproduce

Feed telemetry into the external module bay's S.Port pin.
Go to model settings, telemetry tab, delete any previously discovered sensors if present, try to discover new sensors and none are found.

### Version

2.10.0

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #5064

Summary of changes:
- add S.PORT telemetry to PPM external modules
- add S.PORT telemetry to SBUS external modules

### CODE REVIEW

**Comment by mha1** [comment]
> Right, may I ask for some good soul to take care of companion please?

Don't know about the good soul: https://github.com/EdgeTX/edgetx/pull/5691

image

And there's one odd thing. CPN thinks SBUS is presented at VBat. That can't be true right? Let me know then I'll change it to plan "SBUS".

image

**Comment by raphaelcoeffic** [comment]
Frankly, I have no clue why the label says *"SBUS output at VBat"*. @3djc @elecpower any clue why?

**Comment by 3djc** [comment]
I guess that might be true for frsky radio? (Don't have any to check)

**Comment by mha1** [comment]
OpenTX implemented SBUS out on JR bay twith this PR: https://github.com/opentx/opentx/pull/5225. A screenshot found in this PR hints to how SBUS output at VBat needs to be understood. It's a warning SBUS levels are at battery voltage. Are there really radios doing this?

image

**Comment by mha1** [comment]
2.11 EdgeTX still warns all(!) b&w users that SBUS outputs current radio battery voltage levels. Color LCD users are warned levels are 5V. The wacky world of FrSky radios.

This is a screenshot from a T12max, SBUS@CPPM pin. The T12 outputs SBUS at 3.3V levels, yet the user is warned it's Vbat levels. The warning is if any only valid for some radios. The warning should be selective.

image

WhatsApp Image 2024-12-01 at 17 52 53_fb36a957

```C
        else if (isModuleSBUS(moduleIdx)) {
          lcdDrawTextIndented(y, STR_WARN_BATTVOLTAGE);
          putsVolts(lcdLastRightPos, y, getBatteryVoltage(), attr | PREC2 | LEFT);
```

**Comment by Target0815** [comment]
The warning is false. It was once introduced because SBUS was originally issued on VBat, which is no longer the case.

**Comment by raphaelcoeffic** [comment]
AFAIK, there are still a few old radios doing it (not sure which), but yes, it is probably too much to scare everyone for something that is not really the case anymore.

I don't think however this is related to the issue at hand.

**Comment by mha1** [comment]
> I don't think however this is related to the issue at hand.

Sure, I just noticed and it really looks odd. I mean you're right this is not directly related to the underlying issue but a nice opportunity to do some cleanup too. Let me know what Y'all think, I can do a separate PR if necessary.

**Comment by pfeerick** [comment]
Not related to the body of this PR, so separate PR thanks. Especially since it will require figuring out *which* radios use what voltage levels, as it is not always "false".

**Pull request merged**
