### PR TITLE
Fix missing colors

### PR DESCRIPTION
**Pull request by jfrickmann**
I have tracked down missing colors in the GUI and fixed them. I think that I got >90% of the cases, but please let me know if you find more.
@JimB40 @raphaelcoeffic

### CODE REVIEW

**Review by pfeerick — CHANGES_REQUESTED** [review]
The change to ` radio/src/thirdparty/libopenui/src/static.h` will have to be done over at https://github.com/EdgeTX/libopenui, otherwise I don't see any reason (prior to testing to see what this actually looks like) to not just merge this, and deal with any other missing constants in a followup PR...

**Comment by raphaelcoeffic** [comment]
This is a very good step toward the “Dark Mode” ;-)

**Comment by jfrickmann** [comment]
PR for libopenui: https://github.com/EdgeTX/libopenui/pull/15

**Comment by raphaelcoeffic** [comment]
> PR for libopenui: [EdgeTX/libopenui#15](https://github.com/EdgeTX/libopenui/pull/15)

Merged!

**Review by pfeerick — APPROVED** [review]

**Pull request merged**
