### PR TITLE
feat(color,cpn) - Updates to the model telemetry page.

### PR DESCRIPTION
**Pull request by philmoz**
This PR take the changes from PR #3150 and adds some additional fixes and cleanup.
I opted to create a new PR instead of trying to work in a fork of a fork :(

I also changed the title for the new option to 'Show instance ID' instead of 'Show sensor ID'.

Screen Shot 2023-03-25 at 4 57 32 pm

Changes:
- Add 'Show Instance ID' button to telemetry page to show/hide sensor instance number (default is hidden).
- The 'showInstanceIds' property is saved to the model file.
- Remove the 'Name', 'Value' and 'ID' labels row from the page.
- Fix issues with page refresh when all sensors deleted.
- Select closest sensor when a single sensor is deleted.
- On change, only refresh the sensor list instead of the whole page.
- Update Companion to save/load 'showInstanceIds' in model YAML file.
- Add 'Show Instance IDs" checkbox to telemetry edit page in Companion.

I changed the look for showing the instance ID a bit from PR 3150, to avoid having to change the line height for each row.
Screen Shot 2023-03-25 at 4 38 42 pm

All GPS strings should fit without having to adjust font size on portrait layout:
Screen Shot 2023-03-25 at 4 38 15 pm

### CODE REVIEW

**Comment by ParkerEde** [comment]
@philmoz 
nice job. I really like that already.
Unfortunately, there are still two small problems here.
1. when the sensor discovery is started and the list is filled with found sensors, the focus jumps to the first sensor line (ID0). This is irritating, because you can stop the sensor search only when you scroll to the stop button again. If there are already sensors in the list, the focus also jumps to ID0 and you don't see if the detection is done or not. Here I think the focus should be kept on the Start/Stop sensor search button. Then both cases would be cleanly operable and recognizable.
2) When I edit a sensor, e.g. change the unit or the precision (combo box), the focus always jumps back up to the "Type" line.

**Comment by philmoz** [comment]
I've made the changes suggested by @ParkerEde 
- The 'Stop' button has focus when searching for sensors.
- The ID values start at 1 instead of 0.
- The focus should not jump when editing a sensor.

**Comment by elecpower** [comment]
@philmoz can you also look a PR #2698 and the associated Issues to see they are covered off too and then we can close 2698 as superseded by this one.

**Comment by philmoz** [comment]
> @philmoz can you also look a PR #2698 and the associated Issues to see they are covered off too and then we can close 2698 as superseded by this one.

@elecpower It appears the issues in 2698 are still present.

The B&W radios and the telemetry simulator in Companion display the instance ID +1 while color radios uses instance ID.
Which is correct?

**Comment by ParkerEde** [comment]
Companion adds +1 to the instance ID. Here a further discussion about it.
https://github.com/EdgeTX/edgetx/issues/2678#issuecomment-1306660227

**Comment by ParkerEde** [comment]
> I've made the changes suggested by @ParkerEde
> 
> * The 'Stop' button has focus when searching for sensors.
> * The ID values start at 1 instead of 0.
> * The focus should not jump when editing a sensor.

Yes, perfect. I've tested it. Good job. Thx

**Comment by pfeerick** [comment]
@3djc What's the history with the instance IDs... what number should be shown?

**Comment by philmoz** [comment]
> Here about the history:
> [#2678 (comment)](https://github.com/EdgeTX/edgetx/issues/2678#issuecomment-1307738614)

I've read through all that; but I can't see any explanation as to why it was done.

**Comment by elecpower** [comment]
Also need to consider are there any data conversion considerations or do we force sensor rediscover and recreate all manually configured sensors after this PR is implemented. That is why I asked the question in the referenced PR and Issues.

**Comment by philmoz** [comment]
> With the latest commit, the instaceIDs in Companion are the same as in the radio/simulator. But now the telemetry simulator does not work anymore. Tested with Horus X10 Express profil

The telemetry simulator is working for me on TX16S and QX7.
Do the instance ID's match between the radio simulator and the telemetry simulator?

**Comment by ParkerEde** [comment]
> The telemetry simulator is working for me on TX16S and QX7.
> Do the instance ID's match between the radio simulator and the telemetry simulator?

Yes. With the version before everthing works fine with the telemetrie-simulator. Try to restart Radiosimulator with this button:
Screen01

**Comment by ParkerEde** [comment]
directly after starting the simulator, the instance IDs are not read correctly from the model preset and entered in the simulator. If I do this manually, it is okay, as @philmoz also wrote. But if you press the "Reload all Radio Data" button, all sensors are read from the model preset, but then still entered with the InstanceID+1.

**Comment by ParkerEde** [comment]
the reload button now works correctly again. Thx
Should we also take the opportunity to fix the fact that the InstanceID are not read in correctly immediately after the simulator start? 
Or rather in a separate ticket/PR like #3047?

**Comment by philmoz** [comment]
> Should we also take the opportunity to fix the fact that the InstanceID are not read in correctly immediately after the simulator start?

Probably not - it looks messy/complex to change.
The telemetry simulator is initialised when the main simulator window is opened.
At that point in time there is no model loaded in the radio simulator so there is no data to use to set up the telemetry simulator sensors.

**Comment by ParkerEde** [comment]
tested with QX7 Access Sim. 
After reloading, the correct IDs are now displayed in the telemetry simulator.

**Comment by Eldenroot** [comment]
Tested, TX16s MKII - should be fine, good improvement. Thank you

**Comment by pfeerick** [comment]
Thanks for the checks guys, yes, this also looks good for both EL18 and TX16S.

**Pull request merged**
