### PR TITLE
fix: logs not written to SD card and SpaceMouse not working

### PR DESCRIPTION
**Pull request by mha1**
fixes https://github.com/EdgeTX/edgetx/issues/3207

Summary of changes:
- removed obsolete check for mixer task running

### CODE REVIEW

**Comment by mha1** [comment]
@rotorman confirmed space mouse also not working. Applied same fix as for logs writing.

**Comment by rotorman** [comment]
Tested on TX16S with `-DSPACEMOUSE=YES`. SpaceMouse, as well as logging, both work again after this fix. Well done!

**Comment by raphaelcoeffic** [comment]
@mha1 you didn't try to figure out why `mixerTaskRunning()` is `false`? I think this is actually the issue.

**Comment by mha1** [comment]
@raphaelcoeffic  Hi, from a logging point of view I think it's not necessary to check for the mixer task. And logging can't interfere with the mixer task as uses software timers which run at a lower priority than the mixer task.

Anyway, was the logic reversed by your PR?

**Comment by mha1** [comment]
@raphaelcoeffic  Hi, from a logging point of view I think it's not necessary to check for the mixer task. And logging can't interfere with the mixer task as uses software timers which run at a lower priority than the mixer task.

Anyway, was the logic reversed by your PR?

**Comment by raphaelcoeffic** [comment]
I had it the wrong way… now it should be correct. The whole about stopping certain items while the mixer is not running is for 2 reasons:
- it is not necessary to run
- Some data might be changed by the UI which is why the mixer is stopped in the first place.

**Comment by mha1** [comment]
@raphaelcoeffic Ok, now I got it. I missed subtle change in your PR (logs.cpp and spacemouse.cpp). The move from checking pulse generation to mixer task status:
```
  - if (!s_pulses_paused) {
  + if (!mixerTaskRunning()) {
```
Which of course inverses to each other. So yes, assuming you only want to write logs when the pulses are generated, your change is absolutely correct:
```
  - if (!mixerTaskRunning()) {
  + if (mixerTaskRunning()) {
```
My reasoning for removing the check at all: Logs should have a uninterrupted time line if not stopped by the user but I'm happy with how 2.8 is working, so all good.

**Pull request merged**
