### PR TITLE
Issue 1936 - Trim audio at max/min trim (Alternate)

### PR DESCRIPTION
**Pull request by RJMcInty**
After all the back and forth in the other PR for this issue, I decided to do a more complete fix rather than a "minimal change" fix. Either would be fine, I believe, but I think this one is better. So, I'll create it as an actual PR vs. a draft and abandon the other if this one is accepted.

One concern I had was the scenario where you've got extended trims enabled, and you're normal trim values, and then you disable extended trims. What would the experience be, and would it wait for you to make a trim adjustment before updating the trim value to respect the new (lower) limit? Answer: no, it doesn't. As soon as you disable Extended Trims it respects the Normal Trims limits and adjusts if necessary, in the simulator. In the radio itself though it doesn't, until you move the out of bound trim once, and then it will correct to limit.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@pfeerick have you had time to look at this?

**Review by pfeerick — APPROVED** [review]
Finally, yes ;) On TX16S, this works great - tells you it's at max trim when at end, and tells you each time you press it again if that is still the case, rather than the same pitched beep. 

This fixes what could be perceived as a bug... whereby if you change from extended trim, to 'normal' trim range,  and the trim was in the extended range, it would wind back until it's in range (but not let you go back out of range). Now, it jumps back to the maximum for the trim on the first click. IMO this really needs to be caught when the option is changed, and be the focus of another PR. i.e. when you untick "extended trim" and you are in the extended range, a caution should come up, only allowing you to reset the trim or cancel, forcing you to move it back first if it needs to be done gradually.

**Comment by Eldenroot** [comment]
@RJMcInty - please check this issue with trims as well :) thank you! https://github.com/EdgeTX/edgetx/issues/2050

**Comment by RJMcInty** [comment]
> ... IMO this really needs to be caught when the option is changed, and be the focus of another PR. i.e. when you untick "extended trim" and you are in the extended range, a caution should come up, only allowing you to reset the trim or cancel, forcing you to move it back first if it needs to be done gradually.

I agree with you and spent a bit of time looking for the code executed when this option is changed but couldn't find it. I'll open another issue for that.

**Pull request merged**
