### PR TITLE
feat(color): allow changing the size of topbar widgets

### PR DESCRIPTION
**Pull request by philmoz**
Allows the user to specify how many slots each widget can occupy.
Each widget size can be set to a multiple of the default size - default is x1 to match current layout.

Default layout:
screenshot_tx16s_24-07-01_10-27-40

Adjust layout:
screenshot_tx16s_24-07-01_10-27-57

Adjusted main view:
screenshot_tx16s_24-07-01_13-53-04

The setup UI is basic so any suggestions for making it nicer appreciated.

TODO:
- [x] Translation strings.

### CODE REVIEW

**Comment by pfeerick** [comment]
> The setup UI is basic so any suggestions for making it nicer appreciated.

Basic is good... nice and simple ;) Not sure it could be done any better.. sure... could probably be *fancier*, but probably more complicated to use too.

**Comment by ulfhedlund** [comment]
SE translation:
#define TR_WIDGET_SIZE "Widgetstorlek"

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 Will be merged in seven days or when translations complete, whichever comes first. 

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [x] ulfhedlund SE
- [ ] @ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU 
- [ ] @elektro-NIK UA

```cpp
#define TR_WIDGET_SIZE "Widget size"
```

**Comment by robustini** [comment]
IT
#define TR_WIDGET_SIZE "Dimensione widget"

**Comment by Eldenroot** [comment]
CZ:

Velikost widgetu

**Comment by Pat6874** [comment]
FR:
#define TR_WIDGET_SIZE "Taille Widget"

Le 18 juil. 2024, 05:34, à 05:34, Peter Feerick ***@***.***> a écrit:

**Comment by ParkerEde** [comment]
DE:
#define TR_WIDGET_SIZE "Widget Größe"

**Comment by zyren** [comment]
CN

```c
#define TR_WIDGET_SIZE "小部件尺寸"
```
*********************************************

TW

```c
#define TR_WIDGET_SIZE "小部件尺寸"
```

**Comment by elektro-NIK** [comment]
UA
#define TR_WIDGET_SIZE "Розмір віджета"

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_WIDGET_SIZE "ウィジェットサイズ"

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_WIDGET_SIZE "Rozmiar widżetu"
```

**Comment by zandorsp** [comment]
PT
#define TR_WIDGET_SIZE "Tamanho do widget"

**Comment by pfeerick** [comment]
For those who have asked about long model names in the topbar - this PR + https://github.com/offer-shmuely/edgetx-x10-widgets/blob/master/WIDGETS/ModelName/main.lua works perfectly ;) 

image

**Comment by kobakirill** [comment]
RU
#define TR_WIDGET_SIZE "Размер виджета"

**Pull request merged**
