### PR TITLE
feat(pxx2): add support for SR10+ and R10+

### LINKED ISSUE #3188: FrSky ARCHER PLUS R10+ and SR10+ receiver support
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Frsky R10+ receivers have 10 configurable channel ports, each channel port can be assigned as PWM, SBUS, FBUS, or S.Port. 
At the moment you can only change the channel mapping for the 10 ports.

### Describe the solution you'd like

The possibility to configure all channel ports also to PWM, SBUS, FBUS, or S.Port.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #3188

### CODE REVIEW

**Comment by 3djc** [comment]
Is that only for COLORLCD ?

**Comment by r41065** [comment]
should work for all transmitter with ACCESS protokoll  ( for example x9lite..)

**Comment by raphaelcoeffic** [comment]
> Is that only for COLORLCD ?

Indeed! It would be nice to know if it works first, before the code is adapted to stdlcd as well.

**Comment by raphaelcoeffic** [comment]
**Current status:** still on my TODO list. It seems it's not working properly though.

**Comment by raphaelcoeffic** [comment]
Color LCD changes moved to #4077

**Pull request closed without merging**
