### PR TITLE
fix: NV14 uses active-high for keys and trims

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- add `active_low` boolean attribute for trims and keys
- init pins separately to allow for different pull-up/-down settings based on `active_low`
- read pins according to `active_low`
- activate *"trims as buttons"* in bootloader

### CODE REVIEW

**Comment by pfeerick** [comment]
Trims + pushing for exit/enter works in main firmware. Can enter the bootloader with trims held in, pushing works for enter/exit, but can't navigate using trims.

**Comment by raphaelcoeffic** [comment]
> Can enter the bootloader with trims held in, pushing works for enter/exit, but can't navigate using trims (NV14 and EL18).

*fixed*. Might be wise to leave these 2 commits separate as they fix 2 different issues.

**Comment by pfeerick** [comment]
Yup, works for bootloader also now... thank you! :)

**Comment by pfeerick** [comment]
update: We're still trying to work out what is going on here, as I can't reproduce this on my side. Phil was using a local build when this happened (and rolling back to d9b953095 fixed it), so it is also possible there is something wrong in the (intel) Mac build environment if hasn't doesn't a test against the github build for this PR.

**Comment by philmoz** [comment]
I completely cleaned out my local git repo and started fresh and everything now builds correctly - no idea what broke previously; but it seems ok now.

Apologies for the confusion.

**Comment by pfeerick** [comment]
Ouch! Well, at least you've exorcised the gremlins... that's a win! 😁 It's one reason I always fall back to the github builds for a lot of the issues I've hit, as they are clean builds that can be tested by both sides just incase it's a hardware/operator/config specific issue.

**Pull request merged**
