### PR TITLE
feat(color): Single select option for model labels plus label AND/OR filtering logic.

### LINKED ISSUE #4188: Automatically uncheck a label when checking a second label results in no models
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Several of my label groups are mutually exclusive.  E.g. I have an "EDF" group for fixed wing EDF jets, and I have a "Heli" group for helicopters.  The union of those two sets is empty, so if I check both boxes, I get no models.  In order to switch from EDF to Heli, I have to first uncheck EDF and then check Heli.

### Describe the solution you'd like

I'd love to be able to select a label and have the radio automatically uncheck the previous label(s) if the resulting model list would be empty.  If selecting multiple labels results in at least one model being displayed, the behavior should remain the same as it is currently.

### Describe alternatives you've considered

Today I just manually uncheck the first label before checking the new one.

### Additional context

Current behavior: selecting a second label results in no models shown because there are no models with both labels.

screenshot_tx16s_23-10-10_10-07-34

screenshot_tx16s_23-10-10_10-07-55

Desired behavior: selecting the second label should unselect the first label in cases where the combination yields no models.

screenshot_tx16s_23-10-10_10-07-34

screenshot_tx16s_23-10-10_10-08-09

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4188 

This is my take on a better way to handle labels. Feedback welcome.

TODO:

- [ ] Companion support (may need to wait for #4406).

Adds new options to control how the label selection and filtering work. A new 'Manage Models' setup view has been added to the Radio Setup page with the options (Model quick select has also been moved to this new page).

There are three new options:
- 'Label select' - 'Multi select' or 'Single select' (Multi select is the default). If Single select is chosen then only a single label can be selected.
- 'Label matching' - 'Match all' or 'Match any' (Match all is the default). Match all is the current logic - only models having all selected labels are shown. Match any will show models with any of the selected labels.
- 'Favorites matching' - Only available when 'Match any' is selected for Label matching. Options are 'Must match' and 'Optional match' (Must match is the default). Only applies when 'Favorites' is in one of the selected labels. If 'Must match' is selected then only shows models that have Favorites AND the other selections. If 'Optional match' is selected then models that match Favorites OR any of the other labels are shown.

screenshot_tx16s_24-01-11_15-23-01
screenshot_tx16s_24-01-11_15-23-15
screenshot_tx16s_24-01-11_15-23-31
screenshot_tx16s_24-01-11_15-23-37
screenshot_tx16s_24-01-11_15-23-45

I've also tried to show the logic iin the labels list:

Screenshot 2024-01-11 at 3 30 51 pm
Screenshot 2024-01-11 at 3 31 28 pm
Screenshot 2024-01-11 at 3 31 52 pm

### CODE REVIEW

**Comment by ParkerEde** [comment]
I have tested the PR. Very good idea. Single select" in particular is very good. I only noticed that if a label is selected, the check mark is also displayed. If I now select a model, it is loaded. If I now go back to the model manager, the last label is also displayed correctly, but the check mark is no longer visible.

**Comment by philmoz** [comment]
> I have tested the PR. Very good idea. "Single select" in particular is very good. I only noticed that if a label is selected, the check mark is also displayed. If I now select a model, it is loaded. If I now go back to the model manager, the last label is also displayed correctly, but the check mark is no longer visible.

Thanks for testing - the single select check mark should work now.

**Comment by ParkerEde** [comment]
yes, nice. Thx

**Comment by ParkerEde** [comment]
Now I found out during testing that the PageUp/down no longer work. Please also note that the Horus x10 with page longpress for down must work. It was the same before this PR. The checkmark must also be displayed.

**Comment by philmoz** [comment]
> Now I found out during testing that the PageUp/down no longer work. Please also note that the Horus x10 with page longpress for down must work. It was the same before this PR. The checkmark must also be displayed.

The PGUP/PGDN keys should now work in single select mode.

**Comment by ParkerEde** [comment]
PgUp/Down is not quite perfect yet. The wrap around should jump directly to the first label and not to none. This drastically increases the loading time if you want to jump from the last to the first label. Before this PR, it was also the case that the wrap around jumped directly from the last to the first label. This affects both modes (single/multi select)

**Comment by ulfhedlund** [comment]
Great effort!
SE translations:
  #define TR_LABELS_SELECT                "Etikettval"
  #define TR_LABELS_MATCH                "Etikettmatchning"
  #define TR_FAV_MATCH                      "Matcha favoriter"
  #define TR_LABELS_SELECT_MODE  "Flerval","Enskilt val"
  #define TR_LABELS_MATCH_MODE  "Matcha alla","Matcha någon"
  #define TR_FAV_MATCH_MODE         "Måste matcha","Alternativt matcha"

**Comment by pfeerick** [comment]
> By the way, in 2.9.2 6 labels could be displayed at the same time, now only 5, why did they change that?

Looks like the line height for each entry has increased slightly. 

image

image

**Comment by philmoz** [comment]
> PgUp/Down is not quite perfect yet. The wrap around should jump directly to the first label and not to none. This drastically increases the loading time if you want to jump from the last to the first label. Before this PR, it was also the case that the wrap around jumped directly from the last to the first label. This affects both modes (single/multi select)

I assumed that this was an oversight in the previous code - if it jumps directly to the first/last entry on wrap around then there is no way to clear the selection and show all models (on radios without a touch screen).

**Comment by ParkerEde** [comment]
I think that since there have been no complaints from Horus users about this, the behavior should not be changed. There is also no need to jump to no label in the wrap arround, because why should I be interested in a complete list if I have taken the trouble to organize my model within labels. Please, please do it the way it was in the previous versions. And if you want to have an unsorted complete list, you can go to the list of labels with the focus, press Enter and then select one or more labels or even no label, as it has always been in 2.9.2.

**Comment by ParkerEde** [comment]
DE translations:
#define TR_LABELS_SELECT " Labelauswahl"
#define TR_LABELS_MATCH "Labelvergleich"
#define TR_FAV_MATCH "Favoriten vergleichen"
#define TR_LABELS_SELECT_MODE "Mehrfachauswahl", "Einfachauswahl"
#define TR_LABELS_MATCH_MODE "Alle", "Beliebig"
#define TR_FAV_MATCH_MODE "Muss übereinstimmen", "Alternative Übereinstimmung"

**Comment by philmoz** [comment]
I have reverted the PGUP/DN wrap around logic.

**Comment by ParkerEde** [comment]
Thx. Now it's fine to me.

**Comment by ParkerEde** [comment]
Shouldn't we also make the labeling of this button translatable?
image

**Comment by philmoz** [comment]
> Shouldn't we also make the labeling of this button translatable? ![image](https://private-user-

TR_MANAGE_MODELS

**Comment by ParkerEde** [comment]
DE:
TR_MANAGE_MODELS   "Modellmanager"

**Comment by philmoz** [comment]
> DE: #define TR_MANAGE_MODELS "Modellmanager"

This is also used for the title on the manage models page where all caps is the current standard.
Screenshot 2024-01-20 at 7 30 18 am

**Comment by ParkerEde** [comment]
But on the buttons, all capital letters don't look very good. All other burtons have normal lettering.

**Comment by philmoz** [comment]
> But on the buttons, all capital letters don't look very good. All other burtons have normal lettering.

I agree. I also think that the all caps on the menus looks bad and should be changed; but that's a topic for a separate PR.

**Comment by philmoz** [comment]
I have updated this to use the quick menu string (mixed case) for the button title instead of the all caps menu title string.

**Comment by pfeerick** [comment]
@philmoz Do you have any problems with #4524 and this PR getting merged, and a followup PR to catch Companion up?

**Comment by philmoz** [comment]
> Do you have any problems with #4524 and this PR getting merged, and a followup PR to catch Companion up?

Ok with me; but this one needs translations.

**Comment by pfeerick** [comment]
I think that will probably be it's own PR again, as there are several translations needed for each language now, across multiple PRs, so (overdue) time to pull them all together...

**Comment by pfeerick** [comment]
Looks great on TX16. I love how you added the AND/OR to the label list to help inform why it's matching the way it does... should help with people still confused how labels behave by default.

**Pull request merged**
