### PR TITLE
I2C drivers HAL/LL port

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- moved all I2C drivers to HAL/LL
- merged IMU drivers for LSM6DSxx
- added support for IMU to all Horus based targets

TODO:
- [ ] use FreeRTOS software timers to poll I2C IMU (depends on #1742)
- [ ] auto-discovery of I2C devices

### CODE REVIEW

**Comment by rotorman** [comment]
Present state in a video with [Adafruit LSM6DS33](https://www.adafruit.com/product/4480 ) hooked up via AUX1 to TX16S: https://www.youtube.com/watch?v=xMOIpQKpdaE

If you are wondering about AUX1 on TX16S being by default serial and not I2C, then yes, but luckily the RX and TX pins are mapped to I2C2 bus SCL and SDA of STM32F429BIT6 microcontroller inside the radio, thus it is only a software setting to change this to I2C in order to communicate with I2C devices

**Comment by Stinky80** [comment]
I'm sorry I don't know which thread to write to
i have an empty (without elements) jumper  t16 board on my hands, I see that the processor contacts 31 touch rst and 46 touch init are not connected and do not go anywhere. to the T16 jumper and since the i2C bus is multicast, then the gyroscope :)

**Comment by rotorman** [comment]
I answered you in: https://github.com/EdgeTX/edgetx/pull/1779#issuecomment-1096748374

**Comment by wimalopaan** [comment]
Reading through the code I think:

1) type punning through unions is UB in C++ (`GyroBuffer`) (use `std::bit_cast<>()` in c++20 or `std::memcpy()` - better - simple copy/shift).
2) class `GyroBuffer` should be private to class `Gyro`
3) In the signature `int read(int32_t values[IMU_VALUES_COUNT])` the array dimension is not part of the signature, therefore
4) use `std::array` instead of c-style arrays.
5) Using CPP-symbols clutters namespace, use namespace-scope or class-scope `static constexpr`
6) It looks like the class `Gyro` is meant to be instantiated excatly once. But this is not enforced. Just use an all-static class in this case.
7) observer-functions should be `const`

Just my 2 cents.

**Comment by raphaelcoeffic** [comment]
@wimalopaan there is indeed some clean-up ahead of the old OTX code.

**Pull request merged**
