### PR TITLE
Improve rotary encoder acceleration

### LINKED ISSUE #2417: No acceleration (or acceleration very weak) when changing failsafe values with roller.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Running 2.8.0 RC-1 on TX16S.

In the failsafe menu it's possible to alter a channel's failsafe value using the roller, however the click increment is only 0.1, and the acceleration is very weak. This makes it very slow go from one end of the range to the other.

### Expected Behavior

It should be possible to span the range -100 to +100 in a few seconds.

### Steps To Reproduce

1. In MPM options, choose FrSky D16 protocol
2. Open the Failsafe menu
3. Use the roller to change a failsafe value

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

TX16S / 2.8.0 RC-1

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #2417

Requires EdgeTX/libopenui#78

Summary of changes:
- use a more accurate / smoother implementation
- added specific acceleration factor which can be tuned for each number edit (depends on range / usage)

### CODE REVIEW

**Comment by robustini** [comment]
Hi Raphael, tremendously slow when changing RGB color values.

**Comment by raphaelcoeffic** [comment]
> Hi Raphael, tremendously slow when changing RGB color values.

What about the rest? I believe this is already a huge change. However, I think I have just pushed a better version that should work better when the UI is working slowly.

**Comment by robustini** [comment]
The rest seems ok to me!
But now don't compile it out, top!

immagine

**Comment by pfeerick** [comment]
Something got broken for colorlcd, sure it'll be fixed again shortly ;)

**Comment by robustini** [comment]
@raphaelcoeffic well, very fast in the color selection but really too fast when for example you choose an audio track, the acceleration is really too excessive.
I have a lot of tracks and if I go a few speeds it jumps from A to Z in no time.

**Comment by raphaelcoeffic** [comment]
@robustini it is already using variable speed for different components. Menus however all use the same speed. Maybe we could remove the acceleration for menus except source / switch section?

**Comment by pfeerick** [comment]
Maybe we need to remove it entirely for menus (but in that case, probably also need to restore the ability to wrap around the menus from the top)... as I would have said you want acc on a longer list, but that is what is being commented on here. Perhaps cap the max acc in the menus and _maybe_ on the keyboard?

**Comment by robustini** [comment]
> it is already using variable speed for different components. Menus however all use the same speed (smallest possible with accel) Maybe we could remove the acceleration for menus except source / switch section? Or dependent on the number of elements currently listed? (Which limit?)

I don't see any problems except in the section where I choose an audio track.
What is the section of the code for that explicit acceleration?

**Comment by raphaelcoeffic** [comment]
If you remove this line from the menu, acceleration will be gone from the menus: https://github.com/EdgeTX/libopenui/blob/62cda2983610760b1c8a93f6611ad324e159360f/src/menu.cpp#L82

**Comment by robustini** [comment]
Much better, thanks!
Maybe it's right on the menus, but not that fast.

**Pull request merged**
