### PR TITLE
feat: basic H7 support

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by 3djc** [comment]
Tested ok on main features (as in "doesn't break") on T15 and Boxer

**Comment by richardclli** [comment]
PL18EV external MPM breaks.

**Comment by richardclli** [comment]
PL18EV external MPM works after USART6 AF fix

**Comment by raphaelcoeffic** [comment]
> EL18: external MPM works after USART6 AF fix, but ELRS still EM

I will revisit the method for determining the alternate function.

**Comment by 3djc** [comment]
Tested T15 AUX2 trainer (so UART6) ok with your latest changes

**Review by pfeerick — APPROVED** [review]
LGTM... passed basic functionality tests (i.e. power on, display, sound, controls, RF link, telemetry, Lua, USB) on EL18, TLite, X9D+, TX12, TX16S with no outstanding issues.

**Comment by pfeerick** [comment]
Im sorry, but how is treated to this now merged PR? Even so, it would
probably be better to create a new issue, and reference this PR if there is
a connection, since it has been merged, thus no more changes happening
here.

**Pull request merged**
