### PR TITLE
fix(cpn): More general headline for RSSI warnings

### PR DESCRIPTION
**Pull request by mha1**
Now that firmware distinguishes between different sources (not only RSSI) for measuring RF quality based on the selected RF protocol I figured it was necessary to get rid of the RSSI headline in favor of a more general headline. 

Summary of changes:
- changed headline for RF quality warnings on telemetry tab from `RSSI` to `RF Quality`
- enabled translations for `RF Quality`
- added DE translation for `RF Quality`

before:

image

after:

image

after with translation (DE):

image

### CODE REVIEW

**Comment by mha1** [comment]
@pfeerick While browsing through firmware language definitions some obsolete strings were found:
- (S)TR_RSSIALARM_WARN
- (S)TR_NO_RSSIALARM

If you want me to delete them please let me know shortly before merging this PR. I'd like to stay out of the rebasing game due to translation changes as long as possible.

**Comment by pfeerick** [comment]
Hm... #346 is responsible for that (so basically since day 1 for EdgeTX users), and I don't remember any complaints... so those strings can indeed go. I intend to merge #4282 in the last batch for tonight, so once that is in you should be safe to rebase and cull to your heart's content. And this should then make it into `main` tomorrow sometime.

**Comment by mha1** [comment]
aight, will wait for 4282

**Comment by pfeerick** [comment]
@elecpower Why are you retriggering the mac builds? The PR needs to be rebased before it will work ;)

**Comment by mha1** [comment]
rebase done

**Comment by pfeerick** [comment]
Thanks. 

Can you also update
```
TR_TRAINER
``` 
for de to say "Trainer" instead of "DSC Buchse PPM In/Out" unless you have a better alternative (if so, just go with it :grin:).

**Comment by mha1** [comment]
> for de to say "Trainer" instead of "DSC Buchse PPM In/Out" unless you have a better alternative (if so, just go with it 😁).

Trainer is fine. It's also used for labeling the Trainer menu. And the German word Trainer translates to coach which is on point.

**Comment by elecpower** [comment]
> @elecpower Why are you retriggering the mac builds? The PR needs to be rebased before it will work ;)

@pfeerick Just thought I would help and clear the SDL fails so 3 ticks. No more no less.

**Comment by pfeerick** [comment]
> @pfeerick Just thought I would help and clear the SDL fails so 3 ticks. No more no less.

Thanks. Yeah, because the actions run within the state of a PR and when it branched, until that changes, it wasn't going to succeed. If it wasn't for the case that Michael was going do more work on this PR anyway I probably would have just merged it anyway, since it's a known failure cause.

**Comment by mha1** [comment]
image

**Pull request merged**
