### PR TITLE
chore: Use the CMake way for linker options

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
And fix an issue with the SDRAM start address not being used properly in the bootloader linker command.

### CODE REVIEW

**Comment by TheIsotopes** [comment]
Unfortunately, this does not solve issue #4385.
I thought something was coming now.

**Comment by raphaelcoeffic** [comment]
> Unfortunately, this does not solve issue #4385.
> I thought something was coming now.

Makes sense, it is aimed at fixing some totally different issue: PL18 / EL18 bootloader not starting (due to wrong SDRAM address).

**Comment by richardclli** [comment]
PL18 works, I believed that El18 should works as well.

**Comment by richardclli** [comment]
@raphaelcoeffic Seems the PR misses the parameter to override the SDRAM size definition.

**Comment by pfeerick** [comment]
- [x] EL18 bootloader and firmware starts up fine after DFU flashing this (whereas nightly bootloader crashes the radio). 
- [x] X9D+
- [x] TX16S
- [x] T20 
- [x] LR3
- [x] MT12

Commando8 does not boot the main firmware properly with this PR or nightly, so something broke for it somewhere between now and Oct-27 (that's the build I flashed on it ... for #3870).

**Comment by richardclli** [comment]
@raphaelcoeffic I added the SDRAM size definition support based on your scripts.

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic I added the SDRAM size definition support based on your scripts.

Thx! Looks good to me!

**Pull request merged**
