### PR TITLE
fix(color): Make toggle switch UI consistent with other UI elements

### LINKED ISSUE #4109: Fix styling of UI Switch.
UI Switch being OFF has now applied DISABLED color that is incosistent with other UI elements.

### Describe the solution you'd like

1. Apply PRIMARY2 color as background
2. Apply SECONDARY1 color as switch knob fill
3. Decrease 1-2px diamater of the knob so it has beeter spacing to background element

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4109 

Change background color, knob color and knob size.

### CODE REVIEW

**Comment by philmoz** [comment]
Screenshot 2023-09-26 at 8 42 18 am
Screenshot 2023-09-26 at 8 42 26 am

**Comment by pfeerick** [comment]
image


@JimB40 You actually need to say something... I'm not clairvoyant 🤪 ... does this do everything you were after?

**Comment by JimB40** [comment]
That heart was for @philmoz 😃 
I will flash it & test in a while.

Btw I realy wuld i like to be able to test such a shorts on simu.
Buu building on my macs M1 & M2 does't work.
Any progress @raphaelcoeffic with properly working script to make PR build on newer macs?

**Comment by raphaelcoeffic** [comment]
> Any progress with properly working script to make PR build on newer macs?

Well, I do everything on my M1 Pro, so I guess it should work. We could have a live session at your convenience :-)

**Comment by JimB40** [comment]
Tested with various themes.
Looks absolutely prefect for me.

**Pull request merged**
