### PR TITLE
feat(lua): add getter/setter for Global Variable details

### LINKED ISSUE #5666: lua `model.getGlobalVariable()`/`model.setGlobalVariable()` is an int, whereas all other `model.get*`/`model.set` get/set whole tables with all info
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes, I'm working on input/export functionality in lua to allow, within edgetx to transfer specific configurations between models, and this is quite a problem, making it impossible

### Describe the solution you'd like

I recognize that `model.getGlobalVariable()` / `model.setGlobalVariable()`  likely cannot have API changes introduced, but maybe we can add `model.getGlobalVariableTable()` or similar

### Describe alternatives you've considered

I thought about reading the YAML's but this is not really very possible in lua on the radio.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by forbesmyester**
Fixes #5666 

Add Lua API for getting details about Global Variables (not the value).

NOTE: I can and do code, but I _really_ don't know C++, however I have put significant effort into getting this right. Thanks.

### CODE REVIEW

**Comment by philmoz** [comment]
Looks ok. Might want to remove the extra blank lines added before the #endif though.

**Comment by forbesmyester** [comment]
Removed Lines.

**Comment by forbesmyester** [comment]
I'm somewhat doubting this now. min/max are loaded & saved without issue, which suits my purpose (a load/save lua script)

However the numbers are the values stored presumably in memory, not the numbers the user sees on the screen, somewhat like what was happening in #4379 

I'm looking back and following function calls through the handling of gvars on and end up with the following calls:

 * https://github.com/EdgeTX/edgetx/blob/0ea41f21464741ef68a3443dcb591b82cc6d3051/radio/src/gui/212x64/model_gvars.cpp#L103C9-L103C22
 * https://github.com/EdgeTX/edgetx/blob/0ea41f21464741ef68a3443dcb591b82cc6d3051/radio/src/gui/212x64/widgets.cpp#L149
 * https://github.com/EdgeTX/edgetx/blob/0ea41f21464741ef68a3443dcb591b82cc6d3051/radio/src/gui/212x64/widgets.cpp#L149
 * https://github.com/EdgeTX/edgetx/blob/0ea41f21464741ef68a3443dcb591b82cc6d3051/radio/src/gui/212x64/widgets.cpp#L149

But that last function is somewhat of a monster and while I see it is largely that `do..while` loop that does the work, I'm not confident in editing those functions and feel I cannot copy it either as it's somewhat complex.

I feel either the implementation is fine, but the table values should be prefixed with "raw" or ask assistance on how to get the API values out as what the user sees on screen (which would be preferable).

Sorry I hoped to do this by myself :-(

**Comment by philmoz** [comment]
'unit' and 'prec' are not boolean values, they are integers (even though they are currently limited to be either 0 or 1).
I don't understand why you need to rename the 'min' and 'max' properties.

**Comment by forbesmyester** [comment]
So, I am happy with the first 1st, 2nd or 3rd commits.

In the third commit I'm primarily looking at the user interface and noticing 2 things, as you say, `unit` and `prec` are integers, but displayed usage is as a boolean, so I thought that was better to have them as booleans. Happy to put them back to integers.

I also noticed that, `getGlobalVariableDetails()` the `max` value is represented as 124 when it would display 900 on screen (low precision). of course, using `setGlobalVariableDetails()` with a max of 124 will set it back to 900 (on screen). It's an integer in memory, but one that does not map directly to the screen / user perception... This is why I elected to rename it to `raw_max`, as it's not doing exactly what might be expected from a lua developer.

I'm working on an import/export script in lua and I don't really care, but am happy to go with either commit, or work with you or another team member to improve the API to be more obvious.

Let me know what you want to do.

Thanks

**Comment by forbesmyester** [comment]
Updated, with all your recommendations, thanks for your help.

**Comment by forbesmyester** [comment]
Changed with your recommendations, thanks :-)

**Comment by forbesmyester** [comment]
@philmoz is it right/correct for this to be requested to merge into main and how do we get that to happen? Thanks and Thanks for your help so far 🙂

**Comment by philmoz** [comment]
> @philmoz is it right/correct for this to be requested to merge into main and how do we get that to happen? Thanks and Thanks for your help so far 🙂

@pfeerick will look after merging this when he has reviewed it (and has time).

**Comment by forbesmyester** [comment]
@pfeerick done. let me know if they're not correct. Thanks

**Comment by forbesmyester** [comment]
@pfeerick Thanks.

My dirty test is an Import / Export script to transfer settings easily on-radio.

Is available here - https://github.com/forbesmyester/EdgeTX-ImpExp

**Comment by pfeerick** [comment]
Might be worth adding a mention of in https://github.com/EdgeTX/lua-scripts
at some point?

**Pull request merged**
