### PR TITLE
Danish special characters

### PR DESCRIPTION
**Pull request by HThuren**
Define Danish characters at BW display, same as #2259 and #2083

### CODE REVIEW

**Comment by pfeerick** [comment]
Have you tried this yet? It looks like the characters may be in the wrong order?

image
image

**Comment by gagarinlg** [comment]
Those are no danish glyphs. Öö and Ää do no exits in the danish alphabet. So there must be something else missing.

**Comment by gagarinlg** [comment]
I zhink I found another steop to be dne for this to work, in
radio/src/fonts/std
are PNGs for the fonts plus extra PNGs for the language specific special chars. There is no file with the danish characters.

**Comment by pfeerick** [comment]
This makes more sense then... I just nuked the entire build folder since a clean build doesn't clean *everything*, and now I'm getting
image
image

I think for that radio I'd done a SE translation build, so was probably been filling in the missing letters from that build since they weren't otherwise present.

**Comment by HThuren** [comment]
Hi there, I'll check and works on it when back from my job. 
Big help from your test and observations, I test on Tantaris x9d+
For sure, I didn't made changes to fonts, here to concentrate.

**Comment by HThuren** [comment]
Hmm, I have found the issue, working on it. But how to make .png files ?

**Comment by gagarinlg** [comment]
Paint?
Maybe you can use the swedish or german file and modidy the glyphs. I have no idea where they originally came from.
@raphaelcoeffic ?

**Comment by raphaelcoeffic** [comment]
> I have no idea where they originally came from.

 Neither do I. I‘m passing the hot potato to @3djc 😅

**Comment by HThuren** [comment]
Looking at OpenTx#7542 and OpenTx#4540, but no clear
MS Paint maybe (gosh :-) )

**Comment by HThuren** [comment]
Something happen in the makefiles, maybe pure generated files :-)

**Comment by HThuren** [comment]
@gagarinlg 
I have found the issues, need to paint the danish letters, take some time.

**Comment by HThuren** [comment]
@gagarinlg also try with font2png.py :-)

**Comment by pfeerick** [comment]
That would be https://github.com/opentx/opentx/blob/2.3/radio/util/font2png.py, since for some reason we don't have that anymore 😕

**Comment by HThuren** [comment]
font2png.py are now in this PR :-)

**Comment by HThuren** [comment]
but not found the right solution, swedish chars still in use

**Comment by HThuren** [comment]
On its way now :-)

**Comment by pfeerick** [comment]
Using the Tools and Trainer screens as a reference again, this is looking more like the colorlcd now... 

Did the Æ / æ character come through right? As it seems your images in that last commit have it formatted differently?

image
image

**Comment by HThuren** [comment]
No the æ Æ letter was not that easy to draw. The first try was ockly.
Also need to discover the Tilstan%dKilde, seems ok in the file, but ..

**Comment by HThuren** [comment]
Thank you for your support and patience @raphaelcoeffic, @gagarinlg and @pfeerick 
Danish characters are now drawn with Paint, and the files must exist in radio\src\fonts\sqt5 and radio\src\fonts\std and refered in fonts.cpp and utf8.cpp

**Comment by gagarinlg** [comment]
Thank you for your work!
Maybe I switch the Literadio 3 Pro to danish, learning a bit more of your language than just Øl and "Til stranden"

**Comment by HThuren** [comment]
Lære om dansk hygge :-)

**Comment by pfeerick** [comment]
I'm happy with if you are! :) And oh dear, having to break out mspaint... at least this PR has been an interesting learning journey for B&W translations... will have to do some documentation for that now, based on what we've learnt ;)

image
image

**Review by pfeerick — APPROVED** [review]

**Comment by gagarinlg** [comment]
So, now back to the main discussion ;)
How many non danish people understand the meaning of "hygge"? It is close but not quiet the same as german "gemütlich".

**Comment by HThuren** [comment]
I will say, every danish. Sitting in a large sofa, great bowl of sweets, nice people around, interseting talk, maybe some tv, that can decribe hygge :-)

**Pull request merged**
