### PR TITLE
Potential out of bounds access of flightmode name on main screen (#1333)

### PR DESCRIPTION
**Pull request by wimalopaan**
This fixes one incorrect use of potential unterminated cstrings for the ctor of std::string.

### CODE REVIEW

**Comment by wimalopaan** [comment]
@raphaelcoeffic  Anything I can improve?

**Comment by pfeerick** [comment]
You can remove the commented out code, as that is visible in the commit history if it needs to be referred to in the future. Otherwise if Raphael is happy with this I can try add it to the queue for testing.

**Comment by wimalopaan** [comment]
> You can remove the commented out code, as that is visible in the git history if it needs to be referred to in the future. Otherwise if Raphael is happy with this I can try add it to the queue for testing.

Done so far.

**Comment by wimalopaan** [comment]
Use this for a while now and it should be stable.

**Review by pfeerick — APPROVED** [review]
I can't actually reproduce the problem this fixes - possibly it isn't so visible with yaml? - but this still cleanups up the improper use of string, and makes a reusable function available for others. Thanks!

**Comment by pfeerick** [comment]
@wimalopaan This is actually breaking when Mac Companion is building the firmware
https://github.com/EdgeTX/edgetx/runs/4755792840?check_suite_focus=true

It seems you can only use `constexpr std::string` in C++20 ... so I'll probably revert this for now until we can come up with something different once the other other builds complete. 

https://stackoverflow.com/questions/27123306/is-it-possible-to-use-stdstring-in-a-constexpr

**Comment by wimalopaan** [comment]
Is there an option to force the build script to use clang target ARM?
I'm typically using GCC which is sometimes accepting more of the "new" features, here of the "constexpr-all-things" initiative.
I would like to use clang locally too to test my PRs.

**Comment by raphaelcoeffic** [comment]
> Is there an option to force the build script to use clang target ARM?

I'm using `clang` for native compilation, not for ARM. I think you can give CMake the default compiler / toolchain as a parameter: https://stackoverflow.com/questions/7031126/switching-between-gcc-and-clang-llvm-using-cmake

**Comment by wimalopaan** [comment]
Thank you!
Yes, setting `-DCMAKE_C_COMPILER=clang` and `-DCMAKE_CXX_COMPILER=clang++` works.

Trying the same for `-DCMAKE_CXX_STANDARD=20` does not work, say this in no set for compiling the sources ... I have to set this hard in the `CMakeList.txt`.

**Comment by wimalopaan** [comment]
FIxed the constexpr std::string issue for c++11

**Pull request merged**
