### PR TITLE
Fix companion model edit image names

### LINKED ISSUE #843: Companion not showing all images available for use as model image
@elecpower I have a doozy for you... and this is either a user error, or this bug is also present in OTX as well... 

In a nutshell, I was just creating a new model (new OTX file, TX16S profile), and have the SD card folder selected in Companion settings, and instead of letting me see all 12 `.png` images, it only lets me see three of them. 😮 Gimme my other 9! 😆 

image

This happened with the same dataset on both OTX and ETX companion, and with the ETX companion on windows and linux via the test appimage build. 

Attached is the contents of my images folder at the time of the screenshot (just in case it is related to the files/and better mimic). I noticed that if I added a bunch of `*.jpg` files - probably stock ones from OTX, more files were listed, but even then, it wasn't a complete list. 
[IMAGES.zip](https://github.com/EdgeTX/edgetx/files/7267376/IMAGES.zip)

Just a further note to that - I tried opening an old OTX file on OTX companion, and whilst I can't swear it to be the case, I don't think it was showing configured model images for some models. 

Possibly related (or if not, was the reason I encountered this) is this case where the filename was corrupted, and this users file list was also suitably bare... ([discord comment](https://discord.com/channels/839849772864503828/839849772864503832/893466610898202624))

image

image

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #843
Edited models in Companion and Simulator checking file names up to 10 chars excl .bmp extn for eeprom and 14 chars inc extn for sd card radios. Tested:
- TX16S
- X9D+

Image list sorted case insensitive to match radio.
Use firmware capabilities rather than specifying boards.

### CODE REVIEW

**Comment by elecpower** [comment]
Hold off testing and merge until I add data conversion of the extensions between radios

**Comment by pfeerick** [comment]
Eeek! Thanks for the heads up... I'd just downloaded the build to try it out! 😆

**Comment by pfeerick** [comment]
I won't go any further with the companion testing till you're ready, but in my particular instance - new model, pick a image - it  seems to be working and the dropdown is showing all the images I included in that zip file now. :)

**Comment by elecpower** [comment]
Okay so time to try and break it

**Review by pfeerick — APPROVED** [review]
This looks good to me... Tried on TX16S, NV14 and X9D+2019. Just waiting to see if the other user who encountered this responds and is able to try it out.

**Pull request merged**
