### PR TITLE
fix(b&w): Various rotenc. inversion bugs on radio and simu

### PR DESCRIPTION
**Pull request by pfeerick**
Fixes
- Swapped PAGE >, PAGE < on Boxer
- Simu rotary encoder inversion not matching radios
- Scrolling in popup menus not going in same direction as vertical navigation

### CODE REVIEW

**Comment by pfeerick** [comment]
@3djc @philmoz Would you mind sanity-checking this for me (i.e. when changing between the different rotary encoder options, popup scrolling should now move in the same direction as the vertical menu navigation, and simulator should match the radio. 

I was going around in circles for a good half hour trying to figure out how to fix this, then realised it was because the simulator had a bug also, which is why it worked on the simulator, but not on the radio, and then on the radio, but then not on simulator... so am going to leave it for a little while now 😆

**Comment by philmoz** [comment]
I'm not sure I understand the problem - on QX7S (both radio and simulator) there is no issue or mismatch with direction of the rotary encoder scrolling. Using current main branch.

**Comment by 3djc** [comment]
Looking at the changed files, looks like he had an issue with boxer simu

**Comment by philmoz** [comment]
Won't the changes to popups.cpp affect all B&W radios?

**Comment by 3djc** [comment]
Absolutely, but it is needed, I missed it in my previous PR

**Comment by pfeerick** [comment]
> there is no issue or mismatch with direction of the rotary encoder scrolling

Did you try all five options? And verify that both vertical navigation and popup scrolling are the same on radio and simualtor?

I happened to have the boxer on the desk, so picked up the pgup/pgdn issue because of that, but everything else is generic thus and applies to all b&w targets.

**Comment by swissfreek** [comment]
For what it's worth, on my MT12, this PR does in fact make the menu and sub-menu scroll directions match in all the different scroll direction options.

**Pull request merged**
