### PR TITLE
Clean up some errors introduced in PR #1363

### PR DESCRIPTION
**Pull request by stephenaa**
- Cleaning up bad YAML definitions
- Reverted renaming of 'jitterfilter' radio setting in storage/conversions/yaml/ files

Fixes #

Summary of changes:

### CODE REVIEW

**Comment by elecpower** [comment]
Companion also needs changing doesn't it?

**Comment by pfeerick** [comment]
Only if there was something conversion related touched there? This is basically only making it so the auto-generated yaml is correct as it was manually altered after generation... naughty naughty! :grin: (never done that myself 😇 ... I have a bridge to sell if you're interested... ). Companion is expecting to see GLOBAL, ON, OFF so that should be right.

**Comment by elecpower** [comment]
BTW how much for that bridge and could I get some nice views if I climbed to the top 😉

**Comment by stephenaa** [comment]
> 

yaml_modeldata.cpp uses YamlLookupTables like:

```
static const YamlLookupTable jitterFilterLut = {
  {  0, "GLOBAL"  },
  {  1, "OFF"  },
  {  2, "ON"  },
};
```

- Which is not derived from the YAML generation.

**Comment by stephenaa** [comment]
> Hm... or is it the _lack of conversion_ in Companion that could be problem?

The radio setting was renamed to 'noJitterFilter', so having no conversion from the old name (jitterFilter) would cause reverting the radio setting to the default. Do we need some explicit conversion here?

**Comment by elecpower** [comment]
> The radio setting was renamed to 'noJitterFilter', so having no conversion from the old name (jitterFilter) would cause reverting the radio setting to the default. Do we need some explicit conversion here?
So after rechecking with fresh eyes and some tests looks okay. Edited settings for radio and model then transferred to simulator and in sync.

**Comment by raphaelcoeffic** [comment]
> > Hm... or is it the _lack of conversion_ in Companion that could be problem?
> 
> The radio setting was renamed to 'noJitterFilter', so having no conversion from the old name (jitterFilter) would cause reverting the radio setting to the default. Do we need some explicit conversion here?

The trick to add a fake attribute that is only read but not written. The same applies to Companion.

**Comment by pfeerick** [comment]
Just checking my understanding... a  "if oldName is present, read it in as if it were newName, but then forget all about it?" type logic?

**Comment by pfeerick** [comment]
Seems to be working perfectly. I added a line to make Companion read old value but threat as new also, so will merge once tests are complete.

**Review by raphaelcoeffic — APPROVED** [review]

**Pull request merged**
