### PR TITLE
feat(bw): Change layout of telemetry page on B&W radios to match color layout.

### PR DESCRIPTION
**Pull request by philmoz**
As suggested on RC Video Reviews [video on 2.9 RC1 for B&W radios](https://www.youtube.com/watch?v=gKQeohGMTLk).

Moves the RSSI alarms section to below the sensors section.

### CODE REVIEW

**Comment by pfeerick** [comment]
Something more is needed for both implementations... try scrolling up and down the page so it wraps around (or more simply, just scroll back one line so it wraps around, and then forwards so you should be at the top again), and the sensors heading will now be missing. When it was RSSI before it didn't disappear. But sleeps calls.... 🛌

**Comment by philmoz** [comment]
> Something more is needed for both implementations... try scrolling up and down the page so it wraps around (or more simply, just scroll back one line so it wraps around, and then forwards so you should be at the top again), and the sensors heading will now be missing. When it was RSSI before it didn't disappear. But sleeps calls.... 🛌

This only happens if the sensor list is empty so that the first item is the 'Discover new' button.

**Comment by pfeerick** [comment]
ok, I can see that `k` never returns to `0` on the wraparound, hence ITEM_TELEMETRY_SENSORS_LABEL isn't displayed again. This just feels broken if you can lose a line simply by scrolling, regardless of whether sensors are present are not. It would be nice if that can be fixed, but there is no denying this is an improvement given the RSSI / link quality settings are really only looked at a few and then forgotten.

**Comment by philmoz** [comment]
I've looked at the (complex) menu navigation code and I'm not sure this is easily fixable without risking breaking other stuff.

Maybe something for a separate PR.

**Comment by pfeerick** [comment]
I'll give @3djc a chance to have a look that this and if there's no easy workaround, yes, definitely leave it for a separate PR.

**Comment by philmoz** [comment]
Superseded by #3770

**Pull request closed without merging**
