### PR TITLE
chore(radio): exclude custom functions not relevant to handset

### PR DESCRIPTION
**Pull request by philmoz**
Cleanup sorted list of custom function names to not include entries that are not relevant.

Note: FUNC_RGB_LED should also be conditional; but requires more complex changes.

Also add yaml_datastructs_f16.cpp for F16 radio.

### CODE REVIEW

**Comment by 3djc** [comment]
Well @raphaelcoeffic doesn't want defines anymore, so unsure which direction  to go now

**Comment by philmoz** [comment]
This restores the custom function list content as it was before #5429; but with the list sorted.

Removing all #defines would be a huge undertaking and would increase RAM and FLASH size (having to do everything at runtime instead of compile time).

**Comment by pfeerick** [comment]
Some are unavoidable, but the point is that they should be feature specific, not radio specific... i..e `AUDIO_MUTE_GPIO`, `LED_STRIP_GPIO`, or even `VIDEO_SWITCH` are not *specific* to any radio handset... but whether those features/capabilities exist or not. So no more `if X7 or X9D or XLITE` in main code... only feature defines... the hal / board file is what should be dictating what features the handsets have, and shouldn't be present anywhere else. And if it can be determined at runtime, rather than at compile time, then even better, as that gets us closer to the idea of a single universal or only a handful of binaries - aka unified targets are implemented by BF or ELRS. Although that is a much longer term goal, and probably have to be after the smaller F4s are sunset...

**Comment by philmoz** [comment]
Agree 100% there needs to be better distinction between features and hardware.

LED_STRIP_GPIO is a perfect example.
It is defined in hal.h not in the CMake setup - which is correct as it is a hardware value, not a feature.
But it is used to control code inclusion / exclusion which is wrong IMO.
There should be a corresponding feature definition for RGB_LED which would then make it easier to remove the FUNC_RGB_LED stuff from radios that don't need it.

**Comment by gagarinlg** [comment]
At least some can probably be replaced by constexpr functions. Especially with lto, most of the then unneeded code will be optimised away.

**Comment by 3djc** [comment]
> Agree 100% there needs to be better distinction between features and hardware.
> 
> LED_STRIP_GPIO is a perfect example. It is defined in hal.h not in the CMake setup - which is correct as it is a hardware value, not a feature. But it is used to control code inclusion / exclusion which is wrong IMO. There should be a corresponding feature definition for RGB_LED which would then make it easier to remove the FUNC_RGB_LED stuff from radios that don't need it.

I disagree on that, if there is no RGB led in hardware, don't include the code for it sound highly logical to me, I don't see the logic in having to mirror it in cmake. The FUNC_RGB_LED should be removed from radio that don't have the relevant hardware.

Features are things that you can decide to include or not, not based on HW capabilities, but on a choice. FrSky BT is one for example

**Comment by philmoz** [comment]
> I disagree on that, if there is no RGB led in hardware, don't include the code for it sound highly logical to me, I don't see the logic in having to mirror it in cmake. The FUNC_RGB_LED should be removed from radio that don't have the relevant hardware.

That's my point; but at the moment the RGB LED code is compiled and included for every radio even though only a few need it. At runtime the function is not allowed to be selected; but all the code is still built into the firmware and just wasting space.

To properly control it a 'feature' needs to be defined at the CMake level - the hal.h GPIO value is not sufficient.

Contrast RGB_LED to how VIDEO_SWITCH and VIDEO_SWITCH_GPIO is being done.

**Comment by 3djc** [comment]
I definitely agree with you on the waste of space, but I was lead to understand that this was an edgetx deliberate choice for the goal of a single binary.

I really don't understand the value of having to define things two times, one in cmake, one in hal.h, when they are totally dependent (ie you cannot have one without the other and vice versa). Why two places ???

**Comment by philmoz** [comment]
> I really don't understand the value of having to define things two times, one in cmake, one in hal.h, when they are totally dependent (ie you cannot have one without the other and vice versa). Why two places ???

They are different things - one defines a feature present on the radio, the other defines hardware specific value(s) necessary to implement the feature.

The defines in hal.h don't work to control what gets included when generating the yaml_datastructs files. So without a feature definition at the CMake level we are stuck with RGB LED code in every radio.

IMO a universal binary is a pipe dream given the disparate range of hardware supported.

**Comment by pfeerick** [comment]
> IMO a universal binary is a pipe dream given the disparate range of hardware supported.

_Once_ there is enough flash space to contain everything (i.e. once the F2 and smaller F4 MCUs fall out of support) ... there should really only be a need for each MCU type + screen type (bw/colorlcd) variation. Rather than the current situation... where the are several different builds for the same MCU, same screen type, with GPIOs basically just used different. It may end up the same as how ELRS do it now, which is that configuration info is slapped onto the binary at "compile" time... which is really just downloading the binary and slapping the json file onto it. 

> They are different things - one defines a feature present on the radio, the other defines hardware specific value(s) necessary to implement the feature.

Yes, this is how I see it also... as while you can't have one with out the other (feature without hardware), you can have hardware but the feature turned off, for whatever reason). Another way to look at it is that the CMake can be a list of the capabilities of the radio, without the specifics of how it is implemented.

**Comment by gagarinlg** [comment]
> _Once_ there is enough flash space to contain everything (i.e. once the F2 and smaller F4 MCUs fall out of support) ... there should really only be a need for each MCU type + screen type (bw/colorlcd) variation. Rather than the current situation... where the are several different builds for the same MCU, same screen type, with GPIOs basically just used different. It may end up the same as how ELRS do it now, which is that configuration info is slapped onto the binary at "compile" time... which is really just downloading the binary and slapping the json file onto it.

Where it is gettig difficult is when the oscillators have different frequencies. Also we have issues to detect what radio we are on, unless it is wrtitten somewhere in the internal flash.

**Comment by pfeerick** [comment]
LGTM on T15/V16/F16 (hm... should I have broken the T16 out again so that they are all 16 🤣)...

**Pull request merged**
