### PR TITLE
feat(ui): elevates the max possible telemetry screens count on color radios

### PR DESCRIPTION
**Pull request by rotorman**
Elevates the max telemetry screen count from 5 to 10 on color radios (this is especially interesting in combination with full screen LUA widgets that offer multiple pages):

grafik

### CODE REVIEW

**Comment by elecpower** [comment]
@rotorman extra screens will be lost on Companion read/write so added label as a reminder

**Comment by pfeerick** [comment]
https://github.com/EdgeTX/edgetx/tree/2995-fixup will be doing the `carryTrim -> trimSource` changes once finished.

**Comment by rotorman** [comment]
Good news! I removed the _carryTrim -> trimSource_ fix from this PR.

**Comment by elecpower** [comment]
@rotorman since you asked nicely I will oblige

**Comment by elecpower** [comment]
@rotorman tested read/write in both directions with TX16S libsim and regression tested Companion model setup custom screens tab

**Comment by pfeerick** [comment]
I'll review and merge this after one or two other PRs that will be affecting yaml storage as it's the easier PR to rebase. Also need to fix a bug whereby on main adding the fourth screen doesn't add the + button to create the 5th - need to exit and re-enter the page. So I would presume the 9th view for this PR will have the same problem.

**Comment by elecpower** [comment]
Yes 9th view I had to exit and re-enter but thought it was me and didn't retest.

**Comment by ParkerEde** [comment]
here is something wrong. The headline shows at page 1-9 correct the number, but page 10 shows ":" instead

page9
page10

If I am on page 9 and then press TELE, the settings page for 9 also opens. It's OK for pages 1-9. But on page 10, page 9 opens, which is wrong.

**Comment by rotorman** [comment]
@ParkerEde Thank you for this report. Please have a look at PR #3357

**Comment by ParkerEde** [comment]
@rotorman your Fix PR #3357 is okay now.
But this part of my report isn't fixed:
_If I am on page 9 and then press TELE, the settings page for 9 also opens. It's OK for pages 1-9. But on page 10, page 9 opens, which is wrong._

https://user-images.githubusercontent.com/15068446/225656273-f95a087e-f6a6-4021-aafb-95a781b72050.mp4

**Comment by ParkerEde** [comment]
yes

**Comment by rotorman** [comment]
Tested with v2.8.0 release and I see the same behaviour also with v2.8.0 on screen 5, thus the issue was present already pre PR #3357 for last screen.

**Comment by rotorman** [comment]
@ParkerEde I pushed a fix to PR #3357 - can you please re-try it.

**Comment by ParkerEde** [comment]
@rotorman jep. works now.

**Comment by JimB40** [comment]
Have you also fixed GF/SF so it allows to select main view greater than 5?

**Comment by rotorman** [comment]
@JimB40 You are asking if the additions from #2160 still work? The code from #2160 uses `getMainViewsCount()`and no hard-coded value:
https://github.com/EdgeTX/edgetx/blob/9a898533d18e9e73b54c1ba2938aaddf61b33365/radio/src/gui/colorlcd/special_functions.cpp#L243-L247

**Pull request merged**
