### PR TITLE
Added CN and TW translations for new content

### PR DESCRIPTION
**Pull request by zyren**
Added CN and TW translations for new content.

### CODE REVIEW

**Comment by pfeerick** [comment]
Thanks for this! :)

Can you also add the equivalent of 

```
#define TR_MENUWHENDONE                CENTER "\006" TR_ENTER " WHEN DONE"
```

above 

```
#define TR_FREE                        "空闲"
```

as that seems to be completely missing for CN and TW for some reason. Will be needed if we manage to get B&W builds CN/TW builds happening...

**Comment by zyren** [comment]
> Thanks for this! :)
> 
> Can you also add the equivalent of
> 
> ```
> #define TR_MENUWHENDONE                CENTER "\006" TR_ENTER " WHEN DONE"
> ```
> 
> above
> 
> ```
> #define TR_FREE                        "空闲"
> ```
> 
> as that seems to be completely missing for CN and TW for some reason. Will be needed if we manage to get B&W builds CN/TW builds happening...

Ok, I will carefully compare the EN files and re-edit these translations.

**Comment by pfeerick** [comment]
Thank you for that! 😄 I'll review this tonight. The `TR_MENUWHENDONE` define had been missing for a while (I was going to add it #889 several months ago) but dropped it as,  if I remember correct, the firmware binaries ended up too big. Regardless, having the translations all done brings us one step closer!

**Comment by pfeerick** [comment]
As far as I can tell this is working fine for colorlcd. B&W at least compiles now, but has no font at all, but I think that is a problem for another PR.

**Pull request merged**
