### PR TITLE
Add serial passthrough for T-Pro

### PR DESCRIPTION
**Pull request by pkendall64**
The Jumper T-Pro has a small 2 pin (unpopulated) header on the main board right next to the SD card holder. The pin closest to the SD card holder is connected to PF11 on the MCU.

This PR adds PF11 as the GPIO_BOOTCMD_PIN and also enables serial-passthrough and CLI on the T-Pro.

Adding a transistor (any NPN transistor should work) and 4k7 resistor as shown in the schematic and photo below, the Jumper T-Pro can do full ETX passthrough flashing of the internal ELRS module.

The hardware mod is optional and a user can still perform ETX passthrough flashing of the module with the PR if they hold the GPIO0 button down on the internal module just prior to flashing until the flashing progress starts.

Screen Shot 2022-02-08 at 7 49 40 AM

IMG_0060

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
Was able to flash T-Pro ELRS master branch using PlatformIO using `_via_ETX`. Added a socket, and used a 2N3904 NPN + 4k7 resistor. Thank you for the hard work that went into figuring this out and getting it to work!! :)

IMG_20220209_145837

**Comment by JyeSmith** [comment]
All good here as well.  I pinched this NPN from the beeper curcuit of an old FC, and coupled with a 10k resistor I found on the ground.

image

**Comment by pfeerick** [comment]
Nice! I very nearly used a SMD transistor as well but the through hole ones
were nearer. Very neat indeed! :)

**Comment by Ivosch** [comment]
Hello guys, thanks for your work!
Unfortunately this hw patch doesn't work for me. I tried 2 types of transistors - BC548c and BC337, emitter connected to the ground. But PF11 signal seems to be weak/low:
remote control ON - PF11 ~0V
remote control ON and USB connected - PF11 ~2.4V
remote control ON, USB connected and transistor with resistor installed - PF11 ~0.5V and this is not enough to open transistor
any ideas?

**Comment by pkendall64** [comment]
> Hello guys, thanks for your work! Unfortunately this hw patch doesn't work for me. I tried 2 types of transistors - BC548c and BC337, emitter connected to the ground. But PF11 signal seems to be weak/low: remote control ON - PF11 ~0V remote control ON and USB connected - PF11 ~2.4V remote control ON, USB connected and transistor with resistor installed - PF11 ~0.5V and this is not enough to open transistor Also I tried 3k-47k resistors. Edge TX 2.7.1 installed. any ideas?

The only thing I can suggest is to check your wiring of the transistor as the BC337 pinout is the opposite to the S8050 I used. Also when you plug in the USB you have to select "USB Serial (VCP)" from the menu to enable the code for passthrough.

**Comment by Meldinov** [comment]
sadly, my t-pro board is different and does not have that 2pin header
imagen

**Pull request merged**
