### PR TITLE
Add a DEBUG_BLUETOOTH option to clean up console

### PR DESCRIPTION
**Pull request by dlktdr**
Bluetooth prints a ridiculous amount of data with or without debug turned on. It's currently writing every byte received. Fills the console so quick you can't see anything else happening.

This pull request only prints that data if specifically requested via a cmake option.

Printing of every byte is completely removed.

### CODE REVIEW

**Comment by rotorman** [comment]
Gimme some days to test this PR.
I actually would prefer to have (at least an option) to stream/mirror out via Debug the data received via Bluetooth. I have used this function in the past and found it quite useful.

**Comment by dlktdr** [comment]
Not a rush.. been like that there for 3yrs :)

Could just remove the 96120c1 commit to keep the every byte output. If does need a CRLF added. If actually debugging BT it's easy enough to temporarily comment this out if you don't want every byte.

**Comment by rotorman** [comment]
I tested this PR on a TX16S, firmware built locally with `-DDEBUG=YES` and `-DDEBUG_BLUETOOTH=YES`, FTDI connected to AUX1.
I checked the behaviour with FrSky Bluetooth module connected to internal pads (USART6) and also nothing attached to USART6. During my tests I used a [famous HeadTracker pj. device](https://github.com/dlktdr/HeadTracker) as a Bluetooth connection partner.

With FrSky BT module connected, I noticed two issues in the debug output:
1) Bluetooth messages are not prepended with a timestamp, like other debug output is, and
2) trainer telegram is split awkwardly in the output not at telegram borders

Here is a snippet of debug output showing this:
```
225.37s: unregister widget YaapuMaps
225.37s: luaClose 0xd01439f0
7E 80 DC 5D C5 DC 51 56 B3 5C A5 DC 5D C5 11
7E 7E 80 DC 5D C5 DC 51 56 B3 5C A5 DC 5D C5 11
7E 7E 80 DC 5D C5 DC 51 56 B3 5C A5 DC 5D C5 11
```

expected would be:
```
225.37s: unregister widget YaapuMaps
225.37s: luaClose 0xd01439f0
<timestamp here> 7E 80 DC 5D C5 DC 51 56 B3 5C A5 DC 5D C5 11 7E
<timestamp here> 7E 80 DC 5D C5 DC 51 56 B3 5C A5 DC 5D C5 11 7E
<timestamp here> 7E 80 DC 5D C5 DC 51 56 B3 5C A5 DC 5D C5 11 7E
```
The FrSky trainer starts and stops with `0x7E`, ideally the debug output should also list it this way.

For completeness sake, I tested this PR also with `-DDEBUG=YES` and `-DDEBUG_BLUETOOTH=NO` and did not see any adverse effects.

**Comment by dlktdr** [comment]
I didn't touch any of the formatting. But yes I agree I think it should contain the timestamp. I will modify it.

How do you feel about removing every byte of output received. I don't understand why this is here 
https://github.com/EdgeTX/edgetx/blob/d3f35e83343f7d45048af76c01fa875970d4b733/radio/src/targets/common/arm/stm32/bluetooth_driver.cpp#L126

when it's pushed on to the fifo and printed here anyway.. seems like it was added temporarily and forgot about.

https://github.com/EdgeTX/edgetx/blob/d3f35e83343f7d45048af76c01fa875970d4b733/radio/src/bluetooth.cpp#L98

I will see about fixing where it inserts the CRLF so it lands properly on a frame. 

Also noticed that the receive has similar issue. Don't pull just yet will make a few more tweaks,

...Famous .pj. device :)

**Comment by rotorman** [comment]
> How do you feel about removing every byte of output received. I don't understand why this is here

I would just comment it out by default in the ISR instead of completely removing it - as if `Bluetooth::readline()` for a reason or another never gets called, you get no Bluetooth input trace output otherwise.

**Comment by pfeerick** [comment]
> I would just comment it out by default in the ISR instead of completely removing it

I agree, better to have the TRACE lines there for use, rather than removing them completely. It would be even better if it were all behind a flag... DEBUG_BLUETOOTH_VERBOSE perhaps? so you can turn them on if needed for debugging the hardware/link, but it is entirely up to you if you want to go that way/that far.

**Comment by dlktdr** [comment]
Added a verbose option. -DDEBUG_BLUETOOTH_VERBOSE
Added timestamp output on send trainer / receive trainer and send telemetry.
Line breaks at end of frames on send and receive. As best I could without adding a lot of modification simply looks for two START/STOP_BYTES.

```
2.57s: touch state = 0x80
2.57s: touch event = NONE
BT< OK+DISCS
BT< OK+DISC:EB2F1ADE447B
BT< OK+DISC:F6D98953D644
BT< OK+DISC:EB4210D5B28D
BT< OK+DISCE
...
BT< OK+CONNA
278.30s: touch state = 0x80
278.31s: touch event = NONE
BT< Connecting to:EB2F1ADE447B
BT< Connected:EB2F1ADE447B
4D 54 55 20 53 69 7A 65 3A 36 35 0D 0A 4D 54 55 20 53 69 7A 65 3A 20 36 35 0D 0A 50 48 59 20 55 70 64 61 74 65 20 43 6F 6D 70 6C 65 74 65 0D 0A 43 75 72 72 65 6E 74 20 50 48 59 3A 20 32 4D 0D 0A 2c9.26s: RamBackupWrite sdsize=11943 backupsize=4492 rlcsize=404
7E
280.31s: 80 4B 66 25 E6 6D C5 DC 5D C5 DC 5D C5 C6 7E
280.31s: 7E 80 4B 66 25 E6 6D C5 DC 5D C5 DC 5D C5 C6 7E
280.31s: 7E 80 4B 66 25 E6 6D C5 DC 5D C5 DC 5D C5 C6 7E
```

Verbose prints everything. It's still a mess but it's all there if needed ;)

**Comment by rotorman** [comment]
Tested on physical RM TX16S with FrSky BT module on AUX2/USART6 and connected to BT Headtraker.
Checked with firmware built with `-DDEBUG_BLUETOOTH` and with second firmware built with `-DDEBUG_BLUETOOTH` and `-DDEBUG_BLUETOOTH_VERBOSE`.

First trainer telegram START byte 0x7E is listed on a separate line and BT messages have no timestamp.

Here an example output snippet from firmware built with `-DDEBUG_BLUETOOTH`:
```
37.51s: RamBackupWrite sdsize=11943 backupsize=4492 rlcsize=381
BT< Connected:FF1C17AABBCC
7E
44.08s: 80 DC 5D C5 DC 59 E7 8D 5E 65 DC 5D C5 54 7E
44.08s: 7E 80 DC 5D C5 DC 59 E7 8D 5E 65 DC 5D C5 54 7E
```

With `-DDEBUG_BLUETOOTH` and `-DDEBUG_BLUETOOTH_VERBOSE` the output is (example snippet):
```
BT 5D
BT C5
BT 6D
BT 7E
7E 80 DC 5D C5 DC 59 E7 95 5F 45 DC 5D C5 6D 7E 
21.28s: 7E 80 DC 5D C5 DC 59 E7 95 5F 45 DC 5D C5 6D 7E 
21.28s: 7E 80 DC 5D C5 DC 59 E7 95 5F 45 DC 5D C5 6D 7E 
21.28s: BT 7E
BT 80
BT DC
BT 5D
BT C5
BT DC
BT 59
BT E7
BT 95
BT 5F
BT 45
BT DC
BT 5D
BT C5
BT 6D
BT 7E
BT 7E
BT 80
BT DC
BT 5D
BT C5
BT DC
BT 59
BT E7
BT 95
BT 5F
BT 45
BT DC
BT 5D
BT C5
BT 6D
BT 7E
BT 7E
BT 80
BT DC
BT 5D
BT C5
BT DC
BT 59
BT E7
BT 95
BT 5F
BT 45
BT DC
BT 5D
BT C5
BT 6D
BT 7E
7E 80 DC 5D C5 DC 59 E7 95 5F 45 DC 5D C5 6D 7E 
21.33s: 7E 80 DC 5D C5 DC 59 E7 95 5F 45 DC 5D C5 6D 7E 
21.33s: 7E 80 DC 5D C5 DC 59 E7 95 5F 45 DC 5D C5 6D 7E 
21.33s: BT 7E
BT 80
BT DC
BT 5D
BT C5
```

I will merge it as is, it is an improvement for debugging - does not need to be super pretty.

**Pull request merged**
