### PR TITLE
fix: splash screen on TProV2

### PR DESCRIPTION
**Pull request by 3djc**
Fixes splash not drawn even if requested for TPro V2 (and possibly others)

### CODE REVIEW

**Comment by philmoz** [comment]
This is needed on my X7S as well otherwise the splash screen randomly closes before the timeout expires.

**Comment by pfeerick** [comment]
@3djc The PR works as intially described - i.e. "do not consider customisable switches as part of inactivity" ... but I'm curious as to the reasoning for that... why should the function switches be considered differently to any other switch in this regard? 

@philmoz Was it truly random, or because of a switch/key/gimbal (i.e. activity) input, in which case the splash screen was apparently supposed to be skipped on B&W (whereas on colorlcd it is now skippable via a hard key press).

**Comment by philmoz** [comment]
It was definitely random - the loops summing the analog and switch values were processing non-existent entries.

**Comment by 3djc** [comment]
And because customisable switches can (and likely will) be changed during model load

**Pull request merged**
