### PR TITLE
Added string constants to the read-only tables in Lua

### PR DESCRIPTION
**Pull request by jfrickmann**
In addition to functions and number constants, string constants are now also available in rotables.

I have added the special characters as `CHAR_RIGHT`, `CHAR_LEFT`, `CHAR_UP`, `CHAR_DOWN`, `CHAR_DELTA`, `CHAR_STICK`, `CHAR_POT`, `CHAR_SLIDER`, `CHAR_SWITCH`, `CHAR_TRIM`, `CHAR_INPUT`, `CHAR_FUNCTION`, `CHAR_CYC`, `CHAR_TRAINER`, `CHAR_CHANNEL`, `CHAR_TELEMETRY`, and `CHAR_LUA`.

We can also add other string constants, e.g. some translation strings - please let me know if you have some in mind!

### CODE REVIEW

**Comment by jfrickmann** [comment]
Or you can edit a logical switch in the simulator (e.g. AND type that takes switch input). What you see here should also correspond to what you get in Lua:
Untitled
That's the advantage of using the exact same functions to get the valid switches and names, instead of coming up with a new list of names and trying to keep it all synchronized!

**Comment by wimalopaan** [comment]
Some time ago I had the request for the "@" sign. But I think, that is a different story because it is not in the font-bitmaps?

**Comment by wimalopaan** [comment]
Very well done and many thanks!
Works for me (together with #1154)

**Comment by pfeerick** [comment]
> Some time ago I had the request for the "@" sign. But I think, that is a different story because it is not in the font-bitmaps?

Yes, very different, the font map needs updating and then it should be available system wide. A 2.7 problem I think, unless we can do it in 2.6 without upsetting anything.

**Pull request merged**
