### PR TITLE
For consideration - Curve edit layout update for color LCD

### PR DESCRIPTION
**Pull request by philmoz**
Here is a revised layout for the curve edit page. I was not a fan of the horizontal scroll for the curve points (when there were more than fit across the page), so I organised them in rows of 6, with X & Y labels. Some scrolling is still required if you have a lot of points on the curve; but I think it's more obvious and in keeping with the rest of the UI.

Screen Shot 2022-12-28 at 10 51 17 am

Screen Shot 2022-12-28 at 10 53 05 am

### CODE REVIEW

**Comment by pfeerick** [comment]
> I was not a fan of the horizontal scroll for the curve points 

Yes, it also wasn't so intuitive if you didn't realise it scrolled, so it makes much more sense to just have all the fields laid out.

**Comment by Eldenroot** [comment]
I reminds me Spektrum

**Comment by raphaelcoeffic** [comment]
I’m wondering if it wouldn’t make more sense to show only the point being edited, and otherwise only the curve. That requires however a way to cycle through points (possibly having the possibility to select them directly via touch in the graphic).

**Comment by elecpower** [comment]
> I’m wondering if it wouldn’t make more sense to show only the point being edited, and otherwise only the curve. That requires however a way to cycle through points (possibly having the possibility to select them directly via touch in the graphic).

or have first, next, previous and last buttons

**Comment by JimB40** [comment]
Exactly no need to display all points values. It makes UI cluttered. Just x&y of one point (selected) and selected point is highlighted on preview. This will make this edit page clean and tidy. Regarding points nav. next/prev buttons. We may proof taping also on point to speed up selection, but with max 17 point may be prone to errors. Needs to be tested on physical radio.

**Comment by elecpower** [comment]
> Exactly no need to display all points values. It makes UI cluttered. Just x&y of one point (selected) and selected point is highlighted on preview. This will make this edit page clean and tidy. Regarding points nav. next/prev buttons. We may proof taping also on point to speed up selection, but with max 17 point may be prone to errors. Needs to be tested on physical radio.

Tapping graphic would be challenging to select accurately thus why the nav buttons suggestion

**Comment by Eldenroot** [comment]
Maybe just me, but it should be aligned (numbers) to center, not?

image

**Comment by philmoz** [comment]
The point labels (black) and the X values are centred; but the editable Y values always left align in the control. I could not find a way to change this.

**Comment by philmoz** [comment]
Alternate UI based on everyones comments.
- X & Y values of only 'selected' point shown
- Buttons to change point, and edit values
- Selected point highlighted on preview

This is just an idea so ways to improve it are welcome - or shoot it down if it is really bad :)

Also fixed issue where preview curve was being constantly redrawn even when nothing had changed.

Screen Shot 2022-12-29 at 3 01 44 pm

Screen Shot 2022-12-29 at 3 01 00 pm

**Comment by Eldenroot** [comment]
I do not use touch screen for this kind of settings. Anyway I miss all values displayed at once on one screen. Now ho have to click too much to cycle through all of them, it was better before.

Really dificult to find a good way for touch and notouch users.

Maybe add some button with curve points values on one screen? Something like monitor

**Comment by raphaelcoeffic** [comment]
@Eldenroot you mean just displaying a table with all points? That should be doable, I guess.

**Comment by Eldenroot** [comment]
@raphaelcoeffic - something like that. Just imagine the situation when you use 16 points curve and you have to click one by one and remember all the points and values... 

Thats why I liked first solution more, but I understand that touch screen is useful and we have to go in both directions.

There should be a way to see all points and maybe add some click (touch) on value in the list to direct edit the number.

**Comment by JimB40** [comment]
Can you give real world example of setting 16 points curve with exact precision that "you have to remember all values"?

**Comment by Eldenroot** [comment]
> Can you give real world example of setting 16 points curve with exact precision that "you have to remember all values"?

I am not the only user of EdgeTX :)

**Comment by pfeerick** [comment]
One way to get the best of both worlds (since some people prefer tables to graphs) is to perhaps have a button in the header, that switches between the current graph view, and an editable table view. However, I think this PR as it stands is looking quite nice :)

**Comment by JimB40** [comment]
> I am not the only user of EdgeTX :)
So bring user who gives IRL user that needs it. :)
Sorry but that is when UI starts to get clunky. Elegant & proper solving of non-related (non-existing) problems is very common case in tech world. (watch Musk interview).
Usability of good OS comes from the fact that it shows only what is needed (most of users needed). Rest is hidden or not implemented.

Any way if there would be a need for all values table (I still think there is not) it should be a pop-up preview without UI nav/edit elements (kind of monitor)

**Comment by JimB40** [comment]
ETX_29_CurveEdit_v01

General.
- Added frame not to clip edge points.
- Cross hair is not needed in Curve editing as source is not defined.
- Edited point is highlighted on graph
- X,Y values are displayed in edit fields. there can be selected point X,Y preview on graph (inversed yellow) but it can be challenge to code it's dynamic position so it is  not ovelaping curve
-----

Touch Navgation 
1. Point
>   selects next point
>I  selects last point
<  selects prev point
I< selects first point

2. X and Y
+  short press - increment value 1%
+  long press - repeat incrementing value 1%
-  short press - decrement value 1%
-  long press - repeat decrementing value 1%
>> short press - increment value 10%
>> long press - sets +100%
<< short press - decrement value 10%
<< long press - sets -100%

Tapping on above mentioned buttons should not change focus of edited variable. ie if user tap > , >I , < , I< focus is still on point value

Tapping on editable field can't open standard pop-up for value change as this will cover preview graph which important to see while changing values.
--------

Key navigation
When selecting next/prev field all > , >I , < , I<, + , - , >> , << don't get focus. (you can't select them via roller)

**Comment by JimB40** [comment]
ETX_29_CurveEdit_v01b
Another state.
Since coordinate system is -100,100 we may ephasise with dark blue 0 lines

**Comment by philmoz** [comment]
@JimB40 Thanks for that - lots to think about.

One thing. The crosshairs are active while creating / editing a curve. Moving any stick, pot or slider will move the crosshair position on the preview. I'm not sure how useful this is; but I pretty sure there will be people who want to keep it.

**Comment by JimB40** [comment]
Data source (channel, stick, ets) is not defined when editing curve as curve can be used in various places.
II think you meant Input editing.

**Comment by philmoz** [comment]
Check it on your radio - the curve editing code checks for movement of any stick, pot or slider and then uses that input to move the crosshair.

**Comment by Eldenroot** [comment]
> > I am not the only user of EdgeTX :)
> 
> So bring user who gives IRL case that he needs it. :) Sorry but that is when UI starts to get clunky. Elegant & proper solving of non-related (non-existing) problems is very common case in tech world. (watch Musk interview). Usability of good OS comes from the fact that it shows only what is needed (most of users needed). Rest is hidden or not implemented.
> 
> Any way if there would be a need for all values table (no data it is) it should be a pop-up preview without UI nav/edit elements (kind of monitor)

Well, I will not reply to the first part of your message...

Anyway, there should be some general rules for GUI which would be used across the EdgeTX. With these "rules" it would be much easier to unify the GUI etc. (also for new features and refactoring).

**Comment by Eldenroot** [comment]
> ETX_29_CurveEdit_v01b Another state. Since coordinate system is -100,100 we may ephasise with dark blue 0 lines

Not bad, but:

- numbers in a graph are too small
- I do not see a point why EdgeTX uses two different sizes for elements - I mean this below. I understand that the size of screen is limited but this looks not good (in my opinion), what do you think?
image

I miss the feature from other brands - you can move your stick, you can see the point in the curve (now it is implemented in latest EdgeTX) and anytime you can click to button "add a point". This will create a new point in the curve at the desired "position". Also see all points in one list (even not editable) would be really nice.

I do not use touchscreen, only for adjusting values (numbers) or for inserting letters... I am an old, schooled guy. Anyway, I do not say (I I do not want to say) that touch ui is bad, I like this posibility and I hope it will be better and better) :)

**Comment by JimB40** [comment]
@philmoz - Modified v02 - with source preview

No data source - 1st point selected
ETX_29_CurveEdit_v02a

No data source - 2nd point selected
ETX_29_CurveEdit_v02b

No data source - 3rd point selected
ETX_29_CurveEdit_v02c

No data source - 3rd point edited using keys
ETX_29_CurveEdit_v02d

Data source Mix CH01 - 3rd point selected
ETX_29_CurveEdit_v02e

Data source Mix CH01 - 3rd point selected
ETX_29_CurveEdit_v02f

**Comment by pfeerick** [comment]
> * I do not see a point why EdgeTX uses two different sizes for elements - I mean this below. I understand that the size of screen is limited but this looks not good (in my opinion), what do you think?
>   image

This is for another discussion, as the UI elements do still need some tweaking for consistent sizes, and that will then propagate through to all the screens automatically. The path of least resistance being be the combo fields not having all that extra padding as they do. 

> numbers in a graph are too small

This is on topic though, and I agree... we have a lovely big screen and then stupidly put the numbers in microscopic print. UI dev should be shot. :-P

> I miss the feature from other brands - you can move your stick, you can see the point in the curve (now it is implemented in latest EdgeTX) and anytime you can click to button "add a point". This will create a new point in the curve at the desired "position". Also see all points in one list (even not editable) would be really nice.

That's like the auto-source... we have the sticks/pots as X/Y inputs, so why not use them. If it were to be a "hidden" feature so no UI room is lost, it could be done as a long press on the point field (since it alters both the X and the Y). But IMO that should be done as little as possible, and there should be an "Set" button of sorts shown that you can press to set the current X/Y for the point.

Robert - love the UI mock-ups, but I tend to think the numbers above the graph are too small (and always were) - after all, we have a nice big colour display, and then put small text on it? Would prefer it to be the same size as the rest of the text.

**Comment by philmoz** [comment]
I started looking at implementing the design from @JimB40; but got sidetracked with a new idea that I thought I would throw out there.

In this the curve edit window opens with a list of app the points as buttons:
Screen Shot 2023-01-01 at 5 17 50 pm

Selecting one of the point buttons pops up the point editor:
Screen Shot 2023-01-01 at 5 18 17 pm

This leave more space for point editing controls. In the example I added a 'Symmetry' button that mirrors any changes to the opposite side point to keep the curve symmetrical. The 'Mirror' button flips the curve left to right.

**Comment by JimB40** [comment]
Ha! Very good idea. Now you opened my mind to next iteration that reduces click & screens.
Let me mock-up it

**Comment by Eldenroot** [comment]
So cool! Is possible to add a button to reset the curve? Maybe we need 3 points at minimum to make it?

**Comment by Eldenroot** [comment]
For your latest mock up, so when you tap on text (in your picture  X33 - input keyboard for touch users will popup?

**Comment by philmoz** [comment]
@Eldenroot The black text denotes labels, so do not trigger any actions. They could be editable numbers that trigger the number editor; but it would be a tight squeeze to fit both a number edit control and a label.

**Comment by JimB40** [comment]
Data Source: Mix CH01 

Point 1 selected
ETX_29_CurveEdit_v03a

Point 3 selected
ETX_29_CurveEdit_v03b

Moving roller highlights number of the point

**Comment by Eldenroot** [comment]
> Data Source: Mix CH01
> 
> Point 1 selected ETX_29_CurveEdit_v03a
> 
> Point 3 selected ETX_29_CurveEdit_v03b
> 
> Moving roller highlights number of the point

You are really good in these GUI things! Love IT!

**Comment by Eldenroot** [comment]
> But IMO that should be done as little as possible, and there should be an "Set" button of sorts shown that you can press to set the current X/Y for the point.

I agree, it sounds maybe as a small feature but in combination with stick position in graph it is a really useful feature. Anyway, I am not a coder, so not sure how difficult it is to implement. However would be nice to add it into this PR because of other GUI changes...

**Comment by JimB40** [comment]
Now regarding editing we I can see two options.

Option 1
More challenging to code but I have gut feeling that will be more efficient
When you tap on point or press roller it will go into edit state (point number backgound in theme edit color)
ETX_29_CurveEdit_v03c

Now.
Moving stick will change both X & Y values.
Tricky point is we don't know on wich channel is Throttle that is not self-centered/

----
Option 2 

Tap on value will switch to either point's X or Y edit (X or Y value background highlighte in Theme edit color)
Tapping on preview or Movin roller will change value
ETX_29_CurveEdit_v03d
ETX_29_CurveEdit_v03e

We may code that tapping on block closer to X or Y axix wil change +/- 1 while tapping on further block wil change +/- 10

**Comment by JimB40** [comment]
@philmoz pay attention to "whitespaces" as we call it (UI elements separation including screen edges)
To my experience 480x320 needs as minimum 4px.
Without whitespaces design always looks kind of broken.
whitespaceg

**Comment by philmoz** [comment]
@JimB40 I like your designs; but they might be a bit ambitious right now.

I'm not sure about trying to use sticks/pots/sliders to set the curve point position - I can't really see a way this could work.

I did play around with tapping of the graph to adjust the curve point however this forces user to use the touch interface - you lose the ability to use the scroll wheel and enter button. I also did not find it intuitive - it would need some sort of on screen indicators overlayed on the preview graph which might then interfere with the curve display.

I will sort out whitespace when I've got the basic UI sorted - LVGL is tricky (for me at least) to get all the padding options correct. Also we have to be careful as we are trying to squeeze a lot in and too much white space might make it harder - for example your designs have a smaller preview graph which might not be as clear when there are a lot of points in the curve.

**Comment by JimB40** [comment]
> I like your designs; but they might be a bit ambitious right now.
So let's ditch editing via stick. I may be tricky to make it intuitive together with using sticks for preview.

> I did play around with tapping of the graph to adjust the curve point however this forces user to use the touch interface - you lose the ability to use the scroll wheel and enter button. I also did not find it intuitive - it would need some sort of on screen indicators overlayed on the preview graph which might then interfere with the curve display.

Maybe we misunderstood. 
1. Tapping should be in parallel with roller once point's X or Y is marked green. So you can use either roller or tap. Tapping will not disable editing focus on X or Y.
2. About indicators I agree but 2.8/2.9 is transitional. We learn LVGL. There is a lot to improve. Example. Show me indicator that you can go to to Curve Editing while editing Input by long pressing Enter on curve selection. Then we have youtubers  
 that will explain it & everybody happy :) 

But the main point is that this UI design based on your proposition allows to 
 1.  Show overview all points values
 2. Select/edit quicky & directly X&Y of any point without going forth and back to new screen. 
 "Naviation tree" should be as small as possible.

**Comment by philmoz** [comment]
When the X or Y value is green the scroll wheel changes the value so you can only increase or decrease by 1 - that's a lot of wheel scrolling to get from -100 to +100.
Also how do you unselect the green and get back to scrolling between the points?

**Comment by JimB40** [comment]
1. Roller should have implemented INC/DEC based on speed. I think it's already part of numeric field edit. If you scroll fast increment value changes to 10, if you slow down go back to 1
2. X & Y of every point behaves like stadard number field, ie moving roller you focus  in carousel Name, Smooth, Type, X1, Y1, X2, Y2, ...  etc.  (just when X1 or Y1 is focused also 1 background is in focus color, when X2 or Y2 is focused also 2  background is in focus color) 
Presing ENTER goes to edit-mode. RTN back to selection. 
3. Tapping on X or Y enables edit mode intantly like  any other field.
4. Tapping ouside X or Y while in edit-mode switches editing off like any other field.

**Comment by philmoz** [comment]
> * Roller should have implemented INC/DEC based on speed. I think it's already part of numeric field edit. If you scroll fast increment value changes to 10, if you slow down go back to 1
> * X & Y of every point behaves like stadard number field, ie moving roller you focus  in carousel Name, Smooth, Type, X1, Y1, X2, Y2, ...  etc.  (just when X1 or Y1 is focused also 1 background is in focus color, when X2 or Y2 is focused also 2  background is in focus color)
> * Presing ENTER goes to edit-mode then  RTN backs to selection.
> * Tapping on X or Y enables edit mode intantly like  any other field.
> * Tapping ouside X or Y while in edit-mode switches editing off like any other field.

I'm even more confused now. Earlier you said that tapping an X/Y value activates it (highlighted in green) and then the user can edit it directly by scrolling with the wheel or tapping on invisible button areas on the preview graph. Now it sounds like you are saying tapping on X/Y opens the standard number edit keyboard popup to edit the value.

Which is it - you can't have both?

I don't understand why the number edit keyboard popup is an acceptable navigation pattern; but my point editor popup is not. The number edit keyboard can only change one value at a time and must be closed and re-opened to edit another, it covers the preview graph making it hard to see the effect of changes, and it lacks the ability to have quick access special convenience buttons like 'Symmetry' and 'Mirror'.

For example to create the curve below with the point editor takes 8 taps on the screen after entering the curve editor. Using the number edit keyboard would take at least 15 taps.
Screen Shot 2023-01-02 at 6 42 24 am

**Comment by philmoz** [comment]
> * Tapping on X or Y enables edit mode intantly like  any other field.

The X & Y buttons are very small (41x28) and close together. Users with large hands may have difficulty in tapping these.

**Comment by philmoz** [comment]
@JimB40 I've played around with your design some more and I think I am starting to understand what you are getting at.

My main concern at the moment is that, while it works well using the scroll wheel and enter button, it does not seem very touch friendly at the moment.

**Comment by pfeerick** [comment]
> So let's ditch editing via stick. I may be tricky to make it intuitive together with using sticks for preview.

This is probably where you need to look at how other systems (i.e. [Spektrum](https://www.youtube.com/watch?v=kpRKVUsDDwk)) have done this. It's not used for editing, it's used for assigning the initial point, which you can then fine tune. You are simply adding/assigning where the cursor preview is ;)


> I'm even more confused now. Earlier you said that tapping an X/Y value activates it (highlighted in green) and then the user can edit it directly by scrolling with the wheel or tapping on invisible button areas on the preview graph. Now it sounds like you are saying tapping on X/Y opens the standard number edit keyboard popup to edit the value.
> 
> Which is it - you can't have both? (I'm talking about tapping on the screen - not selecting with the wheel/enter).

I think that Robert may have missed explaining was that it wasn't going to open the standard number edit keyboard popup. When you use the scroll wheel ENT on a numberedit field, the number edit keypad doesn't come up and you scroll the RotEnc to change the value 'in situ' as it were, with acceleration if you scroll fast. I think what Robert was suggesting was that for touch instead of bringing up the number edit keyboard, the graph would become the editor, and you could tap the top part to increase, or bottom part to decrease the value in the case of the Y value being edited. And presumably the sides if it was the X axis.

**Comment by JimB40** [comment]
Exactly. Thx @pfeerick.

1. Number edit keypad (keyboard) doesn't show and we edit in-line (in-situ) as you call it, using hidden buttons on the graph. Here is very important to see preview graph all the time.

2. @philmoz Don't know what you mean by non touch friendly. Hidden buttons on graph are much bigger. We can even implement changing point while you move finger on graph with slide event. but let's proof simple tapping first.
 
3. I didn't know we have input preview PR'ed to curve editing. Now it makes sense to implement adding point based on preview position as it helps for example to add hovering point. But not all at once :) Kazein step by step.

**Comment by JimB40** [comment]
@philmoz tested with LUA above mentioned UI concept
screenshot_tx16s_23-03-20_08-36-38

1. Direct X,Y change works very efficiently. You just tap on X or Y and change quicly value with rotEncoder seeing all the time change on the graph.

2. Inc/Dec via tapping on graph works so-so. 
- Without  long tap event that would increase point's speed movement it requires lots of tapping
- Selecting points via tap (not implemented in LUA) can be also problematic due to resolusion (point/finger)
- Moving points via slide (not implemented in LUA) will work for rough changes. Precise set always need tap or press
So most probably no-go

Enclodisg LUA testing LUA script to give test ride (TX16S)
Just move file and folder into /SCRIPTS/TOOLS/
  
[ETX29_CurveEdit.zip](https://github.com/EdgeTX/edgetx/files/11015320/ETX29_CurveEdit.zip)

**Pull request closed without merging**
