### PR TITLE
enh(cpn): Cloudbuild

### LINKED ISSUE #4858: Companion add support for Cloudbuild
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Within Companion have the ability to update firmware from Cloudbuild as currently exists for firmware from GitHub 

### Describe alternatives you've considered

Use EdgeTX Buddy

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #4858

Summary of changes:
- add Cloudbuild as an updateable component
- add build process to interface
- improve freeing control to other processes during long running Internet requests
- allow the update process to be cancelled (stops at end of higher level processes)
- housekeeping inc removing unused files

Status:
- supports all radios defined in Companion and build targets
- language from radio profile
- supported options:
  - fai mode
- firmware file name [target radio]-[language][-option[-option]...]-[version].bin

TODO:
- [x] consider build timeout in case build server has build queue or has an issue (user can cancel but maybe not a great idea to have status requests hitting the build server every couple of seconds from multiple sources for long periods).
- [x] add async process to flash firmware

Phase 2 (separate PR):
- review and refine radio profile options GUI
- add more options to build request as they become supported by Cloudbuild system
- remove Github firmware update component when Cloudbuild stable

Screenshot from 2024-04-12 08-19-55

Screenshot from 2024-04-12 08-20-11

Screenshot from 2024-04-12 08-21-45

### CODE REVIEW

**Comment by elecpower** [comment]
Ready for playtime in the sandpit.
I have not tinkered with the Radio Profile options yet.
Refer description above for status.

**Comment by pfeerick** [comment]
Rodger Rodger... Will play with it on the weekend...

**Comment by elecpower** [comment]
> Quick run through until github rate limits said no... seems to be working just fine. Looking forward to phase 2 ;)
> Two minor niggles / food for future improvements :

aka complaints ;-)

> * I think I bumped into our old friend again, whereby making changes in Settings -> Update Settings -> Options (i.e. for MPM, changing filter from all MPM firmware to just the TAER firmwares) doesn't get honoured if you then go back into the downloads screen until you restart Companion. Minor, but confusing. 🤪

Will have to work on this one as it comes down to the way the settings were implemented. There are two copies: one on disk and one in memory. Maybe I erred when implementing the Updates.

> * It would be good if you could cancel all pending downloads... i.e. canceling while downloading MPM firmware led to needing to cancel multiple times.

You don't want much. Cancel wasn't an option until now. But to be honest I also thought the cancel could go further in a later PR. The rework to cascade up the lower level cancel is not insignificant and I wanted to get this Beta version incorporated for some invaluable feedback from fellow devs.

**Comment by pfeerick** [comment]
Could also be user error, as I hit the rate limit at the exact wrong time as I was trying to do a repeat test to confirm it wasn't PBKAC, but just wanted to flag it so it's at the back of your mind when working on this code... 

lol... more just QoL improvements that would nice to have *some day* (as would a "just go away already" button that... complaints get me stomping my (small) boots and waving a "thou shall not pass" sign :rofl:

**Comment by elecpower** [comment]
Your diligent testing and feedback is appreciated. These are on my TODO list.

**Pull request merged**
