### PR TITLE
Fix colors as per #730

### PR DESCRIPTION
**Pull request by kevinkoenig**
This PR begins to finalize the theme color changes.  as per #730.  There are still some items to finish, so dont merge this quite yet

### CODE REVIEW

**Comment by pfeerick** [comment]
I've just rebased this on current main and force pushed, as you did the same as me the the other day, and worked from an non-up-to-date `main` ;) So you'll just need make sure you pull the update on your end before the next commit ;)

**Comment by kevinkoenig** [comment]
i believe this is ready to merge now.  Please check with @JimB40 for final verification.  I am sure we will have additional changes, but we will handle those using a new PR

**Comment by kevinkoenig** [comment]
> I've just rebased this on current main and force pushed, as you did the same as me the the other day, and worked from an non-up-to-date `main` ;) So you'll just need make sure you pull the update on your end before the next commit ;)

well I didn't do that.  Sorry, missed your comment.  Now we need to do it again as I further updated things.  It is really ready to go now.  

I did revert some of the changes I merged in by mistake.  Sorry for the confusion

**Comment by pfeerick** [comment]
Oh boy, that's *not* the way to do it... by reverting you're you've actually told git to 'undo' commits/fixes that have been done... meaning merging this PR in it's current state will undo a lot of fixes. 

@raphaelcoeffic What's the best course of action? Cherry-pick into a new branch and pray?

**Comment by kevinkoenig** [comment]
I thought I might have screwed it up.  I will figure it out tomorrow.

**Comment by pfeerick** [comment]
Closing as was cleaned up and re-implemented in #833

**Pull request closed without merging**
