### PR TITLE
MAVLink for EdgeTx II

### PR DESCRIPTION
**Pull request by olliw42**
continuation of https://github.com/EdgeTX/edgetx/pull/26

(had to close that one since I screwed up my fork, sorry for the inconvenience)

* adds in addition generation of fastmavlink header files form CMakeList (thx to Risto for hints!)

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
> sorry for the inconvenience

No problem! I was just surprised ;-)

**Comment by olliw42** [comment]
the test fail ... it seem there is a tiny thing wrong with some flags ... I'll correct asap

**Comment by olliw42** [comment]
compiles locally now for t16 without mavlink ... let's see if this corrects the checks ...

**Comment by raphaelcoeffic** [comment]
To keep track of the Tests done by @rotorman, here are the current issues:
- [ ] When unchecking the new SYSTEM -> Hardware -> Mavlink external checkbox, power is cut to external JR-Bay VDD rail, even if the external RF is set to something other than OFF. IMHO it should stay on in case, when smth. other than OFF is set under Model -> Model Settings -> External RF. If the checkbox is unchecked and one power-cycles the radio, and something other than OFF is set to External RF, then JR-Bay VDD rail gets power. Thus currently, when toying with the Mavlink external, need to power cycle the radio in order to feed JR-Bay with power again.
- [ ] Top USB-C not providing virtual serial port option yet (for MAVLink routing) and offers only joystick and mass storage.

**Comment by olliw42** [comment]
issue 1 is known and "by design", i.e., not so easy to overcome ... if that should happen to be a blocker, it would be a hard blocker

issue 2 should be solved, I hope it already is, we would need a test with the latest pr

**Comment by rotorman** [comment]
I pulled the latest, rebuilt and tested on TX16S, incl. connected Mission Planner via top USB-C. I can verify that the second issue is solved. USB VCP pops up, it can be selected, and data flows to Mission Planner as expected. Awesome @olliw42 !

**Comment by raphaelcoeffic** [comment]
> issue 1 is known and "by design", i.e., not so easy to overcome ... if that should happen to be a blocker, it would be a hard blocker

We will find a solution, no worry, you're not alone ;-)

**Comment by rotorman** [comment]
Hi @olliw42 building with CMake flag DEBUG enabled (-DDEBUG=YES) fails unfortunately for aux_serial_driver.cpp for bootloader (undefined reference _mavlinkTelemAuxSerialRxFifo_). Some time ago for your OTX fork, I proposed a fix: https://github.com/olliw42/opentx/pull/10 Would be nice if you could look into this. Thanks!

**Comment by olliw42** [comment]
@rotorman many thx. applied (but not tested myself) :)

**Comment by rotorman** [comment]
Thank you. I can confirm, it builds now with -DDEBUG=YES.

Next issue: building with -DCLI=YES fails for mavlink_telem.cpp line 602: UART_MODE_NONE not declared (irrespective if -DDEBUG setting is included or not). Can you please check this as well.

**Comment by olliw42** [comment]
@rotorman 
ok, corrected and tested that it compiles for any combination of debug an cli for a t16

I want to **STRESS** however, that compiling is NOT a test that it works!! So, unless it is confirmed that it works for debug and/or cli I keep it marked as not tested and would remove it before any merge :)

**Comment by rotorman** [comment]
Hi @olliw42 Thank you for the update. To test CLI and DEBUG using USB, I added also USB_SERIAL=YES as well, thus -DTELEMETRY_MAVLINK=YES -DDEBUG=YES -DCLI=YES -DUSB_SERIAL=YES. This builds fine, but unfortunately with it, the radio does not start. When I power on the radio, I can see the chicken feet run, thus power is applied (6-Pos. has nothing to do with STM32F4), but screen remains blank. IMHO, USB_SERIAL/CLI should take precedence for the USB port, when compiled in, thus MAVLink should release it for the USB for USB_SERIAL/CLI. Would you care to have a look at the USB_SERIAL CMake option as well. Thank you!

**Comment by olliw42** [comment]
frankly, where is the news here? we are back to an old discussion
also, frankly, I'm not sure why I should work out all strange combinations of all sorts of flags which are not relevant to users
I guess what I will do is ensure that unexpected/untested combinations will disable mavlink telem

**Comment by rotorman** [comment]
I do not see that it needs to be so radical.
E.g. when using DEBUG and CLI, UART3 is reserved, UART6 and USB are free for MAVLINK
When using DEBUG, CLI and USB_SERIAL, USB is reserved, UART3 and UART6 are free for MAVLINK
When BLUETOOTH or GPS is added, UART6 is reserved for them.
Thus, IMHO there will always be room for MAVLINK to run on at least on possible port.

**Comment by olliw42** [comment]
I'm not saying that it wouldn't be possible, I was just saying that I don't see me working it out for all special-purpose cases.
I furtehr imply that it is better to not allow a compile which is not working than to allow it compile but not work
:)

**Comment by olliw42** [comment]
merge latest master, tested to work on T16 as much as it's possible to test currently

**Comment by rotorman** [comment]
Tested 6cf372c1 on RM TX16S (built under Ubuntu with GNU ARM Toolchain 10 2020-q4).

DragonLink with Flight controller outputting MAVLink @57600 baud, connected to AUX1, AUX2 has internal GPS. Mission Planner connected via top USB-C. My modified Yaapu LUA script with MavSDK additions running.
All looking good, except 6cf372c1 still the Shutdown EM bug in it (#104).

**Comment by rotorman** [comment]
Just noticed that on Shut-down I do not get the Link connected warning/confirmation dialog anymore.

**Comment by olliw42** [comment]
moved all mavlink string stuff to untranslated.h

also merged in yet the latest master :)

comment: something is weird as now it suddenly is 250 files changed ... not sure how that happened and/or how to correct....

**Comment by rotorman** [comment]
Just tested building _owpr-mavtelem2_ branch (562ebbe1) for the first time natively under Windows 10 with GNU Arm Toolchain v10 2020-q4. Works great, runs on radio w/o major issues, also the SBUS output.

- Can now turn off the radio without EM, even if LUA widgets are active.

- The old issue with turning off JR-bay power is still there. Even if under Model Setup -> External RF -> Mode is set to something other than Off (SBUS in my case), unchecking SYSTEM->Hardware->Mavlink external cuts power to external JR-Bay unnecessarily. Have to power-cycle to get JR-Bay (DragonLink in my case) powered up again. Maybe @raphaelcoeffic can help to fix this.

**Comment by olliw42** [comment]
thx for the testing!

concerning JR-power that's as said "by design", and i hope that's not going to be a blocker

concerning the "Link connected warning/confirmation dialog on shut down", you are saying it is working fine now?

concerning the 250 files I'm planning to recreate the PR into now the III attempt :)

**Comment by olliw42** [comment]
@raphaelcoeffic @rotorman 

the question doesn't belong to here, but let me ask nevertheless: Is GNU Arm Toolchain v10 2020-q4 now the OFFICIAL toolchain to be used on all platforms? 
(i.e. should I  change my docker too to use it?)

**Comment by rotorman** [comment]
> concerning the "Link connected warning/confirmation dialog on shut down", you are saying it is working fine now?

Forgot to report, sorry. This was my own fault, forgetting checking RSSI at Model Setup and setting the RSSI Scale to 255. Thus, yes, it works, as expected, Shutdown warning/confirmation is being emitted as it should.

> Is GNU Arm Toolchain v10 2020-q4 now the OFFICIAL toolchain to be used on all platforms?

PR #120 tests it at the moment also for GitHub.

**Comment by olliw42** [comment]
ok, thx
(would be helpful to strike out or mark resolved otherwise resolved issues)

so I'm closing it and replace it with MAVLink for EdgeTx III, PR https://github.com/EdgeTX/edgetx/pull/122

**Pull request closed without merging**
