### PR TITLE
feat(cpn): Add radio sort order edit and sorting models list by any column

### LINKED ISSUE #3033: Companion - Being able to sort models alphabetically
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

This is not a problem, it would be a considerable convenience, especially for people like me who have many models on TX.
It would be very useful to be able to sort models alphabetically based on Name, RX # or Labels by clicking on the relevant column.
This feature already exists on the tx side, so on Companion it would be easier to locate models with the same name or RX #.

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #3033 #3546

Summary of changes:
- add support for editing radio sort order (color radios only) Note: independent of models list sort order
- add support for sorting models list by any column in ascending or descending order
- housekeeping:
replace depreciated macro Q_DECL_OVERRIDE with override keyword
replace NULL with nullptr
stubs for model list label filtering (separate PR)

New color radio model list
After

Sort by RX# indicator
after2

New B&W radio model list
after bw

Sort by name indicator
after bw2

### CODE REVIEW

**Comment by robustini** [comment]
@elecpower thanks!
This fix your previous commits?
I have tried a recent compiled version but I see no possibility of effecting the short.

**Comment by elecpower** [comment]
> @elecpower thanks!
> This fix your previous commits?
> I have tried a recent compiled version but I see no possibility of effecting sorting.

This adds to previous commits.
If you mean radio sorting drop down not showing, you need to stretch the dialog horizontally to make enough space to display the drop down in the toolbar.

**Comment by robustini** [comment]
> > @elecpower thanks!
> > This fix your previous commits?
> > I have tried a recent compiled version but I see no possibility of effecting sorting.
> 
> This adds to previous commits. If you mean radio sorting drop down not showing, you need to stretch the dialog horizontally to make enough space to display the drop down in the toolbar.

I've tried but I don't see anything.

immagine

**Comment by elecpower** [comment]
Try dragging the Model toolbar below Radio Settings toolbar as my screenshot or keep stretching.

**Comment by robustini** [comment]
Nothing can be moved or dragged here.


https://github.com/EdgeTX/edgetx/assets/3864712/e8705042-f254-4d46-8496-e9f416af3b9c

**Comment by pfeerick** [comment]
I not sure you're running this PR build - it says 2.9.0-main instead of 2.9.0-PR3659 in that about screen...

**Comment by robustini** [comment]
> I not sure you're running this PR build - it says 2.9.0-main instead of 2.9.0-PR3659 in that about screen...

Downloaded from Action section, does the latest version also include all other previous fixes?

**Comment by pfeerick** [comment]
Thank link goes to PR#3501. A build for this PR would only include fixes as of two weeks ago, since it was added then and hasn't been rebased since.

**Comment by pfeerick** [comment]
Neil, are you happy enough with this PR to include it in 2.9?

**Comment by robustini** [comment]
> Thank link goes to PR#3501. A build for this PR would only include fixes as of two weeks ago, since it was added then and hasn't been rebased since.



That's the arcane revealed, thank you!
I thought the build was recent.

**Comment by pfeerick** [comment]
If you're on Windows, you'll be able to pick up a build shortly, as this the build for this PR expired today. Generally best to go via the Checks tab at the top of the PR you're interested in testing to make sure you get offered the right file ;) I've been known to test the wrong version of stuff by not doing that 🤭

**Comment by elecpower** [comment]
+1 to testing wrong branch

**Comment by elecpower** [comment]
> @elecpower Are you happy enough with this PR to include it in 2.9?

Yes. I should be around to fix my mistakes if any pop up in RCs. If any exist they'll likely be around drag drop and cut paste combination.

**Comment by pfeerick** [comment]
I did some quick drag'n'drop testing with a T-Pro ,and after confusing myself into thinking it wasn't working since the models had never been manually named, it seems to be working fine. 

For colour, I can't, but I presume this is because we basically can't "manualy" order models atm, only via the sorting?

**Comment by elecpower** [comment]
This PR has sort always active.
B&W has the 'luxury' of slots so you can move models between slots and sort by slot column. Colour no such 'luxury'.
Since colour radios have option for No Order then I suppose Companion should also. I'll see how cumbersome this would be to implement.

**Comment by pfeerick** [comment]
It's entirely up to you... ideally, could possibly add a "last opened" column for colorlcd, then, when you use the sort options, it would make the view match ... i.e. "Name up" would be make the name column sort ascending, "name down" make name column sort descending, etc, etc... but then that doesn't make sense given you can see all the labels, and depending on the label selected, you can only so x models... so the model list is going to be a bit of a mess whatever gets done until/if/when can also replicate the... active label view filter? 

Also, I think "none" is only an option on radio atm until you actually select one of the sorts, then you're sorta stuck with them (pun not intended).

**Comment by elecpower** [comment]
Models list is now unsorted by default. Sorting is turned on and off by double clicking any column. When turned on the double clicked column will be sorted ascending. When turned off the model list will be returned to the unordered state.

**Comment by pfeerick** [comment]
That seems to work just fine. And yes, definitely for a future effort.

**Pull request merged**
