### PR TITLE
Companion configure AUX serial port as "External module"

### PR DESCRIPTION
**Pull request by elecpower**
Summary of changes:
- the other half of #2562
- housekeeping

### CODE REVIEW

**Comment by elecpower** [comment]
I am correct to remove the externalaccessmod option all Radio Profile Options?

**Comment by pfeerick** [comment]
I believe so yes - this will be a "standard option" for radios that can support it, runtime configurable.

**Comment by elecpower** [comment]
If that be the case should not the now unnecessary compiler directives be removed from the radio side to avoid confusion?

**Comment by rotorman** [comment]
Indeed, good point - thx!

**Pull request merged**
