### PR TITLE
Add X7S BT detection

### LINKED ISSUE #3752: Bluetooth Settings missing in Hardware menu for Taranis QX7S
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Compared to the QX7, the Taranis QX7S has a built-in Bluetooth module. However, this is not displayed under SYSmenu/Hardware for configuration. This means that it cannot be activated for the trainer function and cannot be selected in modelsettings under DSC BTMaster or BTSlave.
This setting is already offered in Companion.

With the Taranis QX7S ACCESS, on the other hand, it is already correct.

### Expected Behavior

QX7S should offer BT settings in Hardwaremenu

### Steps To Reproduce

1. Enter Hardwaremenu
2. try to edit BT settings
3. observ, the BT settings are not offered

### Version

Other (Please specify below)

### Transmitter

FrSky Q X7 / Q X7S (ACCST)

### Operating System (OS)

Windows

### OS Version

_No response_

### Anything else?

2.9.0 RC1

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #3752

### CODE REVIEW

**Comment by philmoz** [comment]
Should we delete the redundant function BT_USART_IRQHandler in bluetooth_driver.cpp as part of this PR?

**Comment by raphaelcoeffic** [comment]
Gents, feel free to delete that `_OBSOLETE` code, no problem with me :-) And if it works, just merge it!

**Comment by raphaelcoeffic** [comment]
> Is it possible that this PR is not yet included in the 2.9 branch? Or do I just have tomatoes in my eyes? ;-)

Either way: it's been merged 3 days ago, so that it should be in today's nightly build.

**Comment by ParkerEde** [comment]
Yes, that is correct. I saw that too. However, I am specifically interested in branch 2.9, as I would like to test it extensively with all the PRs that have already been merged.

**Comment by raphaelcoeffic** [comment]
> However, I am specifically interested in branch 2.9, as I would like to test it extensively with all the PRs that have already been merged.

I don't think this has been cherry-picked to `2.9`, indeed. The question is whether or not this is necessary.

**Comment by 3djc** [comment]
I think it should, there is no other way for X7S users to get working BT

**Comment by ParkerEde** [comment]
This PR is assigned to milestone 2.9. Now it is only about the merge into the 2.9 branch.

**Comment by pfeerick** [comment]
I'm on a different device atm, but it has probably been cherry-picked, just not pushed.

**Pull request merged**
