### PR TITLE
fix(lua): handle ENTER_LONG properly

### LINKED ISSUE #2267: Long press roller doesn't bring menu on betaflight Lua script
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The betaflight Lua script long press menu doesn't appear on roller long  press on my tx16s. 

Latest nightly on tx16s
Latest nightly on Lua script 
3.0.0 RC2 

### Expected Behavior

 be hable to save and reboot from Lua script menu when roller long press 

### Steps To Reproduce

Enter betaflight Lua script 
Adjust pids with betaflight Lua script
Long Press roller does nothing (should appear menu) 

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #2267

### CODE REVIEW

**Comment by pfeerick** [comment]
Right, so this fixes the underlying issue of LONG_PRESS of ENT not working, but either reveals another issue, or causes a secondary one... Just to be clear from the onset, this is a change in behaviour from 2.7.1. 

So, at this screen, long press to get the save (send to BF) option...
image

Now that that pop-up appears, it should be a tap of ENT to save the settings, or a scroll to another opt and short ENT there also.. 
image

However, I need to press enter *twice* before it works as expected?

**Comment by raphaelcoeffic** [comment]
The first `ENTER` key press seems to be absorbed by the BF scripts on purpose:
https://github.com/betaflight/betaflight-tx-lua-scripts/blob/cdd9ec2bd77ca4828a8492ff39c21815e53d105c/src/SCRIPTS/BF/ui.lua#L267-L282

Special attention should be paid to `killEnterBreak` (seems to be there since my first implementation....).

So we should not prevent it as commented in the new code:
```
    // Do not use `lv_indev_wait_release()` as some LUA scripts
    // rely on EVT_KEY_BREAK(KEY_ENTER) being generated on key release
```

**Comment by raphaelcoeffic** [comment]
Tested with this script (used as `Tool` script in `/SCRIPTS/TOOLS/EventDemo.lua`):
```lua
local toolName = "TNS|EventDemo|TNE"
local lastEvent = 0
local eventTime = 0

-- String identifying events
local function evt2str(event)
  if event == EVT_VIRTUAL_PREV then return "EVT_VIRTUAL_PREV"
  elseif event == EVT_VIRTUAL_NEXT then return "EVT_VIRTUAL_NEXT"
  elseif event == EVT_VIRTUAL_DEC then return "EVT_VIRTUAL_DEC"
  elseif event == EVT_VIRTUAL_INC then return "EVT_VIRTUAL_INC"
  elseif event == EVT_VIRTUAL_PREV_PAGE then return "EVT_VIRTUAL_PREV_PAGE"
  elseif event == EVT_VIRTUAL_NEXT_PAGE then return "EVT_VIRTUAL_NEXT_PAGE"
  elseif event == EVT_VIRTUAL_MENU then return "EVT_VIRTUAL_MENU"
  elseif event == EVT_VIRTUAL_ENTER then return "EVT_VIRTUAL_ENTER"
  elseif event == EVT_VIRTUAL_MENU_LONG then return "EVT_VIRTUAL_MENU_LONG"
  elseif event == EVT_VIRTUAL_ENTER_LONG then return "EVT_VIRTUAL_ENTER_LONG"
  elseif event == EVT_VIRTUAL_EXIT then return "EVT_VIRTUAL_EXIT"
  else 
    local txt = string.format("Event = %i", event)
    return txt
  end
end

local function run(event)
  
  lcd.clear()

  if event ~= 0 then -- We got a new event
    -- Save the event for subsequent cycles and mark the time
    lastEvent = event
    eventTime = getTime()
  end

  -- Show the last event for 1 sec. in the upper left corner
  if getTime() - eventTime < 100 then
    lcd.drawText(3, 3, evt2str(lastEvent))
  end

  return 0
end

return {run = run}
```

**Comment by pfeerick** [comment]
lol... yeah, we probably have to keep what was previously buggy behaviour for now...

**Pull request merged**
