### PR TITLE
Fix building with -DGVARS=NO

### PR DESCRIPTION
**Pull request by rotorman**
PR in response to https://www.rcgroups.com/forums/showthread.php?3916381-Official-EdgeTX-Discussion-Thread/page101#post48295353

This PR needs testing.

### CODE REVIEW

**Comment by eshifri** [comment]
Doesn't this mean that without GVARS output limits are not editable?
Also, if memory serves me, these Edit functions are used in some other places.

**Comment by eshifri** [comment]
The real problem is here:
https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/colorlcd/gvar_numberedit.h#L33
GVarNumberEdit() has one extra parameter now (offset).

The quick (and rather dirty) fix is to call NumberEdit() instead of GVarNumberEdit() if GVARS are not defined.

**Comment by eshifri** [comment]
Actually, even easier: just put the last parameter into the #if defined bracket:


      new GVarNumberEdit(window, grid.getFieldSlot(), -limit, 0,
                         GET_SET_DEFAULT(output->min), 0, PREC1
#if defined(GVARS)
                         , -LIMIT_STD_MAX
#endif
                           );

**Comment by ducatiJake** [comment]
Hi Guys,
I'm using the instructions for building edge on Windows and using the following modified command to fetch the source.
git clone --recursive -b no_gvars_fix https://github.com/EdgeTX/edgetx.git edgetx_main

And the following command to build the firmware.bin file.
cmake -G "MSYS Makefiles"  -Wno-dev -DCMAKE_PREFIX_PATH=$HOME/5.12.9/mingw73_64 -DSDL_LIBRARY_PATH=/mingw64/bin/ -DPCB=X10 -DPCBREV=TX16S -DGVARS=NO -DDEFAULT_MODE=2 -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DCMAKE_BUILD_TYPE=Release ../

This is the same as I was using before which produced the compile errors I submitted on RCGroups.
With the above commands I no longer get a compile error and get a usable firmware.bin out the other end.
So, that works.  But... with the above, -DGVARS=NO I still see the Global Variables tab in the model editor.
I tried just not specifying -DGVARS=NO at all, same result.
I tried removing the -DCMAKE_BUILD_TYPE=Release for grins, same result.
I tried specifying -DGVARS=YES, thinking maybe some logic was reversed, same result.

I may be doing something wrong, been developing SW my whole life, but never used GitHub or built OpenTX or EdgeTX before so lots of new stuff for me and I could easily be doing something wrong.
I did successfully remove the GPS build option and got a firmware.bin that didn't have the GPS icon on the top row, so that worked correctly.

Good Luck, let me know if I can help further.
John Murphy

**Comment by pfeerick** [comment]
It just needs the GVARS tab hidden if GVARS are not enabled - I just added a commit with that ;)

**Comment by rotorman** [comment]
@ducatiJake update your local copy with:
Step 1: navigate to the edgetx_main folder where you checked out the no_gvars_fix branch
Step 2: issue `git pull`
Step 3: issue `git submodule update --init`
Step 4: navigate to the build-output directory and re-run the make (no need to re-run the cmake, if you do not want to update any option)
Please let us know how it goes for you. Thanks!

**Comment by ducatiJake** [comment]
Great instructions Risto, thanks.
All is good now, Global Variables tab is now hidden.  I will continue to check this out, but have found no other fallout,
Thanks again
John

**Comment by pfeerick** [comment]
I'm going to merge this as it is for now as it should only be UI issues that are present in non-standard builds, and this resolves all of them that I can see

**Pull request merged**
