### PR TITLE
Bluetooth Trainer Options in model_setup

### PR DESCRIPTION
**Pull request by dlktdr**
Added Bluetooth trainer options to models_setup.

Also requires a pull request on libopenui to get current selection from menu.

### CODE REVIEW

**Comment by rotorman** [comment]
Tested this PR, together with https://github.com/EdgeTX/libopenui/pull/17 and HeadTracker v2.04 (https://github.com/dlktdr/HeadTracker) on RadioMaster TX16S with FrSky CC2540 Bluetooth module.
The Bluetooth partner discovery finally works on EdgeTX - well done Cliff and thank you ;)

Irrespective of this PR, IMHO, the string showing not connected state could be changed to more commonly understandable "Not connected" instead of typical informatics "!Connected".

@raphaelcoeffic would you plz look into https://github.com/EdgeTX/libopenui/pull/17 and merge if deemed appropriate - thx!

**Comment by dlktdr** [comment]
We probably want to add a new Extra Translation string then. I'm guessing the !Connected was probably due to size constraints on the B/W models.

**Comment by pfeerick** [comment]
I think translation strings can be done contitionally, i.e. colour screen
vs b&w, so should be possible to have extended string if on colourLCD.

**Comment by raphaelcoeffic** [comment]
> Tested this PR, together with [EdgeTX/libopenui#17](https://github.com/EdgeTX/libopenui/pull/17) on RadioMaster TX16S with FrSky CC2540 Bluetooth module, built using following CMake line:
> 
> ```
> -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DFLYSKY_HALL_STICKS=YES -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DBLUETOOTH=YES
> ```
> 
> As a Bluetooth partner, I used the HeadTracker v2.04 (https://github.com/dlktdr/HeadTracker) (Arduino Nano 33 BLE Sense).
> The Bluetooth partner discovery & trainer functionality finally works on EdgeTX - well done Cliff and thank you ;)
> 
> Independent to this PR, IMHO, the string showing not connected state could be changed to more commonly understandable "Not connected" instead of present more programmer term "!Connected".
> 
> @raphaelcoeffic would you plz look into [EdgeTX/libopenui#17](https://github.com/EdgeTX/libopenui/pull/17) and merge if deemed appropriate - thx!

*done*

**Comment by rotorman** [comment]
@dlktdr Thank you for the update. The build test fails on GitHub yet for X10 and X12S and is thus yet a blocker for a merge to main branch - plz see the report under "Checks".

**Comment by dlktdr** [comment]
I've actually been working on an issue where if you switch from Master to Slave BT is still shows connected. Didn't realize it keeps adding my branches the pushes to this pull request. 
Still new to this... I'll see what issue is here soon. I'll remember not to push till then :)

**Comment by pfeerick** [comment]
> The build test fails on GitHub yet for X10 and X12S and is thus a blocker for a merge to main branch - plz see the report under "Checks".

The failures are due to the fact that the additions in the libopenui PR are not yet visible in the EdgeTX repo. This will remain the case until the repo is updated to point to a newer submodule version which includes that PRs changes (since it has now been merged into libopenui), and then this PR would also need rebasing so that it also can see the updated submodule pointer as everything is version/commit locked (for a reason).

**Comment by pfeerick** [comment]
> Didn't realize it keeps adding my branches pushes to this pull request.

A PR is basically just a request to merge your branch into another branch (in the same or a different repo)... so until said branch is merged, you can keep making changes. 

Ideally if you are working on a different area, you would then create a new 'topic' branch for the nex new thing you are working on.

**Comment by pfeerick** [comment]
If it helps, branches are points in time... I.e. branching from main two weeks ago means any subsequent changes to main or libopen or any other submodule don't exist, unless you rebase (move in time point branch occured) or merge (add changes) to import those changes.

**Comment by dlktdr** [comment]
Oops. don't think I did that right..

**Comment by pfeerick** [comment]
Welp... I think you can hard reset back `9fd7585` and force push back to that state, but you'd have to redo the three commits after that point...

**Comment by dlktdr** [comment]
Ok I see the libui update before my commits now.. think I got it :)

**Comment by pfeerick** [comment]
That fixed it ;)

**Comment by dlktdr** [comment]
Woot.. learned more a bit more about git and submodules today 👍

**Review by pfeerick — APPROVED** [review]
Right, I've run this on my TX16S (although I have no Bluetooth module) and even in that state it worked great - extra bits were all there - "Not Connected" showed up - buttons for init were shown and nothing crashed even though I enabled non-existent Bluetooth. :innocent:

@rotorman If you wouldn't mind testing this latest version of the PR out since you have hardware to test it with, I think this will be ready to merge.

**Comment by rotorman** [comment]
Tested on RM TX16S with FrSky BT CC2540 module, paired with HeadTracker (Arduino 33 BLE Sense).
First time connected as Trainer Master/Bluetooth - OK. Then just for fun changed to Slave/Bluetooth and then back to Master/Bluetooth and hit Discover again. Unfortunately got EM screen.

Then rebooted and set Master/Bluetooth and Discover again. This time, for fun did not select anything, but backed out with RTN. Dialog gets dismissed, but the radio UI locks up. RTN does nothing anymore, also Page buttons (only action I see is that the backlight turns bright again, when I press anything, but display content does not change).

Unfortunately I guess, this PR needs further checking/fixes. Sorry.

**Comment by pfeerick** [comment]
😢 Don't be sorry... that's less cranky users after us all with a 🗡️ !!

**Comment by rotorman** [comment]
Here a video demonstrating the UI lockup in another constellation:
https://www.youtube.com/watch?v=T4U1LSjW4d4

**Comment by dlktdr** [comment]
I will take a look! Thanks for video.

**Comment by dlktdr** [comment]
Getting stuck in a loop at back.focus->setFocus(SET_FOCUS_DEFAULT); in layer.h :( 

But not always.

Working
```
17.40s: # Layout2P1 refresh: Layout [0, 0, 480, 272]
17.90s: # Layout2P1 refresh: Layout [0, 0, 480, 272]
17.96s: MenuBody [0, 30, 200, 59] received event 0x604
17.96s: MenuBody [Window] [0, 30, 200, 59] received event 0x604
17.96s: MenuWindowContent [Window] [140, 111, 200, 89] received event 0x604
18.11s: MenuBody [0, 30, 200, 59] received event 0x204
18.11s: MenuBody [Window] [0, 30, 200, 59] received event 0x204
18.11s: MenuWindowContent [Window] [140, 111, 200, 89] received event 0x204
18.11s: Layer removed for Menu [0, 0, 480, 272] (1 layers)
18.11s:  - MainWindow [0, 0, 480, 272] (focus=Window [240, 44, 234, 20])
18.11s: Delete 0xd0267d48 Menu [0, 0, 480, 272]
18.11s: Delete 0xd026ae20 MenuBody [0, 30, 200, 59]
18.11s: Delete 0xd026ada0 MenuWindowContent [140, 111, 200, 89]
```
Crash

```
136.31s: # Layout2P1 refresh: Layout [0, 0, 480, 272]
136.81s: # Layout2P1 refresh: Layout [0, 0, 480, 272]
137.17s: MenuBody [0, 30, 200, 60] received event 0x604
137.17s: MenuBody [Window] [0, 30, 200, 60] received event 0x604
137.17s: MenuWindowContent [Window] [140, 111, 200, 90] received event 0x604
137.31s: # Layout2P1 refresh: Layout [0, 0, 480, 272]
137.37s:
```

Is there any other examples of a Popup Menu other than USB in the source somewhere I can follow?

**Comment by dlktdr** [comment]
Found the cause of the issue. If you get an event which cased a GUI update while a pop-up is open causes the hang. Added a check to make sure the pop-up isn't open when re-drawing.

I still need to add a check to make sure the Trainer Choice() Pop-up isn't open, because an update in here also causes the same issue.

**Comment by dlktdr** [comment]
@rotorman Can you re-check this. I'm happy with the result.

You can click around like crazy touch or buttons switch modes back forth and seems good

**Comment by rotorman** [comment]
@dlktdr I gave it some beating and it worked now flawlessly - no EM, no hanging UI. Awesome - thanks!
I noticed only a tiny optical issue - when Bluetooth is off on cold boot and it is first turned on, thus under SYSTEM -> Hardware e.g. to Trainer mode, then the local address is updated/shown first, when the page is closed and re-openend (e.g. changed with page > and page < back and forth).

**Comment by dlktdr** [comment]
Could you take a video of what you mean on this one?

I turn Bluetooth mode off (set under hardware to ---)
Reboot, 
Then set Bluetooth back to Trainer but the Local address doesn't show up until you pick a Bluetooth trainer mode?

**Comment by rotorman** [comment]
Luckily I did not see a crash, had it running for more than half an hour.

Here video of what I mean. Turn Bluetooth off, power down. Power up, turn BT on -> local address is not shown. Go Page> and then Page<, address shows up. By now turning BT off and back on (without cold start), the address is shown immediately when BT is turned back on.

https://www.youtube.com/watch?v=BVCbjBArDbw

**Comment by dlktdr** [comment]
Looks like it takes a second to initialize the Bluetooth module and the GUI isn't told to refresh until you change pages and go back.

I did the same thing as in models_setup. if the state changes it causes an update.

**Comment by dlktdr** [comment]
There we go.. 
I can't get it to EM in either models or radio anymore. BT address shows up after initially off too.

**Comment by rotorman** [comment]
Just tested the latest - the local addr. now pops up nicely, w/o having to change pages back and forth. Did not experience any issues by experimenting with TX16S. Nice work @dlktdr 

@pfeerick What do you say - can we merge this PR?

**Comment by pfeerick** [comment]
If you're happy with the current state, I'll give it another look and hopefully merge in the morning for the next nightly.

**Comment by pfeerick** [comment]
I applied autoformatting to the modified code, and also tweaked the spacer as it looks like the TX16S could also do with bottom spacer not just the NV14 - other than that from what I can see this works perfectly, and also doesn't do anything nasty to me if I am silly enough to enable Bluetooth Trainer on a non-BT equiped TX... which is always a plus ;)

**Comment by dlktdr** [comment]
Awesome! I'll remember to autoformat my changes next time!

**Comment by pfeerick** [comment]
Thanks ;) I'm only just starting to do it myself also, after a gentle prod from Raphael as he is stubborn enough to be using emacs on an 13" screen so doesn't like long lines 😁

**Pull request merged**
