### PR TITLE
Companion change model edit curves tab to list and add curve images to inputs, mixes and outputs

### PR DESCRIPTION
**Pull request by elecpower**
Summary of changes:
- rework model edit curves tab from compound edit widget to tabular list to better show configured and unconfigured curves
- curves tab row id has context sensitive menu on right mouse click and double clicking image opens edit dialog
- new curve edit dialog to facilitate editing from multiple places
- add curve image and double click to edit functionality to input edit, mix edit and outputs tab

Curves tab
curves_tab
Input dialog
input
Mix dialog
mix
Outputs tab
outputs_tab
Curve edit dialog
curve_edit

### CODE REVIEW

**Comment by pfeerick** [comment]
Dang, that looks really nice! :)

**Review by pfeerick — APPROVED** [review]
Looks to be working perfectly after reading and writing some curves for some of my old heli models. Will merge once github actions QT install cache is rebuilt as it has expired and is being a pain again. 

Food for thought - since you've now got ability to show the curve for custom curves in the mix edit dialog, it would be nice to be able to see expo and diff curves also maybe? If you like that idea, I can add an issue for it for later...

**Comment by elecpower** [comment]
> Food for thought - since you've now got ability to show the curve for custom curves in the mix edit dialog, it would be nice to be able to see expo and diff curves also maybe? If you like that idea, I can add an issue for it for later...

Yeah why not so raise an issue so its on the wish list. Adding expo and diff is the least of the challenge. The current implementation only draws straight lines between points which has been a deficiency that users have wanted fixed for some time. The trick is working out how to draw the curves in Qt. There are some examples out there and I do have the maths on the radio side. Something to keep me up at night.

**Comment by Eldenroot** [comment]
I think this is possible in Spektrum old radios - you can see everything in one chart, really useful (expo, d/r, curve etc).

**Comment by pfeerick** [comment]
Old and newer ones... the curve is shown at the side while editing mixes and such.

**Pull request merged**
