### PR TITLE
Improve gyro/acc range and config

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by rotorman** [comment]
Found ALPHA 0.98 relatively sluggish, with 0.99 and mixer gain set to 200% for the TiltX and TiltY, the control experience was nicer IMHO (tested with a 2-servo controlled ball maze and Adafruit LSM6DS33).

**Comment by raphaelcoeffic** [comment]
@pfeerick maybe short cleanup. I was actually hoping for some more tests, at least from *Team X12S*

**Comment by pfeerick** [comment]
As resident X12S guinea pig, @rburrow87 has 48 hours to test or forever hold peace :-P (unless a dr's note or other suitable excuse tendered). /jk ... or am I? 😈

**Comment by rburrow87** [comment]
I didn't even realize there was a gyro in the X12S 😂

It only showed either +100 or -100 in the nightly, but with this PR, 0 to +/-100 takes rotating it 90 degrees one way or the other which seems right to me! No idea what to do with this newly found feature 😛

**Comment by gagarinlg** [comment]
> I didn't even realize there was a gyro in the X12S 😂
> 
> It only showed either +100 or -100 in the nightly, but with this PR, 0 to +/-100 takes rotating it 90 degrees one way or the other which seems right to me! No idea what to do with this newly found feature 😛

Control aileron and elevator?

**Comment by rburrow87** [comment]
Sure, let me borrow your plane!

**Comment by gagarinlg** [comment]
Sure
Saturday, Saarmund?

**Comment by pfeerick** [comment]
> I didn't even realize there was a gyro in the X12S 😂
> 
> It only showed either +100 or -100 in the nightly, but with this PR, 0 to +/-100 takes rotating it 90 degrees one way or the other which seems right to me! No idea what to do with this newly found feature 😛

Much appreciated @rburrow87. And yes, I think finding a use could be interesting, but at least it works. I know a friend of Raphael used this capability for one-handed control in the OTX days (so had a hand free for a beer?) so certainly a possibility (maybe use a switxh to change from stick to acc/tilt control?). I suppose backlight state would be another nice opt - i.e. Pick up the radio and the movement is enough to bring the backlight back up.

**Pull request merged**
