### PR TITLE
feat(ui): adds explicit "Travel" string

### PR DESCRIPTION
**Pull request by rotorman**
Changes "Weight" to "Travel" on model input page.
Follows a suggestion from: https://www.rcgroups.com/forums/showpost.php?p=50993435&postcount=15625

grafik

Keeps string "Weight" for the heli and std. mixers page.

Translators - could you please check if rewording for the model input page might make sense also in other languages than English - thanks!

- [ ] @zyren CN / TW
- [x] @Eldenroot CZ
- [ ] @HThuren DA
- [x] @ParkerEde DE
- [x] @Pat6874 FR
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [x] @ajjjjjjjj PL
- [ ] @ulfhedlund SE

### CODE REVIEW

**Comment by Eldenroot** [comment]
CZ: I think the best is "Pohyb"

**Comment by 3djc** [comment]
Sorry but it makes no sense. How is travel better when source is a gv ? An ls ? A telemetry item ?

**Comment by ParkerEde** [comment]
DE: done by rotorman

**Comment by 3djc** [comment]
They say that because they have used edgetx the way they use their spektrum and never made any other input than the 2 sticks and maybe (but unlikely) pots or sliders. There is soo much more to it...

https://www.statisticshowto.com/weighting-factor/#:~:text=A%20statistical%20weight%20is%20an,of%20an%20in%2Dclass%20test.

**Comment by jtaylor2** [comment]
Because two people on RC Groups say something, you want to change wording that tens of thousands of people understand and  have been using for over ten years?  Not to mention obsoleting every document and video that currently exist.  Makes no sense to me.

In my opinion better two new users be confused than the thousands of current users.

**Comment by mha1** [comment]
please don't

**Comment by rotorman** [comment]
OK, I hear you, closing then.

**Comment by pfeerick** [comment]
> At least two English native speakers at RCGroups say that "weight" does not work there and "travel" does

Not to beat a dead horse, but as a native English speaker, with some knowledge of electrical and engineering terms, weight is the correct term to use. Weight is the *strength* of the input, not the amount it moves. That parameter also doesn't necessarily the travel, since it is weight in conjunction with offset. Travel might be something you would see in the outputs page. 

But it is always good to discuss these things, and see if it makes sense to change them. In this case though, it doesn't.

**Pull request closed without merging**
