### PR TITLE
Highlite active inputs and mixies (#337). Take 2.

### PR DESCRIPTION
**Pull request by eshifri**

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@eshifri much better, thx!

**Comment by raphaelcoeffic** [comment]
@JimB40 is this your intended way?

**Comment by JimB40** [comment]
How can I check it? Which binary?

**Comment by pfeerick** [comment]
You'll have to let me know your preference so I can tell you the right one in future ;)

1) In Flasher, you're after
image

2) Via github (sometimes the quickest if you just want the file to do a bootloader flash):
First go into the checks tab ... 
image

... and then once you're there, you can get the zip file via the artifacts menu at 1. The quickest place to get the latest  commit id you need in the flasher is at 2, since it looks like it now shows the commit id from the pull requests, rather than the merge commit ids!!!! 
image

**Comment by JimB40** [comment]
Mimic OTX 2.3.13 behaviour 100%
Bit to shiny as all mixes will be always active, but for 2.4.0 is okay.
Good job. To be closed.

**Comment by pfeerick** [comment]
Many thanks for this @eshifri ... I just tried this as it's in the latest nightly... and it worked perfectly. I have a couple of models with four input lines per 'channel' and I can now see which one is the active one as I change the mode switches. :+1:

**Pull request merged**
