### PR TITLE
feat: SPI flash driver

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- New wear levelling driver
- New SPI flash driver

On behalf of @richardclli 😋

### CODE REVIEW

**Comment by richardclli** [comment]
I worked out your TODO, reimplement LRU Page Buffer with linked list and hash table.   Pushed the limit to 256MB flash.  Fixed some problems as well.

**Comment by raphaelcoeffic** [comment]
@richardclli I'll have a look ASAP.

**Comment by raphaelcoeffic** [comment]
@richardclli PR is your, let me know how that works you!

**Comment by raphaelcoeffic** [comment]
> I think I do not have any amendments to the FrFTL, everything is good, parameters are well balanced, it should be good to use now.

@richardclli Cool! Let's poke @pfeerick to check this does not break anything for others, then let's merge.

**Comment by richardclli** [comment]
Current parameters keep FTL overhead only around 2% of flash size, and RAM usage up to around 256KB max.  I have done an extensive test case using FatFS library and EdgeTX SD card image and did 10000 rounds random delete and copy replace without any integrity problem.

**Comment by richardclli** [comment]
@raphaelcoeffic Just remember one parameter that may need to check, not sure where it is.  All operations in the FTL is quite fast except the ftlSync.  As the current parameters limited the no. of PageBuffer to 64 max.  Which means the worse case the ftlSync needs to flush 64 pages back to flash.  I think we may need to estimate the timing and ensure that the watchdog timer will not trigger, or we add some code to reset the watchdog timer during ftlSync.

**Comment by richardclli** [comment]
The watchdog looks good, I tried to copy a very large file (around 40MB) via USB and do not have any problem.  I once have a problem in fs_pl18-2.9 branch that the watchdog will trigger when copying a large file.

**Comment by richardclli** [comment]
@pfeerick So finally need you to see if it will breaks anything.

**Comment by pfeerick** [comment]
I'll look at this one next (tonight), and then go back to the currently queued PRs, so you can continue on with the PL18.

**Comment by richardclli** [comment]
By changing build options, you can flash EL18 and/or TX16S to use internal NOR flash instead of SD card as well, have fun.

**Comment by pfeerick** [comment]
I've kicked the tyres a bit on X9D+2019, TX16S (with and without `STORAGE_USE_SPI_FLASH` enabled) and also EL18. Everything seems to be working AFAICT. Over to the nightly users to break it ;)

**Pull request merged**
