### PR TITLE
Fix Lua Mixer index issue

### PR DESCRIPTION
**Pull request by jfrickmann**
Fixed a dumb bug where I used the wrong index

### CODE REVIEW

**Comment by wimalopaan** [comment]
The test script of the issue now works, but this one still doesn't (it is as useless as the other because it stems from a real script, but now is stripped down):

```
local input = {
   {"Input", SOURCE},
   {"Reset", SOURCE},
   {"Scale", VALUE, 0, 100, 10},
   {"Deadb", VALUE, 0, 100, 2}
};

local output = {
   "Incremental"
};

local value = 0;

local function run(inp, reset, scale, deadband)
   if (reset) and (reset > 0) then
      value = 0;
   end
   return value;
end

return {
   input = input,
   output = output,
   run = run
};

```
To reproduce just insert a new model and choose this one as the first mixser script. The radio immediately crashes.

In simulator27 this kind of works, but with the following observation (both for this script as well as for the test script from the isseu): if one inserts thos or the other script the inputs/outputs are not immediately visible (on radio they are for the other scripz from the issue since it simply doesn't crash). One has to leave the script dialog and reenter it: then the inputs and outputs are visible. I think this observation shows that there are some other problems.

**Comment by wimalopaan** [comment]
Just make another test: made a EN version of the very same firmware: no crash.

Looks like there is a translation problem, maybe with the german umlauts ...

**Comment by wimalopaan** [comment]
This is the `cmake` line to generate a fw that crashes the radio if the above script is used:

`cmake -DUSB_SERIAL=Off -DTRANSLATIONS=DE -DPCB=X10 -DPCBREV=TX16S -DLUA=YES -DLUA_MIXER=YES -DGVARS=YES -DINTERNAL_MODULES="MULTI"  ..`

**Comment by pfeerick** [comment]
> the inputs/outputs are not immediately visible (on radio they are)

It's funny you mention this... as I thought the opposite had always the been the case until now... that on the radio you needed to reload the page before it showed the inputs outputs - probably because it simply isn't refreshed after selecting which mixer script to load into that "slot".

**Comment by jfrickmann** [comment]
> Just make another test: made a EN version of the very same firmware: no crash.
> 
> Looks like there is a translation problem, maybe with the german umlauts ...

That's Über strange 🙂! Sorry 🙄

**Comment by wimalopaan** [comment]
Well, I hope you can reproduce that ... and then hopefully fix the bug. There have been spurious crashes with mixer-scripts since ever. But the actual situation renders it as unusual, sadly.

**Comment by jfrickmann** [comment]
Unfortunately, no luck so far. I just built companion27 with TRANSLATION=DE, und kein Zusammenbruch hier!

**Comment by jfrickmann** [comment]
What version are you on?

**Comment by wimalopaan** [comment]
I recreated once again.

I did:
```
git fetch origin pull/1312/head:mixermess
git checkout mixermess
```
Then i built with the cmake line above with DE. On radio there is an immediate crash. 

`simulator27` (stand-alone) does not crash  but does not display the script inputs/outs on the first time as mentioned.

```
$ strings jf_mm_de.bin | head
BOOT10edgetx-tx16s-2.7.0 (9b1489ee)
```
Then I built the EN version that also crashes immediately inserting the above script ...

I attach both versions:

[fw.tar.gz](https://github.com/EdgeTX/edgetx/files/7789382/fw.tar.gz)

**Comment by jfrickmann** [comment]
I cannot use binary files for anything. Please submit the source code, if you want me to look into it!

**Comment by wimalopaan** [comment]
> I cannot use binary files for anything. Please submit the source code, if you want me to look into it!

I had the hope that you can use the bin-files just to see the phenomenom.

> What version are you on?

Well, as I described above I just used the source code of this PR - no modifications.

If you have any suggestions that I can do to resolve this issue please let me know.

**Comment by wimalopaan** [comment]
Ok, I think I got it: if the name of the script is 6 +3 chars long, then it either freezes or crashes the radio. If names are 5 + 3 chars or shorter, all scripts run well.

**Comment by pfeerick** [comment]
Ok, so we just need to cap the field length for now, as that sounds like an old limit that the new gui isn't protecting against.

**Comment by wimalopaan** [comment]
The next problem that still remains is that the radio freezes / crashes if you use the fourth instance of this script:

[abcd.zip](https://github.com/EdgeTX/edgetx/files/7791777/abcd.zip)

This is a little bit more computational intense than the other.

**Comment by pfeerick** [comment]
Ok, so lets fix the first two problems, and then worry about that one next 😁

**Comment by wimalopaan** [comment]
> The next problem that still remains is that the radio freezes / crashes if you use the fourth instance of this script:
> 
> [abcd.zip](https://github.com/EdgeTX/edgetx/files/7791777/abcd.zip)
> 
> This is a little bit more computational intense than the other.

Maybe it helps to identify this one: the first three instances are not saved in the model. After crash and restart the model does not contain the first three instances of the script. This is reproducible.

**Pull request merged**
