### PR TITLE
Update T18 gt911 configuration

### PR DESCRIPTION
**Pull request by norulers**

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Thx! I’lol test this evening!

**Comment by raphaelcoeffic** [comment]
@norulers are you sure this is correct? It is the same behaviour as before here: coordinates are inverted, and only the upper half of the screen is covered.

**Comment by norulers** [comment]
It is possible that the touch controller has not updated the new configuration，Touch controller manual indicates that the version number will be updated only when it is greater than or equal to the current version number。I'll test it！

**Comment by norulers** [comment]
The configuration file is correct，I changed 0x3d to 0xff, the screen updated the correct definition, but I can't go back to the previous wrong configuration

`0x3D,0xE0,0x01,0x10,0x01,0x05,0x0C,0x00,0x01,0x18,0x28,0x0F,0x50,0x3C,0x03,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x04,0x18,0x1A,0x1E,0x14,0x87,0x29,0x0A,0x4B,0x4D,0xD3,0x07,0x00,0x00,0x00,0x19,0x02,0x10,0x32,0x00,0x00,0x00,0x00,0x03,0x00,0x00,0x00,0x00,0x00,0x32,0x73,0x94,0xD5,0x02,0x07,0x00,0x00,0x04,0xAE,0x36,0x00,0x94,0x40,0x00,0x7E,0x4C,0x00,0x6D,0x59,0x00,0x5D,0x6A,0x00,0x5D,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x0A,0x0C,0x0E,0x10,0x12,0x14,0x16,0x18,0x1A,0x1C,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x00,0x02,0x04,0x06,0x08,0x0A,0x0C,0x1D,0x1E,0x1F,0x20,0x21,0x22,0x24,0x26,0x28,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x78,0x01`

**Comment by raphaelcoeffic** [comment]
@norules ok, I'll check again. It seems OTX has a PR running for this as well: opentx/opentx#8552

**Comment by raphaelcoeffic** [comment]
@norulers Thx! This works much better! I have your commits cherry-picked on top of my locally rebased PR. I will just push this and merge.

**Comment by raphaelcoeffic** [comment]
@norulers your changes have been merged together with the other PR. It should be fine now :-)

**Pull request closed without merging**
