### PR TITLE
CPN: user configurable audio mute in radio settings. Supports PR #3703

### PR DESCRIPTION
**Pull request by mha1**
Adds user configurable audio mute in CPN's radio setting. Supports PR #3703

### CODE REVIEW

**Comment by mha1** [comment]
Updated to make checkbox only visible for radios with AUDIO_MUTE_GPIO pin (see target/hal.h files):
 - All color lcd radios (including NV14) except Horus X12S
 - TX12, TX12MK2, ZORRO, BOXER, T8, TLITE, TPRO, LR3PRO, COMMANDO8

**Comment by pfeerick** [comment]
@elecpower Can you give this a glance over, and let me know if you're happy with it? I'll give the combined two PRs a try tomorrow.

**Comment by elecpower** [comment]
@pfeerick looks okay

**Review by pfeerick — APPROVED** [review]
LGTM and has Neil's blessing also ;) Will merge after #3703

**Pull request merged**
