### PR TITLE
chore(cpn): upgrade miniz to version 3.0.2

### PR DESCRIPTION
**Pull request by elecpower**
Fetch miniz v3.0.2 from its repo via cmake and remove our copy.
Remove double include of header.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@elecpower Maybe we should start avoiding to have library source code in our repo and use either submodules or CMake `FetchContent` as demonstrated in 54ed94e2615dff98b9ee1346689012b118765477.

**Comment by elecpower** [comment]
> @elecpower Maybe we should start avoiding to have library source code in our repo and use either submodules or CMake `FetchContent` as demonstrated in [54ed94e](https://github.com/EdgeTX/edgetx/commit/54ed94e2615dff98b9ee1346689012b118765477).

I was just following those who came before. Maybe there was a reason to copy the code when first hooked in. The Fetch maybe simpler than submodule on first glance

**Comment by raphaelcoeffic** [comment]
> The Fetch maybe simpler than submodule on first glance

With a little twist:
- `FetchContent` will fetch the code only for native targets, so that firmware build won't download anything.
- submodules are fetched during checkout phase, which would happen for firmware builds as well.

Now that we have Cloudbuild, I'm trying to reduce what is fetched on build for firmwares, so that I would love to prevent fetching code parts used by Companion when building firmwares. Fetching submodule on demand is a huge pain and has no native support in CMake.

**Comment by elecpower** [comment]
@raphaelcoeffic  I've merged your branch

**Pull request merged**
