### PR TITLE
Fix switch warnings

### LINKED ISSUE #1036: Preflight Checklist Switch Positions are not saved
On the model setup page under section "Preflight Checklist" you can select which switches should be checked by the radio.
Also the switch positions can be saved, but this is not happening.

**To Reproduce**
-Set switches to desired positions
-Go to Model Setup
-Scroll to the Switch Positions and activate the item (click the wheel).
-Scroll left to select all switches and click again.
-The arrows next to the switches now reflect the current positions of each.
-Exit the menu
-Load another model from Model List (or reboot radio)
-Go back to the model where you did the change.
-Check the preflight checklist switch postions - they are reset back to default.

**Expected behavior**
The switch positions should be saved to the model and retained on model change or reboot.

**Screenshots**
screen-2021-11-12-141613

**General information**
 - nightly b4903d8
 - Frsky X9D+ 2019 (Access Version)

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #1036 

Summary of changes:
- removed MENUS_LOCK (legacy)
- unified switch warn states to be the same on all targets
- fixed conversions from 2.3/2.4

### CODE REVIEW

**Comment by pfeerick** [comment]
PR breaker, reporting for duty! 😜 

Test subjects are X9D+2019 (yes, it's back)... and TX12. 

For both:
- improved behaviour considerably in settings - now shows up, middle and down options/symbols for switches rather than just toggling 'b' (TX12) or showing up arrow (X9D+2019)
- auto-detection (press and hold whilst switches are were you want them) works
- appears to be correctly saving and restoring
- is only showing switches, not buttons or momentary toggles.

X9D+2019:
- There seems to be a 'ghost' entry in the switch list... there is one more position that does not seem to do anything when manually setting the switch positions... this is not new behaviour - it was present in 2.5.0 (used for baseline testing), and also seems present in OTX (Companion simulator) ... I thought perhaps there was one switch too many, but Companion and radio both show up to G
- On startup, warning screen is showing wrong letters/symbols for some switch positions... i.e. SBh instead of SB-, SCv instead of SC-, SDv instead of SDup, etc. 

Later I'll try conversion and colourlcd just to be complete ;)

**Comment by pfeerick** [comment]
TX16S - switch warnings working, however when a switch is in the correct position, it is still shown on the startup warnings screen - i.e. it does not 'auto-clear' when it is moved into the correct position.

TX12 & X9D+2019 - Switch warnings do work however, switch positions displays are still wrong. Switches auto-clear when moved to correct position. X9D+2019 still seems to have one more entry in the list than it should. Auto switch position detection (press and hold ENT on field) is not working. 

image
image
image
image

**Comment by PSi86** [comment]
If something needs testing with the x9d+ 2019, just ping me.

**Comment by raphaelcoeffic** [comment]
Switch warnings should be behaving properly now 🙂
- Please note that the switch warnings, if not set to "empty" for a particular switch, will update according to their current state when `[ENTER LONG]` is pressed.
- The only question that is left is: should the warnings be setup to "all up" in a new model?

**Comment by pfeerick** [comment]
To me, the current behaviour seems to be more once they have been sent *once*, a long ENT on the group (on B&W) will auto-set switch positions. But not before. 

On TX12S, other than that, this seems to work perfectly. Correct indicators are being shown, not garbled characters :)

On X9D+2019, similar improved behaviour, still seems to have one more switch option than valid but can live with that for now.

On TX16S, no garbled characters, no "long ent" switch position auto-detection (#1229) but I consider that out of scope of this PR. 

re: default warning state, I vote no warning state by default - as unlike other transmitter firmware, we don't assign switches to channels by default, so don't care about the switch position until we do.

**Review by pfeerick — APPROVED** [review]
My complaint for X9D+2019 still stands re: apparent ghost entry but that is minor. Auto switch position detection does not work on press and hold *if the switch positions are blank* (i.e. not set to a position already) for X9D+2019 and TX12 but that can be worked on separately as a followup as it is more important that the right symbols are being shown, etc!

**Comment by raphaelcoeffic** [comment]
> My complaint for X9D+2019 still stands re: apparent ghost switch entry at the end but that is minor. Auto switch position detection does not work on press and hold *if the switch positions are blank* (i.e. not set to a position already) for X9D+2019 and TX12 but that can be worked on separately as a followup as it is more important that the right symbols are being shown, etc!

In fact, I see this as an asset: it will only fill the enabled warnings. Otherwise you end up disabling all the switches for which you wish no warnings.

**Pull request merged**
