### PR TITLE
feat(color) - New switch choice dialog

### LINKED ISSUE #1538: Global Functions inverted Switches
**General information**
 - EdgeTX version 2.6.0 338d4d2
 - Hardware Eachine (Radiomaster) TX16S

when you want to setup a global Fuction and Filter the list by Switches you only can select "positive" Switchevents
if you want to select an inverted switch you must deselect the Filter.

Switches Filtered 
switch_filter

no Filter selected
inverted_switches

### LINKED ISSUE #3106: "!" entries missing when using PgUp/Dn to preselect switchgroup
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If I am in a switch selection, e.g. in the special functions, and select a group there with the PgUp/Dn key, I have no possibility to select the entries with the "!"

before using PgUp/Dn:
screenshot_x10express_23-01-25_11-02-00

after using PgUp/Dn:
screenshot_x10express_23-01-25_11-04-08

### Expected Behavior

with PgDn/Up preselection, the "!" entries should also be selectable.

### Steps To Reproduce

1. open special function
2. edit an SF
3. Enter switch selection
4. Press PgDn/Up button to preselct a switchgroup
5. try to select !SA- or any else "!" entry

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

all versions

### PR DESCRIPTION
**Pull request by philmoz**
I've always found the switch choice popup difficult to use and prone to error (accidentally selecting a value when scrolling with the touch screen).

Here is a revised switch choice dialog for consideration.

I've tried to make it both touch and button/scrollwheel friendly as well as more intuitive to use.

Resolves #1538,  and resolves #3106 

Some screenshots:
Screen Shot 2023-04-13 at 4 44 25 pm
Screen Shot 2023-04-13 at 4 44 39 pm
Screen Shot 2023-04-13 at 4 45 02 pm
Screen Shot 2023-04-13 at 4 45 56 pm

### CODE REVIEW

**Comment by philmoz** [comment]
Notes on the UI:
- The '!' button selects 'inverted' switches.
- The '---' button clears the selected value.
- 'Cancel' aborts any changes.
- 'Save' updates the caller with the new value and closes the dialog.
- The 'RTN' button is equivalent to 'Cancel'.
- The buttons on the left side filter the list (as with the current implementation).
- The 'PAGE DN' button cycles through the filter options (as with the current implementation).
- The 'PAGE UP' button cycles through the action buttons at the bottom (starting with 'Save').
- Tapping on the current selected switch (on screen) saves the value and closes the dialog.
- A long press of the Enter button saves the current selected value and closes the dialog.

**Review by froqstar — COMMENTED** [review]
What about the "ON" switch that is always on, would that special case still fit next to `!` and `---`?

**Comment by philmoz** [comment]
> What about the "ON" switch that is always on, would that special case still fit next to `!` and `---`?

Thanks for that. Updated to include the 'ON' switch and added a separate section for this, 'TELE' and 'ACT'.

Screen Shot 2023-04-14 at 8 25 37 pm

**Comment by Eldenroot** [comment]
Cool! There are some.opened tickets related to this page. Could you please check?

**Comment by philmoz** [comment]
This PR should address issues #1538 and #3016

**Comment by JimB40** [comment]
There is already #3286 for filtered list styling

**Comment by philmoz** [comment]
The problem with not using Save/Cancel on popups is that it is too easy to accidentally select while scrolling when using the touch screen.

**Comment by JimB40** [comment]
With all respect to your good work I have to mention that this PR is not considering upcoming features like givin desctiptive labels do different sources categories like LS, GV, SF (ie. https://github.com/EdgeTX/edgetx/pull/2219)

With existing scrollable list, it will be pretty straight forward to implement those labels
 
Popup List

While proposed layout will 
- make it harder to implement
- limit number of label lenght as UI items are placed horizontally one by one
etc.

Plus there will be two different pop-up layouts for pretty same task which is source selection (sometimes including switches)
screen-2023-06-28-123627

Anyway I flashed artifact
This stange list of LS appeared
screen-2023-06-28-123700
and radio went into EM
IMG_0385

**Comment by raphaelcoeffic** [comment]
Switching the "Draft" as this is still being discussed. @JimB40 is this where we're heading?

**Comment by philmoz** [comment]
Closing, replaced with #4104

**Pull request closed without merging**
