### PR TITLE
Companion Build for Win32

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Let's see whether or not we can get this to work for 32-bit as well.

### CODE REVIEW

**Comment by pfeerick** [comment]
It would be interesting, but I would also be somewhat concerned about how old a computer someone is running to need my laptop from 2005 which wasn't anything flash was 64bit... have to go back about another five years for another one I have before hitting the 32bit/i686 barrier (which even most Linux distros has given up support for 😢)...

**Comment by jtaylor2** [comment]
Actually the asus t100ta that I use at the flying field is running 32 bit Windows 10.  It was released in 2015 with 32 bit Windows 8.1 and upgraded with the free Windows 10 upgrade to 32 bit Windows 10

**Comment by raphaelcoeffic** [comment]
> It would be interesting, but I would also be somewhat concerned about how old a computer someone is running to need it... 😆 My laptop from 2005 which wasn't anything flash was 64bit... have to go back about another five years for another one I have before hitting the 32bit/i686 barrier (which even most Linux distros has given up support for 😢)...

So, should we choose to support 32bit windows, or just say: we’re edge, aren’t we???

**Comment by raphaelcoeffic** [comment]
The verdict is crystal-clear:
Screenshot 2021-09-12 at 16 14 01

**Comment by pfeerick** [comment]
> Actually the asus t100ta that I use at the flying field is running 32 bit Windows 10. It was released in 2015 with 32 bit Windows 8.1 and upgraded with the free Windows 10 upgrade to 32 bit Windows 10
> https://www.asus.com/me-en/Commercial-Laptops/asus_transformer_book_t100ta

Well, that just sucks, doesn't it... I had the 2011 ASUS TF101 (RIP) and thought it was an excellent tablet and design - especially loved the mechanically latched keyboard and auxiliary battery in the keyboard... but to then to an do a 32bit tablet in 2015... Asus have rocks in their heads! Anyway, we can see it looks like 32bit will build, and will most likely run on Windows 7, 8.1 and Windows 10, judging from the QT5.12 supported OS list. 

I've just run up a 32bit Windows 7 VM to try this out, since it did build, and the binary is still available for now ... and it looks like it does work - it installed fine, Companion started up, and I was able to go through the various dialogs and stuff, so might be worth grabbing it form the checks tab if you need it ;) Because it's from before the debug symbols were stripped from the files it will unfortunately be a big install, but it's at least an option.

**Comment by jtaylor2** [comment]
The ASUS t100 itself is 64 bit, but the memory and ssd are hardwired  and can't be upgraded so it doesn't have enough to run 64 bit Windows.  Dropping 32 bit is no real problem for me as I have 2 other laptops and only use it at the field to upgrade other peoples equipment.  Used the ASUS because it was little, and I didn't care if it got broke or fuel spilled on it.

I was just pointing out that there are people still using 32bit.  I have been compiling openTX (and now edgeTX also) for 10 years.  I compile on openSUSE 15.3 every day and on Windows 10 once a week using vs19 or mingw so compiling my own for the T100 won't be a problem if I really want to keep using it.

**Comment by raphaelcoeffic** [comment]
> The ASUS t100 itself is 64 bit, but the memory and ssd are hardwired and can't be upgraded so it doesn't have enough to run 64 bit Windows. Dropping 32 bit is no real problem for me as I have 2 other laptops and only use it at the field to upgrade other peoples equipment. Used the ASUS because it was little, and I didn't care if it got broke or fuel spilled on it.
> 
> I was just pointing out that there are people still using 32bit. I have been compiling openTX (and now edgeTX also) for 10 years. I compile on openSUSE 15.3 every day and on Windows 10 once a week using vs19 or mingw so compiling my own for the T100 won't be a problem if I really want to keep using it.

Using @rotorman's HowTo, this is only about replacing `MINGW64` with `MINGW32`. For the packages, all you need is to replace `x86_64` by `i686` in the names.

**Pull request closed without merging**
