### PR TITLE
fix(el18): Audio output should be OFF if no audio playing

### LINKED ISSUE #3669: EL18: Audio output should be switched off when no sound is playing
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Audio is remain on all the time.

### Expected Behavior

Audio should switch off when nothing is playing.

### Steps To Reproduce

1. Install ELRS ext module
2. Use 2W output
3. Hissle sounds maybe heard in the speaker

### Version

2.8.4

### Transmitter

Flysky EL18, Flysky NV14

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #3669

Summary of changes:

### CODE REVIEW

**Comment by pfeerick** [comment]
Doesn't seem to take into account "Play Sound" SF audio. i.e. put a repeating beep on a switch... now you won't hear it, but if you get a play-track to run at the same time you will sometimes here the beep since it's in the audio queue.

**Comment by richardclli** [comment]
> Doesn't seem to take into account "Play Sound" SF audio. i.e. put a repeating beep on a switch... now you won't hear it, but if you get a play-track to run at the same time you will sometimes here the beep since it's in the audio queue.

Umm...... interesting, didn't beeping is somewhat mixed with wave playing during output?  Did I missed anything?

**Comment by richardclli** [comment]
https://github.com/EdgeTX/edgetx/blob/main/radio/src/audio.cpp#L733-L812

Seems everything mixed here in the audio buffer before playing.  Did SF

**Comment by richardclli** [comment]
Just found that dac driver has.mute implementation.  Let me use similar constructs and see if it works.  It has more delays.

**Review by pfeerick — APPROVED** [review]
LGTM, and `Play sound` SF working as expected again.

**Pull request merged**
