### PR TITLE
fix(cpn): T-Pro function switches

### LINKED ISSUE #4898: companion v2.10-rc3 loses switch settings from v2.9.2 file
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

when I load a .etx file from v2.9.2 companion into v2.10-rc3 some of my switches above the screen are lost.
see my first model (bee) Special function SF10 and SF11 - the Switch is missing in 2.10-RC3 and it's listed as TML which is the first button/switch above the screen on my t-pro
both are configured  for the t-pro (v1)

here's the .etx file that I renamed to .zip so I can attach it.
[t-pro.zip](https://github.com/EdgeTX/edgetx/files/15045046/t-pro.zip)

### Expected Behavior

loding the v2.9.2 file into v2.10-rc3 should preserve all my settings.

it was [this thread](https://discord.com/channels/839849772864503828/1051165136473313290/threads/1230955556311797760) on discord that led me here.

### Steps To Reproduce

load attached file into v2.10 rc 3 companion
see how switches don't work.

### Version

Other (Please specify below)

### Transmitter

Jumper T-Pro

### Operating System (OS)

macOS

### OS Version

Sonoma

### Anything else?

this might be in the core edgeTX and not just companion since I just plugged my v2.9.2 jumper t-pro v1 sd card into my jumpter t-pro v2 running 2.10-rc3 and the buttons stopped working there too with no companion involved either.

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #4898

Note: I have not tested on hardware or simulator

### CODE REVIEW

**Comment by 3djc** [comment]
No no no, the customisable (function) switches name need to be displayed as SWx for end users, on radio too (and always have been, sorry if I have been unclear).

The issue with 'alias' names is only those where used in yaml before 2.10

**Comment by elecpower** [comment]
So the only change needs to be in yaml_rawswitch.cpp decode to map SE -> SW1 thru SJ - SW6 for T-Pro radios only. The encode yaml is SW1 thru SW6. Correct?

**Comment by 3djc** [comment]
In 2.9, customisable switches are displayed SW1 to SW6 on radio, and encoded SE to SJ for TPro
In 2.10, customisable switches are displayed SW1 to SW6 on radio, and encoded SW1 to SW6 for TPro

I belive TPro was the only radio with customosable switches in 2.9

**Comment by elecpower** [comment]
@3djc hopefully I have got it right this time

**Comment by 3djc** [comment]
2.9.4:
`customFn: 
   0:
      swtch: "SE2"
      func: OVERRIDE_CHANNEL
      def: "0,0,0"
   1:
      swtch: "SJ2"
      func: OVERRIDE_CHANNEL
      def: "0,0,0"`

Opening in 2.10 companion (this PR)
Read perfectly:
image


Save to radio:
customFn:
  0:
    swtch: SW12
    func: OVERRIDE_CHANNEL
    def: 0,0,0
  1:
    swtch: SW62
    func: OVERRIDE_CHANNEL
    def: 0,0,0

Open with 2.10rc3
image


PERFECT !

**Review by 3djc — APPROVED** [review]

**Comment by arkarkark** [comment]
This isn't going to conflict with the t-pro v2 having extra switches between the triggers and the pots which it calls SE and SF, right? the v1 t-pro doesn't have these switches.

**Comment by pfeerick** [comment]
It shouldn't no. The TPro V1 actually *does* have those switches, but they default to `None` as they are very hard trigger on the V1 (the trim caps go in too far making it hard to press).

**Comment by pfeerick** [comment]
A read/write cycle is working fine here on TPro V1 hardware also on Windows with a more elaborate setup. No customisable switches were harmed 🤭 

image

image

**Review by pfeerick — APPROVED** [review]
A read/write cycle is working fine here on TPro V1 hardware also on Windows with a more elaborate setup. No customisable switches were harmed 🤭 

image

image

**Pull request merged**
