### PR TITLE
chore: formatting of telemetry structs for readability

### PR DESCRIPTION
**Pull request by HThuren**
Just improve reading of telemetry struct and secure formatting
Helpful when making documentation elsewhere

### CODE REVIEW

**Comment by pfeerick** [comment]
If you're changing this from the `clang-format` autoformatted structure, you'll need to wrap the block in 
```
// clang-format off

// manually formatted code goes here

// clang-format on
```

otherwise it will be reverted the next time this file is edited ;)

**Comment by HThuren** [comment]
@pfeerick very good service information, thank you :-)

**Comment by HThuren** [comment]
.. seems to the build for el18 never pass line 49 -- CMAKE_BUILD_TYPE: Debug
same for the cancled x12s and x9lite

**Comment by pfeerick** [comment]
Appears to be an issue on GitHubs side that is supposed to be fixed on
Friday - i.e. next linux GitHub acfions image update.

**Comment by HThuren** [comment]
Right, no hurry for this PR :-), I give it a try next friday

**Comment by pfeerick** [comment]
LGTM... it's hit or miss which builds will fail... and different ones fail on retry (i.e. el18, x12, x9lite passed on a repeat run, but others are going to fail... just haven't timed out yet)... and given it is a cosmetic rather than functional code change, it really only needs to pass a few of the checks given the current issues.

**Pull request merged**
