### PR TITLE
feat(color): show global variable names in UI

### LINKED ISSUE #3623: Use Global Variables names everywhere in the GUI instead of certain places only
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I often have problem to set up a Special Function or Widget using a global Variable, because those functions don't show the names of the GV but their standard number (GFx) instead.
When we have many GV it becomes complicated to remember what GV is what...
In some settings the system use the GV names (such as Input, Mixes...) which is convenient to identify each GV.

### Describe the solution you'd like

I would simply like that the system uses the GV names when they are set, each time we have to refer to a GV, everywhere in the GUI.
Exactly as the source inputs (switches, sliders, pot.) when they have been renamed in the radio settings. 

### Describe alternatives you've considered

_No response_

### Additional context

GV names lack

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3623 

SF/GF edit:
screenshot_tx16s_24-09-11_07-42-13

SF list:
screenshot_tx16s_24-09-11_08-51-49

GV edit (title bar):
screenshot_tx16s_24-09-11_07-47-07

Source select (already in 2.11):
screenshot_tx16s_24-09-11_07-26-34

### CODE REVIEW

**Comment by pfeerick** [comment]
LGTM on TX16S 😍

**Comment by frankiearzu** [comment]
Great job Phil! The Logical switches page also could benefit also from displaying the GV name.

**Comment by philmoz** [comment]
> Great job Phil! The Logical switches page also could benefit from displaying the GV name.

I thought I'd covered all cases - where are you still seeing just the GVx string?

**Comment by frankiearzu** [comment]
All good.. sorry, wrong firmware while testing.

**Pull request merged**
