### PR TITLE
Implemented View Text

### PR DESCRIPTION
**Pull request by eshifri**
This implements View Text (and, hopefully, model notes (checkList)).
It works good on the touch screen, but without it implementation is "old style": using PGUP and PGDN buttons; for some reason EVT_ROTARY_* is not coming down to this window. If anybody has ideas why...
Some code cleanup is also included based on the creation of new class DynamiMessageDialog.

### CODE REVIEW

**Comment by pfeerick** [comment]
Nice work there! It is still a work in progress? As it looks like the T16 build failed 😢 

```
[ 84%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/colorlcd/view_statistics.cpp.o
[ 84%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/colorlcd/view_text.cpp.o
/__w/edgetx/edgetx/radio/src/gui/colorlcd/view_text.cpp: In member function 'virtual void ViewTextWindow::onEvent(event_t)':
/__w/edgetx/edgetx/radio/src/gui/colorlcd/view_text.cpp:97:13: error: 'onE' is not a member of 'Page'
   97 |       Page::onE vent(event);
      |             ^~~
 ```

**Comment by eshifri** [comment]
Just a typo. I have commited the fix.

**Comment by pfeerick** [comment]
Don't you just hate that... wrong window / tab gets focus, and something goes where it shouldn't! 😮 😆 I'm having that problem at the moment getting used to the new VSCode console tabs... when you click a tab on the tab bar, the focus stays there, so when you start typing you're interacting with the tab bar...  not the tab you just switched to! 😱

**Comment by pfeerick** [comment]
Right, just tried it on my TX16s... viewing the text file in the SD browser works great... even shows the up and down arrows... for switches... e.g. 
image

Showing as a pre-flight checklist doesn't work though... it seems that `(g_model.displayChecklist && modelHasNotes())` is working as there is an attempt to show the 'pre-flight' checklist (need to power on with that model selected and the checklist enabled due to #348), but the text view is blank. If the pre-flight checklist option is selected, and there is no matching text file, no attempt is made to show the checklist (correct behaviour). 

image

Model name is FPV250, and text file name is `/MODELS/FPV250.txt`, with the following content:
```
Model: FPV250
Batt: 3S or 4S

SD\up  = Self-Level
SD!\up = Acro

SG\up  = Mute
SG!\up = Voice Telem
```

**Comment by pfeerick** [comment]
Also, given the ifdef block was only there there to display the colour screen warning compiler warning, you should be able to remove it completely ;)

image

to 

image

**Comment by eshifri** [comment]
Right! It was VSCode. :-) Definitely I have pressed Enter thinking that I'm on the different Tab or in the console. :-(

I have never used check-lists, so did not know how to test it. :-)
I will look into it. 
Actually, I was expecting problems with the model name. Go figure..

Yes, I thought about removing the ifdef, but decided to keep it for time being: just in case readModelNotes() does npt work and I need to disable it again. :-)

**Comment by pfeerick** [comment]
Can you make it so the header stays put, so you don't need to scroll up to get back to the back 'touch' button?

Also, it chops off the last line of a text file if there is no following newline... I went silly and put a really long model note file in, and thought it was a number of lines problem, but it also happened with a really short one. i.e. the last line of this won't show... (unless you hit enter at the end of the last line. 

[FPV250.txt](https://github.com/EdgeTX/edgetx/files/6761152/FPV250.txt)

**Comment by pfeerick** [comment]
Another thought also, would be to add an icon for model notes to the main menu carousel if valid (since there is the `modelHasNotes`)... I added this to `view_main_menu.cpp` just to see if the concept would work, and it correctly inserted the icon if only if model notes were present... obviously needs a proper icon and actual view. It depends how far you want to go with this PR - stick with just the text view, and by happy co-incidence, pre-flight checklist in it's current form actually does something, or flesh out model notes as well. 

```
  if (modelHasNotes())
  {
    carousel->addButton(ICON_MONITOR, "Model\nNotes", [=]() -> uint8_t {
      deleteLater();
      new ModelSelectMenu();
      return 0;
    });
  }
```

**Comment by eshifri** [comment]
Many thanks for testing this!
I will try to fix it.

**Comment by JimB40** [comment]
Hey. Gave test run. :)
1. Top bar should stay if possible (back button (logo) and file name)
2. Try to check against big data ie text file with lots of lines and long lines
a. Seems like wrapping doesn't work properly. I know it may be tough to implement as ColorLCD fonts have variable width so you can't wrap at contant column. Maybe horizontal scroll would be solution instead if wrapping?
b. vertical scrolling seems to have some bug
https://youtu.be/DXD_RWugX-A

**Comment by eshifri** [comment]
model notes are working now.
Last line is displayed.

I understand the problem with horizontal clipping - will fix.

The maximum size of the text file in OTX is limited to 2K.
I cannot reproduce the scrolling problem: it stops for me at the last line.
Please notice that empty lines (CR) will be also shown.
It is possible that this is induced by horizontal clipping as well.

**Comment by pfeerick** [comment]
The scrolling problem will might be because of the whopping big file loaded... perhaps the view window size is still calculated, but the file content isn't there because of the 2K limit?

I would think if opening large text files were to be a 'supported' feature... some other mechanism would have been be implemented... being able to choose which 2K segment of the file to load, etc. But for the standard model notes this is intended to be used with it's more than sufficient.

**Comment by pfeerick** [comment]
Just loaded latest build of this PR... Woohoo! Pre-Flight checklist, check! :) Text now appears in the box... so fantastic work there. 

I was just thinking it would also be good if there was a slight margin off the edge of the screen... probably about 5px so the text isn't so close to the bezel. ;)

**Comment by eshifri** [comment]
All wishes granted. :-)

**Comment by pfeerick** [comment]
Dang it... missed it by 'that much' ... But yes, I think the wishlist is complete for now ;)
This file ... [FPV2502.txt](https://github.com/EdgeTX/edgetx/files/6766537/FPV2502.txt) ... when just viewed ... results in 

image

I don't have time to look at the code to any constructive suggestions as to what might be doing it, but it seems like it's being a bit overly opportunistic about wrapping (I take it you went with wrapping rather than horizontal scroll?), and seems to take a character with it when it wraps - index out by one?

**Comment by eshifri** [comment]
OK, every working code has at least two bugs in it. :-)
What radio is this? On my TX16S the text covers the full screen width.

**Comment by pfeerick** [comment]
Um... TX16? 😝 

Hm... with that text file? As it don't actually have long lines in it and the lines "were" shorter than the screen width (hasn't been edited since yesterday) ... ye ye ye... what is this TX doing to me? 😮

**Comment by pfeerick** [comment]
Removing the manual newlines so that the text wraps on it's own gives me this... 

[FPV2503.txt](https://github.com/EdgeTX/edgetx/files/6766587/FPV2503.txt)

image

**Comment by eshifri** [comment]
Lost letter fixed.
I will look into horizontal scroll later.

**Comment by eshifri** [comment]
Different length is due to non-fixed side font: the number of letters in the string is the same.

**Comment by pfeerick** [comment]
Yeah, I just realised that when looking at the change... one of the times monospaced fonts are nice! :D

**Comment by pfeerick** [comment]
@eshifri Do you have any objections to this being merged tomorrow so it's in the next nightly? I'm sure there's more that can be done on it, but it is at least functional at present, if not as pretty as it could be.

**Comment by raphaelcoeffic** [comment]
@eshifri is there a particular reason for having 2 different implementations based on whether or not touch-sensor is supported?

**Comment by eshifri** [comment]
@pfeerick No objections from my side.

@raphaelcoeffic Unfortunately there is: ROTARY events are not coming to the Window class (or at least I do not know how to force them to come there). 
So I cannot make scrolling window without touch screen.
"Old style" no-touch version is actually more generic (although does not look as good), but there is no way (or at least I was not able to find it) to get sliding touch events and instead of moving the window reload the buffer.
Hope the explanation makes some sense. :-)

**Comment by raphaelcoeffic** [comment]
> @pfeerick No objections from my side.
> 
> @raphaelcoeffic Unfortunately there is: ROTARY events are not coming to the Window class (or at least I do not know how to force them to come there).
> So I cannot make scrolling window without touch screen.
> "Old style" no-touch version is actually more generic (although does not look as good), but there is no way (or at least I was not able to find it) to get sliding touch events and instead of moving the window reload the buffer.
> Hope the explanation makes some sense. :-)

Ah ok! But that should be easy to fix. Basically, you can do the scrolling the same way with the rotary events, you just have to call the scroll function yourself, that’s it.

**Comment by eshifri** [comment]
That is what I wanted to do, but ROTARY events are not coming into the window. I have added code to print all received events: all button presses are received; rotations are not.

**Comment by raphaelcoeffic** [comment]
> That is what I wanted to do, but ROTARY events are not coming into the window. I have added code to print all received events: all button presses are received; rotations are not.

Ok, I'll sort it out.

**Comment by eshifri** [comment]
Figured it out.

**Comment by pfeerick** [comment]
Nice! Button and rotary scrolling TX16S well as touch scrolling! :)

Is is possible to bump the scroll speed up to say three lines per "event" or do you think that's a bad idea?

Something to be considered, and I don't know if it's a fault here, or in the USB popup menu, but when viewing a text file, and attaching the USB lead, the popup menu for joystick or strange doesn't get focus from the scroll-wheel, so scrolling actually makes the dimmed text view scroll.

**Comment by eshifri** [comment]
Of course it should be possible to bump the scroll speed, but IMHO it will be too fast: after all the text files are limited to 2K.

I will take a look at the USB thing. Touch interface is working with USB menu, but buttons and scroller with the text view. So something is not right with checkEvents() function. Is there an event associated with USB connection?

**Comment by pfeerick** [comment]
Yeah, that's why I was thinking maybe three lines... as 1 line just seems a bit slow... then again, if you want to get really fancy, that's where you could have line by line, and page by page - as 2048 characters is still between 3-5 pages depending on the wrapping. 

There is also this... it seems like is an automatically generated value as part of libopenui that tracks the rotation speed of the encoder... maybe it can be used to dynamically change the scroll if the roller is used? 
https://github.com/EdgeTX/edgetx/blob/802127852e401633512dcf75f5ee5c1d6eac7b41/radio/src/gui/colorlcd/timeedit.cpp#L64-L71

I think it is only the rotary + ENTER that is normally used for the menu. And I can't see any mention of an event being pushed... there is the usbPlugged() function returns a true-false... but if there isn't anything 'polling' there it probably isn't of any use?

I wonder if it is worth doing another PR and adding a events to the menu https://github.com/EdgeTX/edgetx/blob/7f472ff5e8a0cc599fd69288480f732cc7575b64/radio/src/main.cpp#L99  (i.e. prepare to be given the boot) and/or the actual USB connection, so underlying code and LUA can be told about it also (more for joystick as I don't know what lua, if any is allowed to still run in storage mode. Plus there's usb serial?)? https://github.com/EdgeTX/edgetx/blob/7f472ff5e8a0cc599fd69288480f732cc7575b64/radio/src/main.cpp#L118

That's more a @raphaelcoeffic question? 😉  Or a suggestion on how to alleviate the current focus issue 😀

**Comment by pfeerick** [comment]
One more think (I'm sorry, there's a lot to unpack here!) do you think that it's possible to limit the scroll area to the actual loaded amount of text? Or at least show some indication that that is all that can be loaded? If not, maybe we can look later into trying to dynamically read the file in 2k chunks as you scroll through it - i.e. you might be trying to review a log file (meaning `.csv` at least needs to have a option also for viewing text files, since that's the default logging extension).

**Comment by eshifri** [comment]
The USB issue is fixed (last delivery).

Everything is possible - it is just a SW :-).
It is possible to read the file by a number of screen lines chunks and move this window along the file (if you know what I mean).
Unfortunately, ot requires to increase the size of the reusable_buffer and it is currently the same for all TXs.
Another trick I have not mastered yet is to get touchscreen events; this sliding window is relatively straight forward with rotary encoder, but may be tricky with touch screen.
It will also be less nice than sliding with pixel resolution - the screen will jump by a full screen.

Going by line with scroller and by page with buttons should not be too difficult, but the thing is I'm not familiar with ALL color screen radios :-). Are there any that do not have rotary encoder? Then it will move by page only. 

So my suggestion would be to merge what we have and keep improvement in mind for future releases.

**Comment by pfeerick** [comment]
Nice, I'll test it a little later on and see what I can break this time! 😆 

Sure, but there's also practical limits to what you can do (i.e. implementing something without writing a whole new class or something just because of one tiny detail) and knowledge of the codebase (guilty as charged!)

Yeah, a sliding window is what I was thinking of, but I think that can wait. 

I'm not familiar with *all* colour radios, either... and there probably are some without an encoder (not counting the NV14 yet), so yeah, it gets messy ... i.e. 

https://github.com/EdgeTX/edgetx/blob/7f472ff5e8a0cc599fd69288480f732cc7575b64/radio/src/gui/128x64/model_select.cpp#L225-L244

**Comment by raphaelcoeffic** [comment]
@eshifri I noticed that the read routine does open and close the file for basically every single line of text, could this be fixed please? Second point: you don't have to use the reusable buffer, as the color lcd radios have plenty of memory. Just use `new` or `malloc` as you need, and don't forget to free that memory when not used anymore.

**Comment by eshifri** [comment]
I thought dynamic memory allocation was "no-no"...

**Comment by eshifri** [comment]
Extra f_open()/f_close() removed.

**Comment by raphaelcoeffic** [comment]
> I thought dynamic memory allocation was "no-no"...

On the colorlcd targets we are using it all the time. We have 8MB RAM ;-)

**Comment by pfeerick** [comment]
Oh, very nice! And yes, it seems to be working quite nicely! :) 

Scroll bar is MIA?

**Comment by eshifri** [comment]
Scrollbar is lost since the inner size is equal window size now: we are not scrolling the existing text in the window any more. I will look into possibility to simulate it, but I'm not too hopeful.

**Comment by eshifri** [comment]
Added scrollbar. It is not ideal, since the number of lines is not known beforehand.

**Comment by pfeerick** [comment]
> we are not scrolling the existing text in the window any more

Ouch, yes, sliding window, which is a bit variable due to variable character rendering... 

I haven't tried this yet, so I'm presuming the scrollbar will be a bit... inaccurate... but at least give guidance as to "keep scrolling, there's more to see"...

**Comment by eshifri** [comment]
Yes, I fought with this overshooting with rotary encoder issue for some time and gave up for now. It does not overshoot too far though: I have limited the jump be 0.5 page, unless you really try to get into this situation deliberately.
Hm, it might be possible to read the file, count the lines without showing them, set the scrollbar range and return to start. Let me take a look.
"No hot water - no life!" Gosh, I remember the times when the whole city was without hot water for two months every summer. :-)

**Comment by eshifri** [comment]
Added scrollbar "prediction" and some smoothing to the long lines scrolling.

**Comment by raphaelcoeffic** [comment]
@pfeerick @eshifri do you guys have the feeling this something that can be included into 2.4.0, or would you feel more comfortable with 2.4.1? Given that we don't have any text viewer right now, anything is better than nothing, so minor nits are ok, as long as it does not crash/EM ;-)

**Comment by eshifri** [comment]
IMHO it is prime time ready. :-)

**Comment by pfeerick** [comment]
I haven't tried the last couple of commits... but as of about two days I ago I was more than happy with it... so I think it's time to commit. So unless there are objections I would like to merge in about 15-18 hours from now, i.e. roughly two hours before the next nightly so there's time for some last minute testing and final tweaks to the PR. Unless Raphael is really impatient and does it before then, naturally! 😆

**Comment by pfeerick** [comment]
With my long text file, scrollbar shows up, and is small indicating plenty to scroll through. Only niggle is it probably shows up *under* the header so can't see it until scroll a page or so and it apperas from under the header bar. 

With a small text file (less that one screen) a big scroll bar appears, and I can scroll. Initial testing shows it works fine otherwise.

**Pull request merged**
