### PR TITLE
feat(color): Add alignment option for text widget

### PR DESCRIPTION
**Pull request by rotorman**
Adds text alignment option for the text widget.
Here the results, as tested with TX16S simulator:

grafik

grafik

grafik

grafik

grafik

grafik

Translators, please double check the translation TR_ALIGNMENT - thanks!

### CODE REVIEW

**Comment by Eldenroot** [comment]
Maybe for CZ: it should be:

Zarovnání

**Comment by Eldenroot** [comment]
Maybe for CZ: it should be:

Zarovnání

**Comment by Eldenroot** [comment]
Maybe for CZ: it should be:

Zarovnání

**Comment by Eldenroot** [comment]
Maybe for CZ: it should be:

Zarovnání

**Comment by ulfhedlund** [comment]
Perhaps the other translators will miss this, like I almost did. 
Here's a ping to those I know of:
@ParkerEde DE
@Eldenroot CZ (already replied)
@robustini IT
@zyren CN / TW
@ajjjjjjjj PL
@ToshihiroMakuuchi JP
@HThuren DA
@Pat6874 FR

**Comment by zyren** [comment]
***************************************************
CN

#define TR_ALIGNMENT "对齐"
***************************************************
***************************************************
TW

#define TR_ALIGNMENT "對齊"
***************************************************

**Comment by ajjjjjjjj** [comment]
PL

`#define TR_ALIGNMENT "Wyrównanie"`

**Comment by Pat6874** [comment]
FR translation:
#define TR_ALIGNMENT "Alignement"

Le 9 mai 2023, 20:37, à 20:37, ulfhedlund ***@***.***> a écrit:

**Comment by ParkerEde** [comment]
DE
#define TR_ALIGNMENT "Ausrichtung"

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_ALIGNMENT "アライメント"

**Comment by robustini** [comment]
IT
#define TR_ALIGNMENT "Allineamento"

**Comment by pfeerick** [comment]
Looking good on TX16S hardware.

**Pull request merged**
