### PR TITLE
fix: plurals and indefinite articles in German TTS, plus

### PR DESCRIPTION
**Pull request by mha1**
fix for no voice output for unit radian and fix for missing LUA constant for unit dbm

German TTS:
- fixed use of plurals and indefinite articles depending on unit (radio and LUA)
- use case: playValue(telem_sensor_capacity) -> wrong output, not using plurals where necessary
- use case: LUA playNumber for various units, e.g. not using plural for two minutes ("zwei Minute" -> "zwei Mintuten")

no voice output for unit radian, all languages:
- fixed reference to non-existing wav file radian0.wav/radian1.wav to existing rad0.wav/rad1.wav
- use case LUA playNumber(n, UNIT_RADIANS, no outout of unit for all languages

missing LUA constant for unit dbm:
- added LUA constant UNIT_DBM
- use case LUA playNumber(n, UNIT_DBM), luac fails.

### CODE REVIEW

**Comment by pfeerick** [comment]
Actually, your radian fix would break https://github.com/EdgeTX/edgetx-sdcard-sounds/commit/363b38b7d00aec4c9ec814d572954af7e6bc85be, so I'll need to now revert that, as this will make old packs work without changes. 

I'll assume you have tested the audio since it's native language for your :grin:

**Comment by mha1** [comment]
welcome back. why does the radian fix break etx?

tested? it compiled ok. just kidding, I did test it.

**Comment by pfeerick** [comment]
Um... have a look at the commit perhaps? `rad#.wav` -> `radian#.wav` after that commit...  🤭

**Comment by mha1** [comment]
Sorry, actually it's the other way round. Current SOUNDS/SYSTEM audio files have rad#.wav files, but audio.cpp is looking for 'radian'. This is the reason why there is no spoken unit radians in any language. I changed audio.cpp to look for 'rad' instead of 'radian' to match the real file names.

**Comment by pfeerick** [comment]
All I can say is LOOK AGAIN at the referenced commit... As of July you are
wrong :-P (which is why it will need to be reverted now).

**Comment by mha1** [comment]
gotcha, wasn't looking at the sdcard-sounds commit. you fixed the problem at the other end.

**Comment by mha1** [comment]
and sorry for my tunnel vision. always feeling guilty I misread you as my fix needs to be reverted. reverting any of the two would but yeah, mine is backwards compatible.

**Comment by pfeerick** [comment]
lol... sorry about that... given the fault is in the sound pack, yeah,
altering the code is probably the simplest fix for existing ETX users. I'd
picked up the issue when I noticed one of the other telemetry items wasn't
being read out, and when checking with ETX and OTX code, it's pretty much
always been radianX.wav (for like 7+ years), so I don't know why our sound
pack had it as radX.wav, especially as that introduces an unnecessary
incompatibility with OTX packs.

**Pull request merged**
