### PR TITLE
refactor: IWDG driver and EM trigger

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- removed usage of RTC BKP registers to detect software/watchdog reboots
- use HAL/LL drivers for watchdog handling
- DRY linker scripts (including uninitialised RAM region)

### CODE REVIEW

**Comment by pfeerick** [comment]
Well, I just had my TX16S in a perpetual EM for no apparent reason (except the RTC battery is getting low on my test radio... 2.4v immediately after boot boot, 2.8v a few seconds after)... flashing other PR firmware made no change... deleting radio.yml made no change... flashing this PR made it return to normal operation immediately. 

I just tried a hard power cut, and that didn't trigger EM? Expected?

**Comment by raphaelcoeffic** [comment]
> I just tried a hard power cut, and that didn't trigger EM? Expected?

Yes. The only thing that will trigger EM now is a watchdog reboot, as it should be IMHO.

The master piece of this PR is basically this:
```c++
// abnormal_reboot.h
#define UNEXPECTED_SHUTDOWN() \
  (abnormalRebootGetCause() == ARC_Watchdog)

// abnormal_reboot.cpp
void _init_reboot_cause()
{
  if (_reboot_cause != _REBOOT_CAUSE_DEFAULT) return;

#if defined(DEBUG)
  _dbg_csr = LL_RCC_ReadReg(CSR);
#endif
  
  if (LL_RCC_IsActiveFlag_IWDGRST()) {
    _reboot_cause = ARC_Watchdog;
  } else if (LL_RCC_IsActiveFlag_SFTRST()) {
    _reboot_cause = ARC_Software;
  } else {
    _reboot_cause = ARC_None;
  }

#if !defined(BOOT)
  LL_RCC_ClearResetFlags();
#endif
}
```

**Comment by mha1** [comment]
> Yes. The only thing that will trigger EM now is a watchdog reboot, as it should be IMHO.

how about other exceptions like division by zero, illegal instruction, etc.

**Comment by raphaelcoeffic** [comment]
> how about other exceptions like division by zero, illegal instruction, etc.

They trigger a `HARD FAULT`, which in turn uses the default handler, which is an endless loop, thus triggering the `IWDG`. So it should work the same.

If you compile with `-DDEBUG=Y` and edit the handler for the test function in `functions.cpp`, you can test it. Something like that:
```c
__asm volatile(
    "MOV r0, #1\n\t"
    "MOV r1, #0\n\t"
    "UDIV r0, r0, r1\n\t"
);
```

Then trigger that function with a switch via special function, and see what happens :-)

**Comment by philmoz** [comment]
> They trigger a `HARD FAULT`, which in turn uses the default handler, which is an endless loop, thus triggering the `IWDG`. 

Does that mean there will be a longer delay before the radio restarts?
 
> If you compile with `-DDEBUG=Y` and edit the handler for the test function in `functions.cpp`, you can test it. Something like that:
> 
> ```c
> __asm volatile(
>     "MOV r0, #1\n\t"
>     "MOV r1, #0\n\t"
>     "UDIV r0, r0, r1\n\t"
> );
> ```

Or use:
```
              __builtin_trap();
```

**Comment by raphaelcoeffic** [comment]
> `__builtin_trap();`

Nice! I didn't know about that one! Works like a charm as well, as generates a dedicated `Permanently Undefined` instruction:
Screenshot 2023-11-20 at 11 00 22

**Comment by raphaelcoeffic** [comment]
> Does that mean there will be a longer delay before the radio restarts?

It's not that long, the watchdog is about 1 second or so.

**Comment by philmoz** [comment]
> > Does that mean there will be a longer delay before the radio restarts?
> 
> It's not that long, the watchdog is about 1 second or so.

Is that wise? 

An extra second before the model reconnects could make a big difference in the field.

**Comment by mha1** [comment]
> An extra second before the model reconnects could make a big difference in the field.

Does the current implementation also propagate a usage fault down to a WDT trigger (Ithink so)? Then we'd be at the same total EM time.

The total EM time is dominated by the time it takes to boot EM, get it up and running including the RF module power cycle and module reconnect. If I remember correctly this can take up to 2-4s until control is regained.

**Comment by raphaelcoeffic** [comment]
> If I remember correctly this can take up to 2-4s until control is regained.

Yes, that's about it. Shortening the IWDG might not be such a good idea. And triggering an immediate reboot on Hard fault makes it much hard to debug. I'd leave it like that for now. We can still start to find some smarter way later. Please note that this is the way it has been for ages, and is a pretty unique feature among RC radio systems.

My preferred way to improve the safety of the system would be to introduce support for the MPU and start enforcing privilege levels. This way we could hopefully crash the UI or other parts without crashing the radio.

**Comment by mha1** [comment]
> My preferred way to improve the safety of the system would be to introduce support for the MPU and start enforcing privilege levels. This way we could hopefully crash the UI or other parts without crashing the radio.

Quite the project. freeRTOS should be able to support an MPU.  Fork EdgeTX to  EdgierTX

**Comment by gagarinlg** [comment]
I just decided to not use the MPU ona work project, but there the SW is a lot simpler. Just a UART, a Display and a few buttons

**Review by richardclli — COMMENTED** [review]
Any mechanism to map different sizes of SDRAM?

**Comment by raphaelcoeffic** [comment]
> Any mechanism to map different sizes of SDRAM?

No problem: if necessary, the same mechanism as for different FLASH sizes or different SDRAM start address will be used. We just pass a linker parameters to be used in the linker scripts.

**Comment by richardclli** [comment]
I need to know how to do this, because current main target can have their own linker script to specify the memory map.  Please drop me some brief notes.

> > Any mechanism to map different sizes of SDRAM?
> 
> No problem: if necessary, the same mechanism as for different FLASH sizes or different SDRAM start address will be used. We just pass a linker parameters to be used in the linker scripts.

**Pull request merged**
