### PR TITLE
Allow LUA widget translations

### PR DESCRIPTION
**Pull request by DavBfr**
Allows #221

Summary of changes:
Add the ability for Lua Widgets to display proper text in the Settings Menu as well as Display translated strings for Settings and The Widget name itself.

Backward compatibility is preserved as it adds a widget callback `translate(text, lang)` that is called if defined.

Example:

```lua
local name = "MyWidget"

local options = {
    {"FirstChannel", VALUE, 1},
    {"FillBackground", BOOL, 0},
    {"BgColor", COLOR, COLOR_THEME_SECONDARY3},
    {"TextColor", COLOR, COLOR_THEME_PRIMARY1},
    {"BarColor", COLOR, COLOR_THEME_SECONDARY1}
}

local function update(widget, options)
    widget.options = options
end

local function create(zone, options)
    local widget = {zone = zone, options = options}
    return widget
end

local function refresh(widget, event, touch)
end

local function translate(text, lang)
    local tr = {
        MyWidget = "My Widget",
        FirstChannel = "First Channel",
        FillBackground = "Fill Background?",
        BgColor = "Bg Color",
        TextColor = "Text Color",
        BarColor = "Color"
    }
    local tr_fr = {
        MyWidget = "Mon Gadget",
        FirstChannel = "Permier canal",
        FillBackground = "Remplir le fond ?",
        BgColor = "Couleur du fond",
        TextColor = "Couleur du texte",
        BarColor = "Couleur"
    }
    local v
    if lang == "FR" then
        v = tr_fr[text]
    else
        v = tr[text]
    end
    return v == nil and text or v
end

return {
    refresh = refresh,
    name = name,
    create = create,
    update = update,
    options = options,
    translate = translate
}
```

Screen Shot 2022-09-05 at 10 18 51

Screen Shot 2022-09-05 at 10 23 29

Screen Shot 2022-09-05 at 10 18 40

Screen Shot 2022-09-05 at 10 23 35

### CODE REVIEW

**Comment by pfeerick** [comment]
Is the example code given compatible with the current Lua version and support? As I get errors as soon as I try it is things like `const` do not appear to be a Lua keyword in the Lua 5.2 engine currently in use ;)

**Comment by DavBfr** [comment]
@pfeerick Sorry, that's not LUA at all.

**Review by pfeerick — APPROVED** [review]
Very nice indeed. I'm guessing the original example code you had up will be seen again in a future PR? :grin:

**Comment by DavBfr** [comment]
> Very nice indeed. I'm guessing the original example code you had up will be seen again in a future PR? 😁

No, it's just the original typescript code. The Lua script is transpiled from it.

**Pull request merged**
