### PR TITLE
chore(bw): simplify navigation code

### PR DESCRIPTION
**Pull request by philmoz**
- Add switch & source popup menus to 9x nav..
- Add 'View note' / 'View channels' popup to x7 (from x9d).
- Fix off by one errors.
- Fix repeat movement not stopping at bottom of page (9x & xlite).
- Unify and merge 9x & xlite navigation.
- Unify and merge x7 & x9d navigation.
- Move common code to navigation.cpp

### CODE REVIEW

**Comment by 3djc** [comment]
Will try to review this in the coming days

**Comment by 3djc** [comment]
x7 nav (tested on MT12)
Place yourself in drive mode
old: you enter the next screen as soon as you click
this; you enter the next screen only on release, only on short clicks, and since short need to be really short, I get stuck
seems a general behavior since the same happens on G1 once view is entered

same comment for page up/down, you need to succeed a short click, if not, it does nothing

**Comment by philmoz** [comment]
I see no difference between current main and this PR.
The changes you describe are from PR #4849

**Comment by 3djc** [comment]
Bit odd since my reference MT12 runs a firmware done on July 9th

**Comment by philmoz** [comment]
I have restored the BREAK after LONG key press.
Navigation that does not explicitly use the LONG press (and kill the BREAK event) will now trigger on a BREAK event.

This should restore the 2.10 navigation functionality.

@3djc does this work better for you on the MT12?

**Review by 3djc — COMMENTED** [review]
Works for me in current state, thanks @philmoz

**Comment by pfeerick** [comment]
bw128 (T20) 
- `model_outputs` - long press of ENTER for min or max to toggle between constant and GV results in inability to leave the page - have to power down the transmitter. 
- `model_special_functions` - pressing enter / long enter (for popup) to assign trigger for new SF works, but am unable to leave edit mode for that column. 

bw212 (X9D+)
- `model_select` - long press for popup menu not working.
- `model_outputs` - long press of ENTER for subtrim, min or max to toggle between constant and GV results in inability to leave the page - have to power down the transmitter. 
- `model_special_functions` - pressing enter / long enter (for popup) to assign trigger for new SF works, but am unable to leave edit mode for that column.

**Comment by philmoz** [comment]
> bw128 (T20)
> 
> * `model_outputs` - long press of ENTER for min or max to toggle between constant and GV results in inability to leave the page - have to power down the transmitter.
> * `model_special_functions` - pressing enter / long enter (for popup) to assign trigger for new SF works, but am unable to leave edit mode for that column.
> 
> bw212 (X9D+)
> 
> * `model_select` - long press for popup menu not working.
> * `model_outputs` - long press of ENTER for subtrim, min or max to toggle between constant and GV results in inability to leave the page - have to power down the transmitter.
> * `model_special_functions` - pressing enter / long enter (for popup) to assign trigger for new SF works, but am unable to leave edit mode for that column.

Thanks, should be fixed now.

**Comment by pfeerick** [comment]
bw212(x9d+) and bw128 (tx12). Had a quick poke around the tlite interface also... and it seems to be working fine also. I had clearly forgotten how limited the UI was there though... i.e. x7 navigation is so much nicer with the popup menus and long press helpers!

**Pull request merged**
