### PR TITLE
Added OS theme colors as suggested by JimB40 in #506 and improved color handling in Lua

### PR DESCRIPTION
**Pull request by jfrickmann**

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
I think @JimB40 's idea was to replace the existing colours (incl. those used in C++) to only use these. For now, that basically means two things:
- these colours are already attributed to some names: search & replace these names everywhere (scripting?).
- some colours are used for multiple indexes: reduce/remove the superfluous indexes by replacing them through one of the 10.

But there is still one big chunk of issues with one single thing: many function calls does not specify any colour in the flags, so that *black* is used (all `0` for RGB), which is not what we intent. So we need to find some smart way of either adding the default colour param everywhere, or add it in some smart way that does not need to change 100+ places in the code.

**Comment by jfrickmann** [comment]
If I touch the existing colors, then the checks fail. So we will need to remove the color checks before we move forward.

**Comment by jfrickmann** [comment]
I just looked around in libopenui, and as far as I can see, the whole color-index-palette thing is in EdgeTX and not in libopenui. So how about we take the 16 color bits and code them so we have up to 0x7FFF palette colors and 3x5 bit RGB colors? I.e. we use bit 16 to tell if we look up an indexed color or if we convert the other 15 bits to RGB?

**Comment by jfrickmann** [comment]
So in Lua, people are not forced to pick an existing palette color, and change it before using it. They can just use the RGB function directly.

**Comment by jfrickmann** [comment]
We can also add "literal" colors to the palette like BLACK, WHITE, BLUE etc.

**Comment by raphaelcoeffic** [comment]
> I just looked around in libopenui, and as far as I can see, the whole color-index-palette thing is in EdgeTX and not in libopenui. So how about we take the 16 color bits and code them so we have up to 0x7FFF palette colors and 3x5 bit RGB colors? I.e. we use bit 16 to tell if we look up an indexed color or if we convert the other 15 bits to RGB?

I think there are 2 aspects to this:
- how it is handled in C++,
- and how this is handled in LUA.

In **C++**, the colours are already de-facto used directly, whereby the constants used are actually using a lookup in the palette before returning their values (see `DEFAULT_COLOR` vs `DEFAULT_COLOR_INDEX` in `colors.h`). Here it is already ok, and we just need to replace/consolidate the constants used. This is where we need to solve the *"default colour issue"* (not passing a constant in the `LcdFlags` means *black*, whereby it should be `DEFAULT_COLOR`).

In **LUA**, the colours are passed only as an index into the palette, which is not necessarily what we want, at least not always. If using a flag for "true colours", we should place it in the lower 16-bits, like the other flags, this leaving the full 16-bits for the colour itself.

**Comment by raphaelcoeffic** [comment]
> We can also add "literal" colors to the palette like BLACK, WHITE, BLUE etc.

This would be useful in LUA, but then it should use directly RBG565 (+flag) in the LUA constant.

**Comment by jfrickmann** [comment]
So we will replace the old color palette with the new one in C++, and go through the code to change it everywhere.
In Lua, we will change the color flag from using palette index to using RGB565.
We will also provide a Lua function to convert (trunate) from RGB888 to RGB565, so users can use e.g. color(0xFF0000) for red (@JimB40's idea).
For using the theme colors in Lua, if we provide them as RGB565 constants, then we would have to reboot before changes would show up in Lua. So maybe we should provide the palette indices as constants and a Lua function, so we can use osColor(OS_COLOR_*) to get the current RGB565 value of a theme color?

**Comment by JimB40** [comment]
There is such a function already lcd.setRGB(R,G,B)
Just name is confusing as it converts RGB888 to RGB565 so should be getRGB565()
Plus it takes 3 params that is far less convenient then passing 24bit hex 0xRRGGBB

**Comment by jfrickmann** [comment]
> There is such a function already lcd.setRGB(R,G,B)
> Just name is confusing as it converts RGB888 to RGB565 so should be getRGB565()
> Plus it takes 3 params that is far less convenient then passing 24bit hex 0xRRGGBB

I do not see any function named setRGB, but there is setColor - is that what you meant? lcd.setColor changes a theme color to an RGB565 value.
https://doc.open-tx.org/opentx-2-3-lua-reference-guide/part_iii_-_opentx_lua_api_reference/lcd-functions-less-than-greater-than-luadoc-begin-lcd/setcolor

**Comment by jfrickmann** [comment]
Here is a little python script to find files and replace strings in them. Now we just need to decide how to decide what OS_COLOR will replace the old theme colors. Shall we simply pick the color with the shortest Euclidean distance in the RGB space?
```
import os

replacements = [
  ( 'ALARM_COLOR', 'OS_COLOR_WARNING' ),
  ( 'BARGRAPH1_COLOR', 'OS_COLOR_WARNING' ),
  ( 'BARGRAPH2_COLOR', 'OS_COLOR_PRIMARY1_INDEX' ),
  ( 'BARGRAPH_BGCOLOR', 'OS_COLOR_PRIMARY3_INDEX' )
]

def FindFilesWith(str):
  files = os.popen('grep -r -l -s ' + str).read()
  files = files.split('\n')
  files.remove('')
  files.remove('replacer.py')
  return files

def ReplaceTextIn(file, findTxt, replaceTxt):
  f = open(file, 'r')
  file_source = f.read()
  replace_string = file_source.replace(findTxt, replaceTxt)
  f.close()

  f = open(file, 'w')
  f.write(replace_string)
  f.close()

for rep in replacements:
  files = FindFilesWith(rep[0])
  
  for file in files:
    ReplaceTextIn(file, rep[0], rep[1])
```

**Comment by jfrickmann** [comment]
NewColors
@JimB40, I have now matched the OS colors to the existing colors as described above. Except for a couple of greys, everything else seems to match almost exactly. What do you think?

**Comment by jfrickmann** [comment]
@pfeerick, like this? @JimB40, what do you think?
NewColors 2

**Comment by pfeerick** [comment]
Would actually have to see it in action, and obviously it needs the approval of the head of UI/UX 😉 , but yes, that's what I had in mind. Naturally *something* will look not quite right after applying this, but at that point it's a game of spot the problem ;)

**Comment by raphaelcoeffic** [comment]
> Would actually have to see it in action, and obviously it needs the approval of the head of UI/UX 😉 , but yes, that's what I had in mind. Naturally _something_ will look not quite right after applying this, but at that point it's a game of spot the problem ;)

The goal should be that old LUA script “work”. Some are crashing directly if the constant does not exist…

**Comment by JimB40** [comment]
Jesper awesome work.
Now I believe we should make few important decisions, as we will try to set balance between flexibility, ease of use, ease of code maintenance & backward compatibility.
Another thing is I dont want to make changes just because we are ETX. OTX solutions may not be user friendly or bug free but I don’t perceive them as ‘trash’
Anyway first step is claryfing so looking at your chart and using Themer I can now spot issues & opportunities

I will post insights in separate comments

**Comment by JimB40** [comment]
1. Number color constants
Actually left column is what I should be called OS_Colors while right column is THEME_Colors. 
My view is biased with ease-of-use for user. As you can see to make decent looking Theme, most of OS_Colors assigned with same THEME_Color value.
Still playing with Themer I’ve noticed that having 10-11 colors we lost flexibility to set it “as I want”. 
Example are Trims as they are bound to COLOR_FOCUS. I know we can remap but once we will do it it will be hard coded.

**Comment by JimB40** [comment]
**Naming**
Here is bold. Any change is breaking compatibility, still we should move forward. 
Good thing is I had a sneak peek in few scripts and they use very basic LUA color constants so

If I was coding this from scratch I would code

**A. names for left column items as _COLOR_OS_xxx_  - where xxx is replaced by ALARM, HEADER, HEADER_BG etc**

naming sheme would be _AAA_BBB_CCC_DDD_
_AAA_ - Var Type (COLOR)
_BBB_ - Color Type (GROUP)
_CCC_ - UI element or function
_DDD_ - UI element component and funcion (Text, background, frame & focused, disable etc)

Examples:
**Non UI Items**
COLOR_OS_WARNING
COLOR_OS_LOGO
elc.

**UI Items**
COLOR_OS_DEFAULT
COLOR_OS_DEFAULT_FOCUSED
COLOR_OS_DEFAULT_SELECTED
COLOR_OS_DEFAULT_ACTIVE
COLOR_OS_DEFAULT_DISABLED
 
COLOR_OS_HEADER_TEXT 
COLOR_OS_HEADER_TEXT_FOCUSED
COLOR_OS_HEADER_TEXT_SELECTED
COLOR_OS_HEADER_TEXT_ACTIVE
COLOR_OS_HEADER_TEXT_DISABLED

COLOR_OS_HEADER_ICON
COLOR_OS_HEADER_ICON_FOCUSED
COLOR_OS_HEADER_ICON_SELECTED
COLOR_OS_HEADER_ICON_ACTIVE
COLOR_OS_HEADER_ICON_DISABLED

COLOR_OS_HEADER_ICON_BG
COLOR_OS_HEADER_ICON_BG_FOCUSED
COLOR_OS_HEADER_ICON_BG_SELECTED
COLOR_OS_HEADER_ICON_BG_ACTIVE
COLOR_OS_HEADER_ICON_BG_DISABLED

COLOR_OS_MENU_TEXT 
COLOR_OS_MENU_TEXT_FOCUSED
COLOR_OS_MENU_TEXT_SELECTED
COLOR_OS_MENU_TEXT_ACTIVE
COLOR_OS_MENU_TEXT_DISABLED

COLOR_OS_MENU_TEXT_BG 
COLOR_OS_MENU_TEXT_BG_FOCUSED
COLOR_OS_MENU_TEXT_BG_SELECTED
COLOR_OS_MENU_TEXT_BG_ACTIVE
COLOR_OS_MENU_TEXT_BG_DISABLED

Coding in C++ Dev can create new names for new UI element 
COLOR_OS_UIELEMENT 
COLOR_OS_UIELEMENT_FOCUSED
COLOR_OS_UIELEMENT_SELECTED
COLOR_OS_UIELEMENT_ACTIVE
COLOR_OS_UIELEMENT_DISABLED

or use one of _COLOR_OS_DEFAULT_xxx_

**B. names for right column items as _COLOR_THEME_xxx_ - where xxx is replaced by PRIMARY1, SECONDARY1 etc**

here is simpler naming scheme _AAA_BBB_CCC_
_AAA_ - COLOR
_BBB_ - GROUP
_CCC_ - UI element

Examples
COLOR_THEME_DEFAULT
COLOR_THEME_FOCUSED
COLOR_THEME_SELECTED
COLOR_THEME_ACTIVE
COLOR_THEME_DISABLED
COLOR_THEME_PRIMARY1
COLOR_THEME_PRIMARY2

**C. Then we map constants from A with constants from B**
Very important question is where we do this C++ or LUA ? As you can see we can provide simplicity with LUA App 
Is there going to be Theme Color changer in C++? 

**D. Compatibility issue**
Since we changed naming scheme we broke compatibility with 2.3

**Comment by JimB40** [comment]
**B. names for right column items as _COLOR_THEME_xxx_ - where xxx is replaced by PRIMARY1, SECONDARY1 etc**

here is simpler naming scheme _AAA_BBB_CCC_
_AAA_ - COLOR
_BBB_ - GROUP
_CCC_ - UI element

Examples
COLOR_THEME_DEFAULT
COLOR_THEME_FOCUSED
COLOR_THEME_SELECTED
COLOR_THEME_ACTIVE
COLOR_THEME_DISABLED
COLOR_THEME_PRIMARY1
COLOR_THEME_PRIMARY2

**C. Then we map constants from A with constants from B**
Very important question is where we do this C++ or LUA ? As you can see we can provide simplicity with LUA App 
Is there going to be Theme Color changer in C++? 

**D. Compatibility issue**
Since we changed naming scheme we broke compatibility with 2.3

**Comment by jfrickmann** [comment]
@JimB40, the colors in the left column are the existing names, and most of these are defined in libopenui, which we share with ETHOS and possibly others. So we cannot change these, but rather remap them to our theme colors.

**Comment by jfrickmann** [comment]
[OS colors.xlsx](https://github.com/EdgeTX/edgetx/files/6938396/OS.colors.xlsx)
Here is a spreadsheet with the previous suggestions plus OS_COLOR_DISABLED mapped in. Maybe that can be helpful for deciding on a theme color scheme.

**Comment by jfrickmann** [comment]
I have now done the scripted search and replace to replace 40 old theme colors with 11 new ones. I have also added back Lua constants mapping the old theme colors to the new ones, so things should be backwards compatible. And yes, TEXT_INVERTED_BGCOLOR is also included ;-)
So seen from Lua, things should remain as they were before, but we should update the documentation to point out that the old theme colors are "deprecated", and people should use the new ones going forward.

**Comment by JimB40** [comment]
Just to mention #563

**Comment by jfrickmann** [comment]
I am working my way through the Lua functions using colors, and I have fixed some missing boundary checks of color index, drawPoint color did not work, and if color flag is missing, it should have a default color instead of black. I have also done some changes to make improve the code style.
But looking at inverse text - here it uses a fixed color for text (COLOR_THEME_PRIMARY2) and for background (COLOR_THEME_FOCUS). Could we instead have it use the flags color for the background and the complementary color for the text? E.g. yellow for blue and white for black?

**Comment by jfrickmann** [comment]
I have now give the color handling in Lua a major overhaul; hence the title of this PR has been updated. 
Color flags can now hold either the index of a theme color as before, or a RGB value. Hence we can now use theme colors, CUSTOM_COLOR, values from lcd.RGB() or literal colors like e.g. WHITE, BLUE etc. interchangeably in Lua code. I find that is much easier and more intuitive than before when we were forced to work with indexed colors only.
I have also updated lcd.drawText(), lcd.drawNumber() and lcd.drawTimer() so they use a common function to draw that implements all of the party tricks involving the INVERS and BLINK flags. With INVERS the background is now drawn in the color specified by the flags instead of blue, and the INVERS text color can either be specified in a 5th argument, or it will be drawn in the complementary color to the background.

Please test it out, and let's merge it in before too long so we can test it thoroughly, and so we don't end up in rebasing chaos when something else is changed - it is a very big PR!

@raphaelcoeffic @pfeerick @JimB40 @lshems 

P. S. Here is a quick test widget and some screen shots from it:
```
options = {
}

local function create(zone, options)
  local widget = {
    zone = zone, 
    options = options,
    t0 = getTime()
  }

  return widget
end

local function refresh(widget, event, touchState)
  local x, y = 1, 1
  lcd.drawText(x, y, "No flags")
  y = y + 20
  lcd.drawText(x, y, "Mid size dark red", MIDSIZE + DARKRED)
  y = y + 30
  lcd.drawText(x, y, "Mid size blue inverse", MIDSIZE + lcd.RGB(0, 0, 255) + INVERS)
  y = y + 30
  local orange = lcd.getColor(ORANGE)
  lcd.setColor(CUSTOM_COLOR, orange)
  lcd.drawText(x, y, "Mid size orange blink", MIDSIZE + CUSTOM_COLOR + BLINK)
  y = y + 30
  lcd.drawText(x, y, "Mid size dark red inverse blink", MIDSIZE + DARKRED + INVERS + BLINK)
  y = y + 30
  lcd.drawText(x, y, "Mid size white on blue", MIDSIZE + COLOR_THEME_FOCUS + INVERS, COLOR_THEME_PRIMARY2)
  
  x, y = widget.zone.w, 1
  local ticks = getTime() - widget.t0
  lcd.drawTimer(x, y, 0.01 * ticks, MIDSIZE + RIGHT + BLACK + INVERS + BLINK)
  y = y + 30
  lcd.setColor(CUSTOM_COLOR, lcd.RGB(255, 150, 200))
  lcd.drawNumber(x, y, ticks, MIDSIZE + RIGHT + PREC2 + CUSTOM_COLOR)
  
end

local function background(widget)
end

local function update(options)
end

return {
  name = "Test",
  options = options,
  create = create,
  refresh = refresh,
  background = background,
  update = update
}
```
Blink1
Blink2

**Comment by jfrickmann** [comment]
P. S. I also changed opacity in draw[Filled]Rectangle() so it is a separate argument instead of embedded in the flags, because those are the same bits used for storing RGB color values. I assume that is fair game, as that feature was undocumented AFAIK.

**Comment by jfrickmann** [comment]
Here is an overview of the colors available with this PR:
### Indexed colors
These are the theme colors plus CUSTOM_COLOR, and they can be changed with lcd.setRGB().
 - COLOR_THEME_PRIMARY1
 - COLOR_THEME_PRIMARY2
 - COLOR_THEME_PRIMARY3
 - COLOR_THEME_SECONDARY1
 - COLOR_THEME_SECONDARY2
 - COLOR_THEME_SECONDARY3
 - COLOR_THEME_FOCUS
 - COLOR_THEME_EDIT
 - COLOR_THEME_ACTIVE
 - COLOR_THEME_WARNING
 - COLOR_THEME_DISABLED
 - CUSTOM_COLOR

### Deprecated indexed colors
These are included for backward compatibility of scripts, and they are mapped to the above new indexed colors as follows:
 - ALARM_COLOR -> COLOR_THEME_WARNING
 - BARGRAPH_BGCOLOR -> COLOR_THEME_SECONDARY3
 - BARGRAPH1_COLOR -> COLOR_THEME_SECONDARY1
 - BARGRAPH2_COLOR -> COLOR_THEME_SECONDARY2
 - CURVE_AXIS_COLOR -> COLOR_THEME_SECONDARY2
 - CURVE_COLOR -> COLOR_THEME_SECONDARY1
 - CURVE_CURSOR_COLOR -> COLOR_THEME_WARNING
 - HEADER_BGCOLOR -> COLOR_THEME_FOCUS
 - HEADER_COLOR -> COLOR_THEME_SECONDARY1
 - HEADER_CURRENT_BGCOLOR -> COLOR_THEME_FOCUS
 - HEADER_ICON_BGCOLOR -> COLOR_THEME_SECONDARY1
 - LINE_COLOR -> COLOR_THEME_PRIMARY3
 - MAINVIEW_GRAPHICS_COLOR -> COLOR_THEME_SECONDARY1
 - MAINVIEW_PANES_COLOR -> COLOR_THEME_PRIMARY2
 - MENU_TITLE_BGCOLOR -> COLOR_THEME_SECONDARY1
 - MENU_TITLE_COLOR -> COLOR_THEME_PRIMARY2
 - MENU_TITLE_DISABLE_COLOR -> COLOR_THEME_PRIMARY3
 - OVERLAY_COLOR -> COLOR_THEME_PRIMARY1
 - SCROLLBOX_COLOR -> COLOR_THEME_SECONDARY3
 - TEXT_BGCOLOR -> COLOR_THEME_SECONDARY3
 - TEXT_COLOR -> COLOR_THEME_SECONDARY1
 - TEXT_DISABLE_COLOR -> COLOR_THEME_DISABLED
 - TEXT_INVERTED_BGCOLOR -> COLOR_THEME_FOCUS
 - TEXT_INVERTED_COLOR -> COLOR_THEME_PRIMARY2
 - TITLE_BGCOLOR -> COLOR_THEME_SECONDARY1
 - TRIM_BGCOLOR -> COLOR_THEME_FOCUS
 - TRIM_SHADOW_COLOR -> COLOR_THEME_PRIMARY1
 - WARNING_COLOR -> COLOR_THEME_WARNING

### Literal colors
These are constants and cannot be changed:
 - BLACK
 - WHITE
 - LIGHTWHITE
 - YELLOW
 - BLUE
 - DARKBLUE
 - GREY
 - DARKGREY
 - LIGHTGREY
 - RED
 - DARKRED
 - GREEN
 - DARKGREEN
 - LIGHTBROWN
 - DARKBROWN
 - BRIGHTGREEN
 - ORANGE

### Using the new colors
The flags have been modified so they can either hold an indexed color or a RGB color. This means that any of the above colors can be used interchangeably for drawing function flags and 2nd argument for lcd.setColor(). 
Only the indexed colors can be used as the first argument to lcd.setColor. lcd.getColor() will return a color flag holding the RGB value. So if you want to store the RGB value of e.g. CUSTOM_COLOR before changing it, then you can do the following:
```
CUSTOM_COLOR = ORANGE
lcd.drawText(x, y, "Look, I am orange", CUSTOM_COLOR)
color = lcd.getColor(CUSTOM_COLOR)
CUSTOM_COLOR = lcd.RGB(255, 150, 200) 
y = y + 30
lcd.drawText(x, y, "Look, I am pink", CUSTOM_COLOR)
y = y + 30
lcd.drawText(x, y, "But I am still orange", color)
```
Of course, it would be easier to just use:
```
lcd.drawText(x, y, "Look, I am orange", ORANGE)
y = y + 30
lcd.drawText(x, y, "Look, I am pink", lcd.RGB(255, 150, 200))
y = y + 30
lcd.drawText(x, y, "But I am still orange", ORANGE)
```

**Comment by raphaelcoeffic** [comment]
@jfrickmann your libopenui PR has been merged today, so you should be able to make your PR have the sub-module pointer changed ;-)

**Comment by jfrickmann** [comment]
> @jfrickmann your libopenui PR has been merged today, so you should be able to make your PR have the sub-module pointer changed ;-)

I have now updated libopenui to the current master, but it still complains about conflicting files. I don't know why?
.git/modules/libopenui/refs/heads/master is 5c708913e7e2fe370c61e1b1cc13df0a4003501d

**Comment by raphaelcoeffic** [comment]
> > @jfrickmann your libopenui PR has been merged today, so you should be able to make your PR have the sub-module pointer changed ;-)
> 
> I have now updated libopenui to the current master, but it still complains about conflicting files. I don't know why?
> .git/modules/libopenui/refs/heads/master is 5c708913e7e2fe370c61e1b1cc13df0a4003501d

I did a rebase + force push. That should fix it.

**Comment by jfrickmann** [comment]
> I did a rebase + force push. That should fix it.
Yeah it worked 😄  🥇

**Comment by raphaelcoeffic** [comment]
@jfrickmann merged :-) Please be prepared for required fixes in case folks start complaining 😅

**Comment by JimB40** [comment]
So great. Should be done like that long ago :) Chapeau bas @jfrickmann 

1. What you say about equalizing color constants naming?
CUSTOM_COLOR -> COLOR_CUSTOM
BLACK -> COLOR_BLACK
WHITE -> COLOR_WHITE
LIGHTWHITE -> COLOR_LIGTHTWHITE
YELLOW -> COLOR_YELLOW
etc.
Think once it's done it will be much more easier to maintain both C++ and LUA code

**Comment by jfrickmann** [comment]
> @jfrickmann merged :-) Please be prepared for required fixes in case folks start complaining 😅

I will do my best! Better bring my laptop when I go over to see my parents in Denmark next week 😉

**Comment by jfrickmann** [comment]
> So great. Should be done like that long ago :) Chapeau bas @jfrickmann
> 
> 1. What you say about equalizing color constants naming?
>    CUSTOM_COLOR -> COLOR_CUSTOM
>    BLACK -> COLOR_BLACK
>    WHITE -> COLOR_WHITE
>    LIGHTWHITE -> COLOR_LIGTHTWHITE
>    YELLOW -> COLOR_YELLOW
>    etc.
>    Think once it's done it will be much more easier to maintain both C++ and LUA code

Thanks Robert 😄 

For the sake of backward compatibility, I think that it is best to keep the literal color names as is.

Are we going to see a working version of your color picker soon? 😎

**Comment by JimB40** [comment]
> For the sake of backward compatibility, I think that it is best to keep the literal color names as is.
Mapping? You mapped OTX constants anyway. I tell you future generations will thank you :)

> Are we going to see a working version of your color picker soon? 😎
It is working just colors are not changed in system :)

We talked on Discord about accessing Constants in LUA.
What I'd like is to have posibility to evaluate string with constant name into actual constant pointer (or whatever it is) in lcd.setColor() function 

Example:
t = {}
t[1] = { cName = "COLOR_THEME_PRIMARY1",   cValue = 0 }, 
t[2] = { cName = "COLOR_THEME_PRIMARY2",  cValue = 65525 }, 
lcd.setColor( t[1].cName, t[1].cValue )

Is that possible anyhow? 
Otherwise I have to hardcode those constant names into THEMER (so change LUA code every time we change any name in C++)

**Comment by jfrickmann** [comment]
> > Are we going to see a working version of your color picker soon? 😎
> 
> It is working just colors are not changed in system :)
> 
> We talked on Discord about accessing Constants in LUA.
> What I'd like is to have posibility to evaluate string with constant name into actual constant pointer (or whatever it is) in lcd.setColor() function
> 
> Example:
> t = {}
> t[1] = { cName = "COLOR_THEME_PRIMARY1", cValue = 0 },
> t[2] = { cName = "COLOR_THEME_PRIMARY2", cValue = 65525 },
> lcd.setColor( t[1].cName, t[1].cValue )
> 
> Is that possible anyhow?
> Otherwise I have to hardcode those constant names into THEMER (so change LUA code every time we change any name in C++)

Yes! The way to do it is:
```
t = { }
t[1] = { name = "COLOR_THEME_PRIMARY1", index = COLOR_THEME_PRIMARY1, red = 0,  green = 0, blue = 0 },
t[2] = { name = "COLOR_THEME_PRIMARY2", index = COLOR_THEME_PRIMARY2, red = 255, green = 255, blue = 21 },
-- etc.

for i, tt in ipairs(t) do
  lcd.setColor(tt.index, lcd.RGB( tt.red, tt.blue, tt.green))
end
```

**Comment by jfrickmann** [comment]
@JimB40 I found a way to do it using the string and the _ENV environment table!
```
t = { }
t[1] = { name = "COLOR_THEME_PRIMARY1", red = 0,  green = 0, blue = 0 },
t[2] = { name = "COLOR_THEME_PRIMARY2", red = 255, green = 255, blue = 21 },
-- etc.

for i, tt in ipairs(t) do
  lcd.setColor(_ENV[tt.name], lcd.RGB( tt.red, tt.green, tt.blue))
end
```

**Comment by JimB40** [comment]
Great so I can _scan ENV for "COLOR_THEME*" vars and make Themer future proof :)

**Comment by jfrickmann** [comment]
He he, "future proof" is oldest IT myth 😀

**Comment by JimB40** [comment]
So if you can implement 
CUSTOM_COLOR -> COLOR_FIX_CUSTOM
BLACK -> COLOR_FIX_BLACK
etc
We can scan _ENV for "COLOR_FIX_*" and get all predefined in EdgeTX colors :)

**Comment by jfrickmann** [comment]
Robert,

You cannot do wildcard search on Lua tables. I tried if you could iterate over _ENV with:
```
for name, value in pairs(_ENV.Bitmap) do
  print(name .. " = " .. tostring(value))
end
```
but that did not work. It only returned the name of the current function and a couple of global variables declared elsewhere. This is probably due to the fact that these constants are added to the global environment as read-only values.

Besides, I don't think that you need a list of literal colors (BLACK, RED etc.), as you cannot change them anyway. These are constants returning a RGB565 value; not indexed colors. The only colors that you can change are the 11 theme colors and CUSTOM_COLOR.

**Pull request merged**
