### PR TITLE
touch interface support for time_edit. Take2.

### PR DESCRIPTION
**Pull request by eshifri**
This brings up virtual keyboard (NV14) for temer edit.
Also simplifies the code.

### CODE REVIEW

**Comment by eshifri** [comment]
You can call it "enhancement", but NV14 does not work without it. :-)

**Comment by raphaelcoeffic** [comment]
Ok gents, we need some tests on other targets to make sure it does not break anything else ;-)

**Comment by eshifri** [comment]
It works (for me :-) ) on NV14 and RM TX16S

**Comment by pfeerick** [comment]
I'll test it later today on the TX16S also. And it changing from not working to working on the NV14 would be considered an enhancement, no? 😆

**Comment by pfeerick** [comment]
Am I correct in thinking on the TX16S the only change in behaviour would be that before if you touched a time field multiple times it would only highlight it, and now it highlights it on the first press, and makes it 'active for editing' if you press it a second time (thus ready for the on-screen keyboard)? If so, it LGTM.

**Comment by eshifri** [comment]
I do not think there is a visible change of behavior on TX16S, since virtual keyboard is not available.
The first touch switches it into "editable mode" and you can use rotary encoder for editing (as before).
On NV14 it brings on the virtual keyboard. I would think the same will happen on TX16S if VK is enabled.

**Comment by pfeerick** [comment]
On the TX16S the behavior to this PR was that pressing multiple times on a time field only highlights the field (i.e. turns blue) - it does not switch it to 'editable mode'. With the PR, first press highlights (turns blue), second press switches to 'editable' mode (turns green). Side effect is you can't touch again to get out of the field, but when the touch keyboard is enabled on the TX16s and co, I don't think that will be a problem.

**Pull request merged**
