### PR TITLE
feat(bw): add 'Set Screen' special function to B&W radios

### LINKED ISSUE #3983: We dont have "Set Main Screen" function in black and white yet
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

As a user of black and white monochrome screen, we may need to bring the telemetry screen to active using special function. 
In comparison to the color LCD screen, that have ability to "Set Main Screen", currently in 2.9 RC 2, we dont have similar ability. 
https://www.youtube.com/watch?v=5a-sNYZ-7uc&t=12s 

### Describe the solution you'd like

Implement new feature in black and white radio, that have similar ability like "Set Main Screen" in color radio. We may name it "Set Tele Screen", since we dont have customizable main screen. Remember, we only have some preset main screen in black and white and it's not editable. Instead, in black and white, telemetry screen is customizable, and also it has multiple pages. Please make it happen, so the black and white become more equivalent in terms of functionality, compared to the color radio.  

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3983 

The parameter for the 'Set Screen' function can be from 0 to 4.
- when set from 1 - 4 it will load the corresponding telemetry screen (if it is set up).
- when set to 0 it will reload the normal main view.

Needs translation (must be kept short to fit on B&W screen):
```C
#define TR_SF_SET_TELEMSCREEN          "Set Screen"
```

### CODE REVIEW

**Comment by 3djc** [comment]
Repeat filed is enabled ?

**Comment by philmoz** [comment]
> Repeat filed is enabled ?

Yes, same as color implementation.

I assume this is so you can have !1x (not activated on startup).

**Comment by 3djc** [comment]
What does it do then ? Doesn't seem obvious to me

**Comment by philmoz** [comment]
> What does it do then ? Doesn't seem obvious to me

You mean the repeat field? It works the same as for any other SF/GF.

**Comment by 3djc** [comment]
So if you do "ON Set screen 1 1 enabled", you basicaly looked yourself out ?

**Comment by philmoz** [comment]
> So if you do "ON Set screen 1 1 enabled", you basicaly looked yourself out ?

Not locked out entirely - you would still have 1 second after pressing RTN to press MDL and fix it in the model setup.

It might be possible to limit the repeat to just !1x and 1x - will need to investigate.

**Comment by ajjjjjjjj** [comment]
PL
```#define TR_SF_SET_TELEMSCREEN          "UstawEkran"```

**Comment by ulfhedlund** [comment]
SE
#define TR_SF_SET_TELEMSCREEN          "Sätt skärm"

**Comment by pfeerick** [comment]
Can we get some translations for this please 😃 Will be merged in seven days or when translations complete, whichever comes first. 

Please keep it short since it is only needed for B&W screens. Is a new SF that will allow you to trigger a telemetry screen to be shown. See initial comment for more details. 

```
#define TR_SF_SET_TELEMSCREEN          "Set Screen"
```
- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes / @froqstar DE
- [ ] @Pat6874 FR
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] ulfhedlund SE
- [ ] ajjjjjjjj PL
- [ ] @zandorsp PT
- [ ] @kobakirill RU

**Comment by robustini** [comment]
IT
#define TR_SF_SET_TELEMSCREEN          "Setta Schermo"

**Comment by froqstar** [comment]
DE
`#define TR_SF_SET_TELEMSCREEN "Tel.seite setzen"`

**Comment by philmoz** [comment]
> DE `#define TR_SF_SET_TELEMSCREEN "Tel.seite setzen"`

This is too long - needs to fit in space shown in screenshot above.

**Comment by froqstar** [comment]
Fixed?

**Comment by Pat6874** [comment]
FR:
#define TR_SF_SET_TELEMSCREEN "Conf. écran"

Le 10 oct. 2024, 03:55, à 03:55, Peter Feerick ***@***.***> a écrit:

**Comment by ajjjjjjjj** [comment]
PL updated
```#define TR_SF_SET_TELEMSCREEN          "Ustaw ekran"```

**Comment by zandorsp** [comment]
PT
#define TR_SF_SET_TELEMSCREEN "Def Tela"

**Comment by HThuren** [comment]
DA
#define TR_SF_SET_TELEMSCREEN "Vis skærm"

**Comment by Eldenroot** [comment]
CZ - is it fine for text lenght?

#define TR_SF_SET_TELEMSCREEN          "Nast obrazovku"

**Comment by zyren** [comment]
CN
********************
```c
#define TR_SF_SET_TELEMSCREEN          "设置主屏"
```

TW
********************
```c
#define TR_SF_SET_TELEMSCREEN          "設置主屏"
```

**Comment by ulfhedlund** [comment]
If it is not too late I would like to change the Swedish translation. Otherwise I'll create a separate PR later, no problem.

SE
#define TR_SF_SET_TELEMSCREEN "Visa skärm"

**Comment by pfeerick** [comment]
We're at day seven and not merged, so you're safe ;)

**Comment by pfeerick** [comment]
Any chance of that being one letter shorter? And are you interested in translating future stuff for Spanish?

image

**Comment by Luznatural** [comment]
Yes to both questions:
ES
#define TR_SF_SET_TELEMSCREEN "Ajus. pantalla"

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_SF_SET_TELEMSCREEN "画面設定"

We are very sorry for the delay in confirmation.

**Comment by pfeerick** [comment]
Better late than never! Much appreciated! :)

**Comment by kobakirill** [comment]
> Can we get some translations for this please 😃 Will be merged in seven days or when translations complete, whichever comes first.
> 
> Please keep it short since it is only needed for B&W screens. Is a new SF that will allow you to trigger a telemetry screen to be shown. See initial comment for more details.
> 
> ```
> #define TR_SF_SET_TELEMSCREEN          "Set Screen"
> ```
> 
> * [x]  @zyren CN / TW
> * [x]  @Eldenroot CZ
> * [x]  @HThuren DA
> * [x]  @ParkerEde / @TheIsotopes / @froqstar DE
> * [x]  @Pat6874 FR
> * [x]  @robustini IT
> * [ ]  @ToshihiroMakuuchi JP
> * [x]  ulfhedlund SE
> * [x]  ajjjjjjjj PL
> * [x]  @zandorsp PT
> * [ ]  @kobakirill RU
> 
> The translation strings need to fit in this space: screenshot_t20v2_24-10-10_16-54-14

#define TR_SF_SET_TELEMSCREEN          "Устан экран"

**Comment by Luznatural** [comment]
Good morning,

Although not in the list:

Translation for ES (Spanish)

#define TR_SF_SET_TELEMSCREEN "Ajust. Pantalla"

Warm regards

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
