### PR TITLE
Prevent TF lock

### PR DESCRIPTION
**Pull request by 3djc**
Some background here : https://forum.sparkfun.com/viewtopic.php?t=31759
Succesfully tested by Radiomaster

### CODE REVIEW

**Comment by Eldenroot** [comment]
Doea it affect only Radiomaster? Or Taranis xd+2019 is also affected? I am asking because my Taranis displays no sd card error message so no boot up. It starter after flashing edgetx

**Comment by raphaelcoeffic** [comment]
@Eldenroot from what I know, this is more related to the card itself rather than anything else.

**Comment by pfeerick** [comment]
I've not been unlucky enough to get this on the X9D+2019 yet (caveat. it gathers a fair amount of dust now that the TX16S is on the block), but I also still use the 2GB card that came with it - smaller cards are less prone to this issue on affected radios (i.e. those using SPI interface), but it is still just a matter of random luck if you ask me! 😆

**Review by pfeerick — APPROVED** [review]
No problems here either with repeated cycles on NV14 and TX16S as two candidate radios using SDIO...

**Pull request merged**
