### PR TITLE
Jumper TPro V2

### PR DESCRIPTION
**Pull request by 3djc**
This brings support for Jumper T-Pro V2 (F4 processor, more switches, Oled screen)

This also brings two additional switches (pushing down the trim 'sticks') to the v1 Jumper T-Pro

This PR superseeds #3554

image

### CODE REVIEW

**Comment by black-funny-cat** [comment]
I have a problem with timers. Timer modes TH% and other throttle-activated timers. In my jumper T-Pro V2 trigger to activate the timer isn't throttle, but elevator (right vertical stick, mode 2)

**Comment by 3djc** [comment]
@black-funny-cat , please use this
[T20-PROD-29-06-23.zip](https://github.com/EdgeTX/edgetx/files/11902823/T20-PROD-29-06-23.zip)

**Comment by black-funny-cat** [comment]
It works! Thank you very much 👍

**Comment by black-funny-cat** [comment]
execuse me, i have one more probleem. "discover new" button (from telemetry tab) disappeared. 
[screen-2022-06-29-210544.zip](https://github.com/EdgeTX/edgetx/files/11908056/screen-2022-06-29-210544.zip)

**Comment by 3djc** [comment]
Unfortunatly not specific to this radio  : https://github.com/EdgeTX/edgetx/pull/3734

**Comment by vchirikov** [comment]
@3djc with this firmware my stick names in `INPUTS` setup page are messed up. When I move UP-DOWN the left stick in `Source` field I see `Ele` instead of `Thr`. On the stock firmware was Thr. Could you help me and say how and where I can change `Source` names for sticks?

**Comment by MKaiserW** [comment]
> @black-funny-cat , please use this [TPROV2-PROD-29-06-23.zip](https://github.com/EdgeTX/edgetx/files/11902830/TPROV2-PROD-29-06-23.zip)

Flashing this bios leaves me with only multi for my internal RF module. Is there a internal ELRS (CFRS) version? I have really messed up my controller and it feels like nothing im doing is bringing it back to working order.

**Comment by pfeerick** [comment]
Go to RADIO -> HARDWARE and change the Internal RF from MULTI to CRSF (for ELRS).

**Comment by MKaiserW** [comment]
Yeah unfortunately that isn't an option, only off and MULTI.

**Comment by pfeerick** [comment]
OFF isn't an option, so you're in the wrong place. RADIO/SYS (not MODEL) ... long press the top button on the left side. Then use the second button to navigate to the HARDWARE page. Then use the roller on the right side to scroll down to Internal RF, and change the Type from MULTI to CRSF. When you go back to the MODEL settings, you will then have OFF and CRSF as your options.

**Comment by 3djc** [comment]
Latest production firmware

[TPROV2-PROD-09-07-23.zip](https://github.com/EdgeTX/edgetx/files/12060947/TPROV2-PROD-09-07-23.zip)

**Comment by smartinick** [comment]
> Latest production firmware
> 
> [TPROV2-PROD-09-07-23.zip](https://github.com/EdgeTX/edgetx/files/12060947/TPROV2-PROD-09-07-23.zip)

Should this already Work with companion?

3554 mentiones 2631 ist required, 2631 is merged, but companion 2.8.4 still gives me the radio.yml parsing error.

So is it my fault, or do we e.g. wait for a newer companion version?

**Comment by 3djc** [comment]
No, companion support is not available yet. Support will come in later nightly and will be in 2.10

**Comment by smartinick** [comment]
> No, companion support is not available yet. Support will come in later nightly and will be in 2.10

Great, Thanks for clarification!

And Thanks for the .zip above, upgrade in the field worked seamlessly!

**Comment by YardoDEVS** [comment]
Hi, here my tx from the first batch lose the rtc time from powered to power off state. I have tried to do the fix of doing the bridge between the two pins at the mcu and the last version of @3djc that I'm using is giving me 0.50 volts in the rtc battery read on the hardware tab of edgeTX... So the question is... Did I have failed doing the fix or should I change the battery of the RTC bay? Thanks in advance

**Comment by 3djc** [comment]
It depends when the fix was applied. The battery might have been already depleted. It is easy to check the fix (but needs an rtc bat above 2v): set the correct time, turn radio off, turn on radio after 5 minutes : time is ok ? Fix is ok. Time is 5min late because it did not increment while off: fix is not correct

**Comment by YardoDEVS** [comment]
> It depends when the fix was applied. The battery might have been already depleted. It is easy to check the fix (but needs an rtc bat above 2v): set the correct time, turn radio off, turn on radio after 5 minutes : time is ok ? Fix is ok. Time is 5min late because it did not increment while off: fix is not correct

Thanks @3djc as you can see I am a complete newbie to EdgeTX and I would like to know one thing... If I have already changed the hall magnetic sensors (the most important factory failure I think) what characteristics would it affect if the transmitter does not have the RTC working correctly? Now that I have changed the hall magnetic sensors for the ones Jumper Support sent me can I fly a drone without problems? The gimbals drift is supposed to be solved with the new batch fix replacement then... In which characteristics can not having correctly executed the welding operation affect me? The TX will operate normally except that it will only not show the right time on the screen? Or will it have other consequences for the tx normal use? Thanks in advance

**Comment by 3djc** [comment]
No other conscequances than messing up radio time (which messes up radio based logs) and draining the battery

**Comment by YardoDEVS** [comment]
> No other conscequances than messing up radio time (which messes up radio based logs) and draining the battery

Draining the 18650 batteries (the main battery I mean) or draining the RTC battery? If it's the main battery its a real bad deal. I really don't need any log... Thanks so much for all the info you give to the newbies like me @3djc

**Comment by 3djc** [comment]
rtc

**Comment by YardoDEVS** [comment]
> rtc

Thank you so much, I will go then with your latest firmware and I will update ELRS firm too

**Comment by YardoDEVS** [comment]
@3djc one more question. I'm upgrading to the last firmware of ELRS, but when I'm updating throw the wifi AP website that creates the tx, I get an error saying target version is AION 2.4GHZ and the firm that I'm sending is an ESP32 version... The last version of the v3 elrs for t-pro v2 is now ESP32 2.4GHZ firm?

**Comment by 3djc** [comment]
Really a question for [https://discord.com/invite/dS6ReFY]

**Comment by Blackh0le57** [comment]
Hi, I managed to flash the TPROV2-PROD-09-07-23.zip to my controller and none of the analogue outputs work, they are all stuck in one state and it is not just visual because when I tried it in a flight sim it was stuck in the top right corner as well. I did previously flash the v2.8.5 from edgetx buddy not knowing that it wasn't supported, and then flash the latest one. Any ideas on how to fix this?

thumbnail_IMG_8026

**Comment by pfeerick** [comment]
Have you tried stick calibration? SYS/RADIO (long press the top button of
the three on the right grip) -> HARDWARE -> Calibration

**Comment by Blackh0le57** [comment]
Thanks so much!!! 
I had no idea you could do that and it worked, any ideas on the scroll wheel things because these are also stuck. If not it is fine because they are not very important for me

**Comment by 3djc** [comment]
If you are talking about the sliders, you deleted the declarations with 2.8.5. Back to SYS/hardware and set p1 and p2 to pot w center. Re run calibration, making sure you start with those middle and move them during calib

**Comment by Blackh0le57** [comment]
That worked! Thank you both, I really appreciate people like you

**Comment by pushcommit** [comment]
My telemetry sensor discovery on my Jumper T-Pro ELRS is basically non-functional. 

The "discover new sensors" is never shown. Instead there is just a weird empty line for Sensor 1 which can not be selected.

Is it just my version?

IMG_2049
IMG_2050

**Pull request merged**
