### PR TITLE
Check MCU type at start

### PR DESCRIPTION
**Pull request by 3djc**
Given the increased pressure on MCU sourcing, it becomes more likely that similar, or very similar radio get available with different MCU. This is already the case with TX12 and TX12-MK2, it will become more with  upcoming T-Lite with F4 MCU.

On F2 hardware, F4 firmware do not start, but on F4 hardware, an F2 firmware starts and can appears to be running, when all timers and such are completely off, which can create great confusion.

This prevent running the firmware on MCU they where not compiled for. It includes all currently used MCU, as you never know whats comming

### CODE REVIEW

**Comment by ggoraa** [comment]
I would've made the text "Bad MCU" instead of "WRONG MCU" imo

**Comment by ggoraa** [comment]
Good point! But at least I would've liked it without CAPS, so that instead of "WRONG MCU" it's "Wrong MCU"

**Comment by pfeerick** [comment]
Don't you start... the translators are going to be after me soon enough as it is insisting that it needs to be translated! 🤪

**Comment by 3djc** [comment]
I have choosen those terms to allow easier searching for solution (also why I haven't made it translatable). Edgetx wrong firmware probably leads to too much answers, edgetx wrong mcu far far less.

**Comment by pfeerick** [comment]
Exactly. And if we have a FAQ entry for that up pretty much straight away... there is a good chance it will come up as pretty much the first result if anyone searches for it...

**Pull request merged**
