### PR TITLE
feat(radio): Logical Switch list display UI

### PR DESCRIPTION
**Pull request by philmoz**
Changes:
- Change color UI to show V1, V2 and AND switches in bold when they are on (to match B&W UI).
- Show 'Stcky' label for sticky switches in bold when the switch sticky state is ON.

Sticky LS with an AND switch can be off; yet still have the 'sticky' state set to on.
This can make setting up a LS somewhat confusing.
This change aims to show the 'sticky' state in addition to the LS switch state.

screenshot_tx16s_24-08-01_09-08-09
screenshot_tx16s_24-08-01_09-08-19

### CODE REVIEW

**Comment by pfeerick** [comment]
Yes, indeed... the set/reset sticky could be in the set position, but if AND not active, results in the line not being active... nice thinking!

**Comment by pfeerick** [comment]
Hm.. just thinking about this a bit more... this is relevant for **any** logical switch with AND, not just the sticky (and edge). What are your thoughts on extending this to all LS? e.g. a  `a>x Thr 0 SDdn` LS doesn't (on either UI, prior to this PR) show that Thr > 0 condition has been met (by bein bold) yet SD is up, so the line not true yet.

**Comment by philmoz** [comment]
Unfortunately the other functions don't have a stored state, they are re-calculated each time.
This would require a way to re-calculate the switch state while ignoring the AND switch.

**Comment by pfeerick** [comment]
Ok, so something to thing about in the future then maybe... i.e. v3 UI stuff ;)

**Comment by 3djc** [comment]
Quite nice, we just need to keep in mind that mixer runs much faster than UI anyway, so you can only display the state of 'slow' SF

**Pull request merged**
