### PR TITLE
Changes after using QtLinguist (Danish)

### PR DESCRIPTION
**Pull request by HThuren**
After instructions in #2685 now changed Danish translation

### CODE REVIEW

**Comment by HThuren** [comment]
@pfeerick, is it possible this PR will be merged into EdgeTx 2.8 ?

**Comment by pfeerick** [comment]
I'm afraid not - it will have to go into main, and then I'll need to rebase https://github.com/EdgeTX/edgetx/pull/2685 as there are conflicts with that, and then finish working on the changes to the translation system there.

**Comment by HThuren** [comment]
> I'm afraid not - it will have to go into main, and then I'll need to rebase #2685 as there are conflicts with that, and then finish working on the changes to the translation system there.

ok, anything I can help with ? otherwise I'll wait :-)

**Comment by HThuren** [comment]
Hi @pfeerick, maybe reconsider, since the danish changes here not really depends of #2685, but are a result of using QtLinguist. There are no changes acording to #2685 
and I am afraid the changes here get too much out of sync with other PRs

**Comment by pfeerick** [comment]
No, that is not the case. Otherwise, I would have been able to just merge this into the `etx28-qtlinguist-release` branch for https://github.com/EdgeTX/edgetx/pull/2685 - but I can't as it had a merge conflict. Which is why I said
> it **(this PR)** will have to go into main, and **then** I'll need to rebase https://github.com/EdgeTX/edgetx/pull/2685 as there are conflicts with that

In other words, it will go into main (which is for 2.9), but I was hoping to not make any major changes to the 2.8 translation base. However, given it seems like 2.9 release date is going to be pushed out, it might end up in 2.8.x as well.

**Comment by HThuren** [comment]
Ok, sorry I cant help with the rebase, but very good the translation end up in 2.8, since there where many good changes from the QtLinguist run and translation process. I try to be patient :-)

**Comment by HThuren** [comment]
Thank you for this christimas present :-)

**Pull request merged**
