### PR TITLE
Color options for Lua widget get translated to Lua color flags

### PR DESCRIPTION
**Pull request by jfrickmann**
To support new color encoding in Lua widgets.
@pfeerick please check if this solved the color option problem for Lua widgets!

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
Timer2 colour changes now work. Counter doesn't, but that is a (already known) fault in the script, not with this PR.

**Review by raphaelcoeffic — APPROVED** [review]
Looks ok to me. I did not test though.

**Comment by pfeerick** [comment]
This PR fixes exactly the issue it says it does, but also opens the door for next PR 😆 ... and I was so close to pressing Merge without saying anything more!

On NV14 and TX16S,  using Timer 2 as the readily available example (ShowItAll also suffers from this)... set a custom widget colour, and then restart the transmitter... it won't use those "custom" options colours until you go back in the widget options - nothing more - just open and close the options panel.

**Comment by jfrickmann** [comment]
> On NV14 and TX16S, using Timer 2 as the readily available example (ShowItAll also suffers from this)... set a custom widget colour, and then restart the transmitter... it won't use those "custom" options colours until you go back in the widget options - nothing more - just open and close the options panel.

I know exactly why - I forgot to translate the color option for the create() function. I will get that fixed!

**Comment by jfrickmann** [comment]
Please see #649!

**Pull request merged**
