### PR TITLE
More layouts

### PR DESCRIPTION
**Pull request by pfeerick**
Per #372, implemented 1+3, 2+3 and 2x3 layouts. A couple more may be added, more suitable for the NV14.

### CODE REVIEW

**Comment by pfeerick** [comment]
Just finished trying this out on the NV14/TX16S after having been exclusively simulated... and all seems to be working... enough of Roberts wishlist has been implemented for this round.

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by JimB40** [comment]
Still we have this naming/layout 'issue' with NV14 vertical slicing.

So @richardclli implemented this 3 area layout. 3 rows but lower two are half-height of top one.
If we start to implement it in vertical it will be naming armagedon.
Maybe NV14 should use NV14 specific layouts. While this vertical layout (like the one @richardclli introduced) can be used on horizontal LCDs, any of 2 column layouts from Horizontal is practically not usable on Vertical.

What u think?

**Comment by richardclli** [comment]
Maybe we can have a list of suitable layouts definition according to the screen size/orientation, etc.

**Comment by pfeerick** [comment]
Yeah, I was starting to think the same thing, also for the masks, as when you think of it, the masks shown are for the horizontal screens, not the vertical ones, so don't look right for those screens.

**Pull request merged**
