### PR TITLE
Check FM Trims translateable for color radios

### LINKED ISSUE #2797: Check FM Trims - inconsistent text
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Check FM Trims button is not consistent between BW and color radios. For BW radios the button is translateable and the current flight mode is included in the button name, whereas for color LCD radios the button text "Check FM Trims" is hard coded and hence neither translateable nor includes the current flight mode. 

### Describe the solution you'd like

IMO the behavior for BW radios is preferable, i.e. the Check FM Trims button should be translateable and include the current flight mode.

### Describe alternatives you've considered

1. all firmware work the same way as for BW radios
2. color LCD radios should at least have a "Check FM Trims" button text that can be translated

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ulfhedlund**
Fixes #2797

Summary of changes:
Added translation for Check FM Trims button for color radios and separated the button text string for BW and color radios in the firmware translation files.

### CODE REVIEW

**Comment by ulfhedlund** [comment]
Can't remember who the translators are...

In any case, I have added a text string for color radios that contains the same text as for the BW, for all languages.
If a translators would like some other wording, you are welcome to let me know and I can change before this is merged.

**Comment by pfeerick** [comment]
This is the list atm

Please see above comment:
@ParkerEde DE
~~@ulfhedlund SE~~
@Eldenroot CZ
@robustini IT
@zyren CN / TW
@ajjjjjjjj PL
@ToshihiroMakuuchi JP

**Comment by robustini** [comment]
IT already ok.

**Comment by ulfhedlund** [comment]
@HThuren for DA, ok?

**Comment by ajjjjjjjj** [comment]
PL is ok.

**Comment by zyren** [comment]
***************************************************************************************
CN Translation
***************************************************************************************
#if defined(COLORLCD)
  #define TR_TRIMS2OFFSETS             "将当前微调量保存至中点"
#else
  #define TR_TRIMS2OFFSETS             "\006微调存至中点"
#endif
**************************************************************************************
**************************************************************************************
TW Translation
**************************************************************************************
#if defined(COLORLCD)
  #define TR_TRIMS2OFFSETS             "將當前微調量保存至中點"
#else
  #define TR_TRIMS2OFFSETS             "\006微調存至中點"
#endif
**************************************************************************************

**Comment by ParkerEde** [comment]
DE
#if defined(COLORLCD)
  #define TR_CHECKTRIMS                "Prüfe Flugphasen-Trimmung"
#else
  #define TR_CHECKTRIMS                CENTER"\006Prüfe\012Trimmung"
#endif

**Comment by Eldenroot** [comment]
For CZ I need to check, I think that for eng it could be better forncolor lcd, not? I mean longer text

**Comment by ToshihiroMakuuchi** [comment]
JP Translation

#if defined(COLORLCD)
#define TR_CHECKTRIMS "現在の飛行モードのトリムをチェック"
#else
#define TR_CHECKTRIMS "\006チェック\012トリム"
#endif

**Comment by ulfhedlund** [comment]
> For CZ I need to check, I think that for eng it could be better forncolor lcd, not? I mean longer text

Yes, it could be something equivalent to "Check FM Trims" or as in Swedish "Kontrollera FM-trimmar". So something longer than "Kont. Trimy" would be fine. Let me know what you prefer.

**Comment by ToshihiroMakuuchi** [comment]
@ulfhedlund
I noticed that the CENTER string was missing in JP. Do you need this string?
Could you please fix it?

#define TR_CHECKTRIMS "\006チェック\012トリム" >>> #define TR_CHECKTRIMS CENTER "\006チェック\012トリム"

**Comment by Eldenroot** [comment]
#if defined(COLORLCD)
  #define TR_CHECKTRIMS                "Kontrolovat trimy"
#else
  #define TR_CHECKTRIMS                "\011Kont.\010Trimy"
#endif

**Comment by ulfhedlund** [comment]
@ToshihiroMakuuchi: As far as I can tell it makes no visible difference with our without the CENTER string but I now have added it in the jp.h.

**Comment by ulfhedlund** [comment]
> #if defined(COLORLCD) #define TR_CHECKTRIMS "Kontrolovat trimy" #else #define TR_CHECKTRIMS "\011Kont.\010Trimy" #endif

@Eldenroot: I updated the octal characters in TR_CHECKTRIMS to be in line with the other languages and it looks better in my opionion: #define TR_CHECKTRIMS "\006Kont.\012Trimy". If you want it changed back to let me know.

**Comment by ulfhedlund** [comment]
@pfeerick: I believe this is ready for merge as all requests from the translators have been taken care of.

**Comment by HThuren** [comment]
> @HThuren for DA, ok?

Yes, DA are quite well

**Comment by pfeerick** [comment]
> As far as I can tell it makes no visible difference with our without the CENTER string but I now have added it in the jp.h.

It would only change the B&W radios - the string is centred on the screen there IIRC.

**Review by pfeerick — APPROVED** [review]
LGTM on Zorro and TX16S, English only

**Pull request merged**
