### PR TITLE
chore(cpn): QtLinguist translation files refresh

### PR DESCRIPTION
**Pull request by pfeerick**
Revises line numbers for code and adds any missing "unfinished" translation strings

### CODE REVIEW

**Comment by mha1** [comment]
how did you that?

**Comment by ulfhedlund** [comment]
By using the Qt Linguist [lupdate](https://doc.qt.io/qt-6/linguist-lupdate.html) tool

**Comment by pfeerick** [comment]
Sorry, I forgot to reply to this yesterday. As Ulf said, using the lupdate tool. In my case, I run the below script. One of these days I'll knock up a github action to do it on repo...

```
@ECHO OFF

SET QTLINGUIST_LUPDATE="c:\tools\QtLinguist\bin\lupdate"
SET REPO_DIR="U:\home\pfeerick\repos\edgetx"
SET CPN_SRC_DIR="U:\home\pfeerick\repos\edgetx\companion\src"

for %%f in ("%CPN_SRC_DIR%\translations\*.ts") do (
    echo Processing "%%f"...
    %QTLINGUIST_LUPDATE% %CPN_SRC_DIR% -no-obsolete -ts "%%f"
)
```

**Comment by mha1** [comment]
So we don't really have to put meaningful line numbers in? Saves time.

**Pull request merged**
