### PR TITLE
refactor: USB HAL conversion + USB lib update

### PR DESCRIPTION
**Pull request by gagarinlg**
Summary of changes:
use current USB device driver lib from ST
convert USB code to HAL

### CODE REVIEW

**Comment by richardclli** [comment]
This will breaks PL18 PR, I think it should be rebased on top of pl18 branch and work out the pl18 specific changes as well.

**Comment by richardclli** [comment]
@gagarinlg This PR will fail the debug build (-D DEBUG), I tried with el18 target.

**Comment by pfeerick** [comment]
Sorry, #3846 created conflicts again. 😢

**Comment by gagarinlg** [comment]
🤬😤😭

**Comment by pfeerick** [comment]
Looks mostly trivial... includes changed in the same place,... if not, blame Raphael  😝 As far as whether this PR or #4105 goes first, I leave it for you and Richard to fight it out... 🤣 #4105 has been in the works for quite some time now, but this affects all radios so I'll sit on the fence for this one.

**Comment by gagarinlg** [comment]
I don't really care, on any case the PL18 files have to be updated

**Comment by pfeerick** [comment]
Testing USB Access via bootloader. Then USB Joystick, USB Storage (updating SOUNDS folder, which could often fail  if done on radio), USB VCI (when present) sequentially with no reboot between disconnects for each. 
- [x] X7 - No problems
- [ ] T20 - Unable to flash ELRS via VCP, tried recently nightly and that worked. Seems like serial just timed out.
- [ ] TX16 (MPM) - No response from VCP when I tried connecting via Putty. Nightly was fine. 
- [ ] EL18 - Lockup during copying sound pack files to radio about 90% in (has happened before, so not blaming this PR).  No response to VCP. Bootloader no display and lockup (which #4396 should resolve).

**Comment by gagarinlg** [comment]
@pfeerick would you be so kind to re-test? I fixed the USB-VCP issue
SD access looks also good

**Comment by pfeerick** [comment]
Repeat test:

- [x] X7 - Joystick, SD Storage, Bootloader Storage
- [x] T20 - Same as X7, USB VCP was successful this time.
- [x] TX16 (MPM) - Same as X7, Putty was able to connect to VCP
- [x] EL18 - Same as X7, RF module access for Flysky assistant and VCP via putty also working. 

I don't see any reason to not subject 2.10 users to this PR now that the VCP issue seems to be gone. Nothing else seems to be wrong. 🤞

**Comment by richardclli** [comment]
@pfeerick No!!!! PL18 and PL18EV breaks, You missed the testing on the PL18, it can compile but all USB function not working.  The radio can detect USB plugged in and change the logo (in bootloader), or popup the function choice (in firmware), but no USB devices are detected in the computer side.

> Repeat test:
> 
>     * [x]  X7 - Joystick, SD Storage, Bootloader Storage
> 
>     * [x]  T20 - Same as X7, USB VCP was successful this time.
> 
>     * [x]  TX16 (MPM) - Same as X7, Putty was able to connect to VCP
> 
>     * [x]  EL18 - Same as X7, RF module access for Flysky assistant and VCP via putty also working.
> 
> 
> I don't see any reason to not subject 2.10 users to this PR now that the VCP issue seems to be gone. Nothing else seems to be wrong. 🤞

**Comment by richardclli** [comment]
I finally know what happens and fixed it by the following PR, no need to worry anymore.

https://github.com/EdgeTX/edgetx/pull/4471

**Pull request merged**
