### PR TITLE
fix(telemetry): process DSM LIPO Cells Monitor sensor correctly

### LINKED ISSUE #4715: For SPEKTRUM telemetry, the sensor with 6 lipo cell provides wrong values for the last 5 cell voltages
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When the spektrum sensor (SRXL2) is filled with following data:
A6  80  16  21  3A   0   4  57   8  AE   D   5  11  5C  7F  FF  7F  FF  7F  FF  F4  DC

The first cell should be reported as 11.11V based on 0X04 and 0X57. This is the case. So cell1 is OK
The other cells are reported with following values
cel2=677.58            (instead of 22.22 based on 0X08 0XAE)
cel3=1344.05          (instead of 33.33)
cel4=2010.52          (instead of 44.44)
cel5=2949.11         (for this the value is 7FFF which means that the value is not provided)
cel6=3604.47        (for this the value is 7FFF which means that the value is not provided)

### Expected Behavior

Correct values for cell2...cell4; 
Cell5 and 6 should not be displayed (because the value is 0X7FFF = not provided)

### Steps To Reproduce

simulate the telemetry frame given above.

This has been tested with version 2.10.0 Rc1 Centurion

### Version

Other (Please specify below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by frankiearzu**
Fixes #4715

Summary of changes:

**Fix processing of message 0x3A:**

1. Create individual Cells Sensors (Cel1..Cel6)
2. Create Grouped "Cels" sensor who contains all the Cells.  This is compatible with FrSky, and can be used as the source to compute the Min/Max Cell.

**Fix Temperatures to have no decimals, otherwise they will not convert correctly between C/F.**

image
image

### CODE REVIEW

**Comment by pierrotm777** [comment]
Thanks you for your job :-)
Do i need to build a nightly firmware or can you build a firmware for a Tx16S please ?

**Comment by pierrotm777** [comment]
Sorry, i don't understand what is the PR page (too french :-).
Do you have a link ?
Thanks

**Comment by pierrotm777** [comment]
OOps PULL REQUEST ?

**Comment by pfeerick** [comment]
Sorry, yes, Pull Request. You are there/here already.

**Comment by pierrotm777** [comment]
Ok, i have found thanks

**Comment by frankiearzu** [comment]
@pfeerick don't merge it yet..    I think by fixing #4723 will allow to have temperatures using decimal places.
Looking at the code, many Telemetry protocols have Temperatures with Prec1, so better for do a fix that works for all (frsky, and other).   I can remove just the temperature override in this fix.

**Comment by frankiearzu** [comment]
@pfeerick DONE.. Checked in the fix for the temperature UNIT conversion in another PR.

**Pull request merged**
