### PR TITLE
Removed the call to update() when widget leaves fullscreen mode

### PR DESCRIPTION
**Pull request by jfrickmann**
As discussed on Discord with @pfeerick  and @lshems

### CODE REVIEW

**Comment by wimalopaan** [comment]
Just an idea (actually only have a vague application for this): we have a ctor-like function (init()), maybe it would be useful to have a dtor-like function (e.g. destroy()) ?

**Review by pfeerick — CHANGES_REQUESTED** [review]
This is *not* the `update()` you're looking for... this breaks the UI quite badly, as the widget no longer updates properly when coming out of full screen. 

It is overridden in `/radio/src/lua/widgets.cpp` at 256 for implementation at 406. I'm guessing perhaps that needs to know the widget is fullscreen and to return out instead of process?

**Comment by jfrickmann** [comment]
Oops, I should have been more careful checking my work there, instead of just assuming that it was trivial! 

The role of `Widget::update()` is really not to update the *widget*, but to update the widget *container*. The *only* widget that overrides it is Lua; none of the C++ widgets do anything with `update()`.

So I have now replaced the call to `update()` with a call to `Widget::update()`, so the container gets updated. And it works as intended in the simu.

**Comment by lshems** [comment]
Thanks!

**Review by pfeerick — APPROVED** [review]
Yes, that fixed it. Now that I'm hooked up the debugger I can see where it headed down the wrong path before.

**Pull request merged**
