### PR TITLE
fix issues:

### PR DESCRIPTION
**Pull request by kevinkoenig**
Fixes for Issues
- [x] #302 
- [ ] #307 
- [x] #482 
- [ ] #404

### CODE REVIEW

**Comment by pfeerick** [comment]
Both #302 and #482 fixes seems to be working great.

#307 partly overlaps overlap with #404, and #307 was for the outputs tab, not mixes ;)

**Comment by kevinkoenig** [comment]
> Both #302 and #482 fixes seems to be working great.
> 
> Fix for #307 partly overlaps overlap with #404, and #307 was for the outputs tab, not mixes ;)
> 
> IMO, since 480x272 displays in particular have limited vertical space, for things like the output bars I would like to see more of that essentially 'wasted' header bar space used if it can be... could maybe even put the double-bars in like on the channel monitor? There is also plenty of space in the header on the NV14 aspect ratio. It would also be consistent with the usage in a few places for the header bar to be used for 'live' data. What do you think?

let me push a change that showcases that, and we can decide which one is better.  I like the double bar idea.

**Comment by pfeerick** [comment]
This indeed does look really good... can clearly see what is going on with input and output (i.e. I have some crazy subtrim offset on that ch atm), as well as exact ch value. 

It just seems a little oddthat the background fill is not the header colour... I suppose the CH and us text becomes unreadable?

image

**Comment by kevinkoenig** [comment]
That is exactly true.  The text is the same blue.  Threw me for a loop for 10 minutes.  I didn’t want to change what colors these standard controls were using as it would have impact to channel monitor screen.  So That is why I did what I did.  

Sent from Mail for Windows

**Comment by pfeerick** [comment]
Ok then, that makes sense. So the question is then how hard is it to add 'custom/override colours' to the channel bars? If it's a 10 minute job, I'd like that, otherwise this can stay as it is for now.

**Comment by kevinkoenig** [comment]
20 minutes.  Super easy.  I’ll do it we ver next couple of days

**Comment by pfeerick** [comment]
Given the choices, I don't thing there is going to be a 'right' one for the 'end stop' (for want to better word) indicators... For the default, and a lot of the themes I have installed this is about the most visible it is going to be... anything else will go very, very wrong. Plus, it serves it's purpose - as it should be visible once you are no longer at the 100% channel movement position. 

I think that wraps up the edit screen half of #404 ;) Unless you have objections, lets merge this, and then pick up the other half in another PR, as well as #307, as they are somewhat related. 

snapshot_26

**Comment by kevinkoenig** [comment]
> Given the choices, I don't thing there is going to be a 'right' one for the 'end stop' (for want to better word) indicators... For the default, and a lot of the themes I have installed this is about the most visible it is going to be... anything else will go very, very wrong. Plus, it serves it's purpose - as it should be visible once you are no longer at the 100% channel movement position.
> 
> I think that wraps up the edit screen half of #404 ;) Unless you have objections, lets merge this, and then pick up the other half in another PR, as well as #307, as they are somewhat related.
> 
> snapshot_26

I would merge it as is, but lets let others comment

**Comment by pfeerick** [comment]
Right, this can have a two day cooling period, and then it's in :grin:

**Comment by kevinkoenig** [comment]
> Right, this can have a two day cooling period, and then it's in 😁

works for me 👍

**Pull request merged**
