### PR TITLE
Test new EdgeTX splashes and remove vendor specific branding

### LINKED ISSUE #154: EdgeTX splash: 212x64 and 128x64 needed
Some testers have complained that we don't have any splash screens for the following screen types:
- 4-bit greyscale `212x64` (X9D).
- 1-bit black/white `128x64` (X7, T-Lite and pals).

Please submit your designs here!

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #154

### CODE REVIEW

**Comment by pfeerick** [comment]
I still see the FrSKY and OpenTX as the default image for no models on the X9D+? Is that a leftover on my end from the SD card? Splash screen is good though on both the X9D+ and T-Lite.

**Comment by raphaelcoeffic** [comment]
> I still see the FrSKY and OpenTX as the default image for no models on the X9D+?

Thx, I did not remember this was also existing.... Will patch as well. We might need another image for that as well, let's see.

**Comment by pfeerick** [comment]
Yup, that last commit dealt with that last OTX logo. I'm just wondering if it can be improved further... The aliasing around the 'EDGE' and the line doesn't look the best... I'm wondering if it would be better to treat it as a 1 bit black and white, and also make sure there are no soft edges / aliasing to the text. Maybe something @MRC3742 can comment on?

android_to_browser_dfTENk27pps_IMG_20210608_145956

**Comment by raphaelcoeffic** [comment]
Yep! @MRC3742 offered to do it, and he is obviously better skilled at that than me ;-)

**Comment by MRC3742** [comment]
Resizing that small usually washes out the image.
I'll rework it later today and post a few different options.

Rich

**Comment by MRC3742** [comment]
Here are a few options for that logo.png used on the 212x64 screens

Original logo cleaned up for 64x32 (4 bit)
logo01

EdgeTX logo 64x32 (4 bit)
logo02

EdgeTX logo 64x32 (1 bit)
logo03

If you want something different or a variant of above let me know.
Rich

**Comment by MRC3742** [comment]
I've added in the post above the EdgeTX (4 bit) logo with a darker background.
That is the one I think would work best for this radio?
I think the (1 bit) file will look choppy but I'll try to build the firmware with each and see. 
This logo.png bitmap file is only used on the 212x64 screens which are mainly X9D models.

Rich

**Comment by pfeerick** [comment]
Oh, nice! I'll change my order to the `EdgeTX logo 64x32 (4 bit) - Darken` then ;) Whilst X9D can do greyscale, it's basically crap, so for something like the logo, as near to simply B&W as possible is looks best.

**Comment by MRC3742** [comment]
I stand corrected. After building the firmware versions you and I are both correct. 
The Darker (4 bit) looks good straight on but fades at different areas at different screen angles.
The B&W (1 bit) logo gives the cleanest look although somewhat choppy.
I cleaned that B&W one up some more and now (5) seems to view the best on the 212x64 screen.

Anyway I'm sure making a project out of this. Just think if I was doing something important! LOL
Images and screenshots pics are now shown in the above post.

Rich

**Comment by pfeerick** [comment]
Thank you very much for trying them all out! :smiley: Yes, I concur, (Johnny) 5 is the best one!

**Comment by raphaelcoeffic** [comment]
Ok, so number 5 it is for now!

**Comment by raphaelcoeffic** [comment]
@pfeerick please whenever it pleases you (use "Create a merge commit").

**Comment by pfeerick** [comment]
Aw... doesn't that look prudy! :smiley_cat: 

android_to_browser_dfTENk27pps_IMG_20210609_193921

**Pull request merged**
