### PR TITLE
chore(bw): disable USBJ_EX on all F4 targets with only 512KB flash

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Free some FLASH on tight targets.

### CODE REVIEW

**Comment by pfeerick** [comment]
lol... so PXX2 is safe for now? 🤣 🤣

**Comment by raphaelcoeffic** [comment]
The real question is: what can we disable on the X9D+2019, without disabling PXX2 🤭

**Comment by 3djc** [comment]
The X9D+2019 itself ? 🤣

**Comment by pfeerick** [comment]
Hm... The bit before the X9D+2019 has to be worth at least a few hundred
bytes! But yeah, that is somewhat of a problem there... If something still
needs to got for it, I think Bluetooth is enabled on it by default?

**Pull request merged**
