### PR TITLE
Use ETX instead of OTX (also as a file extension).

### PR DESCRIPTION
**Pull request by rotorman**
Changes from *.otx extension to *.etx extension, plus changes function and variable names also from OTX to ETX.

This PR was inspired by the following 3 posts at RCG:

- https://www.rcgroups.com/forums/showthread.php?3916381-Official-EdgeTX-Discussion-Thread/page78#post48132683
- https://www.rcgroups.com/forums/showthread.php?3916381-Official-EdgeTX-Discussion-Thread/page83#post48152167
- https://www.rcgroups.com/forums/showthread.php?3916381-Official-EdgeTX-Discussion-Thread/page84#post48156589

in short asking:
`Scott Page: has there been thought or discussion of using a unique suffix for EdgeTX files -- such as .etx to differentiate them from OpenTX files?`
and
`Miami Mike: It would be bad if EdgeTX files could be opened with OpenTX Companion (or vice versa) but would result in corrupted data.`
plus
`Scott Page: If I double click on an .otx file it will open OpenTx companion.  I'd like a different suffix so when that those for Edge will open Edge Companion and those for my OpenTX radio will open OpenTX companion.`

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Can we still open `.otx` files with this? That would help when converting via Companion.

**Comment by rotorman** [comment]
> Can we still open `.otx` files with this? That would help when converting via Companion.

Yep, *.otx is still supported when opening files. Here file open dialog under Windows:

open dialog

**Review by elecpower — COMMENTED** [review]
I was going to propose adding etx extension as part of yaml implementation in Companion as we need to be able to create and read ETX bin and yaml settings backups. So you beat me to the punch on that part 👍 
I haven't had time to compile this branch to test it. From a quick desk check most looks okay. However have you tried to open an otx extension file, as you have removed the storage format to read and write them albeit we do not want to use the write functions moving forward.

**Comment by rotorman** [comment]
Yep, I tried opening *.otx file under Win10 version of this PR Companion (used https://github.com/EdgeTX/edgetx/blob/main/radio/src/tests/model_25_tx16s.otx ). I did not see any abnormal behaviour:

grafik

**Comment by elecpower** [comment]
I suspect it tried each registered format until it found one that was successful. The etx format as is able to open and process current otx files but this will not be the case moving forward. Also we would want otx files force converted and saved as etx (bin for now and yaml when implemented).
If my suspicion is correct then the choice of storage format for a particular file type needs tightening up to give more granular control. The method might have been okay before so many OTX supported formats can into being.

**Comment by rotorman** [comment]
@elecpower Please feel free to modify the PR / branch as you see fit.

**Comment by elecpower** [comment]
Confirmed suspicion
[D] storage/etx.cpp::EtxFormat::load():38 - File "/home/neil/Documents/EdgeTX/models/Models and Settings 2021-08-15.otx" read, size: 5781
[D] storage/etx.cpp::EtxFormat::loadFile():101 - "Extracted file RADIO/radio.bin, size=889"

**Comment by elecpower** [comment]
Working on extending your PR including renaming libsims which has a domino effect to firmwares and profiles.

**Comment by elecpower** [comment]
Note: Companion profiles will only be upgraded for those who haven't run up a 2.6 version of Companion. For 2.6 users they will get a bad profile message and need to reset the firmware (drop down) for each profile. Alternatively users can hack the settings (location OS dependent) and perform edits.
This PR needs some serous testing to ensure it hasn't broken anything else. 
Will need more changes when we get to Companion being able to download firmware and its own updates as I have left a number of opentx references, download methods and checks alone.

**Comment by pfeerick** [comment]
So, basically try this out with and without 2.6 installed, and see what breaks?

**Comment by elecpower** [comment]
The only version difference testing is whether the profiles auto upgrade or not. The rest are to confirm the file extension changes work and i haven't broken references in changing firmware names.

Note libsims should be recompiled to check that process works and then Companion can load.

PS I'm going to remove the yaml file option as it is a stub and assumed a single file. It may come back when we implement yaml and decide if we can support reading just a single model file and default the radio files.

**Comment by pfeerick** [comment]
Excellent. This is why I like using the github action builds for testing stuff... everything is freshly ~~squeezed~~ compiled. 

btw, just in case you didn't know... yaml is in main now... it's just any last bugs or gremlins being dealt with ;)

**Comment by elecpower** [comment]
I'm just about to start digging into radio yaml to work up a proposal for Companion implementation.

**Comment by elecpower** [comment]
Ready for stress testing

**Comment by rotorman** [comment]
I checked the behaviour with Windows version (64-bit). I uninstalled my previous Companion, selecting to uninstall Settings as well, and reinstalled this PR Companion. On first start I got:
First start
After going into Settings, I see my previous TX16S setting is still there, but uses FrSky Taranis X9D+ as radio type. After opening Settings..., re-selecting RM TX16S and clicking OK, closing Companion and re-opening, the update profile message is not shown anymore.

I can open *.otx settings, and do not see any problems. Tried with *.etx, works as well.

The simulator dll-s are all libedgetx*.dll, instead of old libopentx*.dll :)

The default radio type in standalone full simu was reverted to edgetx-nv14 (my last usage was tx16s). Also, it does not seem to save all changes back to virtual SD card on exit, but this might have something to do with YAML being integrated into simu libs of this PR.

**Comment by elecpower** [comment]
@rotorman if it cannot find current version settings it looks for older versions back to 2.4. Though it still should have upgraded so you do not get that first start message. I tested in Ubuntu. Anyway I'll retest :-(
The default simulator radio type is likely due to loading older settings.
In testing I noticed what appear to be yaml conversion glitches but haven't had time to do a deep dive as my priority is for us to get this PR merged.

**Comment by elecpower** [comment]
If you successfully removed your 2.6 settings this message should have been displayed. We this is what I get in Ubuntu. Maybe its a Win thingy.

Screenshot from 2021-11-17 07-13-12

However, the import of an older version is corrupted. I originally tested with a code version fudge. 2 steps forward and 1 step back :-(

**Comment by rotorman** [comment]
I was not presented with the dialog in your last post. As it works for you under Ubuntu, this might be Windows version peculiarity.

Just to be sure, I re-run the uninstall/install procedure. Picked explicitly to remove the settings during uninstall:
Uninstall

After uninstall finished (successfully), I see that it did not remove the newly renamed simu libs. `C:\Program Files\EdgeTX\Companion 2.6 lists`:
AfterUninstall
The uninstaller might need changing the opentx to edgetx as well.

Reinstalled. I do not get the warning dialog to update profile settings, but this is likely, because the previous install updated them already. Although I did remove settings, RM TX16S is still listed on first start:
RMTX16S still listed

but this time with correct settings (not with FrSky X9D+ as last time):
correct settings

**Comment by elecpower** [comment]
If old 2.6 installed and then new 2.6 over the top I suspect Win might be using the first install for uninstall. Either way there is the likelihood of libsim artefacts.
 I'll check to make sure opentx is not hard coded in the installer.

**Comment by elecpower** [comment]
@rotorman ready for retesting

**Comment by pfeerick** [comment]
Windows 10:
 - installing on top of older ETX 2.6 gh build gave expected profile settings message... too bad.
 - completely removing prior 2.6 build + settings, and installing this version. Resulted in upgrade message shown earlier
 - choosing import from v2.5 worked fine - profiles were there, seemed to be working fine. 
 - OTX => ETX seems to be working fine. Defaults to ETX for save, opens otx without having to change any options.

**Comment by rotorman** [comment]
Tested under Win10 by first uninstalling the previous Companion (previous version from this PR).
I can open *.otx, I can open *.etx. I can save *.etx - the main goal of this PR works nicely. Did not observe issues.

Uninstalled and installed 2.5 release Companion instead to simulate typically end-user scenario. Created a profile for TX16S. Did not uninstall 2.5, but just ran the installer of this PR Companion. I was not presented with a conversion prompt, but that might have something to do that even if selecting `Settings` to be uninstalled, the uninstaller does not wipe `HKEY_USERS\<SIDs of users>\SOFTWARE\EdgeTX\Companion 2.6` (uninstaller runs in Administrative user context and the EdgeTX registry keys can be under other user SIDs).

An observation, not directly related to this PR, more a cosmetic issue - presently, the uninstaller deletes `C:\Program Files\EdgeTX\Companion 2.6`, but does not delete `C:\Program Files\EdgeTX`, even if the installer instance created it and there is nothing else in it.

**Review by pfeerick — APPROVED** [review]
Usability wise, fine by me. @elecpower is the Companion guru, so if he is happy with the current state, good to merge. We can look at tweaking the NSIS installer/uninstaller and better cleanup in another PR.

**Comment by rotorman** [comment]
@elecpower what is your expert opinion - should we merge this PR as is?

**Comment by elecpower** [comment]
If no issues found in testing except for installer artefacts then I'm okay with merge.
BTW I have been discussing yaml with @raphaelcoeffic and agreed that once YAML is implemented in Companion etx files will only contain yml files. Reading raw/bin/txt files from radios will be written to otx extension for backup purposes. If the radio supports yaml the file read from the radio will be force converted to yaml.

**Comment by elecpower** [comment]
@rotorman I favour pure when possible. So if others are okay to wait then close the PR but leave the branch as the base for cpn yaml, which is what I was planning to do anyway. The good part is the work to date has been tested. In the meantime someone might have some time to look at the installers.

**Pull request closed without merging**
