### PR TITLE
fix(cpn): ACCESS owner registration id validation (#2672)

### LINKED ISSUE #2672: Owner Registration ID allows no "-" character in Companion radio settings
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Currently it is not possible to enter a character such as a "-" in the radio settings under "Owner Registration ID". However, this is possible in the simulator as well as in the radio firmware.

### Expected Behavior

It should be possible to use the same characters in Companion that are allowed in the radio firmware.

### Steps To Reproduce

1. start Companion
2. create a new document
3. enter radio settings
4. try to enter abc-def in field "Owner Registration ID"

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

2.8.0 selfbuild 8ce3612f

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #2672

Summary of changes:
- add standard name validation
- hide label and field if radio does not support ACCESS

Note: decision required on inconsistent validation across radios

### CODE REVIEW

**Comment by ParkerEde** [comment]
I've checked [elecpower/cpn-fix-2672](https://github.com/EdgeTX/edgetx/tree/elecpower/cpn-fix-2672) and works so far.

**Comment by elecpower** [comment]
@pfeerick Hi Peter do you want to merge this as is since it improves the current situation and have the consistency debate separately?

**Comment by pfeerick** [comment]
Sounds like a plan. 2.8 or 2.9? I'm leaning towards 2.9 since it's only an issue if you *edit* the field on Companion, but since the fix is here I'm cool either way ;)

**Comment by elecpower** [comment]
I vote for 2.9 as only limited user testing since not in nighties and 2.8 needs to get out

**Comment by ParkerEde** [comment]
I vote for 2.8. beacuse it's ready and works ;-)

**Comment by pfeerick** [comment]
Think this also needs to check the module type when hiding the field - i.e. ISRM on a TX16S

image

**Comment by ParkerEde** [comment]
I don't think that's quite right. If you work with an external ACCESS module R9M2019, for example, you should also be able to specify the ownerid, shouldn't you?

**Comment by pfeerick** [comment]
Well, that as well. But as this PR currently stands with TX16S internal RF set to ISRM you can't set the owner ID, hence my comment ;)

**Comment by elecpower** [comment]
Following the comments and checking the TX16S sim where the owner id is displayed no matter the internal radio module I have simplified the change to just field validation.

**Comment by pfeerick** [comment]
Thanks. Yes, for now I think that is the path of least resistance - the setting probably needs to go somewhere else generally (given  it is really dependent on what internal and external RF the radio has - and hence almost model specific but global), but for now that's where it is.

**Pull request merged**
