### PR TITLE
Eshifri/widget edit

### PR DESCRIPTION
**Pull request by eshifri**
Fix for #529 Allows to exit widget setup screen using touch interface

### CODE REVIEW

**Comment by pfeerick** [comment]
This should also work on the TX16S, etc? I think Raphael specifically prevented the back option in the edit screens because of another issue... And it may not a complete solution, as what happens when the top bar is turned off?

**Comment by eshifri** [comment]
Yes, it works on TX16S as well. Touching the screen anywhere outside the widget takes you back to the previous screen, so top bar is not important.

**Comment by pfeerick** [comment]
lol... I was thinking of the wrong screen... I'm with you now... widget options shadowing... 🤦

**Comment by pfeerick** [comment]
Hm, this isn't working properly in `simu` or the TX16S hardware ... this PR makes it so you can't even set a widget up. Screens Settings -> Main View 1-> widgets setup. If you press on any of the layout spaces, it jumps back to the prior "Main View 1" screen, instead of the options to either select a new widget, or modify an existing one.

You'll also see that if you try Screens Settings -> User Interface -> Setup widgets that you can't go back without a hardware button. For that one, I think it's legitimate that you should be able to go back via the corner logo, just like anywhere else.

**Comment by eshifri** [comment]
You are right. I do not know how I missed it. Got too excited, I guess. :-)

**Comment by raphaelcoeffic** [comment]
Please rebase 😋 I should see only the commits relevant to this, nothing else.

**Comment by pfeerick** [comment]
@eshifri Part of the problem you will have is that your https://github.com/eshifri/edgetx/tree/main is 9 commits ahead of https://github.com/Edgetx/edgetx/tree/main, which should not be the case. It should always be in sync, or commits behind, needing fast-forwarding/pulling. 

i.e. 
1) I would make sure you've checked out your `main`
2) Roll it back to before your fork diverged from EdgeTX's main - `git reset --hard 34c588d9f630f93a01d297f0d8b6d33fed539594` 
3) Add the upstream remote if you don't already have it - `git remote add upstream https://github.com/EdgeTX/edgetx.git`
4) Tell git to grab the current state of the upstream repo - `git fetch upstream` 
5) Tell git to merge your checked out branch with upstream repo - `git merge upstream/main` - it should simply fast-forward, not create a merge commit. 

Instead of 3-5, you can use the 'Fetch upstream' option on GitHub to do all of that automatically... but you *will* need to force-push the reset state of your repo so that the out-of-sync issue is resolved first. 

image

Once you have it all reset and re-synced, you can run `git rebase origin/main` on your PR branch (i.e. you need to have it checked it out so it's active) to make it only have the one commit that belongs to that PR, and force-push that to github, and it will update here also.

**Comment by eshifri** [comment]
Thank you! Let me try to re-sinc my main using your procedure.

**Comment by eshifri** [comment]
After doing all this, my main is still 9 commits ahead...

**Comment by raphaelcoeffic** [comment]
> After doing all this, my main is still 9 commits ahead...

May I ask which Git client you are using? If you like UI programs: I use Fork (https://git-fork.com/; free version)

Otherwise there are lots of ways to do this / automate it from command line. Let me know if you need anything. @jfrickmann had similar issues, and solved them by reading this: https://git-scm.com/book/en/v2.

I think the following chapters are important to read:
- https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository
- https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
- https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by pfeerick** [comment]
I only see rebasing as 'evil' if you are working with others as it basically trashing the state of the branch for other users... if it's a single user PR then I think it's whatever you want. ;)

@eshifri This is the sequence of commands I just used to reset the main branch of a [fork of your repo](https://github.com/pfeerick-tests/edgetx) to the same current state as the edgetx repo (currently commit 704c03a):
```
git checkout main
git reset --hard 34c588d9f630f93a01d297f0d8b6d33fed539594
git remote add upstream https://github.com/EdgeTX/edgetx.git
git fetch upstream
git merge upstream/main
git push -f
```

After that, I think it would have been:
```
git checkout widget_edit
git rebase main
git push -f
```
to rebase and push the new state of that branch to github.

You can do a lot of this in VSCode (i.e. adding the remote, fetching, rebase, checkout) but some of the more specific commands like reset, and forced push aren't readily available until you play with some of the settings (i.e. forced push) and/or install the gitlens extension as well (ability to reset to a specific commit).

**Comment by rotorman** [comment]
I added a page is EdgeTX dev. Wiki about getting started with Git:
https://github.com/EdgeTX/edgetx/wiki/Getting-started-with-Git

Please feel free to modify and augment.
Especially if you have a tip about useful GUI tool for Linux to recommend, would be nice if we could list it as well.

**Comment by pfeerick** [comment]
Just added Sublime Merge and VSCode, as both are cross-platform Linux, Mac and Windows. Sublime Merge is a GUI frontend, and VSCode's git support is ok, and really good when extended with the GitLens and Github extensions.

**Comment by eshifri** [comment]
Thank you for your help, guys!
I'm using GitHub Desktop.

**Comment by eshifri** [comment]
@pfeerick after performing this sequence
git checkout main
git reset --hard 34c588d9f630f93a01d297f0d8b6d33fed539594
git remote add upstream https://github.com/EdgeTX/edgetx.git
git fetch upstream
git merge upstream/main
git push -f

my main is 14 commits ahead. :-)
I guess I will need to remove the repository and create a new one, but I do not want to lose all pull requests.

I think there is work around: I can rebase every feature branch on edgeTX:main and public it as a new branch.

**Comment by eshifri** [comment]
Somehow, eventually main looks OK.

**Pull request closed without merging**
