### PR TITLE
fix(cpn): llvm clang dll filename change breaking libsimulator builds

### PR DESCRIPTION
**Pull request by pfeerick**
Fixes #

Summary of changes:

### CODE REVIEW

**Comment by philmoz** [comment]
It looks like the findLibClang function in radio/util/find_clang.py is failing - so every radio with RTC backup is going to fail.

**Comment by philmoz** [comment]
Has libclang.dll been removed from msys?

**Comment by pfeerick** [comment]
Not from what I can tell  - if you check the comment I posted on discord the other day pointing out it was failing in find_clang, one of the commits in msys yesterday was in relation to a name change... but I also cannot reproduce this locally with a freshly installed msys environment... :shrug:

**Comment by philmoz** [comment]
Can you print all the directories that findLibClang is searching and their contents?

**Comment by philmoz** [comment]
Looks like the dll's in bin have the version in the name - what a mess.

What happens if you force it to load bin/libclang-18.1.dll?

**Comment by pfeerick** [comment]
Yes, that makes sense now... I saw mention that it now seems to add the llvm version number :vomiting_face: 

Seeing if it symlinking it will trick it into behaving...

**Comment by pfeerick** [comment]
Ok, that was a dirty fix, but it seems to be working now... time to cleanup this PR! :zany_face:

**Pull request merged**
