### PR TITLE
fix: Correctly reflect state of AUX1 when DEBUG build

### LINKED ISSUE #3813: Debug build: unexpected debug output on AUX1 with AUX1 set to OFF
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Firnware built with -DDEBUG=YES -DCMAKE_BUILD_TYPE=Debug outputs debug data on AUX1 TX with AUX1 set to OFF in radio settings/hardware

### Expected Behavior

No debug output on AUX1 with AUX1 set to  OFF.

### Steps To Reproduce

Build fw with -DDEBUG=YES -DCMAKE_BUILD_TYPE=Debug
connect serial monitor (400000,8,N,1) to AUX1 GND and TX
make sure radio settings / hardware has AUX1 set to off
power radio
observe debug output in serial monitor

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

current nightly, think problem is also present in 2.9

### PR DESCRIPTION
**Pull request by mha1**
fixes #3813

Summary of changes:
- removed forced default serial initialization of AUX1 for debug builds

### CODE REVIEW

**Comment by 3djc** [comment]
Then you need another method of providing early debug output when model and radio settings aren't loaded yet

**Comment by mha1** [comment]
Actually I was waiting for this comment. Yes, there are 1-2 of the first seconds missing booting with AUX1 set to debug. How about a DEBUG_EARLY define (which also sets DEBUG). You'd have to explicitly build for this. Building just DEBUG would allow debugging (TRACE()) all AUX1 modes.

**Comment by philmoz** [comment]
> Actually I was waiting for this comment. Yes, there are 1-2 of the first seconds missing booting with AUX1 set to debug. How about a DEBUG_EARLY define (which also sets DEBUG). You'd have to explicitly build for this. Building just DEBUG would allow debugging (TRACE()) all AUX1 modes.

Rather than break existing functionality and force users to change build settings, I would suggest a better approach would be to add a new define to disable the code that you don't want.

**Comment by 3djc** [comment]
Or don't force everybody to change and add a DEBUG_WITHOUT_AUX1 option that fits your need

**Comment by mha1** [comment]
I found a solution to my original problem of not being able to select any AUX1 mode in DEBUG configuration. Moving trace output to AUX2 and USB-VCP is possible, the missing part for trace debugging AUX1 functions was being able to select a different mode on AUX1.

Two observations made me curious. DEBUG mode initializes AUX1 early in the startup process but AUX1 radio hw settings didn't show that AUX1 was in DEBUG mode and selecting any other mode on AUX1 was not possible in DEBUG mode.

The reason for not being able to select a different mode is the early initialization. The AUX1 serial port is correctly initialized and it's state information saved. But the serial ports are initialized later again as part of the normal startup process. This clears all ports states which is  preventing the selection of a different mode. Not clearing the state data structure again in DEBUG mode solves the problem. Calling serialSetMode() as part of the early initialization solves the Debug not shown in AUX1 radio hw setting problem.

I hope this is an acceptable solution without forcing anything on anybody.

**Comment by mha1** [comment]
@3djc you good with this?

**Comment by pfeerick** [comment]
Conceptually I don't have any issue with this, haven't tried it yet though. 

Just a thought... is there any reason to not do the following and thus not duplicate code (since it should skip that iteration)?

```cpp
#if defined(DEBUG)
if(port_nr == AUX1)
   continue;
#endif
```

**Comment by mha1** [comment]
@3djc @pfeerick asking for review

**Comment by 3djc** [comment]
My only concern is that the settings gets wipe when you run debug build (I tend to swap between builds to compare behavior) which will be anoying. Tbh, I'm not concerned that the UI doesn't match that specific settings when you run a DEBUG/TRACE build (because in this case, you really know you are running a special firmware to troubvleshoot something specific), but you seem to think it is a big issue, I guess I can live with that PR

**Comment by mha1** [comment]
which settings you're talking?

**Comment by raphaelcoeffic** [comment]
@mha1 it seems @pfeerick @gagarinlg @3djc are uncomfortable with the PR as-is. What about really just having this:
```diff
diff --git a/radio/src/targets/horus/board.cpp b/radio/src/targets/horus/board.cpp
index 3ce7eeb280..f25f27b454 100644
--- a/radio/src/targets/horus/board.cpp
+++ b/radio/src/targets/horus/board.cpp
@@ -148,7 +148,7 @@ void boardInit()
 
   __enable_irq();
 
-#if defined(DEBUG)
+#if defined(DEBUG) && !defined(DEBUG_SERIAL_NO_INIT)
   serialInit(SP_AUX1, UART_MODE_DEBUG);
 #endif

```

**Comment by mha1** [comment]
@raphaelcoeffic Where do you read Peter's or Malte's discomfort? Phil had a comment which I addressed with the now proposed solution which Peter thumbed-up. JC is the only one that had a valid point which is a side effect of doing it "right". 



But luckily I'm only a pawn and don't have any say in any decision. @3djc And no, I don't think it's a major problem. I just stumbled over it  with the use case I described above. The sun will rise again regardless of this PR being in or not but the early init followed by the regular init clearing a valid data structure again leaving the serial port in a working but half dead AUX1 GUI is just wrong which is noticeable by the fact that you can't select any other AUX1 mode in DEBUG configuration. The side effect of doing it right is that AUX1 will be set to "Debug" which is exactly what is asked for building with DEBUG. And the AUX1 mode can be changed to anything else if desired. 

But if this PR is nuisance just scrap it. It's really low emotional debt to me.

PS for Raphael: Fun fact - my use case was to debug CLI not working. Rings a bell :-)?

**Comment by raphaelcoeffic** [comment]
> PS for Raphael: Fun fact - my use case was to debug CLI not working. Rings a bell :-)?

LoL

**Comment by pfeerick** [comment]
I simply haven't had time to look at this further, and had put it off an update notification i.e.  a reply from JC re: settings changed. As I wasn't aware this in its updated form would do anything more than correctly synchronise the UI with the *actual* state of the hardware, as well as finish initialising stuff that was left hanging in the wind. My only discomfort was probably a failed attempt to be more DRY 🤭

**Comment by mha1** [comment]
please unzip the last sentence for me

**Comment by pfeerick** [comment]
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

😂😂

**Comment by pfeerick** [comment]
@mha1 Can you review the last commit(s) I made, as it seems you probably forgot to compile with with DEBUG=Y set (since it will would not compile due to a typo, and out of scope memset).

**Comment by mha1** [comment]
@pfeerick I have no idea what happened to AUX1 vs SP_AUX1. Also serialPortStates was known in board.cpp (memset) when I was working on it. Gremlins? I'm very sure I have tested this with and without DEBUG.

memset: serialPortStates is a static. Hence will (should) be default initialized to zero at startup. Clearing serialPortStates should not be necessary. The memset in non-debug (late) initSerialPorts() could also go. As far as I can see initSerialPorts() is only called once. call tree: main() -> tasksStart() -> opentxInit() -> initSerialPorts()

Updated:
- removed unnecessary memset (in initSerialPorts() in addition to your commit for the b
- AUX1 -> SP_AUX1 (your commit)

retested ok on TX16s in debug and non-debug build config:
- if radio settings has AUX1 set to OFF early debug will be initialized with AUX1 set to DEBUG (also reflected in GUI)
- if radio settings has AUX1 set to mode other than OFF (e.g. telemetry mirror) AUX1 setting will be retained
- changing of AUX1 mode now also possible in DEBUG config
- running non-DEBUG firmware after running DEBUG firmware with AUX1 set to DEBUG sets AUX1 to NONE (cleanup after DEBUG as DEBUG is non selectable in non-DEBUG configurations)
- radio settings GUI and AUX1 modes are consistent in DEBUG and non-DEBUG configurations

**Comment by pfeerick** [comment]
Low-level stuff has been in a state of flux for a while, so quite likely something changed the scope of `serialPortStates`, but thankfully it seems that isn't an issue. Dunno about `SP_AUX1` either... it _seems_ like it was like that originally, but I would put it past a git rebase to have clobbered it. 

Much appreciated the repeat testing and log, I'll counter-test using the Boxer as it has an AUX1 also and then hopefully merge.

**Comment by pfeerick** [comment]
LGTM, I can repeat the aforementioned UI behaviour on RM Boxer.

**Pull request merged**
