### PR TITLE
feat: RGB leds supports

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of Changes:
- Adds support for WS2812 LEDs (taranis targets only for now)
- New custom function allowing to select a LUA script that controls a LED strip (see EdgeTX/edgetx-sdcard#115)
- `stm32_pulse_driver` modified to initialise DMA only once during init
- Improved pulse driver support for complementary channels

### CODE REVIEW

**Comment by Eldenroot** [comment]
CZ:

#define TR_SF_MOD_BIND                 "Modul Bind"
#define TR_SF_RGBLEDS                  "RGB led"

**Comment by raphaelcoeffic** [comment]
@mha1 may I ask you to check if the changes in the timer / pulses drivers still work for all modules / protocols?

**Comment by mha1** [comment]
@raphaelcoeffic good one. batting my pitch to a home run.

I'll do some spot checks on what I think I can do . §xternal/internal MPM, external ELRS, PWM out, softserial in. That's about it I think .

**Comment by mha1** [comment]
Including quick functional tests:
external ELRS control, telemetry, ELRS LUA script-> ok
internal MPM control, telemetry, HOTT LUA script -> ok
external MPM control, telemetry, HOTT LUA script -> ok
module bay softserial-in on SPort pin -> ok

Just looking at signals, no functional test:
DSM2 out (all 3 sub protocols) at CPPM pin -> looks ok
XJT D16 out at CPPM pin -> idle low bitstream available at 11Hz, -> should be ok
PPM out at CPPM pin -> single pulse at 22Hz with correct idle level but no channel data -> **not ok**

Hope that helps

**Comment by raphaelcoeffic** [comment]
@mha1 should be fixed now.

**Comment by raphaelcoeffic** [comment]
For example, with a internal XJT module on QX7:

Screenshot 2023-08-10 at 15 13 54

The internal module sends every 9ms, but as the PPM pulse is not finished, every other slot is skipped, so that you get 2x9ms = 18ms.

**Comment by mha1** [comment]
It looks a lot like MPM's 7ms. And indeed it was on. I was fooled because there is no more GUI indication (yellow) if there is a module set. But at least consistent. No indication for internal and external modules. Set internal module to off, all good now.

**Comment by mha1** [comment]
Was the highlighting Internal RF and External RF is set to other than off scraped on purpose?

**Comment by raphaelcoeffic** [comment]
> Was the highlighting Internal RF and External RF is set to other than off scraped on purpose?

Probably a question for @JimB40 and @philmoz

**Comment by JimB40** [comment]
If on purpose you would see PR with rather long discussion. Most of UI behaviour that differs from 2.8 ismdue to some 'fixes'.

**Comment by mha1** [comment]
@raphaelcoeffic alll the serial out on CPPM/SPort and (soft and hardware) serial in on SPort seems to work too

**Comment by pfeerick** [comment]
Of concern: anything that uses soft serial, i.e. pulse drivers

**Comment by richardclli** [comment]
Hey, I need this one and see if it works in my PL18 branch.

**Comment by pfeerick** [comment]
Neither X9D+2019 nor Boxer are booting with the GitHub builds for this PR.

**Comment by raphaelcoeffic** [comment]
> Neither X9D+2019 nor Boxer are booting with the GitHub builds for this PR.

Should be fixes now.

**Comment by pfeerick** [comment]
TX16S, X9D+2019, X9D, Zorro: All connected to pre-bound/bound as necessary RXs with internal MPM/ISRM/XJT, telemetry and control link good. Mix of Ghost, CRSF, Tracer, XJT/XJTLite and MPM external modules used across all the radios with no issues with github builds.

**Pull request merged**
