### PR TITLE
feat(color): Replace static bitmap QR code with LVGL generated QR code

### PR DESCRIPTION
**Pull request by philmoz**
This functionality could also be used in future to add 'help' links to pages.

### CODE REVIEW

**Comment by gagarinlg** [comment]
I am still thinking about a way to share model settings via QR Code and a camera in the TX

**Comment by pfeerick** [comment]
Bluetooth/wifi link to your phone, app on your phone? 🤭

**Comment by raphaelcoeffic** [comment]
> share model settings via QR Code and a camera in the TX

You'll have hard times encoding everything into a single QR code. Most apps doing this do upload everything and generate a single ID, which is exchanged via QR code, and then used to download whatever needs to be exchanged.

**Comment by raphaelcoeffic** [comment]
@philmoz the most interesting question is: what is the impact on FLASH usage? Aka. is code more efficient than a pre-generated image?

**Comment by philmoz** [comment]
> @philmoz the most interesting question is: what is the impact on FLASH usage? Aka. is code more efficient than a pre-generated image?

Replacing only a single QR image will use more FLASH for the LVGL QR library - ~6K on TX16S.
The libopenui refactor PR saves ~5K so overall it's not too expensive.

**Comment by pfeerick** [comment]
Last main build:
```
Totals         KB    usage  of ttl	KB free
  Flash:  1572.14   76.76%    2048	 475.86
  CCRAM:    47.15   73.68%      64	  16.85
  SRAM1:    72.75   64.96%     112	  39.25
  SRAM2:     0.00    0.00%      16	  16.00
  SRAM3:     0.00    0.00%      64	  64.00
 SDRAM2:  5116.00   62.45%    8192	3076.00
```
This PR:
```
Totals         KB    usage  of ttl  KB free
  Flash:  1577.86   77.04%    2048   470.14
  CCRAM:    47.15   73.68%      64    16.85
  SRAM1:    72.77   64.98%     112    39.23
  SRAM2:     0.00    0.00%      16    16.00
  SRAM3:     0.00    0.00%      64    64.00
 SDRAM2:  5116.00   62.45%    8192  3076.00
 ```

**Comment by raphaelcoeffic** [comment]
> 90% is still far away (will regret that soon, I'm sure!)

You didn't try the `TW` build, right? 😇

**Comment by gagarinlg** [comment]
When the libopenui reactor PR is merged and it really saves 5kB, 2e are good.

**Comment by pfeerick** [comment]
> > 90% is still far away (will regret that soon, I'm sure!)
> 
> You didn't try the `TW` build, right? 😇

Not since 2.8.4, with extra heli and luamixer 🤭 
```
Totals         KB    usage  of ttl	KB free
  Flash:  1971.34   96.26%    2048	  76.66
```

**Comment by philmoz** [comment]
Ouch - what causes that huge jump?

**Comment by raphaelcoeffic** [comment]
> Ouch - what causes that huge jump?

The fonts.... They are quite huge for asian languages (especially `XXL`).

**Comment by pfeerick** [comment]
TW character set is a lot bigger than our paltry English one... plus that firmware still has all the binary conversion support, and luamixer on top.

**Comment by gagarinlg** [comment]
So we need a ttf font renderer and cache used symbols in Ram?

**Comment by 3djc** [comment]
I was about to add a qr code for <undisclosed hardware > so I vote for this !

**Comment by philmoz** [comment]
RTTI costs about 78K on my TX16S build. Unfortunately it's required for a handful of places where dynamic_cast is being used. Has anyone tried to get this of this?

**Comment by gagarinlg** [comment]
Where are dynamic casts used?

**Comment by philmoz** [comment]
Screen layouts and widgets.

**Comment by JimB40** [comment]
Can it be used to generate qrcode in *.png that is saved to SD? I have qrcode LUA but it is so calculation intensive that is almost killing MCU.

**Comment by philmoz** [comment]
> Can it be used to generate qrcode in *.png that is saved to SD? I have qrcode LUA but it is so calculation intensive that is almost killing MCU.

Possibly. Rendering to an off screen canvas should be ok; but not sure about saving to a png file.

**Comment by philmoz** [comment]
> So we need a ttf font renderer and cache used symbols in Ram?

LVGL can load binary format fonts from files. Binary fonts can be created with the lv_font_conv program by changing the output format.

I've mocked up a quick test of this to load the XL and XXL fonts from the SD card instead of embedding them in the firmware.

Tested and working in the simulator and TX16S.

If the fonts can't be loaded then the L font is used instead.

Any thoughts - is it worth developing further? It would require adding font files to the SD card content.

**Comment by 3djc** [comment]
If XL and XXL are indeed not used by the non lua stuff (and likely not used by most lua add on either) then it would be something to look at as a side pr to reduce flash usage, imho

**Comment by JimB40** [comment]
If you do research XXLSIZE is used mostly for numbers.
https://github.com/search?q=XXLSIZE+language%3ALua&type=code&p=1&l=Lua
Thats obvious as XXL font is way to big to use for anything meaninful as text.

There are 2 or 3 cases LUA dev used it for text.
Screenshot 2023-08-04 at 08 36 01

Not important though as "No Value" can be replaced with '-'.

So if it matters for reducing firmware size I'd left XXL font, but change it - so it contains Numbers & Special Characters like '-', ':'

**Comment by pfeerick** [comment]
@JimB40 Check https://github.com/EdgeTX/edgetx/pull/3881 ;)

**Pull request merged**
