### PR TITLE
fix(cpn): Model print global and special functions

### LINKED ISSUE #3074: Companion model print SF/GF settings missing or unnecessary
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Timer value missing and others there is no need to generate

Screenshot from 2023-01-22 06-29-04

### Expected Behavior

Add timer value and remove unnecessary values and repeats

### Steps To Reproduce

Add SF/CF to model and print

### Version

2.8.0

### Transmitter

Other (Please specify below)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #3074

Summary of changes:
- fix generate set timer parameter value
- do not generate parameter when function does not support
- do not generate repeat when function does not support
- convert to table format with per column compare highlighting
- minor housekeeping

Before
Screenshot from 2023-01-22 08-48-50

After
Screenshot from 2023-01-22 08-47-00

### CODE REVIEW

**Comment by HThuren** [comment]
Maybe you can put at tab after the Switch/Trigger to align after
image

**Comment by elecpower** [comment]
@HThuren I'll have a look but it may have to be a new column as I seem to remember tabs not working or not working as expected as the output is a hybrid html document.

**Comment by HThuren** [comment]
> @HThuren I'll have a look but it may have to be a new column as I seem to remember tabs not working or not working as expected as the output is a hybrid html document.

Thank you !
By the way impressive programming you did here..

**Comment by elecpower** [comment]
I got carried away and converted GFs and SFs to table format. This also has the advantage that for model compare the highlighted changes are refined from row to each column.

Screenshot from 2023-01-24 21-17-21

Screenshot from 2023-01-24 21-26-57

**Comment by HThuren** [comment]
@elecpower will this PR be merged :-)

**Comment by elecpower** [comment]
@HThuren up to @pfeerick but most likely after bug fix 2.8.1 released as it is an enhancement

**Comment by pfeerick** [comment]
An after and before screenshot:
image
image

**Comment by HThuren** [comment]
Hi @elecpower, this is a very nice change.
Doing the same some day for Inputs, Mixers and Telemetry Sensors would be nice :-)

**Comment by elecpower** [comment]
Hi @HThuren, one day. Too many fields for one per column so will likely be some groupings.

**Pull request merged**
