### PR TITLE
Automatically detect FlySky digital hall sticks

### PR DESCRIPTION
**Pull request by rotorman**
Removes the necessity of custom build-time CMake option FLYSKY_HALL_STICKS.
Checks on power-up, if the FlySky digital sticks are present or not and accordingly activates either digital or analog sampling of the sticks.

Added special UART4 init routine to sample if FlySky sticks are present or not. The detection result is saved in `globalData.flyskygimbals`.

Tested on two RM TX16S radios, one with FlySky digital hall sticks and second with stock analog sticks.

### CODE REVIEW

**Comment by rotorman** [comment]
@richardclli could you please test on NV14 if the stick direction is still correct. I had to remove the inversion for channels 3 and 4 for TX16S. In case NV14 needs it, I would need to add a NV14 case to: https://github.com/EdgeTX/edgetx/blob/eb389d38602e3c9bcdcac976e34ad1aca4564f46/radio/src/targets/horus/flyskyHallStick_driver.cpp#L85-L93

e.g. as
```
uint16_t get_flysky_hall_adc_value(uint8_t ch) 
 { 
   if (ch >= FLYSKY_HALL_CHANNEL_COUNT) 
   { 
     return 0; 
   } 
#if defined(PCBNV14)
  if (ch < 2) // Just assuming, could also be ch >= 2, don't have NV14
  {
    return hall_adc_values[ch]; // Non-inverted
  }
 #endif
   return 2*FLYSKY_OFFSET_VALUE - hall_adc_values[ch];  // TX16S std. is all 4 channels inverted
 } 
 ```

**Comment by rotorman** [comment]
Thx for testing @pfeerick . So I clearly forgot something for NV14 target, need to figure out what.

**Comment by rotorman** [comment]
@pfeerick could you please re-test. Thx!
If that last commit does not fix it for NV14, then I am out of ideas unfortunately.

**Comment by pfeerick** [comment]
That unstuck it... sticks are responding normally again now ;)

**Comment by richardclli** [comment]
Seems this is part of hardware auto detection, looks nice.  Will test when I have some spare time, now focusing in working out the translations.

**Comment by rotorman** [comment]
@pfeerick thank you for testing, this is great news. Let's give this code/PR some days to ripe and for further testers give it a go before merging. Would be interesting to see:
a) that it does not break any B/W radio (shouldn't, but one knows for sure only after testing. I do not have (yet) any B/W to test myself, so am again dependant on testers)
b) Jumper T16
c) X10 & X12S (should hopefully not break anything)

**Comment by rburrow87** [comment]
My X10S Express seems to work fine still!

**Comment by rotorman** [comment]
@rburrow87 thank you for testing, much appreciated!

We still need feedback from B/W radio users, and ideally at least one Jumper T16 and X12S report would be sweet before merging. Thx!

**Comment by pfeerick** [comment]
I'll try on X9D+2019 and TX12 later today, then it's just the T16 & X12S left ;)

**Comment by rotorman** [comment]
Further test report from Ari via Discord, letting us know that X9d and T18 work as well: https://discord.com/channels/839849772864503828/839895574244229152/910516555568255056

**Pull request merged**
