### PR TITLE
Translated theme text

### PR DESCRIPTION
**Pull request by ulfhedlund**
Adds translation for theme edit texts.
Thank you @philmoz for helping out.

I can ping the translators once this is reviewed.

### CODE REVIEW

**Comment by pfeerick** [comment]
No complains of any consequence, translate away! And thanks :)

**Comment by ulfhedlund** [comment]
Hello translators, here is another PR that needs your input, this time for theme edit texts.
@ParkerEde DE
@Eldenroot CZ
@robustini IT
@zyren CN / TW
@ajjjjjjjj PL
@ToshihiroMakuuchi JP
@HThuren DA
@Pat6874 FR

Please provide your translations for the following:
#define TR_THEME_COLOR_DEFAULT         "DEFAULT"
#define TR_THEME_COLOR_PRIMARY1        "PRIMARY1"
#define TR_THEME_COLOR_PRIMARY2        "PRIMARY2"
#define TR_THEME_COLOR_PRIMARY3        "PRIMARY3"
#define TR_THEME_COLOR_SECONDARY1      "SECONDARY1"
#define TR_THEME_COLOR_SECONDARY2      "SECONDARY2"
#define TR_THEME_COLOR_SECONDARY3      "SECONDARY3"
#define TR_THEME_COLOR_FOCUS           "FOCUS"
#define TR_THEME_COLOR_EDIT            "EDIT"
#define TR_THEME_COLOR_ACTIVE          "ACTIVE"
#define TR_THEME_COLOR_WARNING         "WARNING"
#define TR_THEME_COLOR_DISABLED        "DISABLED"
#define TR_THEME_COLOR_CUSTOM          "CUSTOM"
#define TR_THEME_CHECKBOX              "Checkbox"
#define TR_THEME_ACTIVE                "Active"
#define TR_THEME_REGULAR               "Regular"
#define TR_THEME_WARNING               "Warning"
#define TR_THEME_DISABLED              "Disabled"
#define TR_THEME_EDIT                  "Edit"
#define TR_THEME_FOCUS                 "Focus"

**Comment by Pat6874** [comment]
Le 9 juin 2023, à 20:37, ulfhedlund ***@***.***> a écrit:FR

FR

#define TR_THEME_COLOR_DEFAULT "DEFAUT"
#define TR_THEME_COLOR_PRIMARY1 "PRIMAIRE 1"
#define TR_THEME_COLOR_PRIMARY2 "PRIMAIRE 2"
#define TR_THEME_COLOR_PRIMARY3 "PRIMAIRE 3"
#define TR_THEME_COLOR_SECONDARY1 "SECONDAIRE 1"
#define TR_THEME_COLOR_SECONDARY2 "SECONDAIRE 2"
#define TR_THEME_COLOR_SECONDARY3 "SECONDAIRE 3"
#define TR_THEME_COLOR_FOCUS "FOCUS"
#define TR_THEME_COLOR_EDIT "EDITER"
#define TR_THEME_COLOR_ACTIVE "ACTIF"
#define TR_THEME_COLOR_WARNING "ATTENTION"
#define TR_THEME_COLOR_DISABLED "DESACTIVE"
#define TR_THEME_COLOR_CUSTOM "PERSO"
#define TR_THEME_CHECKBOX "Case à cocher"
#define TR_THEME_ACTIVE "Actif"
#define TR_THEME_REGULAR "Par défaut"
#define TR_THEME_WARNING "Attention"
#define TR_THEME_DISABLED "Désactivé"
#define TR_THEME_EDIT "Editer"
#define TR_THEME_FOCUS "Focus"



Le 9 juin 2023, 20:37, à 20:37, ulfhedlund ***@***.***> a écrit:

**Comment by HThuren** [comment]
DA:

#define TR_THEME_COLOR_DEFAULT         "STANDARD"
#define TR_THEME_COLOR_PRIMARY1        "PRIMÆR1"
#define TR_THEME_COLOR_PRIMARY2        "PRIMÆR2"
#define TR_THEME_COLOR_PRIMARY3        "PRIMÆR3"
#define TR_THEME_COLOR_SECONDARY1      "SEKUNDÆR1"
#define TR_THEME_COLOR_SECONDARY2      "SEKUNDÆR2"
#define TR_THEME_COLOR_SECONDARY3      "SEKUNDÆR3"
#define TR_THEME_COLOR_FOCUS           "FOKUS"
#define TR_THEME_COLOR_EDIT            "REDIGER"
#define TR_THEME_COLOR_ACTIVE          "AKTIV"
#define TR_THEME_COLOR_WARNING         "ADVARSEL"
#define TR_THEME_COLOR_DISABLED        "DEAKTIV"
#define TR_THEME_COLOR_CUSTOM          "BRUGER STYRET"
#define TR_THEME_CHECKBOX              "Checkbox"
#define TR_THEME_ACTIVE                "Aktiv"
#define TR_THEME_REGULAR               "Almindelig"
#define TR_THEME_WARNING               "Advarsel"
#define TR_THEME_DISABLED              "Deaktiv"
#define TR_THEME_EDIT                  "Rediger"
#define TR_THEME_FOCUS                 "Fokus"

**Comment by ToshihiroMakuuchi** [comment]
JP:

#define TR_THEME_COLOR_DEFAULT "デフォルト"
#define TR_THEME_COLOR_PRIMARY1 "プライマリ 1"
#define TR_THEME_COLOR_PRIMARY2 "プライマリ 2"
#define TR_THEME_COLOR_PRIMARY3 "プライマリ 3"
#define TR_THEME_COLOR_SECONDARY1 "セカンダリ 1"
#define TR_THEME_COLOR_SECONDARY2 "セカンダリ 2"
#define TR_THEME_COLOR_SECONDARY3 "セカンダリ 3"
#define TR_THEME_COLOR_FOCUS "フォーカス"
#define TR_THEME_COLOR_EDIT "編集"
#define TR_THEME_COLOR_ACTIVE "有効"
#define TR_THEME_COLOR_WARNING "警告"
#define TR_THEME_COLOR_DISABLED "無効"
#define TR_THEME_COLOR_CUSTOM "カスタム"
#define TR_THEME_CHECKBOX "チェック"
#define TR_THEME_ACTIVE "有効"
#define TR_THEME_REGULAR "通常"
#define TR_THEME_WARNING "警告"
#define TR_THEME_DISABLED "無効"
#define TR_THEME_EDIT "編集"
#define TR_THEME_FOCUS "フォーカス"

**Comment by robustini** [comment]
IT

#define TR_THEME_COLOR_DEFAULT "DEFAULT"
#define TR_THEME_COLOR_PRIMARY1 "PRIMARIO1"
#define TR_THEME_COLOR_PRIMARY2 "PRIMARIO2"
#define TR_THEME_COLOR_PRIMARY3 "PRIMARIO3"
#define TR_THEME_COLOR_SECONDARY1 "SECONDARIO1"
#define TR_THEME_COLOR_SECONDARY2 "SECONDARIO2"
#define TR_THEME_COLOR_SECONDARY3 "SECONDARIO3"
#define TR_THEME_COLOR_FOCUS "FUOCO"
#define TR_THEME_COLOR_EDIT "MODIFICA"
#define TR_THEME_COLOR_ACTIVE "ATTIVO"
#define TR_THEME_COLOR_WARNING "ATTENZIONE"
#define TR_THEME_COLOR_DISABLED "DISABILITATO"
#define TR_THEME_COLOR_CUSTOM "PERSONALE"
#define TR_THEME_CHECKBOX "Casella di spunta"
#define TR_THEME_ACTIVE "Attivo"
#define TR_THEME_REGULAR "Regolare"
#define TR_THEME_WARNING "Attenzione"
#define TR_THEME_DISABLED "Disabilitato"
#define TR_THEME_EDIT "Modifica"
#define TR_THEME_FOCUS "Fuoco"

**Comment by ajjjjjjjj** [comment]
PL

#define TR_THEME_COLOR_DEFAULT "DOMYŚLNY"
#define TR_THEME_COLOR_PRIMARY1 "GŁÓWNY1"
#define TR_THEME_COLOR_PRIMARY2 "GŁÓWNY2"
#define TR_THEME_COLOR_PRIMARY3 "GŁÓWNY3"
#define TR_THEME_COLOR_SECONDARY1 "POBOCZNY1"
#define TR_THEME_COLOR_SECONDARY2 "POBOCZNY2"
#define TR_THEME_COLOR_SECONDARY3 "POBOCZNY3"
#define TR_THEME_COLOR_FOCUS "WYBRANY"
#define TR_THEME_COLOR_EDIT "ZMIEŃ"
#define TR_THEME_COLOR_ACTIVE "AKTYWNY"
#define TR_THEME_COLOR_WARNING "OSTRZEŻENIE"
#define TR_THEME_COLOR_DISABLED "WYŁĄCZONY"
#define TR_THEME_COLOR_CUSTOM "WŁASNY"
#define TR_THEME_CHECKBOX "Pole wyboru"
#define TR_THEME_ACTIVE "Aktywny"
#define TR_THEME_REGULAR "Normalny"
#define TR_THEME_WARNING "Ostrzeżenie"
#define TR_THEME_DISABLED "Wyłączony"
#define TR_THEME_EDIT "Zmień"
#define TR_THEME_FOCUS "Wybrany"

**Comment by ParkerEde** [comment]
DE
#define TR_THEME_COLOR_DEFAULT "Standard"
#define TR_THEME_COLOR_PRIMARY1 "Primär1"
#define TR_THEME_COLOR_PRIMARY2 "Primär2"
#define TR_THEME_COLOR_PRIMARY3 "Primär3"
#define TR_THEME_COLOR_SECONDARY1 "Sekundär1"
#define TR_THEME_COLOR_SECONDARY2 "Sekundär2"
#define TR_THEME_COLOR_SECONDARY3 "Sekundär3"
#define TR_THEME_COLOR_FOCUS "Fokus"
#define TR_THEME_COLOR_EDIT "Edit"
#define TR_THEME_COLOR_ACTIVE "Aktiv"
#define TR_THEME_COLOR_WARNING "Warnung"
#define TR_THEME_COLOR_DISABLED "Deaktiviert"
#define TR_THEME_COLOR_CUSTOM "CUSTOM"
#define TR_THEME_CHECKBOX "Schalter"
#define TR_THEME_ACTIVE "Aktiv"
#define TR_THEME_REGULAR "Regulär"
#define TR_THEME_WARNING "Warnung"
#define TR_THEME_DISABLED "Inaktiv"
#define TR_THEME_EDIT "Editieren"
#define TR_THEME_FOCUS "Fokus"

**Comment by pfeerick** [comment]
@offer-shmuely Would you mind doing Hebrew also? https://github.com/EdgeTX/edgetx/pull/3664#issuecomment-1584991882

**Comment by offer-shmuely** [comment]
#define TR_THEME_COLOR_DEFAULT "DEFAULT"
#define TR_THEME_COLOR_PRIMARY1 "ראשי 1"
#define TR_THEME_COLOR_PRIMARY2 "ראשי 2"
#define TR_THEME_COLOR_PRIMARY3 "ראשי 3"
#define TR_THEME_COLOR_SECONDARY1 "משני 1"
#define TR_THEME_COLOR_SECONDARY2 "משני 2"
#define TR_THEME_COLOR_SECONDARY3 "משני 3"
#define TR_THEME_COLOR_FOCUS "מיקוד"
#define TR_THEME_COLOR_EDIT "עריכה"
#define TR_THEME_COLOR_ACTIVE "פעיל"
#define TR_THEME_COLOR_WARNING "אזהרה"
#define TR_THEME_COLOR_DISABLED "לא פעיל"
#define TR_THEME_COLOR_CUSTOM "מתקדם"
#define TR_THEME_CHECKBOX "Checkbox"
#define TR_THEME_ACTIVE "פעיל"
#define TR_THEME_REGULAR "רגיל"
#define TR_THEME_WARNING "אזהרה"
#define TR_THEME_DISABLED "לא פעיל"
#define TR_THEME_EDIT "עריכה"
#define TR_THEME_FOCUS "מיקוד"

**Comment by offer-shmuely** [comment]
> @offer-shmuely Would you mind doing Hebrew also? https://github.com/EdgeTX/edgetx/pull/3664#issuecomment-1584991882

Sure, as long as it is not translating scripts...

**Comment by ulfhedlund** [comment]
@pfeerick: I have now added translations for all but CN/TW languages. 
I'll let you decide if we should wait for them or go ahead and merge.

**Comment by ulfhedlund** [comment]
@pfeerick: there are now proper translations except for CN/TW.
I'll let you decide whether to wait some more or merge without them. And sorry about the conflicts.

**Comment by pfeerick** [comment]
np about the conflicts, should be easy enough to figure out when it comes to merge. I'll give another day for CN/TW and then merge tomorrow sometime. *What doesn't happen today can happen tomorrow...* 🤭

**Comment by zyren** [comment]
CN
'''
#define TR_THEME_COLOR_DEFAULT      "默认"
#define TR_THEME_COLOR_PRIMARY1     "主色1"
#define TR_THEME_COLOR_PRIMARY2     "主色2"
#define TR_THEME_COLOR_PRIMARY3     "主色3"
#define TR_THEME_COLOR_SECONDARY1   "副色1"
#define TR_THEME_COLOR_SECONDARY2   "副色2"
#define TR_THEME_COLOR_SECONDARY3   "副色3"
#define TR_THEME_COLOR_FOCUS        "焦点"
#define TR_THEME_COLOR_EDIT         "编辑"
#define TR_THEME_COLOR_ACTIVE       "激活"
#define TR_THEME_COLOR_WARNING      "警告"
#define TR_THEME_COLOR_DISABLED     "禁用"
#define TR_THEME_COLOR_CUSTOM       "自定义"
#define TR_THEME_CHECKBOX           "复选框"
#define TR_THEME_ACTIVE             "激活"
#define TR_THEME_REGULAR            "常规"
#define TR_THEME_WARNING            "警告"
#define TR_THEME_DISABLED           "禁用"
#define TR_THEME_EDIT               "编辑"
#define TR_THEME_FOCUS              "焦点"
'''

TW
'''
#define TR_THEME_COLOR_DEFAULT      "默認"
#define TR_THEME_COLOR_PRIMARY1     "主色1"
#define TR_THEME_COLOR_PRIMARY2     "主色2"
#define TR_THEME_COLOR_PRIMARY3     "主色3"
#define TR_THEME_COLOR_SECONDARY1   "副色1"
#define TR_THEME_COLOR_SECONDARY2   "副色2"
#define TR_THEME_COLOR_SECONDARY3   "副色3"
#define TR_THEME_COLOR_FOCUS        "焦點"
#define TR_THEME_COLOR_EDIT         "編輯"
#define TR_THEME_COLOR_ACTIVE       "激活"
#define TR_THEME_COLOR_WARNING      "警告"
#define TR_THEME_COLOR_DISABLED     "禁用"
#define TR_THEME_COLOR_CUSTOM       "自定義"
#define TR_THEME_CHECKBOX           "復選框"
#define TR_THEME_ACTIVE             "激活"
#define TR_THEME_REGULAR            "常規"
#define TR_THEME_WARNING            "警告"
#define TR_THEME_DISABLED           "禁用"
#define TR_THEME_EDIT               "編輯"
#define TR_THEME_FOCUS              "焦點"
'''

**Comment by zyren** [comment]
@ulfhedlund 
@pfeerick
I'm very sorry. I've been so busy the last few days that I just saw the notice.

**Comment by ulfhedlund** [comment]
No worries @zyren. We will wait for your translations.

**Comment by ulfhedlund** [comment]
@pfeerick: All translators have now contributed, so ready to merge when you so decide.

**Comment by pfeerick** [comment]
> @ulfhedlund @pfeerick I'm very sorry. I've been so busy the last few days that I just saw the notice.

No apologies are necessary, we all do what we can, when we can :) Thank you for getting this in before review for merge, one less translation to catch up on ;)

**Pull request merged**
