### PR TITLE
Translate bootloader

### PR DESCRIPTION
**Pull request by HThuren**
Translate language shown when Bootloader are active.

Notice: Special chars are not working well at bootloader envoriment, translate without them, ie. ascii only.

### CODE REVIEW

**Comment by Eldenroot** [comment]
I will add CZ translation in 3 days, I am on Christmas holidays and visiting my family

**Comment by HThuren** [comment]
> I will add CZ translation in 3 days, I am on Christmas holidays and visiting my family

Making code are holyday joy for me :-)

**Comment by gagarinlg** [comment]
> > I will add CZ translation in 3 days, I am on Christmas holidays and visiting my family
> 
> Thank you. Making code are holyday joy for me :-)

Same here

**Comment by robustini** [comment]
PR created in your fork.

**Comment by ulfhedlund** [comment]
PR for Swedish translations created in your fork

**Comment by TheIsotopes** [comment]
PR for DE translation in your fork

**Comment by ToshihiroMakuuchi** [comment]
Sorry for the delay in working on this.
PR for JP translation in your fork.

**Comment by HThuren** [comment]
> Sorry for the delay in working on this. PR for JP translation in your fork.

No worry at all, thank you for contribute..

**Comment by HThuren** [comment]
My mistake, found TR_DISABLE when resolve the code :-)

**Comment by HThuren** [comment]
Hi @Eldenroot, @zyren and @ajjjjjjjj , maybe you have the option to translate, please :-)

**Comment by Eldenroot** [comment]
@HThuren - buddy, I have already made a PR many days ago :)

**Comment by HThuren** [comment]
> @HThuren - buddy, I have already made a PR many days ago :)

Gosh, sorry, you did :-)

**Comment by ajjjjjjjj** [comment]
PL

`#define TR_DISABLE "Wyłączone"`
```
// Bootloader common
#define TR_BL_USB_CONNECT_BOOT        CENTER "\011USB połączone"
#define TR_BL_USB_CONNECTED           "USB połączone"
#define TR_BL_USB_PLUGIN              "lub podłącz kabel USB"
#define TR_BL_USB_MASS_STORE          "dla trybu danych"
#define TR_BL_USB_PLUGIN_MASS_STORE   "lub podłącz kabel USB dla trybu danych"
#define TR_BL_WRITE_FW                "Zapis firmware"
#define TR_BL_FORK                    "Fork:"
#define TR_BL_VERSION                 "Wersja:"
#define TR_BL_RADIO                   "Radio:"
#define TR_BL_EXIT                    "Wyjdź"
#define TR_BL_DIR_MISSING             " Brak katalogu"
#define TR_BL_DIR_EMPTY               " Katalog jest pusty"

#if LCD_W >= 480
  #define TR_BL_INVALID_FIRMWARE       "Nieprawidłowy plik firmware"
#elif LCD_W >= 212
  #define TR_BL_OR_PLUGIN_USB_CABLE    TR_BL_USB_PLUGIN_MASS_STORE
  #define TR_BL_HOLD_ENTER_TO_START    "\012Przytrzymaj [ENT] by zacząć zapis"
  #define TR_BL_INVALID_FIRMWARE       "\011Nieprawidłowy plik firmware!      "
  #define TR_BL_INVALID_EEPROM         "\011Nieprawidłowy plik EEPROM!        "
#else
  #define TR_BL_OR_PLUGIN_USB_CABLE    TR_BL_USB_PLUGIN
  #define TR_BL_HOLD_ENTER_TO_START    "\006Przytrzymaj [ENT] by zacząć"
  #define TR_BL_INVALID_FIRMWARE       "\004011Nieprawidłowy firmware!   "
  #define TR_BL_INVALID_EEPROM         "\004011Nieprawidłowy EEPROM!     "
#endif

#if defined(PCBTARANIS)
   // Bootloader Taranis specific
  #define TR_BL_RESTORE_EEPROM        "Przywróć EEPROM"
  #define TR_BL_WRITING_FW            CENTER "\015Zapis..."
  #define TR_BL_WRITING_COMPL         CENTER "\007Zapis ukończony"
  #if defined(RADIO_COMMANDO8)
    #define TR_BL_POWER_KEY           "Naciśnij przycisk Power"
    #define TR_BL_FLASH_EXIT          "Wyjdź z trybu flashowania"
  #endif
#elif defined(PCBHORUS)
   // Bootloader Horus specific
  #define TR_BL_WRITING_FW            "Zapis firmware ..."
  #define TR_BL_WRITING_COMPL         "Zapis ukończony"
  #define TR_BL_SELECT_KEY            "[ENT] aby wybrać plik"
  #define TR_BL_FLASH_KEY             "Przytrzymaj [ENT] aby flashować"
  #define TR_BL_EXIT_KEY              "[RTN] aby wyjść"
#elif defined(PCBNV14)
   // Bootloader NV14 specific
  #define TR_BL_WRITING_FW            "Zapis firmware ..."
  #define TR_BL_WRITING_COMPL         "Zapis ukończony"
  #define TR_BL_RF_USB_ACCESS         "Dostęp RF USB"
  #define TR_BL_CURRENT_FW            "Obecny firmware:"
  #define TR_BL_SELECT_KEY            "[R TRIM] aby wybrać plik"
  #define TR_BL_FLASH_KEY             "Przytrzymaj [R TRIM] aby flashować"
  #define TR_BL_EXIT_KEY              " [L TRIM] aby wyjść"
#endif
```

**Comment by zyren** [comment]
********************************************************************
CN

#define TR_DISABLE                     "禁用"


// Bootloader common
#define TR_BL_USB_CONNECT_BOOT        CENTER "\011USB已连接"
#define TR_BL_USB_CONNECTED           "USB已连接"
#define TR_BL_USB_PLUGIN              "或插入USB电缆"
#define TR_BL_USB_MASS_STORE          "作为移动存储"
#define TR_BL_USB_PLUGIN_MASS_STORE   "或插入USB电缆作为移动存储"
#define TR_BL_WRITE_FW                "写入固件"
#define TR_BL_FORK                    "代码分支:"
#define TR_BL_VERSION                 "固件版本:"
#define TR_BL_RADIO                   "遥控型号:"
#define TR_BL_EXIT                    "退出"
#define TR_BL_DIR_MISSING             "文件夹错误"
#define TR_BL_DIR_EMPTY               "空文件夹"

#if LCD_W >= 480
  #define TR_BL_INVALID_FIRMWARE       "无效的固件文件"
#elif LCD_W >= 212
  #define TR_BL_OR_PLUGIN_USB_CABLE    TR_BL_USB_PLUGIN_MASS_STORE
  #define TR_BL_HOLD_ENTER_TO_START    "\012长按 [ENT] 写入固件"
  #define TR_BL_INVALID_FIRMWARE       "\011无效的固件文件!        "
  #define TR_BL_INVALID_EEPROM         "\011无效的EEPROM文件!          "
#else
  #define TR_BL_OR_PLUGIN_USB_CABLE    TR_BL_USB_PLUGIN
  #define TR_BL_HOLD_ENTER_TO_START    "\006长按 [ENT] 开始"
  #define TR_BL_INVALID_FIRMWARE       "\004无效的固件文件!        "
  #define TR_BL_INVALID_EEPROM         "\004无效的EEPROM文件!          "
#endif

#if defined(PCBTARANIS)
   // Bootloader Taranis specific
  #define TR_BL_RESTORE_EEPROM        "恢复EEPROM"
  #define TR_BL_WRITING_FW            CENTER "\015正在写入固件..."
  #define TR_BL_WRITING_COMPL         CENTER "\007固件写入成功"
  #if defined(RADIO_COMMANDO8)
    #define TR_BL_POWER_KEY           "按下电源键."
    #define TR_BL_FLASH_EXIT          "退出刷机模式."
  #endif
#elif defined(PCBHORUS)
   // Bootloader Horus specific
  #define TR_BL_WRITING_FW            "正在写入固件 ..."
  #define TR_BL_WRITING_COMPL         "固件写入成功"
  #define TR_BL_SELECT_KEY            "按 [ENT] 选择文件"
  #define TR_BL_FLASH_KEY             "长按 [ENT] 写入固件"
  #define TR_BL_EXIT_KEY              "按 [RTN] 退出"
#elif defined(PCBNV14)
   // Bootloader NV14 specific
  #define TR_BL_WRITING_FW            "写入固件 ..."
  #define TR_BL_WRITING_COMPL         "写入成功"
  #define TR_BL_RF_USB_ACCESS         "访问射频USB"
  #define TR_BL_CURRENT_FW            "当前固件:"
  #define TR_BL_SELECT_KEY            "右 [TRIM] 选择文件"
  #define TR_BL_FLASH_KEY             "长按右 [TRIM] 写入固件"
  #define TR_BL_EXIT_KEY              "按左 [TRIM] 退出"
#endif
********************************************************************
********************************************************************
TW

#define TR_DISABLE                     "禁用"


// Bootloader common
#define TR_BL_USB_CONNECT_BOOT        CENTER "\011USB已連接"
#define TR_BL_USB_CONNECTED           "USB已連接"
#define TR_BL_USB_PLUGIN              "或插入USB電纜"
#define TR_BL_USB_MASS_STORE          "作為移動存儲"
#define TR_BL_USB_PLUGIN_MASS_STORE   "或插入USB電纜作為移動存儲"
#define TR_BL_WRITE_FW                "寫入韌軆"
#define TR_BL_FORK                    "代碼分支:"
#define TR_BL_VERSION                 "韌軆版本:"
#define TR_BL_RADIO                   "遙控型號:"
#define TR_BL_EXIT                    "退出"
#define TR_BL_DIR_MISSING             "目錄錯誤"
#define TR_BL_DIR_EMPTY               "空目錄"

#if LCD_W >= 480
  #define TR_BL_INVALID_FIRMWARE       "無效的韌軆文件"
#elif LCD_W >= 212
  #define TR_BL_OR_PLUGIN_USB_CABLE    TR_BL_USB_PLUGIN_MASS_STORE
  #define TR_BL_HOLD_ENTER_TO_START    "\012長按 [ENT] 寫入韌軆"
  #define TR_BL_INVALID_FIRMWARE       "\011無效的韌軆文件!        "
  #define TR_BL_INVALID_EEPROM         "\011無效的EEPROM文件!          "
#else
  #define TR_BL_OR_PLUGIN_USB_CABLE    TR_BL_USB_PLUGIN
  #define TR_BL_HOLD_ENTER_TO_START    "\006長按 [ENT] 開始"
  #define TR_BL_INVALID_FIRMWARE       "\004無效的韌軆文件!        "
  #define TR_BL_INVALID_EEPROM         "\004無效的EEPROM文件!          "
#endif

#if defined(PCBTARANIS)
   // Bootloader Taranis specific
  #define TR_BL_RESTORE_EEPROM        "恢復EEPROM"
  #define TR_BL_WRITING_FW            CENTER "\015正在寫入韌軆..."
  #define TR_BL_WRITING_COMPL         CENTER "\007韌軆寫入成功"
  #if defined(RADIO_COMMANDO8)
    #define TR_BL_POWER_KEY           "按下電源鍵."
    #define TR_BL_FLASH_EXIT          "退出刷機模式."
  #endif
#elif defined(PCBHORUS)
   // Bootloader Horus specific
  #define TR_BL_WRITING_FW            "正在寫入韌軆 ..."
  #define TR_BL_WRITING_COMPL         "韌軆寫入成功"
  #define TR_BL_SELECT_KEY            "按 [ENT] 選擇文件"
  #define TR_BL_FLASH_KEY             "長按 [ENT] 寫入韌軆"
  #define TR_BL_EXIT_KEY              "按 [RTN] 退出"
#elif defined(PCBNV14)
   // Bootloader NV14 specific
  #define TR_BL_WRITING_FW            "寫入韌軆 ..."
  #define TR_BL_WRITING_COMPL         "寫入成功"
  #define TR_BL_RF_USB_ACCESS         "訪問射頻USB"
  #define TR_BL_CURRENT_FW            "當前韌軆:"
  #define TR_BL_SELECT_KEY            "右 [TRIM] 選擇文件"
  #define TR_BL_FLASH_KEY             "長按右 [TRIM] 寫入韌軆"
  #define TR_BL_EXIT_KEY              "按左 [TRIM] 退出"
#endif
********************************************************************

**Comment by HThuren** [comment]
hi @pfeerick , happy newyear :-)
ready to merge

**Comment by gagarinlg** [comment]
Do the east asian versions fit into the flash and is the font file included in the bootloader builds?

**Comment by HThuren** [comment]
> Do the east asian versions fit into the flash and is the font file included in the bootloader builds?

Not sure what you ask for, but no change to font file, there you might have a point. 
I make some test

**Comment by HThuren** [comment]
> > Do the east asian versions fit into the flash and is the font file included in the bootloader builds?

I did the notice in top of PR: Notice: Special chars are not working well at bootloader envoriment, translate without them.
But forget it regarding the asian translation. I make a rollback of them. Sorry to @zyren for wasted work. But also @ajjjjjjjj must consider not to use ć.

**Comment by ajjjjjjjj** [comment]
@HThuren, updated.

**Comment by HThuren** [comment]
> updated to skip diacritics

Very fast response, thank you,  :-)

**Comment by Eldenroot** [comment]
CZ is fine? I have tried to not use special symbols...

**Comment by HThuren** [comment]
> CZ is fine? I have tried to not use special symbols... but sometimes it is not possible, there is no other similar word.

I made a test with danish special chars, the are just not shown, if you are ok with that, no change are needed.

**Comment by Eldenroot** [comment]
Hmm, not good, because some words will not make sense.

Which symbols are not usable? All with "ˇ" and "´" etc.? So something like ř, č, š, ě, ý, á, í, é ? Or some of them are working?

**Comment by gagarinlg** [comment]
just stick to ASCII please. The amount of flash reserved for the bootloader is relatively small, to have more space for the real firmware. If we need additional space for characters it might get tight.

**Comment by HThuren** [comment]
> Hmm, not good, because some words will not make sense.
> 
> Which symbols are not usable? All with "ˇ" and "´" etc.? So something like ř, č, š, ě, ý, á, í, é ? Or some of them are working?

I'm sorry, but afraid none of them will work. Myself had to make some compromise when translated to Danish, not the best language, but to understand.

**Comment by Eldenroot** [comment]
@HThuren - ok, so please sync your fork with these changes and I will make a PR. thx

**Comment by Eldenroot** [comment]
@HThuren - PR opened

**Comment by HThuren** [comment]
Right, now the bootloader messages are prefered in ascii, and some mix with TR_ENABLE - as used and to be translated - are removed from all *.h translationsfiles. Now 2 new define TR_BL_ENABLE and TR_BL_DISABLE and to be kept in ascii.
Sorry to CN, TW and JP translators, not possible to translate to non ascii in bootloader envoriment.
I belive the PR are ready to merge now.

**Comment by HThuren** [comment]
hi @pfeerick , are you ready to merge this one, will be nice to get it done.

**Comment by HThuren** [comment]
Hi @gagarinlg, @Eldenroot  and @pfeerick do you think this PR are ready to merge, or you maybe will review and comment ?

**Comment by Eldenroot** [comment]
I am fine - CZE lang.

If anything I create a new PR, but for now it seems fine :), thank you!

**Comment by HThuren** [comment]
Hi  @pfeerick, I am worried about this 4 week old PR will seperate too much with the change in every language file, from the aftercomming changes. 
Any chance to have this PR merged ? Anything I can do to help ?

**Comment by pfeerick** [comment]
I've been mostly holding off on this PR until 2.8.1 was finally out of the way, and some other necessary changes in `main` which free up flash space, as I don't know how impact this will have on firmware build sizes. I'll be reviewing this PR in the next few days to see what hte implications are, as well as clearing up the PT conflict (minor - single line change).

**Comment by HThuren** [comment]
> I've been mostly holding off on this PR until 2.8.1 was finally out of the way, and some other necessary changes in `main` which free up flash space, as I don't know how impact this will have on firmware build sizes (particularly an issue for the radios like X9D which are close to the limit - and actually were OVER that in 2.8.0 😮). I'll be reviewing this PR in the next few days to see what the implications are, as well as clearing up the PT conflict (minor - single line change).

Very to understand, in fact I din not use the const char STRxx[]=TR_xx; and made the reference to STRxx just to not increase size in firmware. Look forward to your review :-)

**Comment by pfeerick** [comment]
All languages still build with this PR, and in fact, wit hthe worst case x9dp-CZ build, it seems like this actually brought the size down slightly from the current `main` build (which would have had an EN bootloader)... (and yes, I know, `.text` isn't the only metric to look at, but it is the most revealing in this instance... 16 bytes smaller firmware file for x9dp `TW` isn't so exciting 😆 ). 

main vs this PR
image

In contrast, TX16S went up slightly, but we have space to play with there. 
main vs this PR
image

**Pull request merged**
