### PR TITLE
Changes as to PR 2109

### PR DESCRIPTION
**Pull request by HThuren**
Summary of changes:
Danish changes as PR 2109 and 1891

### CODE REVIEW

**Comment by pfeerick** [comment]
I rebased this as the `libopenui` shouldn't have been there... I think you spotted it at the same time and were trying to do it through a merge commit which won't do it.

**Comment by HThuren** [comment]
Yes, the libopenui was unexpected, and I merged with master to get trid of it.
Thanks for the correction.

**Comment by pfeerick** [comment]
Yeah, submodules are...  messy... once out of sync and caught in a commit it's a pain to get it back on track.

**Comment by pfeerick** [comment]
I just built this locally as the build system only builds English, and realised that a few more additions/changes were missing (using TX16S target). Feel free to make corrections as I only did it in English. 😉 Will merge in the morning if there are no further changes needed.

**Comment by HThuren** [comment]
Now changed da.h acording to PR 1744, compile well locally

**Comment by HThuren** [comment]
Thank you :-)

**Pull request merged**
