### PR TITLE
RSSI label translation

### PR DESCRIPTION
**Pull request by ulfhedlund**
Added translation for RSSI label, used on the Telemetry page. Was hard coded to "Rx-Stats".
New translation string: TR_RSSI_LABEL "Rx Status"

### CODE REVIEW

**Comment by ulfhedlund** [comment]
Hi translators, if you wish to add your translation instead of the default, let me know.

EN: #define  TR_RSSI_LABEL  "Rx Status"

@ParkerEde DE
@Eldenroot CZ
@robustini IT
@zyren CN / TW
@ajjjjjjjj PL
@ToshihiroMakuuchi JP
@HThuren DA
@Pat6874 FR

**Comment by HThuren** [comment]
DA:
#define TR_RSSI_LABEL "Rx status"

**Comment by Eldenroot** [comment]
CZ:

TR_RSSI_LABEL "Rx stav"

**Comment by ajjjjjjjj** [comment]
PL:
`#define TR_RSSI_LABEL "Status Rx"`

**Comment by pfeerick** [comment]
I'll need to investigate this further, but this will likely not be accepted in its current form. `getRssiLabel()` was supposed to return different strings dependent on the link in use, but that has changed - I think it may have been an oversight when thinking that rather than it be hardcoded the telemetry protocol in use should inform on the name, but that part not written yet, so something like the original code may need to be reinstated. That's one reason it's not a good idea to ping translators until we know if the PR is in the right shape for translation yet. 

https://github.com/EdgeTX/edgetx/blob/2d8d7494f37d5c81c1342e59860e9f1995fe57ec/radio/src/telemetry/telemetry.h#L134-L157

**Comment by ulfhedlund** [comment]
OK, I see. I thought it was an unusual way of assigning a label.

In this case the translators were unnecessarily pinged, in other cases they are not pinged at all...

**Comment by HThuren** [comment]
No worry from me :-)

**Comment by zyren** [comment]
******************************************************
CN

#define TR_RSSI_LABEL "接收机状态"
******************************************************
******************************************************
TW

#define TR_RSSI_LABEL "接收機狀態"
*****************************************************

**Comment by ToshihiroMakuuchi** [comment]
JP

#define TR_RSSI_LABEL "受信状態"

**Comment by Pat6874** [comment]
hello,

in french:
#define TR_RSSI_LABEL "Statut Rx"

Le dim. 23 avr. 2023 à 11:25, まっく まるちぷろとこる ***@***.***> a
écrit :

**Comment by mha1** [comment]
@pfeerick please check out https://github.com/EdgeTX/edgetx/pull/3523, (requires https://github.com/EdgeTX/libopenui/pull/90)

**Comment by pfeerick** [comment]
Closing, as now merged https://github.com/EdgeTX/edgetx/pull/3523 re-implements and enhances protocol-specific RX signal strength name/units

**Pull request closed without merging**
