### PR TITLE
avoid compile warning

### PR DESCRIPTION
**Pull request by olliw42**
interesting for how long this one could persist ... ;)

### CODE REVIEW

**Comment by pfeerick** [comment]
lol... is a duplicate of the fix I did in https://github.com/EdgeTX/edgetx/pull/426 ... although I cast the other variable since it will always be never be less than zero. Looks like it was just merged, so if you think casting the other side is better, this will need rebasing.

**Comment by olliw42** [comment]
ähm ... indeed ... I fetched the latest few "moments" ago and it was till there ... few moments can be a long time as it seems LOL

I indeed think that casting the size is more cleaner

**Comment by pfeerick** [comment]
Rebase and push again, and I'll merge when I see it (will be AFK for a little while) as I do agree... better to make the STL just do the comparison it's told to do ;) I thought I'd tried that and got compile error, but might have been using the alternate cast syntax also...

**Comment by raphaelcoeffic** [comment]
@olliw42 sorry for that! I was obsessed by the touch sensor issue lately....

**Comment by pfeerick** [comment]
The PR is only 30 minutes old... I think he might mean how long the warning has been there... like one of the others he fixed...

**Comment by olliw42** [comment]
>  I think he might mean how long the warning has been there... like one of the others he fixed...

yes :+1:

**Comment by raphaelcoeffic** [comment]
> > I think he might mean how long the warning has been there... like one of the others he fixed...
> 
> yes 👍
> 
> sorry if my wording was misleading

And I confused this PR for another I left untouched for weeks 😝

**Comment by olliw42** [comment]
@pfeerick 
just looked only now at https://github.com/EdgeTX/edgetx/commit/da661a6e031bde68e093ccc0bfb6e44368c19026
I think typecasting to (unsigned) would be even a bug, if at all it should have been typecasted to size_t

**Comment by pfeerick** [comment]
> deleted, I might have been talking nonsense

What did I miss? 🤣

*Maybe I should have taken the hint, in denying it ever happened...*

**Comment by olliw42** [comment]
@pfeerick 
my comment was that I was just looking this morning at the alternative in https://github.com/EdgeTX/edgetx/commit/da661a6e031bde68e093ccc0bfb6e44368c19026 and that typecasting index to an unsigned is potentially rather a bug.
The size of std list is typically of type size_t which is an int, but I reminded me that this here is gcc and that I wasn't totally sure, so I deleted.
Whatever it is, I have a strengthened believe that doing as here is the better solution... ;)

**Comment by pfeerick** [comment]
```
/src/radio/src/gui/colorlcd/model_select.cpp:275:34: warning: comparison of integer expressions of different signedness: 'const int' and 'std::__cxx11::list<ModelCell*>::size_type' {aka 'unsigned int'} [-Wsign-compare]
  275 |                     update(index < category->size() - 1 ? index : index - 1);
      |                            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~

```

I often find it helps if you actually look at the warnings given by the compiler... it actually *says* the type it was expecting to see on both sides of the comparision... `unsigned int` and since we know that index is an int (initalised to 0)

https://github.com/EdgeTX/edgetx/blob/24f85545904ff97e6901ac23247489444ccb91cb/radio/src/gui/colorlcd/model_select.cpp#L223

, it means ` category->size() ` is returning a `unsigned int`. Since it never appears to be driven negative, it is probably fine, but I bet after you have 127 categories(!!) on your Tx it would become a problem (not!) ... so better to make the `category->size()` return a sensible type in this instance just in case it does get driven negative for some reason. 

Part of the reason for the discussion is still waiting you to rebase so this can be merged...  :-P

**Comment by olliw42** [comment]
yes, it is always good to look at warnings
and yes, the warning, if I had it in mind, would have told me what it would be
but no, doing straightforwardly what the warning may suggest is not always a correct solution. The warning can't decipher the context. I uphold that typecasting to unit is rather a bug 
(the problem is not that size is never driven to negative, but the subtraction of -1)(-1 would be converted to UINT_MAX, and the < would never trigger anymore).

> Part of the reason for the discussion is still waiting you to rebase so this can be merged... :-P

ohhh ... I totally missed that ... given me a moment ...

**Comment by pfeerick** [comment]
If you're unsure how do rebase, I should be able (if github lets me push it as I've already rebased this commit locally).

**Comment by olliw42** [comment]
well, rebasing a pushed pr is indeed something I'm "unsure" of ... also because all of the big red warnings in any tutorial that this is the one thing you never want to do ... I just merged in latest master, so should at least work now

**Comment by pfeerick** [comment]
lol... yeah, this is actually a case were you should probably rebase, not merge in particular... it's breaking as the submodule references haven't been updated... still pointing to the submodule version for libopenui that it was pointing to at the time you made this PR...

**Comment by olliw42** [comment]
no ... I screwed it up ... for some reason this edgetx repo is behaving than all the other repos I'm working with ... I close and just redo ... sorry

**Comment by pfeerick** [comment]
Rebase basically reapplies your commits on top of the branch you are rebasing from (i.e. 2.4). So for example, with this PR, git removes your commits, pulls in 2.4, and then re-applies your commits on top of 2.4 with no merge messages or anything. In other words, it re-applies your commits on top of 2.4. This does mean you get merge issues due to things changing in the mean time, i.e. the line you want to change is different to what it was, so you then 'resolve' that issue, and then you can force push the branch to update it on github. 

It's not something you should do if you are working on a PR or branch with other collaborators, as it will screw with their ability to work on the code royaly... but for stuff you are the sole author of, it is perfect for getting things back in sync (and without numerous 'merge commit' noise)

**Comment by olliw42** [comment]
so, you are saying that these big red warning bells do not apply to pushed PRs !?! ... I'll try that the next time, and see what happens LOL

**Comment by pfeerick** [comment]
The warning bells don't apply if you're the sole author... as rebasing is essentially re-writing history, for example, so if I were collaborating with you, it would break my copy of the branch when you rebase... 

A simple  PR like this is perfect to try it out on... worst that can happen is you make a mess of it, and have to do a new PR for that one line change ;) Then at least you get to find out if it works for your preferred workflow, or if it should be avoided.

**Pull request closed without merging**
