### PR TITLE
Fix for #197

### PR DESCRIPTION
**Pull request by eshifri**

### CODE REVIEW

**Comment by eshifri** [comment]
The change is in the libopenui. 
I guess cannot be delivered from here.

**Comment by pfeerick** [comment]
Did you try to edit the file directly instead of editing it in the right repo? libopenui is in another repo, and is submoduled... maybe make the change there? https://github.com/EdgeTX/libopenui/blob/master/src/numberedit.cpp

**Comment by eshifri** [comment]
Created a fork of libopenui and created pull request.

**Comment by pfeerick** [comment]
Closing since it's now over in https://github.com/EdgeTX/libopenui/pull/5, which has been merged btw ;)

**Pull request closed without merging**
