### PR TITLE
Fixed clearing curves

### LINKED ISSUE #1295: Issue after "clear" curves
There is an issue at the curves.
Tested with EdgeTX 2.5 and 2.6 Nighties. Everything is fine at openTX 2.3.14.
Same result with Companion Simulator or Radio (both TX16s)

Test:
modify Curve 1 - fine to this point. You can edit Curve 1 again without issue
"clear" Curve 1 - fine to this point. 
modify Curve 1 again
now Curve 2 or 3 appears by itself with random values - ISSUE !

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #1295

Summary of changes:
- "Clear curve" now correctly handles shifts in global point array.
- Change applied to B&W targets as well.

### CODE REVIEW

**Comment by pfeerick** [comment]
- [ ] TX16S - simu and hardware - unable to reproduce curve related corruption any more, mirroring still works. 
- [ ] T-Pro

**Comment by pfeerick** [comment]
This looks good to me... just asking since you've just touched curves - any chance you can kick this one? https://github.com/EdgeTX/edgetx/issues/1125

**Comment by raphaelcoeffic** [comment]
> This looks good to me... just asking since you've just touched curves - any chance you can kick this one?

*done*

**Comment by pfeerick** [comment]
Perfect! :) Knew it would be something stupidly simply like that...

**Pull request merged**
