### PR TITLE
Yaml support

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This is a continuation of #3.

### CODE REVIEW

**Comment by elecpower** [comment]
Add each model's checklist to YAML file?
Currently it is an independent file with its name based on the model name.
Issues:
- renaming the model breaks the link
- Companion reading models and settings from radio does not read and transfer the checklist file (maybe it should?) and vice versa. Manual step to transfer and edit in Companion.

**Comment by raphaelcoeffic** [comment]
> Add each model's checklist to YAML file?
> Currently it is an independent file with its name based on the model name.
> Issues:
> 
> * renaming the model breaks the link
> * Companion reading models and settings from radio does not read and transfer the checklist file (maybe it should?) and vice versa. Manual step to transfer and edit in Companion.

We need to be really careful with this. ATM, the YAML parser on radio is limited to “short” strings to keep the memory consumption low. We shall see very soon if it can be extended to support this kind of things. The good point about the separate file is that most people are comfortable with editing simple text files, rather than editing YAML. We will see how that develops.

**Comment by elecpower** [comment]
Just a thought bubble moment. Better to put ideas out there now. Though I might consider an enhancement to Companion.

**Comment by pfeerick** [comment]
We've discussed this in DM but for completeness, I believe all the new model issues are now resolved. And thank you for fixing the slider inversion and source/logical switch madness ;)

**Comment by pfeerick** [comment]
Oh popsicles! Mixes are fine now... but logical switch V1/V2 values are still changing for that model bin in question... :-/ It's jumping in increments of around 10 per power cycle or model unselect and re-select. but only appears to be an issue when they are logical switch indexes... switches/sources look to be fine.  😮 😆

**Comment by raphaelcoeffic** [comment]
> Oh popsicles! Mixes are fine now... but logical switch V1/V2 values are still changing for that model bin in question... :-/ It's jumping in increments of around 10 per power cycle or model unselect and re-select. but only appears to be an issue when they are logical switch indexes... switches/sources look to be fine. 😮 😆

Fixed, as well as the issue with the `Value` widget source.

**Comment by pfeerick** [comment]
Caught this when testing on TX12, but to TX16S also:

image

becomes

image


i.e. switch and action are right, parameter and enable state are wrong

Also

image

has changed from inc/dec to constant
image


Not sure if any others... tried a few random SFs and more wacky combos and seemed fine. Every else seems to be converting just fine.

**Comment by raphaelcoeffic** [comment]
> i.e. switch and action are right, parameter and enable state are wrong
> has changed from inc/dec to constant

Both should be fixed now (backed by unit tests).

**Comment by jfrickmann** [comment]
I had a compile failure due to missing `const` in front of `char *`s in `patchFilenameToYaml` and `convertBinModelData`. 
Also, I had a problem running the simu. If I edit my model in Companion (built from main on WSL using Docker) everything looks OK, but if I open the model edit menu in the simu, all the logical switches are gone, and they also do not appear to be processed. I wonder if that is also somehow related to YAML?

**Comment by wjcbsr** [comment]
Are there any plans to make companion YAML compatible?  If so,  what is the ETA?

**Comment by raphaelcoeffic** [comment]
> Are there any plans to make companion YAML compatible? If so, what is the ETA?

No worry, it’s being worked on, just takes time.

**Comment by wjcbsr** [comment]
I know.  Sorry to bug you.  Thank-you for responding.  I’ll rry and be patient ;-)

**Comment by wimalopaan** [comment]
Looks like there is one more : #1205

**Pull request merged**
