### PR TITLE
refactor: bootloader & cmake cleanup

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Merge after #5233

### CODE REVIEW

**Comment by richardclli** [comment]
> _ No description provided. _

See if you can rebase this after my nb4+ PR, I have refactorized Flysky based bootloader as well, not sure what you will break.

**Comment by raphaelcoeffic** [comment]
> See if you can rebase this after my nb4+ PR

Is this #5095 ? I don't see much conflicts there, it should go smooth.

**Review by pfeerick — CHANGES_REQUESTED** [review]
It looks nice, but can I have the bootloader back please? I wasn't expecting optimisations to remove the ability to actually _enter/use_ the bootloader :zany_face: 

TX16S actually tries, but just halts on a grey screen.
T20, PL18EV just ignore bootloader request and boot normally
EL18 started, but I can't test bootloader due to failed trim hats

**Review by pfeerick — COMMENTED** [review]
TX16S, T20, X9D+2019, TX12, EL18 (the one with non-broken trims :hand_over_mouth: ) all good now.

NV14 won't boot, but doesn't with main, so unrelated. 

PL18EV still skips the bootloader.

**Review by pfeerick — APPROVED** [review]
PL18EV bootloader trims (and trims generally, thanks for spotting that! :facepalm:) now working...

**Pull request merged**
