### PR TITLE
fix(cpn): radio settings yaml for adc refactor

### LINKED ISSUE #3758: Radio/Model settings cannot be backed up by Companion in 2.10 firmware version
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Because of the changes to the RADIO.YML file format any attempt to backup/restore settings from a radio using companion will result in a corrupted RADIO.YML file. Companion has not yet been updated so it is now impossible to backup/restore a radio using any version of companion.

More concerning is, in future, if someone upgrades their radio; but does not upgrade Companion they risk corrupting their radio.yml file when attempting to do a backup/restore.

### Expected Behavior

Radio can be backed up and and restored using Companion.

### Steps To Reproduce

- Connect radio running 2.10 to any version of companion.
- Read settings from radio.
- Write settings to radio.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS), FrSky X12, FrSky X-Lite / S / Pro, Jumper T12, Jumper T16, Jumper T18, Jumper T-Lite, Jumper T-Pro, Radiomaster Boxer, Radiomaster T8, RadioMaster TX12 / TX12MK2, Radiomaster TX16S / TX16SMK2, Radiomaster Zorro

### Operating System (OS)

macOS

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #3758

Summary of changes:
- continue support for pre adc settings
- support adc settings remapping to pre adc sequences
- remap internal settings on encoding to adc format
- add version check for unsupported settings versions refer #3766
- fix pots and sliders refer #3731
- fix calibration
- fix pots and sliders config
- add global yaml radio and model settings versions variables to assist in data conversion

### CODE REVIEW

**Comment by elecpower** [comment]
For x9d+, X10S and tx16s profiles and libsims, tested:
- reading 2.8.4 settings and writing to 2.10 then simulating
- reading converted 2.10 then simulating
- writing new and reading 2.10 then simulating

**Comment by pfeerick** [comment]
I'm just catching up on these inter-related PRs. Am I right in thinking to drop the top five commits from this PR since #3766 is merged (and slightly different I think) and after merging https://github.com/EdgeTX/edgetx/pull/3731, and then it'll be right to continue on with? Just want to make sure before I go ahead and remove something :zany_face:

**Comment by elecpower** [comment]
> I'm just catching up on these inter-related PRs. Am I right in thinking to drop the top five commits from this PR since #3766 is merged (and slightly different I think) and after merging #3731, and then it'll be right to continue on with? Just want to make sure before I go ahead and remove something 🤪

I'll have look and advise.

**Comment by elecpower** [comment]
@pfeerick, after reviewing, I agree with your proposed steps.

**Comment by pfeerick** [comment]
Closing this PR to redo the PR request as Github appears to have gone completely stupid and is not reflecting the current state of the branch. 

ie... 

image

vs 

image

**Pull request closed without merging**
