### PR TITLE
TX viewer for log files for color LCD (#1608)

### LINKED ISSUE #1608: Preview log file on the screen to find lost model from last GPS...
Hi,

If you go to SYS/SD-HC CARD/LOGS there is no option to read the log files, you can see they exist... In case you crash somewhere and you need GPS coordinates from the LOG file you are in trouble. 

Is it possible to view file contents like with TXT readme files? Well, CSV is actually just another TXT file? I know the LOG files could be bigggg, maybe there could be an option to read last 100 lines or so?

I tried to rename a file into TXT, but it is not possible to change its extension...

### PR DESCRIPTION
**Pull request by eshifri**
Fixes #1608 

Summary of changes: This PR adds menu option "View" for log (csv) files.
CSV files are opened in the TXT file viewer and opened from the end.
It allows to see last logged GPS coordinates.

This PR also includes fixies from #1613 , so #1613 can be skipped if this PR is accepted.

### CODE REVIEW

**Comment by pfeerick** [comment]
Hm... I think this needs a large file warning still... I found one log file that was bigger than 21k (all the ones inc 21k and below were fine)... a 109 KB file... and while it did eventually open... it took way, way, _WAY_ too long... and I half expected the radio had hung... on a second open, with a timer this time... 2m14s... 

[MODEL30-2022-01-20-175145.zip](https://github.com/EdgeTX/edgetx/files/8121060/MODEL30-2022-01-20-175145.zip)

So perhaps a file size check with a "do you want to proceed still?" prompt? There's a ConfirmDialog you might be able to use for that... like used for model select...

https://github.com/EdgeTX/edgetx/blob/357ae8889fcecbcea0dd0eb41ce7b0dd64d42d72/radio/src/gui/colorlcd/model_select.cpp#L278-L287

**Comment by kevinkoenig** [comment]
What about loading file dynamically based on scroll?

**Comment by eshifri** [comment]
It is logged dynamically.
The tricky part is in order to draw the scrollbar, we need to know the size of the file.
The time is spent in the code that reads the file in small chunks from the beginning to the end before displaying anything.
It might be possible to draw the scrollbar based on the size of the file (ignoring the line-breaks), but it will be less accurate.

**Comment by pfeerick** [comment]
If the current delay is simply due to the the scan to determine the scrollbar size, I would make it file size dependent, and live with inaccuracy... it's not worth the delay for that. If the scrollbar can be updated dynamically, it's size could be refined as you know more about the file when scrolling it (i.e. line endings)

**Comment by eshifri** [comment]
Will try to eliminate that extra read.

**Comment by eshifri** [comment]
Commit [5e0adb5] adds warning when opening big files (more than 96K) and speeds-up file loading.

**Review by pfeerick — APPROVED** [review]
Perfecto! And the file load on the oversized log file is now that fast it almost isn't even worth having, but it is still good to have, as it will also explain to user why scrolling is sluggish (i.e. they can't complain about it being slow if the large file warning came up and they still opened the file ;) )

**Pull request merged**
