### PR TITLE
fix: MPM protocol options missing in various protocols

### LINKED ISSUE #1470: Add "RF Channel" to options when XN297 protocol is selected for Multi-module
The "RF Channel" option seems to be missing when using the XN297 Dump protocol.  This allows picking the channel on the module you specifically want to dump.  Otherwise it will always default to channel 0 if you don't select the AUTO subprotocol.

### LINKED ISSUE #2713: MPM protocol options missing in various protocol
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

e.g OMP protocol uses CC2500 but do not have freq. tuning options.

Accordingly to Pascallanger's description:

EdgeTX is pulling at startup all the protocols and their features. But at that time and until the protocol is actually launched there are some unknowns.
Once the protocol is launched, multi sends in each status frame to the radio what exactly should be displayed. -> This is where the issue is. EdgeTX seems to ignore the changes being sent.

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/747

### Expected Behavior

e.g. OMP protocol should shown freq. tuning options.

### Steps To Reproduce

Internal Module -> OMP protocol 
No freq. tuning options

### Version

Nightly (Please give date/commit below)

### Transmitter

All - when MPM in use.

### Anything else?

_No response_

### LINKED ISSUE #3046: Binding DSM using AUTO  as RF protocol: UI does not automatically display chosen protocol after successful binding
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Binding to any DSM RX, using internal MPM, mode DSM, RF protocol: Auto
I activate binding. LED in Rx goes solid, showing successful binding. 
But TX16S still shows "AUTO" as RF protocol. The UI is not automatically updated after successful bind.
initial state

When I leave this screen and enter it again, all the parameters are updated and show the correct details.
after binding

### Expected Behavior

In OpenTx the UI was automatically updated. After succcessful bind, the "AUTO" changes automatically to the activated protocol type, e.g. X 2F. 
It would be nice, if this automatic update of the displayed parameters would also take place in EdgeTx.

### Steps To Reproduce

Open RF setup
Choose internal MPM
Select DSM
Select AUTO protocol
Bind Rx
Wait until bind is completed.
Observe Rx LED going solid - but no change on Tx display.
Close and re-enter the menue: See updated information. Especially, which RF protocol was successfully chosen.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mha1**
Fixes #2713, fixes #3046 (partly #3500), and fixes #1470

Summary of changes:
- use getMultiOptionTitle() instead of rfproto->getOptionStr() as getMultiOptionTitle() takes updated MPM status in account
- changes to mpm_settings.cpp to check for MPM changing subtype for DSM auto

### CODE REVIEW

**Comment by mha1** [comment]
@pfeerick any concerns?

**Comment by richardclli** [comment]
I have tested, the "Auto" mode can bind, but the status is not refreshed, still need some more works to resolve:
https://github.com/EdgeTX/edgetx/issues/3046

**Comment by mha1** [comment]
@richardclli I have include a fix for #3046 in this PR. It is tested as far as I can do it without hardware. Please give it try on real hardware.

**Comment by mha1** [comment]
@pfeerick poke. U good? This and other PR's are waiting to be merged. All reviewed and tested but in need of community testing. Let me know if I can do more of anything to get the PR's out the in the field.

**Comment by mha1** [comment]
@richardclli Hi Richard. sorry to bother you again. I somehow misunderstood how the MPM is reporting back the DSM subtype it has chosen after a bind in auto mode. It's not communicated via the MPM status but through telemetry which adjusts the model settings after a successful bind. I was using the MPM status misinterpretating a status field. The field I used is reporting the number of subtypes (for DSM 6, index range 0..5). So me setting the subtype to 6 led to "invalid protocol". I changed my mistake and hope you can try again. Sorry again that I have to bother you for testing but I don't have Spektrum hw.

**Comment by mha1** [comment]
@richardclli Hey Richard, I just remembered that there had to be a Blade 180 AIO unit in my scrap box which I never knew if it worked or not. Found it and it turned out it works and confirms the latest commit. Using check firmware https://github.com/EdgeTX/edgetx/suites/12641320168/artifacts/677209600) the subType changes after successful bind as expected. I'd still appreciate your confirmation.

**Comment by richardclli** [comment]
> @richardclli Hey Richard, I just remembered that there had to be a Blade 180 AIO unit in my scrap box which I never knew if it worked or not. Found it and it turned out it works and confirms the latest commit. Using check firmware https://github.com/EdgeTX/edgetx/suites/12641320168/artifacts/677209600) the subType changes after successful bind as expected. I'd still appreciate your confirmation.

You are welcome, I would like to do the testing, will do it later today when I get back from work.

**Comment by mha1** [comment]
@richardclli Thanks for testing. I was able to reproduce the sporadic missing updates of DSM2 subtype after a successful bind in auto. Please be so kind and re-test once again with the new commit which is solved the problem for me.

**Comment by richardclli** [comment]
> @richardclli Thanks for testing. I was able to reproduce the sporadic missing updates of DSM2 subtype after a successful bind in auto. Please be so kind and re-test once again with the new commit which solved the problem for me.

Sure, will do.

**Comment by richardclli** [comment]
Still have some problems.  The receiver ID cannot be saved after your PR.  Auto mode will reset the receiver ID to 0.  Cannot change to different value for bind.  And after bind, the value will reser to 0 when existing and reentering the module.  Let me take a look on what you have changed to see if I can spot any problems.

**Comment by mha1** [comment]
Thanks. This might be a different and  independent bug. Seems to be current main 2.9 behavior. I'll investigate further.

**Comment by mha1** [comment]
I just checked 2.8. Same behavior, not related to this PR. Selecting a different subType on any protocol will reset receiver ID.

**Comment by mha1** [comment]
@richardclli Hi Richard, I found the problem. The reason was the set handler of the subType selection field. It resets all MPM options (not only receiver ID) on value change. This is ok for manual subType changes but not ok for the subType change triggered by a successful DSM2 auto bind. Fixed accordingly. Tested ok and is working fine for me.

I'd very much appreciate you cross checking again. Thanks for your help!

**Comment by richardclli** [comment]
@mha1 Wow, nice work, hope this works, will test tonight.

**Comment by mha1** [comment]
@richardclli Hi Richard, I fully agree. Give it a hard time.

**Comment by mha1** [comment]
@richardclli Hi Richard, got a chance to torture DSM?

**Comment by richardclli** [comment]
> @richardclli Hi Richard, got a chance to torture DSM?

A busy busy this week.  Will work this out during weekend.

**Review by pfeerick — APPROVED** [review]
Have done a quick run through with Spektrum AR610 (X 1F), AR637T (X 2F) and some OrangeRX receivers (X 1F, 2 1F) and they all bound and servos worked (well, the AR637T probably wants me to set it up again but telemetry was functional). In each case I chose auto and it updated accordingly. Flicked through several other protocols like OMP and it was giving the missing fine tune option so LGTM unless Richard finds something.

**Comment by mha1** [comment]
@pfeerick Thanks for testing!

**Comment by mha1** [comment]
Thanks Richard

**Comment by pfeerick** [comment]
Sounds like time to let others break it :)

**Pull request merged**
