### PR TITLE
feat(MT12): Enable AUX Serial when BT not defined

### PR DESCRIPTION
**Pull request by 3djc**
For most recent BW radio that have a serial port that can used either as flexible serial or BT (that means FrSky module compatible BT), actually exposes serial if BT is not defined.

### CODE REVIEW

**Comment by rotorman** [comment]
Tested with MT12 and HappyModel EP2 as inverted SBUS trainer receiver - works as expected. Student radio in test was TX16S mkII with internal ELRS module bound to EP2. ExpressLRS settings Full 100 Hz, EP2 set via WebGUI to output SBUS inverted, baud rate 100000 baud.

Some pictures:
grafik

grafik

grafik

MT12 settings:
SYSTEM -> HARDWARE -> Serial port AUX1 -> SBUS Trainer
MODEL -> SETUP -> Trainer Mode: Master/Serial
MODEL -> SPECIAL FUNCTIONS -> ON Trainer Chans Enabled

**Comment by rotorman** [comment]
Here further positive test result - video in HeadTracker Discord https://discord.gg/ux5hEaNSPQ:
https://discord.com/channels/827622724565467196/827622724565467199/1187182326359277679

**Comment by Corey-Harding** [comment]
@rotorman  What kind of connector is that on the board so I can order a pigtail? JST SH 1.0mm?

**Comment by rotorman** [comment]
It is a 4-pin MX1.25 connector.

**Comment by Corey-Harding** [comment]
Thank you

**Pull request merged**
