### PR TITLE
feat(color) - Add LVGL scroll bar where needed.

### PR DESCRIPTION
**Pull request by philmoz**
WIP - add scroll bars to views with more content than will fit on a single screen.

Part 1 - Radio Settings:
- Tools
- SD Card
- Radio Setup
- Themes
- GLobal Functions
- Hardware

### CODE REVIEW

**Comment by philmoz** [comment]
Part 2 - model and screen pages.

- Model Setup
- Preflight checks
- Timers setup
- Module setup
- Inputs list
- Inputs edit
- Mixes list
- Outputs list
- Curves list
- Curve edit
- Logical switches list
- Special functions list
- Custom scripts list
- Telemetry list
- Telemetry sensor edit
- Screen settings - main view
- Screen settings - user interface

**Comment by JimB40** [comment]
Styling: https://github.com/EdgeTX/edgetx/issues/3259
@philmoz on tight layouts packed from left to right screen's edges we have to test transparent scrollbar background.
To my test in Figma solid backround with color of scrolled area works better even it clips content. 

but we may be forced in some cases to use transparent background (like in Model Browser aircrafts list)
Screenshot 2023-02-27 at 09 13 51

**Comment by JimB40** [comment]
Definetely we need touch styling.
Current one doesn't work at all. Can you spot scrollbar?
screen-2023-02-27-092721

@raphaelcoeffic @gagarinlg you have best knowledge abt LVLG styling. Can you make kind of dev session with @philmoz to agree how to code LVGL styling.
Most of styling sheets are aready uploaded. Summary here https://github.com/EdgeTX/edgetx/issues/3220

I don't think we'll manage to do styling in 2.9 rather 2.10 but we should start.

**Comment by philmoz** [comment]
For popup lists and menus the required change is in the libopenui project (PR 85).

**Comment by pfeerick** [comment]
With a build of this PR (using current libopenui head commit) it seems like there is an issue with refreshing the list views properly after adding a new input or mix - the plus button ends up in the middle of the list. On switching tabs it is rebuilt correctly. SF and LS views are fine though. 

image

And while it is not directly related to this PR, I noticed when testing it on the EL18 that there seems to be a double-up of the sensor names on the NV14/EL18 screen. 

image
image

**Comment by philmoz** [comment]
I've fixed the position problem with new entries on Inputs and Mixes.

I can't reproduce the telemetry problem on the NV14 in the simulator.

**Comment by pfeerick** [comment]
This might help with reproducibility (got it to play up with `main` simu and a recent PR Simulator also):
[model1.zip](https://github.com/EdgeTX/edgetx/files/11057470/model1.zip)

However, since it's not related to this PR, that's a bug to squash later. Latest changes seems to be working fine.

**Review by pfeerick — APPROVED** [review]

**Pull request merged**
