### PR TITLE
Correction of Japanese Kanji display

### PR DESCRIPTION
**Pull request by ToshihiroMakuuchi**
@pfeerick 
@raphaelcoeffic 
Fixed display of Kanji characters.

### CODE REVIEW

**Comment by pfeerick** [comment]
Ok, so it looks like this replaces #2026? It looks fine to me, so if @raphaelcoeffic has no concerns in it goes...

**Comment by pfeerick** [comment]
Just putting this up for later review... it seems like there is a mismatch between the output of 
`tools/list-utf-8-code-points.py jp` and the list in `radio/src/fonts/lvgl/make_fonts.sh` - there is a discrepancy in both lists - it's not like one is more complete than the other. 

https://user-images.githubusercontent.com/5500713/183625718-6cfa2dac-daa4-462b-9270-b4c78460b988.mp4

**Comment by raphaelcoeffic** [comment]
For some characters (Hiragana / Katakana) I added the full range (in form of a range) as there are only few of them. And for Kanji I added only those required, as there are too many of them (>50.000).

**Comment by ToshihiroMakuuchi** [comment]
@pfeerick 
You said that tools/charset.py was conflicted, but could not merge Japanese?
What should I have done?

**Comment by pfeerick** [comment]
#2026 was closed in favour of this PR since it was understood that it replaced it. But you've deleted the branch for this PR now. Was that intentional?

**Comment by ToshihiroMakuuchi** [comment]
It is not intentional and will be reopened.

**Comment by ToshihiroMakuuchi** [comment]
@pfeerick 
It is not intentional. So we have created a new jp.h using the latest en.h.

**Comment by pfeerick** [comment]
The changes from this PR have pulled into #2456, so will close this PR now.

**Pull request closed without merging**
