### PR TITLE
fix: I2C support for H7

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- fix I2C timing calculations for H7
- add `i2c_deinit`

### CODE REVIEW

**Comment by Kevltan** [comment]
Seems to have made a difference to my TX16S randomly powering off when I plug in my USB data cable, when using my LSM6DS33 IMU modification. All seems to work fine now!

**Comment by pfeerick** [comment]
Seems ok on TX16S, TX12, TX12MK2, T20, EL18, X9DP. I also seem to remember a comment that it resolves an issue on I2C for someone using an IMU w/ TX16S.

**Comment by Kevltan** [comment]
Hi Peter, have tried this PR with the same results - USB connection drops
out indescriminately and radio switches off (into bootloader mode if cable
is still in). My selfbuild firmware 5281b8b3 (from a couple of months ago)
works fine, no drop out and the IMU cmake declaration works as expected. If
I remove the IMU cmake declaration from the latest firmware selfbuild then
the USB issue also goes away. So there must be a clock issue or something
on the I2c bus that has changed that is causing a conflict somewhere - I
think, maybe!?

**Comment by pfeerick** [comment]
Ok, so maybe it was the other way :zany_face: 

If you're doing self-builds, can you try 2110f1b9380a801b8c1b902c9206fa2e3dc5b66c ... if that works, it is most likely something from the STM32H7 MCU changes... which is to be expected since this is overhauling a lot of low level code in order to add support for another two MCU families... 5281b8b3 is recent enough that I don't think there would be much else that would have done it...

**Comment by Kevltan** [comment]
OK I will try that 👍🙂

**Pull request merged**
