### PR TITLE
feat(color): customizable switch UI support

### PR DESCRIPTION
**Pull request by 3djc**
Add custom switch UI support to main branch.

Hardware support was already introduced as part of adc refactor

### CODE REVIEW

**Comment by pfeerick** [comment]
I have no problem with fd52437 being reverted... while it does reduce the amount of repetition, I think it starts to blur the lines between driver and UI/helper code too much... It seems like instead of via includable headers for files like `led_driver`, some function protos are declared in board.cpp as needed? Some protos are in the wrong place though... as getFSLogicalState getFSPhysicalState , getFSPreviousPhysicalState  and evalFunctionSwitches are all defined in switches.cpp, but not declared in  switches.h

**Comment by 3djc** [comment]
Not sure I'm following your comment @pfeerick . Seems to me it is now, thanks to Philmoz changes, quite nice

**Comment by pfeerick** [comment]
> Not sure I'm following your comment

Why were getFSPhysicalState , getFSPreviousPhysicalState and evalFunctionSwitches declared in board.h instead of switches.h? 

I can see why 
```
void fsLedOff(uint8_t);
void fsLedOn(uint8_t);
```
were since there is no other header defining them.

**Comment by 3djc** [comment]
History (or copy/paste of history). i think having those under switches.h like Phil changed is much better, but I think we all violently agree :D

**Comment by pfeerick** [comment]
Like I changed, actually :laughing: Ok, good, just wanted to make sure I wasn't missing something. Think I will need to move fsLedOn / fsLedOff / getFSLedState back into board.h as they actually come out of led_driver.cpp, but the rest can stay where they are.

**Comment by 3djc** [comment]
My appologies ! No no makes a lot more sense this way.

**Comment by pfeerick** [comment]
Nice! :)

**Comment by 3djc** [comment]
This PR is now obsolete given some of the changes that have happened. I think I'll probably do very soon a t15 pr for 2.11 that will include an updated version of this

**Pull request closed without merging**
