### PR TITLE
File copy and file rename implementation

### PR DESCRIPTION
**Pull request by eshifri**
This is an implementation of FileCopy and FileRename functionality fro SD card.

### CODE REVIEW

**Comment by lshems** [comment]
Nice.

**Comment by raphaelcoeffic** [comment]
@eshifri Could you please use `clang-format` on your changes ? (and only on the changes please). There is a `.clang-format` at the root of the project for this purpose. Thx a lot!

**Comment by eshifri** [comment]
@raphaelcoeffic  Done.

**Comment by pfeerick** [comment]
I think the file rename needs bounds checking... it goes haywire and has garbage characters if you clear the name. I'm unclear on how to actually *apply* the name change after changing the name. 

For the copy, I tried 'Copy' (model checklist txt file)... and then 'Paste' in another folder, and the TX locked up completely, needing a hard power cycle (remove the battery). 

TX16S, latest GH build of this PR.

**Comment by pfeerick** [comment]
I was about to do a video of the garbled text that came up when I cleared the filename, to give it a new one, but now it's being typical technology and trying to make a liar out of me. So I will try and better explain what happened. I picked a file, chose to rename it. I then cleared the filename - for both using a longpress of enter before entering character edit mode and choosing Clear from the menu, and also using multiple presses of 'Page>' when in character edit then somehow resulted in the whole line become a series of seemingly random characters. I may or may not have pressed some other button in the process - I can't be sure. I thought I'd cleared the name, and had pressed enter again to be able to set the first character, but don't hold me to it ;)

So instead it will be just one video, the copy/paste crash. Interestingly enough, it does actually appear to copy the file... after power cycling, it has copied to the target folder, and upon checking the contents, the contents is there also. 
https://youtu.be/LyD_SiAB6mM

**Comment by eshifri** [comment]
@pfeerick thank you for testing it. I will try to reproduce the problem on my radio.

**Comment by eshifri** [comment]
@pfeerick  was it paste without copy? Looked to me you have touched View text. Never occurred to me to test it. Goo catch!
Most likely clipboard.type is not initialized.

**Comment by pfeerick** [comment]
It is possible... if that is the case, it means a prior copy worked though, and locked up still, as the end product was the file was copied from one folder to another... 

I've just run through with the same fw build as before, (you can confirm the build id against the name of the gh action files generated) and used the roller+enter instead for selecting stuff, to eliminate mistakenly pasting without copying as a culprit. I only paused the video whilst I yanked the battery and reconnected. 

https://youtu.be/bP4Ptt0bm5s

**Comment by eshifri** [comment]
Fixed. Everything is working now.

**Comment by pfeerick** [comment]
LGTM... 
* renames worked just fine... change the name and it takes when you exit the rename screen
* copy and paste worked great, and paste only shows once you've copied.

Tested with TX16S

**Pull request merged**
