### PR TITLE
Solve the messy display after Boxer shutdown

### PR DESCRIPTION
**Pull request by zyren**
Solve the redundant cluttered display on the screen after Boxer is shut down.

### CODE REVIEW

**Comment by 3djc** [comment]
Is it all RM radio with f4 ?

**Comment by zyren** [comment]
Yes, this issue occurs on the Zorro F4, TX12MK2, and BOXER devices. When the radio is turned off, after a while, the screen displays random lines. Please refer to #2155. This issue does not occur on the TX12 of F2.

**Comment by 3djc** [comment]
Then maybe replace by, so it cover existing and new models: 
#if defined(MANUFACTURER_RADIOMASTER)  && defined(STM32F407xx)

**Comment by zyren** [comment]
Okay, I will make the changes and submit a new PR. Is that alright?
```c
#if defined(MANUFACTURER_RADIOMASTER) && defined(STM32F407xx)
        lcdInit();
#endif
```

**Comment by 3djc** [comment]
You can update this PR, just update the branch and push it, that will update this PR without the need to create a new one :)

**Comment by pfeerick** [comment]
@3djc Do you think this actually needs to be RM specific? Regardless of the radio, is there any harm in doing this on B&W generally, since it is essentially a screen clear on power off?

**Comment by pfeerick** [comment]
Very true. I've actually noticed this on the TX12 (not sure offhand if it was the TX12 or TX12MKII), and have never really thought anything more of it since the radio is powering off. I agree with that philosophy... if someone else suggests it's needed later, it's just a matter of removing the define 🤷 😆

**Pull request merged**
