### PR TITLE
Quote theme summary values

### PR DESCRIPTION
**Pull request by elecpower**
This fixes the problem of Companion's YAML parser misinterpreting summary tag values as YAML control eg hyphen.

Feel free to improve my feeble attempt at string manipulation, I will not be offended in the least. Thus why I have left it in Draft.

### CODE REVIEW

**Comment by pfeerick** [comment]
I'll just double check this is working but I think this is the simplest way to do it... it's certainly the first method I saw mentioned on stackoverflow 😆

**Comment by raphaelcoeffic** [comment]
IMHO, this should use the generic parser to avoid issues.

**Comment by elecpower** [comment]
> IMHO, this should use the generic parser to avoid issues.

Agree! Job for the Theme devs?

**Comment by elecpower** [comment]
Resolved better by PR #3346

**Pull request closed without merging**
