### PR TITLE
Short press to SYS/MODEL on BW screens, long for ModelSelect on colorlcd

### PR DESCRIPTION
**Pull request by CapnBry**
## Changes
On B&W screens with dedicated buttons, changes the SYS and MODEL buttons from long presses to just short presses. This is how they are on TX16S, so clearly there isn't some sort danger to pressing them by mistake, and it seems weird to have them be both dedicated buttons but require long presses to activate them. They currently do nothing when pressed.

On colorlcd screens, allows a long press of the MODEL button to go directly to the Model Select screen. I find the ability to get to this screen sort of elusive. The ENTER key brings it up a menu to get you there, but only if a widget isn't selected (which is hard to determine "Does anything have a light dotted 1 pixel line around it somwhere?!"). Tapping the screen in some locations brings up that menu too, but only in the title bar, which is hard to discover. Long press of MODEL gets you there now directly, without a stop at the intermediate menu.

### Details
* B&W screens with `RADIO_T8` and `NAVIGATION_X7_TX12` navigation style: Changes SYS and MODEL to from KEY_LONG to KEY_FIRST
* ColorLCD: Change MODEL from KEY_FIRST to KEY_BREAK, and add a KEY_LOG to jump to ModelSelectMenu

I've brought this up a few times in discord but never heard anyone say anything for or against it, so I figured I'd let the code talk for me,

### CODE REVIEW

**Comment by eshifri** [comment]
No implementation for 212x64 B/W TX?

**Comment by CapnBry** [comment]
> No implementation for 212x64 B/W TX?

Oh snap you're right, I forgot about that wee screen. I'll push changes for that size too, thanks!

**Comment by JimB40** [comment]
What about this? 
https://github.com/EdgeTX/edgetx/issues/169
Model config and selection is most used feature so Key binding would speed-up UX

**Comment by CapnBry** [comment]
I just made it match what it is on colorlcd, but if the dev team wants me to remap them all I could take a swing at doing that too.

**Comment by pfeerick** [comment]
If you want to change current short TELE press => channel monitor, and move screen settings to a long TELE press that would be great. Otherwise this PR is good for merged as it is now. colorlcd doesn't have a specific telemetry screen (not to be confused with model settings => telemetry sensors setup tab).

**Comment by CapnBry** [comment]
Sorry about the delay on my side, I was away for the weekend.

The channel monitor is already easily accessible with the page +/- buttons though (one of the five main display options), and long pressing to do the primary function of the TELE button seems backwards to me? Maybe this:

TELE short -> Launch telem view. If no telem view ("No Telemetry Screens") then jump directly to the model DISPLAY page (where these would be created)
TELE long -> Jump to Model TELEMETRY page (where sensors are discovered and to see the whole list)

I find I frequently I need to get to the TELEMETRY page to see a sensor I don't have in a telemetry view / screen, so to me the long press to get to essentially "all telemetry" would make sense. And the short press to get to the telemetry view / screen since that's something the user needs to do on every boot if they want to see telemetry (as the main view at boot is timer or sticks display or channels monitor). I agree that the channels monitor doesn't really fit in with the other view styles since it changes the whole display and not just the bottom half, but having a shortcut to get to TELEMETRY always could be nice if channels monitor is left off the TELE button.

**Comment by pfeerick** [comment]
Yeah, that sounds fine for B&W, since there is no screen settings for it anyway. colorlcd should probably be the same for consistency, but then people would probably moan it has changed has it has been access to screen settings since the OTX days...

**Comment by raphaelcoeffic** [comment]
> colorlcd should probably be the same for consistency, but then people would probably moan it has changed has it has been access to screen settings since the OTX days...

I think we are passed that: we are a different project 😅

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by pfeerick** [comment]
Nice try... but history and muscle memory matters. This is just waiting for the TELE button tweaks... But can probably follow that up in another PR.

**Comment by pfeerick** [comment]
I'll probably pick up the TELE button changes as I want to also change behaviour on B&W radios with dedicated button when in tele screen (i.e. can press TELE to enter and exit tele screen).

**Pull request merged**
