### PR TITLE
Interactive/progressive checklist

### LINKED ISSUE #133: Checkable preflight-checklist
**Is your feature request related to a problem? Please describe.**

There should be a really checkable checklist: only iff all options are checked by user the model gets started.

**Describe the solution you'd like**

A textfile containing "[ ]" should be checkable in the above way, a file without "[ ]" should behave as normal.

**Describe alternatives you've considered**

none

### PR DESCRIPTION
**Pull request by gagarinlg**
rebased, fixed and LVGL converted replacement for #1417 

copied from #1417:
Summary of changes:
Adds an option to display check-boxes at the beginning of each checklist / model notes line. 
- Item to be currently processed has selected (active) check-box, confirmed item - selected checkbox, unconfirmed item - empty.
- You can only advance by one in the checklist (by clicking ENTER - rotary encoder click).
- You can normally scroll the checklist if it exceeds screen size and in addition it is automatically scrolled when currently processed item is at the bottom (or row above bottom) and there are more items available.
- You can remove displaying and processing of some items by placing `=` sign as a first character in a line
- You can mark only items, that are displayed on a screen (no off-screen item confirmation)
- Interactive checklist loaded on model selection (and after reset flight) might be closed only when complete (additional ENTER click after last item completed), see #133
- Interactive checklist loaded from View Notes is closed by pressing EXIT/RTN, no check-boxes are displayed in the view.

Fixes #133

example checklist file
```
EdgeTX
=is
the
best
=and
=this
is interactive
checklist
=with some items disabled and now a very long line to test what happens then
EdgeTX
=is
the
best
=and
=this
is interactive
checklist
=with some items disabled
````

### CODE REVIEW

**Comment by Eldenroot** [comment]
Great! Thx for rebasing + other fixes :)

One of a long opened PR... really interesting new feature. There are more form @piotrva

**Comment by philmoz** [comment]
Model setup menu on B&W radios is broken. There are blank lines and the scrolling is not consistent.
The MENU_TAB array in menuModelSetup looks wrong.

**Review by philmoz — COMMENTED** [review]
Needs to be done for 212x64 as well.

**Comment by 3djc** [comment]
> Needs to be done for 212x64 as well.

Indeed, was asked to fix 128, but yes, 212 was broken in several ways. Fixed it (but havent tested the feature itself at all on either platform)

**Comment by philmoz** [comment]
A couple of things;
- On B&W radios the checklist is not loaded on radio startup, it is only loaded when switching models.
- On B&W radios the ENTER button exits the checklist after the last item is checked. On color radios the ENTER button toggles the last entry off again.
- Long text lines do not wrap on either B&W or color radios.

I wonder if there should be a 'Close' button somewhere on the screen for color radios. It was not immediately obvious to me how to close the text viewer on a radio without hardware keys (NV14). This could trip up new users. A 'Close' button that only shows when the list is complete would also give something to focus on for the ENTER key to close the checklist.

**Comment by philmoz** [comment]
I've made some changes to the color checklist code in PR #3787

**Comment by philmoz** [comment]
In PR #3787 I've indented the checkboxes for easier touch activation and also kept the 'RTN' button visible so the last checkbox is further away from the bottom of the screen.

Screenshot 2023-07-13 at 10 08 58 am

Screenshot 2023-07-13 at 10 08 31 am

**Comment by Eldenroot** [comment]
Maybe some graphic separation between check boxes when you use longer text?

**Comment by pfeerick** [comment]
Keeping in mind the list used to generate it was 

> is interactive
checklist
=with some items disabled and now a very long line to test what happens then
EdgeTX
=is

it may be better to first check what happens if there is a blank line. If that is correctly rendered, IMO it would be better to leave the formatting up to the checklist author.

**Comment by pfeerick** [comment]
i.e. 
image

**Comment by Eldenroot** [comment]
Yes, because when you have more lines and tge check box is aligned to the middle...it could be confusing.

**Comment by pfeerick** [comment]
This can be controlled by the checklist author... I added a blank line in the checklist file, and it was correctly displayed. So if you want spaces, add them. And if you don't, don't put them in?

**Comment by raphaelcoeffic** [comment]
@gagarinlg @pfeerick what is the status of this PR? Can we engage into the merge train?

**Comment by gagarinlg** [comment]
Should be OK after a rebase

**Comment by raphaelcoeffic** [comment]
> Should be OK after a rebase

will you?

**Comment by gagarinlg** [comment]
Not this week

**Comment by pfeerick** [comment]
@philmoz Did something change in the checkbox handling recently? When I did the rebase, I only needed to make two changes in preflight_checks.cpp due to the CheckBox -> ToggleSwitch name changing... i.e. 

```cpp
new CheckBox(line, rect_t{}, GET_SET_DEFAULT(g_model.checklistInteractive));
```
to 
```cpp
auto interactiveChkList = new ToggleSwitch(line, rect_t{}, GET_SET_DEFAULT(g_model.checklistInteractive));
```

But the checkboxes in the preflight checks text viewer are now not visible on TX16S 🤔

**Comment by philmoz** [comment]
> But the checkboxes in the preflight checks text viewer are now not visible on TX16S 🤔

Needed a class constructor for the LVGL checkbox (for the libopenui refactor stuff).

For some reason the checkbox is slightly smaller with this version - still investigating as to why.

**Comment by pfeerick** [comment]
Thanking you so much! :) I'll try and look at this in the morning, otherwise, it'll be tomorrow evening I'll be hoping to merge this in.

**Comment by pfeerick** [comment]
Ok, is working good again. TX16S and TPro seem ok on repeat testing.

**Pull request merged**
