### PR TITLE
Work out a dynamic splash screen that fits all screen sizes.

### LINKED ISSUE #638: Bootloader and Startup screen background
So we already started this with @raphaelcoeffic but stalled waiting for 2.5 UI rework

So here is preview
1. Startup screen
Splash
2. Bootloader
Bootloader

Do here is how to do:
1. Tile (535 bytes)
bkg_holes_tile
2. Full Mask (48kB)
bkg_holes_mask
3. Quarter Mask (12kB)
bkg_holes_mask_025

So to reduce mem usage trick is to get Quarter mask duplicate 3 times, rotate and position in right place
Should be 100% symmetrical. If not I'll replace it
@pfeerick @richardclli feasible?

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #638

Summary of changes:

### CODE REVIEW

**Comment by richardclli** [comment]
This is the best I can do, not quite sure how to apply masks.

**Comment by richardclli** [comment]
Let's use this change first, may enhance it later.

**Comment by pfeerick** [comment]
Yup, it at least fixes the screen corruption issue for LVGL 8.3.

**Comment by philmoz** [comment]
This makes having a custom splash screen pretty hard for users.

Maybe the code should check for the presence of a specific file and use it instead so users can still override this new splash screen.

Probably should be something other than 'splash.png' as anyone who is using the default (old) splash screen will still have this on their radio.

**Comment by pfeerick** [comment]
I'm not sure what you mean - this only applies when `/IMAGES/splash.png` is **not** present as an override for a custom splash screen - which is also normally never present. So nothing changes for users - place `/IMAGES/splash.png`, enjoy custom splash screen. 

This fixes the issue for NV14 where the screen isn't fully filled by the splash screen, which is more of an issue in LVGL8.3. This is also one step towards being able to have a single built-in splash screen for both of the current screen sizes, as well as the one or two more that are coming. The next step will probably be to add the version number (or branch/commit hash if it is a PR or nightly) somewhat like how was shown in #638.

**Comment by philmoz** [comment]
My mistake, you are correct. Sorry.

**Comment by pfeerick** [comment]
No problem, thanks for making me double check 😉

**Pull request merged**
