### PR TITLE
fix  INRM301 failsafe BUG

### LINKED ISSUE #3296: EL18 will automatically power on when the USB cable is unplugged during charging
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### step

1.Power off the EL18
2.Plugin the USB cable for charging
3.Unplug the USB cable
4.Auto power on.

### Describe the solution you'd like

Does not automatically power on when unplugging the USB

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #3297: EL18 internal AFHDS3RF failsafe cannot be set successfully
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

EL18 internal AFHDS3RF failsafe cannot be set successfully

### Expected Behavior

The failsafe function can be used correctly

### Steps To Reproduce

1.MODEL SETUP->InternalRF->Failsafemode(Custom)->set

### Version

2.8.0

### Transmitter

Flysky EL18

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Xy2019**
Fixes #3297

Summary of changes:

### CODE REVIEW

**Review by richardclli — COMMENTED** [review]
Seems finally got a way to do boardOff properly without entering emergency mode in next power on.

**Comment by richardclli** [comment]
@raphaelcoeffic Please take a look in the protocol part, @Xy2019 the programmer of Flysky, he will help to fix problems from now on.

**Comment by Xy2019** [comment]
> Seems finally got a way to do boardOff properly without entering emergency mode in next power on.

The last modification would lead to emergency mode, so I re-modified and submitted it.

**Comment by richardclli** [comment]
@Xy2019 it would be better to split PR so that each PR only fix one issue.  Hard to review and merge when mixing together.

**Comment by Xy2019** [comment]
> @Xy2019 it would be better to split PR so that each PR only fix one issue. Hard to review and merge if mixed together.

OK, I tried to resubmit.

**Comment by pfeerick** [comment]
> Seems finally got a way to do boardOff properly without entering emergency mode in next power on.

Not quite... while this mostly works, I naturally found one what that still triggers this... which is if USB was active (i.e. SD mode) when you power down, it will indeed startup fine and show the charge screen. But the next time the radio powers on, it will EM. 

Maybe needs to be handled at the charge screen so that `UNEXPECTED_SHUTDOWN()` is not true in that edge case. 

@Xy2019 Can you remove the change to `board.cpp` now as the changes were merged as part of #3325

**Comment by pfeerick** [comment]
Seems to be working perfectly on EL18 w/ Ftr12B - can now set custom failsafe.

**Pull request merged**
