### PR TITLE
fix: Fixed grammatical errors in the :ukraine: translation

### PR DESCRIPTION
**Pull request by ruffian93**
I suggest a correction in the Ukrainian localization.
I am a native speaker and found some mistakes.
I fixed errors of the following types:
- Incorrect order of letters in the word.
- Some words were in Russian - I replaced them with Ukrainian.
- Incorrect word meanings. I used the English localization as a basis and selected the best match in Ukrainian.
- The ending of the word. For example: TR_NO_PICTURE

### CODE REVIEW

**Comment by GennadiyChe** [comment]
I am a native speaker and I read everything, everything is correct.

**Review by AlexanderKruglyak — COMMENTED** [review]
I'm a native speaker and I do not see any issues here

**Comment by Slab3** [comment]
As a native speaker, I can tell that all the fixes make sense

**Comment by nomatterhowyoutry** [comment]
Im a native speaker - lgtm!

**Pull request merged**
