### PR TITLE
feat: Option for inverting rotary encoder direction

### PR DESCRIPTION
**Pull request by pfeerick**
Adds partner requested "rotary encoder" inversion option on both radio and companion side. 

Needs more testing, preliminary testing with TX16S, TX12, X9D+2019 and Zorro suggest it is working as intended, but I haven't read/written to the radios yet. 

Companion and simulator *appear* to be working, but the setting as set in Companion doesn't seem to be being read in Simulator... so I've probably missed something there. 

Intended tests with 

TX16S (tx16s-2f22a85.bin)
- [x] on radio (inc. bootloader)
- [x] companion read and write
- [x] simulator

TX12 (tx12-2f22a85.bin)
- [x] on radio (inc. bootloader)
- [x] companion read and write
- [x] simulator

X9D+2019(x9dp2019-2f22a85.bin)
- [x] on radio (inc. bootloader)
- [x] companion read and write
- [x] simulator

Zorro (fw 8557033, cpn 2f22a85)
- [x] on radio (inc. bootloader) - I may still look at inverting zorro default as it is inverted compared to all other radios
- [x] companion read and write
- [x] simulator

TPro (tpro-2f22a85.bin)
- [x] on radio (inc. bootloader)
- [x] companion read and write
- [x] simulator

### CODE REVIEW

**Comment by Eldenroot** [comment]
Same feature was added into opentx lately, good to have it in edgetx too, thx

**Comment by 3djc** [comment]
I was about to check on that before 2.3.15 release, I think the default is inverted vs "before the option"

**Comment by 3djc** [comment]
I recommend considering : https://github.com/opentx/opentx/commit/3c1ee3c3b69e6a36ad584647abc69817ebdd53cd

**Comment by pfeerick** [comment]
lol... I think I probably beat you to that one... https://github.com/EdgeTX/edgetx/pull/1690/commits/b9da322fcf9334f650cb84a664f729fae85edc7a

**Comment by pfeerick** [comment]
@elecpower I think this is functional. One thing I wasn't able figure out was the radio is using 0 for no checkbox tick, -1 for checkbox tick, but I wasn't able to resolve that whilst keeping opentxeeprom happy as it expects a boolean. However, radio firmware seems to 1 instead of -1 and convert it itself, and companion is reading the current state without issue.

**Comment by breadoven** [comment]
Does this invert both vertical and horizontal scrolling ? Seems on the Zorro only the vertical scrolling is "wrong" for me so I'd want the horizontal scrolling unchanged.

**Comment by pfeerick** [comment]
Inverts the direction of the rotary encoder, nothing more... so doesn't take into account where. It _may_ be possible to invert the direction selectively without too much effort, but it then becomes a question of where do you stop in providing options.

**Comment by Batambatam** [comment]
Works well on my T-Pro, FYI.

**Comment by JimB40** [comment]
> Inverts the direction of the rotary encoder, nothing more... so doesn't take into account where. It _may_ be possible to invert the direction selectively without too much effort, but it then becomes a question of where do you stop in providing options.

Which is a thing to consider in UI/UX redesign.
There are differen cases when direction should be implemented diferently
1. Horizontal UI change
2. Vertical UI change
3. Value change
When physical roller is placed at angle we need to code proper direction as it's not up/down or left/right any more

**Comment by pfeerick** [comment]
While I concur with what you say, can you not raise this is closed issues / merged PRs? As this is how this point gets lost and forgotten... ;) i.e. Raise it in a new issue, and reference this PR if needed for context ;)

**Comment by JimB40** [comment]
Done

**Pull request merged**
