### PR TITLE
perf: Process CRSF telemetry by frame

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of Changes:
- uses idle line IRQ to process incoming CRSF chunks directly
- modified frame parser with some heuristic to reassemble fragmented frames
- CRSF telemetry stream processing is now done right after frame reception (not on a periodic timer anymore)

### CODE REVIEW

**Comment by pkendall64** [comment]
Installed the binary on TX16S and external Ranger module works, but internal ELRS module no longer functions.

**Comment by pfeerick** [comment]
feat, perf or refactor?

https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type

**Comment by raphaelcoeffic** [comment]
Yes, why not.

**Comment by pfeerick** [comment]
lol... that was quick... got the email about the failure, and by the time I'd pulled the PR locally you'd already added the fix commit so it didn't fail locally 🤣

**Comment by ParkerEde** [comment]
I have already been in direct dialogue with raphaelcoffic. 
With an X10S Express I get telemetry lost/recover messages via ACCESS (R8 pro and G-RX8) as well as via ACCST (X4R with UNI Fw) as soon as I have connected an external sensor (original Frsky GPS or Unisens-E) to the receiver.
If I use the Rx without sensors, I do not get any lost/recover messages.
If I use a QX7S ACCESS, the problem does not occur even with external sensors.
I tested with the current main from today + PR #4038

**Comment by pfeerick** [comment]
I've used internal and external RF, on TPro V2, TX16S and X9D+2019, and no issues with telemetry loss or connection (well, until the battery ran flat 🤪) even when running multiple links in parallel (with different receiver IDs, packet rates and baud rates).

**Pull request merged**
