### PR TITLE
fix: do not init the watchdog in flash driver

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fix issue introduced in #5232 and reported by @philmoz on Discord

https://discord.com/channels/839849772864503828/909552654328406056/1265246121484226661

### CODE REVIEW

**Comment by 3djc** [comment]
Tested ok on T15

**Comment by 3djc** [comment]
Hold fire on this, I think having watchdog in bl is wrong, need to discuss it

**Comment by 3djc** [comment]
No ok, we disabled it in BL and moved it to firmware only, good to go :)

**Comment by pfeerick** [comment]
No bootloader EM trigger on TX16S, Boxer or TPro, and main firmware starts. 

#5290 is all yours now @3djc :grin:

**Pull request merged**
