### PR TITLE
Fixes for MPM UI for colorlcd

### LINKED ISSUE #2203: MPM not showing RF fine tune value
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When setting the `RF Freq. fine tune`, it becomes blank when you leave the RF menu and return.

### Expected Behavior

Frequency fine tune value should be displaying in the field.

### Steps To Reproduce

Go to model settings using either an internal or external MPM, choose a protocol that has fine tuning, and attempt to set it. If you back out of the menu and go back in, it becomes blank again.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

This is present with nightly c41de59. Works fine on the Zorro and TX12 MK2.

It seems to be saving the value, it's just not displaying it when the RF menu loads. If I set it to 1 and back out, go back in, and use the touch screen to increment it by 1, it goes to 2. Then if you back out and do it again, it goes to 3, etc.

I know, I know. Very fussy today. 😬

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #2203

Summary of changes:
- set field values to current option value when configuring fields
- hide sub-protocol choice if the list is empty

### CODE REVIEW

**Comment by pfeerick** [comment]
@raphaelcoeffic I couldn't find a trigger case for `STR_MULTI_WBUS` ... maybe it's not used anymore?

I wasn't able to figure out the right setValue for the `MODULE_SUBTYPE_MULTI_DSM2` checkbox, and it needs it something also...

Another gremlin with the Choices seems to be the loading of the option strings. i.e. Set the protocol to `Bayang` , and the telemetry value to the third value `Off+Aux`. Now go in and out of the module options screen... the choice will show blank, and when you open it it doesn't list `STR_MULTI_TELEMETRY_MODE` but shows `OFF|1|2|3`... (but will be on the correct value now)... is there a refresh/update call I need to prod??

**Comment by gagarinlg** [comment]
> @raphaelcoeffic I couldn't find a trigger case for `STR_MULTI_WBUS` ... maybe it's not used anymore?
> 
> I wasn't able to figure out the right setValue for the `MODULE_SUBTYPE_MULTI_DSM2` checkbox, and it needs it something also...
> 
> Another gremlin with the Choices seems to be the loading of the option strings. i.e. Set the protocol to `Bayang` , and the telemetry value to the third value `Off+Aux`. Now go in and out of the module options screen... the choice will show blank, and when you open it it doesn't list `STR_MULTI_TELEMETRY_MODE` but shows `OFF|1|2|3`... (but will be on the correct value now)... is there a refresh/update call I need to/can prod??

try this:
`
diff --git a/radio/src/gui/colorlcd/mpm_settings.cpp b/radio/src/gui/colorlcd/mpm_settings.cpp
index 8dabca00f..277c0939d 100644
--- a/radio/src/gui/colorlcd/mpm_settings.cpp
+++ b/radio/src/gui/colorlcd/mpm_settings.cpp
@@ -278,6 +278,7 @@ MultimoduleSettings::MultimoduleSettings(Window *parent,
   new CheckBox(line, rect_t{}, GET_SET_DEFAULT(md->multi.disableTelemetry));
 
   cm_line = new MPMChannelMap(this, &grid, moduleIdx);
+  update();
 }
 
 void MultimoduleSettings::update()
`

it solves the problem for me. The inputs are not completely initialised when the screen is entered, by calling the update method it should be ok.

**Comment by pfeerick** [comment]
Ah, yes, much better... now it seems to be filling RF tune in with the correct values... so still just the matter of getting the checkbox values properly set now...

**Comment by pfeerick** [comment]
Can you cast an eye over this latest commit to see it makes sense... it *appears* to be working, but I somehow think I'm doing it wrong still 😆 .

There appears to be an issue (or has just been created 😇 ) still around values updating... and I've not checked if it's cosmetic/in memory issue or affects the module yet. i.e. Select Frsky - change the fine tune value to *anything else* (e.g. DSM)... and then back again ... the value will have either reverted (in most cases), or _sometimes_ will be 0.

**Comment by pfeerick** [comment]
Actually, I've just noticed the 'values not updated' might be related to a larger issue, which is that a lot of model NumberEdit style fields aren't being saved full stop (in simu, anyway)... i.e. timer names, curve names, model name. The latter is a sore point as it also isn't trigging a callback needed to trigger the model select page to be updated, as well as the models.yaml list updated.

**Pull request merged**
