### PR TITLE
Fix companion radio profile default module resetting to board default

### LINKED ISSUE #1871: [Bug]: Companion internal module cant be changed (Companion 2.7)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

grafik

I try to set multi in radio profile but it always reverts back to CSRF. 
2.7 Release Version
RM Zorro 4-1 

### Expected Behavior

Set internal module to MULTI 

### Steps To Reproduce

Open radio profile
set internal module
leave
open profile again
module is set back to CRSF

### Version

2.7.0

### Transmitter

Radiomaster Zorro

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #1871

### CODE REVIEW

**Comment by pfeerick** [comment]
It's annoying one-line gremlins like this make me think we need to somehow break Companion out so it can have it's own release cycle... i.e. 2.7.1 just for this? Although, admittedly, it is the *default* setting, not the radio setting, right? So when you read from the radio, it should use what you set there....

**Comment by gagarinlg** [comment]
I think this would ceate a lot of additional support requests, because it is then unclear which versions belong together.
I something is worth creating a bugfix release, then just do it, even when it only effects one part of the suite.
Else just wait until a big issue is fixed or enough small fixes are made, to justify a release.

**Comment by elecpower** [comment]
> It's annoying one-line gremlins like this that make me think we need to somehow break Companion out so it can have it's own release cycle... i.e. fw and cpn 2.7.1 just for this? Although, admittedly, it is the _default_ setting, not the radio setting, right? So when you read from the radio, it should use what you set there....

One release cycle please! Yep only the default and radio setting the one that matters.

**Comment by pfeerick** [comment]
True... I was thinking more that any 2.7 should work with any 2.7,  so the build number for companion could always be incremented separately... but, yeah, if suppose if we find anything that could trigger a 2.7.1 release generally could come back and add this then... unless we add bugfixes like this to the 2.7 branch anyway, since 2.7.0 is a tagged version so can keep adding to the branch, and it may or may not make a release?

**Comment by gagarinlg** [comment]
This is essentially what we do at work.

**Comment by pfeerick** [comment]
Perfect, thanks!

**Pull request merged**
