### PR TITLE
[color] Dynamic MPM proto list

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This implements the dynamic protocol list as returned by the MPM. This is based on scanning the MPM by switching to each protocol in the right order according to previous/next protocol returned by MPM status packets.

At the moment, it takes around 110-120ms per protocol. With the "normal" 4in1 MPM, it takes around 6-7 seconds to fetch the complete list.

TODOs:
- [ ] use dynamic subtypes as well.
- [ ] use sorted static list in case MPM does not reply properly? mostly due to bugs / unplugged module, is it really useful? 
- [ ] nicer animation / text dialog?

### CODE REVIEW

**Comment by pfeerick** [comment]
Re 1 - yup, and also sort that stupid combo box out - it doesn't always show when there are subprotocols to be selected - I keep having to go to something like DSM. 

Re 2 - if error, just say error. However, there is value if you want to be able to configure a model that will have a MPM without the MPM connected... so if external can be handled differently?

Re 3 - if the total number of protocols can be determined, it could become progress text or progress bar. For it to be 'nicer'. Plus hiding the dropdown while that happens as from an end-user perspective it looks janky... I get what you mean... but I'm saving your from Robert :-P

**Comment by pfeerick** [comment]
A quick test on the TX16S with older MPM firmware shows this working fine... 64 or so protocols found, ~8.5 seconds... as an end user, that is acceptable delay especially since it's cached whilst in the model setup page and doesn't look like it's 'frozen'. I still wonder if it would be even better to cache it to file with the MPM version number... make use of that RADIO folder ;)

**Comment by raphaelcoeffic** [comment]
> Re 1 - yup, and also sort that stupid combo box out - it doesn't always show when there are subprotocols to be selected - I keep having to go to something like DSM.

Yep, this is still buggy, but will be fixed.

> Re 2 - if error, just say error. However, there is value if you want to be able to configure a model that will have a MPM without the MPM connected... so if external can be handled differently?

It should be possible to have a fall-back to the static list.

> Re 3 - if the total number of protocols can be determined, it could become progress text or progress bar. For it to be 'nicer'. 

Sorry, no. The total number is not known. Not even while it's progressing.

> Plus hiding the dropdown while that happens as from an end-user perspective it looks janky... I get what you mean... but I'm saving your from Robert :-P

That one could be done, at least I believe so.

**Comment by raphaelcoeffic** [comment]
> Re 1 - yup, and also sort that stupid combo box out - it doesn't always show when there are subprotocols to be selected - I keep having to go to something like DSM.

This one should be fixed now.

**Comment by pfeerick** [comment]
> > combo box - it doesn't always show when there are subprotocols to be selected - I keep having to go to something like DSM.
> 
> This one should be fixed now.

Yes, it does indeed. It would be nice is the choice list also jumped to the currently selected protocol, rather than to the top of  the list each time. 

It looks like Pascal has granted your wish for MPM also ;) https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/commit/5c00ce6b88c955ecd81cd9f6ef18275c9be8a545 ... and I see there is also mention of "number of protocols in the list" in a later commit... :)

**Comment by elecpower** [comment]
Companion will need to be maintained manually as it needs to know all possible MPM protocols.

**Comment by rotorman** [comment]
Could Companion use MPM as a Git submodule, in order to fetch there automagically the latest list (git pull & build time)?

**Comment by rotorman** [comment]
> Had a quick look at the MPM repo and the Companion code and does not look promising. Not as simple as an #include or two.

On the long run keeping the protocol list in sync manually with EdgeTX and OpenTX Companion is not a nice option IMHO.

Maybe @pascallanger has an idea or a way to store the protocol list info in a dedicated header file, that would be used by MPM itself, but could also be used by EdgeTX and OpenTX Companion (via Git submodule)?

**Comment by elecpower** [comment]
> On the long run keeping the protocol list in sync manually with EdgeTX and OpenTX Companion is not a nice option IMHO.
> 
Agree. This is just one of many areas which are painful to maintain due to Companion having to handle every radio capability in one executable.

**Comment by elecpower** [comment]
> Maybe @pascallanger has an idea or a way to store the protocol list info in a dedicated header file, that would be used by MPM itself, but could also be used by EdgeTX and OpenTX Companion (via Git submodule)?
> 
There are headers but the formats would require slicing and dicing. Cannot rely on @pascallanger to lock in a format just for another project.

**Comment by rotorman** [comment]
> There are headers but the formats would require slicing and dicing.

Would you be able to make a suggestion at @pascallanger how the header could look like that would be in your thoughts be best for Companion (and also remain usable for MPM)? That could be a solid discussion basis with MPM project maintainers to hear their thoughts about it and possibly even get it merged, so that everyone profits.

**Comment by pascallanger** [comment]
I do maintain already a couple of protocol lists:
 - [Multi.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/Multi.txt) used by erskyTX to display the protocols and subprotocols when the module is not in the radio
 - [MultiChan.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Lua_scripts/MultiChan.txt) this file is used by the [MultiChannelsUpdater](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Lua_scripts/MultiChannelsUpdater.lua) lua script which lists all the protocols, subprotcols but also the name of the channels (Flip, RTH, Light...)
 - [Multi_Proto.ino](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/Multi_Protos.ino) this is the file that the multi fw uses to configure itself and send all the protocol details to the radio so it includes the protocol number, protocol name, number of sub_protocols, subprotocol texts, Option field type and if failsafe and/or ch map disable is supported.

Let me know what you are looking for.
Pascal

**Comment by elecpower** [comment]
@pascallanger thank you for the links and their file purpose. I'm in the middle of another complex change and do not want to be distracted. But when I have some time, I will see how best to 'automate'. If I need any assistance I will get back to you. Neil

**Pull request closed without merging**
