### PR TITLE
EdgeTX Companion 2.4 - For review - DO NOT MERGE

### PR DESCRIPTION
**Pull request by elecpower**
Data conversion to v220.
Update Timers ui to cater for mode field split.
Replace some OpenTX refs. Cannot replace all as things start falling over.
Tested on Ubuntu 20.04.
Notes:
- could someone check the radio conversion of TimerData in /radio/src/storage/conversions/conversions_219_220.cpp as by my reckoning there is a one bit shift in the structure with the deletion of direction and its reuse but not catered for in the conversion.
- EdgeTX icons and images required. I'll leave that to the theme team.
- Individual Simulators compile (except Taranis flavours) BUT crash on load and appears related to themes. To diagnose whether it is my data conversion or they are truly broken will need to test against a set of files from a real radio. (I do not have a test radio to generate a set from).
- no support for NV14

### CODE REVIEW

**Comment by pfeerick** [comment]
I have a TX16S - what files do you need - like the `radio.bin` and a fresh `model.bin`?

**Comment by elecpower** [comment]
@pfeerick yes please. Just need new files that have not been converted or near companion.

**Comment by pfeerick** [comment]
Freshly created on transmitter model from TX16S - has never been near companion. Radio settings 'may' have been imported from OTX 2.3.11, I can't remember now as it's been through so many cycles and a few full formats. 

[tx16s_fresh_model.zip](https://github.com/EdgeTX/edgetx/files/6766646/tx16s_fresh_model.zip)

**Comment by elecpower** [comment]
Thank you

**Comment by elecpower** [comment]
@pfeerick checked your bin files against those I converted using Companion and they look consistent. However the Companion Simulator still crashes using your files and Edge sd card with the last two debug lines:
0.02 opentxInit (<-- Note: this is from the radio code)
[W] ::unknown():0 - QObject::installEventFilter(): Cannot filter events for objects in a different thread.
and the result code "4420 Segmentation fault" returned to the shell cmd
I will have to build a full 2.4 Qt debug environment to narrow this down.
I'll also try and get a Taranis X9d+ sim object compiled to see if it runs.

**Comment by pfeerick** [comment]
I also have a X9D+ and T-Lite... I'll make a new model on each and back
them up if that helps.

**Comment by elecpower** [comment]
Thanks, I will likely call on you for those. I have an x9d+ which I can use for 2.3 to 2.4 conversion as well. But 1st I have to fix/hack the current Taranis radio sim object compiler error(s).

**Comment by raphaelcoeffic** [comment]
@elecpower thanks a lot for this amazing work! Do I still need to check the 1-bit offset you mentioned earlier?

**Comment by elecpower** [comment]
Yes. Needs another set of eyes to confirm or disprove.

**Comment by elecpower** [comment]
Update: built a Taranis X9D+ sim and it works as expected so at least we can have some confidence that the foundations of the simulator appear to be okay in the 2.4 toolchain.

**Comment by sfjuocekr** [comment]
If you run the simulator and have the directories setup correctly, it should run. At least it does for me when I build the companion and simulator. It will tell you convert the stuff when you start the simulator the first time when using the edge SD contents + audio.

I did notice a timer oddity on my radio with pausing timers (switch up = go (works), switch down = pause (fails)) that does not work. Likely the same is true for throttle up timers, I did not test this yet.

**Comment by elecpower** [comment]
@sfjuocekr thanks for the advice. I do have an Edge SD card which I will rebuild to eliminate that as the cause but it could also be my dev environment.

**Comment by sfjuocekr** [comment]
Im on Ubuntu 21.04 and simulating the T18

**Comment by elecpower** [comment]
So after building more dev environments and trying the Edgetx docker image and still crashing I have discovered that launching the Companion Simulator 2.4 from the commend line supplying an otx model file created and saved by Companion 2.4 is successful.
Now to track down what is going wrong in the launch from Companion gui

**Comment by raphaelcoeffic** [comment]
> So after building more dev environments and trying the Edgetx docker image and still crashing I have discovered that launching the Companion Simulator 2.4 from the command line supplying an otx model file created and saved by Companion 2.4 is successful.
> Now to track down what is going wrong in the launch from Companion gui

Woah! Nice! So it seems we are damn close to it! Are you using Window as your dev environment? Or something else?

**Comment by elecpower** [comment]
Win 10 host running VirtualBox with Ubuntu guest VMs which in some cases run Docker images.

**Comment by sfjuocekr** [comment]
Oh that is obviously what I did first, I created the model with the companion and started it from there! It will then also work if you start the sim directly as it takes the config from the companion.

**Comment by elecpower** [comment]
I think and I stress think I have found the cause of the simulator crash when launched from Companion. My knowledge of this area is minimal to non-existent so with that said.
Qt Creator in Companion24 debug mode has a trace sequence that appears to show a jump from radio/.../libopenui/src/mainwindow.h in the libopentx-tx16s-simulator.so module to companion/src/mainwindow.cpp in the companion24 module. This is not what is expected. My guess is the non-unique MainWindow class is the cause but since the simulator is dynamically loaded I'm not sure how to fix.
I have attached the trace for an expert to review.
[simcrashtrace.txt](https://github.com/EdgeTX/edgetx/files/6913588/simcrashtrace.txt)
Thoughts?

**Comment by raphaelcoeffic** [comment]
> I think and I stress think I have found the cause of the simulator crash when launched from Companion. My knowledge of this area is minimal to non-existent so with that said.
> Qt Creator in Companion24 debug mode has a trace sequence that appears to show a jump from radio/.../libopenui/src/mainwindow.h in the libopentx-tx16s-simulator.so module to companion/src/mainwindow.cpp in the companion24 module. This is not what is expected. My guess is the non-unique MainWindow class is the cause but since the simulator is dynamically loaded I'm not sure how to fix.
> I have attached the trace for an expert to review.
> [simcrashtrace.txt](https://github.com/EdgeTX/edgetx/files/6913588/simcrashtrace.txt)
> Thoughts?

You are right! This is plain wrong! No clue how the compiler decided this would work!

Here in the thing in all it's glory:
```
#9  0x000055555583343d in MainWindow::MainWindow() (this=0x7fff7c000c20) at /home/neil/edgetx/edgetx/companion/src/mainwindow.cpp:108
        showSplash = false
        str = {static null = {<No data fields>}, d = 0x0}
        model = 0
        count = 0
        updateDelay = 0
        strl = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x0}, d = 0x0}}, <No data fields>}
        printfilename = {static null = {<No data fields>}, d = 0x0}
        printing = 0
#10 0x00007fffea2bebb7 in MainWindow::instance() () at /home/neil/edgetx/edgetx/radio/src/thirdparty/libopenui/src/mainwindow.h:46
```

I'll need to check if I can reproduce this on OSX. If that works, I'll find a solution.

**Comment by raphaelcoeffic** [comment]
@elecpower I have no clue how that works under Windows, but you should check the unresolved symbols in the radio dll. On OSX, it works like this:

Here is the list of resolved symbols (so, functions/methods for which the code already knows the address), whereby `-C` asks for demangled names:
```
% nm -C libopentx-tx16s-simulator.dylib | grep MainWindow 
000000000006a0e0 T MainWindow::emptyTrash()
000000000006a570 T MainWindow::invalidate(rect_t const&)
000000000006a280 T MainWindow::checkEvents()
000000000006a840 T MainWindow::run(bool)
000000000006a6c0 T MainWindow::refresh()
000000000000cde0 T MainWindow::instance()
00000000007efe68 S MainWindow::_instance
000000000000d940 t MainWindow::MainWindow()
000000000000d960 t MainWindow::MainWindow()
000000000006a8f0 t MainWindow::~MainWindow()
000000000006a8d0 t MainWindow::~MainWindow()
000000000006a920 t MainWindow::~MainWindow()
00000000007c1370 S typeinfo for MainWindow
0000000000723ba6 S typeinfo name for MainWindow
00000000007c12f0 S vtable for MainWindow
%
```

And the list of *unresolved symbols* is empty (`-u` is for unresolved symbols):
```
% nm -uC libopentx-tx16s-simulator.dylib | grep MainWindow
%
```

**Comment by elecpower** [comment]
@raphaelcoeffic FYI I'm testing and debugging in Ubuntu 20.04. Here are my results.
```
nm -C libopentx-tx16s-simulator.so | grep MainWindow

00000000002d5586 T MainWindow::emptyTrash()
00000000002d59be T MainWindow::invalidate(rect_t const&)
00000000002d5642 T MainWindow::checkEvents()
00000000002d5c72 T MainWindow::run(bool)
00000000002d5b0e T MainWindow::refresh()
0000000000293b88 W MainWindow::instance()
00000000006898e0 B MainWindow::_instance
0000000000293aa6 W MainWindow::MainWindow()
0000000000293aa6 W MainWindow::MainWindow()
00000000002d5d16 W MainWindow::~MainWindow()
00000000002d5cd4 W MainWindow::~MainWindow()
00000000002d5cd4 W MainWindow::~MainWindow()
0000000000661ea8 V typeinfo for MainWindow
00000000004c6680 V typeinfo name for MainWindow
0000000000661e28 V vtable for MainWindow
```
Nothing listed from command
```
nm -uC libopentx-tx16s-simulator.so | grep MainWindow
```

**Comment by raphaelcoeffic** [comment]
> FYI I'm testing and debugging in Ubuntu 20.04

Yeah, and you told me once already! 😝

To the libs themselves, I must admit I'm clueless. But this is a good news in a sense, as this means I can test myself if it's not on windows.

**Comment by rotorman** [comment]
I tried to build this PR under Windows 10, without success unfortunately.

Whereas I am able to build companion.exe and simulator.exe of the main branch (but not yet radio simulator dll libraries under Windows), building companion.exe and simulator.exe fails for this PR.

Using following batch file (that works for OpenTX 2.3 and EdgeTX main branch companion.exe and simulator.exe generation):
```
SET BUILDPATH=C:\edgetx\build-edgetxMain_comp_sim_libsim_tx16s-PR409
SET SRCPATH=C:\edgetx\edgetx-PR409
SET QTPATH=C:\Qt\5.15.2
SET CMAKEOPTIONS=-DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES

CALL "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuildCmd.bat"
cmake -A win32 -S %SRCPATH% -B %BUILDPATH% -DCMAKE_PREFIX_PATH=%QTPATH%\msvc2019 %CMAKEOPTIONS%
cmake -G "MinGW Makefiles" -S %SRCPATH% -B %BUILDPATH% -DCMAKE_PREFIX_PATH=%QTPATH%\msvc2019 %CMAKEOPTIONS%
msbuild %BUILDPATH%\INSTALL.vcxproj /t:Build /p:Configuration=Release
MOVE %BUILDPATH%\*.dll %BUILDPATH%\Release
%QTPATH%\msvc2019\bin\windeployqt.exe --no-translations --no-opengl-sw --no-system-d3d-compiler --no-angle --no-compiler-runtime -dir "%BUILDPATH%\Release" %BUILDPATH%\Release\companion.exe %BUILDPATH%\Release\simulator.exe
```

I believe the issue of radio library files failing to build lies in the change of _STM32F4xx_DSP_StdPeriph_Lib_V1.4.0_ to _V1.8.0_, that seems to work fine with GCC under Ubuntu, but is not compatible with MS Visual C++ anymore.

Failing of building companion.exe and simulator.exe seems to be newly introduced in this PR. Unfortunately I cannot pinpoint the issue/ problematic line(s).

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic FYI I'm testing and debugging in Ubuntu 20.04. Here are my results.
> 
> ```
> nm -C libopentx-tx16s-simulator.so | grep MainWindow
> 
> 00000000002d5586 T MainWindow::emptyTrash()
> 00000000002d59be T MainWindow::invalidate(rect_t const&)
> 00000000002d5642 T MainWindow::checkEvents()
> 00000000002d5c72 T MainWindow::run(bool)
> 00000000002d5b0e T MainWindow::refresh()
> 0000000000293b88 W MainWindow::instance()
> 00000000006898e0 B MainWindow::_instance
> 0000000000293aa6 W MainWindow::MainWindow()
> 0000000000293aa6 W MainWindow::MainWindow()
> 00000000002d5d16 W MainWindow::~MainWindow()
> 00000000002d5cd4 W MainWindow::~MainWindow()
> 00000000002d5cd4 W MainWindow::~MainWindow()
> 0000000000661ea8 V typeinfo for MainWindow
> 00000000004c6680 V typeinfo name for MainWindow
> 0000000000661e28 V vtable for MainWindow
> ```
> 
> Nothing listed from command
> 
> ```
> nm -uC libopentx-tx16s-simulator.so | grep MainWindow
> ```

So the shortest path to success is to rename one of both, right? It is not used that much in the radio code, how is it in companion? Or maybe just adding a namespace? It would end-up in the mangled name, I believe.

**Comment by elecpower** [comment]
> So the shortest path to success is to rename one of both, right? It is not used that much in the radio code, how is it in companion? Or maybe just adding a namespace? It would end-up in the mangled name, I believe.

Lots of references in Companion using nm -C companion24 | grep MainWindow
[cpnmwrefs.txt](https://github.com/EdgeTX/edgetx/files/6919280/cpnmwrefs.txt)

From my research rename and namespace are the recommended options but first before we head down that path another option I want to test to confirm the issue is to set a linker flag on the shared library to -Bsymbolic. From man ld 
```
When creating a shared library, bind references to global symbols to the definition within the shared library, if any.
Normally, it is possible for a program linked against a shared library to override the definition within the shared library.
This option is only meaningful on ELF platforms which support shared libraries.
```

**Comment by elecpower** [comment]
Adding the following results in the simulator launching from companion and confirms the issue is the non-unique class name and the runtime resolution.
```
target_link_options(${SIMULATOR_TARGET} PRIVATE "LINKER:-Bsymbolic")
```
This line may need to be conditional depending on compile/target environment.
This gives some breathing room until a better permanent solution is implemented.

**Comment by raphaelcoeffic** [comment]
> Adding the following results in the simulator launching from companion and confirms the issue is the non-unique class name and the runtime resolution.
> 
> ```
> target_link_options(${SIMULATOR_TARGET} PRIVATE "LINKER:-Bsymbolic")
> ```
> 
> This line may need to be conditional depending on compile/target environment.
> This gives some breathing room until a better permanent solution is implemented.

Can you please add this to the PR so we can try it out on all platforms? If that works properly, we can keep it this way for now. From the docs you posted, this looks like what we would want.

**Comment by elecpower** [comment]
Yes will do

**Comment by elecpower** [comment]
@raphaelcoeffic seems depending on what toolchain environment instructions one follows you end up with different versions of cmake. Windows and Qt Creator circa 3.19 and docker image and Ubuntu circa 3.10. target_link_options was released in 3.13. Can you please advise which cmake version I should be targeting the PR.

**Comment by elecpower** [comment]
The switch from branch 2.4 to main confused my local repo and would have made a messy PR so had to do some housekeeping.

**Comment by raphaelcoeffic** [comment]
> target_link_options

No problem, I’ll update the docker image to use a newer version and let you know once this is done.

**Comment by raphaelcoeffic** [comment]
> The switch from branch 2.4 to main confused my local repo and would have made a messy PR so had to do some housekeeping.

Will you open a new PR once you’re done? Any help required?

**Comment by elecpower** [comment]
Yes new PR

**Comment by raphaelcoeffic** [comment]
> > target_link_options
> 
> No problem, I’ll update the docker image to use a newer version and let you know once this is done.

@elecpower docker images should be updating right now (see EdgeTX/build-edgetx@83b3be6c5b8c4fc).

**Pull request closed without merging**
