### PR TITLE
Fix missing Discover telemetry line missing

### PR DESCRIPTION
**Pull request by 3djc**
Fix a bug introduced in #3643 that makes Discover new sensor line disapear on BW ui

### CODE REVIEW

**Comment by pushcommit** [comment]
I am running 2.9.0-selfbuild from stock (bought 12/2023).

It seems like this fix did not make it into my v2.9.0 🤔?

IMG_2049
IMG_2050


Thanks for the help

**Comment by pfeerick** [comment]
Without a screenshot of the SYS -> VERSION page to see the actual date of that build, all we know is it is from time of 2.9 being developed. 

Flash a release version of 2.9 (ie. v2.9.2) rather than a self-build, and see if it goes away.

**Comment by pushcommit** [comment]
IMG_2051

**Comment by pfeerick** [comment]
That explains that then... that is a build from before v2.9.0 was released (2nd of September 2023), and before this fix was merged into the 2.9 branch (1st of July).

**Comment by pushcommit** [comment]
Yeah, missed it by a day or two

**Pull request merged**
