### PR TITLE
feat: bootloader support for SPI NOR flash storage

### PR DESCRIPTION
**Pull request by richardclli**
This PR add support to initialize SPI NOR flash in horus and nv14 targets:

1. Add storage initialization function in bootloader
2. Add placeholders for user to select the use of SPI NOR flash instead of SD card for storage

### CODE REVIEW

**Comment by richardclli** [comment]
I have added TX16S support.  Need to change the commented lines in CMakelist.txt and hal.h to test it out.

**Comment by raphaelcoeffic** [comment]
This sounds cool! I should try it out!

**Review by pfeerick — CHANGES_REQUESTED** [review]
- `ua.h` is missing being updated in this PR
- `he.h`, `jp.h` and `ru.h` need changes around TR_BL_SELECT_KEY to be ASCII text only

**Comment by richardclli** [comment]
I think Raphael still thinking how to make use of internal NOR flash together with SD card.  Need to enable the support of multiple volume of FatFS to really make use of it.  This PR just enable the exploration of usage by adding something in BL to init the NOR flash volume for feature explorarion.

**Review by pfeerick — APPROVED** [review]

**Review by pfeerick — CHANGES_REQUESTED** [review]
Ok I think we have a gremlin hiding in the UI code now. 

After making these changes

image

TX16S is booting up with a SPI file system (I either tried this PR a while back, or this was from an ealier SPI flash experiment), so then proceeded to try and erase the flash... booloader to could see two old firmware files on the SPI flash at this point. I thought the the internal flash storage was not working as after 10 minutes it was still giving me the may take 200s to erase prompt... I tried again and no change, but this time I tried pressing enter again, and noticed the PSU was drawing a little more power, and was then erased, so looks like maybe just a UI/input glitch?

**Comment by richardclli** [comment]
Just like the flashing firmware, it need a long press [Enter] to erase.

**Comment by pfeerick** [comment]
> Just like the flashing firmware, it need a long press [Enter] to erase.

No. The sequence is currently Erase Flash Storage => Erase Flash Storage (Hold [ENT] long to erase) => "This may take up to 200s" => 10 minutes later, short press of ENT... several seconds later returns to main screen, flash has been erased. The short press of ENT should not be needed ;)

**Comment by richardclli** [comment]
This behavior should be the same as PL18,  I never need the short press [Enter], after wait should just return.

**Comment by pfeerick** [comment]
I'll have to check again on the PL18, but I bet you do... not sure this is right? Looks like it **is** halting until ENTER release when in the `ST_CLEAR_FLASH` phase...

https://github.com/EdgeTX/edgetx/blob/cf32dbbed40da88bbb381354cb061b043c02a6e8/radio/src/targets/common/arm/stm32/bootloader/boot.cpp#L534-L535

**Comment by richardclli** [comment]
> I'll have to check on the PL18EV, but I bet you do... not sure this is right? Looks like it **is** halting until ENTER release when in the `ST_CLEAR_FLASH` phase... for **all** `SPI_FLASH` enabled targets ;)
> 
> https://github.com/EdgeTX/edgetx/blob/cf32dbbed40da88bbb381354cb061b043c02a6e8/radio/src/targets/common/arm/stm32/bootloader/boot.cpp#L534-L535

This should be common to all targets.

**Review by pfeerick — APPROVED** [review]

**Pull request merged**
