### PR TITLE
fix(color): Center flight mode text and 6Pos numbers

### PR DESCRIPTION
**Pull request by mha1**
fixes https://github.com/EdgeTX/edgetx/issues/2818

https://user-images.githubusercontent.com/5615068/208301862-d9f20a91-f978-4717-ac99-a8effce8f66d.mp4

### CODE REVIEW

**Comment by mha1** [comment]
This is an alternative implementation to https://github.com/EdgeTX/edgetx/pull/2887 plus new 6 position switch presentation, please see video

**Comment by Eldenroot** [comment]
Looks nice!

**Comment by gagarinlg** [comment]
Did you test this with the NV14 simu/simulator?

**Comment by mha1** [comment]
> Did you test this with the NV14 simu/simulator?

working in it

**Comment by mha1** [comment]
> Did you test this with the NV14 simu/simulator?

Well, it seems NV14 doesn't have a 6Pos. And shouldn't have flight mode texts longer than 6 characters. This is not releated to this PR. Want me to put in an issue?

image

**Comment by mha1** [comment]
@pfeerick I count three thumbs up (@rotorman @eshifri and @Eldenroot), no thumbs down so far. Please decide if this is worthy

**Comment by philmoz** [comment]
Looks good. It's a bit busier than the tick marks so the selected number does not stand apart quite as much (IMHO).
I wonder if it's possible to use a slightly larger font for the selected number so it pops out a but more?

**Comment by mha1** [comment]
I believe fonts have to be generated for different sizes. Those are currently avalable:

```
enum FontIndex
{
  FONT_STD_INDEX,
  FONT_BOLD_INDEX,
  FONT_XXS_INDEX,
  FONT_XS_INDEX,
  FONT_L_INDEX,
  FONT_XL_INDEX,
  FONT_XXL_INDEX,

  // this one MUST be last
  FONTS_COUNT
};
```

XS is used for the numbers. The next step up from XS is L. This is what it looks like:
image

Using L you'd need to change the box size, the spacing (with it width changes), the vertical position of the numbers  and it would move the flight mode up. Think this effort is not justified and moving flight mode text up probably interferes with the widget area. And I believe generating a new font with maybe 1 or 2 pixels size increase would also be frowned up by management.

**Comment by philmoz** [comment]
I was also playing with this, here's a small tweak to your idea.
The change to the selected number display is:
     dc->drawNumber(x+MULTIPOS_W_SPACING/4, **-2**, value+1, FONT(**BOLD**) | COLOR_THEME_PRIMARY2);

Screen Shot 2022-12-19 at 9 10 04 pm

**Comment by mha1** [comment]
great idea, looks much better!

image

**Comment by philmoz** [comment]
I think this is the preferred solution, will close my PR in favour of this.

**Comment by ParkerEde** [comment]
Now that we've already had a hand in the flight mode, could this ticket be made at the same time?
https://github.com/EdgeTX/edgetx/issues/2688

**Pull request merged**
