### PR TITLE
chore(cpn): remove some compiler warnings

### PR DESCRIPTION
**Pull request by elecpower**
Remove some easy ones

### CODE REVIEW

**Comment by mha1** [comment]
Hi, is there a specific reason to type cast passed parameters within the function rather than changing the functions signature and making sure the calling function passes the correct data type?

**Comment by elecpower** [comment]
> Hi, is there a specific reason to type cast passed parameters within the function rather than changing the functions signature and making sure the calling function passes the correct data type?

To maintain consistency with other label related function signatures and if changed all signatures then likely same issue arise again in other functions. Too many other tasks to do than to go down this rabbit hole.

**Comment by mha1** [comment]
> > Hi, is there a specific reason to type cast passed parameters within the function rather than changing the functions signature and making sure the calling function passes the correct data type?
> 
> To maintain consistency with other label related function signatures and if changed all signatures then likely same issue arise again in other functions. Too many other tasks to do than to go down this rabbit hole.

Thanks for your response and I appreciate your effort. Please don't get me wrong but I'd rather leave it as it was because the warning indicates a potential problem or ambiguity in need of consideration. Just type casting it in this way will get rid of the warning but doesn't solve the potential underlying type conflict. Getting rid of the warning leads to a real todo to be forgotten.

**Comment by elecpower** [comment]
Compiling in Ubuntu does not generate a compiler error or warning if the function signature is unsigned int and it is called passing an int which is currently coded. So in changing the signature we introduce a potentially hidden future gotcha.
If we want to go strict then no PRs should be merged until the submitting dev eliminates all warnings, coding standards are met, etc so others do not have to clean up the residual.
I appreciate where your coming from but this is a community project, not a commercial one so there has to be compromises or contributions would dry up if we get pedantic.
My objective of this PR is to use explicit casting to reduce the relatively minor warnings without refactoring so the important ones stand out. Agree not ideal.

**Comment by mha1** [comment]
I get your point

**Comment by gagarinlg** [comment]
A cast might just be the correct fix, in some cases. The warning is there to force the developer to think about this piece of code. When it is good like it is because e. g. you checke the value before casting, the cast is the right fix for the warning.

**Pull request merged**
