### PR TITLE
fix: use keysGetMaxTrims() instead of MAX_TRIMS

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by pfeerick** [comment]
FWIW... I'm not surprised the xlite splattered... every time I've had to use simu with it, I've had to disable an assert related to the trims for it to build 🤪

**Comment by pfeerick** [comment]
@raphaelcoeffic Realised after merging this that it appears to stop MDL/SYS/TELE buttons on TX16S responding - not even picked up in diags screen - everything else was fine though for it, NV14 and T20, and worked again when I went back to another PR build.

**Comment by philmoz** [comment]
Changing keysGetMaxKeys() back to MAX_KEYS fixes it (issue occurs in simulator as well).
Had to change keys.cpp and radio_diagkeys.cpp files.

**Comment by pfeerick** [comment]
Fix already somewhere between editor and github, and thanks...

**Comment by raphaelcoeffic** [comment]
@philmoz this does not work?

```c++
for (uint8_t i = 0; i < keysGetMaxKeys(); i++) {
  auto k = get_ith_key(i);
  // some more code
}
```

**Comment by philmoz** [comment]
> @philmoz this does not work? (in `radio_diagkeys.cpp`)
> 
> ```c++
> for (uint8_t i = 0; i < keysGetMaxKeys(); i++) {
>   auto k = get_ith_key(i);
>   // some more code
> }
> ```

Yes, that works in radio_diagkeys - I was looking at the wrong thing.

Maybe the keys.cpp code needs to all get_ith_key as well rather than use MAX_KEYS.

**Comment by raphaelcoeffic** [comment]
> Maybe the keys.cpp code needs to call get_ith_key as well rather than use MAX_KEYS.

I fixed it directly in `main` by reverting to using `MAX_KEYS` just for scanning the keys.

**Pull request merged**
