### PR TITLE
feat(sim):  hat switches support for NV14 and EL18

### PR DESCRIPTION
**Pull request by elecpower**
Summary of changes:
- new graphics
- hats
- needs to work in conjunction with #3894

To do:
- [x] graphics for hat and direction clicks
- [x] clickable areas overlaying graphics
- [ ] keys associated with clicks

### CODE REVIEW

**Comment by pfeerick** [comment]
@elecpower Where were things at with this PR? Was it just making the key events work properly now? Is there anything I can do to help with that now? I have the the handsets as well as some idea of how the hat switching functionality worked...

**Comment by elecpower** [comment]
@pfeerick it's been some time so I'll have to get back up to speed, likely tomorrow.

**Comment by pfeerick** [comment]
Thanks. No rush ;)

**Comment by elecpower** [comment]
The hat direction buttons appear to work. Key mapping validation and testing seems to be the missing piece. I think I just did a best guess.
Also ADC refactor has come along and so some more changes to key mappings likely necessary.
If you could test and let's see what else needs fixing.

**Comment by elecpower** [comment]
This may have short life if generic works sooner rather than later

**Comment by pfeerick** [comment]
lol... I think so... I was going to ask how did you want to proceed with this... i.e. finish and get it in or just implement it in generic form...

**Comment by elecpower** [comment]
If it is ready I'd merge so the sim can be tested.

**Comment by pfeerick** [comment]
Ok, I'll check it tonight, let you know what is/isn't working and we can re-evaluate from there ;)

**Comment by pfeerick** [comment]
Ok, state at present is this... all good except two buttons not doing anything... not sure why though. I moved some buttons around though, and also gave the EL18 same treatment... If nothing obvious stands out, I think it's worth merging until it can be resolved. 

```
Left side:
Up     = OK, RADIO SETTINGS
Down   = OK, SCREEN SETTINGS
Left   = OK, MODEL SETTINGS
Right  = NONE
Press  = OK, RTN

Right side:
Up     = NAK, not incrementing/moving up
Down   = NAK, not decrementing/moving down
Left   = OK, NEXT PAGE
Right  = OK, PREV PAGE
Press  = OK, ENTER
```

**Comment by JimB40** [comment]
> Left side:
> Up     = OK, RADIO SETTINGS
> Down   = OK, SCREEN SETTINGS
> Left   = OK, MODEL SETTINGS
> Right  = NONE
> Press  = OK, RTN
> 
> Right side:
> Up     = NAK, not incrementing/moving up
> Down   = NAK, not decrementing/moving down
> Left   = OK, NEXT PAGE
> Right  = OK, PREV PAGE
> Press  = OK, ENTER

Is that for Simulator in Companion?
Key bindings to hats movement are somehow different than in firmware :)
MDL is LeftHat Right
PAGE> is RightHat Right
PAGE< is RightHat Left

**Comment by pfeerick** [comment]
No, I simply have left and right swapped. Companion simulator matches
hardware.

**Comment by pfeerick** [comment]
Given I think https://github.com/EdgeTX/edgetx/pull/3932#issuecomment-2298515488 is related to some work needed in simulator layer for to support NV14/EL18 (and probably PL18/PL18EV also), rather than a bug in this PR, I'm going to merge this sooner rather than later so it is in place for when simulators get further UI rework.

**Comment by philmoz** [comment]
Appears to be missing right side Up / Down navigation:
screenshot_nv14_24-10-24_16-03-18

**Comment by pfeerick** [comment]
Correct. As per the comment referenced above.

**Pull request merged**
