### PR TITLE
Fix failsafe settings

### LINKED ISSUE #1393: Failsafe Mode and Failsafe Positions Problems
**Describe the bug**
Two issues
1. The Failsafe Mode and Failsafe Settings do not appear in the Model Settings screen on my radio for Internal mm RF module set to the DSM protocol.  They are displayed in the Companion Model Setup screens for these models read from the radio.  The radio does display these items in the model setup screens for my FrSky protocol models.  I only have DSM and FrSky receivers.
2. The Failsafe Settings are all set back to zero whether I change them to non-zero values in the radio and read them back to Companion or change them in Companion and write them to the radio. PILOTS TAKE NOTE BEFORE FLYING WITH 2.6.0-RC2.

**General information**
  - EdgeTX 2.6.0-rc2
  - Companion Version 2.7.0 "dev", Jan 9 2022
  - Windows 10 - latest rev
  - RadioMaster TX16s

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolve #1393

Summary of changes:
- (de-)serialize failsafe settings properly
- fixed radio failsafe display (use proper scale instead of raw value)

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@elecpower this is only missing the fix related to failsafe mode & MPM (see #1393).

**Comment by pfeerick** [comment]
How about we split that (failsafe mode & MPM) off as an separate issue, since it's not a new change in behaviour?

**Comment by raphaelcoeffic** [comment]
> How about we split that (failsafe mode & MPM) off as an separate issue, since it's not a new change in behaviour? 

Ok, then let's have a separate PR for that.

**Review by pfeerick — APPROVED** [review]
LGTM. TX16s and X9D+2019. Failsafe screen on colorlcd needs more work generally, but this appears to fix the intended issues.

**Pull request merged**
