### PR TITLE
feat(cpn): add support for surface radios inc Radiomaster MT12

### LINKED ISSUE #4969: Companion add MT12 support
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No companion support for mt12 yet

### Describe the solution you'd like

Can use companion with mt12

### Describe alternatives you've considered

_No response_

### Additional context

I didn't see any issue or PRs related to MT12 companion support, thought it might be useful to have an issue to track progress and coordinate contributions?

Wondering if there is some way I can contribute, I understand there are a lot of differences so may be a fair amount of work.

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #4969

Summary of changes:
- add support for surface radios
- add support for Radiomaster MT12
- move lcd capabilities from firmware to boards
- minor fixes found during testing
- more post ADC refactor fixes
- housekeeping

TODO
- [x] surface radio configuration
- [x] Companion yaml encode/decode own models and settings
- [x] surface radio decode Companion encoded yaml
- [x] Companion decode radio encoded yaml
- [x] surface radio simulator
- [x] MT12 default settings eg battery, screen
- [x] MT12 radio configuration
- [x] MT12 generic simulator operation i.e. no custom images and buttons

Screenshot from 2024-09-19 09-07-24

### CODE REVIEW

**Comment by 3djc** [comment]
Add a very brief look, on the simu, the left stick can only be moved horizontally and does steering, good, but the right one that does throttle,  is also only horizontal, which makes it really difficult for user to understand which one is which. Could the right one made to only move vertically ?

**Comment by philmoz** [comment]
Looking good - will do more testing later.

One thing - button text is clipped slightly on MacOS.
Screenshot 2024-09-21 at 8 25 57 AM

**Comment by philmoz** [comment]
Reading from radio and writing back to radio seems to work ok. No obvious issues with conversion.

**Comment by philmoz** [comment]
I think the LCD and buttons could be bigger.

I had a look at the LCD code and it seems it could do scaling based on widget size (rather than just x2):
Screenshot 2024-09-21 at 9 43 29 AM

Patch for this (have not tested if it affects other simulators yet):
[lcd scale patch.diff.txt](https://github.com/user-attachments/files/17081678/lcd.scale.patch.diff.txt)

**Comment by elecpower** [comment]
If we enlarge the lcd then buttons could also be enlarged and widened to take into account each OS font.

**Comment by elecpower** [comment]
Need to test layout for the new screen size you have been working on for a while so we have the full range covered.

**Comment by elecpower** [comment]
@pfeerick can we get this one is asap to exposed to more testers and opinions plus reduce the complexity of any merge conflicts.

Another PR on a generic sim for all radios would follow including auto resizing to lcd and scale the smaller ones along the lines @philmoz has suggested.

**Comment by elecpower** [comment]
I'm also considering custom surface widgets for throttle/brake and steering to substitute for the air joysticks. Will need to determine how much effort and float mock up with surface users.

**Comment by pfeerick** [comment]
If you are happy with this as it is, fine with me :) I'm not able to do much for the next few days on project so won't catch anything more than blindingly obvious issues. Just downloading the PR build now, will merge shortly if nothing immediate jumps out.

**Comment by elecpower** [comment]
@3djc and @philmoz have performed some checks and nothing stood out. Some   other testers this far out from 2.11 release is a good thing to enable time to fix.

**Comment by bd4** [comment]
Thanks for all the work on this! will test this weekend.

**Comment by HungryGhostLiving** [comment]
Kills Global Functions/Special Functions switch data  when copying model in companion MT12

**Comment by elecpower** [comment]
Steps to reproduce please as this is too vague

**Comment by HungryGhostLiving** [comment]
After you import from radio, if you export the same model, then copy to a new model slot the switches loose assignment. To repeat import models with special functions via companion, S function dual rate to a trim as example. 
 Copy imported model in companion to a new model. Turn on radio go to new model you just copied on the radio  and global functions will still show in drive modes, and pop up still works but inputs  do not change channel parameters.

**Comment by pfeerick** [comment]
Detailing only the minimum reproducible steps is important for any bug report to ensure it is actually possible to reproduce, and so that *only* what is necessary to trigger the perceived bug is focused on. It's nice to know other stuff is working, but that is not the focus of the bug report. Which, by the way, really should have been added as a new issue/bug report, rather than a comment to a closed PR.

Since you have not mentioned, I will have to assume that you are running a recent nightly firmware and matching version of Companion - as failure to do so for any handset/firmware combination is **_always_** going to lead to issues at some point if reading/writing settings. e.g. using newer companion with older firmware can result in settings being written in a new format that the older firmware is not compatible with. 

You've said that GF/SF switch data is lost  - is this the SF trigger/switch or something else? Is it specific to a particular SF... i.e. Adjust GV? Is it loosing for any switch you've configured, or just a particular one? i.e. 

It sounds like you are exporting and importing... ( the `.yml` files?) ... to copy... rather than just doing a copy and paste? Intentional for your workflow, or did you not realise you could just copy and paste models?

I have tried to reproduce this on MT12 with recent firmware and companion, by creating several SFs, reading radio, exporting the model, opening/importing the yml, reading the radio again, dragging the model to an new slot, and then writing it back. All the SFs still exist and trigger. So either I'm not able to reproduce the problem/steps enough from your description, or there is some different in your setup causing it.

**Pull request merged**
