### PR TITLE
Serial refactor

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
## Changes description:

- generic STM32 Serial driver, applied to internal and external serial modules.
- generic STM32 timer base pulse driver, applied to internal and external modules.
- generic AUX serial driver, based on the generic STM32 driver.
- UI lists available serial ports dynamically and allows for assigning a function to each port (AUX1, AUX2, VCP).
- each serial function can be assigned to *at most* exactly one port.

## Supported Serial Functions

The following serial functions are supported on AUX1/AUX2:
- Telemetry Mirror (any protocol)
- Telemetry Input (*missing protocol selection on color UI*)
- SBUS trainer (normal UART polarity)
- LUA (input/output)
- CLI
- GPS

The following function are supported on VCP:
- Telemetry Mirror (any protocol)
- LUA
- CLI

*Please note:*
- Serial passthrough has only limited support over AUX1/AUX2 as it does not support automatic baudrate changes. It is however planned to add a baudrate setting command to allow for forcing a specific baudrate on the primary connection.
- Baudrate per port (AUX1/AUX2) and additional parameters per function will be added later (probably in 2.8).

TODOs:
- [x] `VCP` serial mode should default to `CLI`.
- [x] Companion support (YAML format for port settings have changed; Firmware is backward compatible with Companion though)

### CODE REVIEW

**Comment by wimalopaan** [comment]
Maybe we can consider #1272 also?

**Comment by raphaelcoeffic** [comment]
> Maybe we can consider #1272 also?

In the long run, yes, but that requires adding a more generic way of implementing software serial. Some radios do have configurable inverters on some serial ports (like NV14 for instance), but this is rather rare.

**Comment by brainbubblersbest** [comment]
Flashed fae5874 to test serial-refactor on x12s
Aux1 is shown in ui, but cant be changed to Externalaccess. (Uart3)
Aux2 is not shown in ui. 
(if i read correct, you swapped Uart 6 for Uart 4 to make use of the jst connector)

CON: Solder Wires To BT Pads wont work this way. 
PRO: GPS Connector its better for change connected Devices.  

An additional Aux3 option for UART 4 wouldnt make sense here?
I know its the only Radio with 3 usable Uarts and its maybe not worth the effort. ;)
Anyway: Thank you for This Huge Work. 👍

**Comment by raphaelcoeffic** [comment]
On X12S, the GPS is hardwired. To be able to keep it as a serial function, the port is added “hidden” (name is empty).

Regarding the access mod, having it configurable will require to further streamline the modules, which is part of the plan. So be patient 😜

**Comment by brainbubblersbest** [comment]
The gps on uart 4 is not hardwired. I swapped mine to bn180. There is a jst plug on the Mainboard. 😉 Best way to connect a esp32 instead. 

I also removed my Horus BT Module on Uart6 to use it as a Serial.
With the activate BT with EN Pin functionality, remove is not longer in need.

**Comment by raphaelcoeffic** [comment]
> The gps on uart 4 is not hardwired. I swapped mine to bn180. There is a jst plug on the Mainboard. 😉 Best way to connect a esp32 instead.

Ah! Good to know! Ok, then we might make it configurable in later releases.

> I also removed my Horus BT Module on Uart6 to use it as a Serial.

Configuring BT serial on run-time is coming next 🤓

**Comment by pfeerick** [comment]
Below is my running log, but these are the main points:

- NV14 seems to have issue with VCP set to LUA... something to look into in the future and CLI option missing
- TX12, X9D+, X9D+2019 don't have VCP entries?
- Zorro radio fw vs Companion - one is not correct...
- maybe we can change "USB Serial (Debug)" to "USB Serial (VCP)" so no more nasty "Debug"? 😄 

This is looking pretty good! Just some loose ends to tidy up and it is ready to set loose... 😆 

TX16S:
- AUX1/2 GPS working
- AUX1 T. Mirror working
- VCP CLI, TMirror
- Int MPM (Flysky) working
- external XJT and ELRS working
- topbar GPS icon seems wonky (I'll look into)

NV14
- Internal RF & ext CRSF still working
- **VCP : OFF, T Mirror and LUA... no CLI?
- Setting to LUA EMs radio shortly afterwards**
- Companion shows AUX + VCP, vs VCP only on radio

TX12
- Internal MPM still working
- CRSF & XJT external working
- **No VCP or AUX entries?**
- USB storage and joystick working

TPro
- Only checked HW screen - VCP only, TMirror, LUA, CLI
- Companion matches

Zorro
- XJT Lite still working
- CRSF (int), CRSF (ext) working
- Radio has AUX1 and VCP, but companion only shows VCP... which is wrong?
- No TMirror with XJT lite, but works with ELRS/CRSF - expected?
- Could see ExpressLRS lua messages when VCP was in TMirror mode?

X9D+2019
- internal - no idea - still haven't flashed a receiver to ACCSTv2
- CRSF & XJT external working
- USB storage working
- **no AUX/VCP options** - perhaps AUX is becasue it has SPORT instead?

X9D+
- internal - unable to test as antenna mount for new case should arrive this work
- CRSF + XJT external working
- AUX1 entry only, TMirror, Telem In, SBUS trainer, LUA
- USB storage and joystick working

**Comment by raphaelcoeffic** [comment]
> X9D+2019 no AUX1

It seems the port is used by the external ACCESS UART.

**Pull request merged**
