### PR TITLE
Add Lua file system operations

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This is a port of opentx/opentx#6148 to add basic filesystem operations like listing a directory or get file info. Thx @mpaperno for pointing us at this old gem!

### CODE REVIEW

**Comment by mpaperno** [comment]
Hi Raphael,

Looks good to me...  ;-) 

Regarding your comment on the other thread:

> Only aspect I would change would be to use an iterative method for “ls” operation, thus avoiding to return a table which can have a potentially very big size (mem constraints, again…). This way, scripts could have the same memory consumption regardless of the number of files in directory.

Yes this is a very good point.  Got any ideas?  :)

My first thought was literally some kind of iterator routine which would yield results one at a time.  Often referred to as a "coroutine." Lua even has [the concept](https://www.lua.org/pil/9.1.html) and a promising C API function [`lua_yield()`](https://www.lua.org/manual/5.3/manual.html#lua_yield)... and I see @jfrickmann even refactored the Lua interface to support `LUA_YIELD` response/etc. However, upon further investigation it seems this isn't going to help us... for a number of reasons but primarily because of the way Lua implements this feature, the C function has to `return lua_yield(L);`  Which is basically useless w/out some kind of worker thread with state tracking and data buffer (in this case), etc.  Or maybe I'm wrong and someone with direct experience here can chime in.

Another option would be some kind of "get next N result(s)" parameter, so the `ls` only returns N results at a time (perhaps one by default).  The problem here is that we'd have to re-scan the directory each time,`fileSystem()` is called, iterate to the Nth item, then return the result(s).  I don't see a way to efficiently cache the results, and besides that wouldn't help the memory issue anyway.

So... third option is to basically recreate what FatFS does, which you can see in the code which handles `ls`.  (There's a reason FatFS does it this way, and it's pretty much the same issue as with Lua, eg. possibly need a huge buffer.)  That is, have 3 separate calls to get a listing:

```lua
-- get directory file handle for reading
fh = fileSystem("opendir", path)
return if fh == nil  -- psuedcode
while (1) do
  -- get next listing as a result code and file info table
  result, fi = fileSystem("readdir", fh)
  -- nil fi means end of listing, or error (check if result == 0)
  break if fi == nil
  -- do something with file info, break early if finished
end
-- don't forget to close (can we hook this somehow to ensure it always gets closed, eg. if script crashes/etc)
fileSystem("closedir", fh)
```

Maybe not those exact op names, but you get the idea.  More verbose to use, but should solve the issue you rightly bring up.  Shouldn't be hard to implement on C side (he says glibly... oh and assuming the `DIR` handle stays valid between calls, until closed).  Not sure how to handle my last comment in the code above, if even possible.

I'm out of ideas on this for now  :)

Cheers,
-Max

**Comment by raphaelcoeffic** [comment]
I was actually thinking about something along the lines of the example shown here:
https://www.lua.org/pil/29.1.html

This allows this kind of LUA code:
```
for fname in dir(".") do  print(fname)  end
```

It uses `lua_pushclosure` to encapsulate the iterator functionality, and leverages the LUA GC to make sure `DIR` is closed after use.

**Comment by mpaperno** [comment]
Yea that would be perfect, basically what I was looking for with the coroutines.  But how to register that "dir" function like they do in the book example? Or more specifically I guess the GC routine.  We need a new "library," with it's own meta table, just for this feature, with its own `__gc` function...?   OTOH the `opentxLib` doesn't seem to have a `__gc` function now (at least the old version I'm looking at) so it could be usurped I suppose... but would make it unavailable/unusable for anything else down the line (if I understand all this correctly).  I'm also vague on when exactly this GC runs, among some other things.

**Comment by mpaperno** [comment]
PS. The color LCD bitmap handling in `api_lcd.cpp` does the `__gc` thing (search `bitmapFuncs`). Though again I may be looking at something old.

So does `flib` in `liolib.c` (in Lua source).  Come to think of it, one could extend the current `io` library with something like "dir" or even the other features as direct method (instead of a monolithic `fileSystem()` function for everything).  It currently has no `__gc`, and would maybe save a bit of overhead memory vs. creating a new library.  But it would be kinda "abusing" a standard Lua lib.

**Comment by raphaelcoeffic** [comment]
> PS. The color LCD bitmap handling in `api_lcd.cpp` does the `__gc` thing (search `bitmapFuncs`). Though again I may be looking at something old.
> 
> So does `flib` in `liolib.c` (in Lua source). Come to think of it, one could extend the current `io` library with something like "dir" or even the other features as direct method (instead of a monolithic `fileSystem()` function for everything). It currently has no `__gc`, and would maybe save a bit of overhead memory vs. creating a new library. But it would be kinda "abusing" a standard Lua lib.

I have not looked at memory implications yet, but it sounds good to have single functions. It’s probably easier to use.

**Comment by mpaperno** [comment]
Each entry has some overhead which is why I didn't create separate functions in the first place.  I can't tell you how large exactly, at least a few pointer's worth I imagine. Certainly introducing a whole new library (with its own meta table) would have a more significant impact (again, can't quantify).  Lua is not exactly known for memory efficiency, as you probably know, which is one reason it had to be "hacked" for OTX use (to use the `rotables`).  I mean what does one expect from a system that uses 64 bits to store 1 byte's worth of data (eg `double` storing a `short`)?  :)

OTOH I see `std::string` and dynamic arrays and such being used in the newer radio code, so I'm guessing memory isn't an issue there!

**Pull request closed without merging**
