### PR TITLE
Refresh Windows, Linux and Mac Companion icons + helper script

### PR DESCRIPTION
**Pull request by pfeerick**
Simple icon generator tool that grabs the icon from the website repo, and uses it to create the linux and windows icons.

Caveats:
- it doesn't do the SVG scalable icon for linux, as I can't readily find find a PNG => SVG conversion module. 
- pillow (the image toolkit) doesn't do all the windows icon sizes, so some of them are different sizes - but I would also question if all those sizes are actually needed, as pillow only supports the "standard" sizes
- havn't even considered the mac icon ;)

Should help a bit with #555 (not to be confused with the triple 5 timer!)

### CODE REVIEW

**Comment by elecpower** [comment]
@pfeerick you can change generated file names in images/winicons to edgetx prefix and edit icon.rc and all should work if not on me to fix.

**Comment by pfeerick** [comment]
Ask and ye shall receive ;)

**Comment by elecpower** [comment]
> * it doesn't do the SVG scalable icon for linux, as I can't readily find find a PNG => SVG conversion module.

From my searching seems base image is generally svg and other formats derived from it

**Comment by pfeerick** [comment]
Yeah, that is the way it should be, since SVG is the infinitely scalable version... but it is possible to convert the other way for those "just need it in SVG to satisfy requirement X" moments... Since I've also done the other images, I might just use a online converter and do just replace it.

**Comment by pfeerick** [comment]
Screw it... Inkscape PNG to SVG save it is... online converters were useless. It isn't ideal, as it won't be properly scaleable (upwards, at least), but at least if something in companion uses it it will be the correct logo. I suspect it was probably the source image for all the other icons though.

**Comment by elecpower** [comment]
I'll see how clever you are when I next compile and test companion

**Comment by elecpower** [comment]
Tested on Ubuntu and we need a file to replace images/icon.png size 96 x 96 pixels.
I made a temp one up from your svg, compiled and success.
Needs testing on Windows and when @JimB40 has time to generate a new iconmac.icns on OSX
Many thanks for your help ;-)

**Comment by pfeerick** [comment]
Like so? One of these days, I think we should be able to go through all of these and remove most of them... probably find out we only need a handful of the 'icon' graphics.

**Comment by elecpower** [comment]
Found this python script for icns https://github.com/retifrav/python-scripts/tree/master/generate-iconset. It is licensed under MIT.

**Comment by elecpower** [comment]
> One of these days,

Yeah when there are no open issues, all PRs merged, no new radio hardware, no new protocols, the devs are in covid lockdown or can't sleep...of course LOL

**Comment by pfeerick** [comment]
Oh, nice... so ImageMagick can be used for that file... thanks for that! Ok, that will be tomorrows commit. You've had my quota of brain cells for the weekend 😜  Plus I'm in mourning over the loss of my Taranis X9D+... 😿

**Comment by elecpower** [comment]
You need to change the title of this PR again ;-)
FYI I've created title and splash images for  companion in my big PR just to change the branding. Someone with some real gfx skills could have a go later.

**Comment by pfeerick** [comment]
I was hoping no-one would notice... although I suppose the native mac generation code is basically someone elses (with attribution)... so if it's broken I can deny all knowledge, especially cause I'm too lazy to bother running up a MacOS VM again... 😆

**Pull request merged**
