### PR TITLE
feat(el18): Use trim hats as keys for navigation

### PR DESCRIPTION
**Pull request by mha1**
Fixes [#3202](https://github.com/EdgeTX/edgetx/issues/3202)

Summary of changes:
- implemented navigation by trims (hats) on NV14/EL18
- specification by @JimB40 

NV14-EL18_hats_modes

### CODE REVIEW

**Comment by mha1** [comment]
nope, have at it.

**Comment by mha1** [comment]
Neil, you might want to wait a bit. There was some UI discussion started, see #3202

**Comment by elecpower** [comment]
Michael, noted though I'll do the common parts and pause until the discussion reaches a conclusion

**Comment by elecpower** [comment]
@mha1 here is my version of cpn side for consideration and merging onto yours. Note: mine is branched from yours.
https://github.com/EdgeTX/edgetx/tree/elecpower/cpn-nv14-trims-as-keys

**Comment by mha1** [comment]
First go at model level hats mode selection (overriding radio setting).

**Comment by elecpower** [comment]
@mha1 I updated my branch with your latest and added model level setting code on my branch again.
Note: to be consistent with the new way of encoding and decoding yaml values I have mapped the enum to/from text. Companion side only.  Feel free to change the text I chose but ensure identical on both sides.

**Comment by mha1** [comment]
@elecpower Thanks, merged and harmonized radio and companion yaml tags and id's

@pfeerick @JimB40 please let me know if you came to an agreement were best to put the hats mode model level settings. after ADC filter or in Trims doesn't make a difference for me. I believe it fits the Trims head line pretty well but don't mind shifting it one level up. Just let me know.

**Comment by JimB40** [comment]
For me either Peter decides.

**Comment by elecpower** [comment]
@mha1 Michael I would strongly recommend adding back the HATS_ prefix to then enums as there are other MODEs already and likely in the future. Having an enum of MODE_GLOBAL when it is not global is sure to mislead and catch someone out. The yaml text is in context of the label so I have no issue with hatsMode: GLOBAL

**Comment by philmoz** [comment]
PR #3903 adds the bubble popup you were asking about on Discord.

**Comment by pfeerick** [comment]
> in Trims

Is fine... I hadn't considered the "trims off means navigation only" path Robert mentioned earlier, so if trims get disabled at the radio or model level, that option will implicitly get forced to "keys only".

**Comment by mha1** [comment]
@philmoz This is so much better. Thank you very much! I merged your PR and unfortunately pushed. Do you want me to revert this commit and wait for your PR to be merged?

**Comment by philmoz** [comment]
> Thank you very much! I merged your PR and unfortunately pushed. Do you want me to revert this commit and wait for your PR to be merged?

No problem - better to get it tested anyway. We can sort it out when the PR's get merged.

**Comment by mha1** [comment]
tried it on your el18?

**Comment by philmoz** [comment]
> tried it on your el18?

The build from this PR works on my EL18.

I would suggest that the default for the model level setting should be Global (like enabled features).

If you look at the 'Enabled Features' model settings, I display the current radio level setting when the model is set to global to let users know the state. Might be nice to add this as well.

**Comment by mha1** [comment]
Thank you for testing and your suggestion, makes sense. Will discuss with @JimB40

**Comment by mha1** [comment]
Added hats mode defaults:
- radio settings: Trims only (inherently set to Trims only by memclear)
- model settings: Global

**Comment by mha1** [comment]
Dear Translators, 

I'd very much appreciate your support for a new NV14/EL18 feature.

FlySky NV14/EL18 radios have two little joy sticks usually used as trims. Those joysticks are called "hats". This PR adds logic to make the hats available as keys for navigating the GUI. The hats can be moved up, down, left, right and pressed. "Hats mode" refers to the state of the hats. In "Trims mode" the hats act as trims, in "Keys mode" they act as Keys according to the key map shown in https://github.com/EdgeTX/edgetx/pull/3894#issue-1833036739. Switching between the two hats modes is possible. Option "Switchable" refers to a users setting that allows switching between trims mode and hats mode.

Don't hesitate to ask if you have any question.

ENG original text:
#define TR_HATSMODE                    "Hats mode"
#define TR_HATSOPT                     "Trims only","Keys only","Switchable","Global"
#define TR_HATSMODE_TRIMS              "Hats mode: Trims"
#define TR_HATSMODE_KEYS               "Hats mode: Keys"

- [ ] @zyren CN / TW
- [ ] @Eldenroot CZ
- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes DE
- [ ] @Pat6874 FR
- [ ] @offer-shmuely HE
- [ ] @robustini IT
- [ ] @ToshihiroMakuuchi JP
- [ ] @ulfhedlund SE
- [ ] @ajjjjjjjj PL

Thanks,
Michael

**Comment by Pat6874** [comment]
in FR:

#define TR_HATSMODE "Mode chapeaux"
#define TR_HATSOPT "Trims uniquement","Touches
uniquement","Permutable","Global"
#define TR_HATSMODE_TRIMS "Mode chapeaux: Trims"
#define TR_HATSMODE_KEYS "Mode chapeaux: Touches"

**Comment by HThuren** [comment]
Hi Michael, Can we understand 'hat' as a joystik ?

**Comment by mha1** [comment]
@HThuren Well, they are little joysticks and I suppose the are called hats because the sticks grow wider at the top. To me the little joystick sticks look a bit like tiny mushrooms. I'll leave it to up you. Call it whatever makes sense in your language. Maybe calling them joystick might collide with the USB mode where the radio can act as Joystick when connected to a PC.

**Comment by Eldenroot** [comment]
I am thinking about to use “joysticks” word for these "hats".

**Comment by mha1** [comment]
I think calling the hats Joystick will be confusing. There is a USB mode Joystick and the Hats mode setting in radio settings is right below the USB mode settings.

image
image

**Comment by Eldenroot** [comment]
Well, maybe joystick USB should be renamed then... because hats mode is more confusing :)

**Comment by mha1** [comment]
We don't want to open this can of worm, don't we? Hats is a NV14/EL18 thing only. By calling the hats hats (I understand this is a real term for the NV14/EL18) you confuse NV14/EL18 owners only (if at all).

**Comment by mha1** [comment]
Oh, and dont worry to much, the Hats mode setting is visible on NV14/EL18 radios only.

**Comment by Eldenroot** [comment]
CZ:
#define TR_HATSMODE "Režim kloboučků"
#define TR_HATSOPT "Pouze trimy","Pouze tlačítka","Přepinatelné","Globální"
#define TR_HATSMODE_TRIMS "Režim kloboučků: Trimy"
#define TR_HATSMODE_KEYS "Režim kloboučků: Tlačítka"

**Comment by HThuren** [comment]
don't intend to make caos :-)
From my point of view a joystik ara a stik you can move around - like you describe 'hat - but we also have the 2 pins :-)
I will see the Swedish translation ;-) maybe Ulf have a good suggestion

**Comment by robustini** [comment]
IT

#define TR_HATSMODE "Modo hats"
#define TR_HATSOPT "Solo trims","Solo keys","Commutabile","Globale"
#define TR_HATSMODE_TRIMS "Modo hats: trims"
#define TR_HATSMODE_KEYS "Modo hats: keys"

**Comment by JimB40** [comment]
Agree that "joystick" name for USB mode is not the best, should be something like "Sim controler". but it is used already here and there in OS and even in ELRS script an people got used to to this name for this feature.

What you say about:
Multi-direction buttons mode
or shorter.
Multi-dir buttons mode.

In fact hats are devices that have 5 on/off buttons while joystick is device that gives as output different angle values.

**Comment by Eldenroot** [comment]
lets rename the simulator for PC mode

**Comment by offer-shmuely** [comment]
HE
#define TR_HATSMODE "מצב כובעונים"
#define TR_HATSOPT 
"קיזוזים בלבד",
"ניווט בלבד",
"משולב",
"גלובאלי"

#define TR_HATSMODE_TRIMS 
"מצב כובעונים: קיזוזים"
#define TR_HATSMODE_KEYS 
"מצב כובעונים: ניווט"

**Comment by zyren** [comment]
CN
```c
#define TR_HATSMODE "按键帽模式"
#define TR_HATSOPT "微调","导航键","可切换","全局"
#define TR_HATSMODE_TRIMS "按键帽: 微调"
#define TR_HATSMODE_KEYS "按键帽: 导航键"
```

TW
```c
#define TR_HATSMODE "按鍵帽模式"
#define TR_HATSOPT "微調","導航鍵","可切換","全局"
#define TR_HATSMODE_TRIMS "按鍵帽: 微調"
#define TR_HATSMODE_KEYS "按鍵帽: 導航鍵"
```

**Comment by ajjjjjjjj** [comment]
PL
```c
#define TR_HATSMODE "Tryb grzybków"
#define TR_HATSOPT "Tylko trymy", "Tylko przyciski", "Przełączane", "Globalne"
#define TR_HATSMODE_TRIMS "Tryb grzybka: trymy"
#define TR_HATSMODE_KEYS "Tryb grzybka: przyciski"
```

I don't really feel "hats" for that purpose in polish, changed it to "mushrooms" which feels more natural in polish for what it is. But I will revert if you want.

**Comment by mha1** [comment]
@ajjjjjjjj thanks, you're the expert

**Comment by pfeerick** [comment]
Another name for this type of switch is "Hat switch" (i.e. as used on joysticks), so Hats is technically correct ;) And given the joystick mode is for... well, use as a joystick (it's not "simulator mode" 🤦) I don't see that changing anytime soon 🤣

**Comment by ulfhedlund** [comment]
@HThuren: I was hoping you could give me some ideas 😉 I'm away from computers for a week and not sure how to translate this. Will give it some thought and get back later in the week.Den 6 aug. 2023 19:21 skrev HThuren ***@***.***>:
don't intend to make caos :-)
From my point of view a joystik ara a stik you can move around - like you describe 'hat - but we also have the 2 pins :-)
I will see the Swedish translation ;-) maybe Ulf have a good suggestion

**Comment by HThuren** [comment]
> @HThuren: I was hoping you could give me some ideas 😉 I'm away from computers for a week and not sure how to translate this. Will give it some thought and get back later in the week.Den 6 aug. 2023 19:21 skrev HThuren ***@***.***>: don't intend to make caos :-) From my point of view a joystik ara a stik you can move around - like you describe 'hat - but we also have the 2 pins :-) I will see the Swedish translation ;-) maybe Ulf have a good suggestion —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Sorry, but I think the right word are 'Joystik'
image

**Comment by mha1** [comment]
I'll buy it

**Comment by ulfhedlund** [comment]
SE
#define TR_HATSMODE "Hattläge"
#define TR_HATSOPT "Endast trimm","Endast knapp","Ändringsbar","Global"
#define TR_HATSMODE_TRIMS "Hattläge: Trimmar"
#define TR_HATSMODE_KEYS "Hattläge: Knappar"

It's best I can come up with, although not very good I think.

**Comment by HThuren** [comment]
I belive best translation are to understand 'hat buttom' as a joystick:

EN (**but not my decision**)
#define TR_HATSMODE "Joystick mode"
#define TR_HATSOPT "Trims only","Keys only","Switchable","Global"
#define TR_HATSMODE_TRIMS "Joystick mode: Trims"
#define TR_HATSMODE_KEYS "Joystick mode: Keys"

**DA**
#define TR_HATSMODE "Joystik indstilling"
#define TR_HATSOPT "Kun trim","Kun knap","Trim / Knap", "Global"
#define TR_HATSMODE_TRIMS "Joystik: Trim"
#define TR_HATSMODE_KEYS "Joystik: Knap"

**Comment by JimB40** [comment]
> I belive best translation are to understand 'hat buttom' as a joystick:

@pfeerick is right.
https://en.wikipedia.org/wiki/Joystick
Hat switch is name used for this input. 

Althought in PL example it translates to english equivalent of 'mushroom switch'. Sounds little funny.
I think we should go with 'Joystick' or 'Hat switch' whatever sounds more natural in particular languange.

**Comment by JimB40** [comment]
> PL
> 
> ```c
> #define TR_HATSMODE "Tryb grzybków"
> #define TR_HATSOPT "Tylko trymy", "Tylko przyciski", "Przełączane", "Globalne"
> #define TR_HATSMODE_TRIMS "Tryb grzybka: trymy"
> #define TR_HATSMODE_KEYS "Tryb grzybka: przyciski"
> ```
> 
> I don't really feel "hats" for that purpose in polish, changed it to "mushrooms" which feels more natural in polish for what it is. But I will revert if you want.

Small fix in PL as we change both hats mode not single so plural form.

```
#define TR_HATSMODE "Tryb grzybków"
#define TR_HATSOPT "Tylko trymy", "Tylko przyciski", "Przełączane", "Globalne"
#define TR_HATSMODE_TRIMS "Tryb grzybków: trymy"
#define TR_HATSMODE_KEYS "Tryb grzybków: przyciski"
```

**Comment by HThuren** [comment]
> > I belive best translation are to understand 'hat buttom' as a joystick:
> 
> @pfeerick is right. https://en.wikipedia.org/wiki/Joystick Hat switch is name used for this input.
> 
> Althought in PL example it translates to english equivalent of 'mushroom switch'. Sounds little funny. I think we should go with 'Joystick' or 'Hat switch' whatever sounds more natural in particular languange.

Good point and link to wiki are illustrative. Hat switch since the switch are on to of a joystick. Not easy. In this case we have the switch not on top of (gamer) joystick, but almost same functionality as a joystick. 
I cant't find a danish term that differ between joystick and switch on top of a joystick. :-)

**Comment by robustini** [comment]
IT (updated)

#define TR_HATSMODE "Modo joystick"
#define TR_HATSOPT "Solo trims","Solo keys","Commutabile","Globale"
#define TR_HATSMODE_TRIMS "Modo joystick: trims"
#define TR_HATSMODE_KEYS "Modo joystick: keys"

**Comment by ToshihiroMakuuchi** [comment]
JP

#define TR_HATSMODE "アナログスティック"
#define TR_HATSOPT "トリムのみ","キーのみ","スイッチ","すべて"
#define TR_HATSMODE_TRIMS "アナログスティック: トリム"
#define TR_HATSMODE_KEYS "アナログスティック: キー"

In Japan, we do not use the word "Hat".
On a gamepad controller, it is expressed as [analog stick].

**Comment by mha1** [comment]
@ParkerEde @TheIsotopes  Reminder for DE translations if you find some spare time

**Comment by ParkerEde** [comment]
Yes, I will do if I'm back from holidays.

**Comment by TheIsotopes** [comment]
DE

```
#define TR_HATSMODE                    "Joystick Modus"
#define TR_HATSOPT                     "Nur Trimmung","Nur Tasten","Umschaltbar","Global"
#define TR_HATSMODE_TRIMS              "Joystick Modus: Trimmung"
#define TR_HATSMODE_KEYS               "Joystick Modus: Tasten"
```

**Comment by HThuren** [comment]
Good team work !

**Comment by mha1** [comment]
True words, thank you very much to all translators. If you want to check if I transferred your contributions without errors please download Companion from the checks tab.

**Comment by Pat6874** [comment]
After consultation and harmonization with other languages I propose to modify the translation into French of:

#define TR_HATSMODE "Mode joystick"
#define TR_HATSOPT "Trims uniquement","Touches uniquement","Commutable","Global"
#define TR_HATSMODE_TRIMS "Mode joystick: trims"
#define TR_HATSMODE_KEYS "Mode joystick: touches"

Patrick

**Comment by mha1** [comment]
@elecpower Hi Neil, can you please do me the favor to unmess my modeledit/setup.ui mess I created in a rebase. Label and cb overwrite each other:

image

**Comment by pfeerick** [comment]
Can't push to this branch for some reason, but this seems to fix it (at least in QT Designer form view):

```diff
diff --git a/companion/src/modeledit/setup.ui b/companion/src/modeledit/setup.ui
index f828efdaa..de0498958 100644
--- a/companion/src/modeledit/setup.ui
+++ b/companion/src/modeledit/setup.ui
@@ -184,7 +184,7 @@
         </widget>
        </item>
        <item alignment="Qt::AlignRight">
-        <widget class="QLabel" name="label_spacer">
+        <widget class="QLabel" name="lblHatsMode">
          <property name="font">
           <font>
            <weight>50</weight>
@@ -192,7 +192,7 @@
           </font>
          </property>
          <property name="text">
-          <string/>
+          <string>Hats Mode</string>
          </property>
          <property name="alignment">
           <set>Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter</set>
@@ -675,13 +675,6 @@ If this is checked the throttle will be reversed.  Idle will be forward, trim wi
           <string>Throttle trim switch</string>
          </property>
         </widget>
-       </item>
-	   <item row="1" column="0">
-        <widget class="QLabel" name="lblHatsMode">
-         <property name="text">
-          <string>Hats Mode</string>
-         </property>
-        </widget>
        </item>
        <item row="2" column="2">
         <widget class="QCheckBox" name="extendedTrims">
@@ -774,4 +767,4 @@ If this is checked the throttle will be reversed.  Idle will be forward, trim wi
  </tabstops>
  <resources/>
  <connections/>
-</ui>
\ No newline at end of file
+</ui>

```

**Comment by mha1** [comment]
Thx, looks good!

image

**Comment by mha1** [comment]
Any idea why this craps out?
```
make[1]: *** [radio/src/CMakeFiles/firmware-size.dir/rule] Error 2
CMakeFiles/Makefile2:516: recipe for target 'radio/src/CMakeFiles/firmware-size.dir/rule' failed
make: *** [firmware-size] Error 2
Makefile:280: recipe for target 'firmware-size' failed
Error: Process completed with exit code 2.
```

**Comment by mha1** [comment]
check build works fine on NV14

**Comment by mha1** [comment]
@pfeerick are we good on this? please release me from rebasing and fixing the rebases over and over again

**Comment by pfeerick** [comment]
Should be. Don't rebase it again 🤪

**Comment by mha1** [comment]
what do mean? those frequent translation changes suck. even more if companion translations are touched

**Comment by pfeerick** [comment]
'cause merges aren't rebases...  🤪 and I'll hopefully be looking at this tomorrow

**Comment by JimB40** [comment]
Can't we use fall back to english text version?
Then translation can be updated afterwards.

**Comment by pfeerick** [comment]
This isn't what Michael is referring to. Changes to translations, particularly companion changes can cause clashes with existing PRs because either the prior or next line is altered, or the same line has been altered.

**Comment by Eldenroot** [comment]
Thats why there should be one complete PRs (lets say once a month)  which would cover all the language changes at once

**Comment by pfeerick** [comment]
You're welcome to organise that... this is an open project that anyone can contribute to ;) I think however you'll find that would create an even bigger mess. IMO it would be better as we're going into RC to check all the languages being maintained over thoroughly since at that point we're in feature freeze with only bugfixes happening. 

i.e. For the firmware, it could be a matter of diffing the current file with the prior release to see what's been changed, and focus on those. For Companion, QTLinguist manages the state of translation files (i.e. translated, not translated). 

But if anyone has a better idea, please run with it! :) Eventually, we should be able to use something like [Crowdin](https://crowdin.com/), but that won't be for a while.

**Comment by Eldenroot** [comment]
There is no need to organize that... better to use something like crowdit? Just a point for discussion :)

**Comment by mha1** [comment]
@pfeerick don't speak to a simple man in riddles. was that a subtle hint to merge rather than rebase?

**Comment by gagarinlg** [comment]
> @pfeerick don't speak to a simple man in riddles. was that a subtle hint to merge rather than rebase?

No, please rebase PRs, do not merge main into them

**Comment by gagarinlg** [comment]
> There is no need to organize that... better to use something like crowdit? Just a point for discussion :)

We have to redo the whole translation mechanism for the firmware before we can do this. With the current implementation it is not possible.

**Comment by pfeerick** [comment]
Regarding a question you had... 
```
LROT_NUMENTRY( EVT_VIRTUAL_PREV_PAGE, EVT_KEY_LONG(KEY_PAGEDN) )    // do colorLCD radios with only PAGEDN HW key exist?
```

yes, a lot of them only have page down, and not page up. e.g. Frsky X9, X7, Jumper T16, TLite, TPro. Radiomaster was the first to consistently do page down AND page up as seperate keys IIRC... hence why the long hold to trigger page up is needed.

**Comment by pfeerick** [comment]
Can you check the permissions for this branch/PR... I still can't push to it, and have three commits pending. I noticed Malte had issues with another PR recently so it could be something github changed.

**Comment by mha1** [comment]
I never changed any access rights before. All PR's were created with the same process.

I've added you as a collaborator. Hope this works.

**Comment by pfeerick** [comment]
Thanks, that did it... and well, that's annoying... something has clearly changed in how GitHub is treating PRs and permissions...  ... now gotta go see what they've been up to this time 🤦

image

Silly GitHub ... should have had that already  🤮

**Comment by mha1** [comment]
Thanks for cleaning up after me. I wonder about the white spaces at the of lines. Maybe I miss a setting in VSCode to remove them automatically on save.

**Comment by pfeerick** [comment]
There wasn't one earlier on but I think there is now (just go into the settings UI and search for whitespace... it'll show up in reference to the text editor). I used to use an extension for that before, but now it's usually whatever clang-format (on auto format using the repo config) wants it gets. One thing to be aware of is that git insists on a single blank line at the end of files... (a Linux convention IIRC) i.e. files should end with a newline. Else it will show up as an angry red line on GitHub in the diff view 🤣

**Comment by mha1** [comment]
woohoo

**Pull request merged**
