### PR TITLE
Lua font alignment - per discussion on Discord

### PR DESCRIPTION
**Pull request by jfrickmann**
https://discord.com/channels/839849772864503828/842693696629899274/894878085210574889

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@jfrickmann so we're ok this was never necessary in the first place? Nothing broken after that?

**Comment by jfrickmann** [comment]
I adjusted everything because my thinking at the time was that the corner of the INVERS box should be at (x, y), and therefore the text should also be moved. But in hindsight I can see that was stupid, and I did not do it for x either. So now the box is moved, and the text should be where it belongs. So hopefully, it should all be good now!

**Comment by pfeerick** [comment]
Are happy with this now @jfrickmann?

**Comment by jfrickmann** [comment]
> Are you happy with this now @jfrickmann?

Yes, I slipped in Git on my way out of the door this morning - therefore, the last change did not get in before now. Sorry! But It all looks OK to me now.

**Pull request merged**
