### PR TITLE
Add some translation strings + update helper

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
- four strings from model labels were hard-coded, now moved to translations
- translation helper was never updated post LVGL, so was looking for/trying to edit wrong files. Also removed some OS specific path coding, and flagged a required parameter as required.

### CODE REVIEW

**Comment by robustini** [comment]
@pfeerick if you already want to integrate the correct Italian in your PR:

#define TR_NO_PICTURE                  "No immagine"
#define TR_INVALID_MODEL               "Modello invalido"
#define TR_MOVE_UP                     "Muovi Su"
#define TR_MOVE_DOWN                   "Move Giù"

**Comment by Eldenroot** [comment]
@pfeerick - or leave my translations, I will create a new PR - there are few more to translate into Czech (I think that it was because of other new feat added).

**Comment by pfeerick** [comment]
@HThuren @ulfhedlund Did you want to give me your take on these also?
```
#define TR_NO_PICTURE               "No Picture"
#define TR_INVALID_MODEL            "Invalid Model"
#define TR_MOVE_UP                  "Move Up"
#define TR_MOVE_DOWN                "Move Down"
```

**Comment by Eldenroot** [comment]
I will create a new PR for the Czech translation after you merge this one.

**Comment by ulfhedlund** [comment]
For the Swedish translation I would suggest the following:#define TR_NO_PICTURE "Ingen bild"
#define TR_INVALID_MODEL "Ogiltig modell"
#define TR_MOVE_UP      "Flytta uppp"
#define TR_MOVE_DOWN "Flytta ner"Den 19 sep. 2022 03:24 skrev Peter Feerick ***@***.***>:
@HThuren @ulfhedlund Did you want to give me your take on these also?
#define TR_NO_PICTURE               "No Picture"
#define TR_INVALID_MODEL            "Invalid Model"
#define TR_MOVE_UP                  "Move Up"
#define TR_MOVE_DOWN                "Move Down"

**Comment by HThuren** [comment]
I suggest this translation:
#define TR_NO_PICTURE               "Ingen billede"
#define TR_INVALID_MODEL            "Ugyldig model"
#define TR_MOVE_UP                  "Flyt op"
#define TR_MOVE_DOWN                "Flyt ned"

**Pull request merged**
