### PR TITLE
Touch events to Standalone Lua scripts

### PR DESCRIPTION
**Pull request by jfrickmann**
As promised, here is an implementation of touch events to Standalone scripts, based on what I did for Lua widgets.

### CODE REVIEW

**Comment by jfrickmann** [comment]
Right now, the touch driver is broken, probably by PR #1000. Since that PR is labeled "unfinished", that is not surprising. But why does unfinished work get pulled into main?!?
Anyway, that makes it pretty hard for me to test if everything actually works here...
`slideX` and `slideY` are obviously wrong, they are accumulating instead of being reset for every event. They should reflect how far the finger has been sliding since the previous event.

**Comment by jfrickmann** [comment]
The build fails for NV14, apparently because `touchState` has been deleted or renamed here. It is probably also #1000. 
I am going to take a break and wait for y'all to clean up.

**Comment by pfeerick** [comment]
>  Since that PR is labeled "unfinished", that is not surprising.

Where exactly? It says untested on NV14, not unfinished. However, NV14 *is* working. 

It looks like your PR has tripped up the compiler and an `#include <touch.h>` is needed...

**Comment by gagarinlg** [comment]
The slide variables probably have the same problem as in simu. As I will be on the roas the whole day, I will take a look at the evening or tomorrow.

**Comment by pfeerick** [comment]
@gagarinlg `simu` does get affected by this, but I think is different to the `simu` issue we caught the other day... touch slide had an 'inertia' factor whereby you could slide/swipe and release, and it would keep scrolling ... e.g. a slow swipe down and release in the first model setup screen would scroll down a few say half the screen height, but a quick one could virtually scroll from top to bottom. That's why I'm wondering if `slideX`/`slideY` are what needs fixing. Look when you can (and I will also try to look this evening as well, but looking more likely Sunday afternoon), but the underlying compile issue should be gone now, allowing this PR to continue.

**Comment by jfrickmann** [comment]
> > Since that PR is labeled "unfinished", that is not surprising.
> 
> Where exactly? It says untested on NV14, not unfinished. However, NV14 _is_ working.
> 

https://github.com/EdgeTX/edgetx/commit/ced9df95102066f43f0ef53636433c4217ff6db1

**Comment by jfrickmann** [comment]
> Would that explain #1077?
I don’t know, that may be yet another issue. But please try out the EvenDemo widget and see what happens!

**Comment by jfrickmann** [comment]
> It looks like your PR has tripped up the compiler and an `#include <touch.h>` is needed... if you rebase now it should build - it did locally after this change.

That's right, I forgot about that. Probably because it it is not needed for Horus...

Now it builds, and the only problem is the accumulating `(slideX, slideY)`. I have attached a Standalone version of EventDemo that also shows the values of touchState, so you can see for yourself.

[EventDemo Standalone.zip](https://github.com/EdgeTX/edgetx/files/7570462/EventDemo.Standalone.zip)

**Comment by pfeerick** [comment]
Right, so it looks like the changes to main that were incorporated into this PR resolved the issue? The tail is being correctly drawn as I slide around the screen using EventDemo Standalone (thanks!), and the slideX/slideY values are not accumulating. 

Is there anything that _needs_ fixing before this can be merged for more fingers to break it? 😁  @jfrickmann

**Review by pfeerick — APPROVED** [review]

**Comment by jfrickmann** [comment]
Yes, I just rebased a branch of my own on main yesterday, and noticed that the tails were looking good again 🥇

**Comment by pfeerick** [comment]
Excellent, Robert will be happy with what is about to happen then. 😆

**Comment by JimB40** [comment]
All goodies in one place. Thx guys

**Pull request merged**
