### PR TITLE
chore(cpn): update branding

### PR DESCRIPTION
**Pull request by elecpower**
Summary of changes:
- update source image location for generating icons
- replace logo, icon and splash image files

@pfeerick can you please run the OSes icon generation script at the appropriate time, thanks

### CODE REVIEW

**Comment by JimB40** [comment]
Screenshot 2023-07-18 at 18 05 04
Screenshot 2023-07-18 at 18 05 13

This Logos have wrong typography. Until fixed and rebranding annouced no-go for this PR.

**Comment by elecpower** [comment]
> This Logos have wrong typography. Until fixed and rebranding annouced no-go for this PR.

Someone has already updated the logos on the official website so I'd say counts as 'announced'.

If our resident graphic artists would like to provide the typographically correct images for each use case then I can substitute.

**Comment by pfeerick** [comment]
The change was premature as not all the materials were updated and ready to go, so has been rolled back.

**Comment by elecpower** [comment]
Hi @mhotar to ensure consistency with your design, would it be possible for you to create a few official images for Companion?
Need an application icon (star logo), splash screen (Edgehog) and title for the About dialog (star logo plus Companion name).
Other than the icon the image sizes have some flexibility (see v1 images)

**Comment by mhotar** [comment]
Hello @elecpower ,here are my attepts. Hope it fits.
companion
EtxLogo9696

**Comment by mhotar** [comment]
companionTitle
companionEddie

**Comment by elecpower** [comment]
Hi @mhotar thank you they fit

**Comment by pfeerick** [comment]
Are you happy with the fonts now @JimB40 ? 🤪

**Pull request merged**
