### PR TITLE
Try fix X12S RTC coin cell sampling

### PR DESCRIPTION
**Pull request by rotorman**
Needs testing on X12S hardware!

### CODE REVIEW

**Comment by brainbubblersbest** [comment]
Proof of work

**Comment by brainbubblersbest** [comment]
Reading measured at coin cell=2,64V
Displayed Voltage in ETX=2,919

**Comment by rotorman** [comment]
@brainbubblersbest Would it be possible for you to measure the voltage at pin 41 of STM32F439BIT6 while the radio is powered on. You need pinhead test leads and this is tricky, so plz say no if you are not feeling up for it!

**Comment by brainbubblersbest** [comment]
The cell has 2,919V measured when the Radio is running.
Seems that i changed the cell already because i cant find it. 
So the 2,64V seems to be a bit to low.
Already wrote in the last Response in the PR and the issue
Should be that pin here

**Comment by brainbubblersbest** [comment]
It's not adc_vref_prec2 250?
(Line 328 in hal.h from opentx source code)

**Comment by rotorman** [comment]
According to hal.h X12S uses 3.0 V VREF+:
https://github.com/EdgeTX/edgetx/blob/4667b296989dc19c0d6915c031f401a6f28542d5/radio/src/targets/horus/hal.h#L280
Before changing the code, would need to know what voltage is really put on pin 41 of the chip?

**Comment by raphaelcoeffic** [comment]
@rotorman are we waiting for confirmation of VRef voltage before merging?

**Comment by rotorman** [comment]
The voltage ref value is another issue and could be fixed in a further PR, if necessary and proven by somebody with X12S who could measure the VREF+ pin. Thus, we could merge this PR, as it seems to first at least enable the RTC coin cell voltage sampling on X12S in the first place.

**Comment by brainbubblersbest** [comment]
Hello, im a bit busy right now. You can expect a measurement this evening. Do i need to Do that with a scope?

**Comment by rotorman** [comment]
No, a voltage meter is enough, as it should be a non-dynamic voltage level.

**Comment by brainbubblersbest** [comment]
Ok i measured the voltages.
On the cell it appears that at Boot up, when the nightly warning showes up. The cell voltage Drops down to 2,55 V after check the Boot up message and are in Main menu. The cell voltage rise up to 2.902V
I think it's when the rtc bridge is applied.
TO double Check that. I ordered a New varta 1220Cell and Do another Test. On saturday.

**Comment by pfeerick** [comment]
So how does this compare with the voltage the transmitter is showing? 2.902V on the meter, ? on the transmitter?

Also, it's the VREF (voltage reference) that's needed now (pin 41), to see if the scaling is correct, as if that is wrong (i.e. is actually 3.3v, as opposed to 3.0v as it's set in the code now) this would explain the inaccurate voltage reading.

**Comment by brainbubblersbest** [comment]
I record this with a two channel scope to Show you what i try to Tell. It's very dynamic at Boot up.

**Comment by pfeerick** [comment]
The VREF voltage reference pin? That should not change, otherwise it's absolutely useless as a _reference voltage_.

**Comment by pfeerick** [comment]
For completeness, there is some more info in this discord post and following conversation, https://discord.com/channels/839849772864503828/839895574244229152/862883697014341672, which is suggesting that the

**Pull request merged**
