### PR TITLE
Embedded default theme

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This aims at getting rid of the SD card requirement for the default theme by embedding the bitmaps into the firmware.
It can basically start with an empty SD card, which is obviously still required as a radio & models settings storage.

### CODE REVIEW

**Comment by JimB40** [comment]
What about changing default color scheme and default background to differentiate from OpenTX.
Looking at EdgeTX logo I can see you like bahama ocean-blue :)

**Comment by raphaelcoeffic** [comment]
@JimB40 something along the lines of dark blue with light/dark option would be a great start.

**Comment by JimB40** [comment]
@raphaelcoeffic may I join your discord channel?

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic may I join your discord channel?

Of course! Just head to https://edge-tx.org and hit the discord link at the end of the page.

**Comment by pfeerick** [comment]
New splash screen looks nice, and shutdown progress and final image are just perfect, and fit in well together. Now we just need the bit in-between to look a bit prettier! :stuck_out_tongue_winking_eye:

**Pull request merged**
