### PR TITLE
fix(color): Move mdls not in models.yml to `/Models/Unused`

### LINKED ISSUE #2373: Model Necromancy
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When upgrading from an earlier version, which has unreferenced models on the SD card, those models are imported again.
This may cause problems for people who delete many models by creating duplicates. 

### Expected Behavior

That is to be discussed.
Leave it as is or automatically delete all unreferenced model files and then models.yml

### Steps To Reproduce

Upgrade radio with unreferenced model files

### Version

Nightly (Please give date/commit below)

### Transmitter

Other (Please specify below)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dlktdr**
This PR will find either /MODELS/Models.yml or /RADIO/models.yml, if it exists all the models filename are read. Any of the files that are not listed  here will be moved to /MODELS/UNUSED. If any models are moved a message will pop-up "Unused models moved to.."

snapshot_05

The models.yml file is also moved into this folder.

### CODE REVIEW

**Comment by dlktdr** [comment]
Ok, I think this is what was requested.

Have have done some testing from OpenTX 2.3.15 bin format and it also only brings in the files that were listed in the models.txt file. Extras there others don't even get converted (same as before).

Would like to see some extra testing with some real world backups would be good. I apparently don't have a backup from /radio/models.yml days 😦 

If for some reason you end up with it in both locations it uses the models/models.yml file, the one in /radio/models.yml gets permanently deleted in this case.

**Comment by pfeerick** [comment]
IIRC, I this (`/radio/models.yml`) was very short-lived, as I pushed for it to be moved for the MODELS dir at the same time... so it may never have even made it out for the PR that did the `model.yml` implementation. So basically it should just be `RADIO/models.txt` and `MODELS/models.yml`, but I think there was a fallback to `RADIO/models.yml` *just in case*.

**Comment by dlktdr** [comment]
That would explain none of my backups having it. Should I remove this bit of code then? also from the other locations?

**Comment by pfeerick** [comment]
I'd have to look to check... which I will be shortly... but I would instinctively go with *cleanup for 2.9 since it's less work for now* :grin:

**Comment by pfeerick** [comment]
While I'm thinking of it, John did mention the warning doesn't give any idea how to dismiss it... he said to add "press return to continue" ... either that or maybe an OK or Close/Dismiss button that is focused?

If this works for you guys (The Translation Crew?), I'll keep tagging you with a request for translation when I spot new ones being added ;)
@ParkerEde DE
@ulfhedlund SE
@Eldenroot CZ
@robustini IT

```
#define TR_MODELS_MOVED "Unused models moved to"
```

**Comment by dlktdr** [comment]
> While I'm thinking of it, John did mention the warning doesn't give any idea how to dismiss it... he said to add "press return to continue" ... either that or maybe an OK or Close/Dismiss button that is focused?

Ok let me look, that is one of the pre-defined pop-up's available. I'll see if there are better ones in there., will try for a close button (less translations needed)

**Comment by robustini** [comment]
> #define TR_MODELS_MOVED "Unused models moved to"

IT
#define TR_MODELS_MOVED "Modello inutilizzato spostato in"

**Comment by Eldenroot** [comment]
`#define TR_MODELS_MOVED "Unused models moved to"`

CZE
#define TR_MODELS_MOVED "Nepoužívané modely přesunout do"

**Comment by ParkerEde** [comment]
`#define TR_MODELS_MOVED "Unused models moved to"`

DE
#define TR_MODELS_MOVED "Unbenutzte Modelle werden verschoben nach"

**Comment by pfeerick** [comment]
Ok, so when feeding it a backup from 2.4/2.5 days... it appears to have silently skipped converting over any bins not referenced in `RADIO/models.txt` => no necromancy in effect. 

Then a 2.7.0 config with a bunch of duplicated unreferenced models => got the popup and unreferenced files were moved=> no necromancy in effect. 

An abbreviated 2.7.0 config however with no duplicated models appears to trigger an "SD card error" popup (on radio)? Or is it too late at night for me to doing this testing now? 😆 

[random3.zip](https://github.com/EdgeTX/edgetx/files/9673600/random3.zip)

This is the snippet of the `simu` log (as simu behaved exactly the same) ... while the SD card error is onscreen so second last line is looking suspicious...
```
0.01s: storageReadAll
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/RADIO/radio.yml) = OK
0.01s: YAML radio settings reader
0.01s: f_open(/home/pfeerick/repos/edgetx/build-TX16S/native/RADIO/radio.yml, 1) = 0x7fdf0c043840 (FIL 0x7fdf24bfe840)
0.01s: f_close(0x7fdf0c043840) (FIL:0x7fdf24bfe840)
0.01s: f_opendir(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS) = OK
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/model2.yml) = OK
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/model1.yml) = OK
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/models.yml) = OK
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/model3.yml) = OK
0.01s: f_closedir(0x7fdf24bfe8b0)
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/models.yml) = OK
0.01s:  not found
0.01s: f_stat(/home/pfeerick/repos/edgetx/build-TX16S/native/RADIO/models.yml) = error 2 (No such file or directory)
0.01s: f_open(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/models.yml, 1) = 0x7fdf0c043840 (FIL 0x55bd79f651a0)
0.01s: FOUND modelslist.yml in /models, Scanning it
0.01s: f_close(0x7fdf0c043840) (FIL:0x55bd79f651a0)
0.01s: f_open(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/models.yml, 1) = 0x7fdf0c043840 (FIL 0x7fdf24bfc950)
0.01s:  not found
0.01s: f_open(/home/pfeerick/repos/edgetx/build-TX16S/native/MODELS/UNUSED/models.yml) = error 2 (No such file or directory) (FIL 0x7fdf24bfcb90)
0.01s: f_close(0x7fdf0c043840) (FIL:0x7fdf24bfc950)
```

**Comment by dlktdr** [comment]
Just woke up here, so might be too early 😉 but I will check this out.

**Comment by Eldenroot** [comment]
> Edit: Yes missed this case. I quit.. this one seems so obvious, how did I miss it. 🙃

We are not robots :)

**Comment by pfeerick** [comment]
> We are not robots :)

Oi, I resemble that remark! 🤣 

> Edit: Yes missed this case. I quit(not really).. this one seems so obvious, how did I miss it. 🙃

Your resignation is not accepted - else then I can't complain about buggy code (ok, that's an outright lie). I bet you it's less obvious than you thought... even a radio backup that I thought would be "clean" didn't trigger it... I had to deliberately make a test case that was "clean".

**Review by pfeerick — APPROVED** [review]
LGTM... it has behaved with my test case of good setup, bad setup and conversion did well with an 2.5 setup, where there would have been a major "rise of the undead" going on! 😆 I'll merge this before next nightly, will just give ulfhedlund a little more time to spot and give a translation.

**Comment by gagarinlg** [comment]
This would probably a good point in time for RC2, to show people we care.

**Comment by pfeerick** [comment]
Yup, there were enough fixes already to warrant RC2, this being a major QoL one ;)

**Comment by jmxp69** [comment]
For the unreferenced fix in RC2, is the recommended procedure to allow the radio to handle conversion from all pre-RC2 firmware? i.e. Don't try to introduce or convert with Companion, just load firmware on radio and let radio do the work?

Good work EdgeTX team! Thanks for jumping on this one.

**Comment by gagarinlg** [comment]
> For the unreferenced fix in RC2, is the recommended procedure to allow the radio to handle conversion from all pre-RC2 firmware? i.e. Don't try to introduce or convert with Companion, just load firmware on radio and let radio do the work?

Yes, that is the recommended way. Companion should also do the right thing, but the radio part is the most tested variant. 

> 
> Good work EdgeTX team! Thanks for jumping on this one

👍

**Comment by pfeerick** [comment]
> For the unreferenced fix in RC2

Now, why didn't you tell me I can't spell model properly... as it was referenced... badly (but still, how would it resurrect modules?) 😆 

image

**Comment by jmxp69** [comment]
I knew what you meant...

**Pull request merged**
