### PR TITLE
Companion-build-updates

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
- remove need for a seperate companion build script for 32bit and 64bit windows builds
- remove release script and rename nightly as this is the one actually being used. 
- teach companion about version tag

This is all without compilation as I was too lazy to do this locally, so it will be interesting to see what the github biuld system makes of this :)

### CODE REVIEW

**Comment by pfeerick** [comment]
Oi, no laughing at me, peanut gallery... I just did it blind and went to bed, hoping the build system wouldn't spit the dummy :grin: Imagine my utter shock when I looked and it actually built 😆 . It seems like it is now working. The commit added a missing space between the suffix and build codename strings. will just need to verify the 32bit toolchain works properly also and this should be right to go. 

image

**Comment by pfeerick** [comment]
32bit build correctly branched off and used 32bit `SDL_LIBRARY_PATH` ... https://github.com/EdgeTX/edgetx/actions/runs/2243391953

**Comment by elecpower** [comment]
Copyright year needs updating to 2022. This should be automated shouldn't it?

**Comment by pfeerick** [comment]
Yeah, I noticed what when doing the screenshots so bumped the year. When I think of it (c'mon... don't have to fix it for 7 months now :grin:), will probably add it (year) somewhere central so only needs to be changed in one place...

**Comment by rotorman** [comment]
Pointing fingers here, ah?
Heheh. On the serious side, why firmware screenshot shows v2.7.1, the others v2.8.0?

**Comment by pfeerick** [comment]
That one just had a different version number tag assigned.

**Pull request merged**
