### PR TITLE
fix(b&w): missing timer labels

### LINKED ISSUE #3170: EdgeTx 2.8 Radiomaster Zorro issue Timer do not work or can be set correct
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Updated Radiomaster Zorro from 2.7 to 2.8 German firmware version 

I use a switch B to start my electric motor (counting down time for example 03:00 and in % according switch position. The same switch B is also used to start Flu i.e.  counting up actual model flight time with trigger first Motor start) 

When importing a model (with timers set: Motor start TH% (countdown 03:00) on switch B and starting Flu Flight time) everything works fine.

-> However modifing these two settings or when creating a new model 
Timer Flu starts immediately no matter if swithc is still on 0 - Position.    Label THt or Gst seems incorrect
Timer Mot (countdown motortime depending switch position % )          LabeL TH% or Gs% seems incorrect.
Tried every possible setting - none worked as in 2.7

Went back to 2.7 on my Zorro where everything works fine again . 
My 2 Collegues have exactly same problem with RM Zorro and 2.8   

Remark:  this issue was not found on Radiomaster TX16S and Version 2.8 

### Expected Behavior

Timers should work correctly and in the same way as with software 2.7 and is hope fully found at other Zorro users with 2.8 
Will try 2.9 when available

### Steps To Reproduce

1 use German 2.8 firmware on Radiomaster Zorro
2 Setup Timers directly on the Radio
3 set timer Mot using switch B to start electric Motor (is use CH 4) and start count down time from 03:00 using switch position in % 
4 set timer Flu to start counting up flight time triggered with switch B (when first time Motor is initiated)

### Version

2.8.0

### Transmitter

Radiomaster Zorro

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #3170

### CODE REVIEW

**Comment by pfeerick** [comment]
Any comments from translaters?

- [ ] @ParkerEde / @TheIsotopes DE
- [ ] @Eldenroot CZ
- [ ] @ulfhedlund SE
- [ ] @robustini IT
- [ ] @ajjjjjjjj PL

The limitation here is there is that there is only space for four letters for "Start" (so EN dropped the A). It can't be any longer as the third column start needs the be the same as the one further down. 

image

**Comment by ajjjjjjjj** [comment]
Nothing to change from PL perspective, it's good.

**Comment by robustini** [comment]
Perfect.

**Comment by ulfhedlund** [comment]
SE: Strt (same as EN)Den 12 feb. 2023 02:37 skrev Peter Feerick ***@***.***>:
Any comments from translators?
 @ParkerEde / @TheIsotopes DE @Eldenroot CZ @ulfhedlund SE @robustini IT @ajjjjjjjj PL
The limitation here is there is that there is only space for four letters for "Start" (so EN dropped the A). It can't be any longer as the third column start needs the be the same as the one further down.

**Comment by Eldenroot** [comment]
CZ: leave it as it is, so it is fine :)

**Pull request merged**
