### PR TITLE
Use theme color for poweroff

### PR DESCRIPTION
**Pull request by pfeerick**
@JimB40 Are `COLOR_THEME_SECONDARY1` for the background color, and `COLOR_THEME_PRIMARY1`  for the animation the right ones to use here? 

One point to consider is that for the default theme, this makes the animation black.

### CODE REVIEW

**Comment by JimB40** [comment]
Frankly speaking I'd make all core OS screens UI like booting, USB connected, shutting down in B&W :)
Eventually I'd use gfx from #638 once implemented
Anyway trying to make my first PR to edgetx-sdcard, there is readme.txt with detailed description

**Comment by pfeerick** [comment]
So black background, white animation logo?

**Comment by JimB40** [comment]
Exactly. Core OS scrrens should stay color agnostic. We may introduce some colors later but slowly :) 
Would use EdgeTX blue but then some 'blue-screen' buzz will start :)

**Comment by pfeerick** [comment]
Done. Black background, white animation and power icon. Looks good on TX16S hardware, will double check on NV14 with gh actions build as I'm too lazy to self-build that one atm.

**Comment by NemesisXB** [comment]
> Frankly speaking I'd make all core OS screens UI like booting, USB connected, shutting down in B&W :) Eventually I'd use gfx from #638 once implemented Anyway trying to make my first PR to edgetx-sdcard, there is readme.txt with detailed description

I would disagree with the black and white. If I set a theme color it is because I did not like the original. I should be able to change it. Just my 2c.

**Comment by ChasedMonkey** [comment]
I also think the color should come from the theme.yml

**Comment by pfeerick** [comment]
Ok, so I think what I will do is I will side with @JimB40 for the purposes of 2.5.0, which will unfortunately close this PR... but I will then open a new issue linking back to this, so the discussion can continue. Because we need to come to a group consensus, not just what any one of us thinks this should look like :) As for the moment, this is the same as the menu icons now, and is probably better contrast for the few seconds you see the shutdown animation.

**Comment by NemesisXB** [comment]
> Ok, so I think what I will do is I will side with @JimB40 for the purposes of 2.5.0, which will unfortunately close this PR... but I will then open a new issue linking back to this, so the discussion can continue. Because we need to come to a group consensus, not just what any one of us thinks this should look like :) As for the moment, this is the same as the menu icons now, and is probably better contrast for the few seconds you see the shutdown animation.

Black and White on my nice Color screen. how ironic. ;-)

I understand. And agree it should be a group consensus.

**Pull request merged**
