### PR TITLE
feat: enable S.PORT telemetry by default for SBUS and PPM modules

### LINKED ISSUE #3877: No sbus in 2.8.x but no telemetry in 2.9.x
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Sbus output for external module(rfd900) not working in 2.8.x 

When flashing 2.9 RC1 Sbus output is working but all telemetry data is lost and no telemetry communication.

### Expected Behavior

Should be avle to get telemetry in 2.9 like it was working in previous stable versions

### Steps To Reproduce

Flash 2.9 RC1, telemetry data fed to Yappu telemetry script is not getting received as it was in previous stable versions

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Fixes #3877 

Summary of changes:
- Enable S.PORT telemetry by default for SBUS and PPM modules.

### CODE REVIEW

**Comment by rotorman** [comment]
Tested with [RadioMaster TX16S mkII](https://www.radiomasterrc.com/products/tx16s-mark-ii-radio-controller) running [Yaapu Lua Telemetry widget](https://github.com/yaapu/FrskyTelemetryScript), [MavlinkToPassthrough](https://github.com/zs6buj/mav2pt), [Dragonlink](http://www.fpvpro.com/dragon-link-v3-advanced-complete-system) and [flight controller](https://holybro.com/products/durandal) running [ArduPlane](https://ardupilot.org/plane/) and talking native [MAVLink](https://mavlink.io/en/).

Result - works.

**Comment by rotorman** [comment]
Tested the S.BUS connectivity as well - also functions as it should - I see channel values in Mission Planner, connected at FC side, whereas DragonLink TX was connected via S.BUS.

**Comment by pfeerick** [comment]
Is something also needed for 2.10?

**Comment by pfeerick** [comment]
Perfect... that one is up soon :)

**Pull request merged**
