### PR TITLE
feat(color): Improved navigation with SYS and MDL keys

### LINKED ISSUE #169: MDL/SYS keys' bindings
I think we may consider implementing this idea in 2.4. So we'll have initial feedback after release.
If OS wide implementation would affect code too much I'd go with MainView as it is in OpenTX now.  

event -> tab
------------
MDL short -> MODEL SETUP
MDL long -> MODELS (Select Model)
SYS short -> TOOLS
SYS long -> RADIO SETUP (since no APPS yet)

### PR DESCRIPTION
**Pull request by philmoz**
Allow SYS and MDL key navigation from within radio and model setup pages.

In the Radio Setup pages:
- MDL navigates to the Model Setup page
- Long press MDL navigates to Manage Models page

In the Model Setup pages:
- SYS navigates to the Radio Setup (TOOLS) page
- Long press SYS navigates to the Radio Setup (SETUP) page
- MDL navigates to the Channel Monitor (existing function)
- Long press MDL navigates to the Manage Models page

In the Channels Monitor page:
- MDL navigates to the Model Setup page
- Long press MDL navigates to the Manage Models page
- SYS navigates to the Radio Setup (TOOLS) page
- Long press SYS navigates to the Radio Setup (SETUP) page

In the Manage Model page:
- MDL navigates to the Model Setup page
- SYS navigates to the Radio Setup (TOOLS) page
- Long press SYS navigates to the Radio Setup (SETUP) page

This has been on my todo list for a  while - it always annoyed me that I had to keep returning to the main view.

Resolves #169

### CODE REVIEW

**Comment by JimB40** [comment]
Wil solve #169

**Comment by raphaelcoeffic** [comment]
> it always annoyed me that I had to keep returning to the main view.

Yeah, me too!

**Comment by JimB40** [comment]
> Yeah, me too!

Hehe there were quite a few annoyed but it's @philmoz who finally made PR.

**Review by pfeerick — APPROVED** [review]
It might be worth considering extending this to the Screen Settings and Statistics screens, but this is a much-appreciated improvement to navigation. To completely resolve #169 TELE short would take you to Screen Settings, and TELE long would take you to the screen settings.

**Comment by philmoz** [comment]
> To completely resolve #169 TELE short would take you to Screen Settings, and TELE long would take you to the screen settings.

I got lost in the 169 discussion and couldn't figure out the final decision(s).

Not sure, in your description above, what the difference between TELE short and long is - 'Screen Settings' VS 'screen settings'?

**Comment by pfeerick** [comment]
Sorry, was a typo... 

TELE short -> Channel monitor
TELE long -> Screen Settings

**Comment by arthurson** [comment]
just tried that, finally we don't need come back to homepage all the time, thx

**Comment by philmoz** [comment]
> TELE short -> Channel monitor
> TELE long -> Screen Settings

I understand that Channel Monitor might be used more often; but 'TELE short -> Screen Settings" has been the setting for a while. 

Do we really want to change it?

**Comment by pfeerick** [comment]
It's perfectly fine if it's the other way. Keep in mind that "TELE" never used to have a long press action, nor did MDL or SYS until recently. And these could all change in the future, and become user-configurable.

**Pull request merged**
