### PR TITLE
fix(radio) - Include internal module type in backup data for EM so radio re-connects to receiver.

### LINKED ISSUE #3599: Recovery from a hard fault (emergency mode) not working
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Bug or feature? 

From what I understand a CPU hard fault (e.g. division by zero, misaligned memory access, etc.) causes the CPU to reset. At restart the RTC backup registers holding expected shutdown indicators will be used to decide a hard fault reset occurred (= unexpected shutdown) and the well known Emergency Mode screen shows up. Reading @3djc's issue #3579 I understand "color radios have a dedicated area of memory so that in the event of emergency mode, data needed to safely keep your model flying despite the reset would be safe and not depending on sdcard". All in all I'd expect to have at least the RF link and mixers up and running after a hard fault reset (if it's not a permanent one) to maintain control of the model.

Here's my experiment.  I injected a hard fault using gcc's `__builtin_trap()` in a part of the GUI to allow me event based triggering of a hard fault by clicking a selection field I misuse for this experiment. The manually triggered hard fault actually happens. The radio shows the Emergency screen and the RF link goes down with the rx in failsfe. But the radio link - MPM in my experiment - doesn't come back up. As there is no permanent hard fault I'd expect at least a boot into a (degraded) core system, maybe without the GUI,  coming back to life.

### Expected Behavior

In case of a spurious hard fault at least a degraded core system should be operative.

### Steps To Reproduce

- add line ` __builtin_trap();` after line `resetMultiProtocolsOptions(moduleIdx);` in https://github.com/EdgeTX/edgetx/blob/3d6bc638a68958aa788debee46257f921f4a2941/radio/src/gui/colorlcd/mpm_settings.cpp#L167-L174
- build firmware and flash
- select internal MPM, choose e.g. Mode MULTI HoTT
- make sure RF link and receiver are working
- select the RF Protocol field and select the same value again
- observe Emergency Mode but RF link not coming back
- turn off radio
- turn on radio
- observe RF link being back on

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

latest nightly

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3599

### CODE REVIEW

**Comment by BompaBert** [comment]
Is this fix also applied in version 2.10.0-rc3?  - Horus X10 Express.  Just experienced a 'recovery mode' situation where control to the airplane was lost.

**Comment by 3djc** [comment]
yes it is included in 2.10-x

**Comment by BompaBert** [comment]
Oops. Any root cause analysis available like a log or anything I could look at cos this is scary. In this case though no damage, the plane was very light and floated down in failsafe mode however, I also fly jets...

**Comment by pfeerick** [comment]
And also latest 2.8.x and 2.9.x IIRC. Unfortunately no longs or anything...
This isn't a computer or phone level of hardware... Just a "simple"
microcontroller asked to do a *lot* of things. If the radio EM'd and didn't
reconnect to the RX when using internal RF, that is not good though. Keep
in mind only primary controls will be active - no Lua/Widgets, and possibly
LS/SF will not be active - although that should not effect whether the RF
link is re-established or not.

**Comment by BompaBert** [comment]
Yea, I had no control over the plane at all. It showed failsafe behavior when the radio went in EM - motor cutoff etc, stab auto level engaged etc...

**Comment by mha1** [comment]
It can take up to a few seconds because the CPU resets. Hence the radio firmware including the RF link reboots. Despite taking some shortcuts here and there (eg no pre-start checks, no GUI) it'll take some time until the RF link is re-established.

**Comment by BompaBert** [comment]
In my case, the Horus X10 needed a power off/on to get rid of the recovery mode screen and to regain control over the airplane.

**Comment by mha1** [comment]
EM is not a silver bullet. If the CPU hard fault persists nothing can be done. 

It you can do debug builds you can test if the general EM process to boot into a limp home mode after a hard fault works. Follow this: https://github.com/EdgeTX/edgetx/issues/3599#issuecomment-1548892426

**Comment by pfeerick** [comment]
> In my case, the Horus X10 needed a power off/on to get rid of the
recovery mode screen

That part is expected

>  needed a power off/on to regain control over the airplane.

That is what we are trying to prevent, but it is not guaranteed
unfortunately. How long of a delay between you realising it was in EM and
power cycling? As it will take a few seconds for it to reboot and for the
RF link to re-establish (if it is going to). And are any lua scripts,
logical switches, special functions, etc, required in order for you to have
control?

**Comment by BompaBert** [comment]
Control was lost when the plane was about 70 yards away from me. First time I saw that the radio was in recovery mode was when I got back to the pits after recovering the plane - maybe 5 minutes or so. I do use logical and functions switches managing motor and stabilization see attached .yml file.
[MXS2.zip](https://github.com/EdgeTX/edgetx/files/15138252/MXS2.zip)
@mha1 , love to help out but am not familiar with debug builds - no clue how to run the suggested test.

**Comment by BompaBert** [comment]
If this might help. Radio went into recovery mode again today. This time it happened when I was scrolling to my models list to select another model to fly with. Power off/on got me out and I flew with no issues the rest of the time. I do not believe the EM is related to the SD card as after the first EM, the card was replaced (8G SanDisk Industrial MLC MicroSD SDHC UHS-I Class 10).
I can go back to version 2.9 and see ( I had no EM's then)- advise here is welcome. Last I want to do is go back to OTX :-(

**Comment by mha1** [comment]
Please raise an issue on this.

**Comment by 3djc** [comment]
For reference, I just tested EM on a TX16S with 2.10RC3 and a ELRS link. Upon triggering EM, i regain control of the receiver within 3 seconds, so if an issue exist, it is more radio specific than systemic

**Comment by mha1** [comment]
Yes, I did it a while ago with MPM/HoTT and ELRS. Both regained control within a few seconds. It just takes quite a while for the modules to boot.

And as I said EM is not a silver bullet but a best effort attempting to regain control. If you can regain control depends on the type of fault that caused the EM.

**Comment by BompaBert** [comment]
FYI, a few days ago issue #4940 was opened. Looks very similar to this one but for a TX16.

**Comment by 3djc** [comment]
Absolutely not. This is not about what can create an EM (albeit we are working hard to try to reduce those occurrences), but what happens when it happens

**Comment by pfeerick** [comment]
> FYI, a few days ago issue #4940 was opened. Looks very similar to this one but for a TX16.

The only similarity is that a EM occurred. Unless you are poking around in the SD card files, and looking at images while in flight, that is where the resemblance ends. :zany_face: Also, it seems like that issue was resolved for the user in 2.10.0-rc3 (had been running 2.9.4 when it occurred), whereas you are seeing an issue **on** 2.10.0-rc3. For your particular situation, what we really need to know is whether the RF link is re-established on EM, to verify it is working consistently across all targets, or if some other factor could have been responsible for not regaining controls.

**Comment by BompaBert** [comment]
Just to be clear. I had 2 different situations when non recoverable EM occurred. Once during flight and once by trying to select a model after scrolling through them. I opened the issue on the second occurrence. Sent from my iPhoneOn May 2, 2024, at 5:59 PM, Peter Feerick ***@***.***> wrote:﻿

FYI, a few days ago issue #4940 was opened. Looks very similar to this one but for a TX16.

The only similarity is that a EM occurred. Unless you are poking around in the SD card files, and looking at images while in flight, that is where the resemblance ends. 🤪 Also, it seems like that issue was resolved for the user in 2.10.0-rc3 (had been running 2.9.4 when it occurred), whereas you are seeing an issue on 2.10.0-rc3. For your particular situation, what we really need to know is whether the RF link is re-established on EM, to verify it is working consistently across all targets, or if some other factor could have been responsible for not regaining controls.

**Comment by BompaBert** [comment]
FYI,  moved back to 2.9.4 - what a pain in the butt - partly caused by the changes in the radio profile between both versions - see attachment. Needed to review and adjust each of my models as the pots and sliders disappeared from each file - all special instructions 'play track or value' duration parameters went to 1sec as well.
I'll keep you informed on any EM occurrences.
[ETX prof diff.zip](https://github.com/EdgeTX/edgetx/files/15204290/ETX.prof.diff.zip)

**Comment by 3djc** [comment]
You should never go to previous major version with the new files. This is why it is recommended to save your sd before upgrading

**Comment by BompaBert** [comment]
10/4. Just, I had several major changes in between... All good now. Will keep you guys posted.

**Comment by BompaBert** [comment]
FYI. Two more EM's past week on the same day. Version 2.10-2. One in flight - recovery successful. The other EM occurred while changing from model A to model B. This happened twice and so far only when using the 9 icons per page. No EM using the 4 models per page. Also after pwr off/on, model A is still active.

**Pull request merged**
