### PR TITLE
Improve Chinese CN/TW

### PR DESCRIPTION
**Pull request by zyren**
1. Fix the error that XL font cannot be displayed on CN/TW firmware.
2. Main menu translation.
3. Improve translation.

### CODE REVIEW

**Comment by richardclli** [comment]
The added translations is valuable for hardcoded text is valuable.  However, some questions need to be answered in which the problem exposed some problems in the underlying layer:

1.  Why Chinese fonts with size 31 can display properly while size 32 cannot, I traced and figured the png is generated properly, something in the rendering part?
2. Some text drawing API have problems in displaying correct text, need to dig out why the text indexing logic works in some APIs and not working in some others.  The typical example is the date display which use a 'month' Chinese character and swapped to a '-' for quick fix.

**Comment by richardclli** [comment]
The fix seems too complicated, there is a way to handle the problem easier.  Will work another PL based on the findings from @zyren

**Comment by richardclli** [comment]
@zyren I have fixed underlying mechanism in this PL

https://github.com/EdgeTX/edgetx/pull/1257

Please close this PL and create another PL for change of translations only.  Thanks.

**Comment by zyren** [comment]
Close this submission, the key index error, and display error have been solved more perfectly in #1257, thank you @richardclli for your help, praise the master, respect!

**Pull request closed without merging**
