### PR TITLE
Move YaML models list to /MODELS

### LINKED ISSUE #1073: Move models.txt from \radio\ to \models\
If models.txt or models.yml can be moved to the models directory, it would be easier for people to move models from one tx to another by copying just the models directory. Given there is no radio specific data in models.txt(yml) it should be easy to implement this change.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #1073

### CODE REVIEW

**Comment by pfeerick** [comment]
This worked fine on TX16S. If running a nightly, the subsequently generated `\MODELS\models.yml` is... interesting... as it lists all the correct model files. but `.bin` in instead of `.yml` 😆. Although easily fixed by moving the file manually from RADIO either before or afterwards. It was correctly generated if starting from scratch (i.e. 2.5 => 2.6 migration). 

I'm now confused though... Just noticed my TX12 doesn't have a `models.yml`? Still using EEPROM?

**Comment by raphaelcoeffic** [comment]
> I'm now confused though... Just noticed my TX12 doesn't have a models.yml? Still using EEPROM?

The models list screen is done by scanning the directory. It uses slot # as the EEPROM did. The filename equals the slot #.

**Comment by raphaelcoeffic** [comment]
> This worked fine on TX16S. If running a nightly, the subsequently generated `\MODELS\models.yml` is... interesting... as it lists all the correct model files. but .bin in instead of `.yml`

Wait a sec: this is not related to the file being moved, right? At least the filenames should be patched on conversion. It does not? At least it did for me while testing #1127

**Comment by pfeerick** [comment]
Running a working nightly build, simply booting with this PR without moving the file and it is rather entertaining results...

image

Could select any of the models (so it knew how many existed), and would let me load them. And it stayed that way until I created a new model, and then this was generated! 

```yml
- Models
  - filename: model1.bin
    name: 
  - filename: model2.bin
    name: 
  - filename: model3.bin
    name: 
  - filename: model4.bin
    name: 
  - filename: model5.bin
    name: 
  - filename: model6.yml
    name: MODEL06
```

As I said before, PSA for nightly users, but fine for normal upgrade path. 😆

**Comment by raphaelcoeffic** [comment]
> Running a working nightly build, simply booting with this PR without moving the file and it is rather entertaining results...

Should we try to recreate `models.yml` if it cannot be found?

**Review by pfeerick — APPROVED** [review]
Right, this works great now... Either creates `MODELS\models.yml` during conversion (i.e. release build user migration), or moves from `RADIO\models.yml` to `MODELS\models.yml` (nightly build user migration).

**Pull request merged**
