### PR TITLE
Companion enhancements to curves tab

### LINKED ISSUE #1800: Ideas for tweaks to Curves tab in Companion
With the new curves screen in Companion (which is great, btw!) it is now somewhat less intuitive to know how to add your first curve... would it be possible to do something like the following to give that initial prompt on what to do? i.e. The text would be overwritten by that image, so would not be visible once that first curve was added. Another alternative could be a "+" button when the curve not present, although I think that would look more cluttered. 

image

A second thought that was raised in relation to this, was would it be possible to also be able to right click on the curve _itself_ to get the context menu, not just the sidebar?

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #1800

Summary of changes:
- add context menu to curve image
- add note to advise how the add a new curve

### CODE REVIEW

**Comment by Thermikflieger** [comment]
There is a problem with the simulator. If you press the MDL key after starting the simulator, "MPM: Scanning protocols" starts. After that the simulator is frozen, you can only close the simulator.
I used the RM TX16S.

**Comment by elecpower** [comment]
@Thermikflieger seem you posted the comment to the wrong place. Anyway this issue is known #1793 and PR #1794 has been created to fix

**Review by pfeerick — APPROVED** [review]
Absolutely perfect... thank you! :) 😍

**Comment by elecpower** [comment]
We aim to please

**Pull request merged**
