### PR TITLE
fix(el18): switch ADC channel and direction

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
B & D switches are where they should be on EL18 (and also NV14), with all switches going the right way now.

**Comment by raphaelcoeffic** [comment]
> This PR causes SWB & SWD to be swapped on the EL18 I received today.

I think we really need to clarify what is the "normal" way...

> If I revert this PR then the two switches behave correctly.

This PR has 2 parts:
- exchanging SWB & SWD,
- and correcting `ADC_DIRECTION` (`TX_VOLTAGE` and `TX_VBAT` must be placed *before* the analog switches).

So once we clarified what is the "production" switch types & order, we'd need to recheck.

**Comment by philmoz** [comment]
With this PR, on my EL18 then the physical switch labelled SWB controls the SD switch in the firmware (Hardware, Inputs page). And physical switch SWD controls SB in the radio.

SB is on the front of the radio top left, SD is front bottom right.

If I revert the ADC_GPIO_PIN_SWx and ADC_CHANNEL_SWx changes then SB and SD work as labelled.

Directions are all ok - I did not revert the ADC_DIRECTION change.

**Comment by raphaelcoeffic** [comment]
> revert the `ADC_GPIO_PIN_SWx` and `ADC_CHANNEL_SWx` changes then SB and SD work as labelled.

And the default switch types are OK as well? @pfeerick we really need some feedback from FlySky....

**Comment by philmoz** [comment]
The defaults in 2.10 are wrong for my EL18 if starting from scratch (new SD card).

- S1 & S2 are set to None, instead of POT
- SC is set to Toggle, not 3POS
- SE is set to Toggle, not 2POS

Companion is the same with the additional issue that SC cannot be changed to 3POS. It can be changed to 3POS in the firmware; but not in companion (even if loading radio settings from the actual radio).

**Comment by philmoz** [comment]
Also the 2.10 firmware build on my EL18 lists T5 & T6 as trims.
Shows up in flight modes switch/source selection and the hardware debug keys page.

**Comment by raphaelcoeffic** [comment]
@philmoz we need to finish / integrate #3783, as this introduces the necessary bits to differentiate `EL18` from `NV14` at build time, and thus implement the different default values and possibly the different switches (SWB vs SWD). I believe the current state in `main` serves the NV14 correctly (my EL18 has the same switch config as the NV14).

**Comment by raphaelcoeffic** [comment]
> Also the 2.10 firmware build on my EL18 lists T5 & T6 as trims. Shows up in flight modes switch/source selection and the hardware debug keys page.

This probably need to be addressed separately, as this is no different from the NV14.

**Comment by philmoz** [comment]
> @philmoz we need to finish / integrate #3783, as this introduces the necessary bits to differentiate `EL18` from `NV14` at build time, and thus implement the different default values and possibly the different switches (SWB vs SWD). I believe the current state in `main` serves the NV14 correctly (my EL18 has the same switch config as the NV14).

Does that mean there are different EL18 switch configurations in production radios?
That will make things messy I would think.

**Comment by raphaelcoeffic** [comment]
> Does that mean there are different EL18 switch configurations in production radios?

So it seems. Mine is a pre-prod, so there is that.

**Comment by pfeerick** [comment]
Back at #2675, the EL18 was changed from the switch configuration of the radios shipped to us from

SWC toggle => 3 pos
SWE is toggle => 2 pos

and we weren't informed of any other changes. 

This PR is correct for the NV14 and 2x EL18 that I have - one an early development sample, the other was supposed to be a production line sample (which Raphael should have one of as well), but then they went and changed those two switches. So the question then is - are ours wrong, or is yours? This isn't the first time that I've received a radio with the switches upside down, so we really need input from both Flysky AND more users. 

https://youtu.be/N_XgqNEUxTA

**Comment by philmoz** [comment]
The manual I downloaded from the FlySky web site shows SC and SE as 2POS toggle switches; but it is dated 15th Nov 2022.

**Comment by raphaelcoeffic** [comment]
> my EL18 lists T5 & T6 as trims. Shows up in flight modes switch/source selection and the hardware debug keys page.

Created #3860 to fix this.

**Comment by pfeerick** [comment]
I've thrown the question to Flysky to answer, so hopefully we'll get some clarification on that soon.

**Comment by philmoz** [comment]
Now I'm really confused.

After adding #3783 (which includes #3807) to my local build and rebuilding the EL18 with PCBREV=EL18 then switches SWB and SWD were swapped again.

I had to re-instate the changes in this PR to get them back to normal.

**Comment by philmoz** [comment]
And now I'm really really confused :(

When I powered the radio off and back on again SWB and SWD were swapped.

Then when I went to the SYSTEM - HARDWARE page they got fixed back to their correct assignments?????

**Comment by Delorean14** [comment]
Sorry for the newb question, but does all of this mean that we can select the NV14 if we have an EL18?  I am just getting into the hobby again and got an EL18 last week.  I'm loving it so far, but I'm confused by this thread.

**Comment by pfeerick** [comment]
So why are you here reading this thread? Sucker for punishment? 🤣 

But seriously, while around 2.7 and maybe even 2.8 you probably could have, I think now the EL18 firmware build is actually different to the NV14 firmware build. Even so, there is  a Flysky EL18 firmware target in EdgeTX buddy, as well as two different firmware files since at least 2.9.x. 

image

**Comment by Delorean14** [comment]
> So why are you here reading this thread? Sucker for punishment? 🤣

Hyuuuuuuuup.  ;)

> But seriously, while around 2.7 and maybe even 2.8 you probably could have, I think now the EL18 firmware build is actually different to the NV14 firmware build. Even so, there is a Flysky EL18 firmware target in EdgeTX buddy, as well as two different firmware files since at least 2.9.x.

I guess I was under the wrong impression that the companion could make setting up models a little easier at home in using the computer?  So absolutely everything model related has to be done on the radio's touch screen?  This is all making me feel extremely ignorant, so I apologize for it.

**Comment by pfeerick** [comment]
Ah, now that is a different matter entirely... You didn't mention anything
about Coloajion before :-P The EL18 will become a first class citizen in
Companion in 2.10 - in other words you'll be able to use Companion with the
EL18 soon ;)

**Comment by Delorean14** [comment]
That's great to hear, thank you VERY much for this information.  I was
actually getting a smidge worried there for a second.  I've already updated
the firmware to 2.9 so I'll patiently await 2.10.  Thanks again!

Respectfully,

*-Robb Smith-*
*Electrical Engineer*
*EMAC Incorporated*

**Pull request merged**
