### PR TITLE
chore: make WS2812 support an option

### PR DESCRIPTION
**Pull request by 3djc**
No user changes, just will make newer radio supporting ws2812 easier

### CODE REVIEW

**Comment by richardclli** [comment]
Umm..... this change not seems to conform to the standard of https://github.com/EdgeTX/edgetx/pull/5232, I think may need to rework.

**Comment by raphaelcoeffic** [comment]
> In what regard?

I think there are 2 aspects:
- #5232 moves hardware related things from `FIRMWARE_SRC` to the `board` / `board_bl` object libraries.
- `stm32_ws2812.cpp` is one of these new-style drivers that do not include any hardware definitions, and thus do not include `hal.h`. These drivers can be added unconditionally, as the linker will only include that code if the functions are actually called. In this particular case, this decided in `boards/generic_stm32/rgb_leds.cpp`, which will be compiled only if `LED_STRIP_GPIO` is defined in `hal.h`.

So, IMHO, this option is in fact useless, and could be removed, as the functionality is already provided by a combination of hardware definition in `hal.h` and conditional compilation of `rgb_leds.cpp`.

A CMake option could make sense if you want to disable support for these leds even if supported by hardware, but neither the present code nor this PR provides any of this.

**Comment by 3djc** [comment]
Well that suggest that #5232 should have cleaned that then

**Comment by raphaelcoeffic** [comment]
> Well that suggest that #5232 should have cleaned that then

Yes, you may be right, indeed.

**Pull request merged**
