### PR TITLE
Convert simu/simulator/companion to SDL2

### PR DESCRIPTION
**Pull request by gagarinlg**
Summary of changes:
simu, simulator and companion now use SDL2 instead of SDL 1.2

- [x]  the EdgeTX docker container needs an update
- [x] Github actions untested
- [x] OSX companion build is not adapted yet

### CODE REVIEW

**Comment by gagarinlg** [comment]
some help regarding the build system would be appreciated

**Comment by raphaelcoeffic** [comment]
> some help regarding the build system would be appreciated 

I have some patch to make use of the built-in cmake package as well, and will take care of the Linux container if you like.

**Comment by gagarinlg** [comment]
This would be nice, thx

**Comment by philmoz** [comment]
To fix the Windows build I had to remove line 29 (undef main) in both companion.cpp and simulator.cpp.

**Comment by gagarinlg** [comment]
Did you have to do anything to fix the SDL2 detection? Between the SDL2 version used on Ubuntu 20.02 and the version currently used by MinGW the cmake integration was changed.

**Comment by philmoz** [comment]
On MacOS I made the changes from your PR, deleted the build folder and re-ran the initial cmake command. It detected SDL2 and all built OK.

On Windows I manually installed SDL2 in an existing mingw setup - I did not re-run all the setup scripts. Again deleted the build folder and re-ran the setup cmake which detected SDL2. The companion build failed until I removed the '#undef main' lines.

**Comment by gagarinlg** [comment]
OK, thx

**Comment by pfeerick** [comment]
Windows build seems to be working perfectly - simulator sound and joystick (actually, I think it may have even fixed one of the joystick issues). WSL2 `simu` build sound also working still. LGTM!

@rotorman Heads up just in case this changes any wiki build documentation for you...

**Pull request merged**
