### PR TITLE
EL18 preliminary support

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Summary of changes:
- Support for new INRM301 (AFHDS3)
- Support for RX DMA on internal module
- Improved module API to include telemetry processing
- Fixed NV14 LCD driver to use direct double buffering (buffers from LVGL are used directly as frame buffers by the LTDC unit).
- MPM proto scan now uses RTOS timers to detect scan timeout rather than active state polling.

**Note well:**
- support for the external FRM302 module is killed by this PR. Please note that this module is more or less unsupported by FlySky (you cannot use the newer RX firmwares, supports only the old protocol version, etc).

### CODE REVIEW

**Comment by pfeerick** [comment]
So while this was initially EL18 I take it this also affects other radios due to module changes, etc... so is there anything specific you want me to test for this... At the moment I'm thinking kicking the tyres on the EL18, double checking MPM scanning on say TLite, TX16S, X9D+2019 (external), and that ELRS and internal RF on the X9Ds is still working properly?

**Comment by raphaelcoeffic** [comment]
@pfeerick apparently, there is an issue with ISRM and possibly other PXX2 modules, which I need to look into as well.

**Comment by pfeerick** [comment]
Ok, so accounting for the a0770beb5f8616e2f14f2828de12b3ff8b1f3397 issue (i.e. "D16 == ACCESS") my X9D+2019 also doesn't show version of the ISRM module now, whereas it does on the nightly. So another confirmation and test case for you.

**Comment by rburrow87** [comment]
That fixed it! I can now see the module version and register and bind a receiver on both my X12S ISRM and X9D+2019. But I get frequent telemetry lost/recovered warnings. Doesn't seem to be losing control link though, just telemetry.

**Comment by raphaelcoeffic** [comment]
@rburrow87 could you please retest when you get to it? It should work better now. I have here stable telemetry.

**Comment by pfeerick** [comment]
The only issue I've found after trying various combinatrions of TX16S, X9D+2019, NV14 and EL18 in conjunction with Tracer, ELRS, MPM, XJT and Ghost modules is that the NV14 is no longer talking to AFHDS2A receivers... (or even re-binding, it seems) - there seems to be some UI weirdness where a receiver ID field is made visible when the module is turned off and on again. It also seems that the CAT01 (altitude, pressure) sensor telemetry values are buggered up on the AFHDS3 EL18 (but that is a minor (non-blocking) issue as far as I'm concerned).

**Comment by raphaelcoeffic** [comment]
@pfeerick blocking issue should be fixed now. I haven't touched the CAT01 sensor, as you said it's not blocking (yet?).

**Comment by pfeerick** [comment]
RF power also 🙃 

i.e. NV14, again, just toggling on, off and on again... (as you naturally wouldn't) - I only caught it before because of the "if it don't work, have you tried turning it off an on again" mantra ;)

image

**Comment by pfeerick** [comment]
btw, NV14 RF is working again, so yup, now just the usual bug thwacking as we play with it further. Clobber that last regression and merge so we can move onto the next PR ;)

**Comment by JyeSmith** [comment]
TX16s Version 68511233 31-7-2022

Firstly, the TLM lost warnings are now gone.  Nicely done.!

ELRS passthrough fails and causes the handset to lock up.  Rebooting starts the handset back up in Emergency mode.  Another reboot boots normally.

The boot image is also not displaying colours correctly.  Image below.

image

**Comment by pfeerick** [comment]
@raphaelcoeffic Actually, regarding https://github.com/EdgeTX/edgetx/pull/2100#issuecomment-1209284458, this is also present in 2.7.1 so is a "not related to this PR issue". 

@JyeSmith I can repo that the passthrough crash with the current (a42c3f7) state of this branch. Nightly is fine (on the same radio). I'm not seeing the splash image color corruption (nice to see the ol' testcard again btw!) though... so that could be image specific or something unrelated to this PR that changed in `main`.

**Comment by JyeSmith** [comment]
@pfeerick when I get a chance I'll reflash this PR and also main to check.

**Comment by raphaelcoeffic** [comment]
@pfeerick @JyeSmith passthrough should be fine again. Would you mind to retest please? 🤓 (*disclaimer: I did not try to retest the other passthrough candidates, only TX16S*)

**Comment by pfeerick** [comment]
ELRS passthrough update was successful RM TX16S, TX12, Zorro with 28d80a6. 

Jumper T-Lite V2 failed with 28d80a6, but worked with nightly 2c455e06. 
Jumper T-Pro also failed, but something seems to be wrong with it as it's not updating on 2.7.1 either - so have to double check the passthrough mod is still working.

**Comment by pfeerick** [comment]
Right, so it looks like #1089 inadvertantly clobbered a define for the T-Pro enabling passthrough... 77d51eb brings that back in, and when applied to `main` passthrough is working again, but not when part of this PR... so it looks like neither of the Jumpers are happy.

**Comment by JyeSmith** [comment]
Flashed 77d51eb.

- Boot image is still corrupt.
- ELRS passthrough works.
- Packet errors for internal is 0
- Packet errors for external at 1kHz is about 1000 after boot, but doesn't increase.

**Comment by pfeerick** [comment]
Can you also try a nightly build to pin down if the image issue is related to this PR or not.

I found this one, and it's showing up fine on mine. 

splash

**Comment by JyeSmith** [comment]
Thats weird, your image works with the nightly.  Heres mine if you wanted to try it.

splash_Jyes

**Comment by pfeerick** [comment]
Thanks for that. Righty-o, I can reproduce that with both nightly and PR, but not with 2.7.1... so it's a regression somewhere, but not due to this PR. So it looks like I may have some bisect fun on the agenda tomorrow... 

Having said that, it *is* something about the image - as I litterally just opened it, and saved it using Paint.NET, and not only did it shrink by about 10k, but the colour is right now on the TX... go figure!?

splash

**Comment by raphaelcoeffic** [comment]
@pfeerick I just disabled the RX DMA on T-lite & T-pro, as it displays strange behaviour on passthrough flashing...

Here is a capture where bytes received from the module during passthrough flashing are mirrored to S.PORT (ext. module) so I can see them before sending to USB CDC.

*Green trace is coming from the module / Blue trace is what is sent back over passthrough*

Screenshot 2022-08-11 at 11 51 14
Screenshot 2022-08-11 at 11 52 24

This only happens with RX DMA, not with IRQ based RX. Please note that there is no way the buffer can be messed with as it is declared `static` in the driver, and nothing can access it (apart from random memory access, of course).

**Comment by raphaelcoeffic** [comment]
> Packet errors for external at 1kHz is about 1000 after boot, but doesn't increase.

@JyeSmith Please note that none of the radios (except for the X12S) is able to use RX DMA on S.PORT pin, as the DMA Stream is already taken by either SDIO (colorlcd target) or audio DAC (taranis-like targets). Also note what I just wrote above about RX DMA on T-lite / T-pro (to be further evaluated in another PR / another time).

**Comment by JyeSmith** [comment]
Yep, I just added that point for completeness when testing.

**Comment by raphaelcoeffic** [comment]
Regarding the boot image thing, just consider a couple things:
- we use a lib to load these pictures,
- the version is not the same in 2.7.1 and now,
- it is a pretty basic lib, which main advantage is low footprint, not max compatibility.

We need to draw a line somewhere ;-) Faced with a tradeoff like that, I'll take the small footprint anytime.

**Review by pfeerick — APPROVED** [review]
All tested hardware is good so far.

**Pull request merged**
