### PR TITLE
[color] fixed MPM options (esp. DSM related)

### LINKED ISSUE #458: DSM Channel order
Some issues were listed but not directly related. Comments on the forums are there but no results.

Binding DSM receivers results in sometimes binding but in the wrong channel order. Aileron is the elevator, the rudder seems always OK but the motor either works or doesn't. Even when it does bind, when you turn it back on it goes nuts again. Hit or miss. Seems to be only the receivers with AS3x

There is nothing wrong with the receivers as it will bind with my Spectrum transmitters instantly and works correctly. These were all working with Open TX. 

Using Edge TX 2.4 RC4
All DSM receivers. Transmitter Radiomaster DX16S. Planes with receivers built-in include UMX Timber, UMX Carbon Cub SS. Spectrum AR635 used in a Parkzone Visionaire.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Resolves #458 and possibly other related MPM issues.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Please note that the DSM subtype "Auto" is not supported yet. You will need to choose the proper subtype for your receiver.

**Comment by pfeerick** [comment]
I'll see if I can squeeze in a look at it. So I guess `DSMR` isn't there either? 😆

**Comment by raphaelcoeffic** [comment]
> I'll see if I can squeeze in a look at it. So I guess `DSMR` isn't there either? 😆 It's fairly new to MPM, and is for the land based stuff, so I doubt anyone will notice it there or not yet.

What is this??? Yet another attempt at getting rid of cloners?

**Comment by pfeerick** [comment]
More like "how can we sell another product line based on the same technology" ... has it's own line of transmitters (the car steering wheel sort) and corresponding receivers... think they all have extended antenna, and come in 2, 3, 4 and 6 channel variants.

**Comment by raphaelcoeffic** [comment]
> More like "how can we sell another product line based on the same technology" ... has it's own line of transmitters (the car steering wheel sort) and corresponding receivers... think they all have extended antenna, and come in 2, 3, 4 and 6 channel variants.

Market segmentation, I see. I think what it takes is to have real support for all the dynamic fancy stuff the MPM is having now. For example, it tells you in real time which protos it supports, and lots of other things. This should solve the order as well, and quite some other things.

**Comment by pfeerick** [comment]
I haven't not been able to detect any issues with either DSM2 or DSMX, and all the options I can readily test (remapping, ch throw) are working perfectly / as expected. I can't *properly* test disable telem, servo rate or low power, but enabling them doesn't appear to break anything, and disable telem does say no module telem, so appears to be working. As far as the no throttle issue I was having with DSM2, I think I managed to find a receiver with a dead throttle channel, as my other DSM2 receivers are working fine.

**Pull request merged**
