### PR TITLE
fix(ui) - Convert theme save and delete dialogs to use ConfirmDialog popup.

### PR DESCRIPTION
**Pull request by philmoz**
Use the popup dialog instead of the full screen alert page.
Add strings for translation.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Hi translators,

@ParkerEde / @TheIsotopes DE
@Eldenroot CZ
@ulfhedlund SE
@robustini IT
@zyren CN / TW
@ajjjjjjjj PL
@ToshihiroMakuuchi JP

Please, add your translations. Thank you!

**Comment by ajjjjjjjj** [comment]
PL
```
#define TR_DELETE_THEME                "Usunąć motyw?"
#define TR_SAVE_THEME                  "Zapisać motyw?"
```

**Comment by ParkerEde** [comment]
DE
#define TR_DELETE_THEME                "Theme löschen?"
#define TR_SAVE_THEME                  "Theme speichern?"

**Comment by robustini** [comment]
IT
#define TR_DELETE_THEME                "Cancello Tema?"
#define TR_SAVE_THEME                  "Salvo Tema?"

**Comment by ulfhedlund** [comment]
SE
#define TR_DELETE_THEME "Radera tema?"
#define TR_SAVE_THEME "Spara tema?"

**Comment by ToshihiroMakuuchi** [comment]
JP
#define TR_DELETE_THEME "テーマを削除しますか？"
#define TR_SAVE_THEME "テーマを保存しますか？"

**Comment by HThuren** [comment]
don't forget danish :-)

DA
#define TR_DELETE_THEME "Slet tema?"
#define TR_SAVE_THEME "Gem tema?"

**Comment by HThuren** [comment]
> don't forget danish :-)
> 
> DA #define TR_DELETE_THEME "Slet tema?" #define TR_SAVE_THEME "Gem tema?"

Thank you :-)

**Comment by pfeerick** [comment]
Confirm dialog is good... but am I missing something... unless I select YES there is no way to leave the theme edit screen?

**Comment by philmoz** [comment]
> Confirm dialog is good... but am I missing something... unless I select YES there is no way to leave the theme edit screen now?

Hmmm. When I select No it closes the dialog and exits the edit screen?

**Comment by philmoz** [comment]
The RTN button would exit the dialog without calling the 'cancelHandler' from the theme editor - were you using this?
I've pushed a change to fix it.

Not sure about the crashing - have not seen this in the simulator.

**Comment by pfeerick** [comment]
I think I may have narrowed the EM trigger (on radio) to being somewhat related editing the 'active' theme so will have to try and pin down a reproducable scenario and hope either simu will do it also or set the debugger up again. 

This was on-screen buttons only - RTN behaved the same. 

https://user-images.githubusercontent.com/5500713/215068031-c730dda8-702d-4b70-8097-e1fdfd07c86b.mp4

**Comment by pfeerick** [comment]
Now pressing RTN at the confirm prompt gets me out back to the themes list, but via the touchscreen No it still stays at the edit theme page.

**Comment by philmoz** [comment]
Ok, I get the problem if I flash it to my radio; but it works fine in the Companion simulator ???

**Comment by pfeerick** [comment]
Ouch... so both `simu` and radio show it, but not the fully simulator? 😭

**Comment by philmoz** [comment]
Simu on MacOS works ok - does not show the problem. Bizarre!

**Comment by ParkerEde** [comment]
I use the standalone simulator under Windows and can confirm it. If I make a change and want to close without saving, I remain in the edit screen. It doesn't matter whether I use the standalone simulator or the simulator run from Companion.

**Comment by philmoz** [comment]
If I revert to the full screen dialog then it works as expected on my radio.

Testing just now I got the lockup on the radio after using the theme editor and then it rebooted into EM after pulling the battery.

Looks like there are a few issues with all this - I will be away for a few days and will look into it next week.

**Comment by pfeerick** [comment]
Yes, the theme editor has had more than its share of issues... but slowly getting there. I'll leave this on hold then until we can dig a little deeper.

**Comment by philmoz** [comment]
Had a thought early this morning so one more change to try.
This now works on my TX16S.

**Comment by philmoz** [comment]
So far no more crashes on my TX16S in the theme editor (touch wood). This last change may have helped here as well.

**Comment by pfeerick** [comment]
Agreed... it seems to be back to normal - can exit the theme editor when choosing no or yes via touch or hard key. No lockup on save or poweroff. I was able to make the TX16S EM again when saving a change to the active theme. However, I was also able to get it to EM when changing from the custom theme to the default theme... so I suspect the issue is specific to reading/writing/applying the theme settings, not this PR. Since the theme editor is actually "pre yaml", it has its own yaml writing implementation, rather than using the ... system version? ... so that could be where the issue is.

**Comment by zyren** [comment]
*****************************************************
CN
#define TR_DELETE_THEME         "删除主题?"
#define TR_SAVE_THEME           "保存主题?"
*****************************************************
*****************************************************
TW
#define TR_DELETE_THEME         "刪除主題?"
#define TR_SAVE_THEME           "保存主題?"

**Pull request merged**
