### PR TITLE
feat(cpn): Initial RM Boxer support

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
- Implements Companion support for Radiomaster Boxer
- ~~Simulator is *not* implemented yet (pending graphics)~~

Boxer has survived initial sync with Companion with settings seemingly unscathed, but more testing is underway. 

Rebased after #2685 changes

### CODE REVIEW

**Comment by pfeerick** [comment]
@elecpower Ok, I think I must have done something stupidly simple in the simulator to make it only half work... the SYS and ENT button click zones on the right side are working, but not the left... any ideas before I look at it with fresh eyes in the morning, and start ripping hair out 🤣

**Comment by elecpower** [comment]
@pfeerick what do you expect on NYE. I'll have a look

**Comment by elecpower** [comment]
@pfeerick you owe me a slab for finding why the left side buttons didn't click. Talk about making the diagnosis difficult ;-)

**Comment by pfeerick** [comment]
So true... Was probably not be the best time to be working on it... and lol I said it would be stupidly simple... so it helps if you enable it (and put the buttons in the right order)? 🤣

**Comment by elecpower** [comment]
Too right it does

**Comment by 3djc** [comment]
Let me know if I can help with this guys :)

**Pull request merged**
