### PR TITLE
fix(color): Fix for slider control blocking RTN key.

### LINKED ISSUE #3943: Colorlcd on screen sliders causing RTN key issues
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Sliders are causing issue depending on their focus state. Best example is RADIO SETUP variometer page. RTN key is non functional when you open the page

### Expected Behavior

RTN  keys functionnal

### Steps To Reproduce

SYS / RADIO SETUP/ Variometer, push RTN key

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3943

### CODE REVIEW

**Comment by 3djc** [comment]
Tested ok on simu and radio :)

**Comment by ParkerEde** [comment]
yes RTN is okay now. 
But try to change the volume? For me it doesn't work.
- Open vario
- Press Enter
- Scroll with encoder
- mark jumps over other input field but doesn't change the volume
Importent for non touch color radios I think

**Comment by 3djc** [comment]
Yes, on tx16s as well, you cannot change value with rotenc

**Comment by philmoz** [comment]
> Yes, RTN is fixed, but on tx16s as well, you cannot change value with rotenc (working with touch)

Should be fixed now.

**Comment by pfeerick** [comment]
Fix for both issues is working for me, TX16S

**Pull request merged**
